### ISSUE TITLE
好多页面打不开 404 

### ISSUE THREAD

**Issue by ywcr** [antvis/G2Plot#1002]
https://g2plot.antv.vision/zh/examples/examples/general/axis

**Comment by Luoxcat** [comment]
https://g2plot.antv.vision/zh/examples/general/axis

**Comment by ywcr** [comment]
https://g2plot.antv.vision/zh/docs/manual/advanced/overlapped-combo-plot/#yaxis  地址中的通用图表配置 跳转 都是404

**Comment by paleface001** [comment]
应该是过期地址还没有清理掉，近期我们会更新一下网站

**Comment by hustcc** [comment]
v2 新版本 和 文档正在开发中。
