### ISSUE TITLE
yAxis => label => style 设置 textAlign ：left 问题

### ISSUE THREAD

**Issue by ywcr** [antvis/G2Plot#1003]
![1588056595666](https://user-images.githubusercontent.com/8427087/80456209-c77d5680-895f-11ea-9977-f10a5684b8cf.jpg)

设置 textAlign left 样式后 出现了 label 没有宽度的问题，style 设置 width 不生效

![1588056769322](https://user-images.githubusercontent.com/8427087/80456368-0c08f200-8960-11ea-8e7c-6f78ca681e7c.jpg)

![1588056795040](https://user-images.githubusercontent.com/8427087/80456357-08756b00-8960-11ea-85a4-cb85baafda49.jpg)

**Comment by paleface001** [comment]
width这个配置项在label里不支持

**Comment by ywcr** [comment]
style 不是用来设置样式吗  ？ 
有什么方法可以设置label为固定宽度呢
textAlign:left; 为什么label的宽度没有了呢

**Comment by paleface001** [comment]
axis.label.style支持的样式参考：https://g2plot.antv.vision/zh/docs/manual/graphic-style#%E9%85%8D%E7%BD%AE%E6%96%87%E5%AD%97%E6%A0%B7%E5%BC%8F
label不是类似dom那样的容器，而是一组绘制在canvas上的文字(姑且这么理解)，文本的长度不固定，所以宽度对于label是没有意义的

**Comment by paleface001** [comment]
还有axis.label.position也是不支持的，建议多阅读一下文档

**Comment by ywcr** [comment]
了解，这个看到了不支持，复制过来的。
那label过长的情况下，右侧图标被挤的剩一点了 没办法处理吗

**Comment by paleface001** [comment]
这样的话可以对axis.label进行格式化处理
```
yAxis:{
  label:{
    formatter:(text)=>{
       return '...'; //这里写入你自己的文本简化逻辑
    }
  }
}
```

**Comment by ywcr** [comment]
ok
非常感谢
