### ISSUE TITLE
OverlappedComboPlot x，y轴都显示 null

### ISSUE THREAD

**Issue by cnprinces** [antvis/G2Plot#1009]
1.OverlappedComboPlot x，y轴都显示 null

2. 如果 type是 Area 的话 没有获取到默认的color 需要单独指定，line的是有的。

3.帮组文档中没有地方说明怎么调用事件，以及各个事件的入参。昨天找了一天才找到怎么调用事件。。

> 
   layers: [

            {
              title: {
                alignTo: 'left',
                visible: true,
                text: '资产走势图',
              },
              type: 'Area',
              name: '当前值',
              data: this.data,
              xField: 'DATA_DATE',
              yField: 'TTL_AMT',
              color:["#5B8FF9"],
              label: {
                visible: true,
              },
              meta: {
                TTL_AMT: {
                  alias:'当前值'
                },
                DATA_DATE: {
                  alias: '确认日期'
                }
              },
              areaStyle: {
                fill: 'l(90) 0:#5B8FF9 1:#ffffff',
              }
            },
            {
              type: 'line',
              name: '目标值',
              data: this.data,
              xField: 'DATA_DATE',
              yField: 'TAR_ASSET',
              color: '#f8ca45',
              lineSize: 2,
              meta: {
                TAR_ASSET: {
                  alias:'目标值'
                },
                DATA_DATE: {
                  alias: '确认日期'
                }
              },

            },
          ]`

**Comment by paleface001** [comment]
可以尝试使用1.1.2的正式版双轴图
