### ISSUE TITLE
能否提供筛选legend和tooltip的filter筛选属性？

### ISSUE THREAD

**Issue by RuanXuSong** [antvis/G2Plot#1014]
在一些需要填充假数据才能展现的图表中(比如单例环形图)为了展示效果，需要自己计算出另一半的数值并用环形图展示，以达到效果。如图：
![image](https://user-images.githubusercontent.com/39564114/81135823-3411da00-8f8c-11ea-86e7-aedee309aca5.png)
但是，在实际上，图例里的“空”是不用展示的，这个时候用最新beta版本中的legend-text-formatter属性进行筛选可以达到以下效果：
![image](https://user-images.githubusercontent.com/39564114/81136057-ffeae900-8f8c-11ea-9440-a1f3761e8cbc.png)
但这样还是不满足最终的要求，有没有什么办法可以让被筛选的图例完全隐藏？
同理还有toolTip，“空”的ToolTip也是不需要的，如图：
![image](https://user-images.githubusercontent.com/39564114/81136035-f3669080-8f8c-11ea-861a-96492e5a5f65.png)
用最新beta版的配置最多可实现这样的效果：
![image](https://user-images.githubusercontent.com/39564114/81136095-214bd500-8f8d-11ea-8f17-44b9c1d5b6d3.png)
但是这也不是我们想要的，有没有办法让被筛选的toolTip完全隐藏？

假数据填充实现效果的地方还有很多，希望能尽快给出回复，谢谢！

**Comment by paleface001** [comment]
目前G2Plot还没有开放图例隐藏，tooltip的话可以参考[这个示例](https://g2plot.antv.vision/zh/examples/general/tooltip#tooltip-statistic-value)，修改ev.items

**Comment by RuanXuSong** [comment]
> 目前G2Plot还没有开放图例隐藏，tooltip的话可以参考[这个示例](https://g2plot.antv.vision/zh/examples/general/tooltip#tooltip-statistic-value)，修改ev.items

好吧，希望后续能开放吧
