### ISSUE TITLE
g2plot ie下面不显示，报错相关为g2plot的依赖d3-regression

### ISSUE THREAD

**Issue by JasonSubMara** [antvis/G2Plot#1023]
问题描述： IE浏览器下图表未正常显示，控制台报错信息如下
![image](https://user-images.githubusercontent.com/30927318/81251117-22e0d000-9055-11ea-9a65-81894d4e669f.png)
![image](https://user-images.githubusercontent.com/30927318/81251126-27a58400-9055-11ea-9562-d4c387190a7c.png)

----- 后通过AntV下G6的解决方式类比安装babel-polyfill，
![image](https://user-images.githubusercontent.com/30927318/81251141-31c78280-9055-11ea-90a7-3eb69ef3528c.png)

----- IE下仍旧报错，进一步搜索，找到对应的代码片段，希望得到解决。

![image](https://user-images.githubusercontent.com/30927318/81251165-3b50ea80-9055-11ea-8942-f3f070d072b7.png)

**Comment by paleface001** [comment]
IE版本号是多少？

**Comment by JasonSubMara** [comment]
版本号：11.778.18362.0

**Comment by w675179089** [comment]
您好 请问解决了嘛 我也是参考G6兼容ie文档 在include加了和您一样的 还是不行

**Comment by zqlu** [comment]
@w675179089 include 里面先临时添加 d3-regression 试下？
`include: [resolve(config.src), resolve('@antv/g2plot'), resolve('d3-regression')]`

**Comment by w675179089** [comment]
还是不行 是不是还有别的依赖没有处理呢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"zqlu"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月14日(星期四) 上午10:09
收件人:&nbsp;"antvis/G2Plot"<G2Plot@noreply.github.com&gt;;
抄送:&nbsp;"长相守’’’"<675179089@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [antvis/G2Plot] g2plot ie下面不显示，报错相关为g2plot的依赖d3-regression (#1023)





 
@w675179089 include 里面先临时添加 d3-regression 试下？
 include: [resolve(config.src), resolve('@antv/g2plot'), resolve('d3-regression')]

**Comment by zqlu** [comment]
配置下 webpack，使用 `d3-regression` 的 dist 文件，在 vue 下配置`vue.config.js`:

```js
module.exports = {
  configureWebpack: {
    resolve: {
      alias: {
        "d3-regression": "d3-regression/dist/d3-regression.js"
      }
    }
  }
};
```

@w675179089

**Comment by w675179089** [comment]
我用的 vue-cli 是2.x版本
![image](https://user-images.githubusercontent.com/26165417/81889397-fccbaa80-95d5-11ea-8d27-97b4cbcf6a9f.png)


您说的 vue.config.js 是3+以上的版本吧
如果是2.x 要怎么配置呢

@zqlu

**Comment by zqlu** [comment]
> 我用的 vue-cli 是2.x版本
> ![image](https://user-images.githubusercontent.com/26165417/81889397-fccbaa80-95d5-11ea-8d27-97b4cbcf6a9f.png)
> 
> 您说的 vue.config.js 是3+以上的版本吧
> 如果是2.x 要怎么配置呢
> 
> @zqlu

看你截图都有 webpack 配置文件，那直接在 webpack 中配置就好了 https://webpack.js.org/configuration/resolve/#resolvealias， vue 旧版本的文档需要你自己查下

**Comment by w675179089** [comment]
我用的 vue-cli 是2.x版本&nbsp;



您说的 vue.config.js 是3+以上的版本吧
如果是2.x 要怎么配置呢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"zqlu"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月14日(星期四) 中午11:22
收件人:&nbsp;"antvis/G2Plot"<G2Plot@noreply.github.com&gt;;
抄送:&nbsp;"长相守’’’"<675179089@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [antvis/G2Plot] g2plot ie下面不显示，报错相关为g2plot的依赖d3-regression (#1023)





 
配置下 webpack，使用 d3-regression 的 dist 文件，在 vue 下配置vue.config.js:
 module.exports = {   configureWebpack: {     resolve: {       alias: {         "d3-regression": "d3-regression/dist/d3-regression.js"       }     }   } };
 
@w675179089

**Comment by w675179089** [comment]
您好 请问如果不配置的话 用的是d3-regression哪个js  我直接在module里把d3-regression/dist/d3-regression.js 对应替换过去可否呢

@zqlu

**Comment by w675179089** [comment]
您好 请问如果不配置的话 用的是d3-regression哪个js&nbsp; 我直接在module里把d3-regression/dist/d3-regression.js 对应替换过去可否呢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"zqlu"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月14日(星期四) 中午11:22
收件人:&nbsp;"antvis/G2Plot"<G2Plot@noreply.github.com&gt;;
抄送:&nbsp;"长相守’’’"<675179089@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [antvis/G2Plot] g2plot ie下面不显示，报错相关为g2plot的依赖d3-regression (#1023)





 
配置下 webpack，使用 d3-regression 的 dist 文件，在 vue 下配置vue.config.js:
 module.exports = {   configureWebpack: {     resolve: {       alias: {         "d3-regression": "d3-regression/dist/d3-regression.js"       }     }   } };
 
@w675179089

**Comment by w675179089** [comment]
已解决 vue-cli2.x版本如果出现g2plot白屏报错不显示页面 除了正常配置babel-ployill 贴一下图:
![image](https://user-images.githubusercontent.com/26165417/81916658-ab87df00-9606-11ea-8d9e-61dd15150859.png)

@zqlu  不知道官方能否直接把这个d3依赖转了呢

**Comment by JasonSubMara** [comment]
> 已解决 vue-cli2.x版本如果出现g2plot白屏报错不显示页面 除了正常配置babel-ployill 贴一下图:
> ![image](https://user-images.githubusercontent.com/26165417/81916658-ab87df00-9606-11ea-8d9e-61dd15150859.png)
> 
> @zqlu 不知道官方能否直接把这个d3依赖转了呢

刚好今天看到你的解决方案，现在我在ie下面也可以显示正常的图表了，因为是vue项目，所以用了这个，另外如果静态页面script引入g2plot的方式做图表的话，依旧有问题，可以尝试把g2plot代码下载到本地，修改下配置，自行打包。

**Comment by JasonSubMara** [comment]
虽然解决了，但是应该是由于依赖了d3,国外的开发者没有较好的考虑ie的兼容性，应该是个bug，希望官方大大能在下一版本解决 😭 @zqlu @paleface001

**Comment by zqlu** [comment]
> 虽然解决了，但是应该是由于依赖了d3,国外的开发者没有较好的考虑ie的兼容性，应该是个bug，希望官方大大能在下一版本解决 😭 @zqlu @paleface001

我这边尝试去上游修复

**Comment by chiaweilee** [comment]
> > 已解决 vue-cli2.x版本如果出现g2plot白屏报错不显示页面 除了正常配置babel-ployill 贴一下图:
> > ![image](https://user-images.githubusercontent.com/26165417/81916658-ab87df00-9606-11ea-8d9e-61dd15150859.png)
> > @zqlu 不知道官方能否直接把这个d3依赖转了呢
> 
> 刚好今天看到你的解决方案，现在我在ie下面也可以显示正常的图表了，因为是vue项目，所以用了这个，另外如果静态页面script引入g2plot的方式做图表的话，依旧有问题，可以尝试把g2plot代码下载到本地，修改下配置，自行打包。

用 alias 就可以了，不需要 resolve

**Comment by GodYX** [comment]
https://github.com/chiaweilee，麻烦各位解决了问题的大佬们分享下具体方法呢，或者上传一个ie可用的简单项目呢，git上的图片都看不到这些信息的参考性就不是很大了,从头开始定位问题比较复杂，谢谢大家
