### ISSUE TITLE
水波图设置字体颜色无效

### ISSUE THREAD

**Issue by Dreamvsforward** [antvis/G2Plot#1024]
const liquidPlot = new Liquid(document.getElementById("containerChart"), {
        min: 0,
        max: 10000,
        value: 5639,
        statistic: {
          style:{
            fill: '#FFF'
          },
          formatter: value => ((100 * value) / 10000).toFixed(1) + "%"
        }
      });
      liquidPlot.render();

**Comment by Dreamvsforward** [comment]
水波图设置字体颜色无效

**Comment by hustcc** [comment]
V2 修复，目前已经在 pr 中。
