### ISSUE TITLE
希望tooltip.formatter可以更加灵活

### ISSUE THREAD

**Issue by 18601673727** [antvis/G2Plot#1027]
比如我有如下配置：
```es6
formatter: (_label, value, name) => {
   return { name, value: value }
}
```
需要给每一个value拼接字符串，例如“¥1000.00元”:
```es6
formatter: (_label, value, name) => {
   return { name, value: "¥" + value + "元" }
}
```
报错，因为value的值被限定为`number`，所以我想建议修改返回值的签名为类似下面这样：
```ts
{ name: string; value: number; prepend?: string; append?: string; }
```
相比customContent就会方便很多，小小建议还望官方考虑一下，谢谢！

**Comment by paleface001** [comment]
非常有心的建议，多谢~

**Comment by OuyangQianba** [comment]
我认为，formatter 对每个字段调用一次更好些。现在的formatter的实现是把Tooltip用到的那些字段的值做为函数参数传给formatter的，这样用户就不能做到对每个字段进行格式化。
例如下图中Tooltip显示了三个字段：
![image](https://user-images.githubusercontent.com/17270099/81709567-8aa77880-94a4-11ea-8ce9-32e1e8f5c181.png)
这里用scale的formatter来做的格式化，但就无法格式化name了（图中earlEndDate)。

---

这个formatter 的实现是在有这里吧？
https://github.com/antvis/G2/blob/master/src/util/tooltip.ts#L337-L350
建议改为这类似这样：
```
      for(const field of fields) {
        const {name,value} = callback(field,data[FIELD_ORIGIN][field])
        addItem(name,value)
      }
```

**Comment by hustcc** [comment]
v1 暂不进行迭代。

目前在 v2 中，tooltip 的能力，通过 customContent 可以实现复杂能力，包括 tooltip 浮层上的下钻筛选按钮，但是确实对于上述相对简单的场景来说，易用性上差了一些。

后面我们会专门提供如何做一个复杂的自定义 tooltip demo。

**Comment by hustcc** [comment]
https://github.com/antvis/G2Plot/pull/1730

等待发布版本。
