### ISSUE TITLE
请完善下双折线混合图表的相关api文档，很多配置项和单折线图不一样

### ISSUE THREAD

**Issue by xjx530** [antvis/G2Plot#1030]
例如在双折线图设置meta的alias属性不生效
![image](https://user-images.githubusercontent.com/22742008/81381513-6ca5e500-913f-11ea-9270-e04b317aa1a7.png)

**Comment by paleface001** [comment]
meta是生效的，可以看一下tooltip的情况。不过因为legend是定制的，没有考虑meta的配置，这应该是个bug
