### ISSUE TITLE
分组条形图 每一组只有一条数据时出现问题

### ISSUE THREAD

**Issue by ywcr** [antvis/G2Plot#1031]
第一条数据的tooltip 展示没问题 后面几条展示有问题

可以用下面配置尝试

`
import { GroupedBar } from '@antv/g2plot';

const data = [
  { label: 'Mon.', type: 'series1', value: 2800 },
  { label: 'Tues.', type: 'series2', value: 1800 },
  { label: 'Wed.', type: 'series3', value: 950 },
  { label: 'Thur.', type: 'series4', value: 500 },
  { label: 'Fri.', type: 'series5', value: 170 },
];

const barPlot = new GroupedBar(document.getElementById('container'), {
  title: {
    visible: true,
    text: '分组条形图',
  },
  data,
  xField: 'value',
  yField: 'label',
  groupField: 'type',
  label: {
    formatter: (v) => `${v}`.replace(/\d{1,3}(?=(\d{3})+$)/g, (s) => `${s},`),
  },
});

barPlot.render();
`

**Comment by ywcr** [comment]
摩西摩西

**Comment by ywcr** [comment]
鼠标放在条形图上面会报错 Uncaught TypeError: Cannot read property 'name' of undefined

**Comment by paleface001** [comment]
你这个数据用分组条形图没有意义，因为每个组只有一根柱子

**Comment by ywcr** [comment]
> 你这个数据用分组条形图没有意义，因为每个组只有一根柱子

g2 就可以 封装起来的不行

**Comment by ywcr** [comment]
我这样用是想每一条不同颜色，单个条形图好像没办法设置

**Comment by paleface001** [comment]
```
colorField:'', // 参与颜色映射字段
colors:[] // 指定映射颜色
```

**Comment by ywcr** [comment]
条形图可以固定高度吗

**Comment by paleface001** [comment]
配置barSize就可以固定了

**Comment by ywcr** [comment]
好的 谢谢

**Comment by paleface001** [comment]
客气了
