### ISSUE TITLE
双轴图图例更细粒度的配置

### ISSUE THREAD

**Issue by paleface001** [antvis/G2Plot#1034]
目前双轴图图例的可控度距离常规图表差距比较大

- [ ] formatter

- [ ] title

- [ ] offsetX

- [ ] offsetY

**Comment by xiecg** [comment]
发现在 1.1.0 版本中 OverlappedComboPlot 已被删除了，请问目前的版本可以做到折线图和面积图做搭配吗? @paleface001

**Comment by paleface001** [comment]
不支持，因为目前没有看到这种搭配在统计上的意义，双折线即可

**Comment by Jackeriss** [comment]
@paleface001 是 DualLine 替代了 OverlappedComboPlot 吗？如果是的话建议将官方文档和示例中的 OverlappedComboPlot 删除。

**Comment by hustcc** [comment]
这个 issue 先关闭了哈。目前直接透传 G2 的 custom legend 配置。
