### ISSUE TITLE
使用中发现几个问题，希望官方看看

### ISSUE THREAD

**Issue by maihuochai** [antvis/G2Plot#1035]
最近从echarts转到G2Plot，G2Plot的配置方式和对TS的支持的确是让我很是喜欢，以至于发现有些不能满足功能仍然不想换回echarts。

其中发现几个问题，希望官方能够看看：

1. 可能是bug也可能是官方文档没有描述清楚
水波图中心文本设置颜色、水波渐变无效
详细看我提的另一个[Issues](https://github.com/antvis/G2Plot/issues/1022)

2.文档对刚使用的人来说非常不友好
很多地方的描述太模糊，对于初用者来说如果不翻阅大量文档根本不理解其中意思，比如折线图中的label选项：
![image](https://user-images.githubusercontent.com/28753640/81463211-4be69980-91ea-11ea-98f0-c783c708a340.png)

3.文档描述不全
还是对于开发者友好度问题，目前在使用过程中发现有些文档有缺失部分比如折线图中的title：
![image](https://user-images.githubusercontent.com/28753640/81463163-f7431e80-91e9-11ea-9382-f6379663df41.png)
看了.d文件，应该是left、middle、right

虽然提了几个小问题，但是也事关体验，希望官方考改进
最后：希望Antv系列产品越来越好

**Comment by paleface001** [comment]
非常感谢你的建议，网站文档我们会下周集中更新一波
所有的样式配置都可以在绘图属性中找到：https://g2plot.antv.vision/zh/docs/manual/graphic-style，不过在对应的位置没有注明，对用户的确不友好。
