### ISSUE TITLE
vue项目中运行和打包报错

### ISSUE THREAD

**Issue by maihuochai** [antvis/G2Plot#1039]
在vue项目中运行和打包均出现如下错误：
`ERROR in D:/workspace/smallwater_vue_ts_jest/node_modules/@antv/matrix-util/lib/mat3.d.ts(1,23):
1:23 Could not find a declaration file for module '@antv/gl-matrix/lib/gl-matrix/mat3'. 'D:/workspace/smallwater_vue_ts_jest/node_modules/@antv/gl-matrix/lib/gl-matrix/mat3.js' implicitly has an 'any' ty
pe.
  Try `npm install @types/antv__gl-matrix` if it exists or add a new declaration (.d.ts) file containing `declare module '@antv/gl-matrix/lib/gl-matrix/mat3';`
  > 1 | import * as mat3 from '@antv/gl-matrix/lib/gl-matrix/mat3';
      |                       ^
    2 | export default mat3;
    3 | 
ERROR in D:/workspace/smallwater_vue_ts_jest/node_modules/@antv/matrix-util/lib/vec2.d.ts(1,23):
1:23 Could not find a declaration file for module '@antv/gl-matrix/lib/gl-matrix/vec2'. 'D:/workspace/smallwater_vue_ts_jest/node_modules/@antv/gl-matrix/lib/gl-matrix/vec2.js' implicitly has an 'any' ty
pe.
  Try `npm install @types/antv__gl-matrix` if it exists or add a new declaration (.d.ts) file containing `declare module '@antv/gl-matrix/lib/gl-matrix/vec2';`
  > 1 | import * as vec2 from '@antv/gl-matrix/lib/gl-matrix/vec2';
      |                       ^
    2 | export default vec2;
    3 | 
ERROR in D:/workspace/smallwater_vue_ts_jest/node_modules/@antv/matrix-util/lib/vec3.d.ts(2,23):
2:23 Could not find a declaration file for module '@antv/gl-matrix/lib/gl-matrix/vec3'. 'D:/workspace/smallwater_vue_ts_jest/node_modules/@antv/gl-matrix/lib/gl-matrix/vec3.js' implicitly has an 'any' ty
pe.
  Try `npm install @types/antv__gl-matrix` if it exists or add a new declaration (.d.ts) file containing `declare module '@antv/gl-matrix/lib/gl-matrix/vec3';`
    1 | 
  > 2 | import * as vec3 from '@antv/gl-matrix/lib/gl-matrix/vec3';
      |                       ^
    3 | export default vec3;
    4 | 
Version: typescript 3.8.3
`
希望官方修复

**Comment by zqlu** [comment]
新版本应该会修复了

**Comment by maihuochai** [comment]
> 新版本应该会修复了

感谢
