### ISSUE TITLE
水波图没有居中

### ISSUE THREAD

**Issue by JasonWong-ZS** [antvis/G2Plot#1041]
https://g2plot.antv.vision/zh/examples/liquid/basic#percent

**Comment by JasonWong-ZS** [comment]
@paleface001  参照官方我自己改了一版liquid.ts玩玩,可以实现中心居中,你看看对你们有没有用

registerShape('interval', 'liquid-fill-gauge', {
  draw(cfg: any, container) {
    // 先获取图形实际范围长度
    const box = this.parsePoint({ x: 1, y: 0 });
    // 计算出半径
    const radius = Math.min(box.x, box.y) / 2 * 0.8;
    // 十字交叉求出中心点
    const cp = {
      x: box.x / 2,
      y: box.y / 2,
    };
    const { fill } = getFillAttrs(cfg);
    const waves = container.addGroup({
      name: 'waves',
      attrs: {
        x: cp.x,
        y: cp.y,
      },
    });
    waves.setClip({
      type: 'circle',
      attrs: {
        x: cp.x,
        y: cp.y,
        r: radius,
      },
    });
    const clipCircle = waves.get('clipShape');
    addWaterWave(
      cp.x,
      cp.y,
      1 - cfg.points[1].y, // cfg.y / (2 * cp.y),
      3,
      fill,
      waves,
      clipCircle,
      radius * 4,
    );
    container.addShape('circle', {
      name: 'wrap',
      attrs: mix(getLineAttrs(cfg), {
        x: cp.x,
        y: cp.y,
        r: radius,
        fill: 'transparent',
      }),
    });

    // 计算某字体的宽高
    function getTextInfo(text, fontSize, fontFamily) {
      let canvas = document.createElement('canvas');
      let context = canvas.getContext('2d');
      context.font = `normal ${fontSize}px ${fontFamily}`;
      const textWidth = context.measureText(text).width;
      const textHeight = fontSize / 2;
      context = null;
      canvas = null;
      return { textWidth, textHeight };
    }

    // 显示的文本
    let text = '水波图的中心文本';
    let textColor = '#333';
    let fontSize = (Math.min(box.x, box.y) / text.length) * 0.5;
    let fontFamily = 'PingFang SC';

    // 添加中心文本,保证居中
    const { textWidth, textHeight } = getTextInfo(text, fontSize, fontFamily);
    container.addShape('text', {
      attrs: {
        x: cp.x - textWidth / 2,
        y: cp.y + textHeight / 2,
        fontFamily: fontFamily,
        text: text,
        fontSize: fontSize,
        fill: textColor,
      },
    });
    return waves[0];
  },
});

![image](https://user-images.githubusercontent.com/20633660/81520267-664d7e00-9376-11ea-81c4-ce8becfe4051.png)

**Comment by paleface001** [comment]
赞，我看看哈~

**Comment by RuanXuSong** [comment]
简单方法：修改padding以居中

**Comment by paleface001** [comment]
1.1.3已修复
