### ISSUE TITLE
基础Bar 组件X轴无法正常折叠或者隐匿

### ISSUE THREAD

**Issue by fanzhongyu** [antvis/G2Plot#1045]
是这样的，在使用Bar-基础条状图的时候，我的Y轴，有的是非常长的字段描述（例如任务dsafasdfsadfdsafdsafdsasafsadfsa，超级长，我想隐匿或者折叠），所以我想自动隐藏字段描述，然后我看到官网显示默认是自动隐藏的，在yAxis当中
label: {
    visible: true,
    autoRotate: true,
    autoHide: true
},
我自己也手动加到我的个人代码里了，但还是不行，于是我尝试各种方法，而后我也我尝试到了label中的style的textAlign还是不行，并且我把yAxis所有的能试了的参数都试了，还是不行，请问是默认的隐藏不起作用吗。
代码如下：
const barPlot = new Bar('topFailureBar', {
        data: this.mock.topFailureBarS,
        xAxis: {
          visible: false
        },
        yAxis: {
          label: {
            visible: true,
            **autoRotate: true,
            autoHide: true**                                       //我看官网这里是自动隐匿和换行，是这么用吗？
          },
          line: {
            visible: true
          },
          tickLine: {
            visible: true
          }
        },
        xField: 'value',
        yField: 'key',
        colorField: 'key',
        label: {
          visible: true,
          position: 'right',
          formatter: (v) => v + '%'
        }
      })
barPlot .render()

但是目前遇到的问题就是X轴无法正常隐藏或者换行，这样就会导致，X轴的数据非常长，右边的图片就会被无限的挤

![图片](https://user-images.githubusercontent.com/20722039/81494578-7dd82880-92dc-11ea-813c-aad4aae540b3.png)

**Comment by paleface001** [comment]
autoRotate和autoHide是当两个坐标轴文本相互重叠的时候进行自动旋转和自动隐藏，文本超长的话，建议利用yAxis.label.text.formatter对文本进行格式化

**Comment by fanzhongyu** [comment]
使用yAxis.label.formatter，通过substring解决问题，但是还是建议加上自动隐藏，或者控制yAxis的大小来控制yAxis的长度，来实现自动隐藏功能

**Comment by paleface001** [comment]
> 使用yAxis.label.formatter，通过substring解决问题，但是还是建议加上自动隐藏，或者控制yAxis的大小来控制yAxis的长度，来实现自动隐藏功能

是的，这是我们马上要做的事情，可以及时关注版本发布信息
