### ISSUE TITLE
column图如果X轴的字段重复，会自动覆盖。bar图如果Y轴字段重复，会自动覆盖

### ISSUE THREAD

**Issue by fanzhongyu** [antvis/G2Plot#1047]
column图如果X轴的字段重复，会自动覆盖。bar图如果Y轴字段重复，会自动覆盖，但是我本意就是两条数据，我不想覆盖，我想显示怎么办。。
![图片](https://user-images.githubusercontent.com/20722039/81521224-263bca80-9379-11ea-86b6-3b4cdd4a7dcb.png)

![图片](https://user-images.githubusercontent.com/20722039/81521244-3358b980-9379-11ea-9095-b6bd70f8ef7b.png)

**Comment by zqlu** [comment]
@fanzhongyu X 轴字段相同情况就会在图形上在 X 轴上同一位置上，可以考虑先预先处理下数据的重复数据
