### ISSUE TITLE
双折线混合图表在部分数据下不会渲染

### ISSUE THREAD

**Issue by mushan0x0** [antvis/G2Plot#1048]
https://codesandbox.io/s/crazy-banach-tdwu1?file=/index.js

把`消耗`改成1就能渲染了

**Comment by mushan0x0** [comment]
@paleface001 可以看看啥问题吗

**Comment by Petter-li** [comment]
我也遇到，官方好歹给个回复赛

**Comment by Petter-li** [comment]
提供一个假装解决方法。判断数据全等于0时，更改一个或多个0为0.0001之类的小数，然后调用formatter方法在展示时判断=== 0.0001就显示为0。这样可以做到既绘制图表，看起来效果也像数据为0。

**Comment by hustcc** [comment]
![image](https://user-images.githubusercontent.com/7856674/92603539-01814080-f2e2-11ea-9757-3255d26fc2b8.png)

全零的时候，scale 自动计算，全部为 0，所以看起来好像什么也没有绘制，这个时候可以强制设置 scale 的 min max 不为 0，那么就可以绘制出一些效果了。
