### ISSUE TITLE
事件没有触发

### ISSUE THREAD

**Issue by lls17** [antvis/G2Plot#1050]
事件一个都没触发，是我的写法有问题吗？
<img width="524" alt="事件触发" src="https://user-images.githubusercontent.com/19182925/81547145-0246ac00-93ae-11ea-94f1-6fcea71024e1.png">

**Comment by paleface001** [comment]
要包在`events`配置项里面

**Comment by lls17** [comment]
> events

可以了，真是多谢。
---------------------------------------------
还想问下 怎么实现shape的拖拽？  都在canvas里没法配置呀..

**Comment by paleface001** [comment]
现在G2Plot还不支持编辑态

**Comment by lls17** [comment]
> 现在G2Plot还不支持编辑态

是没开放像chartcube 这种可视的编辑吗？

**Comment by paleface001** [comment]
可视编辑不是g2plot的重点，直接使用chartCube就可以，一个团队维护的
