### ISSUE TITLE
柱状图设置color之后导致tooltip显示错误

### ISSUE THREAD

**Issue by MinchX** [antvis/G2Plot#1053]
柱状图设置 color 以及 colorField之后，tooltip内显示的内容会从[y轴名称：y轴数据]转变成[x轴数据：y轴数据]
比如正常应该显示【 生鲜水果 销售额（万元）：100 】变成显示【生鲜水果 生鲜水果：100】
详见
![image](https://user-images.githubusercontent.com/836569/81562256-1ba82200-93c7-11ea-8568-dee457124036.png)
https://g2plot.antv.vision/zh/examples/column/basic#column-label-color-adjust

**Comment by paleface001** [comment]
因为你配置了colorField，色彩映射的优先级高于位置映射，如果希望topltip显示固定字段的话，可以配置tooltip.fields
