### ISSUE TITLE
Not able to add formatter for waterfall chart label

### ISSUE THREAD

**Issue by karthiak23** [antvis/G2Plot#1054]
I tried adding $ symbol to the label of the waterfall chart. My code is below
label: {
        visible: true,
        formatter: (v) => return `$${v}`,
    },

**Comment by Ayue2229** [comment]
try this
```
label: {
	visible: true,
	formatter: (text, item) => {
		return `${item._origin.type}`
	}
}
```

**Comment by Me-Momo** [comment]
like this:
![image](https://user-images.githubusercontent.com/15646325/90235496-fa3a5480-de53-11ea-9202-ed16010eed55.png)

**Comment by karthi238** [comment]
Thanks @Me-Momo @Ayue2229 . I found the solution
