### ISSUE TITLE
G2Plot IE 下打不开

### ISSUE THREAD

**Issue by w675179089** [antvis/G2Plot#1060]
G2Plot IE 下打不开。
在vue-cli中使用的 版本2+；
刚开始创建项目的时候就加入babel-polyfill插件了 IE下一直没问题。新需求采用G2plot图表 在ie下访问报错。
求教各位大神有解决方法吗。
![image](https://user-images.githubusercontent.com/26165417/81776490-75246400-9521-11ea-9fa3-e0d9a94283f2.png)

**Comment by w675179089** [comment]
@paleface001

**Comment by paleface001** [comment]
不好意思，我这里没有办法测试ie，先排除法一下吧，不在vue环境下，随便写一个g2plot的demo在ie 11下运行，看看报不报错

**Comment by w675179089** [comment]
@paleface001  不引入g2plot 在ie 下访问是正常的 之前处理过vue 在ie白屏报错等问题。现在新页面引入后 访问就白屏了 一段代码一段代码的去注释 发现是 import {xx} from "@antv/g2plot" 这里引入的原因

**Comment by zqlu** [comment]
duplicate to #1023

**Comment by WeekendChang** [comment]
@w675179089 我也出现了这样的问题，请问怎么解决

**Comment by hustcc** [comment]
> 也出现了这样的问题，请问怎么解决

什么版本，什么代码？可以来一个 live demo 嘛？

**Comment by Kyoloro** [comment]
![image](https://user-images.githubusercontent.com/13166060/141272490-ce16e716-30cb-4bbd-834b-c7c73b06a282.png)

**Comment by Kyoloro** [comment]
![image](https://user-images.githubusercontent.com/13166060/141272616-1a573cd3-9879-4bfa-96b6-d0e5bbf951ec.png)

**Comment by Kyoloro** [comment]
看着是build产物里，自带一些IE不能识别的语法，比如const

**Comment by best-yuan** [comment]
请问大佬解决了吗
