### ISSUE TITLE
图表在设置网格线颜色失败

### ISSUE THREAD

**Issue by poison111222333** [antvis/G2Plot#1064]
import { Line } from '@antv/g2plot';

fetch('../data/fireworks-sales.json')
  .then((res) => res.json())
  .then((data) => {
    const linePlot = new Line(document.getElementById('container'), {
      title: {
        visible: true,
        text: '单折线图的基础用法',
      },
      description: {
        visible: true,
        text: '最基础简单的折线图使用方式，显示一个指标的趋势',
      },
      forceFit: true,
      data,
      padding: 'auto',
      xField: 'Date',
      yField: 'scales',
      xAxis: {
        type: 'dateTime',
        tickCount: 5,
        grid:{
           visible: true,
           style:{stroke:'#1c4266'}
        },
      },
      yAxis:{
           grid:{style:{stroke:'#1c4266'}},
           line: {visible:true,style:{stroke:'#2b5877'}},
            label:{style:{fill:'#80bff6'}},
            title:{visible:false}
       },
    });

    linePlot.render();
  });

这是官方基础折线图，界面上网格线可以开启跟关闭，颜色设置不生效

**Comment by paleface001** [comment]
文档有误，使用 axis.grind.line.style 进行配置
