### ISSUE TITLE
有没有类似于 G2 中 #getsnaprecords 的接口

### ISSUE THREAD

**Issue by Hyj2543** [antvis/G2Plot#1066]
当条形图数据太小不容易点击时，可以通过点击条形图阴影获取 data 。G2 有 #getsnaprecords 帮助解决，请问这个有什么解决方案吗？https://github.com/antvis/G2/issues/1598

**Comment by paleface001** [comment]
暂时没有提供

**Comment by Hyj2543** [comment]
那么请问有其他的解决方案吗，当数据差距太大时，图形不太容易点击
