### ISSUE TITLE
图表设置网格线样式不生效

### ISSUE THREAD

**Issue by poison111222333** [antvis/G2Plot#1071]
官网案例：
import { Line } from '@antv/g2plot';

fetch('../data/fireworks-sales.json')
  .then((res) => res.json())
  .then((data) => {
    const linePlot = new Line(document.getElementById('container'), {
      title: {
        visible: true,
        text: '单折线图的基础用法',
      },
      description: {
        visible: true,
        text: '最基础简单的折线图使用方式，显示一个指标的趋势',
      },
      forceFit: true,
      data,
      padding: 'auto',
      xField: 'Date',
      yField: 'scales',
      xAxis: {
        type: 'dateTime',
        tickCount: 5,
         line: {style:{stroke:'#2b5877'}},
                    label:{style:{fill:'#80bff6'}},
                    tickLine:{style:{stroke:'#2b5877'}}
      },
       yAxis:{
                    grid:{style:{stroke:'#1c4266'}},
                    line: {visible:true,style:{stroke:'#2b5877'}},
                    label:{style:{fill:'#80bff6'}}
                },
    });

    linePlot.render();
  });

**Comment by paleface001** [comment]
使用 axis.grid.line.syle 配置
