### ISSUE TITLE
移动端图表插件点击后

### ISSUE THREAD

**Issue by ICEPepsiCola** [antvis/G2Plot#1073]
![image](https://user-images.githubusercontent.com/13042355/81886107-71025000-95ce-11ea-98ea-9889a8525780.png)
![image](https://user-images.githubusercontent.com/13042355/81886192-a6a73900-95ce-11ea-9433-8fd38c7ba3a3.png)

**Comment by paleface001** [comment]
能提供一下配置吗？这样什么都看不出来

**Comment by ICEPepsiCola** [comment]
> 能提供一下配置吗？这样什么都看不出来

emmm，没有配置哦，g2plot官网的demo移动端调试就会出现，点击之后就会报错

**Comment by ICEPepsiCola** [comment]
G2/src/chart/controller/gesture.ts 是这个文件的错误

**Comment by zqlu** [comment]
这个应该已经在G2修复了

**Comment by ICEPepsiCola** [comment]
> 这个应该已经在G2修复了

太牛逼了吧，走点心可以？kpi项目？
