### ISSUE TITLE
StackedBar、PercentStackedBar label 显示 bug。

### ISSUE THREAD

**Issue by MasonLSJ** [antvis/G2Plot#1074]
StackedBar、PercentStackedBar
label : {
  position: 'right'
}
**文本不会显示**

**Comment by zqlu** [comment]
```
label: {
	visible: true,
	position: 'right'
}
```

**Comment by MasonLSJ** [comment]
条形图 - 堆积和百分比（
  label: {
  	  visible: true,
	  position: 'right'
  }
）
无效❌


柱状图 - 堆积和百分比（
  label: {
  	  visible: true,
	  position: 'top'
  }
）
无效❌

**Comment by MasonLSJ** [comment]
谢谢，已解决。 @zqlu
