### ISSUE TITLE
a wish list for new charts

### ISSUE THREAD

**Issue by paleface001** [antvis/G2Plot#1076]
新图表的愿望清单请回复在下面👇

If there is any new chart type u wanna use, please no hesitate to let us know 👇

**Comment by woshimack** [comment]
求箱型图

**Comment by billzxy** [comment]
请问下散点图或折线图现在能否支持误差(Error bars)？多谢！

**Comment by soulmachine** [comment]
蜡烛图，就是 tradingview 这种，基本上主流交易所都在用 tradingview, 这个需求非常大

**Comment by paleface001** [comment]
#1078

**Comment by kaoding** [comment]
寻求 Gantt （甘特图 ）React 组件

**Comment by kaoding** [comment]
https://github.com/ant-design/ant-design-pro/issues/6582

**Comment by wkl007** [comment]
求玉珏图
