### ISSUE TITLE
数据刷新BUG

### ISSUE THREAD

**Issue by mark0325** [antvis/G2Plot#1079]
如果初始数据为空，使用changData刷新为新的新的数据后，坐标轴不显示，次问题在折线图中发现的，其他图例暂未尝试

**Comment by dengfuping** [comment]
- 应该是一个通用问题，在条形图中也有这个问题: https://codesandbox.io/s/agitated-proskuriakova-tq15o

**Comment by paleface001** [comment]
changeData暂时不考虑初始空数据刷新的边界场景
