### ISSUE TITLE
怎样去掉 x轴两侧的留白

### ISSUE THREAD

**Issue by ChenWeihua123** [antvis/G2Plot#1082]
![75334515-f5dca800-58c2-11ea-984a-e4d700c573db](https://user-images.githubusercontent.com/33150900/82014106-7931bc80-96ae-11ea-99dc-66be22179c68.png)

**Comment by paleface001** [comment]
这是因为scale将xField识别为分类字段，分类字段是默认在两侧留有一些空间的，配置meta直接设置range为[0,1]，或声明xAxis.type为cat可解。

```
  meta:{
    year:{
      range:[0,1]
    }
  }
```
