### ISSUE TITLE
热力图 自适应容器宽高，改变视口宽度报错，页面空白显示。

### ISSUE THREAD

**Issue by MasonLSJ** [antvis/G2Plot#1084]
{
  forceFit: true
}
----> **改变视口宽度** 或 **updateConfig() 更新图表配置** 
控制台报错❌：container.js:113 Uncaught TypeError: Cannot read property 'filter' of undefined
页面显示：只显示 legend，其余空白。

**Comment by hustcc** [comment]
same with https://github.com/antvis/G2Plot/issues/805
