### ISSUE TITLE
when use slider the xAxis.label.autoHide not work

### ISSUE THREAD

**Issue by SunGuoQiang123** [antvis/G2Plot#1087]
when I use slider in a line chart, the xAxis label autoHided, but I want to keep them visible always through autoRotate, so I try to set xAxis.label.autoHide to false, but it not worked. the demo on homepage just replay the issue 
https://g2plot.antv.vision/zh/examples/line/basic#line-slider

**Comment by kyokan-xh** [comment]
带滚动条的柱状图这个autoHide也没有生效～

**Comment by kyokan-xh** [comment]
带滚动条的柱状图这个autoHide也没有生效～ @paleface001

**Comment by hustcc** [comment]
看看 v2 版本中是否存在这个问题，我测试是 ok 的。
