### ISSUE TITLE
面积图(Area)，网格线的颜色配置无效

### ISSUE THREAD

**Issue by yginuo** [antvis/G2Plot#1088]
![image](https://user-images.githubusercontent.com/18584367/82073205-8204ab80-970b-11ea-8703-a847ca639ac3.png)

网格线的颜色配置无效。

**Comment by yginuo** [comment]
I expected the color to be white, but it's actually black

**Comment by yginuo** [comment]
Wait online, hurry

**Comment by JasonWong-ZS** [comment]
正解在这里,兄弟
```
 yAxis: {
  grid:{
    line: {
      style:{
        stroke:'#fff',
      }
    }
  },
},
```

**Comment by paleface001** [comment]
楼上正解，文档待更新
