### ISSUE TITLE
柱状图 demo padding 计算错误

### ISSUE THREAD

**Issue by simaQ** [antvis/G2Plot#1092]
访问网址：https://g2plot.antv.vision/zh/examples/column/basic

![image](https://user-images.githubusercontent.com/6628666/82148125-07f83200-9885-11ea-93d5-9083fbcf82dd.png)

**Comment by simaQ** [comment]
是因为 @antv/component 的 axis title offset ?

**Comment by zqlu** [comment]
对的，依赖 https://github.com/antvis/G2Plot/pull/1058

**Comment by paleface001** [comment]
fixed via #1058
