### ISSUE TITLE
使用npm安装图表不显示

### ISSUE THREAD

**Issue by xvivx** [antvis/G2Plot#1094]
使用npm install @antv/g2plot,然后在项目引入相应的图表
import { Line } from '@antv/g2plot';

id为canvas的元素已经在index.html中存在
const linePlot = new Line('canvas', {
      data: '按照官网准备的一组数据',
      xField: 'year',
      yField: 'value'
    });
    linePlot.render();

结果，框架确实画出了一个canvas元素，有宽高，但是没有图表显示出来，页面一片空白。
重现方法：
可以用vue或者react的cli随意生成一个简单项目，然后在入口文件中写入上面代码，确保传入的id元素已经存在。

**Comment by paleface001** [comment]
你react里怎么用的？参考一下这个issue里的答案：https://github.com/antvis/G2Plot/issues/324

**Comment by xvivx** [comment]
@paleface001 我的意思是不一定是在react或者vue中使用g2plot，我只是使用vue脚手架搭出的项目测试了下npm安装这种情况，结果如问题所描述，现在不是说包一层让g2plot能拿到容器承载图表，现在这个容器已经成功传给了g2plot,g2plot也画出了一个canvas，只是这个canvs是空白的。按照#324做了一遍还是空白canvas，并无报错，做前端也有几年了，这些简单的仿照操作和代码执行分析还是能弄明白的，现在的结果是render后出现一个空白的canvas。

**Comment by paleface001** [comment]
那你提供一下复现代码吧，我这里复现不出来

**Comment by xvivx** [comment]
@paleface001 https://github.com/xvivx/g2plot
你克隆这个仓库就能复现，方便留下联系方式吗，您很敬业，希望能有些技术交流，915939795

**Comment by xvivx** [comment]
@paleface001 可否留下花名，我很关心这个问题，方便联系哈

**Comment by paleface001** [comment]
你是什么时候出现这个问题的，今天？

**Comment by paleface001** [comment]
@xvivx

**Comment by paleface001** [comment]
初步判断结果是g2的4.0.8版本导致react环境下计算不出padding，原因暂时还没有找到 @zqlu @hustcc

**Comment by bobo-wangyan** [comment]
我今天出现了这个问题，是1.0.2版本

**Comment by zqlu** [comment]
@xvivx 把yarn.lock删除掉，重新安装依赖应该就ok了

**Comment by vickychu** [comment]
我碰到一样的问题了，我的情况是这样的：
我在开发一个插件，这个插件用到了g2plot，插件内部运行的时候是ok的；这个插件打包发布之后，另一个库调这个插件，就会出现这个问题（有canvas但图标不出现）；

**Comment by zqlu** [comment]
> 我在开发一个插件，这个插件用到了g2plot，插件内部运行的时候是ok的；这个插件打包发布之后，另一个库调这个插件，就会出现这个问题（有canvas但图标不出现）；

是昨天遇到的吗，今天重新按照还有问题么

**Comment by vickychu** [comment]
昨天遇到的 今天重新安装还是有问题
![image](https://user-images.githubusercontent.com/23652084/82276413-c916c900-99b7-11ea-8981-ed12d438a756.png)

**Comment by zqlu** [comment]
> 昨天遇到的 今天重新安装还是有问题
> ![image](https://user-images.githubusercontent.com/23652084/82276413-c916c900-99b7-11ea-8981-ed12d438a756.png)

提供下复现的代码/仓库，看一下？

**Comment by xvivx** [comment]
https://github.com/xvivx/g2plot
这个代码库删除lock文件重装就正常了， @paleface001 具体是什么原因导致的，能分享吗？

**Comment by vickychu** [comment]
> > 昨天遇到的 今天重新安装还是有问题
> > ![image](https://user-images.githubusercontent.com/23652084/82276413-c916c900-99b7-11ea-8981-ed12d438a756.png)
> 
> 提供下复现的代码/仓库，看一下？

https://github.com/vickychu/agileBI
分支：feature/1.0.0

**Comment by xvivx** [comment]
@zqlu 能分享一下原因吗，这个库在昨天做了哪些修改吗

**Comment by xvivx** [comment]
@vickychu 删除lock文件，删除agileshot-common这个依赖，我看你在package里引用了两次，这个依赖安装不上，删除后重现install一下，我跑起来了，看到了好多图表

**Comment by zqlu** [comment]
> @zqlu 能分享一下原因吗，这个库在昨天做了哪些修改吗

应该我们昨天发不了G2的4.0.8版本，其中一个依赖版本号不兼容，G2Plot这边没有同步升级和发布新版本导致的。

**Comment by xvivx** [comment]
@zqlu 感谢感谢，明白了

**Comment by vickychu** [comment]
> @vickychu 删除lock文件，删除agileshot-common这个依赖，我看你在package里引用了两次，这个依赖安装不上，删除后重现install一下，我跑起来了，看到了好多图表

好的 我试试 谢谢
