### ISSUE TITLE
Is there any way to change bullet chart title position?

### ISSUE THREAD

**Issue by vijay4495** [antvis/G2Plot#1095]
Presently, bullet chart title and it's horizontally aligned. like below
![image](https://user-images.githubusercontent.com/38109961/82236178-5ffc6a80-9951-11ea-92eb-b02b36d4f8c5.png)
Is there way to change like below chart
![image](https://user-images.githubusercontent.com/38109961/82236322-8fab7280-9951-11ea-980d-f9022df6c3f3.png)

**Comment by paleface001** [comment]
The text presented on the left side of the bullet bar was axis.label actually, so it could not be positioned in the middle of the bar.

Or you can try to hide the axis:
```
  xAxis:{
    label:{
      visible: false
    }
  }
```
and then draw the center-aligned title instead
```
  title: {
    visible: true,
    text: 'Sales Rate',
    alignTo:'middle'
  },
```

**Comment by NaveenDA** [comment]
Is there is any workaround for this?
