### ISSUE TITLE
G2Plot中bar组件类型如何实现connectedArea这种样式

### ISSUE THREAD

**Issue by xiao15934831580** [antvis/G2Plot#1098]
在G2Plot 中，基础条形图bar，需要实现类似于堆积柱形图StackedColumn中connectedArea这样的样式，有什么方法吗

**Comment by paleface001** [comment]
暂时还不支持，后续可能会作为转化率组件的一个配置项：https://g2plot.antv.vision/zh/examples/bar/basic#bar-conversion

**Comment by xiao15934831580** [comment]
Column支持坐标轴转化吗，有什么方法可以转化坐标系吗

**Comment by paleface001** [comment]
> Column支持坐标轴转化吗，有什么方法可以转化坐标系吗

G2Plot不直接提供转置坐标系，转置坐标系下的column可以直接使用bar
