### ISSUE TITLE
环图修改图形样式的描边不生效？

### ISSUE THREAD

**Issue by poison111222333** [antvis/G2Plot#1101]
想要把环图色块中间的白色描边修改颜色怎么更改？使用API里面的属性设置没有效果
![DWSCK@)RF2{A(KQ2}P1}N~K](https://user-images.githubusercontent.com/65275963/82312120-33039280-99f9-11ea-87d7-069ebd7cc2df.png)

**Comment by paleface001** [comment]
继承了pieStyle但是没有更新成自己的命名域，可以暂时用pieStyle更新样式
