### ISSUE TITLE
雷达图（指定宽度 例如350*350）不配置title时，数据溢出

### ISSUE THREAD

**Issue by Stanny2017** [antvis/G2Plot#1102]
![image](https://user-images.githubusercontent.com/26297802/82343479-7ecc3100-9a25-11ea-85b7-5470c251882f.png)

**Comment by paleface001** [comment]
目前极坐标轴的label还没有做响应式，过长label可以用format自己截断一下

**Comment by Stanny2017** [comment]
> 目前极坐标轴的label还没有做响应式，过长label可以用format自己截断一下

加上title 配置后同样的宽高是能自适应的

另外请教下，雷达图这里如何配置加载动画呀
