### ISSUE TITLE
G2Plot是否支持动态图表的配置

### ISSUE THREAD

**Issue by Sai0514** [antvis/G2Plot#1103]
https://g2.antv.vision/zh/examples/gallery/dynamic
如题，G2里面的动态图表可以用G2Plot直接配置吗？

**Comment by paleface001** [comment]
可以像这个例子一样https://g2plot.antv.vision/zh/examples/line/multiple#line-label，封装成一种动画类型

**Comment by hustcc** [comment]
当前没有内置支持时间序的动态图表，在12月会考虑内部支持掉。包括排行版，散点图等。
