### ISSUE TITLE
Tooltip formatter 返回值类型问题

### ISSUE THREAD

**Issue by hmz5** [antvis/G2Plot#1105]
![image](https://user-images.githubusercontent.com/16495308/82417090-a1099180-9aad-11ea-897d-48a88c1bb3d1.png)

求教为什么formatter中的value需要是一个number值

很多时候在tooltip中还是需要显示一些单位的，所以这个value为数子限制了这些操作

**Comment by Ayue2229** [comment]
这样写也是可以展示的
```
tooltip: {
	visible: true,
	formatter: function (value, type) {
	  if (type === '0') {
		return { name: 'cancel', value: value + '个' }
	  }
	  if (type === '1') {
		return { name: 'done', value: value + '个' }
	  }
	}
},
```

**Comment by hustcc** [comment]
到这里统一回复 #1027
