### ISSUE TITLE
建议当线状图在到底最大值和最小值时完全显示出线的形状

### ISSUE THREAD

**Issue by maihuochai** [antvis/G2Plot#1106]
线状图达到最小值和最大值时，无法完全显示线的新装，只显示一半 ，建议完全显示
下面是到达最大值和最小值时的样式：
![image](https://user-images.githubusercontent.com/28753640/82430427-e33bce80-9abf-11ea-8e64-4c420d2f8c58.png)
![image](https://user-images.githubusercontent.com/28753640/82430443-e636bf00-9abf-11ea-8e3f-4123ca0b8123.png)
![image](https://user-images.githubusercontent.com/28753640/82430709-4d547380-9ac0-11ea-8880-b80c514e0494.png)

**Comment by paleface001** [comment]
可以手动配置一下y轴的最大和最小值
```
yAxis:{
  min: 25,
  max: 120
}
```

**Comment by Airkro** [comment]
@paleface001 

虽然可以通过现有的配置解决，但毕竟涉及到视图裁剪的普遍性问题，如果G2Plot的产品定位之一是便利性，那么官方能否考虑优化一下
