### ISSUE TITLE
g2 plot折线图点击事件无效

### ISSUE THREAD

**Issue by aguoshuai** [antvis/G2Plot#1107]
g2 plot的事件要怎么配置，比如折线图的点击事件就无法生效，配置了没反应。
function getLineConfig(data){
    return {
        title: {
          visible: true,
          text: '曲线折线图',
        },
        description: {
          visible: true,
          text: '用平滑的曲线代替折线。',
        },
        padding: 'auto',
        forceFit: true,
        data,
        xField: 'year',
        yField: 'value',
        smooth: true,
        interactions: [
          {
            type: 'slider',
            cfg: {
              start: 0,
              end: 0.5,
            },
          },
        ],

        onLineClick:clickAction
      }

  }
  function clickAction(){
    console.log('111')
  }

**Comment by paleface001** [comment]
```
events:{
  onLineClick:(ev)=>{}
}
```

**Comment by aguoshuai** [comment]
那我要如何获取到我点击的那个值呢
{x: 60, y: 136.109375, clientX: 405, clientY: 182, target: e, …}
canvas: e {_events: {…}, destroyed: false, cfg: {…}, attrs: {…}}
clientX: 405
clientY: 182
data: (86) [{…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}]
gEvent: t {bubbles: true, target: e, currentTarget: e, delegateTarget: e, delegateObject: undefined, …}
plot: r {_events: {…}, layers: Array(0), destroyed: false, visibility: true, rendered: true, …}
target: e {_events: {…}, destroyed: false, cfg: {…}, attrs: {…}}
x: 60
y: 136.109375

**Comment by paleface001** [comment]
data就是啊，我理解你想要的是当前点击位置对应折线上的数据，这个目前不支持，只能获取某根折线的整条数据。建议通过绘制出折线上的数据点，监听点上的点击事件来完成：

```
point:{
   visible: true
},
events:{
   onPointClick:(ev)=>{}
}
```

**Comment by aguoshuai** [comment]
好的，感谢你的回答。

**Comment by tunshiyu** [comment]
请问`当前点击位置对应折线上的数据`,这个需求咱们后面会考虑实现吗
