### ISSUE TITLE
水波图能否支持配置自定义形状

### ISSUE THREAD

**Issue by maihuochai** [antvis/G2Plot#1113]
希望官方能够支持水波图配置为自定义形状，如隔壁echarts那样，因为有些场景下的确需要自定义形状：
![image](https://user-images.githubusercontent.com/28753640/82544753-2f524600-9b88-11ea-85fe-ec17d1e61fa9.png)
![image](https://user-images.githubusercontent.com/28753640/82544776-36795400-9b88-11ea-9d6a-f53f9aecd8d3.png)
![image](https://user-images.githubusercontent.com/28753640/82544870-5ad53080-9b88-11ea-92c5-bc62c323522d.png)

**Comment by hustcc** [comment]
具体需要哪些形状？
