### ISSUE TITLE
数据动态变化的折线图，鼠标放上去会出现错乱

### ISSUE THREAD

**Issue by dengfuping** [antvis/G2Plot#1118]
- G2Plot 版本: 1.1.3，且经测试发现，该问题从 1.0.4 版本就开始出现。

![2020-05-22 00-11-30 2020-05-22 00_13_19](https://user-images.githubusercontent.com/14918822/82580187-6abd3680-9bc1-11ea-9dac-85271462049d.gif)

**Comment by paleface001** [comment]
应该是G2图形active的bug

**Comment by dengfuping** [comment]
- 奇怪，在 [G2](https://riddle.alibaba-inc.com/riddles/a4943ef1) 和 [G2Plot](https://riddle.alibaba-inc.com/riddles/6dbac6a5) 上都无法重现，业务上先排查下。

**Comment by dengfuping** [comment]
@paleface001 这个问题好解吗？如果问题暂时没有定位到，业务上就先降级处理了。

**Comment by paleface001** [comment]
能复现吗？

**Comment by dengfuping** [comment]
- 写了个 G2Plot 的 [例子](https://riddle.alibaba-inc.com/riddles/6dbac6a5)，还是不能复现 ~。后续我剥离业务逻辑再看下，在 `changeData()` 前先 `updateConfig()` 能避免这个问题，业务上先这样处理，避免影响发版。

**Comment by paleface001** [comment]
好的，可以看看只更新数据，不做其他配置项的更新还会不会出现这个问题
