### ISSUE TITLE
环图Ring 小数计算精度问题

### ISSUE THREAD

**Issue by gracelinmumu** [antvis/G2Plot#1119]
环图数据为小数时，总计计算出现精度问题，数据示例
`import { Donut } from '@antv/g2plot';

const data = [
  {
    type: '分类一',
    value: 0.1,
  },
  {
    type: '分类二',
    value: 0.2,
  }
];

const donutPlot = new Donut(document.getElementById('container'), {
  forceFit: true,
  title: {
    visible: true,
    text: '环图',
  },
  description: {
    visible: true,
    text: '环图的外半径决定环图的大小，而内半径决定环图的厚度。',
  },
  radius: 0.8,
  padding: 'auto',
  data,
  angleField: 'value',
  colorField: 'type'
});

donutPlot.render();
`

![image](https://user-images.githubusercontent.com/7775683/82624073-4fc7e200-9c14-11ea-92ef-22dd2ec111a6.png)

**Comment by Ayue2229** [comment]
手动处理一下 
 `let sum = Math.fround(0.3259).toFixed(2)`

**Comment by hustcc** [comment]
可以参考这个：https://github.com/antvis/G2/issues/2720
