### ISSUE TITLE
能否支持图例之定义

### ISSUE THREAD

**Issue by maihuochai** [antvis/G2Plot#1121]
希望官方支持图例自定义，如：
1.字体颜色
2.字体大小
3.图例间的间距
4.图例marker大小
5.图例marker自定义
6.图例完全自定义：传入的html+css渲染为图例

某些场景下，背景色玩暗色，而图例的字体颜色也为暗色，这会导致字体很难被看清楚
![image](https://user-images.githubusercontent.com/28753640/82640676-954cd500-9c3d-11ea-89f4-f89d4218b2da.png)

**Comment by hustcc** [comment]
v2 中已经支持。

**Comment by VXenomac** [comment]
请问有相关示例代码吗
