### ISSUE TITLE
tooltip 实现自定义 custom 内容时的 bug

### ISSUE THREAD

**Issue by RuanXuSong** [antvis/G2Plot#1122]
之前我提过一个issue，关于filter legend 和 tooltip的，链接：
https://github.com/antvis/G2Plot/issues/1014
有人推荐了用这个官方例子的方法来自定义 tooltip：<a href="https://g2plot.antv.vision/zh/examples/general/tooltip#tooltip-statistic-value">官方例子</a>
效果是可以实现的，但是因为用的是 tooltip.custom.onChange 方法，所以在第一次 hover 图表的时候，tooltip 效果是没处理前的，如下：
![bug1](https://user-images.githubusercontent.com/39564114/82655091-4199b600-9c54-11ea-930e-6d9f31e489d9.jpg)
在滑动鼠标以后，触发 onChange 事件以后才会出来自定义的条目，如下：
![expect](https://user-images.githubusercontent.com/39564114/82655210-68f08300-9c54-11ea-9c50-bd43902d796c.jpg)
这应该算是一个 bug 吧，期望效果：在鼠标第一次 hover 的时候就显示全部自定义条目。

========

附加一点：
在把  tooltip.custom.onChange 参数中 cfg.items 里的数组都移除完以后还会显示空的 tooltip ,如下：
![bug2](https://user-images.githubusercontent.com/39564114/82656076-b4eff780-9c55-11ea-8aa2-e9d9e4aa6a8d.jpg)

期望效果：如果 cfg.items 数组为空，不显示 tooltip。

**Comment by paleface001** [comment]
可以使用
```
tooltip:{
    custom:{
       customContent:()=>{
       }
    }
}
```
这个方法可以返回任意的htmlString
