### ISSUE TITLE
根据主题颜色统一设置线性渐变

### ISSUE THREAD

**Issue by markh5** [antvis/G2Plot#1124]
```
areaStyle: {
  fill: 'l(90) 0:#5B8FF9 1:#ffffff',
}
```

如文档所示，如果有多个区域图的话，那么每个区域图都是一样的样式，我如何根据官方生成的主题色来进行统一的线性渐变设置

![image](https://user-images.githubusercontent.com/16110230/82789106-510b4000-9e9c-11ea-90dd-27be842f912e.png)
如图，我希望每个区域图都是基于官方生成的颜色进行统一的线性渐变配置

**Comment by paleface001** [comment]
可以使用callback的方式指定areaStyle:

```
areaStyle:(...arg){
    return your style;
}
```

**Comment by markh5** [comment]
console了一下arg，发现是seriesField指定的值，但是console次数是data.length的一倍，这个规则是什么啊？

**Comment by markh5** [comment]
@paleface001
