### ISSUE TITLE
xAxis.label.offsetX 失效，rotate错位

### ISSUE THREAD

**Issue by ntscshen** [antvis/G2Plot#1127]
**问题：xAxis.label.offsetX 失效，rotate错位（ 折线图、柱状图 其他图没有测试 ）
版本：v1.1.4**

```javascript
// 打开官网"基础柱状图"案例, 把代码贴一下试试看
  xAxis: {
    label: {
      visible: true,
      offset: 50,
      offsetX: 1200, //失效 -> 在 offset 的基础上，设置坐标轴文本在 x 方向上的偏移量
      offsetY: 1200, //失效 -> 在 offset 的基础上，设置坐标轴文本在 y 方向上的偏移量
      rotate: 360, //错位（ Math.PI / 3 ） -> label 文本旋转的角度，使用角度制
    },
  },
```

![image](https://user-images.githubusercontent.com/21041458/82873315-e70b9d00-9f66-11ea-894e-9f5128f88453.png)

**Comment by paleface001** [comment]
rotate传入弧度试一下

**Comment by ntscshen** [comment]
OK👌的，`Math.PI / 3 `

**Comment by ntscshen** [comment]
@paleface001 还有一个问题 `offsetX和offsetY` 偏移失效

**Comment by ntscshen** [comment]
@hustcc xAxis.label.offsetX和yAxis.label.offsetX 偏移位置失效，会在v2更新吗，还是在小版本修复

**Comment by hustcc** [comment]
```ts
yAxis: {
    label: {
    offset: -100,
    }
  }
```

![image](https://user-images.githubusercontent.com/7856674/95545430-74d8b800-0a30-11eb-9605-7c810307556d.png)

并没有 offsetX，offsetY 的区分。
