### ISSUE TITLE
changeData调用后有上次渲染的残留

### ISSUE THREAD

**Issue by zhangyu1818** [antvis/G2Plot#1128]
![image](https://user-images.githubusercontent.com/11534968/82875120-90539280-9f69-11ea-8770-92d690d59023.png)

我本地是1.1.4，渲染的数据结构相同，内容变了，用changeData上一次的数据没有清除掉，就像上图

我想复现，但是codesandbox里就不会有这个问题，在官方文档上直接改也会出现上次的残留，这个图是我在官网复现截的

**Comment by zhangyu1818** [comment]
```
setTimeout(() => {
  barPlot.changeData([
    { 地区: "华1北", 销售额: 24417301.017000004 },
    { 地区: "西1南", 销售额: 13031124.508000002 }
  ]);
}, 2000);
```
官网的基础条形图下面加上这段

**Comment by paleface001** [comment]
应该是数据重绘的时候label没有清空

**Comment by zhanchengkun** [comment]
+1 changeData label 没刷新 还是旧的

**Comment by zhanchengkun** [comment]
不用changeData
临时用 barPlot.updateConfig({
...定义时的其他属性,
data: 新数据})
barPlot.render(); 可解决。

**Comment by rayroad** [comment]
@paleface001 请问这个问题修复了吗？

**Comment by qq159217** [comment]
1.18 未修复,太坑了,项目里用的还挺多,太坑

**Comment by hustcc** [comment]
使用 updateConfig。
