### ISSUE TITLE
tooltip.domStyles.g2-tooltop失效

### ISSUE THREAD

**Issue by ntscshen** [antvis/G2Plot#1130]
**问题：柱状图tooltip.domStyles.g2-tooltop设置后失效
版本：v1.1.4
原因：文档key值描述错误 `g2-tooltop` -> `g2-tooltip`**

![image](https://user-images.githubusercontent.com/21041458/82896825-2ea32080-9f89-11ea-8945-de97d089f689.png)

![image](https://user-images.githubusercontent.com/21041458/82896796-1fbc6e00-9f89-11ea-9415-c2c6c60915fe.png)

**Comment by paleface001** [comment]
不好意思，笔误，tooltip
