### ISSUE TITLE
多折线图的情况下 当分类字段seriesField为date类型时，系统会默认成颜色值？怎么办

### ISSUE THREAD

**Issue by summDora** [antvis/G2Plot#1131]
多折线图的情况下 当分类字段seriesField为date类型时，系统会默认成颜色值？怎么办
this.line=new Line(document.getElementById(this.name), {
            title: {
                visible: true,
                text: this.linedata.title,
            },
            forceFit:true,
            description: {
                visible: true,
                text: this.linedata.description,
            },
            seriesField :'date',
            data:this.linedata.data,
            xField: 'year',
            yField: 'value',
        });
 linedata:{
        title:'登录用户数',
        description:'今天对比昨天',
        data:[
          /* {groupby:'xx年xx月xx日', year: null,  value: null }, */
          {date:'2020-05-08', year: '1992', value: 4},
          {date:'2020-05-08', year: '1993', value: 3.5 },
          {date:'2020-05-08', year: '1994', value: 5 },
          {date:'2020-05-07', year: '1991', value: 4.9 },
          {date:'2020-05-07', year: '1992', value: 6 },
          {date:'2020-05-07', year: '1993', value: 7 },
          {date:'2020-05-07', year: '1994', value: 9 },
          {date:'2020-05-09', year: '1993', value: 4.9 },
          {date:'2020-05-09', year: '1991', value: 6 },
          {date:'2020-05-09', year: '1992', value: 7 },
          {date:'2020-05-09', year: '1994', value: 9 },
          /* {groupby:'xx年xx月xx日', year: null,  value: null }, */
        ]
      }

**Comment by paleface001** [comment]
多折线的分组字段必需为分类字段，可以尝试通过meta把字段类型指定为cat类型

```
meta:{
  date:{
      type: 'cat'
  }
}

```
