### ISSUE TITLE
折线图changeData时  只更新了y轴的值，x轴没有变化

### ISSUE THREAD

**Issue by zetanvi** [antvis/G2Plot#1134]
![month](https://user-images.githubusercontent.com/30707367/82974721-3b695800-a00d-11ea-9666-3be4a1b2adb5.jpg)
![year](https://user-images.githubusercontent.com/30707367/82974726-3c01ee80-a00d-11ea-99fc-15c70b2b8eb8.jpg)
第一张图只有一个数据，切换到年时发现只有y轴数据改变，x轴数据还是原来的，使用的方法是 plot.changeData(newData);

**Comment by hustcc** [comment]
使用 updateConfig。
