### ISSUE TITLE
雷达图径向轴颜色填充不生效

### ISSUE THREAD

**Issue by Stanny2017** [antvis/G2Plot#1135]
gridAlternateColor 设置不生效
雷达图径向轴分为四块区域，如何分别设置颜色填充？

```js
radiusAxis: {
        tickCount: 5,
        visible: true,


        label: {
            visible: false,
        },
        // gridAlternateColor: 'red',  不生效
        grid: {
            line: {
                type: 'line',
            },
            alternateColor: ['color1', 'color2', 'color3', 'color4', ], // 'color3', 'color4', 不生效
        },
    },
```

使用浏览器全局加载引用

**Comment by paleface001** [comment]
```
  radiusAxis: {
    grid: {
      alternateColor: ['green','blue'],
    },
  },
```
<img width="589" alt="屏幕快照 2020-05-27 下午4 29 32" src="https://user-images.githubusercontent.com/5888974/82996261-4933d300-a037-11ea-90bf-a6dff21b9d3e.png">

**Comment by Stanny2017** [comment]
> ```
>   radiusAxis: {
>     grid: {
>       alternateColor: ['green','blue'],
>     },
>   },
> ```
> 
> <img alt="屏幕快照 2020-05-27 下午4 29 32" width="589" src="https://user-images.githubusercontent.com/5888974/82996261-4933d300-a037-11ea-90bf-a6dff21b9d3e.png">


api文档的写法只能是设置两种颜色间隔交替，求教 能做到下图这种效果吗  不同值范围区分不同颜色，
![image](https://user-images.githubusercontent.com/26297802/82999264-55219400-a03b-11ea-9ae0-dca78502122a.png)

**Comment by TopAlien** [comment]
![企业微信20220822-162429](https://user-images.githubusercontent.com/33052129/185876748-44d62822-da51-46e5-a933-860d388c61c1.png) 如图黄线会被盖掉，有什么办法可以设置层级。
