### ISSUE TITLE
changeData如果开启了scrollBar，且数据数量和上次不一致会导致布局错乱

### ISSUE THREAD

**Issue by zhangyu1818** [antvis/G2Plot#1137]
https://codesandbox.io/s/amazing-glitter-8tgo4?file=/index.js

这种情况使用changeData可以吗，主要是想要数据切换时的动画效果，如果updateConfig的话切换很僵硬

**Comment by zqlu** [comment]
https://codesandbox.io/s/heuristic-heisenberg-xmqx4?file=/index.js 新版本看下是OK的？

**Comment by zhangyu1818** [comment]
![图片](https://tva1.sinaimg.cn/large/007S8ZIlgy1gf98lsvroqg30dw0blnon.gif)
我这看1.1.5还是有这种情况呢，就是20条数据变50条的时候挤在一起了，拖一下窗口就好了

**Comment by zqlu** [comment]
> ![图片](https://camo.githubusercontent.com/91c6c9d2d63570a5fcbd48e8cff2f64fc9682f40/68747470733a2f2f747661312e73696e61696d672e636e2f6c617267652f30303753385a496c677931676639386c7376726f71673330647730626c6e6f6e2e676966)
> 我这看1.1.5还是有这种情况呢，就是20条数据变50条的时候挤在一起了，拖一下窗口就好了

看到了，我这边修下
