### ISSUE TITLE
矩形树图样式配置

### ISSUE THREAD

**Issue by Skyblue-happy** [antvis/G2Plot#1146]
矩形树图只能设置标题的样式，不能设置每个子集内的文字样式，默认文字太小了，看不清楚。

**Comment by Skyblue-happy** [comment]
![image](https://user-images.githubusercontent.com/63780938/83371898-5c0f2480-a3f6-11ea-934d-61dacc595ebe.png)
图表文字字太小.png

**Comment by paleface001** [comment]
```
 label:{
    style:{
      fontSize:15
    }
  }
```
