### ISSUE TITLE
label 配置项不支持textStyle的配置（暂不提供支持）

### ISSUE THREAD

**Issue by Me-Momo** [antvis/g2plot#115]
目前，配置`label.textStyle`是不生效的，看了  g2的`labelController` 层，并没有使用用户配置labelOptions.textStyle, 是不打算 开放 `label.textStyle`的配置吗?只能在 theme 中配置全局 
 `label.textStyle`? 这么做的原因是什么? @paleface001 

复现测试单例如下:
```javascript
    const pie = new Pie(canvasDiv, {
      width: 600,
      height: 600,
      data: largeData,
      label: {  
        visible: true,
        type: 'custom-pie',
        formatter: (text, item, index) => {
          const origin = item._origin;
          return `${origin['type']}\n\n${origin['value']}`;
        },
        //  🔥 此处的配置是无效的 🔥
        textStyle: {
          lineHeight: 16,
          fill: 'red',
        }
      },
      angleField: 'value',
      colorField: 'type',
      padding: [0, 0, 0, 0],
      animation: false,
      radius: 0.75,
      innerRadius: 0.25,
      title: {
        text: '饼图 - custom pie label',
      },
      description: {
        text: '1. 量级大,100条数据;',
      },
      legend: {
        visible: false,
      },
    });
```
![image](https://user-images.githubusercontent.com/15646325/66814233-d9ba1900-ef68-11e9-9ae0-429b265b87fa.png)

**Comment by Me-Momo** [comment]
这样子，`label.textStyle`配置就可以生效了，需要支持的话，我就提交MR
![image](https://user-images.githubusercontent.com/15646325/66814813-cbb8c800-ef69-11e9-904b-1aad755c7c06.png)

**Comment by Me-Momo** [comment]
我发现需要配置为`label.style` 就生效了，但是theme默认中label 字体样式的配置方式是 `label.textStyle` 这样子是不是会心智不统一啊

**Comment by paleface001** [comment]
label.textStyle是g2底层的配置方式，plot包了一层

**Comment by Me-Momo** [comment]
> label.textStyle是g2底层的配置方式，plot包了一层

那G2Plot就是说不支持配置 theme ??
