### ISSUE TITLE
areaStyle规则

### ISSUE THREAD

**Issue by markh5** [antvis/G2Plot#1155]
`
areaStyle:(...arg){
    return your style;
}
`

console了arg，输出了seriesField指定的值，但是console了很多遍。

我想根据不同的seriesField指定不同的渐变颜色，根据console的arg无法做到，能不能根据G2plot生成的颜色统一设置渐变？？

**Comment by paleface001** [comment]
根据seriesField的具体返回值判断，例如：
```
areaStyle: value => {
    if(value === 'bill'){
      return {
        lineDash: [5,2]
      }
    }
  },
```
