### ISSUE TITLE
仪表盘Gauge刻度配置无效，一直都是0，25，50，75，100这5个刻度

### ISSUE THREAD

**Issue by inceptiongt** [antvis/G2Plot#1156]
### subTickCount无效

![image](https://user-images.githubusercontent.com/20478779/83383618-195e4400-a418-11ea-9f6b-e2559b2e33bf.png)
如图，subTickCount已设置为2，但还是4的效果

### 主刻度可以增加到6个，但主刻度label一直是5个：0，25，50，75，100

![image](https://user-images.githubusercontent.com/20478779/83384127-2fb8cf80-a419-11ea-9d4a-a88f50b5093f.png)
**DEMO**：https://antv-g2plot.gitee.io/zh/examples/gauge/gauge#basic-cutomize

**Comment by hustcc** [comment]
新版本 v2 可以配置。如图所示：

![image](https://user-images.githubusercontent.com/7856674/94563257-07db5a80-0299-11eb-8614-ef2b564824a2.png)
