### ISSUE TITLE
xAxis.grid.style属性不生效

### ISSUE THREAD

**Issue by inceptiongt** [antvis/G2Plot#1157]
如图：通过grid.style设置网格颜色，线宽无效
![image](https://user-images.githubusercontent.com/20478779/83404630-994ad500-a43d-11ea-85f1-700eed94625f.png)
DEMO：https://antv-g2plot.gitee.io/zh/examples/line/basic
`grid: {
          visible: true,
          style: {
            stroke: '#ff0000',
            lineWidth: 10,
          }
 }`

**Comment by paleface001** [comment]
```
grid:{
   visible: true,
   line:{
       style:{
            stroke: '#ff0000', 
            lineWidth: 10
       }
   }
}
```

**Comment by sunui** [comment]
@paleface001 感谢。但是官方示例里是错的 https://antv-g2plot.gitee.io/zh/examples/general/axis#axis-style
