### ISSUE TITLE
基础条形图如何显示xAxis？

### ISSUE THREAD

**Issue by zhangyu1818** [antvis/G2Plot#1158]
```
xAxis: {
  label: {
    visible: true,
  },
  grid: {
    visible: true,
  },
}
```
单独写`visible:true`是不生效的吗？

我看官网的例子也没有显示，我看预览图上有，点进去看还是没有显示

![image](https://user-images.githubusercontent.com/11534968/83485851-79b5ba00-a4da-11ea-86cc-d357ace82b30.png)

**Comment by paleface001** [comment]
建议还是多看一下文档，y轴在文档里已经标出来了https://g2plot.antv.vision/zh/docs/manual/plots/bar#%E5%9B%BE%E8%A1%A8%E7%BB%84%E4%BB%B6
截图效果只是没有显示轴线和刻度线而已

**Comment by zhangyu1818** [comment]
是我看岔了，打扰了orz
