### ISSUE TITLE
应用transform: scale后,tooltip出现错位，有没有什么解决方案

### ISSUE THREAD

**Issue by xiaochong44** [antvis/G2Plot#1160]
应用transform: scale后,tooltip出现错位，有没有什么解决方案

**Comment by cnyballk** [comment]
同问

**Comment by hustcc** [comment]
新版本的 v2 已经解决这个问题。PR 在这里 https://github.com/antvis/G2Plot/pull/1674 十一前发布以个 patch 版本包含这个能力。

使用方式：

```ts
new Line('container', {
  supportCSSTransform: true,
});
```
