### ISSUE TITLE
水波图changeValue() 数据失败;

### ISSUE THREAD

**Issue by chenkuangAmber** [antvis/G2Plot#1165]
当前使用G2Polt版本："@antv/g2plot": "^1.1.5",

在使用水波图的过程中，需要对水波图进行更新数据
用到了changeValue方法，报错显示：
![image](https://user-images.githubusercontent.com/31473119/83617751-1bf99e80-a5bc-11ea-91fe-5893d4b14ecb.png)
贴出水波图代码：
![image](https://user-images.githubusercontent.com/31473119/83617873-49464c80-a5bc-11ea-8cad-d82205e2c932.png)

**Comment by hustcc** [comment]
v1 版本不再处理，会在 v2 中避免这个问题！
