### ISSUE TITLE
堆叠条形图在数组的数据值为0时，图表会空一截legend的位置

### ISSUE THREAD

**Issue by zhangyu1818** [antvis/G2Plot#1166]
在数据里的值为0的时候，标题和图表之间会有一截legend的空白，但是legend已经配置在左下角了

[![Edit zealous-booth-hd4nf](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/zealous-booth-hd4nf?fontsize=14&hidenavigation=1&theme=dark)

有数据后，拖一下窗口，就能复现

图片

![](https://tva1.sinaimg.cn/large/007S8ZIlgy1gfg7u37gpvg30b406l76b.gif)

另外想问一下，堆叠条形图如何排序？复现里两次数据的位置都没有变，但是顺序变化了

**Comment by hustcc** [comment]
感谢反馈，看看 v2 是否存在这个问题。 https://g2plot.antv.vision/zh/examples/bar/percent
