### ISSUE TITLE
建议支持自定义图例翻页按钮

### ISSUE THREAD

**Issue by xiecg** [antvis/G2Plot#1170]
现在这个太简陋了

![image](https://user-images.githubusercontent.com/10857932/83844360-6c4a3b00-a739-11ea-9b9a-48def9f5cc5c.png)

**Comment by hustcc** [comment]
你期望的是什么样子的？

**Comment by xiecg** [comment]
能用这种 icon 代替就行 
![image](https://user-images.githubusercontent.com/10857932/90250227-5ca04e80-de6e-11ea-8c58-0a01a1e3583b.png)

**Comment by hustcc** [comment]
我们考虑一下能够抛出来自定义的口子。
