### ISSUE TITLE
xAxis 配置下的 type 设置为 'linear' 无法绘制图表

### ISSUE THREAD

**Issue by xiecg** [antvis/G2Plot#1173]
例子如下：

https://codesandbox.io/s/nostalgic-hooks-71ez4

希望的效果如下图，能把X轴铺满，从 0 轴开始绘制图表

![image](https://user-images.githubusercontent.com/10857932/83848900-22fde980-a741-11ea-802a-5cbac2200fa5.png)

**Comment by paleface001** [comment]
```
  meta:{
    type:{
      range: [0,1]
    }
  },
```

**Comment by xiecg** [comment]
> ```
>   meta:{
>     type:{
>       range: [0,1]
>     }
>   },
> ```


为何这样的例子 https://codesandbox.io/s/broken-framework-2lwdx 配置会无效呢 ？

**Comment by sanshuiwang** [comment]
> > ```
> >   meta:{
> >     type:{
> >       range: [0,1]
> >     }
> >   },
> > ```
> 
> 为何这样的例子 https://codesandbox.io/s/broken-framework-2lwdx 配置会无效呢 ？

```
meta: {
    name: {
      range: [0, 1]
    }
  }
```

meta中的type不是，所谓固定的叫做type, 而是x轴对应的data中字段名：name。 （{ value: 2924, name: "东寰房地产开发" }）
