### ISSUE TITLE
Auto time scale with xAxis type 'dateTime'

### ISSUE THREAD

**Issue by oferitz** [antvis/G2Plot#1181]
**This is a feature request**

[Apex Charts](https://github.com/apexcharts/apexcharts.js) has a cool feature that auto scales xAxis with type `dateTime` according to the time range. 

Basically it detects the Min and Max date values and apply the format and number of ticks automatically. it even knows to display the overlap between days correctly as you can see in the last day example below.

I Wonder if it is possible to do that in G2Plot without me having to write complex formatter by myself.

Here are few examples:

**Last 15 min time range**
![last15min](https://user-images.githubusercontent.com/1668687/84369158-1b29c380-abdf-11ea-8b70-02c107e5e115.jpg)

**Last hour time range**
![lastHour](https://user-images.githubusercontent.com/1668687/84369186-254bc200-abdf-11ea-858e-0759472b21ab.jpg)

**Last day time range**
![lastDay](https://user-images.githubusercontent.com/1668687/84369210-2f6dc080-abdf-11ea-8a48-a883bca6679c.jpg)

**Last week time range**
![lastWeek](https://user-images.githubusercontent.com/1668687/84369229-372d6500-abdf-11ea-98a8-27ed10132674.jpg)

**Last month time range**
![lastMonth](https://user-images.githubusercontent.com/1668687/84369264-414f6380-abdf-11ea-9324-3d4767ab31c6.jpg)

As you can see it automatically changing the xAxis ticks and format according to the Data.

It Would be really nice to have something like that in G2Plot.

**Comment by hustcc** [comment]
@oferitz sorry for reply late. d3 time scale is excellent, which is what we need to improve.

But it takes a lot of time, you can use custom scale by `tickMethod` callback.

```ts
{
  // ...
  meta: {
    [xField]: {
      type: 'time',
      tickMethod: () => {}, // use your scale method for custom
    }
  }
}
```
