### ISSUE TITLE
折线图（line）情况下，在 设置 折线上的点 的前提下，    scrollbar 缩略轴无效。

### ISSUE THREAD

**Issue by MasonLSJ** [antvis/G2Plot#1183]
折线图（line）情况下，在 设置 折线上的点 的前提下，    scrollbar 缩略轴无效。
另外 interactions 的文档没有，type 类型只有 scrollbar 和 slider 吗？这块比较模糊
  point: {
        	visible: true,
          shape: 'circle',
          size: 3,
          style: {
              stroke: '#fff',
					}	
      },
      interactions: [
        {
          type: 'scrollbar',
          cfg: {
            start: 0.1,
            end: 0.2,
          },
        },
      ],

**Comment by hustcc** [comment]
试试目前最新的 v2，已经不存在这个问题了。
