### ISSUE TITLE
I think this is a typo in the tooltip config

### ISSUE THREAD

**Issue by jdbence** [antvis/G2Plot#1184]
Should this be changed to ```g2-tooltip``` since 4.x?
https://github.com/antvis/G2Plot/blob/48a9c55d6d86cf24a9f8cb2bbfbf83169d9e2ee9/src/interface/config.ts#L210

I can get it to work for now with ```any```
```JS
const tooltipStyle: Tooltip['domStyles'] = {
  'g2-tooltip': {
    opacity: 1
  },
} as any;
```

Similar issue https://github.com/antvis/G2/issues/2439

**Comment by yumanfeng** [comment]
+1
tooltip.domStyles
设置'g2-tooltop'无效
设置'g2-tooltip' ts 报错

**Comment by hustcc** [comment]
> +1
> tooltip.domStyles
> 设置 'g2-tooltop' 无效
> 设置 'g2-tooltip' ts 报错

类型定义的问题，已经修复了。使用 g2-tooltip
