### ISSUE TITLE
Bullet plot measureColors prop has no effect

### ISSUE THREAD

**Issue by alex-golubtsov** [antvis/G2Plot#1185]
Having this configuration
```js
{
 ...
  data: [
    {
      title: '满意度',
      measures: [83],
      targets: [90],
      ranges: [0, 0.6, 0.9, 1],
    },
  ],
  rangeMax: 100,
  measureColors: ['#FFB1AC']
 ...
}
```

I expect the color of the bar to be  `#FFB1AC`, but it is default one.

**_How to reproduce._**
In this sandbox https://codesandbox.io/s/pru25 just add `measureColors` prop

**Comment by arcsin1** [comment]
oops, Fix this bugs in V2!  If you're not in a hurry， looking forward to V2。
thanks!
