### ISSUE TITLE
散点图，在设置了坐标轴最大最小值后，散点显示不完整

### ISSUE THREAD

**Issue by GerilLeto** [antvis/G2Plot#1186]
<img width="664" alt="Screen Shot 2020-06-15 at 09 47 37" src="https://user-images.githubusercontent.com/6092647/84610836-9d233080-aeee-11ea-9774-b8c5dd779470.png">

在截图中：

- `xAxis.min = 0`
- `pointSize: 6`
- 左下角的绿色点是 `(0,0)`
- 最左边红色点 `(0.5, 2.3)`

此时绿色点和红色点都没有显示完整

试着搜了搜，大概是因为这一行：
https://github.com/antvis/G2Plot/blob/583335e94d5d4946f55c3c938181a4b54701b48a/src/base/view-layer.ts#L265

可否增加一个参数来自定义是否进行 `limitInPlot` ？

**Comment by hustcc** [comment]
不是因为这个，是因为图形没有参入到布局中。另外你设置了 min = 0，所以必然会出现这个问题，后面我们会修复成不设置 min max 的时候，图形参入布局，然后自动留出位置。

@lxfu1 @zqlu 录入到 G2 的开发中。
