### ISSUE TITLE
Line中smooth属性为true时，theme设置的颜色无效

### ISSUE THREAD

**Issue by inceptiongt** [antvis/G2Plot#1191]
如题：
![image](https://user-images.githubusercontent.com/20478779/84750519-f32acd80-afed-11ea-8af8-dc3fd7b0af49.png)
![image](https://user-images.githubusercontent.com/20478779/84750537-f756eb00-afed-11ea-9454-e1d690a48145.png)

**Comment by hustcc** [comment]
![image](https://user-images.githubusercontent.com/7856674/92604021-97b56680-f2e2-11ea-8603-d13d122d9694.png)


v2 已经自动解决这个问题，v1 暂时不处理。https://g2plot-v2-beta.antv.vision/zh/examples/tiny-line/basic#line-with-scale
