### ISSUE TITLE
哇，更新为啥都是毁灭性的啊……各种东西说丢就丢……

### ISSUE THREAD

**Issue by owops** [antvis/G2Plot#1192]
这次又丢了OverlappedComboPlot

**Comment by hustcc** [comment]
都没有见过 OverlappedComboPlot 这个 plot，即时是 v1 也没有的吧。

**Comment by owops** [comment]
麻烦看一下src/index.ts
line 19
export { default as OverlappedComboPlot, OverlappedComboPlotConfig } from './combo-plots/overlapped';


tag 1.0.4
当时用g2plot从文档中的混合组件中标注的就直接用的OverlappedComboPlot
