### ISSUE TITLE
bug: legend点击后offsetY失效

### ISSUE THREAD

**Issue by zkwolf** [antvis/G2Plot#1195]
g2plot version: 1.1.6

配置：

例如官网柱状图：https://g2plot.antv.vision/zh/examples/column/stacked#stackColumn

添加

`
legend: {
    position: 'bottom-center',
    offsetY: 10}`

后点击图例，图例会上移

**Comment by zhiyan** [comment]
遇到同样的问题, 感觉是初始时的offset要多于设置的offsetY, 点击后又变成了设置的值

**Comment by zkwolf** [comment]
> 遇到同样的问题, 感觉是初始时的offset要多于设置的offsetY, 点击后又变成了设置的值

我也觉得，就是初始化的时候比offsetY多了，然后点了变成设置的了

**Comment by zhiyan** [comment]
看来是g2的问题:
https://github.com/antvis/G2/issues/2621

**Comment by hustcc** [comment]
统一到这个 issue https://github.com/antvis/G2/issues/2621，这里先关闭了。
