### ISSUE TITLE
折线图-yAxis-grid-style  网格颜色

### ISSUE THREAD

**Issue by wjt1981** [antvis/G2Plot#1198]
折线图-yAxis-grid-style  无法改变网格颜色

**Comment by Chuyue0** [comment]
附议，我试了多个参数也没有更改成功

**Comment by LiLinhua** [comment]
@wjt1981 @Chuyue0 我试了多套一个line属性可以 yAxis-grid-line-style

**Comment by tenkiss258** [comment]
修复了嘛？我咋感觉这个他们这个团队压根不管这个呢？这个作品有点low。

**Comment by hustcc** [comment]
非常不好意思，v1 确实代码存在不少的问题，所以我这边接手在做 v2 版本，930 会发布正式版本。目前这个问题在 v2 中不存在问题。https://g2plot-v2-beta.antv.vision/zh/examples/line/basic

![image](https://user-images.githubusercontent.com/7856674/92604481-26c27e80-f2e3-11ea-9e9e-10ba0a589570.png)
