### ISSUE TITLE
图形颜色无法通过修改主题的defaultColor等颜色属性来重新指定

### ISSUE THREAD

**Issue by LiLinhua** [antvis/G2Plot#1199]
![{738158D4-FC43-4BF6-A48C-1AC511391F65}_20200618105406](https://user-images.githubusercontent.com/12910535/84972795-3605b600-b152-11ea-81d7-0198b79748f5.jpg)

**Comment by hustcc** [comment]
defaultColor 属性已经失效，文档中还没有同步删除。不好意思。
