### ISSUE TITLE
堆叠面积图展示有问题

### ISSUE THREAD

**Issue by Chuyue0** [antvis/G2Plot#1200]
如下图：两组数据间差值比较大，出现的位置为什么是一样的?
![image](https://user-images.githubusercontent.com/19585262/84990621-feaa0000-b177-11ea-9c0a-7845a116fa38.png)

**Comment by Gontte** [comment]
@Chuyue0 这个有解决办法吗

**Comment by hustcc** [comment]
@Gontte @Chuyue0 可以来一个数据，或者直接来一个 live demo 吗？

**Comment by Gontte** [comment]
@hustcc 大佬 看下这个例子 https://codesandbox.io/s/elegant-cookies-wzxc5

**Comment by hustcc** [comment]
因为是堆积面积，所以两个点的距离代表的是 56。

**Comment by Hsugar** [comment]
> 因为是堆积面积，所以两个点的距离代表的是 56。

 相差很大的两组数据在同一个点，而且趋势相同，大部分都觉得这是个bug.. 
 这个可以增加个配置项吗？折线图的效果就很正常

**Comment by hustcc** [comment]
isStack: false

默认是 true。
