### ISSUE TITLE
柱线混合图横坐标类型无法统一导致对不齐

### ISSUE THREAD

**Issue by gycsee** [antvis/G2Plot#1201]
修改横坐标数据格式为“YYYY-MM-DD”格式，则柱状图和折线图横坐标无法对齐，xAxis 的 type 应设置成什么才能取消自动识别
![image](https://user-images.githubusercontent.com/15338869/84991232-d5d63a80-b178-11ea-9190-67b752e0e406.png)
[codesandbox](https://codesandbox.io/s/brave-dream-jgsu0?file=/demo.tsx:286-305)

**Comment by hustcc** [comment]
```ts
meta: {
  [xField]: {
     type: 'cat',
 }
}
```
