### ISSUE TITLE
How to format the min and maxText on a Slider

### ISSUE THREAD

**Issue by bn3t** [antvis/G2Plot#1203]
My x axis is a time based axis with timestamps (number of milliseconds since January 1, 1970) and I need to format this value to show to the user. I succeeded to do it in most places but for the Slider I didn't find a way to do it.

<img width="416" alt="image" src="https://user-images.githubusercontent.com/1102723/85018868-2d22dd80-b16e-11ea-96d6-d9ab07bfdedc.png">

Thank you for your help.

**Comment by hustcc** [comment]
@zqlu 我们收录到 G2 需求中，930 前解决掉。
