### ISSUE TITLE
多折线，分组柱状等多个图表元素是否可以考虑设置多个Y轴字段

### ISSUE THREAD

**Issue by AREA-CQK** [antvis/G2Plot#1204]
现在用seriseField 区分，对sql查询的数据不太友好，并且想展示的是多个数据字段 而不是多个分组字段对应一个数据字段

**Comment by hustcc** [comment]
这种场景可以使用双轴图。

**Comment by SignDawn** [comment]
@hustcc  可以配置多轴图吗？
![image](https://user-images.githubusercontent.com/48878568/142595241-307af39e-8937-498d-8de4-bc0d6dc179d0.png)
