### ISSUE TITLE
饼图Pie图例legend.marker.symbol属性bug

### ISSUE THREAD

**Issue by LiLinhua** [antvis/G2Plot#1205]
饼图Pie图例legend-marker-symbol设置为triangleDown、cross、tick、plus、hyphen、line、hollowCircle、hollowSquare、hollowDiamond会有问题，有的会导致图形显示有问题，有的legend不能正常显示。
![image](https://user-images.githubusercontent.com/12910535/85101936-21025300-b236-11ea-9b84-56340f21910a.png)
![image](https://user-images.githubusercontent.com/12910535/85101966-324b5f80-b236-11ea-8f68-2d37e727c5f8.png)

**Comment by Me-Momo** [comment]
按照 issue 指引，给一个 codesandbox 地址

**Comment by Me-Momo** [comment]
ref: https://github.com/antvis/g/pull/689

**Comment by Me-Momo** [comment]
@hustcc  @zqlu  缺失的 symbol，要在 G2 层增加，还是增加一个 GUI，内置一些 marker，让用户按需引入？

相关文件地址：https://github.com/antvis/G2/blob/4432e0ed43249ff65e18884207b946bf6ac9c0bd/src%2Futil%2Flegend.ts#L10

**Comment by Me-Momo** [comment]
`triangleDown` 变更为 `triangle-down`,
`hollow-*` 不再支持
