### ISSUE TITLE
使用changeData更新数据，旧渲染层未清除

### ISSUE THREAD

**Issue by rayroad** [antvis/G2Plot#1206]
![image](https://user-images.githubusercontent.com/1949219/85104748-c23fd800-b23b-11ea-974b-15a44eafa484.png)
**G2Plot 版本** 1.1.7
**问题产生流程**
如图是一个百分比柱状图，初始为四个项目，使用changeData更新数据。
反复禁用、启用最后一条项目数据，第一次数据变更时，表现良好，第二次变更之后开始产生渲染残留，此问题不仅发生在柱状图，很多图表都有类似问题

**Comment by MZChangchun** [comment]
我用的是updateConfig  后面再加一个 render() 方法，会解决重复渲染问题；
