### ISSUE TITLE
词云图表数据没有全部渲染，鼠标 移上去才显示

### ISSUE THREAD

**Issue by Chuyue0** [antvis/G2Plot#1208]
https://antv-g2plot.gitee.io/zh/examples/word-cloud/basic
1.传入数据没有全部显示
2.信息提示框hover有问题，有时候能出现两个框
如下图：
![image](https://user-images.githubusercontent.com/19585262/85110150-05eb0f80-b245-11ea-9c0d-50cb37f69941.png)

**Comment by hustcc** [comment]
看看新版本 v2 的词云图是否存在这样的问题。

**Comment by Chuyue0** [comment]
> 看看新版本 v2 的词云图是否存在这样的问题。

我项目中引用的是v2版本，也会出现上面的情况，数据显示不全、tooltip框也有问题

**Comment by zhangzhonghe** [comment]
> > 看看新版本 v2 的词云图是否存在这样的问题。
> 
> 噢噢好的，做项目时引用的是v1版本，我看了v2还没发布？

已经发布了

**Comment by zhangzhonghe** [comment]
https://github.com/antvis/G2Plot/releases/tag/2.0.0

**Comment by Chuyue0** [comment]
> > > 看看新版本 v2 的词云图是否存在这样的问题。
> > 
> > 
> > 噢噢好的，做项目时引用的是v1版本，我看了v2还没发布？
> 
> 已经发布了

好的谢谢，我有空看了再来反馈
