### ISSUE TITLE
ColumnLine调用changeData时图形不更新

### ISSUE THREAD

**Issue by xiaotupansy** [antvis/G2Plot#1209]
调用方法为：
               changeData([a, a]);
也尝试过：
changeDataByIndex(a, 0)
changeDataByIndex(a, 1)

都不起作用

**Comment by xiaotupansy** [comment]
另外当柱线图全部数据都为0的时候，折线图会显示NaN
![image](https://user-images.githubusercontent.com/10205937/85112599-70ea1580-b248-11ea-993b-724d95c92c83.png)

**Comment by xiaotupansy** [comment]
ColumnLine不响应onColumnDblClick事件，但是会响应onColumnClick事件。
另外事件的示例代码，在官方文档库里面找不到，还需要到github来找，有些不方便。
以上版本皆为1.1.7

**Comment by XDino** [comment]
> 调用方法为：
> changeData([a, a]);
> 也尝试过：
> changeDataByIndex(a, 0)
> changeDataByIndex(a, 1)
> 
> 都不起作用

没 repaint() ？

**Comment by xiaotupansy** [comment]
@XDino 没有，我今天试了下调用repaint，也不起作用。
另外双击事件onColumnDblClick麻烦修复一下，其它事件都响应，就这个双击不响应

**Comment by xiaotupansy** [comment]
@XDino 你们能不能先解决下双击事件的问题啊，很闹心的。
柱线混合图中，onColumnClick这个事件会响应，
onColumnDblClick这个事件不会响应

**Comment by XDino** [comment]
> @XDino 你们能不能先解决下双击事件的问题啊，很闹心的。
> 柱线混合图中，onColumnClick这个事件会响应，
> onColumnDblClick这个事件不会响应

ummm……有点尬，我只是个路人🤣

**Comment by xiaotupansy** [comment]
@XDino 还以为你是项目组的，尴尬了。

**Comment by XDino** [comment]
> @XDino 还以为你是项目组的，尴尬了。

哈哈，找下官方吧😂

**Comment by aaa123123999** [comment]
我也遇到了 讲真感觉官方文档有点鸡肋 例子都没有。。。你可以使用updateConfig更新数据 然后在使用render渲染

**Comment by hustcc** [comment]
#1206
