### ISSUE TITLE
折线或者柱状图的X轴刻度长度默认是自动生成的，可以自定义吗

### ISSUE THREAD

**Issue by debugksir** [antvis/G2Plot#1211]

**Comment by hustcc** [comment]
![image](https://user-images.githubusercontent.com/7856674/92605757-ae5cbd00-f2e4-11ea-92c1-71c569260d91.png)

v2 中已经支持，v1 可以参考应该类似。https://g2plot-v2-beta.antv.vision/zh/examples/line/basic
