### ISSUE TITLE
Donut环图设置为svg渲染后控制台报错，标签线不显示

### ISSUE THREAD

**Issue by Chuyue0** [antvis/G2Plot#1213]
问题：
1.渲染方式更换为svg后，控制台报错如下图：
label 标签配置：
    label: {
                    type: "outer",
                    style: {
                        fontSize: 20,
                        stroke: ‘#f0f0f0’,
                        fill: ‘#f0f0f0’,
                        lineWidth: 1,
                    },
                    offsetY: 20,
                    offsetX: 8
                },
调试有无label都会报错，并且没有label线了。
![image](https://user-images.githubusercontent.com/19585262/85254286-76d33700-b492-11ea-8d1b-d14f85f274eb.png)

2.label指示线不显示

**Comment by Me-Momo** [comment]
不好意思，这个问题在 v2 中没有复现了；v1 不再修复
