### ISSUE TITLE
wordClound词云不能使用svg方式渲染！！

### ISSUE THREAD

**Issue by Chuyue0** [antvis/G2Plot#1214]
假的渲染方式....
配置了svg方式，页面上还是显示的canvas绘图
![image](https://user-images.githubusercontent.com/19585262/85256511-ef3bf700-b496-11ea-8daa-428ceeb889ff.png)
![image](https://user-images.githubusercontent.com/19585262/85256606-1bf00e80-b497-11ea-9d78-595256408e3e.png)

**Comment by hustcc** [comment]
是的，词云图直接使用 wordcloud2，社区实现。v2 中会解决这个问题。
另外，建议在文字比较多的时候，还是使用 canvas，性能会好一些。
