### ISSUE TITLE
希望分组柱+折线混合图表支持滚动轴

### ISSUE THREAD

**Issue by Jackeriss** [antvis/G2Plot#1217]
混合图表不需要缩略轴，但是滚动轴还是需要的。希望能够支持~

**Comment by Louhwz** [comment]
请问你配置过分组柱+折线混合图标的meta属性吗，在我这里配置不起作用，比如别名，比如formatter

**Comment by liuzhenying** [comment]
> 请问你配置过分组柱+折线混合图标的meta属性吗，在我这里配置不起作用，比如别名，比如formatter

@Louhwz Lou https://riddle.alibaba-inc.com/riddles/a2738a1b 看下 xAixs 是否能满足需求？

**Comment by liuzhenying** [comment]
> 混合图表不需要缩略轴，但是滚动轴还是需要的。希望能够支持~

好，新版本会重新考虑相关需求

**Comment by Louhwz** [comment]
> > 请问你配置过分组柱+折线混合图标的meta属性吗，在我这里配置不起作用，比如别名，比如formatter
> 
> @Louhwz Lou https://riddle.alibaba-inc.com/riddles/a2738a1b 看下 xAixs 是否能满足需求？

你好，我的需求是在分组柱+折线混合图中配置折线图的数值添加百分号，并且把原英文名转换成对应的中文名，xAxis并不能符合需求

**Comment by hustcc** [comment]
@liuzhenying v2 中支持之后，关闭这个 issue，v1 暂时不考虑支持 @Jackeriss @Louhwz  不好意思。

**Comment by liuzhenying** [comment]
v2 已 fix mate fommater 问题，滚动轴需求待整理，归档至 https://github.com/antvis/G2Plot/issues/1536
