### ISSUE TITLE
IE11中，SVG渲染模式看不到文字

### ISSUE THREAD

**Issue by 814632742** [antvis/G2Plot#1219]
使用IE11浏览器。SVG渲染模式看不到文字，可能通过添加polyfill修复？但不确定需要添加什么Polyfills特性。
期望：
![image](https://user-images.githubusercontent.com/48433798/85494189-c9376380-b60a-11ea-95a1-a076dd76ff00.png)

实际：
![image](https://user-images.githubusercontent.com/48433798/85493101-dbb09d80-b608-11ea-8980-38be9aa3634c.png)

**Comment by visiky** [comment]
这个会在新版本中解决
