### ISSUE TITLE
Canvas渲染模式在1080P，缩放125%的笔记本屏幕上显示模糊

### ISSUE THREAD

**Issue by 814632742** [antvis/G2Plot#1220]
Canvas渲染模式在1080P，缩放125%的笔记本屏幕上显示模糊。
期望：
![image](https://user-images.githubusercontent.com/48433798/85494420-377c2600-b60b-11ea-9ede-510d795e1dd1.png)

实际：
![image](https://user-images.githubusercontent.com/48433798/85493300-38ac5380-b609-11ea-8b50-c383ce7d3148.png)

**Comment by hustcc** [comment]
计算 scale +  devicePixelRatio 形成性的 devicePixelRatio，传入到 plot 中。
