### ISSUE TITLE
place tooltip at  (x,y) position without mouse hover

### ISSUE THREAD

**Issue by vaasu070** [antvis/G2Plot#1222]
Is it possible to place tool tip at any given position on a scatter plot with custom content without mouse hovering on plot?.

If yes then small example will be very helpful!

**Comment by hustcc** [comment]
大概的逻辑是找到 G2 的 view，然后调用 showTooltip(point); 代码大概为:

>  plot.layer[0].views[0].showTooltip({ x, y });
