### ISSUE TITLE
Issues linking charts

### ISSUE THREAD

**Issue by bravoeguizabal** [antvis/G2Plot#1225]
Hey guys!

Thanks for creating such a powerful library. It's by far the most complete out there.

I have been experimenting with linking two charts together making the slider interaction in a primary chart drive changes in a secondary. After trying different ways I have figured out a solution, sort of. The problem I'm facing now is that sometimes the secondary chart just doesn't visualize.

### This is what I'm doing
 I'm capturing and throttling  "slider:valuechanged" events on Primary then through the StateManager I'm triggering state changes that let Secondary present some accumulates reduced from the filtered data.

### This is what is failing
If I move the slider to a range where no values are shown and back the chart is not repainted and just the title is displayed.
The following image shows 4 snapshots of different app states

![image](https://user-images.githubusercontent.com/33873082/85883055-5666ed80-b7ae-11ea-829f-40421a41b502.png)

### The code
It's hosted in codesanbox and is located in https://codesandbox.io/s/magical-wozniak-o5g7d?file=/demo.js

Thanks for any ideas!

**Comment by hustcc** [comment]
see new version v2, fix it. https://g2plot.antv.vision/
