### ISSUE TITLE
dark 主题下 Legend 没有对齐

### ISSUE THREAD

**Issue by baizn** [antvis/G2Plot#1226]
设置 theme: 'dark' 时 legend 没有和坐标轴及 title 对齐，复现地址：https://g2plot.antv.vision/zh/examples/line/multiple#line-large-data，配置项中增加  theme: 'dark' 。
![image](https://user-images.githubusercontent.com/9443867/85936812-ad94cb80-b930-11ea-8a57-94614518a34a.png)

**Comment by hustcc** [comment]
| light  | dark   |
|---|---|
|  ![image](https://user-images.githubusercontent.com/7856674/94562075-761f1d80-0297-11eb-9f41-67e0f412fec0.png) |  ![image](https://user-images.githubusercontent.com/7856674/94562117-820adf80-0297-11eb-9b48-eae127e674f1.png)
 |
