### ISSUE TITLE
辅助线位置不对,wrong-guideline-position

### ISSUE THREAD

**Issue by Pxygogogo** [antvis/G2Plot#1234]
<img width="1654" alt="issue" src="https://user-images.githubusercontent.com/50876968/86121342-6f520480-bb08-11ea-8540-832a6d22219e.png">
现场还原：https://codesandbox.io/s/wrong-guideline-position-d752z?file=/src/App.js

**Comment by hustcc** [comment]
设置 y meta nice=true 即可。
