### ISSUE TITLE
图表设置缩略轴以后，backgroundStyle、forgroundStyle设置缩略轴背景样式没有效果

### ISSUE THREAD

**Issue by overcastsky** [antvis/G2Plot#1235]
<img width="2163" alt="截屏2020-06-30 下午8 06 11" src="https://user-images.githubusercontent.com/28147733/86124329-8cd59d00-bb0d-11ea-8022-eff5630ea5d6.png">

**Comment by hustcc** [comment]
请使用 v2，具体使用方式：

![image](https://user-images.githubusercontent.com/7856674/94561831-23ddfc80-0297-11eb-8435-6657a3dbe36b.png)
