### ISSUE TITLE
多次设置空数据之后，再设置数据，图没有渲染

### ISSUE THREAD

**Issue by kagawagao** [antvis/G2Plot#1236]
version: `v1.1.7`
demo: [![Edit happy-curran-3ft4c](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/happy-curran-3ft4c?fontsize=14&hidenavigation=1&theme=dark)

**Comment by kagawagao** [comment]
`v1.1.14` 还存在这个问题，有人解决吗 @paleface001

**Comment by hustcc** [comment]
建议迁 v2，无这个问题。
