### ISSUE TITLE
DualLine 双线图 tooltip 数据显示 bug

### ISSUE THREAD

**Issue by RuanXuSong** [antvis/G2Plot#1244]
当数据 data 只有1个值时，第一条折线的数据没有显示在 tooltip 上。

![issue1](https://user-images.githubusercontent.com/39564114/86231333-f9f83980-bbc4-11ea-997b-1184113e5c35.jpg)

我在官网示例的 data1 和 data2 中只保留一个数据，结果导致第一条折线的数据 value 在 tooltip 上没有显示。

期望：两条折线的数据都显示在 tooltip 上

**Comment by RuanXuSong** [comment]
目前最新版本（1.1.22及以上）tooltip会显示两个重复的数据，如图为官网实例
![image](https://user-images.githubusercontent.com/39564114/90306907-37f6b600-df04-11ea-9c3f-0e3702edff48.png)

**Comment by Una-Gao** [comment]
遇到同样问题 请问如何解决

**Comment by RuanXuSong** [comment]
> 遇到同样问题 请问如何解决

首先官网目前还是没有解决这个问题的，
解决方法：自己写一个tooltip，内容自定义，具体方法如下：
1.g2plot 版本用最新的（1.1.22及以上）否则拿不到最后一条数据
2.在tooltip.custom.customContent里写函数:
tooltip: {
                  custom: {
                    customContent: (title: string, dataArr: StoreValue[]) => {
                      // 目前版本 g2plot 会有多余项数据
                      const formattedData = dataArr.slice(0, -1);
                      const { x = 0, y = 0 } = dataArr[0] || {};
                      return `<div class="tooltip" style=" left: ${x}; top: ${y};">
                                <div class="g2-tooltip-title">${title}</div>
                                <ul class="g2-tooltip-list">
                                ${formattedData
                                  .map(
                                    item =>
                                      `<li class="g2-tooltip-list-item" data-index="" style="list-style-type: none; padding: 0px; margin: 12px 0px;">
                                    <span class="g2-tooltip-marker" style="background: ${item.color}; width: 8px; height: 8px; border-radius: 50%; display: inline-block; margin-right: 8px;"></span>
                                    <span class="g2-tooltip-name">${item.name}</span>:
                                    <span class="g2-tooltip-value" style="display: inline-block; float: right; margin-left: 30px;">${item.value}</span>
                                  </li>`,
                                  )
                                  .join('')}
                                </ul>
                            </div>`;
                    },
                  },
                },
3. 写全局样式：
.tooltip {
      position: absolute;
      display: block;
      z-index: 8;
      background-color: rgb(255, 255, 255);
      box-shadow: rgb(174, 174, 174) 0px 0px 10px;
      transition: all 0.4s ease-out;
      border-radius: 3px;
      color: rgb(89, 89, 89);
      font-size: 12px;
      line-height: 12px;
      padding: 0px 12px;
      opacity: 0.95;
      pointer-events: none;
    }
    .g2-tooltip-list {
      margin: 0px;
      list-style-type: none;
      padding: 0px;
    }
  }

**Comment by Una-Gao** [comment]
thx～

**Comment by hustcc** [comment]
V1 按照上述同学解决办法，v2 已经不存在这个问题。
