### ISSUE TITLE
Donut环图更新label.type渲染有点问题

### ISSUE THREAD

**Issue by ILovePing** [antvis/G2Plot#1252]
#### label.type 2秒后label从inner更新为outer， 显示有问题
![image](https://user-images.githubusercontent.com/13430709/86342844-bcf67a80-bc8a-11ea-9043-7190ce217976.png)

## 期望结果：
![image](https://user-images.githubusercontent.com/13430709/86342877-c8e23c80-bc8a-11ea-994d-6cce2488bca4.png)

## 复现repo:
https://codesandbox.io/s/vigilant-agnesi-to9y4?file=/index.js

**Comment by Me-Momo** [comment]
更新的时候，带上 offset 参数
```javascript
  donutPlot.updateConfig({
    ...config,
    label: {
      type: "outer",
      offset: 12
    }
  });
```
