### ISSUE TITLE
Dark theme Legend Labels Font Color in StackedColumnLine

### ISSUE THREAD

**Issue by Bumkeyy** [antvis/G2Plot#1254]
![image](https://user-images.githubusercontent.com/16663226/86423594-2faf3680-bd1b-11ea-8c1d-42f1f6ebc206.png)

Hi :)

It is similiar issue to #877 .
How can I adjust the font color of the legend in StackedColumnLine?

**Comment by hustcc** [comment]
感谢反馈，新版本 v2 中已经不存在这个问题，建议升级。

![image](https://user-images.githubusercontent.com/7856674/95545844-91292480-0a31-11eb-8d5d-2b78cf3e65f5.png)
