### ISSUE TITLE
环图、饼图如何实现鼠标移入块区域放大？

### ISSUE THREAD

**Issue by xiaofuliang** [antvis/G2Plot#1256]
环图、饼图现在块区域鼠标移上去如何放大，用了事件处理加线宽，
 e.target.attrs.lineWidth = 1; e.target.attrs.stroke='#000000'; 
感觉不明显。
![1](https://user-images.githubusercontent.com/23289722/86430963-1364c700-bd26-11ea-9e6a-431c409ba27a.png)

环图、饼图legend区域鼠标移入的事件，图区域对应的块放大等效果如何修改

**Comment by tenkiss258** [comment]
然并卵，我发现，没人管这里的bug

**Comment by hustcc** [comment]
这个能力，我们在 v2 提供吧。当前版本不太好扩展。

**Comment by Me-Momo** [comment]
可以参考 v2 的版本，在自己的业务代码中支持

**Comment by Me-Momo** [comment]
> 然并卵，我发现，没人管这里的bug

按照这个 demo 实现：https://codesandbox.io/s/g2plot-shixianshubiaoyirukuaiquyufangda-88vze?file=/index.js
