### ISSUE TITLE
【文档错误】Line - 折线图  xAxis.grid

### ISSUE THREAD

**Issue by yumanfeng** [antvis/G2Plot#1257]
Line - 折线图  xAxis.grid 内没有 style 属性，而是 line.style

文档：
![image](https://user-images.githubusercontent.com/13445900/86431815-5e7fd980-bd28-11ea-87b2-14501f441e81.png)

实际代码：
![image](https://user-images.githubusercontent.com/13445900/86431857-78212100-bd28-11ea-9cd7-edb60b109cba.png)

**Comment by hustcc** [comment]
非常仔细，有兴趣来提交 PR 嘛~
