### ISSUE TITLE
tooltip.domStyles 的配置希望更灵活

### ISSUE THREAD

**Issue by yumanfeng** [antvis/G2Plot#1262]
希望可以修改 'g2-tooltip-list-item' 的样式，目前可以配置，但是 ts 会报错

希望不同类别的 'g2-tooltip-marker' 可以设置不同的样式，效果如图：
![image](https://user-images.githubusercontent.com/13445900/86443495-ecb48980-bd41-11ea-889d-8d72959e4a01.png)

**Comment by hustcc** [comment]
没有太明白你的问题，ts 报错是什么？因为类型定义中没有允许 'g2-tooltip-list-item'  吗？

**Comment by yumanfeng** [comment]
> 没有太明白你的问题，ts 报错是什么？因为类型定义中没有允许 'g2-tooltip-list-item' 吗？

是的，类型定义中没有 'g2-tooltip-list-item'

**Comment by hustcc** [comment]
@yumanfeng 有兴趣来 PR 加上这个类型定义？

**Comment by yumanfeng** [comment]
> @yumanfeng 有兴趣来 PR 加上这个类型定义？

现在在用 G2，G2Plot 不太满足我们的业务场景，之后再用到 G2Plot 我再来提 PR 😁

**Comment by hustcc** [comment]
已经修复
