### ISSUE TITLE
DualLine 双折线图 rightConfig 不支持 tickInterval

### ISSUE THREAD

**Issue by RuanXuSong** [antvis/G2Plot#1263]
![bug](https://user-images.githubusercontent.com/39564114/86473136-ee4a7580-bd72-11ea-9fe1-221925e6a672.jpg)

如图，实测双折线图的 yAxis 的 rightConfig 不支持 tickInterval 和 tickCount，leftConfig 不支持 tickCount 属性。

另外：希望能提供一个类似 echarts 里的 minInterval 最小刻度的属性，使图表坐标轴可以支持刻度只显示整数（比如人数之类的），用到的场景应该比较多，希望可以加一下！

**Comment by hustcc** [comment]
![image](https://user-images.githubusercontent.com/7856674/87267576-abb73480-c4fa-11ea-936a-ab38f70a471b.png)

left 的 tickCount 可以生效的。感官上不生效的原因是因为计算算法要考虑 count + tick 文本的美观，所以不是一定等于 tickCount。

**Comment by RuanXuSong** [comment]
> ![image](https://user-images.githubusercontent.com/7856674/87267576-abb73480-c4fa-11ea-936a-ab38f70a471b.png)
> 
> left 的 tickCount 可以生效的。感官上不生效的原因是因为计算算法要考虑 count + tick 文本的美观，所以不是一定等于 tickCount。如果还有其他问题的话，方便提供一个 riddle 嘛？

我上面的问题主要是右轴  rightConfig 的 bug，右轴是 tickCount 和 tickInterval 都不会生效的，riddle是指什么呢？

**Comment by hustcc** [comment]
收到问题了，我们在新的 v2 版本修复吧。当然如果你感兴趣的话，可以参入进来 pr。

1. 增加 bugs 目录的单测
2. 修改代码，保证单测通过
3. 回归检测网站 demo 
4. pr

**Comment by RuanXuSong** [comment]
> 3\. 检测

好，还是希望能把 v1 里的 bug 也修一修，能参与当然是最好的。

**Comment by RuanXuSong** [comment]
> 收到问题了，我们在新的 v2 版本修复吧。当然如果你感兴趣的话，可以参入进来 pr。
> 
> 1. 增加 bugs 目录的单测
> 2. 修改代码，保证单测通过
> 3. 回归检测网站 demo
> 4. pr

好，还是希望能把 v1 里的 bug 也修一修，能参与当然是最好的。

**Comment by hustcc** [comment]
v1 中可以尝试在 meta 中设置 tickInterval，而不是在 yAxis 中
```ts

meta: {
   [yField]: {
     tickInterval: 5,
  },
}
```
