### ISSUE TITLE
Cannot read property 'component' of undefined

### ISSUE THREAD

**Issue by ntscshen** [antvis/G2Plot#1268]
问题：在切换 `xAxis.visible` 隐藏时，会提示 **Cannot read property 'component' of undefined**
![componentError1](https://user-images.githubusercontent.com/21041458/86886607-d20b5780-c129-11ea-824e-af0b1d4682eb.jpg)
![componentError2](https://user-images.githubusercontent.com/21041458/86886617-d6d00b80-c129-11ea-99a9-e237f044ee88.jpg)

**Comment by hustcc** [comment]
这个问题有没有兴趣来提一个 pr，应该是比较容易处理的一个问题。因为隐藏，所以导致 axis 找不到，增加一个 非空判断即可。

1. 增加 bugs 目录的单测
2. 修改代码，保证单测通过
3. 回归检测网站 demo 
4. pr
