### ISSUE TITLE
条形区间图瘫痪

### ISSUE THREAD

**Issue by tenkiss258** [antvis/G2Plot#1269]
![image](https://user-images.githubusercontent.com/23648420/86902864-1ce49980-c141-11ea-9d87-17e8def91aac.png)
不知道图片是否能显示，问题是这样，条形去见图，再加了interactions: [
      {
        type: 'scrollbar',
        cfg: {
          type: 'vertical'
        }
      }
    ],
后，最多只能配置12条数据，多一条都不行，立刻报错。难以理解，加竖向滚动条就是为了多显示几条，但是不支持。

**Comment by lxfu1** [comment]
先用一下 slider
