### ISSUE TITLE
环图bug

### ISSUE THREAD

**Issue by tenkiss258** [antvis/G2Plot#1270]
不知道图是否会显示，就是环图中间的数值，没办法格式化，如果有小数，可能会很长很长，he很长。想格式化都不可以。

**Comment by hustcc** [comment]
下面的配置，value 是对应的字段名。

```ts
meta: {
   value: {
       formatter: (v) => {}
   }
}
```

**Comment by Me-Momo** [comment]
> 下面的配置，value 是对应的字段名。
> 
> ```ts
> meta: {
>    value: {
>        formatter: (v) => {}
>    }
> }
> ```

这个配置不可用吗

**Comment by Me-Momo** [comment]
可以先通过这个方式实现：https://codesandbox.io/s/g2plot-huantuzidingyi-uxfru?file=/index.js；
后面直接进行 formatter 的方式，会在 v2 支持
