### ISSUE TITLE
【需求】能否在图例中增加一个默认选中或不选中的属性

### ISSUE THREAD

**Issue by hanguihe** [antvis/G2Plot#1271]
在一定需求下比如类别很多时，可以配置图例哪些字段默认选中或不选中

类似bizcharts的filter属性
https://bizcharts.net/product/bizcharts/category/7/page/24#filter

或者现在已经有这个功能但是文档或示例中都没找到🤣

**Comment by GreatPersonal** [comment]
我也需要这样的一个功能，或者可不可以把G2图例里面的selectMode继承过来

**Comment by hustcc** [comment]
这个会在 G2Plot v2，以及 G2 中做掉。

**Comment by hanguihe** [comment]
> 这个会在 G2Plot v2，以及 G2 中做掉。

会做一些提升大数据量性能提升的方面吗，目前感觉到六七千个数据点就有点卡顿了

另外可不可以再增加一些交互事件🤣

**Comment by hustcc** [comment]
> > 这个会在 G2Plot v2，以及 G2 中做掉。
> 
> 会做一些提升大数据量性能提升的方面吗，目前感觉到六七千个数据点就有点卡顿了
> 
> 另外可不可以再增加一些交互事件🤣

可以的。v2 的交互事件会非常丰富的，不会像 v1 一样做一些过滤筛选。对于性能，我们进行一个测试再看吧，毕竟性能优化是从底层做的，优先级上相对比 图表能力和体验 低一些。
