### ISSUE TITLE
折线图line的config配置图例触发ts报错

### ISSUE THREAD

**Issue by BluesVN** [antvis/G2Plot#1273]
![image](https://user-images.githubusercontent.com/27759401/87015569-2f71d800-c200-11ea-9b30-004d03011f72.png)
![image](https://user-images.githubusercontent.com/27759401/87015605-3862a980-c200-11ea-9961-ac437ba660f8.png)

    "@ant-design/charts": "^0.9.6",

**Comment by hustcc** [comment]
请升级到最新版本 1.0.0 版本。
