### ISSUE TITLE
标签文本->开启adjustPosition-> position:"right"失效

### ISSUE THREAD

**Issue by ntscshen** [antvis/G2Plot#1274]
问题：标签文本->开启adjustPosition-> position:"right"失效

![image](https://user-images.githubusercontent.com/21041458/87109467-55968700-c297-11ea-8085-f3ea0a18e7de.png)

![image](https://user-images.githubusercontent.com/21041458/87109386-19fbbd00-c297-11ea-954e-10ebca0b1a89.png)

**Comment by hustcc** [comment]
这个问题，我们在 v2 修复吧。

**Comment by zqlu** [comment]
参考 v2 中的配置 [https://g2plot.antv.vision/zh/examples/bar/stacked](https://g2plot.antv.vision/zh/examples/bar/stacked)

开启 `interval-adjust-position` 后会忽略 `position` 配置
