### ISSUE TITLE
Missing Meta alias and Tooltip formatter to Line of Combo chart

### ISSUE THREAD

**Issue by calebeaires** [antvis/G2Plot#1282]
**Feature request**
**Version:** 1.1.12
**Problem:** Line Tooltip and Meta properties does not work on this chart. Numbers and alias changing help user to understand more its data.

Obs.: look at comments

```javascript

import { ColumnLine } from '@antv/g2plot';

const uvData = [
  { time: '2019-03', value: 350 },
  { time: '2019-04', value: 900 },
  { time: '2019-05', value: 300 },
  { time: '2019-06', value: 450 },
  { time: '2019-07', value: 470 },
];

const transformData = [
  { time: '2019-03', count: 800 },
  { time: '2019-04', count: 600 },
  { time: '2019-05', count: 400 },
  { time: '2019-06', count: 380 },
  { time: '2019-07', count: 220 },
];

const columnLine = new ColumnLine(document.getElementById('container'), {
  title: {
    visible: true,
    text: 'Replicate line chart',
  },
  description: {
    visible: true,
    text: 'Line chart missing features',
  },
  data: [uvData, transformData],
  xField: 'time',
  yField: ['value', 'count'],
  meta: {
    time: {
      alias: 'Tempo'
    },
    count: { // <=== DOES NOT WORK
      alias: 'Contagem',
      formatter : (v) => {return v * 100} // <== does not work
    }
  },
  lineConfig: { // LINE-CONFIG does not has tooltip formatter
    label: {
      visible: true,
       formatter : (v, a) => {return v}
    }
  },
  tooltip: { // does not emit LINE formater
    formatter : (v, n, c) => {
      return {
        name: v,
        value: n
      }
    }
  }
});

columnLine.render();

```

**Comment by hustcc** [comment]
这个问题在 v2 版本中修复吧~

**Comment by calebeaires** [comment]
hey @hustcc. Thanks.
 Do you have some date this fix will be launch?

**Comment by hustcc** [comment]
@calebeaires 08-15, in the version 2, we will fix it, thanks~

**Comment by hustcc** [comment]
![image](https://user-images.githubusercontent.com/7856674/95547352-6771fc80-0a35-11eb-93ac-4a2f0ff88796.png)

**Comment by calebeaires** [comment]
Thanks. So glad to see it working. I will wait to new releases since the new version 2 does not have all charts from the version 1, like treemap.

**Comment by hustcc** [comment]
@calebeaires documents [here](https://www.yuque.com/antv/g2plot/ffgrfy#U9F3).

treemap will be release in 2020-12 , welcome to pr.

**Comment by calebeaires** [comment]
@hustcc I have tried to access the document (by the link above) but the page is out. I have just on more question that meets this issue: Is the Gauge MeterGauge on that list?
