### ISSUE TITLE
折线图添加数据点point，边界失效

### ISSUE THREAD

**Issue by ntscshen** [antvis/G2Plot#1289]
折线图-添加数据点point-在yAxis添加了(最大值、最小值时)，在x、y坐标轴轴线之外数据点会被切除

是否有必要在api层添加一个配置来支持，这种point在超出边界时被切掉的情况。

![image](https://user-images.githubusercontent.com/21041458/87419830-c2e34880-c606-11ea-8481-20b6115949f7.png)

**Comment by hustcc** [comment]
1. 上下 min max 配置的范围确实不正确。
2. 左右上，可以通过 meta: { date: { range: [0.05, 0.95] } }
