### ISSUE TITLE
迷你图表为什么不支持自适应容器

### ISSUE THREAD

**Issue by lany1721** [antvis/G2Plot#1295]
- [ ] I have searched the [issues](https://github.com/antvis/g2plot/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
迷你图表自适应容器

### What does the proposed API look like?
像普通图表一样增加forceFit属性

**Comment by hustcc** [comment]
感谢反馈~v2 中的 mini 图已经支持自适应容器，大概会在 08-15 发布 beta 版本。v1 版本暂不支持。

**Comment by DusuWen** [comment]
仪表盘也不支持
