### ISSUE TITLE
请问g2plot有稍微兼容一点IE的js包吗

### ISSUE THREAD

**Issue by MangGoDio** [antvis/G2Plot#1297]
- [ ] I have searched the [issues](https://github.com/antvis/g2plot/issues) of this repository and believe that this is not a duplicate.

### Steps to reproduce
在IE 11下调用会提示对象不支持find/includes 属性或方法

| Environment | Info |
|---|---|
| g2plot | 1.1.12 |
| System | windows 10 |
| Browser | IE 11 |

**Comment by hustcc** [comment]
在业务中加入 babel-polyfill 包。
