### ISSUE TITLE
After smooth is turned on, the legend.marker color is distorted

### ISSUE THREAD

**Issue by ntscshen** [antvis/G2Plot#1299]
- [ ] I have searched the [issues](https://github.com/antvis/g2plot/issues) of this repository and believe that this is not a duplicate.

> smooth开启后，图例legend.marker颜色失真

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/cranky-heisenberg-jt3s6?file=/index.js)

### Steps to reproduce
The official website stack area chart, based on the default configuration, add curve smoothing `smooth: true`
========= ========= ========= ========= ========= ========= ========= ========= ========= 
官网堆叠面积图，在默认配置基础上，新增曲线平滑 `smooth: true`

| Environment | Info |
|---|---|
| g2plot | 1.1.6 |
| System | macOS 10.15.3 |
| Browser |  Chrome 83.0.4103.116 |

**Comment by hustcc** [comment]
感谢反馈，最新版本 v2 中已经解决这个问题。
