### ISSUE TITLE
Vertically stacked column chart, setting the minimum value failed

### ISSUE THREAD

**Issue by ntscshen** [antvis/G2Plot#1300]
- [ ] I have searched the [issues](https://github.com/antvis/g2plot/issues) of this repository and believe that this is not a duplicate.

> 垂直堆叠柱形图，设置最小值失败

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/confident-chebyshev-bkuoz?file=/index.js)

### Steps to reproduce
设置最小值失败 `min: 100`
========= ========= ========= 
Failed to set minimum value `min: 100`

| Environment | Info |
|---|---|
| g2plot | 1.1.6 |
| System | macOS 10.15.3 |
| Browser | Chrome 83.0.4103.116 |

**Comment by ntscshen** [comment]
- [ ] 一个类似的问题是，当设置了最小值并打开了标签文本 `label.visible: true` 。

> 问题：标签文本内容小于设置的最小值时，标签文本将显示在x轴轴的外侧，在上面相同的地址中

========= ========= ========= ========= ========= ========= ========= ========= =========
A similar problem is when the minimum value is set and the label text `label.visible: true` is turned on.
Problem: When the label text content is less than the set minimum value, the label text will be displayed on the outside of the x-axis, in the same address above

**Comment by hustcc** [comment]
效果如图：![image](https://user-images.githubusercontent.com/7856674/90084418-dee22300-dd47-11ea-8010-0887a73a1fc4.png)

**Comment by zqlu** [comment]
可以设置label的类型为 column-auto（适用与基础柱形图）、stacked-column-auto（适用与堆积柱形图）：

https://codesandbox.io/s/sparkling-wood-24hov
