### ISSUE TITLE
Request: possible to have One-Axis to the combo column/line chart

### ISSUE THREAD

**Issue by calebeaires** [antvis/G2Plot#1302]
G2Plot: **Version: 1..1.12**
Chart Type: **Column/Line Chart**
Subject: **Feature request**
Request: **One Axis Combo Column/Line**, not only Dual-Axis

The current version let you create a chart with secondary axis to the Line plot; the so called Dual-Axis Combo Chart. This is good to make measures scale well on the canvas. 

Sometimes we need to visually give the user the importance of mesures by comparing the distance of the points. We can do this on a One-Axis combo chart.  **So would be great to have a way to set Column and Line on just one axis**. Like the example above:

| ProductType   |      Price     |  Cost |
|----------|:-------------:|------:|
| OneBase |  1200 | 1000 |
| TowBase |    1340   |   1250|
| ThreeBase| 1100 |    900 |

Here, the **column price** will scale on the same axis of the **line-cost,** this is be helpfully to understand the context or some business.

---
**Combo Dual-Axis (measure by axis)**
<img width="857" alt="Screen Shot 2020-07-18 at 19 13 07" src="https://user-images.githubusercontent.com/794195/87862855-e8d05c00-c92a-11ea-9938-c27578875917.png">

---
**Combo One-Axis to both measure**
<img width="845" alt="Screen Shot 2020-07-18 at 19 11 47" src="https://user-images.githubusercontent.com/794195/87862868-07365780-c92b-11ea-8362-d26e6c59f295.png">

**Comment by hustcc** [comment]
很好的建议，当度量的值范围一致的时候，用一个轴就够了。
我们在 v2 中考虑进去，v1 就不改动了。

**Comment by calebeaires** [comment]
@hustcc Good news!

Do we have some date to v2 launch?

**Comment by hustcc** [comment]
Will be released in 2020-9-30.
