### ISSUE TITLE
图表容器不支持设置背景色

### ISSUE THREAD

**Issue by wucs123** [antvis/G2Plot#1305]
图表容器不支持设置背景色，导出的图片是透明的，不希望是透明的图片，希望增加背景色

**Comment by hustcc** [comment]
@simaQ 这个我们加到 G2 的 feature 中吧，现在的 dark 模式就是在 dom 上设置背景黑色。

**Comment by Me-Momo** [comment]
@hustcc 看下 v1 升级 G2 版本是否可以？

**Comment by hustcc** [comment]
理论时可以的，自动升级最新 g2
