### ISSUE TITLE
Interval range histogram, after clicking the legend, the rendering position of the histogram is wrong.

### ISSUE THREAD

**Issue by ntscshen** [antvis/G2Plot#1307]
- [ ] I have searched the [issues](https://github.com/antvis/g2plot/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/elated-tesla-pwlvi?file=/index.js)

### Steps to reproduce
区间范围柱状图，开启图例并触发它，柱图渲染位置错误。

| Environment | Info |
|---|---|
| g2plot | 1.1.6 |
| System | macOS 10.15.3 |
| Browser | Chrome 83.0.4103.116 |

**Comment by arcsin1** [comment]
@lxfu1  看看v2现在的这个图有木有问题吧

**Comment by lxfu1** [comment]
> @lxfu1 看看v2现在的这个图有木有问题吧

Single Interval needn't  legend.
