### ISSUE TITLE
环形图 Donut 中间的统计数值有精确度bug

### ISSUE THREAD

**Issue by arcsin1** [antvis/G2Plot#1312]
- [x] I have searched the [issues](https://github.com/antvis/g2plot/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/practical-hertz-47tpu?file=/index.js:9-14)

### Steps to reproduce
直接可以看demo 只要出现小数点value就会精度有问题

| Environment | Info |
|---|---|
| g2plot | 1.1.13 |
| System | mac |
| Browser | 谷歌84 |

**Comment by arcsin1** [comment]
而且还没有format方式： 
![image](https://user-images.githubusercontent.com/13724222/88029010-fd4f6700-cb6b-11ea-8262-d8919faa5647.png)

**Comment by arcsin1** [comment]
https://github.com/antvis/G2Plot/blob/master/src/plots/donut/component/ring-statistic.ts
![image](https://user-images.githubusercontent.com/13724222/88029976-418f3700-cb6d-11ea-9d03-b7def5b9b744.png)
https://github.com/antvis/G2Plot/blob/724a277de6af9e6ffa6556e4fb8a8ed34c4519a1/src/plots/donut/component/ring-statistic.ts#L81
![image](https://user-images.githubusercontent.com/13724222/88029989-46ec8180-cb6d-11ea-9e0e-267715ccf399.png)
这个地方 你们能加个format之类的吗

**Comment by Me-Momo** [comment]
可以先用这个方式支持，文档上还没提供
```javascript
    htmlContent: (item, value) => {
      return `<div>
        <div>${item.name}</div>
        <div>${Math.floor(item.value)}</div>
      </div>`
    }
```

**Comment by Yellowang** [comment]
现在还是有这个问题...
