### ISSUE TITLE
饼图changeData 后label残留

### ISSUE THREAD

**Issue by gehaijun** [antvis/G2Plot#1324]
- [ ] I have searched the [issues](https://github.com/antvis/g2plot/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/naughty-austin-d4on1?file=/index.js)

### Steps to reproduce
g2官方饼图示例中changeData后label可以正确渲染，
![image](https://user-images.githubusercontent.com/35563401/88245991-ac568480-cccb-11ea-8e1d-bd066a26a222.png)

g2plot 在changeData后label还是上次data的数据。
![image](https://user-images.githubusercontent.com/35563401/88246018-c5f7cc00-cccb-11ea-8310-a51f043c373a.png)

| Environment | Info |
|---|---|
| g2plot | 1.1.14 |
| System | windows 10 |
| Browser | Chrome x64 84.0.4147.89 |

**Comment by Me-Momo** [comment]
最新的 beta 版本这个问题解决了

**Comment by Me-Momo** [comment]
```
之前的设计：changeData 之后，需要手动调用一次 render
```

**Comment by puppetsheep** [comment]
手动再调用一次render之后，会重复渲染新的饼图

**Comment by Me-Momo** [comment]
这个问题 v1 不修了；2.0 版本后续会修复这个问题
