### ISSUE TITLE
Pie 图表数据展示错误

### ISSUE THREAD

**Issue by kagawagao** [antvis/G2Plot#1325]
https://github.com/antvis/G2Plot/blob/604dccd98d58e22fd3748f4d37574f174a29fe67/src/plots/pie/layer.ts#L145-L156

主要有以下问题

- 第一次渲染数据全为空时，第二次正常数据，调用 `changeData` 之后，`label` 显示为 `null`，因为 `formatter` 在第一次渲染时被设置为 `formatter: () => 'null'`，而第二次没有被重置 [demo](https://codesandbox.io/s/exciting-elgamal-1ic4l?fontsize=14&hidenavigation=1&theme=dark)
- 当数据全为 `null` 或者 `0`，实际不应该渲染，应该为空白图

因此，这里的额外处理其实没有必要

**Comment by SSSpin** [comment]
啥时候能解决呀

**Comment by Me-Momo** [comment]
> 啥时候能解决呀

这个周末

**Comment by kagawagao** [comment]
> > 啥时候能解决呀
> 
> 这个周末

如果是移除这部分处理代码的话，我可以提 PR

**Comment by Me-Momo** [comment]
> > > 啥时候能解决呀
> > 
> > 
> > 这个周末
> 
> 如果是移除这部分处理代码的话，我可以提 PR

暂时不移除，这是解决数据全空的时候，展示错误的问题；需要看下其他解决方案

**Comment by kagawagao** [comment]
@Me-Momo 麻烦发布一个 patch 吧
