### ISSUE TITLE
辅助线报错

### ISSUE THREAD

**Issue by tenkiss258** [antvis/G2Plot#1332]
辅助线bug。react版本，柱状图没办法使用辅助线，一使用辅助线就报莫名其妙的错误一大堆。在官网给的测试模块没问题。就是react版本有问题。为什么这么多瘫痪的bug,蚂蚁不应该这么渣呀。

**Comment by tenkiss258** [comment]
附图

**Comment by tenkiss258** [comment]
![1595580836(1)](https://user-images.githubusercontent.com/23648420/88376011-36d3dc80-cdcf-11ea-9a99-8702f09a92c4.jpg)
重新附图

**Comment by tenkiss258** [comment]
我心目中的蚂蚁呀，给我树立个强大的巨人榜样吧。

**Comment by lxfu1** [comment]
提供一下复现地址或数据，检测下是不是依赖了第三方包引起的。
