### ISSUE TITLE
柱状图slider，如何设置start和end来实现展示数据的条数

### ISSUE THREAD

**Issue by overcastsky** [antvis/G2Plot#1341]
- [ ] I have searched the [issues](https://github.com/antvis/g2plot/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
目前的slider设置的start和end值，好像是根据滚动条的整体长度，如果需求是默认展示数据的前10条，那么就没法计算出对应的end的百分比

### What does the proposed API look like?
希望新增一个方法可以实现上述的功能，根据数据的长度来设置

**Comment by hustcc** [comment]
https://github.com/antvis/G2Plot/issues/1342
