### ISSUE TITLE
柱状图slider，如何设置start和end来控制展示数据的条数

### ISSUE THREAD

**Issue by overcastsky** [antvis/G2Plot#1342]
目前的slider设置的start和end值，好像是根据滚动条的整体长度，如果需求是默认展示数据的前10条，那么就没法计算出对应的end的百分比

**Comment by hustcc** [comment]
暂时不支持。但是可以通过总 x 数据量和你要显示的数据量，计算出这个 start end 的 0-1 的值。大概如下：

- start = 0
- end = showCount/totalCount

**Comment by overcastsky** [comment]
后续会增加这种功能吗
