### ISSUE TITLE
禁用组件的配置项很怪

### ISSUE THREAD

**Issue by elaine1234** [antvis/g2plot#135]
如果要禁用 tooltip，那么 g2plot 是
```js
tooltip: {
  visible: false
}
```
看看其他图表库：
- echarts: `tooltip: false`
- highcharts: `tooltip: false`
- ...

为什么要在这种大家都觉得约定俗成的配置项上做创新？本身这个配置项就够长了，我写个禁用还要占个三行这是什么毛病

**Comment by paleface001** [comment]
@weepy3641  @Leannechn
