### ISSUE TITLE
`yAxis.max` `yAxis.min` 类型错误会触发浏览器崩溃

### ISSUE THREAD

**Issue by Airkro** [antvis/G2Plot#1353]
- [x] I have searched the [issues](https://github.com/antvis/g2plot/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/g2plot-reproduction-template-mnw4o?file=/src/index.js)

### Steps to reproduce
将任意图表的 `yAxis.max` 设为非数字的值，例如 `{}` `"123"`

| Environment | Info |
|---|---|
| g2plot | 1.1.15 |
| System | Windows 10 |
| Browser | 谷歌浏览器84 |

**Comment by hustcc** [comment]
已经 pr 修复，等待发包解决。
