### ISSUE TITLE
g2plot多折线图设置xAxis的tickInterval会引起浏览器崩溃

### ISSUE THREAD

**Issue by jardeng** [antvis/G2Plot#1362]
- [ ] I have searched the [issues](https://github.com/antvis/g2plot/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://antv-g2plot.gitee.io/zh/examples/line/multiple](https://antv-g2plot.gitee.io/zh/examples/line/multiple)

### Steps to reproduce
在代码演示右侧代码区域添加配置：xAxis: { tickInterval: 1000 },

| Environment | Info |
|---|---|
| g2plot | 1.1.16 |
| System | Win10-64 |
| Browser | Google Chrome 85.0.4181.9 |

**Comment by hustcc** [comment]
这个的原因是 x 轴是日期字段， tickInterval 的单位是毫秒，设置 tickInterval: 1000 的时候，导致 tick label 有十万级别的数量，然后画布绘制卡住了。

建议对于 x 轴日期字段，不要设置 tickInterval，或者设置更大的 tickInterval。
