### ISSUE TITLE
可否在基础面积图中增加多维数据的显示，g2是支持的

### ISSUE THREAD

**Issue by libaofeng** [antvis/G2Plot#1369]
- [ ] I have searched the [issues](https://github.com/antvis/g2plot/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
解决了多维数据通过面积图的方式进行直观对比，同时有写额外需求比如截取面积图中间某一段时操作比较方面

### What does the proposed API look like?
同目前api

**Comment by hustcc** [comment]
具体是参考哪个 G2 demo？

**Comment by libaofeng** [comment]
http://antv-2018.alipay.com/zh-cn/g2/3.x/demo/area/area-null.html




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "antvis/G2Plot"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月30日(星期四) 晚上6:39
收件人:&nbsp;"antvis/G2Plot"<G2Plot@noreply.github.com&gt;;
抄送:&nbsp;"那一年的风"<402228304@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [antvis/G2Plot] 可否在基础面积图中增加多维数据的显示，g2是支持的 (#1369)





 
具体是参考哪个 G2 demo？

**Comment by hustcc** [comment]
现在的面积图应该也是支持的啊 https://g2plot.antv.vision/zh/examples/gallery#category-%E5%A0%86%E5%8F%A0%E9%9D%A2%E7%A7%AF%E5%9B%BE

**Comment by libaofeng** [comment]
这个是堆叠面积图，y轴方向数据时叠加在一起显示的。而我指的是非堆叠的情况下实现多维数据的显示




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "antvis/G2Plot"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月30日(星期四) 晚上9:09
收件人:&nbsp;"antvis/G2Plot"<G2Plot@noreply.github.com&gt;;
抄送:&nbsp;"那一年的风"<402228304@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [antvis/G2Plot] 可否在基础面积图中增加多维数据的显示，g2是支持的 (#1369)





 
现在的面积图应该也是支持的啊 https://g2plot.antv.vision/zh/examples/gallery#category-%E5%A0%86%E5%8F%A0%E9%9D%A2%E7%A7%AF%E5%9B%BE

**Comment by hustcc** [comment]
> 这个是堆叠面积图，y轴方向数据时叠加在一起显示的。而我指的是非堆叠的情况下实现多维数据的显示
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "antvis/G2Plot" <notifications@github.com&gt;; 发送时间:&nbsp;2020年7月30日(星期四) 晚上9:09 收件人:&nbsp;"antvis/G2Plot"<G2Plot@noreply.github.com&gt;; 抄送:&nbsp;"那一年的风"<402228304@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题:&nbsp;Re: [antvis/G2Plot] 可否在基础面积图中增加多维数据的显示，g2是支持的 (#1369) 现在的面积图应该也是支持的啊 https://g2plot.antv.vision/zh/examples/gallery#category-%E5%A0%86%E5%8F%A0%E9%9D%A2%E7%A7%AF%E5%9B%BE — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

可以使用 Line，然后 lineStyle 中设置 fill 样式即可。
