### ISSUE TITLE
G2Plot v2 正在激情开发中，欢迎前来指导...

### ISSUE THREAD

**Issue by hustcc** [antvis/G2Plot#1384]
> 分支地址： https://github.com/antvis/G2Plot
> 文档地址：https://www.yuque.com/antv/g2plot

### 目标

v2 版本主要的目的在于：

1. 简化代码逻辑，让用户**实现更简单，贡献更简单，维护更简单**
2. 确定完全基于 G2 4.0 开发，**让体验优化的成果沉到底层**，惠及更多用户

### 怎么贡献？

目前所有开发、排期、分工文档均[在语雀中](https://www.yuque.com/antv/g2plot/ffgrfy#U9F3)。你可以：

1. 看分工表格，挑选一个你感兴趣的图形（也可以回复添加一个新的可视化图形，只要是通用即可）
2. 加群获得 1v1 帮助，帮你了解如果开发这样的图形，难点，重点在哪里
3. 开发和 Code Review
4. 文档、demo、网站
5. 官网图表开发者署名

更具体的新人贡献手册，[点这里](https://www.yuque.com/antv/g2plot/apubgw)。

### 常见问题

1. 为什么 v1 一年就出 v2？

> 架构演进不看时间，不看 kpi，只看是否必要。大版本迭代不是问题，问题是一直不出版本；或者出的版本无法解决现有问题。

2. 我贡献能收获什么？

> - 1 对 1 G2 可视化入门指导，基本入门可视化底层，以后业务中可视化自帮自助；
> -  从开发到上线，开源流程一整套；
> -  官网图表开发者署名，装比!
> - BI 数据领域经验免费交流。

3. 开发一个新可视化图表需要多久？

> 我们期望的新架构就是非常简单的包装 G2，不提高开发者门槛。所以大概时间：
> - 配置确定 2d
> - 开发图表 2d
> - CR 1d
> - 文档、demo、网站 3d

> 平均总计 8d 左右，不要求完全全职投入，中途退出也没关系，我们接锅即可。

4. 为什么要拉社区同学来干活？

> - 互利共赢
> - 了解开发者怎么用 AntV 的

----

**有任何意向欢迎在 issue 留言，或者语雀文档留言。** 或者 issue 回复，我拉你进 **核心开发群**。或者加入用户群：

![image](https://user-images.githubusercontent.com/7856674/97307198-5f6de580-189a-11eb-9099-5385976f2b27.jpeg)

**Comment by zhangzhonghe** [comment]
我想参加

**Comment by cxk0831** [comment]
撸起袖子准备

**Comment by Me-Momo** [comment]
有任何问题，可以随时私聊我

**Comment by hanguihe** [comment]
希望在性能上有一些提升~ 目前几千条数据就有些卡顿了

**Comment by Yuppiezero** [comment]
离开了jquery的时代，这饼图的逻辑也变了，基数变成了自动计算了，难道不应该有个指定的基数的功能么？
如果新访客数想和总访客数比如何比？

新访客数2 总访客数10 按照现在的逻辑 [{ type: '新访客'，value: 2 }, { type: '总访客'，value: 10 }]

结果是2:10 总和12

那要显示 总数10 ？？要怎么办？？

[{ type: '新访客'，value: 2 }, { type: '总访客'，value: 10 -2 }] ？？

在饼图上的提示会显示总访客 8？达不到想要的结果

逻辑 应该是 第一个参数 比 基数 第二个参数 比 基数 第三个参数 比 基数

而不是 第一个参数 加 第二个参数 加 第三个参数 的参数相加的总值作为基数

这样起码可以应对更多的情况 希望能够加一个对比的 基数值

**Comment by yech1990** [comment]
+1

**Comment by hustcc** [comment]
> +1

有兴趣参入某个图形的开发嘛？如果有兴趣的话，告知一下钉钉，我拉你进群^_^

**Comment by yech1990** [comment]
> > +1
> 
> 有兴趣参入某个图形的开发嘛？如果有兴趣的话，告知一下钉钉，我拉你进群^_^

sent by email...

**Comment by hustcc** [comment]
> > > +1
> 
> > 
> 
> > 有兴趣参入某个图形的开发嘛？如果有兴趣的话，告知一下钉钉，我拉你进群^_^
> 
> 
> 
> sent by email...

加我微信吧，好像没有收到邮件。

**Comment by Yuppiezero** [comment]
真的不好意思，现在一个人一整套sass 在全盘开发，时间抽不开……



在 2020-09-11 18:47:10，"hustcc" <notifications@github.com> 写道：

+1

有兴趣参入某个图形的开发嘛？如果有兴趣的话，告知一下钉钉，我拉你进群^_^

**Comment by wengjq** [comment]
G2Plot 支持微信小程序吗？

**Comment by huangdaman** [comment]
请问现在版本支持vue3吗

**Comment by hustcc** [comment]
> 请问现在版本支持vue3吗

没有限定技术栈，可以封装一个 vue3的 的版本，开源出来，如果质量好，我们官网收录一下。

如果没有时间封装，看看官网收录的有没有 vue3 的。

**Comment by hustcc** [comment]
> G2Plot 支持微信小程序吗？

还不支持，可以尝试来 pr。

**Comment by PathFun** [comment]
transform 放大缩小形变都支持吗

**Comment by Me-Momo** [comment]
> transform 放大缩小形变都支持吗

答疑问题，可以单独提 issue 提问哈

**Comment by Eve-Sama** [comment]
钉钉群满了诶
