### ISSUE TITLE
【需求】轴类图表数据为空时不渲染轴

### ISSUE THREAD

**Issue by yuruwang** [antvis/G2Plot#1385]
**需求场景**
业务上希望在没有数据的时候仍然能看到轴类图表（如折线图、雷达图）的轴及其上面的ticks。

**当前状况**
在meta中配置了轴的values，但是当data为空数组的时候，轴也不会渲染。出现这种情况的有雷达图、折线图、面积图等等带有轴的图表。
虽然每种图表都有对应的workaround，但是处理方式五花八门并不统一。

**需求**
只要meta中配置了轴的values数据，在data为空或空数组的时候，仍然能正常渲染轴及其他相关图形

**Comment by hustcc** [comment]
> 只要meta中配置了轴的values数据，在data为空或空数组的时候，仍然能正常

可以看下你具体的代码吗？

对于连续数据，设置 meta 字段的 min max，对于 分类字段，设置 values。
