### ISSUE TITLE
[官网指导]:部分API官网指引过时

### ISSUE THREAD

**Issue by Qiuhang817385** [antvis/G2Plot#1387]
https://g2plot.antv.vision/zh/docs/manual/getting-started
最后的Demo , 关于Y轴label显示的修改API-formatter函数 ,已经过时了 , 应该是在label对象下 , 希望及时更新 , 支持!

**Comment by hustcc** [comment]
![image](https://user-images.githubusercontent.com/7856674/89241906-c3359900-d632-11ea-9441-17e017e12cd9.png)

是生效的啊，你这边用的是什么版本？G2Plot v2 的 formatter 是在 yAxis.label 下面，但是 v2 还没有发版本呢。
