### ISSUE TITLE
js相加精度问题（ 环图、瀑布图 ）

### ISSUE THREAD

**Issue by ntscshen** [antvis/G2Plot#1388]
- [ ] I have searched the [issues](https://github.com/antvis/g2plot/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/condescending-hoover-ydbw7?file=/index.js)

### Steps to reproduce
这些精度问题可以通过formatter做一层转换（ label、tooltip... ），不过在g2plot代码层做处理最好哈。

| Environment | Info |
|---|---|
| g2plot | 1.1.19 |
| System | 10.15.3 |
| Browser | 84.0.4147.105 |

**Comment by hustcc** [comment]
类似的问题，可以看看这里的解答：https://github.com/antvis/G2/issues/2720
