### ISSUE TITLE
tooltip功能API错误指向了坐标轴

### ISSUE THREAD

**Issue by jiwenqiang1996** [antvis/G2Plot#1392]
- [ ] I have searched the [issues](https://github.com/antvis/g2plot/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://g2plot.antv.vision/zh/examples/general/tooltip/API](https://g2plot.antv.vision/zh/examples/general/tooltip/API)

### Steps to reproduce
选中提示信息，再选择API，打开的是坐标轴的API而不是tooltip的API

| Environment | Info |
|---|---|
| g2plot | 1.1.19 |
| System | - |
| Browser | - |

**Comment by hustcc** [comment]
@BBSQQ @lxfu1 帮忙看看这个文档指向问题。
