### ISSUE TITLE
图表container宽度高度较小时，图表渲染异常

### ISSUE THREAD

**Issue by yuruwang** [antvis/G2Plot#1393]
把图表的container的宽度和高度设置得比较小，如50px，图表会渲染异常，渲染成镜像的样子。

正常渲染：
![image](https://user-images.githubusercontent.com/31492974/89276320-18df6500-d676-11ea-8015-ead483856f73.png)

宽度设置为50：
![image](https://user-images.githubusercontent.com/31492974/89276359-2563bd80-d676-11ea-89e8-89f3693c8761.png)

online demo: https://codesandbox.io/s/bitter-pine-lk08l

**Comment by hustcc** [comment]
期望是什么样子？
