### ISSUE TITLE
[BUG]配置了autoHide:false 并没有生效

### ISSUE THREAD

**Issue by yuruwang** [antvis/G2Plot#1399]
在xAixs.label配置了autoHide:false并没有生效，在xAixs配置tickCount后才生效

online demo: https://codesandbox.io/s/lucid-jang-qyum2?file=/demo.tsx

**Comment by hustcc** [comment]
设置：

```ts
"nice": true,
```

否则 tickCount 设置了不一定就一定等于 tickCount，这个算法导致的。
