### ISSUE TITLE
G2Plot的MeterGauge控件设置rangeStyle{lineWidth:1}无效

### ISSUE THREAD

**Issue by qinshaoxu** [antvis/G2Plot#1402]
1，G2Plot的MeterGauge控件设置rangeStyle{lineWidth:1}无效
2，Ant Design Charts的MeterGauge控件设置rangeStyle{lineWidth:1}无效
也就是不能改变linewidth

**Comment by hustcc** [comment]
是的，无法修改。😭  并且这个图在 v2 中都汇总到 gauge 了。
