### ISSUE TITLE
基础条形图转化率显示NaN%

### ISSUE THREAD

**Issue by einsqing** [antvis/G2Plot#1403]
- [ ] I have searched the [issues](https://github.com/antvis/g2plot/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/cocky-grass-0mqk2)

### Steps to reproduce
```
import { Bar } from '@antv/g2plot';

const data = [
  { action: '浏览网站', pv: 50000 },
  { action: '放入购物车', pv: 35000 },
  { action: '生成订单', pv: 25000 },
  { action: '支付订单', pv: 15000 },
  { action: '完成交易', pv: 8500 },
];

const barPlot = new Bar(document.getElementById('container'), {
  "title": {
		"visible": true,
		"text": "用户运营全景图"
	},
	"data": [{
		"步骤": "获客-注册",
		"人数": 15
	}, {
		"步骤": "留存-登录",
		"人数": 20
	}, {
		"步骤": "激活-分销",
		"人数": 4
	}, {
		"步骤": "激活-任务宝",
		"人数": 4
	}],
	"xField": "人数",
	"yField": "步骤",
	"conversionTag": {
		"visible": true
	}
});

barPlot.render();

```

![image](https://user-images.githubusercontent.com/7685948/89602542-8b7c5a80-d899-11ea-8241-821ae6ba6449.png)

| Environment | Info |
|---|---|
| g2plot | 1.1.21 |
| System | - |
| Browser | - |

**Comment by zqlu** [comment]
duplicate to #1478
