### ISSUE TITLE
柱状图格式化数据显示出错

### ISSUE THREAD

**Issue by banboluli** [antvis/G2Plot#1404]
![image](https://user-images.githubusercontent.com/20417790/89602820-26753480-d89a-11ea-8628-4b106b05e718.png)
当数据为金额，需要格式化时（数据类型就不是number），图表就会变成这种情况，请问有什么好的解决办法么

**Comment by hustcc** [comment]
sales 使用数字类型传入 chart，然后在：

```ts
const options = {
  // ... 
  sales: {
     formatter: (v) => 'xxx', // 格式化
  }
}
```
