### ISSUE TITLE
数据点最大值没有达到下一个grid时，grid不会渲染

### ISSUE THREAD

**Issue by yuruwang** [antvis/G2Plot#1414]
描述：在轴类图表中，当数据的最大值还没有达到下一个grid的数值时，下一个grid就不会渲染了，但是在很多场景下这样看起来像是数据渲染超出了图表，视觉上很不友好：
![image](https://user-images.githubusercontent.com/31492974/89849020-3488c500-dbba-11ea-97f7-7e63a034b461.png)
![image](https://user-images.githubusercontent.com/31492974/89848996-26d33f80-dbba-11ea-9795-1b538e91dc35.png)

需求：希望图表能自动渲染出数据最大值所在的下一个grid和tick

**Comment by yuruwang** [comment]
online demo: https://codesandbox.io/s/condescending-bartik-mx1it

**Comment by hustcc** [comment]
配置一下：

```ts
{
  meta: {
    [yField]: {
        nice: false,
    }
  }
}
```
