### ISSUE TITLE
日历图title堆叠bug

### ISSUE THREAD

**Issue by ArranZeyuWang** [antvis/G2Plot#1420]
- [x] I have searched the [issues](https://github.com/antvis/g2plot/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://g2plot.antv.vision/zh/examples/calendar/basic](https://g2plot.antv.vision/zh/examples/calendar/basic)

### Steps to reproduce
demo展示直接出现错误，如图

![image](https://user-images.githubusercontent.com/31071085/89873430-ff499a80-dbec-11ea-9d44-6bff49b60249.png)

| Environment | Info |
|---|---|
| g2plot | 1.1.23 |
| System | - |
| Browser | - |

---
Fix:
      padding: 'auto',
=>
      padding: '0',
可以临时解决问题

什么原因呢？

**Comment by hustcc** [comment]
布局定位上有问题。可以先写死 padding

```ts
      padding: [30, 20, 30, 30],
```
