### ISSUE TITLE
双轴图（DualLine）不支持“多折线（seriesField）”

### ISSUE THREAD

**Issue by qiaolei1973** [antvis/G2Plot#1425]
如题，不知道是不是我使用的姿势有问题，DualLine 的中文名叫做“双折线混合图表”，意思就是不支持双轴多折线么？我看 Line 似乎也没有支持多 view 的能力。是否我只能降级到 g2 上去实现？
期望效果：
![image](https://user-images.githubusercontent.com/20394320/89981766-092fd400-dca7-11ea-9e49-0bd44a6abe51.png)

**Comment by liuzhenying** [comment]
目前是只支持双轴单折线，我们的新版本 g2 plot 会增加对双轴多折线的支持

**Comment by qiaolei1973** [comment]
那新版本的发布时期大概是啥时候？
还有这样的话如果排期等不及我要降级到 g2 了吧？

**Comment by liuzhenying** [comment]
> 那新版本的发布时期大概是啥时候？
大概八九月份。

> 还有这样的话如果排期等不及我要降级到 g2 了吧？
是的

**Comment by liuzhenying** [comment]
或者可以 review 下设计？因为在我看来，双轴图使用多折线，可能会造成表意上的不清晰。
btw 柱线混合图的线都是支持多折线的
