### ISSUE TITLE
Donut 在数据项只有一项时，调用changeData更新数据图表不刷新

### ISSUE THREAD

**Issue by mingtianyihou33** [antvis/G2Plot#1426]
- [ ] I have searched the [issues](https://github.com/antvis/g2plot/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/romantic-wilbur-h5woi?file=/index.js)

### Steps to reproduce
1.只有一个数据项。 2.渲染后，改变数据项的值，然后调用changeData，即可复现

| Environment | Info |
|---|---|
| g2plot | 1.1.23 |
| System | - |
| Browser | - |

---
期望结果：显示最新的值，而不是首次渲染的值

**Comment by Me-Momo** [comment]
目前 changeData 都需要手动 调用 `plot.render()` 才能重新渲染；不管是一条数据还是两条

**Comment by mingtianyihou33** [comment]
多条数据，我试了是可以的
