### ISSUE TITLE
折线图xField的值为number时，数据点和tick没有对齐

### ISSUE THREAD

**Issue by yuruwang** [antvis/G2Plot#1428]
在折线图中，当xField的值是number类型时，数据点和tick会偏离。当把xField的值转换成string后就解决了
问题截图：
![image](https://user-images.githubusercontent.com/31492974/90117404-7451d700-dd89-11ea-8b58-fcd0ad344676.png)

online demo: https://codesandbox.io/s/exciting-swirles-phqwt

**Comment by hustcc** [comment]
增加一下配置：

```ts
meta: {
    year: {
      type: 'cat',
    }
  }
```
