### ISSUE TITLE
子弹图中的legend无法显示

### ISSUE THREAD

**Issue by 1002527441** [antvis/G2Plot#1442]
![image](https://user-images.githubusercontent.com/53967483/90256113-ccff9d80-de77-11ea-978b-6db5cc0e8dcd.png)

https://g2plot.antv.vision/zh/examples/bullet/basic#overflow
在示例中，就没有看见legend显示。

**Comment by Me-Momo** [comment]
子弹图图例需要自定义

**Comment by Me-Momo** [comment]
子弹图图例需要自定义

**Comment by 1002527441** [comment]
是自定义的，还是无法显示.

**Comment by 1002527441** [comment]
是自定义的，还是无法显示.

**Comment by Me-Momo** [comment]
> 是自定义的，还是无法显示.

设置 legend position 为 top 的时候，可以看到图例，应该是默认位置为 bottom 的时候，布局问题导致隐藏了；确实是一个 bug，看下怎么处理好

**Comment by Me-Momo** [comment]
```
  legend: {
    custom: true,
    offsetY: -20,
    position: 'bottom',
    // ...
}
```

可以先这么处理下；后续的问题在 v2 中解决
