### ISSUE TITLE
折线图辅助线计算有问题

### ISSUE THREAD

**Issue by xiecg** [antvis/G2Plot#1444]
50% 的位置，柱图的表现是 30， 折线似乎是 27

![image](https://user-images.githubusercontent.com/10857932/90351235-4531b300-e072-11ea-8672-30065a74304a.png)

https://codesandbox.io/s/holy-moon-347go?file=/index.js

**Comment by lxfu1** [comment]
这个是正常的， 你最大值是 54 。  可以设置 yAxis: { max: 60 }
