### ISSUE TITLE
文档可以添加一些animation和markerPoints相关的介绍吗

### ISSUE THREAD

**Issue by cnyballk** [antvis/G2Plot#1449]
在搜索中搜索关键词没有搜到
![image](https://user-images.githubusercontent.com/25214319/90377429-91004e80-e0aa-11ea-966e-5ddeaa5ffd16.png)

![image](https://user-images.githubusercontent.com/25214319/90377484-9fe70100-e0aa-11ea-80e4-63ba3dd75e3f.png)

**Comment by Me-Momo** [comment]
markerPoint: https://g2plot.antv.vision/en/examples/line/marker/API
