### ISSUE TITLE
使用clipingWithData遇到的问题

### ISSUE THREAD

**Issue by cnyballk** [antvis/G2Plot#1450]
animation: {
    appear: {
      animation: 'clipingWithData',
    },
  },
使用这个的时候在开始动画的瞬间有个小bug
![image](https://user-images.githubusercontent.com/25214319/90379368-3c120780-e0ad-11ea-9561-6e630ab9f35f.png)

**Comment by hustcc** [comment]
这个临时特性已经在 v2 中移除，后面我们在时序图中统一考虑这个特性。如果你在使用 v1，建议你不要使用这个特性。

**Comment by CNFeffery** [comment]
@hustcc 请问目前版本中如何使用类似之前`clipingWithData`的动画效果
