### ISSUE TITLE
环形进度条update方法不起作用

### ISSUE THREAD

**Issue by nasmet** [antvis/G2Plot#1451]
用的库https://unpkg.com/@antv/g2plot@1.1.11/dist/g2plot.js，示例代码   
const ringProgressPlot = new G2Plot.RingProgress(main, {
            width: 105,
            height: 105,
            percent: 0.8,
            color: ['blue', '#dedede'],
 });   
 ringProgressPlot.render();
 setTimeout(()=>{
     ringProgressPlot.update(0.5);
 }, 200);

**Comment by hustcc** [comment]
```ts
update({ percent: 0.5 })
```
