### ISSUE TITLE
多组雷达图 tooltip formatter后的数据重复

### ISSUE THREAD

**Issue by xiecg** [antvis/G2Plot#1453]
基础雷达图没有问题，多组雷达图能复现。

![image](https://user-images.githubusercontent.com/10857932/90463072-a7ef8100-e13c-11ea-9768-fe1954dd416f.png)

https://codesandbox.io/s/lucid-darwin-u114f?file=/index.js

**Comment by hustcc** [comment]
看看 v2 新版本的雷达图是否存在这个问题。 https://g2plot.antv.vision/zh/examples/radar/basic#series
