### ISSUE TITLE
分组柱+折线混合图中折线图tooltip无法格式化

### ISSUE THREAD

**Issue by Louhwz** [antvis/G2Plot#1459]
> > 请问你配置过分组柱+折线混合图标的meta属性吗，在我这里配置不起作用，比如别名，比如formatter
> 
> @Louhwz Lou https://riddle.alibaba-inc.com/riddles/a2738a1b 看下 xAixs 是否能满足需求？

在分组柱+折线混合图中，我发现当我想通过meta属性配置小数=>百分数的格式化转化时（如0.05=>5%），此配置可以在折线图的y轴上体现，但是无法在tooltip中体现。当我想直接配置tooltip属性的时候，我使用formatter发现，每次折线图传入的第三个参数都是undefined，这很显然是个bug，希望可以尽快修复

_Originally posted by @Louhwz in https://github.com/antvis/G2Plot/issues/1217#issuecomment-674065521_

**Comment by liuzhenying** [comment]
不是 bug，因为折线图只有两个数据项，以链接里的数据为例，折线图的数据源是 [{ time: '2019-03', count: 800 }],则参数的值分别是 time，count
分组柱，则分别是 time，value，type

**Comment by SeasonSu** [comment]
源码太乱，不支持，已经自己改源码
