### ISSUE TITLE
chart生命周期事件不触发

### ISSUE THREAD

**Issue by cong876** [antvis/G2Plot#1462]
chart生命周期事件afterrender等不会触发，click等dom事件能正常触发。是个bug么，还是目前就是不支持生命周期函数。
如果不支持的话，想在渲染后做一些事要怎么处理

![image](https://user-images.githubusercontent.com/13564730/90588350-ff115680-e20d-11ea-8024-a79df9ca9d7d.png)

**Comment by lxfu1** [comment]
events: {
    afterrender: ()=>{
      console.log(123)
    }
  }
