### ISSUE TITLE
折线图 guideLine 位置不对

### ISSUE THREAD

**Issue by JackFGreen** [antvis/G2Plot#1469]
复现：https://codesandbox.io/s/g2plot-line-guideline-clf91?file=/index.js

![image](https://user-images.githubusercontent.com/23187848/90713601-47954680-e2d8-11ea-931f-98d3330a5909.png)

**Comment by hustcc** [comment]
我们会子啊 2.0 版本中修复，现在可以先添加如下配置，绕过问题：

```ts
  meta: {
    value: {
      nice: false,
    }
  },
```
