### ISSUE TITLE
GroupedColumn 轴距可以设置嘛

### ISSUE THREAD

**Issue by ClenLu** [antvis/G2Plot#1472]
轴距可以设置嘛

**Comment by hustcc** [comment]
增加配置：

```ts
  theme: {
    columnWidthRatio: 1/4, // 0 ~ 1，默认是 1/3
  }
```

**Comment by ClenLu** [comment]
@hustcc theme 的文档哪里看的  找半天找不到。。。。。。

**Comment by hustcc** [comment]
> @hustcc theme 的文档哪里看的 找半天找不到。。。。。。

Theme 是一个大的 obejct，确实没有文档， 可以暂时直接看代码中的 theme 结构吧。这个我们会在 v2 发布的时候补充 theme 的文档。 @lxfu1
