### ISSUE TITLE
柱状图转化率组件计算bug

### ISSUE THREAD

**Issue by ppxu** [antvis/G2Plot#1478]
![image](https://user-images.githubusercontent.com/1119778/90850224-ad023980-e3a3-11ea-8ccd-df3f9d0f4eee.png)
如图，当柱图值相同时，转化率组件中的 getScaleByField 方法会对值去重，导致计算转化率的时候拿不到对应的值

**Comment by zqlu** [comment]
- [ ] v2 中转化率组件将在 G2 中实现提供

**Comment by zqlu** [comment]
v2 中已经修复
