### ISSUE TITLE
pie changeData function bug

### ISSUE THREAD

**Issue by SignYx** [antvis/G2Plot#1481]
TypeError: Cannot read property 'getCenter' of undefined
PieInnerLabel.push../node_modules/@antv/g2plot/esm/plots/pie/component/label/base-label.js.PieBaseLabel.getCoordinate
node_modules/@antv/g2plot/esm/plots/pie/component/label/base-label.js:232
  229 | };
  230 | PieBaseLabel.prototype.getCoordinate = function () {
  231 |     var coordinate = this.getGeometry().coordinate;
> 232 |     var center = coordinate.getCenter();
      | ^  233 |     // @ts-ignore
  234 |     var radius = coordinate.getRadius();
  235 |     var startAngle = coordinate.startAngle;

**Comment by Me-Momo** [comment]
please provide a demo of issue~

**Comment by hustcc** [comment]
use updateConfig instead of changeData.

```ts
plot.updateConfig({ data })
```
