### ISSUE TITLE
非连续时间的 X 轴呈现不完整

### ISSUE THREAD

**Issue by xiecg** [antvis/G2Plot#1484]
https://codesandbox.io/s/fragrant-frost-k5eqi

希望的效果如下图:

![image](https://user-images.githubusercontent.com/10857932/90998496-d2d34c80-e5f6-11ea-9be5-c7af4f61e450.png)

**Comment by hustcc** [comment]
x 轴自动识别的日期字段，手动指定为分类即可，如下：

```ts
  meta: {
    name: {
      type: 'cat',
    },
  },
```
