### ISSUE TITLE
updateConfig 失效

### ISSUE THREAD

**Issue by catherinezhxj** [antvis/G2Plot#1485]
updateConfig 函数使用后，图形渲染出错
前提：forceFit 已经设置为 false
测试[https://g2plot.antv.vision/zh/examples/bar/basic](url)，添加以下代码段
` setTimeout(()=>{
  barPlot.updateConfig({
    width: 500,
  })
},2000)`

**Comment by hustcc** [comment]
```ts
setTimeout(()=>{
  barPlot.updateConfig({ width: 500 });
  barPlot.render()
},2000);
```
