### ISSUE TITLE
legend 文字长度设置

### ISSUE THREAD

**Issue by ClenLu** [antvis/G2Plot#1493]
legend 文字长度超过一定范围默认显示省略号， 有时候需要全部显示 没找到宽度或者文字长度的设置项

**Comment by ClenLu** [comment]
@hustcc

**Comment by catherinezhxj** [comment]
我也有相同的问题...
新版的 g2 Legend 图例新增 maxItemWidth 属性，超出自动省略
希望 g2Plot 能开放相应配置...
（省略号的问题，现在已经有点影响到正常使用了，或者有没有能暂时解决这个问题的方法）

**Comment by wuzhixian2016** [comment]
> 我也有相同的问题...
> 新版的 g2 Legend 图例新增 maxItemWidth 属性，超出自动省略
> 希望 g2Plot 能开放相应配置...
> （省略号的问题，现在已经有点影响到正常使用了，或者有没有能暂时解决这个问题的方法）

我是暂时设为false，legend在外面自己用html写了

**Comment by hustcc** [comment]
> 我也有相同的问题...
> 新版的 g2 Legend 图例新增 maxItemWidth 属性，超出自动省略
> 希望 g2Plot 能开放相应配置...
> （省略号的问题，现在已经有点影响到正常使用了，或者有没有能暂时解决这个问题的方法）

v1 中没有暴露 g2 的全量能力和配置，**在 v2 中已经全量暴露**。v1 暂时不维护了，非常不好意思，带来不便。https://g2plot-v2-beta.antv.vision/zh/examples/line/multiple#line-large-data
