### ISSUE TITLE
双轴折线图右Y轴想设置min和max

### ISSUE THREAD

**Issue by totemtec** [antvis/G2Plot#1496]
目前只能给双轴一起设置min和max
一个图里分别显示血糖和体重，体重的数值都比较大，最后看起来成了横线了

**Comment by liuzhenying** [comment]
是的，yAxis 的 min max 只能一起设置。或者可以尝试不设置min，max，让双轴图自适应。
2.0 版本将新增单独设置 min，max 的功能，该版本正在开发中。

**Comment by totemtec** [comment]
我正在使用2.0beta2，没看到有这个功能

**Comment by liuzhenying** [comment]
直接在 yaxis 中使用即可，用法同普通 yAxis 相同，例如
```
yAxis: [{
      min: 0,
      max: 10,
  }, {
      min: 0,
      max: 10000
  }]
```
beta2中双轴图还未经过内测，请谨慎使用

**Comment by crazyair** [comment]
> 直接在 yaxis 中使用即可，用法同普通 yAxis 相同，例如
> 
> ```
> yAxis: [{
>       min: 0,
>       max: 10,
>   }, {
>       min: 0,
>       max: 10000
>   }]
> ```
> 
> beta2中双轴图还未经过内测，请谨慎使用
https://github.com/antvis/G2Plot/issues/2736 现在这个自动的有问题，会超出
