### ISSUE TITLE
饼图设置innerRadius无效

### ISSUE THREAD

**Issue by Me-Momo** [antvis/g2plot#15]
试运行 `torch --compile --interactive ./__tests__/unit/pie.spec2.js`
执行结果如下图，内半径设置无效
![image](https://user-images.githubusercontent.com/15646325/63939452-e8706d80-ca99-11e9-81fe-ade319f6d2e5.png)

**Comment by Me-Momo** [comment]
这个问题似乎还没有解决耶

**Comment by hustcc** [comment]
@aa1011372655

**Comment by aa1011372655** [comment]
@Me-Momo 是否为强需求，因为innerRadius这个参数有新的图形ring去实现了,与@paleface001沟通过，如果是你们的强需求，可以兼容一下不暴露
