### ISSUE TITLE
labelRenderer.get('items') 获取的label数量和原始data数量不一致

### ISSUE THREAD

**Issue by Me-Momo** [antvis/G2Plot#150]
```
 /** 获取数据标签的renderer实例 */
  protected _getDataLabel(): Label | null {
    const labelController = this._getElement().get('labelController');
    return labelController.labelsContainer ? labelController.labelsContainer.get('labelsRenderer') : null;
  }

// 获取标签点
  private _getLabelItems(): TextType[] {
    const labelsRenderer = this._getDataLabel();
    const labelItems = labelsRenderer.get('items');
    return labelItems;
  }
```

 结果
`labelItems.length !== data.length`
![image](https://user-images.githubusercontent.com/15646325/67741714-0be17580-fa55-11e9-9fe6-205ff2f714ae.png)

**Comment by hustcc** [comment]
可以看看能不能搞一个复现的例子，比如在 riddle 上。

**Comment by Me-Momo** [comment]
暂时没办法在单测上还原

**Comment by Me-Momo** [comment]
这个问题是G2内的问题
![image](https://user-images.githubusercontent.com/15646325/68913133-49ecd200-0795-11ea-8049-f85ccc3d5e57.png)

为什么有66个points，返回的labelItems才29个（导致上层获取不到所有的data label）

**Comment by paleface001** [comment]
看起来像是g2的逻辑默认过滤掉了，待我排查一下
