### ISSUE TITLE
环图 changeData 后 label 标签文本没有更新

### ISSUE THREAD

**Issue by xiecg** [antvis/G2Plot#1503]
![image](https://user-images.githubusercontent.com/10857932/91675315-7039fd80-eb6e-11ea-9801-b070d31618bd.png)

https://stackblitz.com/edit/react-58azmk?file=index.js

**Comment by Me-Momo** [comment]
1.x 版本的changeData 有点问题，需要手动调用下 plot.render 重新渲染

**Comment by xiecg** [comment]
可是重新 render 图例会被重复渲染

![image](https://user-images.githubusercontent.com/10857932/91676224-b5136380-eb71-11ea-8b3e-49732ad56c56.png)

**Comment by Me-Momo** [comment]
> 可是重新 render 图例会被重复渲染
> 
> ![image](https://user-images.githubusercontent.com/10857932/91676224-b5136380-eb71-11ea-8b3e-49732ad56c56.png)
看 codesank 好像没有这个问题，可以提供一个复现图例覆盖的case么

**Comment by xiecg** [comment]
https://stackblitz.com/edit/react-58azmk-trrqr8

@Me-Momo

**Comment by Me-Momo** [comment]
这个问题v1不解决了，v2中直接更新options.data即可
