### ISSUE TITLE
双轴图排序的问题

### ISSUE THREAD

**Issue by xiecg** [antvis/G2Plot#1506]
这是柱图数据排序后的截图，没有问题，这是希望的效果。

![image](https://user-images.githubusercontent.com/10857932/91679276-69b18300-eb7a-11ea-8b46-1cf40cc0d1ca.png)

这里是折线图排序的截图，会发现 X 轴的排序依然是按照柱图数据来的。似乎现在 `xField: 'time' ` 指定的是柱图的 time ，做折线图的排序这显然不合理，所以想请问这种情况有什么好的解决办法？

![image](https://user-images.githubusercontent.com/10857932/91679028-b0eb4400-eb79-11ea-84a0-bdf3a344a674.png)

https://stackblitz.com/edit/react-sbdjbp?file=index.js

**Comment by hustcc** [comment]
liuzhenying 看看 v2 中是否存在同样的问题。

@xiecg 你目前是怎么控制排序的？使用 meta 配置 x 字段的 values 试试看。

**Comment by xiecg** [comment]
@hustcc 感谢，用 values 可以实现想要的效果。
