### ISSUE TITLE
饼图的逻辑BUG

### ISSUE THREAD

**Issue by Yuppiezero** [antvis/G2Plot#1510]
离开了jquery的时代，这饼图的逻辑也变了，基数变成了自动计算了，难道不应该有个指定的基数的功能么？
如果新访客数想和总访客数比如何比？

新访客数2   总访客数10 按照现在的逻辑 [{ type: '新访客'，value: 2 }, { type: '总访客'，value: 10 }]

结果是2:10 总和12  

那要显示 总数10 ？？要怎么办？？ 

[{ type: '新访客'，value: 2 }, { type: '总访客'，value: 10 -2 }]  ？？ 

在饼图上的提示会显示总访客 8？达不到想要的结果

逻辑 应该是  第一个参数 比 基数   第二个参数 比 基数   第三个参数 比 基数

而不是 第一个参数 加 第二个参数  加 第三个参数 的参数相加的总值作为基数

这样起码可以应对更多的情况 希望能够加一个对比的 基数值

**Comment by hustcc** [comment]
新访客 和 总访客 不是一个维度上的，对比有什么意义？饼图是看一个维度上不同维值下的指标占比。

建议你这个场景将数据处理为：

```ts
新访客：2
老访客：8
```

可以看看各种记录网站用户信息的三方工具，他们是怎么去用饼图展现这些数据的。

----

> 另外，不知道这跟 jquery 有什么关系，那个时代的饼图是指定总数的？
