### ISSUE TITLE
饼图的逻辑BUG 问题

### ISSUE THREAD

**Issue by Yuppiezero** [antvis/G2Plot#1511]
离开了jquery的时代，这饼图的逻辑也变了，基数变成了自动计算了，难道不应该有个指定的基数的功能么？
如果新访客数想和总访客数比如何比？

新访客数2 总访客数10 按照现在的逻辑 [{ type: '新访客'，value: 2 }, { type: '总访客'，value: 10 }]

结果是2:10 总和12

那要显示 总数10 ？？要怎么办？？

[{ type: '新访客'，value: 2 }, { type: '总访客'，value: 10 -2 }] ？？

在饼图上的提示会显示总访客 8？达不到想要的结果

逻辑 应该是 第一个参数 比 基数 第二个参数 比 基数 第三个参数 比 基数

而不是 第一个参数 加 第二个参数 加 第三个参数 的参数相加的总值作为基数

这样起码可以应对更多的情况 希望能够加一个对比的 基数值

**Comment by hustcc** [comment]
#1510

**Comment by Me-Momo** [comment]
没有了解到juery的可视化饼图为什么是你这个逻辑，要不你再往更钱前一点的可视化时代看看😬

**Comment by Yuppiezero** [comment]
> 没有了解到juery的可视化饼图为什么是你这个逻辑，要不你再往更钱前一点的可视化时代看看😬

其实你并没有理解我再说什么， 饼图其实是有三部分的 但是 现在来说 第一部分抽象画了并不能直接展示
![110](https://user-images.githubusercontent.com/29559767/91792481-27ef0e00-ec48-11ea-8f40-085e0dfc3e9d.png)

**Comment by Yuppiezero** [comment]
![110](https://user-images.githubusercontent.com/29559767/91792503-3a694780-ec48-11ea-9ec7-009d958b3519.png)
