### ISSUE TITLE
饼图图例过多的处理，如图所示，建议分页。

### ISSUE THREAD

**Issue by CHEN-DONG** [antvis/G2Plot#1514]
![image](https://user-images.githubusercontent.com/21303026/91927886-36532d80-ed0d-11ea-969f-d001430f935a.png)

**Comment by CHEN-DONG** [comment]
图表会被压缩的很小

**Comment by Me-Momo** [comment]
> 图表会被压缩的很小

现在图例不可以开启分页吗？试一下：
```
legend: {
    flipPage: true
 }
```

**Comment by CHEN-DONG** [comment]
额

> > 图表会被压缩的很小
> 
> 现在图例不可以开启分页吗？试一下：
> 
> ```
> legend: {
>     flipPage: true
>  }
> ```

额 文档上没有 我还以为不支持呢

**Comment by Me-Momo** [comment]
好的～ 文档补充下；谢谢反馈
