### ISSUE TITLE
分组柱状图中，单组内的每个柱状的间隔要怎么控制？

### ISSUE THREAD

**Issue by mu1004** [antvis/G2Plot#1515]
分组柱状图中，单组内的每个柱状的间隔要怎么控制？

由于我应用的比较特殊，每个分组的子key不一样，导致每组内柱间的间隔较大

比如：
const columnPlot = new GroupedColumn(document.getElementById('container'), {
  forceFit: true,
    data: [
      {major: "其他问题", minor: "用例不在配置的范围中", value: 24},
      {major: "其他问题", minor: "因多态策略计算后无需执行（不在测试范围的用例）", value: 100},
      {major: "其他问题", minor: "任务被终止", value: 32},
      {major: "其他问题", minor: "任务运维错误", value: 42},
      {major: "工具问题", minor: "AGENT工具问题", value: 5},
      {major: "工具问题", minor: "EiCo工具问题", value: 87},
      {major: "工具问题", minor: "ITC工具问题", value: 57},
      {major: "工具问题", minor: "公司基础工具问题", value: 11},
      {major: "工具问题2", minor: "AGENT工具问题", value: 5},
      {major: "工具问题2", minor: "EiCo工具问题", value: 87},
      {major: "工具问题2", minor: "ITC工具问题", value: 57},
      {major: "工具问题2", minor: "公司基础工具问题", value: 11},
      {major: "工具问题4", minor: "AGENT工具问题", value: 5},
      {major: "工具问题4", minor: "EiCo工具问题", value: 87},
      {major: "工具问题4", minor: "ITC工具问题", value: 57},
      {major: "工具问题4", minor: "公司基础工具问题", value: 11},
    ],
    xField: 'major',
    yField: 'value',
    // yAxis: {
    //   min: 0,
    // },
    label: {
      visible: true,
    },
    groupField: 'minor',
});

**Comment by zqlu** [comment]
在 v2 中是使用 `marginRatio` 配置控制
