### ISSUE TITLE
文件名的命名规则

### ISSUE THREAD

**Issue by hustcc** [antvis/g2plot#152]
是否保证一个命名规则，规则大概为：

 - 全小写
 - 如果多个单词的，用 `-` 分割

例如：

 - plot
 - base-interaction

如果可以的话， 看到一个改一个，逐步改掉吧~

**Comment by Me-Momo** [comment]
还有label那一系列也是，如出现`stackBar-label`, `spiderLabel`, `areaLabel`这系列？具体规则也定一下？大概为:
-  `描述-label`
-  其中`描述`使用驼峰

例如:

- stackBar-label
- area-label
- spider-label

有其他建议的话，再修改

**Comment by hustcc** [comment]
stackBar-label --> stack-bar-label

**Comment by zqlu** [comment]
这样呢：1)普通文件名驼峰，2)class类文件(一个文件一个class)使用class名字，如class AreaLayer文件名就使用AreaLayer

**Comment by hustcc** [comment]
@zqlu 就是两种风格了，是使用驼峰的方式，还是使用 `-` 的方式~确定一种就 ok @paleface001

**Comment by paleface001** [comment]
`-`的文件名感觉可读性更强一点

**Comment by Me-Momo** [comment]
> stackBar-label --> stack-bar-label

这样子就有另外一个问题了 组件文件名都要统一 `-`分割？而不是驼峰？

**Comment by hustcc** [comment]
@paleface001 @Me-Momo 如果确定了，就逐步改掉了，体力活，不难改~
