### ISSUE TITLE
有任知道G2 图表怎么导出图片吗？

### ISSUE THREAD

**Issue by liu123456789** [antvis/G2Plot#1520]
我查看了API没有找到。。 那位大神帮帮我。

**Comment by BBSQQ** [comment]
> 考虑到 G2 使用环境的不同（浏览器、mobile 等），G2 从 v4 版本开始，不再提供 `chart.toDataURL()` 以及 `chart.downloadImage()` 接口，鼓励用户自己包装。

https://g2.antv.vision/zh/docs/manual/faq/#%E5%A6%82%E4%BD%95%E5%AF%BC%E5%87%BA%E5%9B%BE%E7%89%87
