### ISSUE TITLE
tooltip的onchange事件，containerDom元素插入无效

### ISSUE THREAD

**Issue by brushbird** [antvis/G2Plot#1524]
![image](https://user-images.githubusercontent.com/20636542/92207663-2b8acb00-eebc-11ea-83ce-60f6060da7de.png)
官网示例就有问题，之前就是这样用的，然后不知道什么时候开始，失效了，版本回退都没用
官网demo地址：https://g2plot.antv.vision/zh/examples/general/tooltip#tooltip-inner-chart

**Comment by xiangzhengfeng** [comment]
![image](https://user-images.githubusercontent.com/39773201/93974883-12818580-fda9-11ea-930c-e4b8474dd4e9.png)
demo上面的类别如果减少一个，下面就多生成了两个tips，如果减少为1个，那么这个更加明显。。。。。。。。

**Comment by hustcc** [comment]
是实现类似这样的功能吧。

![image](https://user-images.githubusercontent.com/7856674/95550487-8ffcf500-0a3b-11eb-9b69-4975f41470f1.png)

可以参考： https://g2plot.antv.vision/zh/examples/gallery/trend/#mobile
