### ISSUE TITLE
legend label 的可用宽度不合理

### ISSUE THREAD

**Issue by dengfuping** [antvis/G2Plot#1526]
- 可以看到下图中的 legend 的左侧/右侧都有足够的空间可以展示 label，但却没有利用起来，使得很短的 label 就会出现 ellipsis 的效果:

![image](https://user-images.githubusercontent.com/14918822/92228899-33a63300-eedb-11ea-88e4-2a40c2fb9d92.png)

![image](https://user-images.githubusercontent.com/14918822/92229096-8384fa00-eedb-11ea-8e6a-386623cded4d.png)

**Comment by fanqiao1104** [comment]
我也遇到这个问题，解决了吗？

**Comment by hustcc** [comment]
已经在 2.0.2 版本中解决。
