### ISSUE TITLE
[回归] 10-08 图表走查测试结果

### ISSUE THREAD

**Issue by hustcc** [antvis/G2Plot#1536]
> 09-30 图表包括 P0，P1，具体见：https://www.yuque.com/antv/g2plot/ffgrfy 。测试结果分成为：功能， bugfix，文档，demo

图表负责人，自己在图表后面 at 自己。

# 网站 demo

- [x] 编辑器代码提示 
- [ ] 每个 demo 缺失描述信息（之前是使用图表的 title + desc 做的） @BBSQQ  新网站考虑
- [x] demo 截图更新 @lxfu1  （930 前手动更新，长期截图工具自动覆盖，404 页面检测一起搞）（nit）
- [x] 教程文档  @lxfu1 （整理大纲，分工）
- [x] 配置文档 @lxfu1 
- [x] 标注 demo @Me-Momo 
- [ ] 事件 demo @hustcc 
- [x] 状态量 demo @Me-Momo  
- [ ] 类型定义自动抽取文档（ 交互式文档出来之前，可以生成为 markdown，出来后直接生成网站 ）@hustcc （nit）

# 组件

- [x] legend 支持通过 items 自定义图例
- [x] slider  初始值 start end，初始样式不对
- [ ] annotation  image 标记在 更新的时候 闪烁明显 @Me-Momo (G2 解决，允许 annotation 不重新渲染)

# 通用重构点

- [x] statistic 中心文本的结构统一（饼图、水波图、进度环图） @Me-Momo @hustcc  https://github.com/antvis/G2Plot/pull/1587
- [x] color 为 string 的时候，colorField 丢失了 https://github.com/antvis/G2Plot/pull/1573

# **P0**

### 折线图 

@hustcc 

- [x] 辅助线、预警线 https://github.com/antvis/G2/issues/2805
- [x] 条件样式 (nit)
- [x] slider demo
- [x] scrollbar demo || 滚动轴 (nit)

### 面积图 

@hustcc 

- [x] 辅助线、预警线
- [x] slider demo
- [x] scrollbar (nit)
- [x] 渐变色填充 demo
- [x] 线 样式设置（目前没有 line geometry）(nit)
- [x] 数据标签（原 v1 中的面积图数据标签）(nit)
- [x] range 不正确
![image](https://user-images.githubusercontent.com/7856674/92356179-3e014080-f118-11ea-8e6a-d0ee7c5f539b.png)
- [ ] slider + 堆积面积不生效

### 柱形图 

@zqlu 

- [x] label 只保留一个 demo，然后在代码注释注明可选值
- [x] label demo 没有体现出数据标签的布局优化算法
- [x] 没有图例设置
- [x] 转化率组件（nit）
- [x] 百分比堆积 @lxfu1 
- [x] range 类型的柱形图 @lxfu1 
- [x] label 颜色
![image](https://user-images.githubusercontent.com/7856674/94557288-f1310580-0290-11eb-9176-a3dcc26f399f.png)
- [x] label position 不生效（堆积柱形图）
 
### 条形图 

@BBSQQ 

- [x] label 只保留一个 demo，然后在代码注释注明可选值
- [x] label demo 没有体现出数据标签的布局优化算法
- [x] 没有图例设置
- [x] 转化率组件
- [x] 标签问题 @zqlu 
![image](https://user-images.githubusercontent.com/7856674/92561432-c9a8d780-f2a6-11ea-9716-fe24ae78f5d4.png)

### 饼图 

@Me-Momo 

- [x] demo 中 innerRadius 对比不明显（有两个环图的 innerRadius 配置太相近，看不出有区别）
- [x] label超出图形
- [ ] label 溢出 plot range，没有省略展示
![image](https://user-images.githubusercontent.com/15646325/92996711-2c68d000-f540-11ea-90d5-b28ee1901dd2.png)
- [ ] 提供一个大数据量的数据标签样式

### 散点图 

@lxfu1 

- [x] 四象限 demo 缺失
- [ ] 回归线（nit）
- [x] demo 不是很好看，可直接参考（ https://g2plot.antv.vision/zh/examples/bubble/basic#basic ）
- [x] 连续图例暂时干掉吧，不好看

### 双轴图 

@liuzhenying 

- [x] 图例点击，样式不变化
- [x] 线被柱挡住
![image](https://user-images.githubusercontent.com/7856674/92350149-a9441600-f10a-11ea-845d-4cff58a3653d.png)
- [x] 双折线、柱 + 线，增加 geometry 的自定义图例
- [x] 混合图如果两侧 scale 一致，可以只显示一个 yaxis，看看如果在 demo 中体现能力
- [x] label 过长时图表无法自适应：等待 g2 updateOptions 修复后，再验证 fix 效果  （syncViewPadding）
- [ ] scrollbar（nit）
- [x] 左右图形和配置反了
![image](https://user-images.githubusercontent.com/7856674/94097991-35b83d80-fe5a-11ea-97c9-9429dce9910b.png)
 - [x] 图例过滤不正确，做 column 右 line 的时候
- [x] line column 的时候， x 是 time scale，range 不正确
 - [x] range 计算不正确（分组的时候可能导致遮挡 y 轴线）
![image](https://user-images.githubusercontent.com/7856674/94098055-56809300-fe5a-11ea-9ce0-f8fe8d0b7f64.png)
- [x] 图形 legend 切换之后，图形位置挂了
![image](https://user-images.githubusercontent.com/7856674/94097980-30f38980-fe5a-11ea-8139-49cb4246c717.png)
- [hold]  time 坐标轴产生空数据，这个是 g2 的适配 nice 的pretty 算法，暂时无法更改
![image](https://user-images.githubusercontent.com/11748654/95810710-3bf85600-0d44-11eb-975c-8c0fff047020.png)

- [X] 混合图更新 legend 出错

----

# **P1**

### 雷达图 

@Me-Momo 

 - [x] crosshair ‘xy’ 作为默认吧，感觉挺好看的（nit ）
 - [ ] 提供 demo，通过数据处理+formatter 实现不同轴自己的 max

### 词云图

@zhangzhonghe  @lxfu1 

- [x] demo 缺失
- [x] 单测不全

### 漏斗图 

@liuzhenying 

- [x] demo 中的 padding 都使用 auto（或者不写）
- [x] transpose 之后的动画有点奇怪
- [ ] 对比漏斗的 title 文本样式奇怪 
- [ ] 支持 shape  https://github.com/antvis/G2Plot/issues/1624
- [ ] 测试用例 
- [x] demo legend、tooltip

![image](https://user-images.githubusercontent.com/7856674/95948254-cc0ccd00-0e22-11eb-8052-b5b90f27e16e.png)

### 子弹图

@arcsin1 

- [x] 内置默认图例，而不是通过 legend 配置自定义图例
- [x] 一些样式问题, [配置内容](https://codesandbox.io/s/zidantu-b4clj)
![image](https://user-images.githubusercontent.com/15646325/93743208-2f3f8100-fc22-11ea-998f-30dc62fa9015.png)

### 直方图

@arcsin1

 - [x] tooltip 显示问题
![image](https://user-images.githubusercontent.com/7856674/92349545-04750900-f109-11ea-8094-1b2cd90e188a.png)
- [配置内容](https://codesandbox.io/s/zidantu-b4clj?file=/index.ts)

### 水波图 

@hustcc @CarisL

- [x] 缺失 demo
- [x] 自动文本颜色、大小。
- [x] geometry.custom 传入自定义参数问题 https://github.com/antvis/G2/pull/2831

### 玫瑰图

@zhangzhonghe

- [x] 缺失 demo
- [ ] demo 不是很好看，可以看看一些玫瑰图作品和配色
- [ ] 增加新冠病毒的 demo
- [x] label 建议加上 `layout: { type: 'limit-in-shape' }`

### mini 图 

@hustcc @connono 

- [x] 辅助线能力 + demo
- [x] 进度条/环 的百分比标识 + tooltip
- [x] Progress color 配置失效 
![image](https://user-images.githubusercontent.com/7856674/92385697-e88f5880-f144-11ea-9bf9-661ca3649c5d.png)
- [x] 如何进行 tooltip 文本的格式化，并内置格式化

![image](https://user-images.githubusercontent.com/7856674/93293726-3aa63d00-f81b-11ea-8f38-d994f27ca9d5.png)

### 股票图

@jinhuiWong 

- [ ] demo 中 tooltip 有时候有，有时候没有
- [ ] tooltip 样式不好看

### 旭日图

@lxfu1 

 - [ ] tooltip 默认样式太丑了。
![image](https://user-images.githubusercontent.com/7856674/95948588-679e3d80-0e23-11eb-9299-e9c82bc57529.png)

# 场景化 DEMO

@Me-Momo  负责分配和验收

- [ ] 高亮联动  @hustcc 
- [ ] 绝对值、比例值指标双轴图  @liuzhenying 
   > 业务场景如：左边为金额型或数值型指标，右边为百分比指标（支付笔数 & 渗透率）
- [x] 指标卡图例  @Me-Momo 
- [x] 多指标趋势图 @Me-Momo 
- [ ] 自定义 tooltip 按钮   @lxfu1 
  > tooltip 上带按钮，可以 hover 进去操作
  > tooltip 超多明细数据，最大高度限制，可以 hover 进去滚动展示
- [ ] 自定义交互（图例 hover）  @Me-Momo 
- [ ] label 上链接   @hustcc 
- [ ] 拖拽柱形图，影响数据  @zqlu 
- [ ] 补充 theme 配置化 demo  @Me-Momo

**Comment by arcsin1** [comment]
@hustcc  直方图问题 ，我看了竞品是 xx-yy形态,  而我们的tooltip是自动生成的其实原始数据是[22,33]，如果要改成前面那种xx-yy的话需要自己定制哦

**Comment by hustcc** [comment]
> @hustcc  直方图问题 ，我看了竞品是 xx-yy形态,  而我们的tooltip是自动生成的其实原始数据是[22,33]，如果要改成前面那种xx-yy的话需要自己定制哦

是否可以稍微格式化一下，变短一些。

**Comment by Me-Momo** [comment]
> statistic 中心文本的结构统一（饼图、水波图、进度环图）

 这个等你的 mini 图合并了，一起看下

**Comment by arcsin1** [comment]
@hustcc  子弹图内置图例设为@TODO了

**Comment by severli93** [comment]
![image](https://user-images.githubusercontent.com/14239959/94364244-7930d700-00fa-11eb-8ca0-4eff2a2ff5e7.png)
multiline chart with dot markers: dots disappear on peaks and troughs. looks like bug

**Comment by severli93** [comment]
![image](https://user-images.githubusercontent.com/14239959/94365671-62dc4880-0105-11eb-8033-afa07eed3893.png)
stackareachart with slider stays still after changing the slider

**Comment by severli93** [comment]
![image](https://user-images.githubusercontent.com/14239959/94365781-2bba6700-0106-11eb-890a-b016f686e029.png)
text is not readable enough, suggest to be white filled color

**Comment by arcsin1** [comment]
@liuzhenying  
![image](https://user-images.githubusercontent.com/13724222/94547507-e9b63000-0281-11eb-925c-6b50382f1c9c.png)

**Comment by arcsin1** [comment]
这个图tooltip要看下是否有点小问题 @BBSQQ 
![image](https://user-images.githubusercontent.com/13724222/94633145-05abe700-02ff-11eb-9c74-9ade396295fa.png)

**Comment by arcsin1** [comment]
@lxfu1  图被压缩了 要重新截图一下~
![image](https://user-images.githubusercontent.com/13724222/94633325-84a11f80-02ff-11eb-95d8-7e3be92e44a3.png)

**Comment by arcsin1** [comment]
@jinhuiWong  看一下图表内的细节

![image](https://user-images.githubusercontent.com/13724222/94633618-76073800-0300-11eb-8253-668fb412d87d.png)

**Comment by lxfu1** [comment]
> @lxfu1 图被压缩了 要重新截图一下~
> ![image](https://user-images.githubusercontent.com/13724222/94633325-84a11f80-02ff-11eb-95d8-7e3be92e44a3.png)

@BBSQQ 配置下img属性

**Comment by BBSQQ** [comment]
> 这个图tooltip要看下是否有点小问题 @BBSQQ
> ![image](https://user-images.githubusercontent.com/13724222/94633145-05abe700-02ff-11eb-9c74-9ade396295fa.png)

是不应该显示 Crosshairs 吗？这里有个提交记录是你改成 true 的，你记得是为啥了不？
![image](https://user-images.githubusercontent.com/35586469/94640867-55e07480-0312-11eb-8375-8ffe8ab4081d.png)

**Comment by Me-Momo** [comment]
@lxfu1 可以看下这个
![image](https://user-images.githubusercontent.com/15646325/96240486-8b07ea80-0fd3-11eb-97d7-e693d3d7e506.png)

**Comment by Me-Momo** [comment]
> ![image](https://user-images.githubusercontent.com/14239959/94364244-7930d700-00fa-11eb-8ca0-4eff2a2ff5e7.png)
> multiline chart with dot markers: dots disappear on peaks and troughs. looks like bug
> https://g2plot.antv.vision/zh/examples/line/multiple#marker-active

you can control it by yourself
```
style: ({ year, }) => {
    return {
        r: Number(year) % 4 ? 0 : 3, // 4 个数据示一个点标记
     };
 },
```

**Comment by hustcc** [comment]
issue 已经修复 80%，且时间太久，关闭重开一个了。 https://github.com/antvis/G2Plot/issues/new
