### ISSUE TITLE
[讨论] 视觉通道的映射 callback params 统一问题

### ISSUE THREAD

**Issue by hustcc** [antvis/G2Plot#1540]
G2 通过 callback 的形式将数据映射成视觉通道（ size、shape、color 等 ），对于这个 callback 的参数，以及顺序需要有一个统一的规范。问题：

1. 不同图的映射字段是哪些？
2. 字段顺序怎么确定？

因为这些设计后续的修改一定是 break change，所以需要在发布正式版之前完结。

----

### 方案一：

1. 全量字段映射。比如 line 就是 x*y*seriesField，scatter 就是 x*y*color*size*shape
2. 顺序按照视觉通道的重要性。理论上就是  x*y*color*size*shape 了，大部分图表都只有 x*y*color

具体实现，以 column color 为例：

```ts
if (isString(color) || isArray(color)) {
   g.color('colorField', color);
} else if (isFunction(color)) {
   g.color('x*y*colorField', color);
} else {
   // 其他非法情况不处理。
}
```

### 方案二

1. 视觉通道的只映射对应字段，例如 line 的 color 就映射 seriesField，scatter 的 shape 就映射 shape 字段
2. 不存在顺序问题

具体实现，以 scatter shape为例

```ts
if (shape) {
   g.shape('shapeField', shape);
}
```

### 方案三

1. 各个图形按需确定映射字段。
2. 顺序按照视觉通道的重要性。

----

个人觉得 3 是最差的方案，因为每个图不一样会导致开发一脸懵逼。说下你的看法和选择？

**Comment by lxfu1** [comment]
方案一吧，兼容性好一点。

**Comment by hustcc** [comment]
因为 G2 中 legend 生成字段的问题。具体为：

```ts
g.color('x*y*color', (x, y, color) => {
});
```

这种情况下会生成第一个字段 x 的图例，所以导致问题。因为方案改成：

```ts
g.color('color*x*y', (x, y, color) => {
  return callback({ x, y, color });
});
```

具体为：

1. 通道映射字段为全量字段，但是第一个字段为通道字段
2. callback 函数的参数变成一个 object，避免产生 breakchange
