### ISSUE TITLE
重新渲染无法更换主题颜色

### ISSUE THREAD

**Issue by NierWinter** [antvis/G2Plot#1546]
因为有换肤的需求，需要给图表换主题背景。但无论是销毁后重新渲染，还是更新图表配置项，第一次从默认背景换成暗黑主题成功后，就一直是暗黑主题，无法再换肤。用的是折线图，希望能指导一下。还有就是自定义主题能修改图表的背景颜色吗？谢谢

**Comment by hustcc** [comment]
v1 中存在问题，在 v2 中测试过不存在问题。https://g2plot-v2-beta.antv.vision/zh/examples/line/basic#line
