### ISSUE TITLE
1.1.26 版本漏斗图 hover 报错

### ISSUE THREAD

**Issue by xiecg** [antvis/G2Plot#1549]
https://codesandbox.io/s/great-curie-9en0k

![image](https://user-images.githubusercontent.com/10857932/92583063-5f9f2b00-f2c4-11ea-922e-a7d3f7c74dc3.png)

**Comment by hustcc** [comment]
v2 中避免。

**Comment by xiecg** [comment]
> v2 中避免。

请问 v2 预计什么时候发布 ？

**Comment by hustcc** [comment]
> > v2 中避免。
> 
> 请问 v2 预计什么时候发布 ？

930 会发布 v2 的正式版本，不过漏斗图建议在 10 月中旬再接入使用。
