### ISSUE TITLE
G2Plot 可以支持坐标轴的反转么

### ISSUE THREAD

**Issue by jiazhewang** [antvis/G2Plot#1551]
类似 G2 

`chart.coordinate().scale(1,-1)` 和 `chart.axis('year', { position: 'top' })` 的效果。

是否可以给 axis 提供一个 inverse、position 的配置？

**Comment by hustcc** [comment]
v2 中可以如下追加操作，v1 的做法可以类似，但是需要找到对应的 G2 view.

```ts
 const line = new Line('container', { ... });

line.chart.coordinate('rect').transpose(); // 后者其他 api

line.render()
```

v1 中，上述为 API 提供，作为 G2Plot 暴露 G2 能力的一种方式。

**Comment by jiazhewang** [comment]
我就是想问 v2 有没有可能做成配置项的形式呢？ec 是配置项形式的，用户理解和使用起来很方便。

**Comment by hustcc** [comment]
不考虑吧，和 ec 其实没啥对比，和 highcharts可能可以对比。比如柱形图，条形图就是反转而来，如果再提供坐标系，感觉冗余了，如果要灵活丰富的配置方式，直接 G2 也可以的，全量配置的使用方式都提供的。
