### ISSUE TITLE
宽度有限时百分比堆叠柱状图文字不显示

### ISSUE THREAD

**Issue by xiecg** [antvis/G2Plot#1554]
![image](https://user-images.githubusercontent.com/10857932/92689268-4d2efb00-f371-11ea-8451-867a0c78df7e.png)

https://codesandbox.io/s/vigilant-torvalds-s03w7?file=/index.html

**Comment by mortalYoung** [comment]
你可以试试设置这样子
```ts
 label:{
   adjustPosition: false,
 }
```
![image](https://user-images.githubusercontent.com/18719701/92851554-44493280-f420-11ea-9b9a-56c6278122b8.png)

**Comment by xiecg** [comment]
> 你可以试试设置这样子
> 
> ```ts
>  label:{
>    adjustPosition: false,
>  }
> ```
> 
> ![image](https://user-images.githubusercontent.com/18719701/92851554-44493280-f420-11ea-9b9a-56c6278122b8.png)

谢谢
