### ISSUE TITLE
瀑布图的tooltip配置customContent时tooltip跟随鼠标移动动画不正常

### ISSUE THREAD

**Issue by alobe** [antvis/G2Plot#1556]
[会出现tooltip频繁闪烁的效果](https://ftp.bmp.ovh/imgs/2020/09/02cafd86212a5da6.gif)，waterfall里的tooltip配置为
`{ visible: true, showTitle: false, customContent: () => `\<div class="g2-tooltip" style=""\>自定义 \</div\>` }`;

请问能最近修复下吗？感谢~

**Comment by Me-Momo** [comment]
这个问题在v2上修复吧

**Comment by Me-Momo** [comment]
先配置下 domStyles
   domStyles: {
      'g2-tooltip': {
        transition: 'left 0.4s cubic-bezier(0.23, 1, 0.32, 1) 0s, top 0.4s cubic-bezier(0.23, 1, 0.32, 1) 0s;',
      },

**Comment by alobe** [comment]
> 以后提 issue 的时候给一个复现 demo

好的，不好意思哈
