### ISSUE TITLE
折线图的xField、yField为空时，和其他图表表现不一致

### ISSUE THREAD

**Issue by yuruwang** [antvis/G2Plot#1557]
折线图中如果xField和yField为空，图表仍然能渲染，截图如下：
![image](https://user-images.githubusercontent.com/31492974/92842890-b583e800-f416-11ea-8c92-8468886d7ecc.png)
但是在其他图表中，比如柱状图，xField和yField为空时，图表不会渲染，并且会抛出错误，如下图：
![image](https://user-images.githubusercontent.com/31492974/92842861-a6049f00-f416-11ea-8a43-7d60207ab04c.png)

希望在xField、yField为空时，表现一致，要么都做容错，要么都抛出异常

**Comment by hustcc** [comment]
最新版本的 v2 中，已经不存在这个问题。请测试 https://g2plot.antv.vision/zh/examples/column/basic
