### ISSUE TITLE
[优化]：堆叠条形图 api 文档 adjustPosition 属性

### ISSUE THREAD

**Issue by mortalYoung** [antvis/G2Plot#1558]
### 简介
- `api` 文档中关于 `adjustPosition` 该属性描述如下
> 是否根据显示区域自动调整文本标签位置，position 为 middle 时有效。如图形区域容纳不下 label，则 label 自动隐藏。

- 我试了以后发现 在 position 不为 middle 时 同样生效，不知道考虑不考虑这个误导人的描述修改一哈？

**Comment by Me-Momo** [comment]
不好意思哈 我们刚接手了G2Plot 正在重新v2版本；后面会统一修复
