### ISSUE TITLE
柱状图title无法居中

### ISSUE THREAD

**Issue by puppetsheep** [antvis/G2Plot#1559]
`alignTo`仅有一个配置，与API描述的三种配置不符。(非`left`即右，默认`left`)
[https://g2plot.antv.vision/zh/examples/column/basic](https://g2plot.antv.vision/zh/examples/column/basic)

**Comment by mortalYoung** [comment]
```ts
title: {
    visible: true,
    text: '基础柱状图',
    alignTo: 'middle'
 }
```
你试试这样子可以不，我试了是可以的

**Comment by puppetsheep** [comment]
> ```ts
> title: {
>     visible: true,
>     text: '基础柱状图',
>     alignTo: 'middle'
>  }
> ```
> 
> 你试试这样子可以不,我试了是可以的

多谢，这样是可以的。只是文档上没更新出三个配置，仅填写了一个，我就不知道居中是什么了
