### ISSUE TITLE
如何设置滚动条的样式

### ISSUE THREAD

**Issue by NierWinter** [antvis/G2Plot#1562]
数据多了使用到滚动条，但是滚动条小且没法用滚轮控制，有点难受，暗黑主题下显示也不是很清晰，能自定义滚动条的样式吗？
https://g2plot.antv.vision/zh/examples/bar/basic#scroll-bar

**Comment by huang-ysfirst** [comment]
确实有这个需求

**Comment by glk-hll** [comment]
有没有解决？跟你遇到一样的问题！

**Comment by NierWinter** [comment]
> 有没有解决？跟你遇到一样的问题！

没有

**Comment by hustcc** [comment]
我们在 v4.1.0-beta 中解决这些问题了，但是正式版本暂未发布。稍等 930 我们会发布正式版本。

**Comment by Me-Momo** [comment]
@zqlu 这个支持配置吗？

**Comment by visiky** [comment]
ref: https://github.com/antvis/component/pull/220, will be fixed

**Comment by visiky** [comment]
Will be close in v2.3.12
