### ISSUE TITLE
柱线图不能修改多个 tooltip

### ISSUE THREAD

**Issue by JackFGreen** [antvis/G2Plot#1563]
tooltip 参数怎么修改混合图，比如将 null 修改为 '--'

![image](https://user-images.githubusercontent.com/23187848/92901067-c8b4a900-f452-11ea-9942-6de80d7b57d4.png)

**Comment by hustcc** [comment]
在最新版本中。对于 null 是不会显示的。

![image](https://user-images.githubusercontent.com/7856674/94564885-1a569380-029b-11eb-83f5-80eb058ee368.png)

如果需要自定义，可以使用 customContent。使用 customContent 相对还是有一些成本。
