### ISSUE TITLE
（feat）多饼图同一Legend

### ISSUE THREAD

**Issue by JasonSubMara** [antvis/G2Plot#1564]
目前的折线图或者柱状图均可以表示同一纬度下不同数据构成的分析，但是饼状图不能公用一个label，希望是个可以实现的新需求，或者有官方提供的方法来实现相应的图表联动。
相关截图如下：

![微信截图_20200911172330](https://user-images.githubusercontent.com/30927318/92904236-45e11d80-f455-11ea-90bb-35675442aad6.png)

**Comment by Me-Momo** [comment]
这个需要使用分面的方式来处理多个饼图；还有一个方案就是不使用默认的 legend，在外部实现自己的公用图例，以及对数据进行过滤来实现
