### ISSUE TITLE
Custom tooltips for wordclouds

### ISSUE THREAD

**Issue by pjeannet** [antvis/G2Plot#1574]
Hi, we are trying to add content to the tooltips of wordclouds without any success.  The goal is to add some "aliases" to each words that would be added to the tooltip on hovering words.
We read the doc here : https://g2.antv.vision/en/docs/manual/tutorial/tooltip and also managed to do this https://g2plot.antv.vision/en/examples/general/tooltip/#tooltip-statistic-value on another chart but we can't see how the tooltips for wordcloud are working as the API seems to be different (https://g2plot.antv.vision/zh/examples/word-cloud/basic/API). 
Can you confirm that editing wordclouds tooltip is doable? if yes, where could we find a sample on how to do it?

Thanks a lot

**Comment by zhangzhonghe** [comment]
@pjeannet In the 2.x version, you can use the `customContent` option to implement custom tooltip content.

e.g.
```ts
const wordCloud = new WordCloud('container', {
  data,
  wordField: 'x',
  weightField: 'value',
  tooltip: {
    customContent(title, data) {
      // data could be an empty array
      if (!data.length) {
        return '<div></div>';
      }

      const { text, value } = data[0].data;
      return `<div class="g2-tooltip">
        <div class="g2-tooltip-title">title</div>
        <ul class="g2-tooltip-list">
          <li class="g2-tooltip-list-item">
            <span class="g2-tooltip-marker"></span>
            <span class="g2-tooltip-name">${text}</span>:<span class="g2-tooltip-value">${value}</span>
          </li>
        </ul>
      </div>`
    }
  }
});

wordCloud.render();
```

**Comment by pjeannet** [comment]
Hello, thanks for the answer, as 2.x is still in beta we were using 1.x. We will wait for 2.0 to implement this part.
