### ISSUE TITLE
g2plot 热力图 配置项和事件不生效问题

### ISSUE THREAD

**Issue by rabbit-tian** [antvis/G2Plot#1580]
1. 色块点击事件：当type === rect 时，事件使用 onRectClick；当 type === circle 时, 无对应事件
2. 图例点击事件不生效，onLegendClick
3. 坐标轴刻度数量 tickCount 不生效
4. 当 type === circle 时，鼠标移入色块时，提示框显示问题，有的显示，有的不显示

![image](https://user-images.githubusercontent.com/26690191/93282939-0eca8d80-f802-11ea-9104-3c1a610bce38.png)

**Comment by hustcc** [comment]
@lxfu1 帮忙看看这个在 v2 中的事件，是否都支持，能力是否 cover v1？

**Comment by lxfu1** [comment]
V2 已经解决。
