### ISSUE TITLE
@ant-design/charts 中如何使用 StateManager？

### ISSUE THREAD

**Issue by glk-hll** [antvis/G2Plot#1585]
@ant-design/charts  不是基于 G2Plot 开发的吗？那在 @ant-design/charts 中改如何使用 StateManager？或者说如何导入StateManager？

**Comment by glk-hll** [comment]
没人用过这个 StateManager 吗？？？

**Comment by hustcc** [comment]
通过 ref 拿到实例，然后就是和 g2plot一样的状态量 api 了。

https://g2plot.antv.vision/zh/docs/manual/advanced/state-and-charts-connetion

**Comment by hustcc** [comment]
重复 issue https://github.com/ant-design/ant-design-charts/issues/194
