### ISSUE TITLE
g2plot 文档中文字提示错误

### ISSUE THREAD

**Issue by glk-hll** [antvis/G2Plot#1586]
https://antv-g2plot.gitee.io/zh/examples/general/state#set-selected2
和 
https://antv-g2plot.gitee.io/zh/examples/general/state#set-selected1
图表的标题一样，https://antv-g2plot.gitee.io/zh/examples/general/state#set-selected2 中的标题应改为 "批量（多值）....”

**Comment by hustcc** [comment]
@glk-hll 有兴趣和时间来 pr 吗，直接搜索这个文件就可以定位到文件。

![image](https://user-images.githubusercontent.com/7856674/93319676-bbc4fa80-f842-11ea-8519-2f64c6b23feb.png)

**Comment by glk-hll** [comment]
pr是？？？

**Comment by hustcc** [comment]
> pr是？？？

就是帮忙提交代码修改掉这个问题。
