### ISSUE TITLE
G2Plot图表联动功能疑似出现了BUG

### ISSUE THREAD

**Issue by glk-hll** [antvis/G2Plot#1588]
![bug](https://user-images.githubusercontent.com/44257305/93425200-16666100-f8ec-11ea-913e-d5e6ef736bf1.gif)

实际演示跟官方模拟演示示意图不一致！

**Comment by hustcc** [comment]
好的，有兴趣开走查 v2 版本的官网 demo 个功能吗？

**Comment by hustcc** [comment]
> ![bug](https://user-images.githubusercontent.com/44257305/93425200-16666100-f8ec-11ea-913e-d5e6ef736bf1.gif)
> 
> 实际演示跟官方模拟演示示意图不一致！

实际代码是使用的 click 去触发联动的，但是在样式上似乎存在一些问题，这些我们会在 v2 中修复，v1 暂不处理。

**Comment by glk-hll** [comment]
好吧 其实发现了不少BUG 
有时间再反馈吧。

**Comment by glk-hll** [comment]
还有想在 ant-design-charts 中实现这个图表联动目前我试了都没有成功，这个功能才是趋势，图表数据要能真正实现数据大、全、以及网络化的交叉效应应该会特别好。简单的数据展现感觉不能够发挥图标的最大作用，这个联动效应可能是用户想拥有的，至少我是 哈哈哈。
