### ISSUE TITLE
DualLine 的 tooltip 数据重复显示

### ISSUE THREAD

**Issue by Una-Gao** [antvis/G2Plot#1589]
![image](https://user-images.githubusercontent.com/68375674/93426424-9988b680-f8ee-11ea-8e96-6236f62c6372.png)

**Comment by liuzhenying** [comment]
该问题将在2.0 版本中解决，当前使用请尝试下社区提供的方式 https://github.com/antvis/G2Plot/issues/1244#issuecomment-693948634

**Comment by hustcc** [comment]
> 该问题将在2.0 版本中解决，当前使用请尝试下社区提供的方式 [#1244 (comment)](https://github.com/antvis/G2Plot/issues/1244#issuecomment-693948634)

如果 2.0 中已经没有这个问题了，那么这个 issue 可以关闭掉了。
