### ISSUE TITLE
新版本子弹图目标值是否能显示

### ISSUE THREAD

**Issue by phoema** [antvis/G2Plot#1599]
data: [
    {
      title: '满意度',
      measures: [83],
      targets: [90],
    },
  ],

targets显示到图表上。

**Comment by phoema** [comment]
#1566

**Comment by arcsin1** [comment]
其实目前v2 是支持target的tooltip直接显示的，v1貌似tooltip支持不友好 ，当然想显示label也是可以的，可以让你看看效果:


![image](https://user-images.githubusercontent.com/13724222/93597369-814b9100-f9ed-11ea-8725-719307f23912.png)
