### ISSUE TITLE
条形图单击事件为什么打印出来的数据data是null?

### ISSUE THREAD

**Issue by ityadong** [antvis/G2Plot#1606]
![image](https://user-images.githubusercontent.com/33867329/93730426-22f3fd80-fbfb-11ea-992c-8e579b41e3d3.png)

barPlot.on('click', function(e){
  console.log('打印数据', e)
})

**Comment by hustcc** [comment]
看看我们 [v2 版本](https://g2plot-v2-beta.antv.vision/zh)，不存在这个问题了。 v1 中难以修复，暂时不处理了。
