### ISSUE TITLE
混合图表无法关闭动画

### ISSUE THREAD

**Issue by yuruwang** [antvis/G2Plot#1609]
混合图表的配置中加上animation:false无效，非混合图表这样配置是有效的。
online demo: https://codesandbox.io/s/vigorous-yonath-qwjk7?file=/index.js

**Comment by hustcc** [comment]
在新版本 v2 中的双轴图试试看，已经解决该问题。

https://g2plot.antv.vision/zh/examples/dual-axes/dual-line#custom-dual-line
