### ISSUE TITLE
仪表盘value大于max时指针指向不正确

### ISSUE THREAD

**Issue by yuruwang** [antvis/G2Plot#1611]
当仪表盘value大于max时指针并没有指向仪表盘最大值，而是指向仪表盘中间，会造成用户困惑
截图：
![Uploading image.png…]()
online demo: https://codesandbox.io/s/oheph?file=/index.js

**Comment by hustcc** [comment]
Fixed in v2, pr here: https://github.com/antvis/G2Plot/pull/1673
