### ISSUE TITLE
stackedColumnLine -> columnConfig -> color cannot support function(typescript)

### ISSUE THREAD

**Issue by xiaosunJessica** [antvis/G2Plot#1620]
https://g2plot.antv.vision/zh/docs/manual/combo-charts/stackedColumn-line#color
![image](https://user-images.githubusercontent.com/17615820/93867200-49995d80-fcfb-11ea-8648-5c6b37711715.png)
上图失败的话点击图片链接：https://github-production-user-asset-6210df.s3.amazonaws.com/17615820/93867200-49995d80-fcfb-11ea-8648-5c6b37711715.png
![image](https://user-images.githubusercontent.com/17615820/93867325-78173880-fcfb-11ea-9be0-adf590b36fad.png)
上图失败的话图片链接：https://github-production-user-asset-6210df.s3.amazonaws.com/17615820/93867325-78173880-fcfb-11ea-9be0-adf590b36fad.png

**Comment by hustcc** [comment]
新版本 v2 中已经支持，v1 不再继续迭代。
