### ISSUE TITLE
子弹图如何隐藏当前进度值

### ISSUE THREAD

**Issue by BovineBoy** [antvis/G2Plot#1621]
![image](https://user-images.githubusercontent.com/41846364/93985209-567b8700-fdb7-11ea-8941-725e9d5bdcdb.png)

**Comment by arcsin1** [comment]
v1版本，请用 label: null .  thanks!  也小小期待一下v2版的子弹图

**Comment by phoema** [comment]
v2的子弹图如何将目标值像实际值似的直接在图上显示啊，只能光标放上去才显示吗？

**Comment by arcsin1** [comment]
label: {
     target: true 
 }
文档还有点问题

**Comment by phoema** [comment]
加油
还没找到1.x到2的升级说明

**Comment by arcsin1** [comment]
> 加油
> 还没找到1.x到2的升级说明

抱歉 给你带来了一些困扰，有你们的支持，我们会做得更好 thanks！之后会有个很好的升级指南出现的。https://g2plot.antv.vision/zh/docs/manual/upgrade
