### ISSUE TITLE
图表不能拖拽(drag) G2可以 G2Plot不行

### ISSUE THREAD

**Issue by potatozerg** [antvis/G2Plot#1622]
https://www.w3schools.com/howto/howto_js_draggable.asp
上面是方法，G2没问题。
G2Plot的表并不会跟着鼠标动，然后mouseup之后会瞬移到html右下角，如果写了overflow: auto的话。 一直拖这个图就会让container无限放大。
不知道是不是和现有的event冲突了。
Demo（我的bug和这个稍微有区别 我的是瞬移 这个是慢慢往右下走）:
https://codesandbox.io/s/jolly-butterfly-e5ts5?file=/index.html

**Comment by potatozerg** [comment]
@Me-Momo 这里

**Comment by Me-Momo** [comment]
这个问题我们在 v2 上看下是否解决，v2 只要G2支持 G2Plot都可以

**Comment by potatozerg** [comment]
请问v2大概什么时候release
