### ISSUE TITLE
折线图网格线怎么配置不同的颜色

### ISSUE THREAD

**Issue by alekye** [antvis/G2Plot#1626]
希望折线图网格线颜色配置-yAxis-grid-style支持函数，对应不同y值，可以配置不同的颜色

**Comment by hustcc** [comment]
```ts
yAxis: {
   grid: {
     line: {
       style : function() {}, // 返回对应的样式信息
     }
   }
}
```

![image](https://user-images.githubusercontent.com/7856674/94328145-98d4dc00-ffe2-11ea-852d-c07b6aa22cfc.png)

**Comment by alekye** [comment]
问题解决，谢谢
