### ISSUE TITLE
Question: Column gap

### ISSUE THREAD

**Issue by oferitz** [antvis/G2Plot#1629]
Hi,
I'm looking for a way to set the gap between columns. Sometimes I don't want a gap between the columns.

For example changing from the default auto gap:
![Screen Shot 2020-09-24 at 14 29 48](https://user-images.githubusercontent.com/1668687/94139796-eb8f8600-fe72-11ea-8381-d80eb4cefd8c.png)

To no gap at all:
![Screen Shot 2020-09-24 at 14 30 15](https://user-images.githubusercontent.com/1668687/94139824-f9450b80-fe72-11ea-849c-5c5930f0e9e6.png)

or to 10px gap:
![Screen Shot 2020-09-24 at 14 35 30](https://user-images.githubusercontent.com/1668687/94139983-3f01d400-fe73-11ea-8449-27130cb2c90b.png)

Is it possible?

**Comment by DarrenPei** [comment]
You can use 'columnSize' to set the width of the Column in G2Plot and use ‘size()’ in G2.
```js
import { Column } from '@antv/g2plot';

const data = [
  {
    type: 'Firefox',
    value: 100,
  },
  {
    type: 'IE',
    value: 100,
  },
  {
    type: 'Edge',
    value: 100,
  },
  {
    type: 'Safari',
    value: 100,
  },
  {
    type: 'Opera',
    value: 100,
  },
  {
    type: 'Chrome',
    value: 100,
  },
];

const columnPlot = new Column(document.getElementById('container'), {
  title: {
    visible: true,
    text: 'Column Example',
  },
  width: 700,
  height: 700,
  padding: 0,
  data,
  xField: 'type',
  yField: 'value',
  colorField: 'type',
  columnSize: (700-100)/data.length  ,
});

columnPlot.render();
```

**Comment by oferitz** [comment]
@DarrenPei Thanks. I'm familiar with `columnSize` prop, this is how I did the images above :)
But I'm looking for more robust and standard way, as most of my charts has dynamic width.

**Comment by hustcc** [comment]
this will a feature soon. https://github.com/antvis/G2/pull/2881

**Comment by oferitz** [comment]
@hustcc Great! Really appreciate it!

**Comment by hustcc** [comment]
G2 已经支持，G2 G2Plot 文档需要同步更新。@zqlu

**Comment by Me-Momo** [comment]
you can use `maxColumnWidth` and `minColumnWidth`  like in the code below: 
```
  theme: {
    /** 柱状图最大宽度，像素值 (maxWidth of column) */
    maxColumnWidth: columnSize,
    /** 柱状图最小宽度，像素值 (minWidth of column) */
    minColumnWidth: columnSize,
  }
```
and we will  update document soon~
