### ISSUE TITLE
图表的异步请求空数据为空有没有什么可以友好的配置空数据的字段？

### ISSUE THREAD

**Issue by glk-hll** [antvis/G2Plot#1632]

**Comment by hustcc** [comment]
例如？需要做成什么样子，可以详细描述吗？

**Comment by glk-hll** [comment]
对于图表数据为空的时候，图表有没有自己的一种表现形式，比如提示 “数据为空”，这样子。

**Comment by hustcc** [comment]
> 对于图表数据为空的时候，图表有没有自己的一种表现形式，比如提示 “数据为空”，这样子。

这个数据为空的样式可能不同业务差别太大了，这个建议在业务层使用 html 去绘制，就像 loading 这些一样的。
