### ISSUE TITLE
V2的气泡图被合并到散点图后，时间播放轴是被取消了吗

### ISSUE THREAD

**Issue by NierWinter** [antvis/G2Plot#1634]
原来1.0版本气泡图的时间播放轴我有场景需要用到，在V2版本是被取消了吗
https://g2plot.antv.vision/zh/examples/bubble/basic#timeline

**Comment by lxfu1** [comment]
没有取消，暂时还没支持。

**Comment by NierWinter** [comment]
> 没有取消，暂时还没支持。

好的
