### ISSUE TITLE
双轴图图例 flipPage 无效

### ISSUE THREAD

**Issue by xiecg** [antvis/G2Plot#1645]
例子：https://codesandbox.io/s/gifted-wind-buhgn?file=/index.js

![image](https://user-images.githubusercontent.com/10857932/94358246-36f39f80-00d2-11eb-8369-8a678d17ee25.png)

**Comment by hustcc** [comment]
使用 v2 版本的 双轴图试试看。

**Comment by xiecg** [comment]
> 使用 v2 版本的 双轴图试试看。

解决了，v2 版本太棒了
