### ISSUE TITLE
【反馈】v2 网站和文档问题汇总

### ISSUE THREAD

**Issue by hustcc** [antvis/G2Plot#1657]
### 网站

- [x] v2 网站右上角显示 v1
- [x] 跳转到 v1 之后，v1 网站没有跳转到 v2 的下拉

### 文档

- [x] 缺失 plot 的 API 介绍页
- [ ] 快速上手结束之后，没有具体业务中怎么使用或者封装
- [ ] 事件、状态量、主题等具体介绍
- [x] 使用文档 - 图表（导航层级样式）
- [ ] 文档层级结构问题
- [ ] API 文档的内嵌表格过大时 无法滚动

![image](https://user-images.githubusercontent.com/15646325/98431990-3ef12700-20f5-11eb-8cc0-ecf2bfa82eb6.png)
![image](https://user-images.githubusercontent.com/15646325/98431882-5da2ee00-20f4-11eb-85cc-9d0487db225d.png)
![image](https://user-images.githubusercontent.com/15646325/98745117-e61fd800-23ed-11eb-836c-3515582366db.png)

**Comment by Me-Momo** [comment]
- [ ] 使用文档 - 图表（导航层级样式）
![image](https://user-images.githubusercontent.com/15646325/98431882-5da2ee00-20f4-11eb-85cc-9d0487db225d.png)

**Comment by Me-Momo** [comment]
## demo 走查

### 仪表盘
- 建议新增一个动图，类似这个 [demo](https://www.highcharts.com.cn/demo/highcharts/gauge-solid/dark-unica)

**Comment by DarrenPei** [comment]
散点图的文档中DEMO链接无效：
链接 https://g2plot.antv.vision/zh/docs/manual/plots/scatter
不建议DEMO编号1、2等，文档无法衔接。
