### ISSUE TITLE
404

### ISSUE THREAD

**Issue by bizhigang** [antvis/G2Plot#1659]
https://g2plot.antv.vision/zh/examples/general/title-description
链接404

**Comment by bizhigang** [comment]
![图片](https://user-images.githubusercontent.com/22189845/94385905-d8353100-0178-11eb-9bc8-c8d9ce1394a0.png)

**Comment by hustcc** [comment]
感谢反馈，后面文档网站的内容，可以统一回复，我们常驻一个 [issue](https://github.com/antvis/G2Plot/issues/1657)。

**Comment by bizhigang** [comment]
that will be ok
