### ISSUE TITLE
How to update data in treemap?

### ISSUE THREAD

**Issue by Madasamy26** [antvis/G2Plot#1662]
I have tried to use treemap with changedata() method for updating data !.

Initial rendering is working
`const data = {
  name: 'root',
  children: [
    { name: '分类 1', value: 560 },
    { name: '分类 2', value: 500 },
    { name: '分类 3', value: 150 },
    { name: '分类 4', value: 140 },
    { name: '分类 5', value: 115 },
    { name: '分类 6', value: 95 },
    { name: '分类 7', value: 90 },
    { name: '分类 8', value: 75 },
    { name: '分类 9', value: 98 },
    { name: '分类 10', value: 60 },
    { name: '分类 11', value: 45 },
    { name: '分类 12', value: 40 },
    { name: '分类 13', value: 40 },
    { name: '分类 14', value: 35 },
    { name: '分类 15', value: 40 },
    { name: '分类 16', value: 40 },
    { name: '分类 17', value: 40 },
    { name: '分类 18', value: 30 },
    { name: '分类 19', value: 28 },
    { name: '分类 20', value: 16 },
  ],
};

processData(data);
console.log("data",data)
const treemapPlot = new Treemap(document.getElementById('container'), {
  data,
  colorField: 'name',
});
treemapPlot.render();

function processData(data) {
  let sumValue = 0;
  each(data.children, (d) => {
    sumValue += d.value;
  });
  data.value = sumValue;
}

chart.changeData([]);`

what should be the data structure while using changeData() method in treemap?

**Comment by DarrenPei** [comment]
You can use treemapPlot.updateConfig() instead. I tried changeData() and it fails for treemap. I don't know why.

```js
import { Treemap } from '@antv/g2plot';
import { each } from '@antv/util';

const data = {
  name: 'root',
  children: [
    { name: '分类 1', value: 560 },
    { name: '分类 2', value: 500 },
    { name: '分类 3', value: 150 },
    { name: '分类 4', value: 140 },
    { name: '分类 5', value: 115 },
    { name: '分类 6', value: 95 },
    { name: '分类 7', value: 90 },
    { name: '分类 8', value: 75 },
    { name: '分类 9', value: 98 },
    { name: '分类 10', value: 60 },
    { name: '分类 11', value: 45 },
    { name: '分类 12', value: 40 },
    { name: '分类 13', value: 40 },
    { name: '分类 14', value: 35 },
    { name: '分类 15', value: 40 },
    { name: '分类 16', value: 40 },
    { name: '分类 17', value: 40 },
    { name: '分类 18', value: 30 },
    { name: '分类 19', value: 28 },
    { name: '分类 20', value: 16 },
  ],
};

processData(data);

const treemapPlot = new Treemap(document.getElementById('container'), {
  data,
  colorField: 'name',
});
treemapPlot.render();

const data2 = {
  name: 'root',
  children: [
    { name: '分类 1', value: 100 },
    { name: '分类 2', value: 100 },
    { name: '分类 3', value: 100 },
    { name: '分类 4', value: 100 },
    { name: '分类 5', value: 100 },
    { name: '分类 6', value: 95 },
    { name: '分类 7', value: 90 },
    { name: '分类 8', value: 75 },
    { name: '分类 9', value: 98 },
    { name: '分类 10', value: 60 },
    { name: '分类 11', value: 45 },
    { name: '分类 12', value: 40 },
    { name: '分类 13', value: 40 },
    { name: '分类 14', value: 35 },
    { name: '分类 15', value: 40 },
    { name: '分类 16', value: 40 },
    { name: '分类 17', value: 40 },
    { name: '分类 18', value: 30 },
    { name: '分类 19', value: 28 },
    { name: '分类 20', value: 16 },
  ],
};

processData(data2);

treemapPlot.updateConfig({
  data:data2,
});

treemapPlot.render();

function processData(data) {
  let sumValue = 0;
  each(data.children, (d) => {
    sumValue += d.value;
  });
  data.value = sumValue;
}
```

example from https://g2plot-v1.antv.vision/zh/examples/treemap/rect#basic

**Comment by Madasamy26** [comment]
Thanks...
We could use that ...but updateConfig() repaint everything

**Comment by hustcc** [comment]
> Thanks...
> We could use that ...but updateConfig() repaint everything

in fact, they are the same.
