### ISSUE TITLE
v2.0.1 折线图，title和description不显示

### ISSUE THREAD

**Issue by zangtian2** [antvis/G2Plot#1671]
![image](https://user-images.githubusercontent.com/20548146/94525160-3d1a8500-0266-11eb-9acd-9decf3ca79cb.png)
基本功能都不能保证，越做越回去了。官网文档也跟不上。
v2.0.1 折线图，title和description不显示，请尽快修复。

**Comment by zangtian2** [comment]
藏在语雀里说不支持，也是醉了

**Comment by Me-Momo** [comment]
> 藏在语雀里说不支持，也是醉了

api文档上没有写的 就是不支持的哦；并且v2不支持的原因也是在于业务定制可以加上更灵活的标题和描述

**Comment by hustcc** [comment]
升级文档听清楚的： https://g2plot.antv.vision/zh/docs/manual/upgrade#%E9%80%9A%E7%94%A8%E5%8F%98%E6%9B%B4
