### ISSUE TITLE
堆叠柱状图关于日期的bug

### ISSUE THREAD

**Issue by kooriookami** [antvis/G2Plot#1679]
G2版本2.0.1
https://codesandbox.io/s/p9bke
当横坐标为年月日日期时，最右边会莫名多1个数据。
![image](https://user-images.githubusercontent.com/38392315/94641672-76113300-0314-11eb-8b82-b9e1ac667647.png)
当把legend都关闭时，最右边会多2个数据。
![image](https://user-images.githubusercontent.com/38392315/94641690-82958b80-0314-11eb-8b68-5ede202c29ec.png)

**Comment by arcsin1** [comment]
这个是因为默认坐标轴会nice：true。解决办法可以这样： 
xAxis: {
    nice: false
  }

**Comment by hustcc** [comment]
> 这个是因为默认坐标轴会nice：true。解决办法可以这样： 
> 
> xAxis: {
> 
>     nice: false
> 
>   }
> 
> 

要不默认内部 x 轴都为false 吧

**Comment by arcsin1** [comment]
> > 这个是因为默认坐标轴会nice：true。解决办法可以这样：
> > xAxis: {
> > ```
> > nice: false
> > ```
> > 
> > 
> > }
> 
> 要不默认内部 x 轴都为false 吧

但是 横轴还是有问题 你看图 我刚测试了下也是

**Comment by arcsin1** [comment]
> > > 这个是因为默认坐标轴会nice：true。解决办法可以这样：
> > > xAxis: {
> > > ```
> > > nice: false
> > > ```
> > > 
> > > 
> > > }
> > 
> > 
> > 要不默认内部 x 轴都为false 吧
> 
> 但是 横轴还是有问题 你看图 我刚测试了下也是

倒是可以，但横轴计算时间还是有点问题

**Comment by arcsin1** [comment]
@kooriookami  可以这么解决 https://codesandbox.io/s/kind-chatterjee-uubyf?file=/index.js 时间的比例尺需要特殊处理一下，后续我们会优化到

**Comment by hustcc** [comment]
已经解决，节后发布版本。
