### ISSUE TITLE
[BUG] 双轴图 legend 渲染存在内存泄漏问题  (DualAxes组件)

### ISSUE THREAD

**Issue by dongxiaoyong009** [antvis/G2Plot#1684]
### 🐛 bug 描述 [详细地描述 bug，让大家都能理解]
双轴图 legend 渲染存在内存泄漏问题 每次更新渲染，不会清除原图例数据

### 📷 复现步骤 [清晰描述复现步骤，让别人也能看到问题]
![image](https://user-images.githubusercontent.com/13757451/95070590-ebc53680-073a-11eb-9fab-9c66aad9a4e5.png)
![image](https://user-images.githubusercontent.com/13757451/95070691-11524000-073b-11eb-8db1-de13a023f4c8.png)

### 💻 复现代码 [提供可复现的代码，仓库，或线上示例]
https://github.com/antvis/G2Plot/edit/master/src/plots/dual-axes/adaptor.ts
legend 方法(174行)

### © 版本信息

- ant-design-charts 版本: [e.g. 0.9.0]
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by hustcc** [comment]
@dongxiaoyong009 代码都定位到了， 有兴趣来一个 pr 吗？没有空的话，我就来了~

**Comment by dongxiaoyong009** [comment]
> @dongxiaoyong009 代码都定位到了， 有兴趣来一个 pr 吗？没有空的话，我就来了~

您来吧！国庆加班中😭

**Comment by dongxiaoyong009** [comment]
@hustcc 您来改吧，国庆赶进度加班中~

**Comment by hustcc** [comment]
> @hustcc 您来改吧，国庆赶进度加班中~

已经修复，已经比较大的问题。https://github.com/antvis/G2Plot/pull/1688 国庆后 cr 结束之后发布版本。
