### ISSUE TITLE
changeSize报错，现在有什么能改变宽和高度办法吗

### ISSUE THREAD

**Issue by potatozerg** [antvis/G2Plot#1685]
![image](https://user-images.githubusercontent.com/3282773/95131380-f1ffe680-072b-11eb-935c-f2a16178eec7.png)
g2还有changeWidth, changeHeight等function，但是g2plot貌似只有changeSize，而且会报错，

**Comment by hustcc** [comment]
@potatozerg 可以贴一下一个最小的报错的代码，或者一个 live demo。

暂时不会提供 changeWidth，changeHeight，知会保留 changeSize 方法，而且 G2 应该也没有 changeWidth, changeHeight 方法吧。

**Comment by potatozerg** [comment]
@hustcc 我明天弄下吧

**Comment by potatozerg** [comment]
@hustcc 突然就好了。。。
