### ISSUE TITLE
Invalid regular expression: invalid group specifier name

### ISSUE THREAD

**Issue by ytyt-yt** [antvis/G2Plot#1687]
lookbehind assertions is not supported by safari.

[This line](https://github.com/antvis/G2Plot/blob/master/src/utils/template.ts#L8) will crash the app on safari.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions#Browser_compatibility

@Me-Momo

**Comment by hustcc** [comment]
@ytyt-yt  refactor the function, pr is here https://github.com/antvis/G2Plot/pull/1689 , help give us a code review.

**Comment by dreamkai** [comment]
问题在于正式环境部署,jenkins自动构建,还是会安装依赖,如何解决

**Comment by hustcc** [comment]
> 问题在于正式环境部署,jenkins自动构建,还是会安装依赖,如何解决

这样，你把依赖改成 github 地址，这样保证代码最新，然后在你们环境验证 ok 了之后，我们就发布一个版本。

**Comment by dreamkai** [comment]
谢谢你,好的




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "hustcc"<notifications@github.com&gt;; 
发送时间: 2020年10月8日(星期四) 中午12:52
收件人: "antvis/G2Plot"<G2Plot@noreply.github.com&gt;; 
抄送: "1406731192"<1406731192@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [antvis/G2Plot] Invalid regular expression: invalid group specifier name (#1687)





  
问题在于正式环境部署,jenkins自动构建,还是会安装依赖,如何解决
  
这样，你把依赖改成 github 地址，这样保证代码最新，然后在你们环境验证 ok 了之后，我们就发布一个版本。

**Comment by hustcc** [comment]
v2.0.2 released.
