### ISSUE TITLE
文档中的style，感觉不生效

### ISSUE THREAD

**Issue by wlc11070108** [antvis/G2Plot#1692]
希望在柱子上加手型感觉
![1602215110(1)](https://user-images.githubusercontent.com/43594167/95541066-f1659980-0a24-11eb-849b-638e10e4e672.jpg)
这个属性写上去都没效果

**Comment by hustcc** [comment]
什么版本？我这边在最新版本 v2 中是 ok 的。

```ts
// 柱形图是 column，调试图是 bar
columnStyle: {
   cursor: 'pointer',
}
```

![image](https://user-images.githubusercontent.com/7856674/95541203-5ae5a800-0a25-11eb-818c-62bfbcc96bf0.png)
