### ISSUE TITLE
混合图表一些疑问

### ISSUE THREAD

**Issue by chengmings** [antvis/G2Plot#1696]
混合图表的 分组柱+折线混合图表 如何让柱状图的y轴展示百分比 就是后端返回0.1 就展示10%
混合图标的 分组柱+折线混合图表 如何让隐藏对某一个字段的tooltip进行隐藏？  比如说我想隐藏折线图的tooltip 并且折线图数据的字段和柱状图的一样

**Comment by hustcc** [comment]
使用 tooltip.customContent 配置实现。

```ts
tooltip: {
    customContent: (a, b) => {
      console.log(a, b);
      return `
      <div class="g2-tooltip-title">2019-03</div>
      <ul class="g2-tooltip-list">
        <li class="g2-tooltip-list-item">
          <span class="g2-tooltip-marker" style="background: rgb(91, 143, 249); width: 8px; height: 8px; border-radius: 50%; display: inline-block; margin-right: 8px;"></span>
          <span class="g2-tooltip-name">uv</span>:
          <span class="g2-tooltip-value">350</span>
        </li>
      </ul>
      `;
    },
  }
```

![image](https://user-images.githubusercontent.com/7856674/95642609-179a4080-0adc-11eb-9385-f9ee7c0cce1b.png)

**Comment by chengmings** [comment]
> ```ts
> tooltip: {
>     customContent: (a, b) => {
>       console.log(a, b);
>       return `
>       <div class="g2-tooltip-title">2019-03</div>
>       <ul class="g2-tooltip-list">
>         <li class="g2-tooltip-list-item">
>           <span class="g2-tooltip-marker" style="background: rgb(91, 143, 249); width: 8px; height: 8px; border-radius: 50%; display: inline-block; margin-right: 8px;"></span>
>           <span class="g2-tooltip-name">uv</span>:
>           <span class="g2-tooltip-value">350</span>
>         </li>
>       </ul>
>       `;
>     },
>   }
> ```
你这个方法是v2版本的  这个版本是刚更新的 v1版本这样子是实现不了的
