### ISSUE TITLE
通过js引入，https://unpkg.com/@antv/g2plot@latest/dist/g2plot.js这个路径找不到

### ISSUE THREAD

**Issue by jianlei** [antvis/G2Plot#1702]
通过js引入，https://unpkg.com/@antv/g2plot@latest/dist/g2plot.js这个路径找不到

**Comment by hustcc** [comment]
这个地址： https://unpkg.com/@antv/g2plot@latest/dist/g2plot.min.js

**Comment by jianlei** [comment]
![16801602316179_ pic_hd](https://user-images.githubusercontent.com/3015301/95649547-75e11680-0b10-11eb-9c47-e18a54ecdfd1.jpg)
使用这个地址后报以上报错

**Comment by jianlei** [comment]
@hustcc

**Comment by jianlei** [comment]
引入此文件后好使了
https://cdn.bootcss.com/babel-polyfill/6.23.0/polyfill.min.js

**Comment by hustcc** [comment]
恩恩，业务层需要自己引入 polyfill~
