### ISSUE TITLE
Stacked area behaviour in v2

### ISSUE THREAD

**Issue by solovieff** [antvis/G2Plot#1706]
Hi, is there any way to achieve the following behaviour:
<img width="1182" alt="image" src="https://user-images.githubusercontent.com/5033247/95743877-20854080-0c9b-11eb-8d65-3ea7bda856b8.png">

I did not found a proper way, so I added colors to config in the following way:
`color: ["#5ad8a6", "#499871", "#ffffff"]`

So I faked the last colour to be white and it looked ok. After I faked the color, I faked the data a bit, and my graph looks exactly as on the image.

Before v2 we also had a formatter property for the tooltip, so I replaced the value for the tooltip and had it correct despite of my data was changed. Now formatter property is gone and I am stuck: the graphs do not work as expected now.

**Comment by hustcc** [comment]
what is your problem of tooltip in v2? What do you want to format?

**Comment by solovieff** [comment]
Values in stack are sum, so I fake the values, as I said. For example, the value of "Most Probable" is in fact the sum of "Worst Case" and "Most Probable" shown on my picture, but having real values wont give me the needed graph.

In other words, I need to show the full Y coordinate, not the value I have now. The tooltip should be: 

Best Case: 1 292 960
Most Probable: 1 261 805
Worst Case: 1 097 360 (works now and seen on the picture).

When I had a formatter I could show any values for any date. No I have no idea how to create the chart I need. Looks like I'll have to use "content", or so, and draw the elem myself.

**Comment by hustcc** [comment]
Next version, will has an option named `isStack`, default is `true`. will be released before 10-15.
