### ISSUE TITLE
设置 tickInterval 后 tickCount 失效

### ISSUE THREAD

**Issue by mice33** [antvis/G2Plot#1709]
![image](https://user-images.githubusercontent.com/4945433/95829914-7b856900-0d69-11eb-975a-22d39fdd04ca.png)

在未设置 `tickInterval`，会出现小数点，业务上只会出现整数，所以设置了 `tickInterval: 1`

![image](https://user-images.githubusercontent.com/4945433/95830137-d15a1100-0d69-11eb-97b7-55979db083af.png)

现在都是一样数值不会有问题，但差异过大后就有出现很多条

![image](https://user-images.githubusercontent.com/4945433/95830218-ed5db280-0d69-11eb-9692-4147477d8b1f.png)

![image](https://user-images.githubusercontent.com/4945433/95830260-fcdcfb80-0d69-11eb-9d59-7bc548c9adae.png)

设置 `tickCount` 后也没有效果，不知道是不是我使用错误了。。

**Comment by mice33** [comment]
使用版本 `"@antv/g2plot": "1.1.27"`

**Comment by hustcc** [comment]
> tickCount = (max - min) / tickInterval;

两者有上述关系，所以没有办法两个同时生效。
