### ISSUE TITLE
v2 如何设置无堆积效果的多组面积图

### ISSUE THREAD

**Issue by xiecg** [antvis/G2Plot#1710]
现在 seriesField 设置的分组都是有堆积效果的，请问如何设置一个无堆积效果的多组面积图 ？

效果如图：

![image](https://user-images.githubusercontent.com/10857932/95831687-edf74880-0d6b-11eb-8f1d-28682364b9ab.png)

**Comment by hustcc** [comment]
下一个版本会增加 isStack 配置，默认为 true。大概在周四发布！
