### ISSUE TITLE
图表Y轴

### ISSUE THREAD

**Issue by chengmings** [antvis/G2Plot#1718]
- Y轴的最大值最小值能够自适应数据的吗？就是当数据中最小的为2000+的时候 y的min能够自适应为2000吗
- Y轴刻度能够1以一个刻度为间隔吗？就是当间隔50的时候   Y轴就为0  50  100  150  200

**Comment by hustcc** [comment]
![image](https://user-images.githubusercontent.com/7856674/95940151-4b44d580-0e10-11eb-9701-2d8b57efd47b.png)

```ts
import { Line } from '@antv/g2plot';

fetch('https://gw.alipayobjects.com/os/bmw-prod/1d565782-dde4-4bb6-8946-ea6a38ccf184.json')
  .then((res) => res.json())
  .then((data) => {
    const line = new Line('container', {
      data,
      padding: 'auto',
      xField: 'Date',
      yField: 'scales',
      xAxis: {
        type: 'timeCat',
        tickCount: 5,
      },
      yAxis: {
        tickInterval: 100,
        min: 200,
        max: 3000,
        nice: false,
      },
    });

    line.render();
  });

```

**Comment by chengmings** [comment]
> ![image](https://user-images.githubusercontent.com/7856674/95940151-4b44d580-0e10-11eb-9701-2d8b57efd47b.png)
> 
> ```ts
> import { Line } from '@antv/g2plot';
> 
> fetch('https://gw.alipayobjects.com/os/bmw-prod/1d565782-dde4-4bb6-8946-ea6a38ccf184.json')
>   .then((res) => res.json())
>   .then((data) => {
>     const line = new Line('container', {
>       data,
>       padding: 'auto',
>       xField: 'Date',
>       yField: 'scales',
>       xAxis: {
>         type: 'timeCat',
>         tickCount: 5,
>       },
>       yAxis: {
>         tickInterval: 100,
>         min: 200,
>         max: 3000,
>         nice: false,
>       },
>     });
> 
>     line.render();
>   });
> ```
  min max方法文档里面看到了 我想说的是动态

**Comment by hustcc** [comment]
```ts
nice: false,
```
上面加上，就会自适应 min max。

另外一个问题是什么？ tickInterval 有没有在文档吗？
