### ISSUE TITLE
柱线混合图的字段别名配置不生效 api也是错误的、希望可以配置两个yField的别名、可以在图表中正确展示

### ISSUE THREAD

**Issue by fanlu-778** [antvis/G2Plot#1722]
柱线混合图的字段别名配置不生效 api也是错误的、希望可以配置两个yField的别名、可以在图表中正确展示
![image](https://user-images.githubusercontent.com/69622916/95958943-6c1f2200-0e34-11eb-860a-e7f77b48be9f.png)

**Comment by hustcc** [comment]
使用 v2 版本试试吧，v1 暂时不迭代更新了。
