### ISSUE TITLE
Full list of eventNames?

### ISSUE THREAD

**Issue by JoeCMorgan** [antvis/G2Plot#1723]
Is there a full list of eventNames anywhere? I have tried `element` and `plot` but neither work for what I need.

https://g2plot.antv.vision/en/docs/manual/plots/column#eventname

**Comment by hustcc** [comment]
Document about event is on the way.

Expected before next friday.

**Comment by hustcc** [comment]
The new documents about event is [here](https://github.com/antvis/G2/pull/2931/files), new site will be deployed soon.
