### ISSUE TITLE
建议 tooltip 补充 formatter 方法

### ISSUE THREAD

**Issue by xiecg** [antvis/G2Plot#1724]
![image](https://user-images.githubusercontent.com/10857932/96068488-be148600-0ece-11eb-883e-c28aa478c188.png)

因为 v2 没有百分比堆叠面积图了，自己实现 tooltip 的数值需要转换，但是 customContent 使用成本较高，而且用户体验也不好，所以建议补充 formatter 方法。

另外关于 customContent 体验不好这点，我发现每次鼠标移动都是创建一次dom，tooltip 也就没有了流畅的移动效果。官网的百分比柱状图就是例子。https://g2plot.antv.vision/zh/examples/column/percent

![image](https://user-images.githubusercontent.com/10857932/96069222-4d6e6900-0ed0-11eb-8276-c7f8cb4fd8fb.png)

而且有了 formatter 百分比这块也就不需要用 customContent 了
![image](https://user-images.githubusercontent.com/10857932/96069361-a5a56b00-0ed0-11eb-86e6-74327ab4260e.png)

**Comment by lxfu1** [comment]
不错的提议
