### ISSUE TITLE
文档 404 链接

### ISSUE THREAD

**Issue by afc163** [antvis/G2Plot#1726]
link | visit
-- | --
https://g2plot.antv.vision/zh/examples/advanced/connection | 28
https://g2plot.antv.vision/en/examples/advanced/connection | 3
https://g2plot.antv.vision/zh/docs/manual/plots/range-bar | 2
https://g2plot.antv.vision/zh/examples/column/percent-stacked#basic | 2
https://g2plot.antv.vision/zh/examples/step-line/basic | 2
https://g2plot.antv.vision/en/docs/scatter/basic#shape-mapping | 1
https://g2plot.antv.vision/en/examples/docs/manual/graphic-style | 1
https://g2plot.antv.vision/en/examples/general/title-description/API | 1
https://g2plot.antv.vision/en/examples/general/tooltip#isolate-tooltip | 1
https://g2plot.antv.vision/zh/docs/manual/about-g2 | 1
https://g2plot.antv.vision/zh/docs/manual/plots/bubble | 1
https://g2plot.antv.vision/zh/docs/manual/plots/heatmap | 1
https://g2plot.antv.vision/zh/examples/area/percent-stacked/API | 1
https://g2plot.antv.vision/zh/examples/bar/percent-stacked/design/ | 1
https://g2plot.antv.vision/zh/examples/column/histogram | 1
https://g2plot.antv.vision/zh/examples/general/tooltip#tooltip-inner-chart | 1
https://g2plot.antv.vision/zh/examples/heatmap/basic#basic | 1
https://g2plot.antv.vision/zh/examples/rose/rose | 1

**Comment by hustcc** [comment]
@afc163 这些地址应该都是从 issue，搜索等来的。新旧网站更替，就网站的部分地址在新网站是没有，这种应该无法处理吧。比如新版中都不存在 bubble，step-line 这类。

这种情况，应该怎么去处理最好？

**Comment by afc163** [comment]
第一个不是，在首页这里：

<img width="387" alt="image" src="https://user-images.githubusercontent.com/507615/96108205-e2dd1d80-0f0f-11eb-837c-0e333caecb32.png">

其他外部跳进来的，持续关注一下，流量大的可以用 [redirects](https://github.com/antvis/gatsby-theme-antv) 做一个跳转。只有一两个点击的不管就行了。
