### ISSUE TITLE
v2 雷达图 legend 配置无效

### ISSUE THREAD

**Issue by xiecg** [antvis/G2Plot#1727]
![image](https://user-images.githubusercontent.com/10857932/96089055-def1d100-0ef8-11eb-8aa0-aaa16399a8e5.png)

**Comment by lxfu1** [comment]
@Me-Momo legend 是故意去掉的吗？

**Comment by Me-Momo** [comment]
没有加吧

**Comment by lxfu1** [comment]
> 没有加吧

嗯嗯 我晚上一起添加了

**Comment by Me-Momo** [comment]
> > 没有加吧
> 
> 嗯嗯 我晚上一起添加了

👍 还有label，用使用 common 下的 adaptor 吧
