### ISSUE TITLE
description配置为null的时候 出错

### ISSUE THREAD

**Issue by Me-Momo** [antvis/g2plot#173]
错误信息
![image](https://user-images.githubusercontent.com/15646325/68064214-d0e08a00-fd53-11e9-8be8-1392987ef15c.png)

**Comment by paleface001** [comment]
这个是因为title和description的配置项调整为跟其他组件一样了，可以用`visible:false`关闭显示。
没有跟你们同步，我的责任。

**Comment by Me-Momo** [comment]
可是，默认不是可以不配置吗？不配置的话`props.description`就是空了，这里就会报错了

**Comment by hustcc** [comment]
关于 visible 的配置好像确实变得复杂了一些，后面在讨论吧。这期保证文档和实现一致就可以了。
