### ISSUE TITLE
v2 漏斗图 legend & meta 配置无效

### ISSUE THREAD

**Issue by xiecg** [antvis/G2Plot#1736]
legend
![image](https://user-images.githubusercontent.com/10857932/96222742-5db14180-0fbf-11eb-8c84-ba3ca40c4383.png)

meta
![image](https://user-images.githubusercontent.com/10857932/96223305-46bf1f00-0fc0-11eb-9597-b9bcbc505998.png)

https://codesandbox.io/s/great-shockley-cdcdo?file=/index.js

**Comment by liuzhenying** [comment]
跟随下个版本修复
