### ISSUE TITLE
v2 环图交互问题

### ISSUE THREAD

**Issue by xiecg** [antvis/G2Plot#1737]
hover 一个分类 statistic 内容显示又隐藏掉了

![image](https://user-images.githubusercontent.com/10857932/96224480-3d36b680-0fc2-11eb-8c66-5ea260d56760.png)

https://g2plot.antv.vision/zh/examples/pie/donut#statistics

**Comment by hustcc** [comment]
> hover 一个分类 statistic 内容显示又隐藏掉了
> 
> ![image](https://user-images.githubusercontent.com/10857932/96224480-3d36b680-0fc2-11eb-8c66-5ea260d56760.png)
> 
> https://g2plot.antv.vision/zh/examples/pie/donut#statistics

已经修复，在版本中了，稍等，今天发布。
