### ISSUE TITLE
npm 安装的2.0.2的分组条形图和堆积柱状图legend:false, 不生效

### ISSUE THREAD

**Issue by HUGHHUXIAOJUN** [antvis/G2Plot#1740]
官网的单词也写错了，https://g2plot.antv.vision/zh/docs/manual/plots/bar#legend;
我在官网https://g2plot.antv.vision/zh/examples/bar/grouped这边设置是有效的,复制到自己代码就没用了

**Comment by hustcc** [comment]
v2.0.3 解决了这个问题。https://github.com/antvis/G2Plot/issues/1717
