### ISSUE TITLE
图表在缩放状态下，导致鼠标位置偏移

### ISSUE THREAD

**Issue by LazyJoke** [antvis/G2Plot#1743]
🐛 bug 描述

给图表组件父级节点添加 transform: scale(0.5) 样式，会导致鼠标在图表中的位置偏移，不能准确触发 hover 效果

🏞 期望结果

缩放后鼠标在图表内的位置应该能准确触发原本的 hover 效果

**Comment by hustcc** [comment]
2.x版本下，增加配置 supportCSSTransform: true

**Comment by kuangxianfeng** [comment]
可是线条会变得非常模糊
