### ISSUE TITLE
V2 Wordcloud tooltip is displaying coordinates instead of weight

### ISSUE THREAD

**Issue by pjeannet** [antvis/G2Plot#1754]
While testing migration from v1 to v2 I noticed that the wordcloud charts we used broke.
One of the bug I could identify is that the value for each word displayed in the tooltip seems random and is not the weight.
If you go to the [sample page](https://g2plot.antv.vision/en/examples/word-cloud/basic#basic) (or image below) you can see that  : 
* colors and borders are strange (one of the other bugs)
* tooltip is showing what looks like coordinates instead of the weight value
![image](https://user-images.githubusercontent.com/6052793/96607255-76d82c00-12f8-11eb-85d2-6b9e34f05466.png)
The [react samples](https://charts.ant.design/demos/word-cloud#wordcloud) are also buggy but not as much! (using an older version I think) :
* colors are fine
* tooltip is only showing abscissa
![image](https://user-images.githubusercontent.com/6052793/96607819-07167100-12f9-11eb-98a7-e606ccc23392.png)
I think what we expect to see was something like this (source is the [v1 samples](https://g2plot-v1.antv.vision/en/examples/word-cloud/basic))
![image](https://user-images.githubusercontent.com/6052793/96607548-c0c11200-12f8-11eb-86a8-33d6d74ae856.png)

**Comment by zhangzhonghe** [comment]
close #1754 via #1762
