### ISSUE TITLE
V2 条形图设置label: true报错

### ISSUE THREAD

**Issue by yuruwang** [antvis/G2Plot#1756]
V2中柱状图和其他图表可以直接配置label: true来展示标签，但是在条形图中这么配置会报错：
柱状图中配置可以成功：
![image](https://user-images.githubusercontent.com/31492974/96668277-645c0200-138d-11eb-9ea1-6a86b7f52e77.png)

条形图中配置会报错：
![image](https://user-images.githubusercontent.com/31492974/96668318-8190d080-138d-11eb-8733-de29dc55a30e.png)

希望条形图也能支持label: boolean这样的配置，和其他图表保持一致

**Comment by lxfu1** [comment]
label: {}

**Comment by zqlu** [comment]
不支持 true 来配置：

```ts
export type Label =
  | false
  | ({
      /** 映射的字段。 */
      readonly fields?: string[];
      /** 回调函数。 */
      readonly callback?: LabelCallback;
      /** 功能同 content ，兼容 v1 */
      readonly formatter?: GeometryLabelCfg['content'];
    } & GeometryLabelCfg);
```
