### ISSUE TITLE
使用tooltip formatter后格式问题

### ISSUE THREAD

**Issue by kooriookami** [antvis/G2Plot#1757]
未使用formatter格式是这样
![image](https://user-images.githubusercontent.com/38392315/96671287-05e65200-1394-11eb-92ef-bd32809d8018.png)
formatter后格式这样
![image](https://user-images.githubusercontent.com/38392315/96671306-0f6fba00-1394-11eb-94c5-b66f7727e0f1.png)
上方title变粗了，占用率左侧的圆点不见了

**Comment by lxfu1** [comment]
下个迭代修复， 周五会发布新版本。
