### ISSUE TITLE
V2 迷你面积图 折线颜色无法配置

### ISSUE THREAD

**Issue by yuruwang** [antvis/G2Plot#1758]
v2版本中的迷你面积图的line配置了color但是不生效，还是默认的颜色
![image](https://user-images.githubusercontent.com/31492974/96682649-b449c180-13ab-11eb-8b14-33b8c3852bbd.png)

**Comment by hustcc** [comment]
感谢反馈。内部一个优先级处理的问题，style 优先级高于 color。你先按照下面的来处理，这个本周五会发布版本解决。

```ts
line: {
  style: 
       stroke: 'red',
    },
},
```
