### ISSUE TITLE
雷达图的问题！请问当3个维度值一样就变成点了，现在支持呈现为等边三角形吗？

### ISSUE THREAD

**Issue by wangBo199six** [antvis/G2Plot#1768]
const radarPlot = new Radar('container', {
      data: [
        {
          item: 'Design',
          user: 'a',
          score: 70
        },
        {
          item: 'Development',
          user: 'a',
          score: 70
        },
        {
          item: 'Marketing',
          user: 'a',
          score: 70
        }
      ],
      xField: 'item',
      yField: 'score',
      meta: {
        score: {
          alias: '分数',
        },
      },
      xAxis: {
        line: null,
        tickLine: null,
        grid: {
          line: {
            style: {
              lineDash: null,
            },
          },
        },
      },
      point: {},
    });
    radarPlot.render();``

**Comment by hustcc** [comment]
增加这个配置可以剞劂：

```ts
meta: {
    score: {
      alias: '分数',
      min: 0,
      max: 100,
    },
  },
```

**Comment by hustcc** [comment]
会在 G2Plot 解决掉：如果 y scale.values 的数组去重之后为 1 的时候，那么就设置 min: 0, max = v * 2
