### ISSUE TITLE
V2 双轴图设置column的颜色后legend颜色没有对应生效

### ISSUE THREAD

**Issue by yuruwang** [antvis/G2Plot#1770]
如下图，在左Y轴设置column的颜色后，柱子的颜色生效了，但是对应的legend颜色还是默认的颜色。但是右Y轴的颜色是都生效的
![image](https://user-images.githubusercontent.com/31492974/96950939-00b50e80-151e-11eb-9883-0c543fb3c147.png)

**Comment by liuzhenying** [comment]
已复现，将尽快修复
