### ISSUE TITLE
【雷达图问题】请问如果雷达图的维度的文本太长了，如何显示省略号？

### ISSUE THREAD

**Issue by wangBo199six** [antvis/G2Plot#1775]
请问如果雷达图的维度的文本太长了，如何显示省略号，并且鼠标移上去会有类似于title这样的特性显示全部文字。

**Comment by hustcc** [comment]
目前对于非直角坐标系的图表，axis label 没有做自动碰撞检测和省略，所以目前只能在业务层代码对于超长的文本进行一个省略和缩短。
