### ISSUE TITLE
分组柱状图数据单位不一样 tooltip 如何分别设置数据单位

### ISSUE THREAD

**Issue by aguoshuai** [antvis/G2Plot#1778]
{name: "信件数量", countryName: "包河区", value: 730}
1: {name: "信件数量", countryName: "合肥新站高新区", value: 213}
2: {name: "信件数量", countryName: "合肥滨湖科学城", value: 4}
3: {name: "信件数量", countryName: "合肥经开区", value: 234}
4: {name: "信件数量", countryName: "合肥高新区", value: 191}
5: {name: "信件数量", countryName: "安徽巢湖经开区", value: 2}
6: {name: "信件数量", countryName: "巢湖市", value: 65}
7: {name: "信件数量", countryName: "庐江县", value: 73}
8: {name: "信件数量", countryName: "庐阳区", value: 474}
9: {name: "信件数量", countryName: "瑶海区", value: 578}
10: {name: "信件数量", countryName: "肥东县", value: 287}
11: {name: "信件数量", countryName: "肥西县", value: 572}
12: {name: "信件数量", countryName: "蜀山区", value: 654}
13: {name: "信件数量", countryName: "长丰县", value: 251}
14: {name: "平均处理时间", countryName: "包河区", value: 236}
15: {name: "平均处理时间", countryName: "合肥新站高新区", value: 160}
16: {name: "平均处理时间", countryName: "合肥滨湖科学城", value: 182}
17: {name: "平均处理时间", countryName: "合肥经开区", value: 229}
18: {name: "平均处理时间", countryName: "合肥高新区", value: 222}
19: {name: "平均处理时间", countryName: "安徽巢湖经开区", value: 481}
20: {name: "平均处理时间", countryName: "巢湖市", value: 450}
21: {name: "平均处理时间", countryName: "庐江县", value: 229}
22: {name: "平均处理时间", countryName: "庐阳区", value: 212}
23: {name: "平均处理时间", countryName: "瑶海区", value: 208}
24: {name: "平均处理时间", countryName: "肥东县", value: 192}
25: {name: "平均处理时间", countryName: "肥西县", value: 199}
26: {name: "平均处理时间", countryName: "蜀山区", value: 276}
27: {name: "平均处理时间", countryName: "长丰县", value: 220}

数据是这样的，tooltip中我想让信件数量的单位显示"件"，平均处理时间的单位显示"小时"，请问应该怎么写

**Comment by hustcc** [comment]
你的代码是怎么样的？

**Comment by aguoshuai** [comment]
const config = {
	forceFit: true,
    data,
    xField: 'countryName',
    yField: "value",
    yAxis: { min: 0 },
    meta: {
      countryName: { alias: ' ' },
      value:{ alias: ' ' },
    },
    label: { visible: true },
    groupField: 'name',
    color: ['#1ca9e6', '#f88c24'],
    
  };
这个就是分组柱状图的代码

**Comment by hustcc** [comment]
在 v2.0.5 版本 中的解法：

```ts
{
  tooltip: {
    formatter: function(datum) {
      const { countryName, value, name } = datum;
      if (name === '平均处理时间') { return { name: name, value: value + '小时' }; }
      else { return { name: name, value: value + '件' }; }
   }
  }
}
```

2.0.5 本周末发布。
