### ISSUE TITLE
图形样式配置参数名可否统一

### ISSUE THREAD

**Issue by kagawagao** [antvis/G2Plot#1787]
子弹图的图形样式配置项为 [`style`](https://g2plot.antv.vision/zh/docs/manual/plots/bullet#style-)，而其他图表的配置项为 [`xxxStyle`](https://g2plot.antv.vision/zh/docs/manual/plots/bar#barstyle)，可以统一为 `xxxStyle`，同时也不会与原生 css 样式产生歧义

**Comment by hustcc** [comment]
因为 bullet 的配置有些不一样，style 中包含了三个细分组件的配置。

**Comment by arcsin1** [comment]
这个style跟其他图形的配置是不一样的哦，为了尽量简化属性的配置，减少api的数量，我们择中统一在一起了。
涉及到有比如：label，size，color, style 这4个属性，你会用着更舒心的 https://g2plot.antv.vision/zh/examples/bullet/basic/API

thanks！

**Comment by kagawagao** [comment]
主要是会和 DOM 原生属性冲突
https://github.com/open-data-plan/g2plot-react/blob/b3f93ab96056038759ae0e06d82aa506544c4875/src/components/base/index.tsx#L145

我在封装组件的时候，将配置项当做 `Props` 传递给组件，因此 `bullet.style` 会和原生 DOM 属性冲突

**Comment by arcsin1** [comment]
> 主要是会和 DOM 原生属性冲突
> https://github.com/open-data-plan/g2plot-react/blob/b3f93ab96056038759ae0e06d82aa506544c4875/src/components/base/index.tsx#L145
> 
> 我在封装组件的时候，将配置项当做 `Props` 传递给组件，因此 `bullet.style` 会和原生 DOM 属性冲突

嗯，理解了，准备修复一下这个问题，带来一些困扰麻烦了！

**Comment by hustcc** [comment]
周五发布版本，包含这个。
