### ISSUE TITLE
BI 使用过程中问题汇总

### ISSUE THREAD

**Issue by hustcc** [antvis/G2Plot#1797]
# 折线图、面积图

 - [x] limitInPlot 问题（开启了会导致点被裁剪，不开启，设置 min 有会挂掉。）

# 柱形图、条形图 系列

 - [x] 轴标签抽样
 - [x] 数据标签
 - [x] x 轴后两个标签重叠
 - [ ] x 轴 padding 过程中旋转，被裁剪

# 饼、环图

 - [ ] label 移除 plot range
 - [ ] 提供一个大数据量的数据标签样式
 - [ ] Pie 设置legend的offsetX后点击操作图例里的选项会位置重置 #1729
- [ ] inner label 的布局算法 · 沉淀

![image](https://user-images.githubusercontent.com/15646325/100200936-4d836f00-2f3a-11eb-89ba-0f560e99c2a8.png)

# 双轴图

- [x] https://github.com/antvis/G2Plot/issues/1881

# 散点图

 - [x] 回归线，拟合线
 - [ ] 回归线 多项式阶数，指数底等配置暴露

# 雷达图
- [ ] 标签溢出 @Me-Momo 
![image](https://user-images.githubusercontent.com/15646325/100189769-e6f55580-2f27-11eb-8823-a2f2b4dd30ff.png)

# 词云图

 - [x] 词云图稳定布局，自定义布局 #1755

# 漏斗

# 对称漏斗

# 仪表盘

# 进度条

# 矩阵树图

# 其他

 - [ ] legend 分页开启后，window 下头部被裁减，应该是 bbox 不对。
![image](https://user-images.githubusercontent.com/7856674/97283508-e4e19d80-187a-11eb-9ddb-7bb546dc23cb.png)

# 场景 DEMO

 - [x] 高亮联动 @hustcc
 - [ ] 绝对值、比例值指标双轴图 @liuzhenying

> 业务场景如：左边为金额型或数值型指标，右边为百分比指标（支付笔数 & 渗透率）

 - [x] 自定义 tooltip 按钮，链接 @lxfu1

> tooltip 上带按钮，可以 hover 进去操作

> tooltip 超多明细数据，最大高度限制，可以 hover 进去滚动展示

 - [x] 自定义交互（图例 hover） @Me-Momo 
 - [x] label 上链接 @lxfu1 
 - [ ] 拖拽柱形图，影响数据 @zqlu
 - [x] 补充 theme 配置化 demo @Me-Momo

**Comment by Cuiyansong** [comment]
您好，请问回归散点图是否有开发计划支持展示拟合函数？
下面是EChart展示拟合函数的示例：
![WX20230221-nihe](https://user-images.githubusercontent.com/4497555/220291806-35ae56f7-83b2-4693-b9ee-88437afd3eca.png)
