### ISSUE TITLE
label 文字重叠

### ISSUE THREAD

**Issue by zhouxinyong** [antvis/G2Plot#1799]
官网示例：[https://g2plot.antv.vision/zh/examples/pie/basic#spider-label](https://g2plot.antv.vision/zh/examples/pie/basic#spider-label)

复现步骤：
1. 复制代码，设置容器高度为200px，生成的图表，label文字重叠。

![image](https://user-images.githubusercontent.com/15569753/97271897-2585ea80-186c-11eb-956d-dfaa3fa80a1e.png)

2. 调整容器高度为500px，生成的图表，label文字不重叠。

![image](https://user-images.githubusercontent.com/15569753/97272086-61b94b00-186c-11eb-9291-28285c41419c.png)

没有找到配置项可以解决这个问题

**Comment by Me-Momo** [comment]
设置一下labelHeight看看

**Comment by Me-Momo** [comment]
![image](https://user-images.githubusercontent.com/15646325/97273208-fec8b380-186d-11eb-8f31-8a7142564573.png)
如果文本是多行的 设置一下，根据具体的情况设置

**Comment by zhouxinyong** [comment]
@Me-Momo 可以了，这个属性在文档里没有找到。
另外： label的content是否可以支持自定义html

**Comment by Me-Momo** [comment]
> @Me-Momo 可以了，这个属性在文档里没有找到。
> 另外： label的content是否可以支持自定义html

嗯嗯，具体属性值我会补充下；label content 暂时不支持 html，可以考虑使用 group
