### ISSUE TITLE
柱线混合图默认颜色问题

### ISSUE THREAD

**Issue by 0xDarker** [antvis/G2Plot#1806]
不给折线图设置颜色的时候，
1.  折线图的所有series都是一样的颜色
2. 如果折线图放在柱形图前面，折线图和柱形图都是一样的颜色

![image](https://user-images.githubusercontent.com/13844947/97399903-144ee380-1929-11eb-9949-2c5a51a0de37.png)

![image](https://user-images.githubusercontent.com/13844947/97399820-e23d8180-1928-11eb-9311-364fcde2ac97.png)

**Comment by liuzhenying** [comment]
这个默认颜色，原来是线左蓝右红，柱跟随 theme 色板。下个版本会按照设计师的设计再做优化，这个还请先赋值颜色使用

**Comment by 0xDarker** [comment]
> 这个默认颜色，原来是线左蓝右红，柱跟随 theme 色板。下个版本会按照设计师的设计再做优化，这个还请先赋值颜色使用

主要使用场景是数据不是固定的，series个数也就不固定没法单独设置颜色。
或者，有没有提供从theme色板取色的接口？

**Comment by hustcc** [comment]
> > 这个默认颜色，原来是线左蓝右红，柱跟随 theme 色板。下个版本会按照设计师的设计再做优化，这个还请先赋值颜色使用
> 
> 主要使用场景是数据不是固定的，series个数也就不固定没法单独设置颜色。
> 或者，有没有提供从theme色板取色的接口？

一般都是提供 10 色、20 色的色板。包括 G2 内部也是使用色板的形式，如果维值超过这个色板，就会重复。

**Comment by liuzhenying** [comment]
> > 这个默认颜色，原来是线左蓝右红，柱跟随 theme 色板。下个版本会按照设计师的设计再做优化，这个还请先赋值颜色使用
> 
> 主要使用场景是数据不是固定的，series个数也就不固定没法单独设置颜色。
> 或者，有没有提供从theme色板取色的接口？

这个不需要单独设置颜色，例如

{
      geometry: 'line',
      seriesField: 'name',
      color: ['#f00', '#0f0'],
}

给 color 赋值后，当线多于两条时，会重复 color，所以可以先使用 color 属性定义颜色

**Comment by 0xDarker** [comment]
> > > 这个默认颜色，原来是线左蓝右红，柱跟随 theme 色板。下个版本会按照设计师的设计再做优化，这个还请先赋值颜色使用
> > 
> > 
> > 主要使用场景是数据不是固定的，series个数也就不固定没法单独设置颜色。
> > 或者，有没有提供从theme色板取色的接口？
> 
> 可以使用 color 定义色板，例如
> 
> {
> geometry: 'line',
> seriesField: 'name',
> color: ['#f00', '#0f0'],
> }
> 
> 给 color 赋值后，当线多于两条时，会重复 color，所以可以先使用 color 属性定义颜色

好的，辛苦了
