### ISSUE TITLE
【bug】autoFit为true时，默认高度为25（API中描述为400）。

### ISSUE THREAD

**Issue by catCarrot** [antvis/G2Plot#1807]
问题版本：2.0.0及以上
问题描述：设置 autoFit: true，统计图的实际生成高度为25。
理想状态：根据API的描述，统计图实际高度应为400。

**其他**
版本：1.1.27及以下
现象：高度为400，与API中描述相符。

**Comment by hustcc** [comment]
感谢反馈，autoFit 下高度会自动变成容器的高度。建议你外部容器 div 使用 css 确定高度，或者指定一下图表高度。文档我们会修改掉。
