### ISSUE TITLE
V2 折线图x轴标签和title重叠问题优化

### ISSUE THREAD

**Issue by yuruwang** [antvis/G2Plot#1820]
在折线图或者其他轴类图表中，当轴标签旋转后，标签高度不固定，无法通过设置offset或者spacing让轴title不与轴标签重叠，期望的效果如下图：
![image](https://user-images.githubusercontent.com/31492974/97650105-ea660000-1a93-11eb-9c71-548111e7e69c.png)

**Comment by hustcc** [comment]
@lxfu1 这个问题你看一下吧，熟悉一下 G2 底层的代码。

**Comment by lxfu1** [comment]
> @lxfu1 这个问题你看一下吧，熟悉一下 G2 底层的代码。

👌
