### ISSUE TITLE
vue 中柱状图和折线图混合异步传入数据出现"Error: dodge is not support linear attribute, please use category attribute!"

### ISSUE THREAD

**Issue by dreamkai** [antvis/G2Plot#1822]

**Comment by hustcc** [comment]
有具体的版本，数据，代码吗？

**Comment by dreamkai** [comment]
准确来说是changeData方法怎么更新多组数据
chart.changeData()

**Comment by dreamkai** [comment]
![image](https://user-images.githubusercontent.com/46274935/97661523-8b15e900-1aaf-11eb-9925-cde6727eb2c7.png)

**Comment by dreamkai** [comment]
![Uploading image.png…]()

**Comment by dreamkai** [comment]
![Uploading image.png…]()

**Comment by dreamkai** [comment]
![image](https://user-images.githubusercontent.com/46274935/97661617-ca443a00-1aaf-11eb-91cf-77d979dcdd6c.png)

**Comment by dreamkai** [comment]
![image](https://user-images.githubusercontent.com/46274935/97661642-e1832780-1aaf-11eb-8e33-c1ad98e910c8.png)

**Comment by hustcc** [comment]
看下你的 seriesField 中的数据是不是数字？这个必须用文本才行。

**Comment by dreamkai** [comment]
静态写死数据不会出现如图错误,异步获取的出现如图错误

**Comment by dreamkai** [comment]
![image](https://user-images.githubusercontent.com/46274935/97661833-6706d780-1ab0-11eb-98b2-85f9ba13e85d.png)

**Comment by dreamkai** [comment]
![image](https://user-images.githubusercontent.com/46274935/97661881-91589500-1ab0-11eb-8521-fc4d40f25fa0.png)

**Comment by dreamkai** [comment]
![image](https://user-images.githubusercontent.com/46274935/97661964-bea54300-1ab0-11eb-8e23-69be538bb70b.png)

**Comment by hustcc** [comment]
@liuzhenying

**Comment by dreamkai** [comment]
那我想在watch监听变更数据用啥方法呢?没找到

**Comment by hustcc** [comment]
> 那我想在watch监听变更数据用啥方法呢?没找到

```ts
plot.update({ ...plot.options, data: [newData1, newData2] });
```

**Comment by dreamkai** [comment]
目前的问题还是在于柱状图和折线图混合使用,初始是空数组,init初始化会报错

**Comment by dreamkai** [comment]
感谢蚂蚁生态,上次的问题也给我及时处理,发布版本

**Comment by dreamkai** [comment]
感觉空数组状态下,是不是在option是不是要配置类似于scale的属性,不然映射不到

**Comment by hustcc** [comment]
> 感觉空数组状态下,是不是在option是不是要配置类似于scale的属性,不然映射不到

感觉可能是这个原因，目前 G2 对于数据空的时候，处理不是很好。

**Comment by dreamkai** [comment]
谢谢作者,我再去看看吧

**Comment by liuzhenying** [comment]
已复现，我下午看下怎么修

**Comment by dreamkai** [comment]
![image](https://user-images.githubusercontent.com/46274935/97666178-10050080-1ab8-11eb-989c-221b170b5d73.png)

**Comment by dreamkai** [comment]
![image](https://user-images.githubusercontent.com/46274935/97666216-227f3a00-1ab8-11eb-9ab3-1809a1243e42.png)

**Comment by liuzhenying** [comment]
新版本已修复
