### ISSUE TITLE
@afc163  求来帮我们加一下 ci 的时候 coverage，如果 coverage 比上次底，就挂~~ 1122 要到 95%

### ISSUE THREAD

**Issue by afc163** [antvis/G2Plot#1826]
@afc163  求来帮我们加一下 ci 的时候 coverage，如果 coverage 比上次底，就挂~~ 1122 要到 95%

_Originally posted by @hustcc in https://github.com/antvis/G2Plot/pull/1825#issuecomment-719413571_

**Comment by hustcc** [comment]
致敬
