### ISSUE TITLE
仪表盘禁用动画后还是会出现初始化动画

### ISSUE THREAD

**Issue by laolaolulu** [antvis/G2Plot#1836]
import { Gauge } from '@antv/g2plot';

const gauge = new Gauge('container', {
  percent: 0.75,
  startAngle: Math.PI,
  endAngle: 2 * Math.PI,
  animation: false,
  range: {
    color: ['l(0) 0:#bde8ff 1:#7eabff'],
  },
  indicator: {
    pin: false,
    pointer: false,
  },
  statistic: {
    content: {
      style: {
        fontSize: 48,
        textBaseline: 'bottom',
      },
      offsetY: -60,
    },
  },
});

gauge.render();

**Comment by hustcc** [comment]
2.0.6 已经解决。
