### ISSUE TITLE
2.0.5版本双轴图可以选择面积图展现吗？

### ISSUE THREAD

**Issue by 44326334** [antvis/G2Plot#1837]

**Comment by 44326334** [comment]
比如双面积图

**Comment by hustcc** [comment]
双面积图就是堆积面积图。

在双轴图中加入面积图其实挺少见的，需要描述下你们具体用来干啥，可能是一个伪需求。

**Comment by 44326334** [comment]
可能是为了好看 就是在双轴折线图的基础上填充面积 因为面积图可以展现色块

**Comment by 44326334** [comment]
需求效果比如[#1710](https://github.com/antvis/G2Plot/issues/1710)，只不过少了个双轴而已

**Comment by hustcc** [comment]
他用的就是面积图，请看面积图的 demo，不是双轴图。

**Comment by 44326334** [comment]
这个我知道 不过我的数据是双轴的数据

**Comment by hustcc** [comment]
所以是什么场景，分析什么数据需要用到双轴面积图？

**Comment by liuzhenying** [comment]
目前没有支持，因为在双轴的情况下，面积图-柱状图会相互遮挡，面积图-折线图无法有效区分。双面积图的因为左右轴单位不同，使得面积的比较比起双折线图更加困难。
可否详细描述下应用场景，为什么要使用双面积图而不用双折线图，因为面积图比起折线图，除了可以表达趋势，还可以表达部分和总体量之间的关系。我们再看下是否需要支持

**Comment by 44326334** [comment]
我的数据是数量和价格的趋势，如果使用堆叠面积图，isStack: false的情况后，数量趋势趋近于直线， isStack: true,  数量趋势和价格图形重叠在一起 没有体验，
如果使用双轴折线图可以很好表示数据趋势，但是想增加面积样式

**Comment by 44326334** [comment]
我的数量数据是2位数，价格数据是5位数，数据跨度大，展现出来要么是重叠在一起，要么是一条线是直线

**Comment by hustcc** [comment]
似乎算是合理的需求，双轴面积图。 @liuzhenying
