### ISSUE TITLE
TS类型定义问题 & 图表默认配置

### ISSUE THREAD

**Issue by zqlu** [antvis/g2plot#184]
**图表默认配置优化**

https://yuque.antfin-inc.com/antv/g2-4/kclgfa

**每一个图表的TS类型定义**

使用TS改写默认的line-basic DEMO，会有TS类型错误

```ts
const cfg: LineConfig = {
  padding: 'auto',
  data: [{ x: 'a', y: 1 }, { x: 'b', y: 2 }],
  xField: 'x',
  yField: 'y',
};

const plot = new Line(document.getElementById('canvas'), cfg);
```

问题：
1. cfg定义报错
![image](https://user-images.githubusercontent.com/1142242/68366410-3b3b6500-016e-11ea-94bc-35d4fa3326fe.png)

2. cfg类型LineConfig与Line的构造函数参数要求的ViewLayer不一致
![image](https://user-images.githubusercontent.com/1142242/68366433-4a221780-016e-11ea-9ecf-11dcde6cee42.png)

**Comment by zqlu** [comment]
@paleface001 @hustcc 这个设计到每个图形的类型定义，看是分工改下？

**Comment by paleface001** [comment]
> @paleface001 @hustcc 这个设计到每个图形的类型定义，看是分工改下？

分工吧，跟图表的默认配置一起修掉，咱们定个时间点吧。下周三之前怎么样？

**Comment by zqlu** [comment]
那先按这个来：

- [ ] 折线/面积 @hustcc 
- [ ] 柱形条形 @zqlu 
- [ ] 饼图 @Me-Momo 
- [ ] 其他 @paleface001

**Comment by paleface001** [comment]
> 那先按这个来：
> 
> * [ ]  折线/面积 @hustcc
> * [ ]  柱形条形 @zqlu
> * [ ]  饼图 @Me-Momo
> * [ ]  其他 @paleface001

👌

**Comment by paleface001** [comment]
周三再跟设计师组织一次评审，“默认好看”就差不多了

**Comment by zqlu** [comment]
折柱饼的注意也要保证eva-charts可以build通过

**Comment by paleface001** [comment]
那我把默认配置那个链接也同步过来吧

**Comment by Me-Momo** [comment]
先修复一个，然后作为样例给其他参考吧？有一些是common直接修复就行的

**Comment by hustcc** [comment]
@paleface001 剩下你的搞掉，这个事情就算结束掉了~
