### ISSUE TITLE
V2 柱状图label超过canvas范围时渲染不完全

### ISSUE THREAD

**Issue by yuruwang** [antvis/G2Plot#1846]
在柱状图上设置label的位置为top时，偶尔会有label文字超过canvas范围的情况，这时文字会被遮挡，截图如下：
![image](https://user-images.githubusercontent.com/31492974/97961064-8b82ec80-1ded-11eb-92be-627b4be56692.png)

**Comment by hustcc** [comment]
因为 label 目前暂时没有参入到布局，后面我们在 label 中考虑画布大小，然后自动偏移，这样看是否合理。 @zqlu 

目前可以设置画布的 appendPadding: 16 来留一定的边距，保证 label 不会被顶出去。

**Comment by zqlu** [comment]
目前可以增加 layout 配置：

```
label: {
    // 可手动配置 label 数据标签位置
    position: 'top', // 'top', 'bottom', 'middle',
    layout: [{
		// 调整 label 在图形区域内部
        type: 'limit-in-canvas',
    }],
    // 配置样式
    style: {
      opacity: 0.6,
    },
  },
```

**Comment by hustcc** [comment]
考虑 G2Plot 直接内置这些吧！
