### ISSUE TITLE
xAxis.label.rotate 问题

### ISSUE THREAD

**Issue by xiecg** [antvis/G2Plot#1858]
设置 true 后 x 轴文字被遮挡了

![image](https://user-images.githubusercontent.com/10857932/98192179-8640b180-1f55-11eb-996a-6d44af208c7f.png)

设置 offset 到是可以解决问题

![image](https://user-images.githubusercontent.com/10857932/98192349-d61f7880-1f55-11eb-9cd0-ae544dc057c3.png)

但是如果 x 轴文字太多又有太多间隔了

![image](https://user-images.githubusercontent.com/10857932/98192421-f3544700-1f55-11eb-9599-bc01210c5df5.png)

**Comment by zqlu** [comment]
xAxis.label.rotate 配置类型是 number 类型，即手动设置旋转角度。如果需要字段旋转，请使用 xAxis.label.autoRatate 配置。

具体请看文档 https://g2plot.antv.vision/zh/docs/manual/plots/column#axis
