### ISSUE TITLE
条形图顺序问题

### ISSUE THREAD

**Issue by xiecg** [antvis/G2Plot#1861]
分组的图例的顺利反了，应该是 London -> Berlin

![image](https://user-images.githubusercontent.com/10857932/98204356-dbd68780-1f70-11eb-9433-8049f5e6f60a.png)

堆积和百分百也有同样的问题，图例和柱子应该也是 London -> Berlin

![image](https://user-images.githubusercontent.com/10857932/98204619-599a9300-1f71-11eb-9a0a-7ea56a926898.png)

**Comment by arcsin1** [comment]
你好，能提供版本号，和一些相关demo吗 谢谢 @xiecg 

@BBSQQ  要关注下

**Comment by xiecg** [comment]
> 你好，能提供版本号，和一些相关demo吗 谢谢 @xiecg
> 
> @BBSQQ 要关注下

https://codesandbox.io/s/great-shockley-cdcdo

**Comment by zqlu** [comment]
暂时在 G2Plot 无法修复，待在 G2 中支持图例自定义排序。

**Comment by hustcc** [comment]
> 暂时在 G2Plot 无法修复，待在 G2 中支持图例自定义排序。

好像图例配置中有一个 reverse配置。

**Comment by xiecg** [comment]
> > 暂时在 G2Plot 无法修复，待在 G2 中支持图例自定义排序。
> 
> 好像图例配置中有一个 reverse配置。

分组条形图可以这样解决，但是堆叠条形图就有点麻烦了，如果把 data 也 reverse 下，这样 yAxis 就是从下到上了。
这个顺序也不是大问题，G2 支持了再改吧。

**Comment by zqlu** [comment]
这个正在修复中。

**Comment by zqlu** [comment]
v2.3.1 应该已经修复。
