### ISSUE TITLE
pie 图例 offset 被重置

### ISSUE THREAD

**Issue by HUGHHUXIAOJUN** [antvis/G2Plot#1862]
环形中间显示数据  lenged offset 有值 点击图列之后offsetx会恢复为0 并且中间的数值会很长
![image](https://user-images.githubusercontent.com/32575348/98205073-653a8980-1f72-11eb-95b3-37f3922791d8.png)

**Comment by HUGHHUXIAOJUN** [comment]
中间数值变化问题，最新版的，之前2.0.2现在我更新了下2.0.7，点击之后lenged位置变化还存在

**Comment by hustcc** [comment]
好的，感谢反馈，lenged 设置 offset，交互之后位置复原的问题，我来跟进。

**Comment by hustcc** [comment]
ref ： https://github.com/antvis/G2Plot/issues/1729
