### ISSUE TITLE
面积图图形顺序问题

### ISSUE THREAD

**Issue by NierWinter** [antvis/G2Plot#1864]
面积图有api自定义排列图形顺序的吗，看了api文档，好像没有类似的功能，拜托大佬们，图形如图上的排序该如何操作
![图示](https://user-images.githubusercontent.com/58876127/98215377-ad61a800-1f82-11eb-86d4-fdaba5119514.png)

**Comment by hustcc** [comment]
如果要修改顺序，可以在传入数据之前对数据进行一个排序。

**Comment by NierWinter** [comment]
> 如果要修改顺序，可以在传入数据之前对数据进行一个排序。

好的，谢谢
