### ISSUE TITLE
V2 双轴图-左边轴的图例和右边轴的图例能否分开？

### ISSUE THREAD

**Issue by yuruwang** [antvis/G2Plot#1869]
v2的双轴图能不能把图例配置成V1那样左边轴的图例在左边，右边图的图例在右边？现在V2的图例都是放在一起的，和V1的表现不兼容：
![image](https://user-images.githubusercontent.com/31492974/98321933-37f8e480-2021-11eb-96cb-6d323d30abbb.png)
![image](https://user-images.githubusercontent.com/31492974/98321940-3b8c6b80-2021-11eb-9371-724b0a53c6fb.png)

**Comment by hustcc** [comment]
暂时做不到，目前是沿用 G2 的图例能力，不会单独做一套图例样式，而且 v1 中分开的图例样式也被反馈过不好看。

如果真的需要做左右标记，可以使用 annotation 去绘制。
