### ISSUE TITLE
2.0.7版本双轴图 yField 相同时 左yAxis 不显示

### ISSUE THREAD

**Issue by xiecg** [antvis/G2Plot#1870]
![image](https://user-images.githubusercontent.com/10857932/98321880-17308f00-2021-11eb-9829-bea45b3df154.png)

https://codesandbox.io/s/compassionate-darkness-7zehs

2.0.6版本 没问题

**Comment by hustcc** [comment]
已经 pr 修复，不过建议还是 y 字段保持不一样。
