### ISSUE TITLE
近期是否考虑增加胶囊图？

### ISSUE THREAD

**Issue by LazyJoke** [antvis/G2Plot#1873]
如： http://datav.jiaminghi.com/guide/capsuleChart.html#%E5%9F%BA%E6%9C%AC%E7%A4%BA%E4%BE%8B

**Comment by hustcc** [comment]
这个截图中的图，是柱形图的自定义 shape 的样式。

使用 registerShape 注入自定义的 shape 然后在柱形图中使用即可。
