### ISSUE TITLE
DualAxes双轴图更新数据后 图未更新

### ISSUE THREAD

**Issue by Common-zhou** [antvis/G2Plot#1874]
操作:     DualAxes在绘制出图后
调用chart.data(newData) 后调用render()方法。

问题:      原图始终无法更新。

或者是DualAxes的更新方法是别的方法呢？方便告知吗？
![image](https://user-images.githubusercontent.com/28522049/98431749-2718a380-20f3-11eb-99c4-b4896d9e6bd4.png)

非常感谢

**Comment by hustcc** [comment]
linePlaceholder.update({data: newData})
