### ISSUE TITLE
双轴图bug

### ISSUE THREAD

**Issue by lxfu1** [antvis/G2Plot#1881]
- [x] 双轴图堆叠+多折线时，Column 和 Line 无法 legend 全部关闭掉。
- [ ] Column + Line, Column data 为空时，Line 不显示 xAxis label。

**Comment by liuzhenying** [comment]
双轴图堆叠+多折线时，Column 和 Line 无法 legend 全部关闭掉。 已发版，线上可见

**Comment by liuzhenying** [comment]
Column + Line, Column data 为空时，Line 不显示 xAxis label：方案 x 轴默认使用 cat 分类 + sync 同步，触发 g2 的sync 无法同步 range 的问题，等待 g2 的 pr 通过后再在 g2 plot 上更新

关联问题：https://github.com/antvis/G2/pull/2998

**Comment by hustcc** [comment]
如果已经修复，等待发版本，可以关闭。
