### ISSUE TITLE
slider数值范围某些情况下显示不正确

### ISSUE THREAD

**Issue by 0xDarker** [antvis/G2Plot#1899]
如图，X轴刻度是字符串类型的值，01~09的排到后面去了
![image](https://user-images.githubusercontent.com/13844947/98792638-c0242300-2441-11eb-8ac5-9c80c08ba9e5.png)

**Comment by hustcc** [comment]
对数据传入之前进行排序。

**Comment by 0xDarker** [comment]
> 对数据传入之前进行排序。

是按x轴指标排过序的

**Comment by hustcc** [comment]
有具体的代码用来复现吗？或者直接提供 live demo。

**Comment by 0xDarker** [comment]
> 有具体的代码用来复现吗？或者直接提供 live demo。

[https://codesandbox.io/s/black-leaf-ulfwd?file=/src/App.vue](url)

**Comment by hustcc** [comment]
![image](https://user-images.githubusercontent.com/7856674/98898824-71ca5f00-24e9-11eb-864f-3dca984f7038.png)


```ts
// 指定 x 轴类型为 cat
type: 'cat'
```

**Comment by 0xDarker** [comment]
> ![image](https://user-images.githubusercontent.com/7856674/98898824-71ca5f00-24e9-11eb-864f-3dca984f7038.png)
> 
> ```ts
> // 指定 x 轴类型为 cat
> type: 'cat'
> ```

加了cat，slider上的范围显示还是不对，没变化

**Comment by hustcc** [comment]
> > ![image](https://user-images.githubusercontent.com/7856674/98898824-71ca5f00-24e9-11eb-864f-3dca984f7038.png)
> > ```ts
> > // 指定 x 轴类型为 cat
> > type: 'cat'
> > ```
> 
> 加了cat，slider上的范围显示还是不对，没变化

求贴代码，我来复现一下。

**Comment by 0xDarker** [comment]
> > > ![image](https://user-images.githubusercontent.com/7856674/98898824-71ca5f00-24e9-11eb-864f-3dca984f7038.png)
> > > ```ts
> > > // 指定 x 轴类型为 cat
> > > type: 'cat'
> > > ```
> > 
> > 
> > 加了cat，slider上的范围显示还是不对，没变化
> 
> 求贴代码，我来复现一下。

[demo](https://codesandbox.io/s/black-leaf-ulfwd?file=/src/App.vue)

**Comment by hustcc** [comment]
已经修复，见上面的 commit，本周会发布新版本。

**Comment by 0xDarker** [comment]
> 已经修复，见上面的 commit，本周会发布新版本。

专业！
