### ISSUE TITLE
把官网例子复制到代码里报错Object(...) is not a function

### ISSUE THREAD

**Issue by Kaworus** [antvis/G2Plot#1902]
我的代码：
![image](https://user-images.githubusercontent.com/36876417/98891187-a08c0980-24d8-11eb-96bb-2d9aac140696.png)
报错内容：
![image](https://user-images.githubusercontent.com/36876417/98891219-b5689d00-24d8-11eb-9109-a3746d1df0cb.png)
当前版本：2.0.9

**Comment by hustcc** [comment]
代码贴上来，而不是贴图片。

**Comment by Kaworus** [comment]
const data = [
        { year: '1991', value: 3 },
        { year: '1992', value: 4 },
        { year: '1993', value: 3.5 },
        { year: '1994', value: 5 },
        { year: '1995', value: 4.9 },
        { year: '1996', value: 6 },
        { year: '1997', value: 7 },
        { year: '1998', value: 9 },
        { year: '1999', value: 13 }
      ]

      const line = new Line(document.getElementById('bottomChart'), {
        data,
        xField: 'year',
        yField: 'value',
        smooth: true,
        tooltip: false,
        meta: {
          value: {
            max: 15
          }
        }
      })
      line.render()

**Comment by Kaworus** [comment]
抱歉不太会用issue

**Comment by Kaworus** [comment]
突然解决了。。。。是因为@antv/util里面有一个get，我的版本里没有，重新安装了最新的antv/util
