### ISSUE TITLE
漏斗图在svg模式下的bug

### ISSUE THREAD

**Issue by wlpscx** [antvis/G2Plot#1905]
![image](https://user-images.githubusercontent.com/37279331/98924554-ea441680-250f-11eb-97af-0203aa5671ee.png)
如图那个提示框鼠标移开后没有消失，一直在界面上
其次右侧上下翻页的出现bug，向上翻翻不到正确的数据

**Comment by hustcc** [comment]
建议暂时不要使用 svg renderer，可能还会有其他未知的 bug。
