### ISSUE TITLE
图形下方文字被遮挡

### ISSUE THREAD

**Issue by phoema** [antvis/G2Plot#1914]
我从官网打开的样例图形下方文字被遮挡
![image](https://user-images.githubusercontent.com/8730272/99146204-fca98600-26b0-11eb-8aa6-765263167243.png)

我们自己系统也是
![image](https://user-images.githubusercontent.com/8730272/99146222-1ea30880-26b1-11eb-9c9f-41b72a87d9a6.png)

应该是组件的整体样式问题吧，能调一下吗

**Comment by phoema** [comment]
https://antv-g2plot.gitee.io/zh/examples/column/stacked#basic

https://antv-g2plot.gitee.io/zh/examples/line/basic#line

**Comment by hustcc** [comment]
你们的浏览器是什么？我这边打开是 ok 的。

![image](https://user-images.githubusercontent.com/7856674/99146303-c28cb400-26b1-11eb-8d19-125bb85e676a.png)

**Comment by phoema** [comment]
QQ浏览器

**Comment by phoema** [comment]
相同浏览器 在charts 0.9.x版本正常

![image](https://user-images.githubusercontent.com/8730272/99146568-595a7000-26b4-11eb-9c91-5e4478057f86.png)

charts 1.0.7  g2plot 2.0.9就不正常了，查官网示例也是如此，所以提到g2plot这边来了


![image](https://user-images.githubusercontent.com/8730272/99146576-8149d380-26b4-11eb-9351-e7ac1b325988.png)

**Comment by phoema** [comment]
我开谷歌浏览器看了下
x轴确实不遮挡了，但是一点边距都没有，和以前的样式相比有点丑 
并且图例有两处遮挡


![image](https://user-images.githubusercontent.com/8730272/99146651-13ea7280-26b5-11eb-9379-d932c0dfdea7.png)

**Comment by hustcc** [comment]
边距是为了节省空间的，如果需要增加可以设置 轴的宽高。图例的问题我们先看看 @zqlu 。

**Comment by phoema** [comment]
谷歌浏览器

![image](https://user-images.githubusercontent.com/8730272/99147370-73e41780-26bb-11eb-92e7-d14061e39dad.png)

官网示例：
https://antv-g2plot.gitee.io/zh/examples/column/basic#basic
修改代码如下：

import { Column } from '@antv/g2plot';

const data = [
  {
    type: '家具家电',
    sales: 38,
  },
  {
    type: '粮油副食',
    sales: 52,
  },
  {
    type: '生鲜水果',
    sales: 61,
  },
  {
    type: '美容洗护',
    sales: 145,
  },
  {
    type: '母婴用品',
    sales: 48,
  },
  {
    type: '进口食品',
    sales: 38,
  },
  {
    type: '食品饮料',
    sales: 38,
  },
  {
    type: '家庭清洁',
    sales: 38,
  },
    {
    type: '家具家电',
    sales: 38,
  },
  {
    type: '粮油副食1',
    sales: 52,
  },
  {
    type: '生鲜水果1',
    sales: 61,
  },
  {
    type: '美容洗护1',
    sales: 145,
  },
  {
    type: '母婴用品1',
    sales: 48,
  },
  {
    type: '进口食品1',
    sales: 38,
  },
  {
    type: '食品饮料1',
    sales: 38,
  },
  {
    type: '家庭清洁1',
    sales: 38,
  },
    {
    type: '粮油副食1',
    sales: 52,
  },
  {
    type: '生鲜水果1',
    sales: 61,
  },
  {
    type: '美容洗护1',
    sales: 145,
  },
  {
    type: '母婴用品11',
    sales: 48,
  },
  {
    type: '进口食品11',
    sales: 38,
  },
  {
    type: '食品饮料11',
    sales: 38,
  },
  {
    type: '家庭清洁11',
    sales: 38,
  },
];

const columnPlot = new Column('container', {
  data,
  xField: 'type',
  yField: 'sales',
          seriesField: 'type',

  label: {
          visible: true,
          position: 'top',
          adjustColor: true,
          autoRotate:false,
    // 可手动配置 label 数据标签位置
    position: 'middle', // 'top', 'bottom', 'middle',
    // 配置样式
    style: {
      fill: '#FFFFFF',
      opacity: 0.6,
    },
  },
          xAxis: {
          title: null,
          label:{
            autoRotate:false,
            autoHide:true,
          }
        },
        legend: {
          position:'left-top',
          visible: true,
          flipPage: true,
        },
  meta: {
    type: {
      alias: '类别',
    },
    sales: {
      alias: '销售额',
    },
  },
});

columnPlot.render();

**Comment by phoema** [comment]
> 边距是为了节省空间的，如果需要增加可以设置 轴的宽高。图例的问题我们先看看 @zqlu 。

好的，目前样式兼容性问题有点多。
包括QQ浏览器下边沿的兼容，谷歌浏览器的图例兼容等。

**Comment by phoema** [comment]
折线图，官网示例，下方文字被遮挡
![image](https://user-images.githubusercontent.com/8730272/99471798-467cbf80-2982-11eb-8df0-8dbab592dc67.png)

另外，和旧版本相比，同样的数据默认情况下，柱状图图形间距样式比以前更粗了，就更丑点了
折线图数据少过于贴两侧，下方是新旧版本对比图

新（谷歌）
![image](https://user-images.githubusercontent.com/8730272/99471944-952a5980-2982-11eb-912b-99ea5646ea49.png)

旧（QQ）
![image](https://user-images.githubusercontent.com/8730272/99471995-ae330a80-2982-11eb-9fb9-016d4ec85af6.png)

**Comment by phoema** [comment]
折线图 线与左边线太近会导致 两个数字紧挨
![image](https://user-images.githubusercontent.com/8730272/99472272-3ca78c00-2983-11eb-8276-f1f496e3e08f.png)
另外会导致上方遮挡
![image](https://user-images.githubusercontent.com/8730272/99472411-7f696400-2983-11eb-930a-61f0a541faf4.png)

**Comment by phoema** [comment]
@zqlu 您好，等待中，仅几个版本要改吗

**Comment by zqlu** [comment]
> @zqlu 您好，等待中，仅几个版本要改吗

v2.3.1 可以更新下，应该修复了。

**Comment by phoema** [comment]
@zqlu 你好，升级到最新版，效果还是如此，然后 node_modules删除试了一下，没有变化
遮挡问题还存在，谷歌浏览器如下：
![image](https://user-images.githubusercontent.com/8730272/100968426-48db3e00-356c-11eb-9166-cf76b4b9fc32.png)
QQ浏览器遮挡的和谷歌不太一样
![image](https://user-images.githubusercontent.com/8730272/100968525-72946500-356c-11eb-9431-21bc163a299e.png)

**Comment by zqlu** [comment]
> @zqlu 你好，升级到最新版，效果还是如此，然后 node_modules删除试了一下，没有变化
> 遮挡问题还存在，谷歌浏览器如下：
> ![image](https://user-images.githubusercontent.com/8730272/100968426-48db3e00-356c-11eb-9166-cf76b4b9fc32.png)
> QQ浏览器遮挡的和谷歌不太一样
> ![image](https://user-images.githubusercontent.com/8730272/100968525-72946500-356c-11eb-9431-21bc163a299e.png)

这个是图例的另外一个问题，可以先设置图例位置为 left： https://codesandbox.io/s/vigilant-river-vtjxs?file=/src/index.ts

**Comment by phoema** [comment]
字典图文字遮挡：
谷歌
![image](https://user-images.githubusercontent.com/8730272/102336377-0eda5500-3fcc-11eb-90e4-d963545613e7.png)
QQ浏览器
![image](https://user-images.githubusercontent.com/8730272/102336418-1d287100-3fcc-11eb-9b06-e3ef1eddbae7.png)

源码
import { Bullet } from '@antv/g2plot';

const data = [
  {
    title: '重庆',
    ranges: [80],
    measures: [65],
    target: 80,
  },
  {
    title: '杭州',
    ranges: [99],
    measures: [50],
    target: 99,
  },
  {
    title: '广州',
    ranges: [85],
    measures: [40],
    target: 85,
  },
  {
    title: '深圳',
    ranges: [100],
    measures: [50],
    target: 100,
  },
];

const bulletPlot = new Bullet('container', {
  data,
  layout:'vertical',
  measureField: 'measures',
  rangeField: 'ranges',
  targetField: 'target',
  xField: 'title',
  color: {
    measure: '#1890ff',
    target: '#39a3f4',
  },
  label: {
    target:{
      layout:'middle'
    },
    measure: {
      position: 'middle',
    },
  },
  xAxis: {
    line: true,
  },
  yAxis: true,
  tooltip: {
    showMarkers: true,
    shared: true,
  },
});

bulletPlot.render();

**Comment by zqlu** [comment]
> const bulletPlot = new Bullet('container', {
> data,
> layout:'vertical',
> measureField: 'measures',
> rangeField: 'ranges',
> targetField: 'target',
> xField: 'title',
> color: {
> measure: '#1890ff',
> target: '#39a3f4',
> },
> label: {
> target:{
> layout:'middle'
> },
> measure: {
> position: 'middle',
> },
> },
> xAxis: {
> line: true,
> },
> yAxis: true,
> tooltip: {
> showMarkers: true,
> shared: true,
> },
> });
> 
> bulletPlot.render();

设置 target label 的 layout： 

```js
const bulletPlot = new Bullet(createDiv(), {
      data,
      layout: 'vertical',
      measureField: 'measures',
      rangeField: 'ranges',
      targetField: 'target',
      xField: 'title',
      color: {
        measure: '#1890ff',
        target: '#39a3f4',
      },
      label: {
        target: {
          position: 'middle',
          layout: [{ type: 'limit-in-plot' }],
        },
        measure: {
          position: 'middle',
        },
      },
      xAxis: {
        line: {},
      },
      yAxis: {
        nice: true,
      },
      tooltip: {
        showMarkers: true,
        shared: true,
      },
    });
```

**Comment by phoema** [comment]
谢谢，子弹图有效，就是配置越来越复杂了

**Comment by phoema** [comment]
就是改法挺奇怪，被遮挡不应该添加上下左右的冗余量吗，为啥要往里挤？
另外，这个属性是针对所有图表的吗？是否会是图表组件的默认属性？

**Comment by zqlu** [comment]
> 谢谢，子弹图有效，就是配置越来越复杂了

可以看关联的 PR，新版本发布后就会默认内置个layout，就不需要用户层来配置。

**Comment by zqlu** [comment]
> 就是改法挺奇怪，被遮挡不应该添加上下左右的冗余量吗，为啥要往里挤？
> 另外，这个属性是针对所有图表的吗？是否会是图表组件的默认属性？

图表四周的 padding 需要用户自己设置，label 的 layout 配置适用于所有的图表，当不同的 layout 有不同的适用图形，G2Plot 的图形都应该内置适合该图形的 label layout，之前折柱饼等图形都内置了我们认为最好的 layout 配置，这次会加上子弹图的。
