### ISSUE TITLE
关于字体颜色的默认灰度

### ISSUE THREAD

**Issue by phoema** [antvis/G2Plot#1915]
发现默认颜色发灰
https://antv-g2plot.gitee.io/zh/examples/line/basic#line

下方链接是highcharts的地址
https://www.highcharts.com.cn/demo/highcharts/line-basic

**Comment by hustcc** [comment]
字体颜色是这样吧，你可以通过 API 配置去改变 x y 轴文本的字体颜色。

**Comment by phoema** [comment]
highcharts是文字，所以浏览器上看，显得清晰度很高
咱们的g2plot是在画布上画的图形吗？
 
![image](https://user-images.githubusercontent.com/8730272/99146337-0f708a80-26b2-11eb-8c65-48aae159198c.png)

**Comment by Me-Momo** [comment]
svg和canvas方案的区别而已 可以修改渲染引擎；本质要改变颜色 可以手动自己去修改
