### ISSUE TITLE
【讨论】关于 style 透明度的配置问题

### ISSUE THREAD

**Issue by Me-Momo** [antvis/G2Plot#1917]
看看现在的 opacity、lineOpacity、fillOpacity 的各种用法，有些可能要规避统一下

|属性|作用 shape|
|---|---|
|`opacity`|作用于 `pointShape` 的填充色，`lineShape` 填充(stroke)色 |
|`fillOpacity`|作用于 `pointShape`填充色，`areaShape`填充色，`intervalShape`填充色 |
|`strokeOpacity`|作用于 `pointShape` 的描边（如点图、水波图、散点图等），`lineShape` 填充(stroke)色|
|`lineOpacity`|作用于 `pointShape` 的描边|

| Plots |-|
|---|---|
|**面积图** |![image](https://user-images.githubusercontent.com/15646325/99159948-d28dad80-271c-11eb-8958-a1ab152ee94e.png)|
|**水波图**|![image](https://user-images.githubusercontent.com/15646325/99160154-079aff80-271f-11eb-9a40-3ef40999549b.png)|

**Comment by hustcc** [comment]
感觉只能文档清晰，这个都是 G 层的技术债，上层去补丁不是很好。
