### ISSUE TITLE
升级文档缺失的内容

### ISSUE THREAD

**Issue by jaredleechn** [antvis/G2Plot#1925]
- [x] 词云图的 wordField、weightField 不设置会出错
- [x] StackedBar 的描述看上去是 GroupedBar 的
- [x] RangeBar 没有 stackField 字段
  ![image](https://user-images.githubusercontent.com/5318333/99357861-9f4b4a00-28e7-11eb-9d87-cb3ce45566ef.png)

- [x] PercentStackedArea 补充 isPercent: true
- [x] 描述错误
  ![image](https://user-images.githubusercontent.com/5318333/99355783-dfa8c900-28e3-11eb-896a-d23b63d055fc.png)

**Comment by lxfu1** [comment]
https://github.com/antvis/G2Plot/pull/1937
