### ISSUE TITLE
tooltip 提示异常

### ISSUE THREAD

**Issue by lxfu1** [antvis/G2Plot#1926]
定时更新图表时候，图表提示异常。

![image](https://user-images.githubusercontent.com/31396322/99329229-bc1c5900-28b8-11eb-9d5f-a490f98946b2.png)

**Comment by hustcc** [comment]
来一个 riddle 地址~

**Comment by hustcc** [comment]
赞，自提自改，已修复。

**Comment by lxfu1** [comment]
> 来一个 riddle 地址~

当时为什么没有 riddle 地址！ 现在想要复现 bug ，有点回忆不起来了！
