### ISSUE TITLE
null 情况下 tooltip formatter 执行的问题

### ISSUE THREAD

**Issue by xiecg** [antvis/G2Plot#1930]
![image](https://user-images.githubusercontent.com/10857932/99360965-59dd4b80-28ec-11eb-9341-be6d300a0e90.png)

数据中有一个 null ，tooltip 上没有呈现，这是正确的效果。

但是如果配置了 formatter，tooltip 上却呈现出来了，建议如果是 null 不要执行 formatter。

![image](https://user-images.githubusercontent.com/10857932/99361676-6f9f4080-28ed-11eb-96a3-b9872a0968c4.png)

**Comment by lxfu1** [comment]
formatter 的时候处理成  0 更合适？

**Comment by xiecg** [comment]
> formatter 的时候处理成 0 更合适？

现在是这样处理的，但是特殊情况下还是太多了 

![image](https://user-images.githubusercontent.com/10857932/99376153-8189df00-28ff-11eb-8565-a80ee2c1c2e3.png)

**Comment by Me-Momo** [comment]
> formatter 的时候处理成 0 更合适？

不可以哈，自己内部处理为 -（注意数据 null 和 0 是不等的）

**Comment by lxfu1** [comment]
> > formatter 的时候处理成 0 更合适？
> 
> 不可以哈，自己内部处理为 -（注意数据 null 和 0 是不等的）
> 
> ```
> formatter: () => { .... value: item['xxx'] || '-' }  
> ```

没表述清楚，我的意思是让用户自己处理为 0 ，'-'  还是 0  取决于业务。

**Comment by xiecg** [comment]
0 和 '-' 不是重点，重点是期望的效果和图1 一样，值是 null 时，tooltip 里不要显示出来。

**Comment by Me-Momo** [comment]
> 0 和 '-' 不是重点，重点是期望的效果和图1 一样，值是 null 时，tooltip 里不要显示出来。

一般人是希望数据空也要展示出来 否则会以为数据丢失了，如果希望不展示 就把null的数据过滤了 再传入chart中
