### ISSUE TITLE
条形图需要支持轴标签与图形上下布局

### ISSUE THREAD

**Issue by emliybai** [antvis/G2Plot#1940]
条形图的纵轴的轴标签属于长文本时，标签内容会显示不全，在国际化场景下更加明显。建议能支持上下布局
给个参考
![image](https://user-images.githubusercontent.com/74635430/99473889-7ded6b00-2986-11eb-81f8-de42200816d7.png)

**Comment by hustcc** [comment]
这个图使用条形图，然后隐藏坐标轴，使用 annotations 来绘制标签文本，可以实现完全还原。

可以尝试一下，如果发现有困难，我再帮你来一个 demo。
