### ISSUE TITLE
折线图调用changeData变更数据的时候, 能模拟数据随时间线往左移动的效果吗?

### ISSUE THREAD

**Issue by bthulu** [antvis/G2Plot#1941]
现在每次调用changeData, 都是将整个图表重新渲染一遍, 难道不应该是将旧的数据按x轴左移, 再将新数据填充到右边吗?

**Comment by hustcc** [comment]
将animation设置为false，效果基本可以满足要求。

更完美的时序动态图表，还在规划中，敬请期待。
