### ISSUE TITLE
[2.x] 时间轴右侧会多出一块空白区域

### ISSUE THREAD

**Issue by dengfuping** [antvis/G2Plot#1951]
- 重现链接: https://riddle.alibaba-inc.com/riddles/908ee0c1

![image](https://user-images.githubusercontent.com/14918822/99614906-692bd880-2a55-11eb-9327-c9f08b27a1ad.png)

- 重现代码:
```js
import { Line } from '@antv/g2plot';

const data = [
  { metric: 'all', value: 93.22, timestamp: 1605752340000 },
  { metric: 'all', value: 87.65, timestamp: 1605753300000 },
  { metric: 'all', value: 82.12, timestamp: 1605751920000 },
  { metric: 'all', value: 38.72, timestamp: 1605753360000 },
  { metric: 'all', value: 85.55, timestamp: 1605752220000 },
  { metric: 'all', value: 75.43, timestamp: 1605753180000 },
  { metric: 'all', value: 52.98, timestamp: 1605753660000 },
  { metric: 'all', value: 86.47, timestamp: 1605752280000 },
  { metric: 'all', value: 83.07, timestamp: 1605753240000 },
  { metric: 'all', value: 88.35, timestamp: 1605752100000 },
  { metric: 'all', value: 92.45, timestamp: 1605753060000 },
  { metric: 'all', value: 90.5, timestamp: 1605753540000 },
  { metric: 'all', value: 74.75, timestamp: 1605752160000 },
  { metric: 'all', value: 85.97, timestamp: 1605753120000 },
  { metric: 'all', value: 97.58, timestamp: 1605753600000 },
  { metric: 'all', value: 83.55, timestamp: 1605751980000 },
  { metric: 'all', value: 9.38, timestamp: 1605752940000 },
  { metric: 'all', value: 79.63, timestamp: 1605753420000 },
  { metric: 'all', value: 85.42, timestamp: 1605752040000 },
  { metric: 'all', value: 81.35, timestamp: 1605753000000 },
  { metric: 'all', value: 88.17, timestamp: 1605753480000 },
];

const line = new Line('container', {
  data,
  xField: 'timestamp',
  yField: 'value',
  seriesField: 'metric',
  xAxis: {
    type: 'time',
  },
  yAxis: {
    label: {
      // 数值格式化为千分位
      formatter: (v) => `${v}`.replace(/\d{1,3}(?=(\d{3})+$)/g, (s) => `${s},`),
    },
  },
});
line.render();

```

**Comment by hustcc** [comment]
因为 x 轴占用了一定的宽度。可以解决的办法：

```ts
meta: {
  timestamp: {
    range: [0.05, 0.95]
  }
}
```

**Comment by cong876** [comment]
> 因为 x 轴占用了一定的宽度。可以解决的办法：
> 
> ```ts
> meta: {
>   timestamp: {
>     range: [0.05, 0.95]
>   }
> }
> ```

这种写法不是会让两边的空隙更大么，而且这个问题，随着时间轴的变多，空隙会变得更大

**Comment by dengfuping** [comment]
是的，实际的业务场景，这个空隙会大的无法接受，也和之前的 G2Plot 时间轴表现不一致。为什么要做这样的调整呢？或者有木有其他方案规避掉？(设置 range 实测不生效)
![image](https://user-images.githubusercontent.com/14918822/99752688-bbd1c700-2b1f-11eb-80e3-1f1a2318a24a.png)

**Comment by hustcc** [comment]
> 是的，实际的业务场景，这个空隙会大的无法接受，也和之前的 G2Plot 时间轴表现不一致。为什么要做这样的调整呢？或者有木有其他方案规避掉？(设置 range 实测不生效)
> ![image](https://user-images.githubusercontent.com/14918822/99752688-bbd1c700-2b1f-11eb-80e3-1f1a2318a24a.png)

之前默认的是和柱子一样，按照数据量去调整 range： [1/size/2, 1 - 1/size/2]

但是导致的问题就是 折线图两边留间距，特别是当数据量少的时候，比如两条数据，那么左右留空 [1/4, 3/4]

对于折线图可能还能接受，但是对于面积图、雷达图这类线图，不闭口其实就很难看了。

**Comment by dengfuping** [comment]
1. 咦，那现在这个问题在折线图还存在，说明逻辑上还是动态调整的？
2. 补充下，可以把自动美化关掉 `nice: false`，来避免这一问题

**Comment by hustcc** [comment]
> 1. 咦，那现在这个问题在折线图还存在，说明逻辑上还是动态调整的？
> 2. 补充下，可以把自动美化关掉 `nice: false`，来避免这一问题

我发现理解错你的问题了，你的这个问题是 x scale 自动识别成时间，然后自动会补齐一些数据。你把 xAxis type: 'cat' 就好了。

**Comment by dengfuping** [comment]
> 我发现理解错你的问题了，你的这个问题是 x scale 自动识别成时间，然后自动会补齐一些数据。你把 xAxis type: 'cat' 就好了。

- 截图是 `type: 'time'` 的时间轴，但自动补齐数据之后就会出现预期外的间隙。我理解自动补齐数据就是指的美化 `nice: true` 吧，感觉美化之后的效果反倒是不太能接受，会影响业务判断 (让用户认为对应时间段缺数据).

**Comment by hustcc** [comment]
nice: true 已经带来了很多的 issue 了，不知道当时为啥要底层默认 nice: true。
