### ISSUE TITLE
vue.runtime.min.js:6 TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by z-ab** [antvis/G2Plot#1955]
在动态数据加载中，柱状图还是会报这个问题。
看以前的提案说的是同样问题：https://github.com/antvis/G2Plot/pull/1229

**Comment by hustcc** [comment]
可以贴一下具体是什么数据导致的错误吗？

**Comment by z-ab** [comment]
数据是通过接口请求才会报这个错误，如果把数据直接填充到下边的模板就不会报。看样子是初始化顺序导致的问题，用line 的没有问题，只有柱状图有这个问题

数据是接口拿的，所以贴数据看不出，必须接口请求才出来的，现在看到的现象是这样的。同时报上边错误，导致初始化的一些配置都失效了，例如height等
下边是调用这个模板操作的
`<template>
<div ref="dom"></div>
</template>

<style>
.circle {
    width: 10px;
    height: 10px;
    background-color: red;
    border-radius: 50%;
    display: inline-block;
    margin-right: 5px;
}

.deftooltip tr {
    line-height: 30px;
    font-size: 12px;
}

.deftooltip .tname {
    margin-right: 10px
}
</style>

<script>
import {
    Column
} from '@antv/g2plot';
import {
    on,
    off
} from '@/libs/tools'
export default {
    name: "ColumnChart",
    props: {
        option: {}
    },
    data() {
        return {
            myPlot: {},
            theme: {
                "colors10": ["#025DF4", "#DB6BCF", "#2498D1", "#BBBDE6", "#4045B2", "#21A97A", "#FF745A", "#007E99", "#FFA8A8", "#2391FF"],
                "colors20": ["#025DF4", "#DB6BCF", "#2498D1", "#BBBDE6", "#4045B2", "#21A97A", "#FF745A", "#007E99", "#FFA8A8", "#2391FF", "#FFC328", "#A0DC2C", "#946DFF", "#626681", "#EB4185", "#CD8150", "#36BCCB", "#327039", "#803488", "#83BC99"]
            }
        };
    },
    created() {
        
    },
    watch: {
        //观察option的变化
        option: {
            handler(newVal, oldVal) {
                if (this.myPlot) {
                    if (newVal) {
                        // try {
                          this.myPlot.update(newVal);
                        // } catch (error) {
                       
                        // }
                        
                    } else {
                        this.myPlot.update(oldVal);
                    }
                } else {
                    let option = this.option;
                    this.myPlot = new Column(this.$refs.dom, option);
                    this.myPlot.chart.theme(this.theme);
                    this.myPlot.render();
                    on(window, "resize", this.resize);
                }
            },
            deep: true //对象内部属性的监听，关键。
        }
    },
    methods: {
        resize() {
        }
    },
    mounted() {
        this.$nextTick(() => {
            let option = this.option;
            this.myPlot = new Column(this.$refs.dom, option);
            this.myPlot.chart.theme(this.theme);
            this.myPlot.render();
            on(window, "resize", this.resize);
        });
    },
    beforeDestroy() {
        off(window, "resize", this.resize);
    }
};
</script>
`

**Comment by hustcc** [comment]
重复： https://github.com/antvis/G2Plot/issues/1822
