### ISSUE TITLE
empty array throw error

### ISSUE THREAD

**Issue by jaredleechn** [antvis/G2Plot#1956]
- 地址：https://riddle.alibaba-inc.com/riddles/d969df0
- 问题：在图表初始化的时候，数据是 []，此时页面渲染会报错

这个场景在异步加载数据的场景比较多见

**Comment by lxfu1** [comment]
@hustcc  dodge   ?.data 的问题！  上次说是合理需求  不用判断~~

**Comment by hustcc** [comment]
> @hustcc dodge ?.data 的问题！ 上次说是合理需求 不用判断~~

这个不是这个问题吧，这个问题在双轴图中一直遇到的，就是数据为空的时候，scale 默认初始化为 linear 类型的，这个类型没有办法做 dodge。

你说的这个问题是 data 传 undefined 这些会报错，这个不用兼容。

**Comment by hustcc** [comment]
和这个重复 https://github.com/antvis/G2Plot/issues/1822
