### ISSUE TITLE
环形图legend定位后，点击图例  位置会发生变化

### ISSUE THREAD

**Issue by yanjintao** [antvis/G2Plot#1963]
环形图legend定位后，点击图例  位置会发生变化

**Comment by bookkilled** [comment]
并且 图例legend 的itemWidth 设置无效

**Comment by Me-Momo** [comment]
ref: #1862

**Comment by Me-Momo** [comment]
> 并且 图例legend 的itemWidth 设置无效

可以提供一个复现 demo 吗，另外 图例位置重置问题已解决，itemWidth 失效的问题，可以提供一个 demo，并且重开一个 issue
![image](https://user-images.githubusercontent.com/15646325/102832516-9b03d680-4429-11eb-984e-6109d67df3bd.png)
