### ISSUE TITLE
云凤蝶升级问题汇总

### ISSUE THREAD

**Issue by jaredleechn** [antvis/G2Plot#1965]
#### 高优先级 blocker

- [x] #1956 
- [x] #1928 
- [x] #1925 
- [x] #1957 
- [ ] slider 的变更示例图片错误，1.0 的版本是 `{ type, cfx }`，此外 slider 和 scrollbar 应该支持 `false | { ... }`
  <img src="https://user-images.githubusercontent.com/5318333/99780243-2c450c00-2b51-11eb-97a7-a31200037f9e.png" width="300" />

#### 中优先级

- [x] #1945 
- [ ] chartRef 会执行多次 https://riddle.alibaba-inc.com/riddles/42864fad
- [ ] Area 在 `xAxis.type: time` 并开启 slider 的时候，会图形显示不全 https://riddle.alibaba-inc.com/riddles/bb839dde

**Comment by hustcc** [comment]
> slider 的变更示例图片错误，1.0 的版本是 { type, cfx }，此外 slider 和 scrollbar 应该支持 false | { ... }

现在就是支持 slider，scrollbar 就是支持 false 的

> chartRef 会执行多次 https://riddle.alibaba-inc.com/riddles/42864fad

@lxfu1 

> Area 在 xAxis.type: time 并开启 slider 的时候，会图形显示不全

这个 riddle 地址是因为没有设置 height 吧

**Comment by jaredleechn** [comment]
> Area 在 xAxis.type: time 并开启 slider 的时候，会图形显示不全

![image](https://user-images.githubusercontent.com/5318333/100313151-f2f81a80-2fee-11eb-83d8-497ab05793ac.png)

**Comment by hustcc** [comment]
整个 G2 底层的 time 类型的 scale 问题都很大，所以建议暂时不要用 time 类型的。

**Comment by jaredleechn** [comment]
这个问题的优先级很高，不然 x 轴不连续的时候，图形的变化趋势会受到影响，或者有补全数据的能力也可以

**Comment by hustcc** [comment]
> 这个问题的优先级很高，不然 x 轴不连续的时候，图形的变化趋势会受到影响，或者有补全数据的能力也可以

试试使用 timeCat 是可以可以，双轴图也是遇到类似的问题，近期准备在 g2 层把时间类型默认由 time 改成 timeCat

**Comment by hustcc** [comment]
> 这个问题的优先级很高，不然 x 轴不连续的时候，图形的变化趋势会受到影响，或者有补全数据的能力也可以

可以试试 timeCat。
