### ISSUE TITLE
请问interactions是个什么配置啊？

### ISSUE THREAD

**Issue by wood3n** [antvis/G2Plot#1968]
文档也搜不到，就有的demo里给了个参考，这太模糊了，其他图表想用也不知道咋配置的

![image](https://user-images.githubusercontent.com/31716713/99785680-6ebe1700-2b58-11eb-957f-5e92df040fff.png)

**Comment by arcsin1** [comment]
sorry，这个文档后续会补上，是继承了g2的interaction哦。可以先看这个https://g2.antv.vision/zh/docs/api/general/interaction/#gatsby-focus-wrapper  @wood3n

**Comment by arcsin1** [comment]
@lxfu1  看样子需要补一个通用文档在g2plot里面

**Comment by wood3n** [comment]
> sorry，这个文档后续会补上，是继承了g2的interaction哦。可以先看这个https://g2.antv.vision/zh/docs/api/general/interaction/#gatsby-focus-wrapper @wood3n

可以可以，了解了，多谢

**Comment by Me-Momo** [comment]
目前饼图的交互已经补充上了，其他 plots 也是共用的 https://g2plot.antv.vision/en/docs/manual/plots/pie#plot-interactions
