### ISSUE TITLE
Words missing with V2 wordclouds 

### ISSUE THREAD

**Issue by pjeannet** [antvis/G2Plot#1970]
Hello,

Did V2 introduce some kind of filtering on wordclouds if there is too much words or with a weight threshold? When I compare the same dataset between V1 & V2, V2 is not displaying all the words (see bellow). 
V2 :
![image](https://user-images.githubusercontent.com/6052793/99794479-81b9f280-2b2a-11eb-85f8-7ff335159e52.png)
V1 :
![image](https://user-images.githubusercontent.com/6052793/99794491-88e10080-2b2a-11eb-9525-82da35493d59.png)

This is not bad per se as it makes a cleaner wordcloud out of the box, but it could be better if we could control it and either fix a count threshold or choose the number of words to display (selecting only the n first items with the highest count).

**Comment by pjeannet** [comment]
After more testing it seems that if I remove the fixed height then all words are displayed (but it won't fit anymore as we want).
![image](https://user-images.githubusercontent.com/6052793/99796272-7b794580-2b2d-11eb-87fd-c7b66fd9bb58.png)

**Comment by zhangzhonghe** [comment]
You can try changing the fontSize.
![2A7A6007-2336-4425-9F5F-DC5810058A02](https://user-images.githubusercontent.com/38434641/99798082-54d9ff80-2b6b-11eb-8a4e-b94e9cbdea63.png)

**Comment by pjeannet** [comment]
Thanks, I reduced the fontSize from `[20,60]` to `[10, 50]` and set spiral to `rectangular` and now the results are closer to V1 look.

![image](https://user-images.githubusercontent.com/6052793/99799538-22acab80-2b33-11eb-904f-a857a250174b.png)

I still have an issue with wordcloud containing few verbatims : there's a lot more space between words in V2 than in V1
V1: 
![image](https://user-images.githubusercontent.com/6052793/99799801-90f16e00-2b33-11eb-8d20-b3743b3d56c2.png)
V2:
![image](https://user-images.githubusercontent.com/6052793/99799822-9cdd3000-2b33-11eb-8bd4-b57500eec729.png)

**Comment by zhangzhonghe** [comment]
@pjeannet It is a BUG.

**Comment by zhangzhonghe** [comment]
@pjeannet It's been fixed, please wait for a new release.

you can set the padding to change the space between words.
![6EC25B77-3322-4e5d-A595-12C8D14E16D2](https://user-images.githubusercontent.com/38434641/99865451-b25e6280-2be4-11eb-9cc1-4f0934afb489.png)
