### ISSUE TITLE
基础水平方对称条形图

### ISSUE THREAD

**Issue by lethe-river** [antvis/G2Plot#1996]
![WO((HXZC33UZ}45JVX}G@ E](https://user-images.githubusercontent.com/52186159/99937959-cef3c980-2da1-11eb-825a-f7a512e0275d.png)
请问，如何将字段居中呢？

**Comment by arcsin1** [comment]
sorry，暂时不会支持居中这种配置，其实也不好看；这种如果文字长了 可以考虑放到 position :  'top'  即为左边；谢谢！

**Comment by lethe-river** [comment]
好的，谢谢~
