### ISSUE TITLE
使用DualAxes并且异步获取数据时，显示出多余的数据

### ISSUE THREAD

**Issue by chen515024** [antvis/G2Plot#2003]
![image](https://user-images.githubusercontent.com/27874954/100077616-86a9d980-2e7d-11eb-963b-4e154650e3ff.png)
![image](https://user-images.githubusercontent.com/27874954/100077641-8e697e00-2e7d-11eb-9a4e-bba6293c7c13.png)
![image](https://user-images.githubusercontent.com/27874954/100077708-a3dea800-2e7d-11eb-83de-1fb7546e6b4c.png)
![image](https://user-images.githubusercontent.com/27874954/100077758-b0fb9700-2e7d-11eb-8c43-3f31842186ca.png)
如图，API接口的数据只有三列，但是在实际显示的时候却多了两列

**Comment by hustcc** [comment]
@liuzhenying 和折线图，柱形图一样，可以设置 xAxis 的 type 默认为 type: 'cat'。
