### ISSUE TITLE
混合图表tooltip

### ISSUE THREAD

**Issue by aaa123123999** [antvis/G2Plot#2006]
混合图表的tooltip如何配置啊，这官网写的太随意了吧

**Comment by Me-Momo** [comment]
你现在配置 tooltip 是遇到什么问题呢

**Comment by hustcc** [comment]
> 混合图表的tooltip如何配置啊，这官网写的太随意了吧

这个 issue 也是有点随意~~

文档： https://g2plot.antv.vision/zh/docs/manual/plots/dual-axes#tooltip
