### ISSUE TITLE
最新版本 中的堆叠条形图 当文本超出所在容器，没有自动隐藏

### ISSUE THREAD

**Issue by SummerCreazy** [antvis/G2Plot#2008]
最新版本 中的堆叠条形图 当文本超出所在容器，没有自动隐藏，而在1.x的版本中有介绍使用middle这个位置可以实现，而在新版本中没有起作用，请问一下如何实现该效果

**Comment by SummerCreazy** [comment]
![image](https://user-images.githubusercontent.com/33471987/100178305-96bdc980-2f0e-11eb-9a39-422115e0a1ff.png)

**Comment by Me-Momo** [comment]
尝试加一个v标签布局
```
{
   label: {
      layout: ['limit-in-shape']
  }
}
```

**Comment by SummerCreazy** [comment]
非常感谢  有用了layout: [{type:'limit-in-shape'}]  再就是我想问一下 像layout里面的配置在哪有文档可以找得到，或者在代码里面哪块有说明呢

**Comment by Me-Momo** [comment]
标签支持的布局类型以及适用的 plot 类型，相关文档正在梳理中，现在可以先参考下 G2 文档：[标签布局](https://g2.antv.vision/en/docs/manual/concepts/component/label#%E6%A0%87%E7%AD%BE%E5%B8%83%E5%B1%80)

**Comment by SummerCreazy** [comment]
谢谢啦
