### ISSUE TITLE
散点图中当点的横纵坐标重复，只展示最后一个点，其他的点都不渲染进去了，该怎么解决呢？

### ISSUE THREAD

**Issue by xqb20160824** [antvis/G2Plot#2015]
参数shared设置好像也没有用

**Comment by lxfu1** [comment]
提供一下截图.

**Comment by lxfu1** [comment]
tooltip: {
  field: [xx, xx]
}

**Comment by xqb20160824** [comment]
> 提供一下截图.
![1](https://user-images.githubusercontent.com/21216728/100322371-22af1e80-2fff-11eb-985a-5c84814bd1e0.png)
![3](https://user-images.githubusercontent.com/21216728/100322376-2642a580-2fff-11eb-95b4-c00818b04fa4.png)

**Comment by xqb20160824** [comment]
> fields

你好，设置fields没有用，API文档说是设置shared，我试了也没有用，有解决办法吗
![4](https://user-images.githubusercontent.com/21216728/100323236-6191a400-3000-11eb-9034-9d604fa0f590.png)

**Comment by lxfu1** [comment]
https://g2plot.antv.vision/zh/examples/scatter/basic#quadrant-tooltip 参考下这个  fields是可以的

**Comment by liwanyin** [comment]
请问这个问题解决了吗？我的版本2.4.9版本仍存在tooltip: {shared: true}无效的问题，并没有把相同的数据进行合并，请帮忙看看，谢谢！
