### ISSUE TITLE
双轴折线右轴展示的label个数和刻度线个数不一样

### ISSUE THREAD

**Issue by Una-Gao** [antvis/G2Plot#2018]
![image](https://user-images.githubusercontent.com/68375674/100404617-c3075080-309c-11eb-8e0d-5ba7cba950ac.png)

**Comment by Una-Gao** [comment]
label的position也不太对

**Comment by liuzhenying** [comment]
这是因为在双 y 轴的情况下，两侧的数据经过分割后得到的 tickCount 不一致, 会在之后的版本优化

**Comment by lessonli** [comment]
这个优化好了吗？ 目前g2 也有这个问题  我手动处理了 两侧 tickCount 使得他们总能保持一致 
想问下 g2Plot  现在还有这个问题吗
