### ISSUE TITLE
Y轴的刻度线怎么显示啊

### ISSUE THREAD

**Issue by OneSeven** [antvis/G2Plot#2025]
![2121](https://user-images.githubusercontent.com/17974392/100544116-87cc7380-328e-11eb-8062-ec5d82ebc1c3.png)

像echarts那样有个Y轴的刻度线

**Comment by hustcc** [comment]
![image](https://user-images.githubusercontent.com/7856674/100559409-81211900-32ed-11eb-827b-0a0a78986d8d.png)

**Comment by hustcc** [comment]
```ts
      yAxis: {
        tickLine: {
          style: {
            stroke: 'red',
          }
        },
        line: {
          style: {
            stroke: 'red',
          }
        }
      }
```

 - tickLine & line

![image](https://user-images.githubusercontent.com/7856674/100561228-330f1400-32f3-11eb-8b0c-4762cab5ec76.png)

 - subTickLine

![image](https://user-images.githubusercontent.com/7856674/100561297-77021900-32f3-11eb-97a1-eecd867dc9a2.png)

**Comment by OneSeven** [comment]
> ```ts
>       yAxis：{ 
>         tickLine：{ 
>           style：{ 
>             stroke：'red' ，
>           } 
>         } ，
>         line：{ 
>           style：{ 
>             stroke：'red' ，
>           } 
>         } 
>       }
> ```
> 
> * tickLine和线
> 
> ![图片](https://user-images.githubusercontent.com/7856674/100561228-330f1400-32f3-11eb-8b0c-4762cab5ec76.png)
> 
> * subTickLine
> 
> ![图片](https://user-images.githubusercontent.com/7856674/100561297-77021900-32f3-11eb-97a1-eecd867dc9a2.png)

谢谢，昨晚确实情绪烦躁有失礼貌，在此道歉，望能删除上面截图回复，非常感谢
