### ISSUE TITLE
折线图怎么实现平滑效果，不是整体重绘。

### ISSUE THREAD

**Issue by 905868332** [antvis/G2Plot#2026]
例如：监控CPU利用率，每秒增往后加一个数据，折线图向左平移

**Comment by hustcc** [comment]
设置 animation: false 试试效果。

**Comment by 905868332** [comment]
> 设置 animation: false 试试效果。

没有重绘了，但是没有过度效果了。

**Comment by 905868332** [comment]
> 设置 animation: false 试试效果。



> 设置 animation: false 试试效果。

应该还行 数据量小的时候效果一般，数据量大的时候可以

**Comment by hustcc** [comment]
> > 设置 animation: false 试试效果。
> 
> 应该还行 数据量小的时候效果一般，数据量大的时候可以

完美的更新动画，目前还没有，已经在规划中，但是没法给确定的上线时间。目前的方式只能算是折中，请关注我们 G2 G2Plot 后续的 changelog 更新记录。
