### ISSUE TITLE
多个图形，采用删格布局，当页面变化时如何让图形自适应 宽高

### ISSUE THREAD

**Issue by JuSanZhi** [antvis/G2Plot#2028]

**Comment by hustcc** [comment]
默认就是支持的。

```
autoFit: true
```

这个的逻辑是，放 图表的 div 容器，如果大小变化，图表会自动跟着变化。确保 div 容器的宽高是跟着 删格 大小变化即可。

**Comment by JuSanZhi** [comment]
> 默认就是支持的。
> 
> ```
> autoFit: true
> ```
> 
> 这个的逻辑是，放 图表的 div 容器，如果大小变化，图表会自动跟着变化。确保 div 容器的宽高是跟着 删格 大小变化即可。

初始化我是给了高度，但是页面变化时我的高度不需要变化的，但是这个时候宽应该怎么设置

**Comment by hustcc** [comment]
1. grid 高度需要指定
2. canvas 的容器 div 宽度设置 100%
