### ISSUE TITLE
折线图可以，从右往左描点吗

### ISSUE THREAD

**Issue by 905868332** [antvis/G2Plot#2029]
每秒添加一个数据，数据对应图上的位置从最右边开始出现。就像 任务管理器 性能 里边的CPU利用率、内存使用量 这些图标效果一样

**Comment by hustcc** [comment]
什么意思？出场动画从右到左吗？

**Comment by 905868332** [comment]
> 什么意思？出场动画从右到左吗？

例如，我现在做一个监控功能，每秒添加一个数据，数据对应图上的位置从最右边开始出现。就像 任务管理器 性能 里边的CPU利用率、内存使用量 这些图标效果一样

**Comment by hustcc** [comment]
```ts
{
  // ...
  animation: false,
}

line.update(data);
```

上面的方式基本可以满足的你的需求。更加完善的更新动画，还是规划开发中~
