### ISSUE TITLE
折线图中 X 轴的值如果为 1, 2, 3, .... 会导致折线图渲染出错

### ISSUE THREAD

**Issue by yb** [antvis/G2Plot#2030]
**问题描述：**

当 X 轴的值为 1, 2, 3, 4, ... 时，图表上 X 的落点位置不正确，部分情况下甚至会导致整个图表错版。经过测试如果 X 轴为 2, 3, 4, 5 也有同样的问题。

**在线例子：**

[https://codesandbox.io/s/i4qpj](https://codesandbox.io/s/i4qpj)

**简单代码：**

    import { Line } from '@antv/g2plot';

    const data = [
      { x: 1, y: 100 },
      { x: 2, y: 110 },
      { x: 3, y: 120 },
      { x: 4, y: 130 },
    ];

    const line = new Line('container', {
      data,
      xField: 'x',
      yField: 'y',
      point: {
        size: 5,
        shape: 'diamond',
      },
    });

    line.render();

**预览图：**

![image](https://user-images.githubusercontent.com/25887822/100578821-02909f80-331e-11eb-9c70-b86a41b31dc6.png)

**Comment by hustcc** [comment]
确实是一个 bug，底层修复。暂时先把 x 轴数据转成文本类型吧~
