### ISSUE TITLE
Bar组件相关问题

### ISSUE THREAD

**Issue by chen515024** [antvis/G2Plot#2032]
1.如果设置Y轴的值的宽，或者设置对应的样式。当值太长时，显示样式不怎么好看
![image](https://user-images.githubusercontent.com/27874954/100595333-be10fe00-3335-11eb-9a88-f4b8b8e89ae8.png)
2.当使用滚动条时，界面没有出现滚动条，但是数据却被分成了两份
![image](https://user-images.githubusercontent.com/27874954/100595405-d6811880-3335-11eb-8bd0-9b186e0983bc.png)
![image](https://user-images.githubusercontent.com/27874954/100595460-e26cda80-3335-11eb-86f8-477fb0f358be.png)
![image](https://user-images.githubusercontent.com/27874954/100595525-f87a9b00-3335-11eb-82e8-cb2542dfb386.png)
此处并没有出现滚动条，但是把相同配置和数据放到官方的demo里面却可以滚动，是不是样式的问题?

**Comment by zqlu** [comment]
@chen515024 能在[CodeSandbox](https://codesandbox.io/)上提供一个基本的DEMO吗，方便我这边快速定位问题。

**Comment by chen515024** [comment]
> @chen515024 能在[CodeSandbox](https://codesandbox.io/)上提供一个基本的DEMO吗，方便我这边快速定位问题。

https://codesandbox.io/s/g2plot-question-hiu71?fontsize=14&hidenavigation=1&theme=dark
很奇怪，我在DEMO上的话会有出现滚动条，但是在实际项目中就没有出现，会不会跟样式有关呢？

**Comment by zqlu** [comment]
@chen515024 看了下，chart 的配置有点问题；需要设置下高度， autoFix 是拼写错误？是 autoFit 么，这样看滚动条是没问题的：

https://0zveo.csb.app/

**Comment by chen515024** [comment]
> @chen515024 看了下，chart 的配置有点问题；需要设置下高度， autoFix 是拼写错误？是 autoFit 么，这样看滚动条是没问题的：
> 
> https://0zveo.csb.app/
autoFix确实有拼写错误问题😂已经修改。如果滚动条需要设置高度才能出现的话如果实际的高度不可知的情况下如何解决呢？在项目中用的是grid去实现布局的，高度设置的是百分比的，没有设置指定数值的。不知道是不是这个问题导致滚动条没有出来。

**Comment by zqlu** [comment]
> > @chen515024 看了下，chart 的配置有点问题；需要设置下高度， autoFix 是拼写错误？是 autoFit 么，这样看滚动条是没问题的：
> > [0zveo.csb.app](https://0zveo.csb.app/)
> > autoFix确实有拼写错误问题😂已经修改。如果滚动条需要设置高度才能出现的话如果实际的高度不可知的情况下如何解决呢？在项目中用的是grid去实现布局的，高度设置的是百分比的，没有设置指定数值的。不知道是不是这个问题导致滚动条没有出来。

不会不出现，如果高度上不需要展示滚动条，但设置了滚动条，这个滚动条会展示出来，但不能滚动。这一点我后续可以优化下，实现类似 auto 的方式

**Comment by chen515024** [comment]
> > > @chen515024 看了下，chart 的配置有点问题；需要设置下高度， autoFix 是拼写错误？是 autoFit 么，这样看滚动条是没问题的：
> > > [0zveo.csb.app](https://0zveo.csb.app/)
> > > autoFix确实有拼写错误问题😂已经修改。如果滚动条需要设置高度才能出现的话如果实际的高度不可知的情况下如何解决呢？在项目中用的是grid去实现布局的，高度设置的是百分比的，没有设置指定数值的。不知道是不是这个问题导致滚动条没有出来。
> 
> 不会不出现，如果高度上不需要展示滚动条，但设置了滚动条，这个滚动条会展示出来，但不能滚动。这一点我后续可以优化下，实现类似 auto 的方式

好的，那我检查下自己的样式写的是不是有问题。谢谢😄
