### ISSUE TITLE
Bar 的color属性设置多色无效

### ISSUE THREAD

**Issue by Leannechn** [antvis/G2Plot#2037]
![image](https://user-images.githubusercontent.com/6812138/100705413-1c93b600-33e2-11eb-9313-d009c2ec8bdc.png)

**Comment by Leannechn** [comment]
![image](https://user-images.githubusercontent.com/6812138/100705482-37662a80-33e2-11eb-8739-bb0fa4fcd281.png)

**Comment by hustcc** [comment]
color 和 seriesField 都是顶层属性，不是放到 color 下面。

**Comment by Leannechn** [comment]
![image](https://user-images.githubusercontent.com/6812138/100705662-8ca23c00-33e2-11eb-8a12-0225786fb759.png)
