### ISSUE TITLE
🧚‍♀️🔥 饼图和环图即便修改了 padding，图例仍被截断

### ISSUE THREAD

**Issue by wuzhao** [antvis/G2Plot#2039]
![image](https://user-images.githubusercontent.com/712075/100725550-24158800-33ff-11eb-880d-1e920fc21123.png)
![image](https://user-images.githubusercontent.com/712075/100725563-27107880-33ff-11eb-892e-72762e9de89f.png)

**Comment by hustcc** [comment]
这个是复合逻辑的，需要修改 legend 配置。

```ts
maxItemWidth: number; // 图例项的最大宽度，默认是 200
itemWidth: number;  // 图例项的宽度
```

**Comment by jasonjcpeng** [comment]
版本2.3.18，legend设置
`maxItemWidth: number; // 图例项的最大宽度，默认是 200
itemWidth: number;  // 图例项的宽度`
后，有分页的legend，被截断问题仍未解决。
![image](https://user-images.githubusercontent.com/13363216/115518970-58f57f00-a2bb-11eb-8a41-cc0ae1a3410e.png)
![image](https://user-images.githubusercontent.com/13363216/115519026-67dc3180-a2bb-11eb-9e28-3ebb109cf7cc.png)

**Comment by visiky** [comment]
见 #2711
