### ISSUE TITLE
🧚‍♀️ lineChart 左右的对齐方式跟原本设置不一样

### ISSUE THREAD

**Issue by wuzhao** [antvis/G2Plot#2042]
![image](https://user-images.githubusercontent.com/712075/100726585-1ad8eb00-3400-11eb-90a9-edcfe95ec309.png)

**Comment by hustcc** [comment]
增加默认配置：

```ts
xAxis: {
  range: [0, 1]
}
```

这个的原因：

1. 为了兼容之前 v1 逻辑
2. 在数据为 1 条的时候，保证数据是居中的
