### ISSUE TITLE
Bar方法下scrollbar的backgroundStyle、textStyle、foregroundStyle、handlerStyle无效

### ISSUE THREAD

**Issue by chen515024** [antvis/G2Plot#2048]
![image](https://user-images.githubusercontent.com/27874954/100731851-e61c6200-3406-11eb-849d-338e6f0e03e5.png)
第一张图中已经添加了对应的属性，但是在界面中并没有变化
![image](https://user-images.githubusercontent.com/27874954/100733370-09481100-3409-11eb-8fc7-1816b5a651f5.png)
如果容器的背景色是透明的时候，就会看不到滚动条了

**Comment by visiky** [comment]
文档错误，近期修复。
另外，关于滚动条 trackColor 和 thumbColor 设置，关注 #1562
