### ISSUE TITLE
饼图 percentage 0 转为 null bug

### ISSUE THREAD

**Issue by hnsylitao** [antvis/G2Plot#2054]
https://github.com/antvis/G2Plot/blob/63a636e2195af8e909be41871132269a4614c4b1/src/plots/pie/adaptor.ts#L138
改为这种比较友好
```js
percent ? `${(percent * 100).toFixed(2)}%` : '0%'
```

**Comment by hustcc** [comment]
@hnsylitao 有兴趣来直接 pr 吗？直接改掉~ 
@Me-Momo 看看这样改是否合适。

**Comment by Me-Momo** [comment]
改成 `isNumber(percent) && ！isNil(percent) ? `${(percent * 100).toFixed(2)}%` :  null`

**Comment by hnsylitao** [comment]
@Me-Momo 这种是不是可以
```
isNumber(percent) && ！isNaN(percent) ? ${(percent * 100).toFixed(2)}% : ''
```
因为null 被字符串模版转为 null 字符串了

**Comment by hnsylitao** [comment]
@hustcc 计划什么时候发布新版本。
我好更新到新的版本上。

**Comment by hustcc** [comment]
今天晚上~
