### ISSUE TITLE
Line/Area 的 label 重复绘制了

### ISSUE THREAD

**Issue by zqlu** [antvis/G2Plot#2064]
DEMO： http://riddle.alibaba-inc.com/riddles/707baa93

**Comment by xiecg** [comment]
雷达图疑似也是这种情况
![image](https://user-images.githubusercontent.com/10857932/101133030-f3259500-3642-11eb-983c-b7fa37033d24.png)

**Comment by zqlu** [comment]
已修复，待发布 https://github.com/antvis/G2Plot/pull/2071
