### ISSUE TITLE
🧚‍♀️🔥 饼图的 legend.itemValue 要支持显示 value

### ISSUE THREAD

**Issue by wuzhao** [antvis/G2Plot#2065]
![image](https://user-images.githubusercontent.com/712075/100962949-60acc500-3560-11eb-9c73-77669a69cf93.png)

智能服务场景诉求，负责人 @宸墨

**Comment by wuzhao** [comment]
@绯一 先排除，如果不相关我回来关闭需求

**Comment by jaredleechn** [comment]
legend.itemValue.formatter，现在拿不到的每个分类对应的 value

![image](https://user-images.githubusercontent.com/5318333/100973094-e0dd2580-3574-11eb-904e-621f21702a2f.png)

**Comment by zhenzhenChange** [comment]
> legend.itemValue.formatter，现在拿不到的每个分类对应的 value
> 
> ![image](https://user-images.githubusercontent.com/5318333/100973094-e0dd2580-3574-11eb-904e-621f21702a2f.png)

请问这个`legend.itemValue.formatter`中的`value`拿不到对应的值如何解决？
