### ISSUE TITLE
使用line多折线情况时，服务端返回的数据如果某一类的数据只存在一部分，line的线断了，这个怎么优化呢

### ISSUE THREAD

**Issue by fancymo** [antvis/G2Plot#2067]
![image](https://user-images.githubusercontent.com/13718389/100973138-f5212280-3574-11eb-9746-97e56e986c43.png)

具体可以看图片里，某些天某些分类没有数据，导致没有绘制，有什么配置可以自动填补空数据

**Comment by hustcc** [comment]
```ts
connectNull: true
```

**Comment by fancymo** [comment]
> ```ts
> connectNull: true
> ```

数据格式如下
```
[{ value: 1, category: 'a'  ds:  '20121101'  },
{ value: 2, category: 'a'  ds:  '20121102'  },
{ value: 2, category: 'b'  ds:  '20121102'  }]
```
设置 connectNull: true 后还是断点

**Comment by hustcc** [comment]
已经钉钉上沟通，先业务补数据解决。
