### ISSUE TITLE
多折线图能否支持类似双折线图的数据格式

### ISSUE THREAD

**Issue by hizhengfu** [antvis/G2Plot#2068]
目前多折线图的数据比较冗余，能否支持类似双折线图可以指定多个field的格式或者支持从一个数据集里面提取多个折线图的配置

**Comment by hustcc** [comment]
多指标的折线图，将数据进行一个转换，将多指标变成一个维度。然后使用折线图。

**Comment by hizhengfu** [comment]
> 多指标的折线图，将数据进行一个转换，将多指标变成一个维度。然后使用折线图。

能否支持dataset这种呢，比如[echarts](https://echarts.apache.org/zh/tutorial.html#%E4%BD%BF%E7%94%A8%20dataset%20%E7%AE%A1%E7%90%86%E6%95%B0%E6%8D%AE)的这种encode，非常容易从一组数据中生成不同曲线。

**Comment by hustcc** [comment]
> > 多指标的折线图，将数据进行一个转换，将多指标变成一个维度。然后使用折线图。
> 
> 
> 
> 能否支持dataset这种呢，比如[echarts](https://echarts.apache.org/zh/tutorial.html#%E4%BD%BF%E7%94%A8%20dataset%20%E7%AE%A1%E7%90%86%E6%95%B0%E6%8D%AE)的这种encode，非常容易从一组数据中生成不同曲线。

可以看下 @antv/dataset 模块。很多数据处理方法。

**Comment by elephantme** [comment]
@hustcc 目前转化成分类分组的做法数据会指数级的膨胀，例如10个指标，返回1w条数据，经过这么已处理就变成10w条数据了。我感觉目前的做法在性能上，没有G2中直接调用多次chart.line()，（几个指标就调用几次）的好吧。
