### ISSUE TITLE
axis 网格配置不生效

### ISSUE THREAD

**Issue by Esorakouki** [antvis/G2Plot#2077]
version: 2.3.1
配置x轴或y轴时 grid设为false时 网格仍显示，所以图表可复现。

**Comment by Me-Momo** [comment]
可能文档没有写好，需要设置为: `grid: null`; 如果使用的是 ts，应该会自动进行类型定义提示，需要设置为 null

**Comment by Me-Momo** [comment]
![image](https://user-images.githubusercontent.com/15646325/101312295-5d7e4580-388e-11eb-88f4-945ee09e36b8.png)
