### ISSUE TITLE
直方图label位置无法居中

### ISSUE THREAD

**Issue by Esorakouki** [antvis/G2Plot#2081]
label位置默认不为水平居中， 且设置label.position无效。

version： 2.3.1

![image](https://user-images.githubusercontent.com/15276351/101314134-daabb980-3892-11eb-8288-56d062cad79e.png)

**Comment by arcsin1** [comment]
@Esorakouki  sorry，这个涉及到g2底层可能需要优化，暂时解决办法：
设置偏移量来处理，类似
`label: {
    offsetX: -70
  } `

后续我们会修复的，这个issue暂时保留，带来不便，十分抱歉！感谢支持
