### ISSUE TITLE
Can you create a Horizontal Stacked Bar Chart with G2Plot?

### ISSUE THREAD

**Issue by sturlath** [antvis/G2Plot#2082]
Is this possible with G2?

![image](https://user-images.githubusercontent.com/2386572/101381920-40a63a00-38af-11eb-980a-7dbbc2bf200c.png)

or even better, this

![image](https://user-images.githubusercontent.com/2386572/101382049-692e3400-38af-11eb-8e92-b99bd1f7261a.png)

If not do you know of a React library that can do it?

**Comment by Me-Momo** [comment]
Is this what you are looking for ? https://g2plot.antv.vision/en/examples/bar/stacked#basic
you can also see this example: https://codesandbox.io/s/g2plot-20-horizontal-stacked-bar-chart-rcenz?file=/index.js

**Comment by sturlath** [comment]
@Me-Momo Yes that was it! Thank you so much for your quick answer!
