### ISSUE TITLE
百分比柱状图、条形图统一底纹颜色

### ISSUE THREAD

**Issue by fadeed** [antvis/G2Plot#2083]
![image](https://user-images.githubusercontent.com/6947411/101460704-e66fac80-3974-11eb-9811-39845d7bb94b.png)

**Comment by Me-Momo** [comment]
底色是指？active-region 吗？

**Comment by fadeed** [comment]
> 底色是指？active-region 吗？

是的，激活后的底纹颜色

**Comment by visiky** [comment]
ref: https://github.com/antvis/G2/pull/3284

**Comment by visiky** [comment]
Will be fixed in v2.3.12
