### ISSUE TITLE
数据量较大时，开启“曲线平滑功能”造成明显地性能损失

### ISSUE THREAD

**Issue by realeve** [antvis/G2Plot#2088]
# 例1
 在 [指标卡趋势图](https://g2plot.antv.vision/zh/examples/case/statistical-scenario#trend)中，当开启smooth:true时，移动鼠标查看 tooltip 感觉明显卡顿；关闭后正常。

## 开启时：189ms
![image](https://user-images.githubusercontent.com/448208/101566889-c68ac800-3a0a-11eb-9942-59a9d45e7e19.png)

## 关闭smooth:
![image](https://user-images.githubusercontent.com/448208/101566951-e4f0c380-3a0a-11eb-8cbd-b00758c388a7.png)
# 例2
在[多折线图](https://g2plot.antv.vision/zh/examples/line/multiple#line-large-data)，开启smooth:true时，大量报红，关闭后正常。
```js
import { Line } from '@antv/g2plot';

fetch('https://gw.alipayobjects.com/os/bmw-prod/55424a73-7cb8-4f79-b60d-3ab627ac5698.json')
  .then((res) => res.json())
  .then((data) => {
    const line = new Line('container', {
      data,
      xField: 'year',
      yField: 'value', 
      seriesField: 'category',
      smooth:true,
      xAxis: {
        type: 'time',
      },
      yAxis: {
        label: {
          // 数值格式化为千分位
          formatter: (v) => `${v}`.replace(/\d{1,3}(?=(\d{3})+$)/g, (s) => `${s},`),
        },
      },
    });

    line.render();
  });

```

![image](https://user-images.githubusercontent.com/448208/101567257-73fddb80-3a0b-11eb-80aa-362726c9a83e.png)

![image](https://user-images.githubusercontent.com/448208/101567325-942d9a80-3a0b-11eb-82f7-3df0ae0ced54.png)

**Comment by hustcc** [comment]
感谢反馈，折线平滑有大量的 path 计算，对于数量大的时候，性能问题被放大了。建议在大数据下设置 smooth: false。

后面针对性能问题我们集中解决 @zqlu
