### ISSUE TITLE
如何去除默认line标识，如何format Tooltip的title

### ISSUE THREAD

**Issue by ferried** [antvis/G2Plot#2089]
![image](https://user-images.githubusercontent.com/26159886/101567535-f4bcd780-3a0b-11eb-96f1-e5ecf3b5a356.png)

**Comment by hustcc** [comment]
tooltip title 默认是 x 轴。之前提了一个 g2 的 pr 做 title 的 function 支持，但是被再飞拍了。 @zqlu 感觉可以加回来。

**Comment by Me-Momo** [comment]
使用的是area吗，是的话 设置 line: false
