### ISSUE TITLE
水波图resize的时候，水波动画异常

### ISSUE THREAD

**Issue by hello-stranger-welcome** [antvis/G2Plot#2091]
1. 正常渲染dom的时候，一切正常
2. resize一下渲染的dom后，水波动画出现明显异常
3. console报错 off-screen group animate error!
![image](https://user-images.githubusercontent.com/66589121/101603821-15505600-3a3b-11eb-9248-f2baaa1ae5b2.png)

**Comment by hello-stranger-welcome** [comment]
![搜狗截图20201209162949](https://user-images.githubusercontent.com/66589121/101604369-cb1ba480-3a3b-11eb-9006-4fb9a56e29b3.png)

**Comment by hustcc** [comment]
2 resize 的动画异常是什么？
3 可以忽略，已经 try catch 的异常点，不影响实际渲染和使用，后续解决之后会去掉这个异常捕获。

**Comment by hello-stranger-welcome** [comment]
就是会感觉这个水波的动画一卡一卡的，不流畅

**Comment by hustcc** [comment]
盯着看一会，确实这动画有问题。我来看一下。

**Comment by hello-stranger-welcome** [comment]
好的

**Comment by hello-stranger-welcome** [comment]
@hustcc 大佬，如何了，有什么发现吗

**Comment by hustcc** [comment]
> @hustcc 大佬，如何了，有什么发现吗

已经解决了，顺便增强了一下样式能力。
