### ISSUE TITLE
柱线混合图表是否可以实现共用一个Y轴，或者将Y轴数值设置一样

### ISSUE THREAD

**Issue by NierWinter** [antvis/G2Plot#2094]
![截图_20201210104611](https://user-images.githubusercontent.com/58876127/101715327-3914aa00-3ad6-11eb-85d0-1ad4ff1fd22a.png)

**Comment by lxfu1** [comment]
```ts
 yAxis: [
    {},
    {
      label: false
    }
  ],
```

**Comment by lxfu1** [comment]
```ts
  yAxis: [
    {
      max: 1000,
      min: 0
    },
    {
      max: 1000,
      min: 0
    }
  ],
```

**Comment by NierWinter** [comment]
> ```ts
>   yAxis: [
>     {
>       max: 1000,
>       min: 0
>     },
>     {
>       max: 1000,
>       min: 0
>     }
>   ],
> ```

感谢大佬解惑
