### ISSUE TITLE
图表能调scale吗(不考虑手动设置min，max)？很多chart都有这个问题

### ISSUE THREAD

**Issue by potatozerg** [antvis/G2Plot#2097]
sandbox挂了，通过下面的链接然后替换data就能看到我的问题。

https://g2plot.antv.vision/zh/examples/box/basic#basic

const data = [
  {
    "x": "price",
    "low": 44.625,
    "q1": 45.255,
    "median": 45.4,
    "q3": 45.54,
    "high": 45.85,
  }
];

**Comment by potatozerg** [comment]
还有box chart里面应该是min-q1-median-q3-max而不是low-q1-median-q3-high

**Comment by Me-Momo** [comment]
![image](https://user-images.githubusercontent.com/15646325/101845131-d9c3a200-3b88-11eb-8d0f-d5b9c0326312.png)

@hustcc 这个是不是自动调整坐标轴为 0 起点导致的

**Comment by hustcc** [comment]
可能是的，但是这个逻辑应该 box 没有接入，可以看看。


@potatozerg 设置默认的 min 为 null，内部就会自动计算了。

```ts
yAxis: {
  min: null,
},
```

**Comment by potatozerg** [comment]
@hustcc 多谢！
