### ISSUE TITLE
数据大于150000（15w）行，直方图（histgram）生成报错。

### ISSUE THREAD

**Issue by potatozerg** [antvis/G2Plot#2100]
数据大于130000（我的数据125000行可以）行，直方图（histgram）生成报错。
这个能用配置解决吗还是必须自己先整理数据
![image](https://user-images.githubusercontent.com/3282773/101939916-b5c98600-3bb3-11eb-871e-64602fdd508d.png)

我看之前也有类似的issue: https://github.com/ant-design/ant-design-charts/issues/63

**Comment by arcsin1** [comment]
@potatozerg  这个我们检查下，晚点回复你

**Comment by hustcc** [comment]
@potatozerg 能有更具体的报错信息吧，比如上图 get-range 这一行具体是哪个代码。

**Comment by visiky** [comment]
![image](https://user-images.githubusercontent.com/15646325/107306402-c4eb8800-6abf-11eb-9cc6-941f19b46561.png)

125001 开始报错，复现链接：https://riddle.alibaba-inc.com/riddles/29e758ff

**Comment by visiky** [comment]
这个问题出现在 G 层，需要在 G 层对极小值进行处理（同理，G2 绘制直方图也有这个问题）

**Comment by visiky** [comment]
![image](https://user-images.githubusercontent.com/15646325/107323578-76e77c00-6ae1-11eb-9b08-810a70cd1a76.png)
li浏览器限制，需要在 util 封装一个求 max 方法

**Comment by visiky** [comment]
ref: https://github.com/antvis/util/pull/58/files

**Comment by visiky** [comment]
Will be fixed in v2.3.12
