### ISSUE TITLE
饼图中，标签文本中autoElispse在ts中找不到字段的定义

### ISSUE THREAD

**Issue by Timesgoes** [antvis/G2Plot#2101]
![image](https://user-images.githubusercontent.com/30331225/102048009-4523a300-3e19-11eb-9a8f-f687c2ec5903.png)

**Comment by Me-Momo** [comment]
为什么会在 label 中使用 autoEllipsis，在哪里看到的使用方式

**Comment by Timesgoes** [comment]
![image](https://user-images.githubusercontent.com/30331225/102049490-ea3f7b00-3e1b-11eb-8a20-755657794e5e.png)

**Comment by Timesgoes** [comment]
我看这个图例说明说是在标签文本中，他不是在这里使用的话，是在哪里使用的呀？

**Comment by Me-Momo** [comment]
应该是文档错误了  我把它移除掉；不过你这边的场景是啥，需要使用到 autoEllipsis（现在默认移除面板 label 会自动省略）

**Comment by Timesgoes** [comment]
嗷嗷 好的 我现在版本是2.2.11， 请问是最新版本才可以自动省略吗
