### ISSUE TITLE
spider 文本样式设置

### ISSUE THREAD

**Issue by gg-ui** [antvis/G2Plot#2102]
* **G2Plot Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

蜘蛛布局的饼图文本颜色与图例的字体颜色怎么设置为对应饼块的颜色

**Comment by Me-Momo** [comment]
将 label 的 `style.fil`l 设置为 null 即可
```
  label: {
    type: 'spider',
    style: {
      fill: null
    }
  },
```
