### ISSUE TITLE
百分比柱图刻度大于100%

### ISSUE THREAD

**Issue by xiecg** [antvis/G2Plot#2105]
* **G2Plot Version**: 2.3.2
* **Platform**: mac 10.15.7
* **Mini Showcase(like screenshots)**:
![image](https://user-images.githubusercontent.com/10857932/102062739-1664f700-3e30-11eb-8f03-c948259ae069.png)

* **CodePen Link**: https://codesandbox.io/s/compassionate-darkness-7zehs

![image](https://user-images.githubusercontent.com/10857932/102063946-a22b5300-3e31-11eb-8d93-fd57430cce10.png)

把 B_3 金额中的 2.22 改为 2.21 、 2.23 或者其他的数就没有这个问题，应该是精度问题。

**Comment by xiecg** [comment]
yAxis.max = 1 可以解决这个问题，但我还是提一下吧

**Comment by dengfuping** [comment]
百分比堆叠面积图也有这个问题，需要在 G2Plot 层限制 yAxis 的最大值: https://codesandbox.io/s/amazing-sutherland-jgdfe1?file=/index.js
