### ISSUE TITLE
DualAxes混合图组件只支持柱线混合图？

### ISSUE THREAD

**Issue by ShowJoy** [antvis/G2Plot#2110]
* **G2Plot Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

DualAxes混合图组件可以支持箱形，折线混合图

**Comment by liuzhenying** [comment]
折线混合图，支持，见https://g2plot.antv.vision/zh/examples/dual-axes/dual-line#dual-line
箱型混合图，目前不支持

**Comment by ShowJoy** [comment]
希望各类型的图能够自由组合，像echarts一样

**Comment by Me-Momo** [comment]
要不要尝试下多图层实验室 multiView

**Comment by hustcc** [comment]
@ShowJoy 常规通用是用法是柱线。如果需要定制，可以完全利用 G2 的强大自定义能力。G2Plot 是整体基于 G2 的能力封装的，所以在 G2Plot 上有两种方式：

1. 基于 多图层实验室 MultiView，可以基于 G2 做很多复杂能力，参考 [demo](https://g2plot.antv.vision/zh/examples/case/multi-view#nobel-prize)
2. 基于自定义扩展图表开发方式，开发之后，可以发包多处复用，参考 https://g2plot.antv.vision/zh/docs/manual/plugin
