### ISSUE TITLE
【bug】appendPadding属性update不生效

### ISSUE THREAD

**Issue by Hencky** [antvis/G2Plot#2111]
* **G2Plot Version**: 2.3.2
* **Platform**: macOs
* **Mini Showcase(like screenshots)**: 
* **CodePen Link**: https://codesandbox.io/s/tender-dijkstra-xf3id?file=/src/App.js

**update更改appendPadding属性**，图表**样式不改变**。希望改变appendPadding属性后，图表样式更新。

```js
    const line = new Line(domMountRef.current, {
      data,
      padding: "auto",
      xField: "Date",
      yField: "scales",
      xAxis: {
        type: "timeCat",
        tickCount: 5
      }
    });

    line.render();

    setTimeout(() => {
      line.update({
        appendPadding: 50
      });
    }, 2000);
```

现在效果：
![image](https://user-images.githubusercontent.com/40154205/102346944-a646a480-3fda-11eb-8580-22a69caf74b1.png)

期望效果：
![image](https://user-images.githubusercontent.com/40154205/102347043-ce360800-3fda-11eb-903b-b61996c4a6a1.png)

**Comment by hustcc** [comment]
问下为啥，需要在 update 的时候去更新 这个 appendPadding 属性，具体是什么场景下用？

**Comment by Hencky** [comment]
基于g2plot做可视化搭建，所有属性都可以修改的。

**Comment by hustcc** [comment]
了解了。
