### ISSUE TITLE
柱线混合图表的折线部分能否换成堆叠面积

### ISSUE THREAD

**Issue by NierWinter** [antvis/G2Plot#2119]
* **G2Plot Version**:2.0.8
* **Platform**:vue
* **Mini Showcase(like screenshots)**:
* 
![56387651](https://user-images.githubusercontent.com/58876127/102563859-34bf4100-4115-11eb-918e-81d7aaa93916.png)

* **CodePen Link**:

柱线混合图表折线部分可否换成面积图或实现类似的效果，我希望通过面积图清晰展示不同数据占柱状图的比例，以及它们之间 的对比。我有尝试对其中一条折线数据叠加，修改tooltip的显示数据，形成堆叠面积图的效果，但是当点击图例隐藏另一部分数据，叠加的数据当然展示的还是叠加的，很明显数据的展示就不对了。麻烦大佬解惑，有办法实现换面积图或实现类似的效果吗

**Comment by hustcc** [comment]
line 的配置中支持配置 isStack: true，和单独的折线图使用一样的。

**Comment by NierWinter** [comment]
> line 的配置中支持配置 isStack: true，和单独的折线图使用一样的。

感谢大佬!!
