### ISSUE TITLE
漏斗图数据中如果存在 0， null 的时候，页面崩溃

### ISSUE THREAD

**Issue by hustcc** [antvis/G2Plot#2124]
* **G2Plot Version**: latest
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

漏斗图，对称漏斗图，数据中如果存在 0， null 的时候，页面崩溃，应该是死循环了。必现

**Comment by xoptimal** [comment]
这个仍然没有得到解决, 当漏斗图数据, 都等于0的时候,  莫名其妙的怪异现象, 建议增加判断

**Comment by xoptimal** [comment]
@hustcc
