### ISSUE TITLE
Angular 8.0使用报错

### ISSUE THREAD

**Issue by sujie1992** [antvis/G2Plot#2134]
* **G2Plot Version**:2.3.3
* **Platform**:Angular8
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

 ERROR in node_modules/@antv/g2/lib/chart/controller/annotation.d.ts(14,9): error TS1086: An accessor cannot be declared in an ambient context.
    node_modules/@antv/g2/lib/chart/controller/base.d.ts(20,18): error TS1086: An accessor cannot be declared in an ambient context.
    node_modules/@antv/g2/lib/chart/controller/tooltip.d.ts(15,9): error TS1086: An accessor cannot be declared in an ambient context.
    node_modules/@antv/g2/lib/chart/event.d.ts(26,9): error TS1086: An accessor cannot be declared in an ambient context.
    node_modules/@antv/g2/lib/chart/event.d.ts(28,9): error TS1086: An accessor cannot be declared in an ambient context.
    node_modules/@antv/g2/lib/chart/event.d.ts(30,9): error TS1086: An accessor cannot be declared in an ambient context.
    node_modules/@antv/g2/lib/chart/event.d.ts(32,9): error TS1086: An accessor cannot be declared in an ambient context.
    node_modules/@antv/g2/lib/chart/event.d.ts(34,9): error TS1086: An accessor cannot be declared in an ambient context.
    node_modules/@antv/g2/lib/chart/event.d.ts(36,9): error TS1086: An accessor cannot be declared in an ambient context.
    node_modules/@antv/g2/lib/util/bbox.d.ts(19,9): error TS1086: An accessor cannot be declared in an ambient context.

**Comment by hustcc** [comment]
upgrade "typescript" at least "3.7.4"
