### ISSUE TITLE
DualAxes混合图使用X轴使用缩略轴或滚动条无效

### ISSUE THREAD

**Issue by fxt88** [antvis/G2Plot#2137]
* **G2Plot Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

在DualAxes混合图设置 slider: {start: 0.1,end: 0.2} 后缩略轴不显示，是DualAxes图不支持slider或scrollbar吗？

**Comment by hustcc** [comment]
暂时不支持。

**Comment by fxt88** [comment]
> 暂时不支持。

thx

**Comment by visiky** [comment]
@liuzhenying  @lxfu1  这个特性在双轴图上加了吗

**Comment by liuzhenying** [comment]
@lxfu1  已为双轴图增加了缩略轴，感谢

**Comment by yqf** [comment]
发现无法改变slider的垂直位置
