### ISSUE TITLE
viser图表框架，手动伸缩图表怎么让图表宽高自适应变化呢， g2可以用chart.forceFit(),那viser呢

### ISSUE THREAD

**Issue by MiaoJianxue** [antvis/G2Plot#2139]
* **G2Plot Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

viser图表框架，手动伸缩图表怎么让图表宽高自适应变化呢， g2可以用chart.forceFit(),那viser呢

**Comment by hustcc** [comment]
viser 是什么？G2Plot， ant design charts 一键 autoFit: true 生效不香嘛~

**Comment by MiaoJianxue** [comment]
是香，viser是基于g2用vue封装的图表框架，可是我都已经用viser写了，不可能因为不能手动触发图表自适应变化就放弃用这个，那要付出的时间成本太大了------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;hustcc&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年12月24日(星期四) 上午9:38
收件人:&nbsp;&quot;antvis/G2Plot&quot;<G2Plot@noreply.github.com&gt;;
抄送:&nbsp;&quot;MiaoJianxue&quot;<202051375@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [antvis/G2Plot] viser图表框架，手动伸缩图表怎么让图表宽高自适应变化呢， g2可以用chart.forceFit(),那viser呢 (#2139)

**Comment by MiaoJianxue** [comment]
问题就在刚刚解决了，我手动去触发window.resize事件就可以了，哈哈哈

**Comment by Me-Momo** [comment]
社区有 g2plot-vue 的封装，可以尝试去一起共建下

**Comment by MiaoJianxue** [comment]
好的(^-^)
