### ISSUE TITLE
element:click 事件重复触发

### ISSUE THREAD

**Issue by lxfu1** [antvis/G2Plot#2140]
* **G2Plot Version**: Lastest
* **Platform**:  PC
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:  

![image](https://user-images.githubusercontent.com/31396322/103050216-ca077d00-45ce-11eb-8a68-e4f97a31bf5f.png)

**Comment by visiky** [comment]
ref: https://github.com/antvis/G2/pull/3282

**Comment by visiky** [comment]
Will be fixed in v2.3.12
