### ISSUE TITLE
[需求]自定义图例marker支持实心圆

### ISSUE THREAD

**Issue by yuruwang** [antvis/G2Plot#2143]
* **G2Plot Version**:
* v2
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

现在G2 plot v2的的legend.marker的配置只能配置circle（是空心圆），如果要配置成实心圆的话需要自己指定fill颜色，但是目前fill不支持回调，且图例的颜色不好取到。希望后面能直接支持实心圆的图例marker

**Comment by visiky** [comment]
2.3.11 之后的版本已支持, 如下:
```ts
      legend: {
        marker: {
          symbol: 'circle',
          style: (oldStyle) => {
            return {
              ...oldStyle,
              fill: oldStyle.stroke,
              r: 4,
              // 去除描边
              lineWidth: 0
            }
          }
        }
      }
```
