### ISSUE TITLE
折线图在图元数据量过多的情况下会报栈溢出的错误

### ISSUE THREAD

**Issue by Heng77** [antvis/G2Plot#2148]
* **G2Plot Version**: 2.3.2
* **g-canvas Version**: 0.5.5
* **Platform**: macOS 11.1 
* **Mini Showcase(like screenshots)**:
![image](https://user-images.githubusercontent.com/75822361/103135314-5e1e3500-46f2-11eb-82ce-7011c3043209.png)

* **CodePen Link**:
https://codesandbox.io/s/peaceful-khorana-2zdzo?file=/src/components/HelloWorld.vue

当图元数据量较多的时候，貌似由于递归调用(draw → drawChildren → draw)导致了栈溢出。

**Comment by visiky** [comment]
duplicate with #2100
