### ISSUE TITLE
主题内容之前1.0是title, 副标题使用description，2.0版本后使用哪个属性呢?

### ISSUE THREAD

**Issue by cz495969281** [antvis/G2Plot#2149]
* **G2Plot Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

**Comment by hustcc** [comment]
2.0 移除这个能力，对于标题和描述，建议直接使用 html 实现，比如 ant design 等，样式更丰富，布局更灵活。
