### ISSUE TITLE
希望柱状图提供圆角配置功能

### ISSUE THREAD

**Issue by twtcc2351** [antvis/G2Plot#2157]
* **G2Plot Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

**Comment by hustcc** [comment]
求更具体的内容，比如你们的设计稿截图，图表示意图等等~

**Comment by twtcc2351** [comment]
柱状图图形柱子可配置border-radius，如图
![image](https://user-images.githubusercontent.com/48610673/103326530-b30fd180-4a8b-11eb-9e82-cf861b390fff.png)

**Comment by Me-Momo** [comment]
该特性将会在 2.3.8 提供
