### ISSUE TITLE
有没有计划做树形图，g6太不好用了，功能太简单

### ISSUE THREAD

**Issue by z-ab** [antvis/G2Plot#2158]
* **G2Plot Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

**Comment by hustcc** [comment]
对于重关系分析的，建议用 G6，而对于树图的节点有复杂 UI 结构的，建议用 X6，使用 react 定义节点。他们两的官网应该都有树图的 DEMO。如果能力上不满足可以在两者上提交 issue。

目前 G2Plot 是针对 G2 的统计图表封装，暂时不会做 G6 X6 的关系图封装，但是不排除长远的未来会修改 G2Plot 的概念为所有类型图表的封装。
