### ISSUE TITLE
line 折线图 缩略轴 slider 配置handlerStyle 只能配置宽高两个属性，建议增加图标和颜色等配置。

### ISSUE THREAD

**Issue by bigbigqiang** [antvis/G2Plot#2163]
* **G2Plot Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

**Comment by visiky** [comment]
ref: https://github.com/antvis/component/pull/220

**Comment by visiky** [comment]
暂不支持 slider 配置 handler 图标，后续再支持
