### ISSUE TITLE
堆叠面积图数据为空时，显示异常

### ISSUE THREAD

**Issue by kooriookami** [antvis/G2Plot#2165]
* **G2Plot Version**:2.3.6
* **Platform**:chrome
* **Mini Showcase(like screenshots)**:
第一张图是初始化为空数据时，changeData后的效果
![image](https://user-images.githubusercontent.com/38392315/103394600-74017f00-4b64-11eb-8492-54ff323f22fc.png)
第二张图是初始化有数据时的效果
![image](https://user-images.githubusercontent.com/38392315/103394609-854a8b80-4b64-11eb-9999-a3418fe8d7a0.png)
* **CodePen Link**:

**Comment by hustcc** [comment]
@kooriookami  有具体的 DEMO 代码吗，如何复现出来。

**Comment by kooriookami** [comment]
> @kooriookami 有具体的 DEMO 代码吗，如何复现出来。

官网的代码，顺序改成先渲染再赋值。
```html
import { Area } from "@antv/g2plot";

const area = new Area(document.getElementById("container"), {
  data: [],
  xField: "date",
  yField: "value",
  seriesField: "country"
});
area.render();
fetch(
  "https://gw.alipayobjects.com/os/bmw-prod/b21e7336-0b3e-486c-9070-612ede49284e.json"
)
  .then((res) => res.json())
  .then((data) => {
    area.changeData(data);
  });

```
