### ISSUE TITLE
气泡图tooltip格式化问题

### ISSUE THREAD

**Issue by libaofeng** [antvis/G2Plot#2174]
* **G2Plot Version**: antd chart  0.9.13 所依赖的g2plot版本
* **Platform**: g2plot React
* **Mini Showcase(like screenshots)**:  
![image](https://user-images.githubusercontent.com/21050566/103617164-b82bbf80-4f68-11eb-909e-d4fd4d2cc33f.png)
![image](https://user-images.githubusercontent.com/21050566/103617203-d2fe3400-4f68-11eb-9e21-d3b881e8dcec.png)

* **CodePen Link**:https://codesandbox.io/s/unruffled-violet-x5o1z?file=/demo.tsx

气泡图tooltip按照文档return{name value}的形式无法格式化多个维度的显示 想要的效果是第一张图，但是格式化之后只有第二张图

**Comment by yangguansen** [comment]
可以使用customContent，
```
customContent: ( title, data ) => {
	const listItemDom = data.map( v => `<li class="g2-tooltip-list-item">${v.name}: ${ v.value }</li>` ).join( '' );
	return `<div>
                        <div class="g2-tooltip-title">${title}</div>
                        <ul class="g2-tooltip-list">
	                        ${listItemDom}
                        </ul>
                        </div>`;
}
```

**Comment by libaofeng** [comment]
收到，多谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "antvis/G2Plot"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月6日(星期三) 下午3:42
收件人:&nbsp;"antvis/G2Plot"<G2Plot@noreply.github.com&gt;;
抄送:&nbsp;"那一年的风"<402228304@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [antvis/G2Plot] 气泡图tooltip格式化问题 (#2174)





 
可以使用customContent，
 customContent: ( title, data ) =&gt; { 	const listItemDom = data.map( v =&gt; `<li class="g2-tooltip-list-item"&gt;${v.name}: ${ v.value }</li&gt;` ).join( '' ); 	return `<div&gt;                         <div class="g2-tooltip-title"&gt;${title}</div&gt;                         <ul class="g2-tooltip-list"&gt; 	                        ${listItemDom}                         </ul&gt;                         </div&gt;`; }
