### ISSUE TITLE
changeData时候，有没有办法图像不全部重绘

### ISSUE THREAD

**Issue by TaoLabz** [antvis/G2Plot#2179]
* **G2Plot Version**: v2.2.12
* **Platform**: Chrome Vue
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

changeData能不能像echarts的setOption一样，对比两组数据然后只重绘更改的部分

**Comment by Me-Momo** [comment]
你使用的是哪个 plot？

**Comment by TaoLabz** [comment]
> 你使用的是哪个 plot？

用的是v2.2.12版本的Line

**Comment by Me-Momo** [comment]
更新下最新版本, refer: https://github.com/antvis/g2plot/pull/2142

**Comment by TaoLabz** [comment]
> 更新到最新版本, refer: #2142
解决了，谢谢^_^
