### ISSUE TITLE
在使用BidirectionalBar 制作基础水平方对称条形图设置title时左侧的title是反转的

### ISSUE THREAD

**Issue by 462937186** [antvis/G2Plot#2180]
* **G2Plot Version**:2.3.6
* **Platform**:Chrome Vue
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

在使用BidirectionalBar 制作基础水平方对称条形图设置title时左侧的title是反转的

**Comment by 462937186** [comment]
import { BidirectionalBar } from '@antv/g2plot';

export const data = [
  { country: '乌拉圭', '2016年耕地总面积': 13000.4, '2016年转基因种植面积': 12.3 },
  { country: '巴拉圭', '2016年耕地总面积': 14.4, '2016年转基因种植面积': 6.3 },
  { country: '南非', '2016年耕地总面积': 18.4, '2016年转基因种植面积': 8.3 },
  { country: '巴基斯坦', '2016年耕地总面积': 34.4, '2016年转基因种植面积': 13.8 },
  { country: '阿根廷', '2016年耕地总面积': 44.4, '2016年转基因种植面积': 19.5 },
  { country: '巴西', '2016年耕地总面积': 24.4, '2016年转基因种植面积': 18.8 },
  { country: '加拿大', '2016年耕地总面积': 54.4, '2016年转基因种植面积': 24.7 },
  { country: '中国', '2016年耕地总面积': 104.4, '2016年转基因种植面积': 5.3 },
  { country: '美国', '2016年耕地总面积': 165.2, '2016年转基因种植面积': 7.9 },
];

const BidirectionalBarPlot = new BidirectionalBar('container', {
  data,
  width: 400,
  height: 400,
  xField: 'country',
  xAxis: {
    position: 'bottom',
  },
  yAxis:{
    '2016年耕地总面积':{
      title:{
        text:'12421'
      }
      
    }
  },
  interactions: [{ type: 'active-region' }],
  yField: ['2016年耕地总面积', '2016年转基因种植面积'],
  tooltip: {
    shared: true,
    showMarkers: false,
  },
});

BidirectionalBarPlot.render();

**Comment by Me-Momo** [comment]
@arcsin1 帮忙看下这个问题

**Comment by arcsin1** [comment]
周末会看看 @462937186  带来问题 实在抱歉
