### ISSUE TITLE
使用图的时候。组件类型不兼容，几乎每个组件都有

### ISSUE THREAD

**Issue by NelsonYong** [antvis/G2Plot#2189]
举个柱形图的例子
报错如下：
不能将类型“{ data: { type: string; sales: number; }[]; xField: string; yField: string; label: { position: string; style: { fill: string; opacity: number; }; }; meta: { type: { alias: string; }; sales: { alias: string; }; }; }”分配给类型“ColumnConfig”。
  属性“label”的类型不兼容。
    不能将类型“{ position: string; style: { fill: string; opacity: number; }; }”分配给类型“false | ({ readonly fields?: string[] | undefined; readonly callback?: LabelCallback | undefined; readonly formatter?: string | IGroup | IShape | GeometryLabelContentCallback | undefined; } & GeometryLabelCfg) | undefined”。
      不能将类型“{ position: string; style: { fill: string; opacity: number; }; }”分配给类型“{ readonly fields?: string[] | undefined; readonly callback?: LabelCallback | undefined; readonly formatter?: string | IGroup | IShape | GeometryLabelContentCallback | undefined; } & GeometryLabelCfg”。
        不能将类型“{ position: string; style: { fill: string; opacity: number; }; }”分配给类型“GeometryLabelCfg”。
          属性“position”的类型不兼容。
            不能将类型“string”分配给类型“"middle" | ((data: Record<string, any>, mappingData: MappingDatum, index: number) => IntervalGeometryLabelPosition) | ... 4 more ... | undefined”。ts(2322)

**Comment by Me-Momo** [comment]
没有看懂描述的是什么意思，ts 问题

**Comment by hustcc** [comment]
@NelsonYong 不要标题党，认真反馈问题。组件不兼容是指什么？看 issue 描述是类型定义问题，先确实是自己的传参不符合类型定义，还是库的问题。
