### ISSUE TITLE
饼图 label 同时出现两个 0 时，拉线异常

### ISSUE THREAD

**Issue by visiky** [antvis/G2Plot#2192]
* **G2Plot Version**: latest
* **Platform**:
* **Mini Showcase(like screenshots)**:
![image](https://user-images.githubusercontent.com/15646325/104012155-4d89b680-51ea-11eb-9ed6-f543c47ebbd3.png)

* **CodePen Link**: https://riddle.alibaba-inc.com/riddles/381361a8

**Comment by Me-Momo** [comment]
ref: https://github.com/ant-design/ant-design-charts/issues/414

**Comment by visiky** [comment]
新版本中会解决
