### ISSUE TITLE
能否实现单独拎出Slider数据滑动条组件

### ISSUE THREAD

**Issue by NierWinter** [antvis/G2Plot#2202]
* **G2Plot Version**:lastest
* **Platform**:WINDOWS
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:https://g2plot.antv.vision/zh/examples/line/basic#line-slider

有场景使用到类似的组件，折线背景的滑动时间轴，因此我想请问大佬们，G2plot或是G2是否有api，能直接拿出这个组件独立成一个图表

**Comment by visiky** [comment]
拎出这个组件后，打算怎么使用

**Comment by NierWinter** [comment]
> 拎出这个组件后，打算怎么使用

我打算用来替代通常的日期选择框，通过这个组件的拖拽来控制多个图表的时间，以达到动态更新数据的效果

**Comment by visiky** [comment]
暂时不行哈 可以考虑用div做一个自定义的时间条
