### ISSUE TITLE
饼图中colorField可以配置为data中一个item中两个字段的合吗

### ISSUE THREAD

**Issue by Timesgoes** [antvis/G2Plot#2210]
* **G2Plot Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

**Comment by Me-Momo** [comment]
在数据层处理吧，比如：根据数据 map 后，增加一个字段来表识是什么类型的，再映射到 colorField

**Comment by Timesgoes** [comment]
嗷嗷 好的
