### ISSUE TITLE
饼图配置tooltip.shared: true时tooltip不渲染

### ISSUE THREAD

**Issue by yuruwang** [antvis/G2Plot#2216]
* **G2Plot Version**:
* V2
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

在饼图的配置中，配置tooltip的shared属性为true时，饼图的tooltip无法渲染，配置shared为false时不影响。官网上文档上写的可以配置shared，要不就改官网文档，要不就兼容一下这样的配置。
截图：
![image](https://user-images.githubusercontent.com/31492974/104434655-6cab8e00-55c6-11eb-82aa-f287c9ea1635.png)

**Comment by Me-Momo** [comment]
反馈收到~ 不过 api 文档是通用文档，具体的文档提示可以提交修改**图表指引**，主要进行图表的设计指引、快速上手介绍以及一些常见问题的解答。

文档的格式：https://www.yuque.com/antv/g2plot/igmuix （新增一个 H2: 常见问题, H3: 饼图设置 `tooltip: shared`, 内容大概描述下即可）
文件路径：`g2plot/docs/manual/plots/pie.zh.md`，`g2plot/docs/manual/plots/pie.en.md`

欢迎来提交 PR
