### ISSUE TITLE
饼图数据都为0的时候，tooltip 展示不一致

### ISSUE THREAD

**Issue by jqClub** [antvis/G2Plot#2220]
* **G2Plot Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

1.数组中都为0的时候
![image](https://user-images.githubusercontent.com/27038856/104556686-00d72d00-567b-11eb-8ed6-36e671f3de74.png)

2.数组中有一个不为0的时候
![image](https://user-images.githubusercontent.com/27038856/104556669-f61c9800-567a-11eb-9f9d-51bb5b0016ac.png)

**Comment by hustcc** [comment]
@jqClub 这个有什么问题吗？
