### ISSUE TITLE
scrollbar 配置高度无效

### ISSUE THREAD

**Issue by songsng** [antvis/G2Plot#2222]
* **G2Plot Version**:
"@ant-design/charts": "^1.0.11",
 "@antv/g2plot": "^2.2.11",

* **Platform**:
*mac air
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:
* https://antv-g2plot.gitee.io/zh/examples/column/basic#scrollbar

![image](https://user-images.githubusercontent.com/46083022/104586443-70134800-56a0-11eb-80b0-205feb5e0d78.png)
![image](https://user-images.githubusercontent.com/46083022/104586486-7dc8cd80-56a0-11eb-8e07-fede916f8cff.png)
如图所示，配置滚动条高度没有效果

**Comment by YanYuanFE** [comment]
type需要vertical配置height才会生效

**Comment by songsng** [comment]
> type需要vertical配置height才会生效

![image](https://user-images.githubusercontent.com/46083022/104705766-49631900-5755-11eb-9558-a5ee13326acb.png)
这个配置不是调整滚动条的高度么，另外，我试了下，type=vertical 也有问题

**Comment by YanYuanFE** [comment]
我看错了，sorry，width才是vertical下有效
