### ISSUE TITLE
Is there a way to sort tooltip values in Column chart?

### ISSUE THREAD

**Issue by mhamrah** [antvis/G2Plot#2223]
* **G2Plot Version**: 2.3.7

<img width="401" alt="image" src="https://user-images.githubusercontent.com/91162/104619226-9f539600-565b-11eb-83b2-7550c08f1c68.png">

I'd like these tooltip entries sorted by value. Is it possible? Thank you.

**Comment by visiky** [comment]
you can use `tooltip.customContent` to custom content of tooltip

**Comment by hustcc** [comment]
准备 G2 层增加 items 配置，可以进行渲染前的排序，过滤等。

**Comment by mhamrah** [comment]
Will try that, thank you.
