### ISSUE TITLE
Slider in multi-view

### ISSUE THREAD

**Issue by JyotsnaC** [antvis/G2Plot#2233]
* **G2Plot Version**: 4.0.15
* **Platform**: Mac
* **Mini Showcase(like screenshots)**:
Below is a video of my problem
![Screen Recording 2021-01-17 at 12 03 35 AM](https://user-images.githubusercontent.com/274296/104832629-08076200-5858-11eb-9cb3-8907d1870a04.gif)

How can I add slider in range/Multi view chart ?

**Comment by ai-qing-hai** [comment]
Can you provide clearer pictures and more information
