### ISSUE TITLE
水波图 配置

### ISSUE THREAD

**Issue by Hsugar** [antvis/G2Plot#2236]
* **G2Plot Liquid**:
水波图相关配置怎么设置：
1、边线与水波之间的间距
2、水波的相位、振幅 
3、水波动画的周期、方向、速度等支持吗

**Comment by hustcc** [comment]
1 支持，具体看文档。
2，3 暂时没有开放出来！

**Comment by Hsugar** [comment]
![image](https://user-images.githubusercontent.com/28952469/104913182-3441f080-59c8-11eb-8243-0298e1937dc0.png)
https://antv-g2plot.gitee.io/zh/docs/api/graphic-style

文档并没有说明。是哪个参数麻烦贴下
2、3 会更新吗？

**Comment by hustcc** [comment]
DEMO 和文档中都有描述的，具体见：https://g2plot.antv.vision/zh/docs/api/plots/liquid#outline

2，3 会更新，但是优先级不高！估计在年后左右。🙇‍♂️

**Comment by Hsugar** [comment]
![image](https://user-images.githubusercontent.com/28952469/104978042-fbdbfa00-5a3b-11eb-9678-de304f96c2ba.png)

试过了，border生效了但disatance没生效

**Comment by visiky** [comment]
1. 实际像要的 distance = distance 配置 -   border / 2，这里配置 `distance: 10` 实际为 4
2. typo：not `disatance`

**Comment by Hsugar** [comment]
![image](https://user-images.githubusercontent.com/28952469/104981982-a3f5c100-5a44-11eb-8edc-3503a1feabba.png)

修改完disatance  间距并没有任何变化呢

**Comment by hustcc** [comment]
TODO:

- [ ] 水波的相位、振幅
- [ ] 水波动画的周期、方向、速度等支持

**Comment by hustcc** [comment]
> ![image](https://user-images.githubusercontent.com/28952469/104981982-a3f5c100-5a44-11eb-8edc-3503a1feabba.png)
> 
> 修改完disatance 间距并没有任何变化呢

文档拼写错误，应该是 `distance`.

**Comment by Hsugar** [comment]
get！
官方API修正下：
![image](https://user-images.githubusercontent.com/28952469/104982943-b40ea000-5a46-11eb-842e-506d2c70dc93.png)

**Comment by hustcc** [comment]
> get！
> 官方API修正下：
> ![image](https://user-images.githubusercontent.com/28952469/104982943-b40ea000-5a46-11eb-842e-506d2c70dc93.png)

上面关联的 PR 已经改了。
