### ISSUE TITLE
环形饼图设置pie-statistic-active后，tooltip无效

### ISSUE THREAD

**Issue by ymsh** [antvis/G2Plot#2239]
环形饼图设置了pie-statistic-active后，tooltip不能出现，开发者工具没有报js错误。

代码如下：
interactions: [
                { type: 'element-active' },
                {
                  type: 'pie-statistic-active',
                  cfg: {
                    start: [
                      { trigger: 'element:mouseenter', action: 'pie-statistic:change' },
                      { trigger: 'legend-item:mouseenter', action: 'pie-statistic:change' }
                    ],
                    end: [
                      { trigger: 'element:mouseleave', action: 'pie-statistic:reset' },
                      { trigger: 'legend-item:mouseleave', action: 'pie-statistic:reset' }
                    ]
                  }
                }
]

只保留下面代码可以正常显示tooltip：
interactions: [
                { type: 'element-active' },
]

**Comment by visiky** [comment]
开启中心文本的时候，默认关闭 tooltip，可以使用以下方式开启
```
  interactions: [ { type: 'pie-statistic-active' }, { type: 'tooltip', enable: true }],

```

**Comment by ymsh** [comment]
谢谢提供指导，解决问题
