### ISSUE TITLE
仪表盘 刻度器配置不生效

### ISSUE THREAD

**Issue by Hsugar** [antvis/G2Plot#2243]
* **G2Plot Gauge**:

![image](https://user-images.githubusercontent.com/28952469/105018229-ae817c00-5a7f-11eb-9d7d-4a42ca1d3f43.png)

标记部分配置未生效。
官网API 中 “pivot” 的配置参数是不是更新为“indicator” ？ 
单独的pointer、base、pin 配置就无法使用了

**Comment by visiky** [comment]
查看 2.x 的 api 文档，不使用 1.x 的

**Comment by Hsugar** [comment]
👌  感谢。
2.x对中心原点不支持配置了吗？默认是白色圆点
1.x是base参数，我看2.x没有这个参数了

**Comment by Hsugar** [comment]
![image](https://user-images.githubusercontent.com/28952469/105149855-f7e4d080-5b3e-11eb-9bba-585e393084d5.png)
这块是否支持动态配置？没找到相关参数

**Comment by Hsugar** [comment]
> 查看 2.x 的 api 文档，不使用 1.x 的

Look forward to your reply

**Comment by alphabetabc** [comment]
@visiky 仪表盘文档有明显错误，axis下面只有label和position么？下面的min、max应该不是给label的吧？
![image](https://user-images.githubusercontent.com/29876424/105611361-bb8bcb80-5def-11eb-86de-e7668a6dce77.png)

**Comment by visiky** [comment]
> ![image](https://user-images.githubusercontent.com/28952469/105149855-f7e4d080-5b3e-11eb-9bba-585e393084d5.png)
> 这块是否支持动态配置？没找到相关参数

设置 `range` 的 color 和 ticks

**Comment by Hsugar** [comment]
> > ![image](https://user-images.githubusercontent.com/28952469/105149855-f7e4d080-5b3e-11eb-9bba-585e393084d5.png)
> > 这块是否支持动态配置？没找到相关参数
> 
> 设置 `range` 的 color 和 ticks

我想设置的range之外的背景填充。
比如下图 range0-0.9 可以设置，但0.9-1 没法设置
![image](https://user-images.githubusercontent.com/28952469/105705176-cad35c00-5f4a-11eb-8583-83120c14d3e9.png)

**Comment by visiky** [comment]
`[0, 0.5, 1] -> ['red', 'yellow']`
