### ISSUE TITLE
漏斗图用setState自定义状态，无效

### ISSUE THREAD

**Issue by twtcc2351** [antvis/G2Plot#2246]
* **G2Plot Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

import { Funnel } from '@antv/g2plot';

const data = [
  { stage: '简历筛选', number: 253 },
  { stage: '初试人数', number: 151 },
  { stage: '复试人数', number: 113 },
  { stage: '录取人数', number: 87 },
  { stage: '入职人数', number: 59 },
];

const funnelPlot = new Funnel('container', {
  data: data,
  xField: 'stage',
  yField: 'number',
  legend: false,
  state:{
    custormState:{
      style:{
        stroke:"#f00"
      }
    }
  },
});

funnelPlot.render();
funnelPlot.setState('custormState',data=>{
  return data.number > 100
})
通过自定状态改变漏斗图图形样式

**Comment by visiky** [comment]
哈？不支持 `custormState` 👉 [plot.setState](https://g2plot.antv.vision/zh/docs/api/plot-api#10-setstate)
