### ISSUE TITLE
 DualAxes图表，初始化时自定义图例选中状态

### ISSUE THREAD

**Issue by imakan** [antvis/G2Plot#2259]
双轴图表 如何在初始化自定义图例选中状态

```
 chartRef.chart.views[1].filter('name', (val: any) => {
         return val === 'xxxx';
});
```

**Comment by imakan** [comment]
@liuzhenying  大佬有结论吗？

**Comment by liuzhenying** [comment]
目前 g2 plot 图例初始化数据全显示的，初始不显示需自定义。
如果是分类数据，如堆叠柱-多折线图。迭代柱部分的初始化，如你所示
否则，例如 单折线-单折线，使用  dualAxes.chart.views[0].geometries[0].changeVisible(false) ，可参考 https://github.com/antvis/G2Plot/blob/master/src/plots/dual-axes/adaptor.ts 中的 legend 方法

**Comment by liuzhenying** [comment]
如果想直接利用g2 plot, 也可以采用另一种思路，初始化时 emit 一个图例点击事件，使其隐藏，写法可以参考 https://github.com/antvis/G2Plot/blob/master/__tests__/unit/plots/dual-axes/legend-spec.ts 供参考

**Comment by imakan** [comment]
@liuzhenying  感谢大佬

双轴（多折线）
```
['a', 'b', 'c', 'd'].forEach((item) = >{
    chartRef.chart.emit('legend-item:click', {
        target: legendContainer.findById(` - legend - item - $ {
            item
        } - name`),
        gEvent: {
            delegateObject: {
                item: {
                    id: item,
                    name: item,
                    value: item,
                    viewId: RIGHT_AXES_VIEW,
                    unchecked: false
                }
            }
        }
    });
});
```
使用 `dualAxes.chart.views[0].geometries[0].changeVisible(false) `方法legend隐藏了，但是dualAxes中还是存在相应的折线。

请问还有优化的空间吗？

**Comment by imakan** [comment]
@liuzhenying 感谢大佬

背景双轴（多折线）
第一种方案:
`dualAxes.chart.views[0].geometries[0].changeVisible(false)`
`legend`是隐藏了，但是dualAxes中还是存在相应的折线。（不清楚是不是姿势不对）

第二种方案：
```
['a', 'b', 'c', 'd'].forEach((item) = >{
    chartRef.chart.emit('legend-item:click', {
        target: legendContainer.findById(` - legend - item - $ {
            item
        } - name`),
        gEvent: {
            delegateObject: {
                item: {
                    id: item,
                    name: item,
                    value: item,
                    viewId: RIGHT_AXES_VIEW,
                    unchecked: false
                }
            }
        }
    });
});

```
看起来不是很优雅，请问有优化空间吗？

**Comment by liuzhenying** [comment]
g2plot 暂时没有提供这个 api，目前只能使用 g2 的能力去定制
