### ISSUE TITLE
plot.on事件触发问题

### ISSUE THREAD

**Issue by Zonciu** [antvis/G2Plot#2260]
* **G2Plot Version**: 2.3.9
* **G2 Version**: 4.1.7
* **Platform**: Windows 10，Edge 88.0.705.50
* **Mini Showcase(like screenshots)**:
* **CodePen Link**: https://codepen.io/zonciu/pen/NWRVewg

### 问题1 `plot.on`和`plot.chart.on`监听不一致
比较`plot.on === plot.chart.on`的结果是`true`，但是`plot.on`注册的`mousedown`事件不会触发，`plot.chart.on`注册的就可以触发。
然后`plot.on`和`plot.chart.on`注册`plot:mousedown`又都会触发。

### 问题2 某些事件不会触发
测试了`beforechangedata`和`afterchangedata`。
在[G2的仪表盘例子](https://antv-g2.gitee.io/zh/examples/gauge/gauge#color)中添加`chart.on('beforechangedata', e => console.log('from chart',e))`是正常触发的。

但是在G2Plot的[仪表盘例子](https://g2plot.antv.vision/zh/examples/progress-plots/gauge#basic)中使用

`gauge.on('beforechangedata', e => console.log('from plot',e))`

或

`gauge.chart.on('beforechangedata', e => console.log('from chart',e))`都不会触发

**Comment by hustcc** [comment]
求提供完整 Demo 代码，我们排查下，目前盲猜，可能的原因是 on 的代码是放在 render 之后。

**Comment by Zonciu** [comment]
[dist.zip](https://github.com/antvis/G2Plot/files/5861625/dist.zip)

**Comment by visiky** [comment]
原因定位到了，因为 gauge 的 changeData 并没有触发 G2 的changeData 事件。你这里是什么缘由需要使用到

**Comment by Zonciu** [comment]
> 原因定位到了，因为 gauge 的 changeData 并没有触发 G2 的changeData 事件。你这里是什么缘由需要使用到

在Blazor做G2Plot的封装

**Comment by visiky** [comment]
嗯，G2Plot 层改一下，保持使用统一
