### ISSUE TITLE
fontStyle setting unavailable when fontFamily is undefined.

### ISSUE THREAD

**Issue by yangguansen** [antvis/G2Plot#2265]
* **G2Plot Version**: v2.0.8
* **Platform**: mac/windows
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

I'm setting label fontStyle config as below
```
label: {
    style: {
      fill: 'red',
      opacity: 0.6,
      fontSize: 24,
      fontFamily: ${variable}
    }
  }
``` 
but when ${variable} is undefined , all fontStyle is unavailable, I think a warning or a tip is a good idea to debug when i adjust my customify fontStyle.

I will submit a PR about this if your team agree this pref, will your team approve and agree  this perf?

**Comment by visiky** [comment]
![image](https://user-images.githubusercontent.com/15646325/105937936-80102c00-6091-11eb-9c20-05b450321f60.png)

Could you provide a live demo~

**Comment by yangguansen** [comment]
> ![image](https://user-images.githubusercontent.com/15646325/105937936-80102c00-6091-11eb-9c20-05b450321f60.png)
> 
> Could you provide a live demo~

本来想fork个codeSandbox的demo的，但是官网案例里的codeSandbox都打不开了，是什么情况？

**Comment by visiky** [comment]
> > ![image](https://user-images.githubusercontent.com/15646325/105937936-80102c00-6091-11eb-9c20-05b450321f60.png)
> > Could you provide a live demo~
> 
> 本来想fork个codeSandbox的demo的，但是官网案例里的codeSandbox都打不开了，是什么情况？

貌似是 ts 丢失，暂时还没有解决。你看下用 codepen 先提供一个

**Comment by yangguansen** [comment]
> > > ![image](https://user-images.githubusercontent.com/15646325/105937936-80102c00-6091-11eb-9c20-05b450321f60.png)
> > > Could you provide a live demo~
> > 
> > 
> > 本来想fork个codeSandbox的demo的，但是官网案例里的codeSandbox都打不开了，是什么情况？
> 
> 貌似是 ts 丢失，暂时还没有解决。你看下用 codepen 先提供一个

codepen:
https://codepen.io/yangguansen/pen/KKNPoVr

**Comment by visiky** [comment]
这个问题 最好是深入到 G2 层是看下为什么～ 可以到 G2 上去看下，然后给予修复

**Comment by visiky** [comment]
ref: https://github.com/antvis/G2/issues/3253

**Comment by visiky** [comment]
> ref: [antvis/G2#3253](https://github.com/antvis/G2/issues/3253)



> > > > ![image](https://user-images.githubusercontent.com/15646325/105937936-80102c00-6091-11eb-9c20-05b450321f60.png)
> > > > Could you provide a live demo~
> > > 
> > > 
> > > 本来想fork个codeSandbox的demo的，但是官网案例里的codeSandbox都打不开了，是什么情况？
> > 
> > 
> > 貌似是 ts 丢失，暂时还没有解决。你看下用 codepen 先提供一个
> 
> codepen:
> https://codepen.io/yangguansen/pen/KKNPoVr

ref: https://github.com/antvis/G2/issues/3253 
看下这个，可以进去定位下为什么会这样子  然后提交 PR 修复
