### ISSUE TITLE
折线图区域填充

### ISSUE THREAD

**Issue by Hsugar** [antvis/G2Plot#2273]
* **G2Plot DualAxes**:
请问区域填充怎么设置？
![image](https://user-images.githubusercontent.com/28952469/105942127-97531780-6099-11eb-863f-36d590b98439.png)
期望的效果如下图：

![image](https://user-images.githubusercontent.com/28952469/105942213-bf427b00-6099-11eb-9779-7997444dc1fa.png)

**Comment by visiky** [comment]
目前暂不支持，先用 面积图替代吧

**Comment by visiky** [comment]
duplicate: #2130

**Comment by Hsugar** [comment]
> 目前暂不支持，先用 面积图替代吧


G2是否也不支持？没看到相关参数

**Comment by visiky** [comment]
> > 目前暂不支持，先用 面积图替代吧
> 
> G2是否也不支持？没看到相关参数

https://g2plot.antv.vision/en/examples/area/basic#basic-gradients G2 也是需要 line + area

**Comment by Hsugar** [comment]
> > > 目前暂不支持，先用 面积图替代吧
> > 
> > 
> > G2是否也不支持？没看到相关参数
> 
> https://g2plot.antv.vision/en/examples/area/basic#basic-gradients G2 也是需要 line + area

line + area 支持配置多条线否？

**Comment by visiky** [comment]
可以啊
