### ISSUE TITLE
关于legend的字文本颜色

### ISSUE THREAD

**Issue by baron-time** [antvis/G2Plot#2274]
// 自定义 legend
        legend: {
          custom: true,
          position: 'bottom',
          items: [
            {
              value: '户籍人口',
              name: '户籍人口',
              marker: { symbol: 'square', style: { fill: '#5B8FF9', r: 5}},
            },
            {
              value: '流动人口',
              name: '流动人口',
              marker: { symbol: 'square', style: { fill: '#61DDAA', r: 5 } },
            },
          ],
        },

我怎么给items里面的文本字加颜色  我试过外面写itemValue: { style: {fill:'#5B8FF9'} },  但是那样文字会多出一样的一个而且颜色只能一种 就不能指定自己是自己的颜色吗

**Comment by liuzhenying** [comment]
```
itemName: {
   style: {
     fill: '#f00'
    }
  }
```

可使用 itemName，目前 style 和 itemName 不支持函数
