### ISSUE TITLE
如何设置曲线默认不展示

### ISSUE THREAD

**Issue by halfcomfort** [antvis/G2Plot#2280]
如何设置可以让表中C维度的曲线默认灰色、不展示，点击后才展示

初始
![image](https://user-images.githubusercontent.com/5329383/105991149-6c3ee700-60de-11eb-8afb-6bcdcf8d3bc9.png)

点击“C“后
![image](https://user-images.githubusercontent.com/5329383/105991443-ba53ea80-60de-11eb-8674-cf9887dd0ad2.png)

**Comment by liuzhenying** [comment]
https://github.com/antvis/G2Plot/issues/2259   请参考下这个 issue
