### ISSUE TITLE
堆积面积图 多线条配置

### ISSUE THREAD

**Issue by Hsugar** [antvis/G2Plot#2281]
* **G2Plot Area**:
line - size 数组形式没生效：

![image](https://user-images.githubusercontent.com/28952469/106083175-fe82d180-6156-11eb-8db0-4b1bad7efb44.png)

**Comment by hustcc** [comment]
![image](https://user-images.githubusercontent.com/7856674/106983588-1aaef000-67a1-11eb-9daa-3ee53020537d.png)

size 通过的回调没有 seriesField 数据。

**Comment by Hsugar** [comment]
so long...  什么时候修复一下呢 ？

**Comment by Aarebecca** [comment]
在G2Plot v2.0中，设定`lineStyle`属性以配置线条样式：
```javascript
lineStyle:{
  lineWidth: 20,
  lineDash: [3, 5]
}
```
更多配置属性参见[这里](https://g2plot.antv.vision/zh/docs/api/plots/line#linestyle)
