### ISSUE TITLE
漏斗图：源码（捉虫）和 功能bug

### ISSUE THREAD

**Issue by alphabetabc** [antvis/G2Plot#2286]
* **G2Plot Version**: latest
* **Platform**: pc
* **Mini Showcase(like screenshots)**:
![image](https://user-images.githubusercontent.com/29876424/106235392-89d29480-6235-11eb-8b69-bf50d680c9f0.png)
![image](https://user-images.githubusercontent.com/29876424/106235487-ba1a3300-6235-11eb-86eb-1fe9d57c3b35.png)

* **CodePen Link**: nothing

1.  源码中有汉字，这块感觉不应该有，即使这是一个defaultOption
https://github.com/antvis/G2Plot/blob/master/src/plots/funnel/adaptor.ts
2. legend和label的联动问题，当legend关闭后，相应的label并没有关闭
https://antv-g2plot.gitee.io/zh/examples/more-plots/funnel#compare

**Comment by alphabetabc** [comment]
@liuzhenying 
第二个问题感觉是个bug

**Comment by liuzhenying** [comment]
第一个问题：目前还没有国际化方案，之后会优化
第二个问题：这个应该是 bug，assign 给我了，我修一下

**Comment by hustcc** [comment]
@liuzhenying 国际化也可以参考其他的做法，整理出一个方案试试看~之前也是遇到国际化问题，处理的方式是：

1. 内置的是用相对异动的英文
2. 可以通过 formatter 等方式让开发者自定义文案

**Comment by alphabetabc** [comment]
@liuzhenying 
这个没有必要写 显示一个百分比+label就已经很香了，formatter本来就有的

**Comment by alphabetabc** [comment]
漏斗图对autofit 支持的也不是很好

**Comment by liuzhenying** [comment]
> 漏斗图对autofit 支持的也不是很好
autofit 还需要一些优化，看你还蛮了解 g2 plot 及 g2，有没有兴趣加入一起开发

**Comment by alphabetabc** [comment]
@liuzhenying 
有机会的可以的，哈哈，g系列开源真是很大程度丰富了可视化的资源，因为以前很多东西看不懂

**Comment by visiky** [comment]
国际化在 2.3.23 版本已提供
