### ISSUE TITLE
折线图 数据类型-时间型 报错

### ISSUE THREAD

**Issue by Hsugar** [antvis/G2Plot#2288]
* **G2Plot Line**:
以下形式报错
 
![image](https://user-images.githubusercontent.com/28952469/106252927-ca400b80-6251-11eb-93b0-dc7378d345db.png)

**Comment by Hsugar** [comment]
and 切换数据类型、区域填充等样式没继承。
展示成黑色

**Comment by Hsugar** [comment]
and 切换数据类型、区域填充等样式没继承。
展示成黑色 :

![image](https://user-images.githubusercontent.com/28952469/106254374-9a920300-6253-11eb-9531-9a73e9f64247.png)

**Comment by hustcc** [comment]
1. 数据不是标准日期格式的。
2. 你的数据中是否不存在 分组字段？

**Comment by Hsugar** [comment]
1. 必须是标准格 YYYY/MM/DD hh:mm:ss ?
2. 只有一个区域也必须存在 分组字段吗？ 但是同样数据“cat”渲染出来了，如上第二张图。

**Comment by hustcc** [comment]
> 1. 必须是标准格 YYYY/MM/DD hh:mm:ss ?
> 
> 2. 只有一个区域也必须存在 分组字段吗？ 但是同样数据“cat”渲染出来了，如上第二张图。

1. 支持很多格式，但是建议使用标准的即可
2. 数据中没有 type 字段，但是又设置了 seriesField，问题是这个。

**Comment by Hsugar** [comment]
get～
试了下 数据必须是标准格式 YYYY/MM/DD hh:mm:ss，不然会报错 
TypeError: Invalid Time: 06:00 in time scale!

**Comment by hustcc** [comment]
建议别用 time 类型的 scale，一堆 bug，还可能会 oom，最近会准备重构，建议还是用 cat 类型，自己做好数据排序和补齐。

**Comment by Hsugar** [comment]
> 建议别用 time 类型的 scale，一堆 bug，还可能会 oom，最近会准备重构，建议还是用 cat 类型，自己做好数据排序和补齐。

👌 。 但“cat”类型怎么不支持配置区域颜色样式？ 也是bug吗

**Comment by hustcc** [comment]
进群聊，区间颜色跟这个应该没有关系。
