### ISSUE TITLE
基础柱状图：显示bug

### ISSUE THREAD

**Issue by 11gan6** [antvis/G2Plot#2293]
* **G2Plot Version**:latest
* **Platform**:pc
* **Mini Showcase(like screenshots)**:
* 加入连续性数据的时候，column重叠在了一起
![image](https://user-images.githubusercontent.com/50435482/106547266-e096e180-6547-11eb-9278-a989d58c7ecb.png)

* **CodePen Link**:
```js
import { Column } from '@antv/g2plot';

const data = [
  {y1: 1, y2: 2},
  {y1: 2, y2: 3},
  {y1: 3, y2: 4},
  {y1: 4, y2: 5},
]

const columnPlot = new Column('container', {
  data,
  xField: 'y1',
  yField: 'y2',
});

columnPlot.render();

**Comment by alphabetabc** [comment]
路过， const data = [
  {y1: 1, y2: 2},
  {y1: 2, y2: 3},
  {y1: 3, y2: 4},
  {y1: 4, y2: 5},
].map(d=>({...d,y1:d.y1+''}))  类目轴 别用数字了
