### ISSUE TITLE
MultiView：支持不同图层的图例集中展示

### ISSUE THREAD

**Issue by yuruwang** [antvis/G2Plot#2298]
* **G2Plot Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

使用场景：
如下图所示，面积图、多折线图的图例希望能同时展示在图表上
![image](https://user-images.githubusercontent.com/31492974/106706026-f41a7900-6629-11eb-89f5-4e9fde336d2f.png)

**Comment by visiky** [comment]
没有看到图例 ??? 是说标注还是图例

**Comment by visiky** [comment]
ref: #2299
