### ISSUE TITLE
出现依赖的@antv/g2中变量未导出的情况

### ISSUE THREAD

**Issue by alobe** [antvis/G2Plot#2300]
* **G2Plot Version**: 2.3.10
* **Platform**: mac OSX
* **Mini Showcase(like screenshots)**:
<img width="1221" alt="截屏2021-02-03 下午3 42 59" src="https://user-images.githubusercontent.com/16461608/106714511-e9b2ac00-6636-11eb-94cf-3bcd086104b1.png">
<img width="723" alt="截屏2021-02-03 下午3 47 22" src="https://user-images.githubusercontent.com/16461608/106714697-2f6f7480-6637-11eb-9534-ccbe715d19d2.png">
好像依赖的g2版本下载的版本较低为4.1.2，暂时没有导出Action造成的，4.1.9是有的

**Comment by hustcc** [comment]
那就升级一下哈~

**Comment by alobe** [comment]
> 那就升级一下哈~

这个可能应该要你们plot那边升级下@antv/g2😂

**Comment by hustcc** [comment]
^4.1.0 是会匹配到所有 4 版本的~ 你看看是不是你们的 lock 文件开启了。

**Comment by alobe** [comment]
> ^4.1.0 是会匹配到所有 4 版本的~ 你看看是不是你们的 lock 文件开启了。

果然，非常感谢哈，这个issue可以关了❤️
