### ISSUE TITLE
**柱状图** 更新数据时，数据有负数，柱子无法正确显示负数的柱子

### ISSUE THREAD

**Issue by yangguansen** [antvis/G2Plot#2303]
* **G2Plot Version**: v2.3.11
* **Platform**: Mac
* **Mini Showcase(like screenshots)**: 
![image](https://user-images.githubusercontent.com/24775952/106833648-dd7a2d80-66ce-11eb-8e59-898c72816613.png)

* **CodePen Link**: https://codepen.io/yangguansen/pen/KKNPoVr

柱状图初始化数据后，更新数据，新数据带有负数，则不能显示负数的柱子，Y轴没有显示出来负数部分，能不能给点提示修改哪里？我来试着修复一下

**Comment by hustcc** [comment]
change Data 的时候，没有更新 scale 的 min max，本周修复，下周发包！

可以先暂时使用 update API 吧~

**Comment by hustcc** [comment]
问题的原因是：

折、面、柱等图形，有一个逻辑，就是当数据全部大于 0 或者全部小于 0 的时候，会自动将 scale 的 min 或者 max 设置为 0，而在 changeData 的时候，应该也需要走一下这个逻辑。

**Comment by visiky** [comment]
参考这里，changeData 之前，再执行下 meta 更新 scale
![image](https://user-images.githubusercontent.com/15646325/106841071-5338c600-66dc-11eb-8179-7332a525345c.png)

**Comment by pearmini** [comment]
是不是 area, bar, column, line 都需要修复一下这个 bug 呀？那 tiny-area, tiny-colunm, tiny-line 需要吗?
