### ISSUE TITLE
[Feature Request] 希望双轴图增加双柱状图

### ISSUE THREAD

**Issue by kooriookami** [antvis/G2Plot#2304]
* **G2Plot Version**:
* 2.3.11
* **Platform**:
* win10 chrome88
* **Mini Showcase(like screenshots)**:
* 
![image](https://user-images.githubusercontent.com/38392315/106848085-31930b00-66eb-11eb-847d-2dabce0e7c63.png)
类似于
```js
geometryOptions: [
  {
    geometry: 'column',
    color: '#5B8FF9',
  },
  {
    geometry: 'column',
    color: '#5AD8A6',
  },
 ],
```

**Comment by hustcc** [comment]
这个图不是分组柱形图吗？不建议使用两侧柱子，如果你们设计也是这么设计的，建议驳回。

这个设计和可视化理念违背，容易导致错误的数据洞察。

**Comment by kooriookami** [comment]
好的
