### ISSUE TITLE
[Feature Request] 希望"漏斗图"增加"尖底漏斗图"

### ISSUE THREAD

**Issue by ntscshen** [antvis/G2Plot#2305]
是否有计划新增一个"漏斗图" -> "尖底漏斗图"
底层库G2中是存在的：https://g2.antv.vision/zh/examples/funnel/funnel#pyramid

**Comment by hustcc** [comment]
@liuzhenying 帮忙看看这个是否合理，如果合理，添加这个能力成本怎么样~
