### ISSUE TITLE
折线图横坐标从 1 开始时，后面所有点出现位置的横坐标都会减 1

### ISSUE THREAD

**Issue by lihaobhsfer** [antvis/G2Plot#2309]
* **G2Plot Version**: ^2.2.11
* **Platform**: macOS 11.2
* **Mini Showcase(like screenshots)**: 

![image](https://user-images.githubusercontent.com/17372464/106980182-b6067d80-672d-11eb-94c7-8133230b2769.png)

* **CodePen Link**:

如图所示。多条折线，每条线都会出现同样的问题。

**Comment by visiky** [comment]
x 轴不要使用数值型的

**Comment by hustcc** [comment]
category 有重复数据。

**Comment by lihaobhsfer** [comment]
这跟 category 没有关系吧？在 basic line 也是这种效果。

把横轴改成字符串之后确实显示没问题，但是有些反直觉。之前试过 Bizchart 里用数值就没问题。使用字符串还要自己确保数据是排好序的，处理数据的步骤又变繁琐了。
