### ISSUE TITLE
请教：当类目轴有两个一样的类目的时候该怎么处理？

### ISSUE THREAD

**Issue by alphabetabc** [antvis/G2Plot#2318]
* **G2Plot Version**:latest
* **Platform**:
* **Mini Showcase(like screenshots)**:
![image](https://user-images.githubusercontent.com/29876424/107169728-930fee00-69f9-11eb-9820-17ef31a376ff.png)

* **CodePen Link**: https://antv-g2plot.gitee.io/zh/examples/line/basic#line
-  如果不按照下面代码中方式进行处理，就会出现上图显示的问题， 这样处理对不对？g2中有没有对应的处理方式呢？
```js
import { Line } from '@antv/g2plot';
const data = [
    { x: '00:00', y: 1 },
    { x: '02:00', y: 2 },
    { x: '04:00', y: 5 },
    { x: '06:00', y: 6 },
    { x: '08:00', y: 1 },
    { x: '10:00', y: 3 },
    { x: '00:00', y: 9 }, // 数据产生了重复，
].map((d, i) => ({ ...d, x: i + '', xAlias: d.x })); 

const line = new Line('container', {
    data,
    xField: 'x',
    yField: 'y',
    xAxis: {
        title: {},
        type: 'linear',
    },
    tooltip: {},
    meta: {
        x: {
            // alias: 'xAlias', // 别名title
            formatter: (value, index) => {
                return data[index].xAlias;
            },
        },
    },
});

line.render();
```

**Comment by hustcc** [comment]
聚合掉。数据分析里面的聚合有 sum max min avg 等等。或者直接过滤掉去重即可。

这样的数据本身就不合理，这一时间有两个数据，并且数据还不一样，怎么理解？

**Comment by alphabetabc** [comment]
> 聚合掉。数据分析里面的聚合有 sum max min avg 等等。或者直接过滤掉去重即可。
> 这样的数据本身就不合理，这一时间有两个数据，并且数据还不一样，怎么理解？
在生产中是有这样的情况出现的，他代表的是下一个时间点的取样数据，可是直观的看的话，确实是从00:00 -- 00:00 , 后端不做处理的话只能从前端处理，这点比较坑爹，我能想到的就是这样去处理。。。 只是不知道这样处理有没有坑

**Comment by hustcc** [comment]
@alphabetabc 这个一定得让后端处理，你要坚持。如果是按照分钟来聚合的数据，那分钟就不可能重复。如果按照秒聚合的数据，那么时间返回的文本就到秒粒度。
