### ISSUE TITLE
Line plots seem to miss error bar support.

### ISSUE THREAD

**Issue by charxie** [antvis/G2Plot#2324]
Is there a way to draw error bars in line plots? (This is not exactly a bug report.)

**Comment by visiky** [comment]
maybe you can try custom a plot:
1, using custom plugins:  https://g2plot.antv.vision/en/docs/manual/plugin
2, using multi-view: https://g2plot.antv.vision/en/docs/api/multi-view

**Comment by charxie** [comment]
Thanks! Using annotations seem to be a good choice.
