### ISSUE TITLE
多折线图如何做到初始化时默认显示图例前5条折线？

### ISSUE THREAD

**Issue by HaLoJJ** [antvis/G2Plot#2327]
* **G2Plot Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

请问如何在多折线图中做到初始化时，默认显示图例的前5条，其他的图例变灰，但点击即可显示回来？我知道echarts是有selected属性的，不知道G2Plot有没有？
![image](https://user-images.githubusercontent.com/38327205/107461636-655fac00-6b95-11eb-9060-ef392fc4fe97.png)

**Comment by visiky** [comment]
duplicate with #2133
