### ISSUE TITLE
柱状图slider的Bug

### ISSUE THREAD

**Issue by NierWinter** [antvis/G2Plot#2335]
* **G2Plot Version**:lastest
* **Platform**:windows
* **Mini Showcase(like screenshots)**:
![bug](https://user-images.githubusercontent.com/58876127/108468074-25997280-72c1-11eb-8191-915a257c9837.png)

* **CodePen Link**:

柱状图在添加color的api的回调函数后，操作缩略轴时，x轴不再自适应收缩

**Comment by visiky** [comment]
在这边先关闭，等 G2 层解决
ref: https://github.com/antvis/G2/issues/3269
