### ISSUE TITLE
Treemap sort does not works as expected

### ISSUE THREAD

**Issue by calebeaires** [antvis/G2Plot#2338]
* **G2Plot Version**: 2.3.11
* **Platform**: OSx

Trying to sort treemap in a way that the name A goes to the first position from top to bottom. Sort function of hierarchyConfig does not work as it should work. 

![image](https://user-images.githubusercontent.com/794195/108564834-808f9180-72e2-11eb-90cf-60eb67858f58.png)

```js

import { Treemap } from '@antv/g2plot';

const data = {
  name: 'root',
  children: [

    { name: 'a', value: 9 },
    { name: 'b', value: 8 },
    { name: 'c', value: 7 },
    { name: 'd', value: 6 },
    { name: 'e', value: 5 },
    { name: 'f', value: 4 },
    { name: 'g', value: 10 },

  ],
};

const treemapPlot = new Treemap('container', {
  data,
  colorField: 'name',

  hierarchyConfig: {
    field: 'value',
    tile: 'treemapSquarify',
        sort: () => 1,
      }
});

treemapPlot.render();

```

**Comment by hustcc** [comment]
sort config is supported in #2337, new version will be released recently.

You can try it by clone code and run npm start.
