### ISSUE TITLE
饼图的tooltip不可用？

### ISSUE THREAD

**Issue by 805560947** [antvis/G2Plot#2341]
如题：
1.饼图的tooltip不可用？
2.官网的使用文档是不是没更新了？好多东西都不能用了

**Comment by hustcc** [comment]
v1 的代码使用 v2 的库运行吗？

提 issue 问题的时候，最好能按照 issue 模板来。

**Comment by visiky** [comment]
为了提高issue解决效率，不要一句话提问。先确认文档、历史提问issue，再提供版本、复现demo
