### ISSUE TITLE
g2plot 2.x 气泡图：轴标签设置 rotate 为 90°时，出现标签值偏移，需要 添加  offsetX 和 offsetY 方向偏移配置

### ISSUE THREAD

**Issue by rabbit-tian** [antvis/G2Plot#2343]
轴标签设置 rotate 为 90°时，出现标签值偏移，需要 添加  offsetX 和 offsetY 方向偏移配置
![image](https://user-images.githubusercontent.com/26690191/108840213-fb251d80-7610-11eb-8835-bc5d16c81974.png)

**Comment by rabbit-tian** [comment]
@visiky

**Comment by rabbit-tian** [comment]
@visiky 麻烦帮我加下哈
![image](https://user-images.githubusercontent.com/26690191/108840489-666eef80-7611-11eb-8047-0cd365320b7a.png)

**Comment by lxfu1** [comment]
```ts
label: {
  rotate: Math.PI / 2,
  style: {
    textAlign: 'start',
    textBaseline: 'middle'
  }
}
```
