### ISSUE TITLE
更新数据时，排序有问题

### ISSUE THREAD

**Issue by bowencool** [antvis/G2Plot#2346]
* **G2Plot Version**: `@ant-design/charts@1.0.18`
* **Platform**: `Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.182 Safari/537.36`
* **Mini Showcase(like screenshots)**:
![image](https://user-images.githubusercontent.com/20217146/108969841-c66ea000-76bc-11eb-94d3-0adc3415ffd7.png)
`{
  "height": 200,
  "xField": "value",
  "yField": "deviceType",
  "seriesField": "score",
  "marginRatio": 0.1,
  "isPercent": true,
  "isStack": true,
  "color": "ƒ color() {}",
  "label": {
    "position": "middle",
    "content": "ƒ content() {}",
    "style": "{fill: \"#fff\"}"
  },
  "meta": {
    "value": "{alias: \"占比\", formatter: ƒ formatter() {}}",
    "deviceType": "{alias: \"端类型\"}",
    "score": "{alias: \"分段\"}"
  },
  "data": [{"deviceType":"desktop","score":"Good(<1.5s)","value":93.81844557473451},{"deviceType":"desktop","score":"Need Improve","value":4.586374320475485},{"deviceType":"desktop","score":"Bad(≥2.5s)","value":1.5951801047900034},{"deviceType":"tablet","score":"Good(<1.5s)","value":null},{"deviceType":"tablet","score":"Need Improve","value":null},{"deviceType":"tablet","score":"Bad(≥2.5s)","value":null},{"deviceType":"mobile","score":"Good(<1.5s)","value":100},{"deviceType":"mobile","score":"Need Improve","value":0},{"deviceType":"mobile","score":"Bad(≥2.5s)","value":0}]
}`

**Comment by visiky** [comment]
更新版本，确保 G2Plot 也是最新版本
