### ISSUE TITLE
g2plot 折线点击事件无法触发

### ISSUE THREAD

**Issue by breakinferno** [antvis/G2Plot#2368]
* **G2Plot Version**: ^2.3.13-beta.1
* **Platform**: mac os
* **Mini Showcase(like screenshots)**: 
![image](https://user-images.githubusercontent.com/12684886/109267585-c26d8a00-7844-11eb-92e7-33d03286de59.png)

![image](https://user-images.githubusercontent.com/12684886/109267731-03659e80-7845-11eb-8d9b-7d5fbc05a079.png)

**Comment by visiky** [comment]
![image](https://user-images.githubusercontent.com/15646325/109293750-3456cb00-7867-11eb-9635-6f3218825869.png)

**Comment by breakinferno** [comment]
https://g2plot.antv.vision/zh/examples/case/customize#customize-tooltip

![image](https://user-images.githubusercontent.com/12684886/109378176-599d1500-790b-11eb-80df-df08ffe466d7.png)

**Comment by visiky** [comment]
brush 有时鼠标会和click冲突 建议你吧把brush 交互去掉。从鼠标交互上也是不并存的。需要两种交互同时的话 思考下如何在用户认知上做好交互互斥

**Comment by breakinferno** [comment]
@visiky 尝试去除了brush交互，仍然无法触发点击事件
![image](https://user-images.githubusercontent.com/12684886/109381029-cf58af00-7912-11eb-912d-8e2b8ff4030b.png)

**Comment by breakinferno** [comment]
@visiky  可以再看一下

**Comment by visiky** [comment]
没办法复现
