### ISSUE TITLE
矩形树formatter的时候能增加百分比字段

### ISSUE THREAD

**Issue by 1334310385** [antvis/G2Plot#2369]
* **G2Plot Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

![image](https://user-images.githubusercontent.com/48980855/109270691-60635380-7849-11eb-9840-3a7e4ae0112d.png)

是否可以在tooltip的formatter中增加百分比的返回，这样前端就不用再自己计算百分比了

**Comment by hustcc** [comment]
@liuzhenying 考虑下这个是否合理？
