### ISSUE TITLE
title设置不生效，不展示

### ISSUE THREAD

**Issue by Phyday** [antvis/G2Plot#2373]
* **G2Plot Version**:2.3.7
* **Platform**:vue2.5.16 Windows10
* **Mini Showcase(like screenshots)**:
![image](https://user-images.githubusercontent.com/38483257/109460168-24bfc800-7a9b-11eb-91b0-fa2f2b57a70c.png)
![image](https://user-images.githubusercontent.com/38483257/109460207-373a0180-7a9b-11eb-9f38-bd67dfd18336.png)

* **CodePen Link**:https://codesandbox.io/s/gallant-volhard-zr071

根据https://g2plot-v1.antv.vision/zh/examples/general/title-description#title-description-style配置标题后，不报错，但是不出现标题及描述，在官网的示例中测试同样不出现

**Comment by visiky** [comment]
看下升级指南，2.x 不支持
