### ISSUE TITLE
无法监听到自定义Action中抛出的事件类型

### ISSUE THREAD

**Issue by Esorakouki** [antvis/G2Plot#2374]
* **G2Plot Version**: 2.3.1
* **Platform**: MacOS
* **Mini Showcase(like screenshots)**: 
* **Riddle Link**:   https://riddle.alibaba-inc.com/riddles/1c5beb83

自定义Action并注册交互后，Action中抛出的事件类型无法被plot.on()捕获  @hustcc

**Comment by visiky** [comment]
包括的事件需要包装下，如下：

```ts
 public start() {
    this.emitEvent('test', G2.Event.fromData(2));
  }
```

类似问题见: https://github.com/antvis/G2/pull/3288

另外，可以通过 `G2.Action` 获取 Action class

```ts
import { Column, G2 } from '@antv/g2plot@2.3.13';

const Action = G2.Action;
```

**Comment by visiky** [comment]
@hustcc 你还需要完善 api 吗
