### ISSUE TITLE
漏斗图 转化率 配置conversionTag 不对

### ISSUE THREAD

**Issue by Petter-li** [antvis/G2Plot#2383]
* **G2Plot Version**: 2.3.11
* **Platform**:mac google
* **Mini Showcase(like screenshots)**:
![image](https://user-images.githubusercontent.com/24289824/109609838-ded03600-7b66-11eb-888d-a1706a66e4f8.png)

* **CodePen Link**:

增加conversionTag配置后，文档上提供的 datum.$$percentage$$ 计算出的转化率不对。

**Comment by hustcc** [comment]
怎么不对？ @Petter-li

**Comment by Petter-li** [comment]
> 怎么不对？ @Petter-li

例如上图，录取人数到入职人数的转化率应为：59 / 87 = 0.6782。但我加入默认的conversionTag配置后，转化率变成了上图的
23.32%

**Comment by liuzhenying** [comment]
转化率请使用 FUNNEL_CONVERSATION_FIELD, 这个是向外暴露的转化率字段，$$percentpage$$ 是内部使用的占比子项，是和第一项的比
参考文档：https://antv-g2plot.gitee.io/zh/docs/api/plots/funnel#funnelconversationfield
参考示例 ：https://antv-g2plot.gitee.io/zh/examples/more-plots/funnel#basic-transpose
