### ISSUE TITLE
热力图xAxis定义mask无效

### ISSUE THREAD

**Issue by Hsugar** [antvis/G2Plot#2385]
* **G2Plot Version 2.3.12**

  xAxis: {
    type: 'time',
    mask: "yyyy/mm/dd"
  }
目前基于我的数据只有“cat”能渲染，“time”，“linear”会报错。也无法mask格式

eg：https://codesandbox.io/s/eloquent-sound-ju6t7?file=/index.js:6587-6646

**Comment by Hsugar** [comment]
![Uploading image.png…]()

**Comment by visiky** [comment]
![image](https://user-images.githubusercontent.com/15646325/111861313-20931600-8988-11eb-9c22-f10c9ba2d048.png)

这里的文档再看下：https://g2plot.antv.vision/zh/docs/api/options/meta#metaoptiontype
