### ISSUE TITLE
求助：安装了最新的G2Plot，但一些复杂的图如柱线混合图表、双折线混合图表却无法显示，普通图表正常

### ISSUE THREAD

**Issue by BrettKang** [antvis/G2Plot#2392]
"@antv/g2plot": "^2.3.13",
  "name": "vue-antd-pro",
  "version": "3.0.0",
"ant-design-vue": "^1.6.2",

不知道是什么问题，
饼图-图形标签蜘蛛布局显示出来的也不是示例一样，spider外部只显示数字，不显示label

有同学知道是什么原因吗？

**Comment by BrettKang** [comment]
@vue/cli 4.5.7

**Comment by hustcc** [comment]
直接来一个 live demo，方便我们定位和解决吧！

**Comment by BrettKang** [comment]
> 直接来一个 live demo，方便我们定位和解决吧！

hustcc，我是在ant-design-vue-pro项目中使用，完全使用G2Plot的示例代码运行就是这样的情况。是不是跟哪个依赖项或环境版本有关？和代码没有关系，因为我直接使用的是G2Plot的示例代码也是完全一样的情况。

**Comment by hustcc** [comment]
> 安装了最新的G2Plot，但一些复杂的图如柱线混合图表、双折线混合图表却无法显示，普通图表正常

我看官网的双轴图， demo 都是可以运行的~ 你能具体提供代码，和运行之后的截图，报错吗？

**Comment by BrettKang** [comment]
使用下面的代码，图例不显示，在const dualLine = new DualLine 这个段落触发exception，但捕获不到异常内容

************************
<div id="curve1" style="height:420px;overflow:hidden;"></div>
import { DualLine } from '@antv/g2plot'

const dataa = [
              { year: '1991', value: 3 },
              { year: '1992', value: 4 },
              { year: '1993', value: 3.5 },
              { year: '1994', value: 5 },
              { year: '1995', value: 4.9 },
              { year: '1996', value: 6 },
              { year: '1997', value: 7 },
              { year: '1998', value: 9 },
              { year: '1999', value: 13 }
            ]

            const datab = [
              { year: '1991', count: 10 },
              { year: '1992', count: 4 },
              { year: '1993', count: 5 },
              { year: '1994', count: 5 },
              { year: '1995', count: 4.9 },
              { year: '1996', count: 35 },
              { year: '1997', count: 7 },
              { year: '1998', count: 1 },
              { year: '1999', count: 20 }
            ]

            const dualLine = new DualLine(document.getElementById('curve1'), {
              title: {
                visible: true,
                text: '双折线图'
              },
              description: {
                visible: true,
                text: '双折线混合图表'
              },
              data: [dataa, datab],
              xField: 'year',
              yField: ['value', 'count']
            })
            dualLine.render()

**Comment by hustcc** [comment]
DualLine 是属于 1.x 的图表。你看的文档是什么文档？

你使用的是 2.x 的 G2Plot，但是看的文档是 1.x 的，所以匹配不上！

**Comment by BrettKang** [comment]
啊，这样啊，1.x的文档里没有版本显示切换，我。。。。

**Comment by hustcc** [comment]
> 啊，这样啊，1.x的文档里没有版本显示切换，我。。。。

我来看加上跳转到最新版本的链接。
