### ISSUE TITLE
柱状图数据渲染丢失

### ISSUE THREAD

**Issue by MrSmallLiu** [antvis/G2Plot#2393]
* **G2Plot Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

当X轴字段值出现数字时，导致柱状图渲染错误。使用G2Plot官网即可复现
![image](https://user-images.githubusercontent.com/26038018/109895112-a432de80-7cc9-11eb-93b5-58978e42a689.png)

**Comment by visiky** [comment]
目前现在业务上保证 x 轴字段对应的数据都为字符串类型，后续会对 scale 进行升级

**Comment by MrSmallLiu** [comment]
好的，谢谢
