### ISSUE TITLE
玉钰图，数据值存在字符串数字渲染错误，存在字符串渲染崩溃

### ISSUE THREAD

**Issue by MrSmallLiu** [antvis/G2Plot#2394]
* **G2Plot Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

数值为字符串类型数值渲染不对，如果是字符串导致崩溃。G2Plot官网示例可复现
![image](https://user-images.githubusercontent.com/26038018/109895367-0d1a5680-7cca-11eb-9205-d8ce3b67db30.png)

**Comment by visiky** [comment]
有没有人感兴趣来处理下这个 issue，参考饼图异常数据处理：https://github.com/antvis/G2Plot/pull/1321

**Comment by MrSmallLiu** [comment]
这个issue我来处理
