### ISSUE TITLE
当对包含 antv图表的界面使用css3的transform做放大超过1.5倍时, 图表中的tooltip会被遮挡。

### ISSUE THREAD

**Issue by iBeginner-at** [antvis/G2Plot#2398]
* **G2Plot Version**: 2.3.8
* **Platform**:PC
* **Mini Showcase(like screenshots)**:
![image](https://user-images.githubusercontent.com/52527455/110064165-8b005f80-7da7-11eb-8291-3a6eda2a4261.png)

* **CodePen Link**:
![image](https://user-images.githubusercontent.com/52527455/110064174-92276d80-7da7-11eb-8d07-38b9829cb864.png)

我们的系统中有放大缩小界面指定区域的场景。
当对包含 antv图表的界面区域使用css3的transform做放大超过1.5倍时, 图表中的tooltip会被遮挡（效果见上面的截图）。

**Comment by hustcc** [comment]
@iBeginner-at 可以来一个 demo 实例吗？我官网 demo 测试是 ok 的。

**Comment by iBeginner-at** [comment]
https://user-images.githubusercontent.com/52527455/110080760-e4778700-7dc5-11eb-8ec0-e2cb5c58ba7d.mp4

**Comment by visiky** [comment]
我这边本地也不能复现，你先自查下 transform 和 zindex 的冲突是否存在

**Comment by visiky** [comment]
如果还有问题，可以看下这个配置是不是可以解决：
```ts
supportCSSTransform: true
```
