### ISSUE TITLE
当柱状图添加了ColumnStyle属性后, 在图表width过小时, 图表绘制会报错.

### ISSUE THREAD

**Issue by iBeginner-at** [antvis/G2Plot#2399]
* **G2Plot Version**: 2.3.8
* **Platform**: PC
* **Mini Showcase(like screenshots)**:

https://user-images.githubusercontent.com/52527455/110083272-7a60e100-7dc9-11eb-95c4-2317d387c236.mp4

* **CodePen Link**:

**Comment by visiky** [comment]
原因：radius 大于柱子宽度，导致计算 A 命令出错。

新版本中解决
