### ISSUE TITLE
提示框使用 customContent自定义的时候，内容字体变大，提示框 宽高不自适应了，这个问题可以修复不

### ISSUE THREAD

**Issue by rabbit-tian** [antvis/G2Plot#2403]
* **G2Plot Version**:  v2.3.12
* **Platform**: G2Plot 2.x
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

- 提示框使用 customContent自定义的时候，内容字体变大，提示框 宽高不自适应了
- 
![image](https://user-images.githubusercontent.com/26690191/110412864-ded0b880-80c7-11eb-9335-ebbb10ee6004.png)
- 
![image](https://user-images.githubusercontent.com/26690191/110412870-e2fcd600-80c7-11eb-82bd-5d436d4ddbcc.png)

**Comment by rabbit-tian** [comment]
@visiky 帮忙看看哦

**Comment by lxfu1** [comment]
设置一下 line-height
