### ISSUE TITLE
g2plot 2.x 刻度线长度的配置

### ISSUE THREAD

**Issue by rabbit-tian** [antvis/G2Plot#2405]
* **G2Plot Version**: v2.3.12
* **Platform**: G2Plot 2.x
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

- g2plot 2.x 刻度线长度的配置，目前只有宽度  lineWidth，没有长度配置(height, length, lineHeight 试了都没生效😭 )
- 
![image](https://user-images.githubusercontent.com/26690191/110413578-155b0300-80c9-11eb-8f38-bcb6d11eec08.png)

**Comment by rabbit-tian** [comment]
@visiky 帮忙看下问题

**Comment by lxfu1** [comment]
```ts
 tickLine: {
  length: 20
},
```
