### ISSUE TITLE
g2plot 2.x 坐标轴标签支持  水平方向偏移

### ISSUE THREAD

**Issue by rabbit-tian** [antvis/G2Plot#2407]
* **G2Plot Version**:  v2.3.12
* **Platform**: G2Plot 2.x
* **Mini Showcase(like screenshots)**: 
* **CodePen Link**: 

- 轴标签 label 目前只有 垂直方向上偏移 offset，没有  水平方向的偏移
![image](https://user-images.githubusercontent.com/26690191/110436488-42221100-80ef-11eb-8960-c1cdd94ef773.png)

**Comment by rabbit-tian** [comment]
@visiky 求加配置

**Comment by rabbit-tian** [comment]
@visiky 麻烦加下这个配置哈

**Comment by Aarebecca** [comment]
已经提交pr，将在下个版本可用，但尽量避免过大的偏移量，这会造成图表布局改变

**Comment by visiky** [comment]
更新依赖，确保 @antv/path-util 在 2.0.15 版本
