### ISSUE TITLE
Meta.alias 在饼图上不生效 

### ISSUE THREAD

**Issue by clancyz** [antvis/G2Plot#2409]
* **G2Plot Version**:
2.3.13
* **Platform**:
chrome 89
* **Mini Showcase(like screenshots)**:

### 期望效果

类似柱图、条形图，配置了meta.alias后在tooltip上有展示

![image](https://user-images.githubusercontent.com/4703150/110445666-523eee00-80f9-11eb-8ae7-99470f4f85fd.png)

### 实际效果

meta.alias在饼图上不起作用

![image](https://user-images.githubusercontent.com/4703150/110444376-e4de8d80-80f7-11eb-90ea-b0a18ee29cf7.png)

* **CodePen Link**:
https://codesandbox.io/s/epic-tesla-eskc6?file=/index.ts
https://riddle.alibaba-inc.com/riddles/5a488dbc

**Comment by visiky** [comment]
不是 `meta.alias` 不生效, 实质是饼图 tooltip 默认展示的规范。移步： #2410
