### ISSUE TITLE
【需求】图例支持配置默认显示哪几个

### ISSUE THREAD

**Issue by yuruwang** [antvis/G2Plot#2416]
* **G2Plot Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

目前g2plot图表的图例支持了手动点击图例来渲染/隐藏它对应的数据，但是不支持配置哪些图例的数据默认显示，哪些默认隐藏，效果类似下图：
![image](https://user-images.githubusercontent.com/31492974/110727427-39981a80-8256-11eb-8c79-580e09976bb2.png)

除了支持配置默认显示哪些图例之外，还有一个需求是：希望能配置一个图表上最多能显示n个图例的数据，如果用户手动点击显示第n+1个图例数据，则从原先的渲染数据中自动隐藏掉一个图例的数据。这个交互需求的考虑是不希望在数据比较多时造成用户视觉上的干扰，因此限制一个图表上能显示的图例数据总数

**Comment by visiky** [comment]
已经实现，待 G2 发版本 & 完善 G2Plot 文档

**Comment by visiky** [comment]
ref: https://github.com/antvis/G2Plot/discussions/2484
