### ISSUE TITLE
Fix: 面积图Bug，当横坐标有数据值为Number类型的5是，渲染图会出错

### ISSUE THREAD

**Issue by Too-Tao** [antvis/G2Plot#2419]
* **G2Plot Version**: 2.3.7
* **Mini Showcase(like screenshots)**:
* 
![image](https://user-images.githubusercontent.com/40811570/110887706-ba721780-8325-11eb-8e55-fc91426beac9.png)

* **CodePen Link**:
* https://codesandbox.io/s/exciting-nobel-z7uhd?file=/index.ts

1. 发现面积图，当数据源横坐标为数字5时会出现绘图错位的情况
![image](https://user-images.githubusercontent.com/40811570/110887999-4421e500-8326-11eb-859a-69e2cdf94fd9.png)
![image](https://user-images.githubusercontent.com/40811570/110888055-5e5bc300-8326-11eb-93b9-4c3c4050670e.png)

2. 将数据源中横坐标为数字5，改为字符串问题就没了，所以字符串5和数字5在横坐标上有什么区别，会导致绘图错位
![image](https://user-images.githubusercontent.com/40811570/110888209-b2ff3e00-8326-11eb-8265-8a36ce37395f.png)

3. 将数据源中横坐标为数字5的数据删除，问题就消失了
![image](https://user-images.githubusercontent.com/40811570/110888517-4d5f8180-8327-11eb-9c3e-b99cf62956ee.png)

4. 是不是横坐标数据类型最好为字符串，避免绘图错误问题

**Comment by hustcc** [comment]
- x 轴数据使用文本类型的

 - x 轴的 scale 类型使用 'cat'

```ts
meta: {
  time: { type: 'cat' }
}
```
