### ISSUE TITLE
Ant Design pro vue 引入 G2Plot Liquid浏览器报错

### ISSUE THREAD

**Issue by hhhanshuo** [antvis/G2Plot#2420]
```ts
import { Liquid } from '@antv/g2plot'

mounted () {
    const liquidPlot = new G2Plot.Liquid('container', {
      percent: 0.75,
      outline: {
        border: 4,
        distance: 8
      },
      wave: {
        length: 128
      }
    })
    liquidPlot.render()
  }
```

![image](https://user-images.githubusercontent.com/39038785/110892982-0cb83600-8330-11eb-9fab-cf17d34a25cd.png)

**Comment by hustcc** [comment]
从报错里面，点进去，看看具体是哪一行代码。

**Comment by hhhanshuo** [comment]
![image](https://user-images.githubusercontent.com/39038785/110894911-b816ba00-8333-11eb-9bc5-40a0b2218da6.png)

![image](https://user-images.githubusercontent.com/39038785/110894959-ccf34d80-8333-11eb-839d-e666efed2161.png)


![image](https://user-images.githubusercontent.com/39038785/110894873-a503ea00-8333-11eb-9918-80117a2577e2.png)

**Comment by hustcc** [comment]
看起来像是本地的开发环境问题，你能在 codesanbox 中搞一个 demo 吗？我调试一下！

**Comment by hhhanshuo** [comment]
大佬您好，我在codesanbox里面是没问题的，但是我在本地webstorm里面写就是报错。
是不是跟我用ant design pro vue 有关系呢？
codesanbox地址：：https://zcz5z.csb.app/

**Comment by hhhanshuo** [comment]
感谢大佬，我已经解决此问题了，确实是环境的问题！

**Comment by hustcc** [comment]
@hhhanshuo 如果解决，可以回复具体是什么原因导致的，怎么解决，这样其他同学也有个借鉴。

**Comment by yuanyayi** [comment]
@hhhanshuo 
抱歉跑来翻旧账，我遇到了一模一样的问题，请问下你是如何解决的？谢谢！
