### ISSUE TITLE
仪表盘设置statistics样式无效

### ISSUE THREAD

**Issue by yuruwang** [antvis/G2Plot#2421]
* **G2Plot Version**:
* 
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

仪表盘组件按照文档的方式设置statistics的title/content的style没有生效：
demo: https://riddle.alibaba-inc.com/riddles/4f0acf83
![image](https://user-images.githubusercontent.com/31492974/110895287-67ec2780-8334-11eb-9cb3-1a4ef39a72c7.png)

**Comment by visiky** [comment]
Demo 演示代码错误，统计文本的 style 是 cssProperity（我完善下文档）

```ts
content: {
      formatter: ({ percent }) => `Rate: ${(percent * 100).toFixed(0)}%`,
      style: {
        color: 'rgba(0,0,0,0.85)',
        fontSize: 60,
      },
    },
```

**Comment by visiky** [comment]
文档没问题：https://g2plot.antv.vision/zh/docs/api/plots/gauge#statistic
