### ISSUE TITLE
【需求】Tooltip 中支持排序

### ISSUE THREAD

**Issue by imyuxh** [antvis/G2Plot#2427]
* **G2Plot Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

**Comment by imyuxh** [comment]
如题 现在的tooltip中貌似不支持对多个项目做排序，提供的自定义方法中，也只能获取到鼠标选到的tooltip 无法获取整体从而排序，希望提供。

**Comment by hustcc** [comment]
```ts
tooltip: {
   customItems: () => {},
}
```

这个可能还没有在文档中体现出来。

**Comment by imyuxh** [comment]
> ```ts
> tooltip: {
>    customItems: () => {},
> }
> ```
> 
> 这个可能还没有在文档中体现出来。

这个customItems貌似是只对单个点的数据 做处理吧 我想要对所有数据做排序

**Comment by hustcc** [comment]
如果不满足，那我就没有理解你的意思了，需要你详细描述你的需求了。

**Comment by imyuxh** [comment]
> 如果不满足，那我就没有理解你的意思了，需要你详细描述你的需求了。

![image](https://user-images.githubusercontent.com/15729365/111157408-cf72d300-85d1-11eb-8b3a-67a0783cd2f0.png)
ru'tu如图 我想让每一个x轴对应的点的tooltip中 永远都按照y轴值的大小顺序从上至下排列 目前好像没法实现

**Comment by imyuxh** [comment]
> > 如果不满足，那我就没有理解你的意思了，需要你详细描述你的需求了。
> 
> ![image](https://user-images.githubusercontent.com/15729365/111157408-cf72d300-85d1-11eb-8b3a-67a0783cd2f0.png)
> ru'tu如图 我想让每一个x轴对应的点的tooltip中 永远都按照y轴值的大小顺序从上至下排列 目前好像没法实现

我的x轴是时间，也就是说我想让每一个时间，tooltip里从上至下的排列顺序，是按照我自己的方法来排列，在这个截图里面，我想要的就是从上至下依次：
name1: 0.1101177926927479,
name2：0.301262134500474，
name3:17.497414252304424

**Comment by visiky** [comment]
> > 如果不满足，那我就没有理解你的意思了，需要你详细描述你的需求了。
> 
> ![image](https://user-images.githubusercontent.com/15729365/111157408-cf72d300-85d1-11eb-8b3a-67a0783cd2f0.png)
> ru'tu如图 我想让每一个x轴对应的点的tooltip中 永远都按照y轴值的大小顺序从上至下排列 目前好像没法实现

你先使用下 customItems，自己在回调中处理 items 的顺序

**Comment by visiky** [comment]
Talk is cheap，show me your code

**Comment by imyuxh** [comment]
> ```ts
> tooltip: {
>    customItems: () => {},
> }
> ```
> 
> 这个可能还没有在文档中体现出来。

感谢 是我草率了 用这个就可以了 但确实文档中没看见 
顺便请您帮忙看下我的上一条提问 #2426 我附带了codepen link  可以重现

**Comment by imyuxh** [comment]
> > > 如果不满足，那我就没有理解你的意思了，需要你详细描述你的需求了。
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/15729365/111157408-cf72d300-85d1-11eb-8b3a-67a0783cd2f0.png)
> > ru'tu如图 我想让每一个x轴对应的点的tooltip中 永远都按照y轴值的大小顺序从上至下排列 目前好像没法实现
> 
> 你先使用下 customItems，自己在回调中处理 items 的顺序

感谢 这个确实可以 是我草率了
顺便请您帮忙看下我的上一条提问 #2426 我附带了codepen link 可以重现

**Comment by visiky** [comment]
@hustcc 补充下文档 ?
