### ISSUE TITLE
🌹堆叠玫瑰图🌹，label 相对于数据点在 Y 方向的偏移距离，存在偏差

### ISSUE THREAD

**Issue by ntscshen** [antvis/G2Plot#2437]
label 相对于数据点在 Y 方向的偏移距离偏差

![image](https://user-images.githubusercontent.com/21041458/111562386-1549ba00-87d1-11eb-88be-bd63a45d9605.png)

https://antv-g2plot.gitee.io/zh/examples/rose/stacked#basic 官网案例
```js
  label: {
    // offset: 10,
    offsetY: 10
  },
```

**Comment by visiky** [comment]
offsetX, offsetY 代表着 x 轴方向和 y 轴方向（polar 坐标系建议使用 offset，除非真的想纵向、横向偏移）

如图：offsetY 没有错误

**Comment by ntscshen** [comment]
赞👍，polar坐标中我去使用 offset offsetX。thanks @visiky
