### ISSUE TITLE
🐛 active-region 设置 Y 轴最大值后，获取 shape 错位

### ISSUE THREAD

**Issue by xiecg** [antvis/G2Plot#2438]
* **G2Plot Version**: 2.3.16
* **Platform**: mac 10.15.7 Chrome 89
* **Mini Showcase(like screenshots)**:
* **CodePen Link**: https://codesandbox.io/s/compassionate-darkness-7zehs?file=/index.js

设置了最大值后 hover 上背景色块只有一部分。

![image](https://user-images.githubusercontent.com/10857932/111590868-a33d9900-8801-11eb-9390-8f16d2de8b09.png)

另外这里的数字没有显示，似乎是被顶上去了。

![image](https://user-images.githubusercontent.com/10857932/111591240-26f78580-8802-11eb-9550-c9b05b9d2662.png)

**Comment by visiky** [comment]
1、label 问题可以如下设置解决
```ts
label: {
    offsetY: 8,
    layout: {
      type: 'limit-in-plot'
    }
}
```
2、active-region 交互先关掉，这个 bug 需要定位下
```ts
interactions: [{  type: 'active-region', enable: false  }]
```

**Comment by visiky** [comment]
版本升级到 > 2.3.25，即可解决
