### ISSUE TITLE
这里是不是应该写 G2Plot

### ISSUE THREAD

**Issue by afc163** [antvis/g2plot#245]
<img width="624" alt="image" src="https://user-images.githubusercontent.com/507615/68988939-6adb2300-087a-11ea-953d-3a1c7118455d.png">

**Comment by paleface001** [comment]
之前就大小写问题讨论过，部分人支持小写，部分人为了AntV的整体效果支持首字母大写。

**Comment by afc163** [comment]
主要是 g2 是写作 G2

**Comment by hustcc** [comment]
![image](https://user-images.githubusercontent.com/7856674/69298845-f9b8b880-0c49-11ea-822b-ee6b4d47c5ec.png)

可能要都改成 g2plot，看看 title 是否要改？ @paleface001

**Comment by afc163** [comment]
写 `G2Plot`，和 G2 保持一致。
