### ISSUE TITLE
折线图出现首尾连接问题

### ISSUE THREAD

**Issue by potatozerg** [antvis/G2Plot#2454]
* **G2Plot Version**: 2.3.16
* **Mini Showcase(like screenshots)**:  
![image](https://user-images.githubusercontent.com/3282773/112201847-102ca680-8be7-11eb-9699-56d566c3f268.png)

Same problem for G2: https://github.com/antvis/G2/issues/3255

**Comment by potatozerg** [comment]
Data:
`const data = [
    {
        "name": 100,
        "_value_AGG": -0.58
    },
    {
        "name": 99,
        "_value_AGG": 0.22
    },
    {
        "name": 98,
        "_value_AGG": 0.16
    },
    {
        "name": 97,
        "_value_AGG": 0.16
    },
    {
        "name": 96,
        "_value_AGG": -0.68
    },
    {
        "name": 95,
        "_value_AGG": 1.27
    },
    {
        "name": 94,
        "_value_AGG": 0.35
    },
    {
        "name": 93,
        "_value_AGG": 1.22
    },
    {
        "name": 92,
        "_value_AGG": -0.02
    },
    {
        "name": 91,
        "_value_AGG": -1.8
    },
    {
        "name": 90,
        "_value_AGG": 0.8
    },
    {
        "name": 89,
        "_value_AGG": -0.47
    },
    {
        "name": 88,
        "_value_AGG": 0.85
    },
    {
        "name": 87,
        "_value_AGG": -0.85
    },
    {
        "name": 86,
        "_value_AGG": -0.23
    },
    {
        "name": 85,
        "_value_AGG": 0.05
    },
    {
        "name": 84,
        "_value_AGG": -0.12
    },
    {
        "name": 83,
        "_value_AGG": 0.21
    },
    {
        "name": 82,
        "_value_AGG": -0.68
    },
    {
        "name": 81,
        "_value_AGG": -2.02
    },
    {
        "name": 80,
        "_value_AGG": 0.07
    },
    {
        "name": 79,
        "_value_AGG": -0.12
    },
    {
        "name": 78,
        "_value_AGG": -1.02
    },
    {
        "name": 77,
        "_value_AGG": -0.71
    },
    {
        "name": 76,
        "_value_AGG": 1.49
    },
    {
        "name": 75,
        "_value_AGG": -0.05
    },
    {
        "name": 74,
        "_value_AGG": -0.77
    },
    {
        "name": 73,
        "_value_AGG": -0.89
    },
    {
        "name": 72,
        "_value_AGG": 1.08
    },
    {
        "name": 71,
        "_value_AGG": 0.01
    },
    {
        "name": 70,
        "_value_AGG": -0.98
    },
    {
        "name": 69,
        "_value_AGG": -0.44
    },
    {
        "name": 68,
        "_value_AGG": 0.65
    },
    {
        "name": 67,
        "_value_AGG": 0.22
    },
    {
        "name": 66,
        "_value_AGG": 0.45
    },
    {
        "name": 65,
        "_value_AGG": 0.11
    },
    {
        "name": 64,
        "_value_AGG": -0.4
    },
    {
        "name": 63,
        "_value_AGG": 0.13
    },
    {
        "name": 62,
        "_value_AGG": 0.64
    },
    {
        "name": 61,
        "_value_AGG": 1.8
    },
    {
        "name": 60,
        "_value_AGG": -1.63
    },
    {
        "name": 59,
        "_value_AGG": -0.47
    },
    {
        "name": 58,
        "_value_AGG": -0.19
    },
    {
        "name": 57,
        "_value_AGG": 1.26
    },
    {
        "name": 56,
        "_value_AGG": -1.04
    },
    {
        "name": 55,
        "_value_AGG": -0.57
    },
    {
        "name": 54,
        "_value_AGG": 1.09
    },
    {
        "name": 53,
        "_value_AGG": 0.15
    },
    {
        "name": 52,
        "_value_AGG": -2.76
    },
    {
        "name": 51,
        "_value_AGG": 0.69
    },
    {
        "name": 50,
        "_value_AGG": -0.22
    },
    {
        "name": 49,
        "_value_AGG": 0.31
    },
    {
        "name": 48,
        "_value_AGG": 0.39
    },
    {
        "name": 47,
        "_value_AGG": -0.16
    },
    {
        "name": 46,
        "_value_AGG": 0.22
    },
    {
        "name": 45,
        "_value_AGG": -0.11
    },
    {
        "name": 44,
        "_value_AGG": 1.61
    },
    {
        "name": 43,
        "_value_AGG": -0.22
    },
    {
        "name": 42,
        "_value_AGG": -0.29
    },
    {
        "name": 41,
        "_value_AGG": 0.58
    },
    {
        "name": 40,
        "_value_AGG": -0.72
    },
    {
        "name": 39,
        "_value_AGG": -0.15
    },
    {
        "name": 38,
        "_value_AGG": 0.36
    },
    {
        "name": 37,
        "_value_AGG": 0.95
    },
    {
        "name": 36,
        "_value_AGG": 0.15
    },
    {
        "name": 35,
        "_value_AGG": 0.13
    },
    {
        "name": 34,
        "_value_AGG": -0.35
    },
    {
        "name": 33,
        "_value_AGG": -1.46
    },
    {
        "name": 32,
        "_value_AGG": -0.23
    },
    {
        "name": 31,
        "_value_AGG": -0.01
    },
    {
        "name": 30,
        "_value_AGG": -0.23
    },
    {
        "name": 29,
        "_value_AGG": 0.2
    },
    {
        "name": 28,
        "_value_AGG": 0.37
    },
    {
        "name": 27,
        "_value_AGG": 0.15
    },
    {
        "name": 26,
        "_value_AGG": -0.47
    },
    {
        "name": 25,
        "_value_AGG": -0.29
    },
    {
        "name": 24,
        "_value_AGG": 0.03
    },
    {
        "name": 23,
        "_value_AGG": -0.89
    },
    {
        "name": 22,
        "_value_AGG": -1.11
    },
    {
        "name": 21,
        "_value_AGG": 1.35
    },
    {
        "name": 20,
        "_value_AGG": 0.48
    },
    {
        "name": 19,
        "_value_AGG": -3
    },
    {
        "name": 18,
        "_value_AGG": 0.02
    },
    {
        "name": 17,
        "_value_AGG": 1.92
    },
    {
        "name": 16,
        "_value_AGG": 2.05
    },
    {
        "name": 15,
        "_value_AGG": -0.58
    },
    {
        "name": 14,
        "_value_AGG": -0.43
    },
    {
        "name": 13,
        "_value_AGG": -0.83
    },
    {
        "name": 12,
        "_value_AGG": -0.13
    },
    {
        "name": 11,
        "_value_AGG": 0.35
    },
    {
        "name": 10,
        "_value_AGG": 0.07
    },
    {
        "name": 9,
        "_value_AGG": 0.26
    },
    {
        "name": 8,
        "_value_AGG": 1.93
    },
    {
        "name": 7,
        "_value_AGG": 1.3
    },
    {
        "name": 6,
        "_value_AGG": 2.14
    },
    {
        "name": 5,
        "_value_AGG": -1.53
    },
    {
        "name": 4,
        "_value_AGG": 1.54
    },
    {
        "name": 3,
        "_value_AGG": -0.33
    },
    {
        "name": 2,
        "_value_AGG": 0.15
    },
    {
        "name": 1,
        "_value_AGG": -0.62
    }
]`

**Comment by potatozerg** [comment]
Another data here. G2 works, but not G2Plot.
![image](https://user-images.githubusercontent.com/3282773/112204751-69e2a000-8bea-11eb-8b99-d36b1d6178e7.png)

`[
    {
        "hp": 255,
        "sp_def_AGG": 135
    },
    {
        "hp": 250,
        "sp_def_AGG": 105
    },
    {
        "hp": 190,
        "sp_def_AGG": 58
    },
    {
        "hp": 170,
        "sp_def_AGG": 45
    },
    {
        "hp": 165,
        "sp_def_AGG": 45
    },
    {
        "hp": 160,
        "sp_def_AGG": 110
    },
    {
        "hp": 150,
        "sp_def_AGG": 219
    },
    {
        "hp": 144,
        "sp_def_AGG": 60
    },
    {
        "hp": 140,
        "sp_def_AGG": 50
    },
    {
        "hp": 135,
        "sp_def_AGG": 85
    },
    {
        "hp": 130,
        "sp_def_AGG": 225
    },
    {
        "hp": 126,
        "sp_def_AGG": 196
    },
    {
        "hp": 125,
        "sp_def_AGG": 166
    },
    {
        "hp": 123,
        "sp_def_AGG": 173
    },
    {
        "hp": 120,
        "sp_def_AGG": 335
    },
    {
        "hp": 116,
        "sp_def_AGG": 95
    },
    {
        "hp": 115,
        "sp_def_AGG": 155
    },
    {
        "hp": 114,
        "sp_def_AGG": 80
    },
    {
        "hp": 111,
        "sp_def_AGG": 82
    },
    {
        "hp": 110,
        "sp_def_AGG": 736
    },
    {
        "hp": 109,
        "sp_def_AGG": 99
    },
    {
        "hp": 108,
        "sp_def_AGG": 252
    },
    {
        "hp": 106,
        "sp_def_AGG": 398
    },
    {
        "hp": 105,
        "sp_def_AGG": 510
    },
    {
        "hp": 104,
        "sp_def_AGG": 73
    },
    {
        "hp": 103,
        "sp_def_AGG": 147
    },
    {
        "hp": 101,
        "sp_def_AGG": 89
    },
    {
        "hp": 100,
        "sp_def_AGG": 2379
    },
    {
        "hp": 99,
        "sp_def_AGG": 87
    },
    {
        "hp": 97,
        "sp_def_AGG": 50
    },
    {
        "hp": 95,
        "sp_def_AGG": 1610
    },
    {
        "hp": 92,
        "sp_def_AGG": 90
    },
    {
        "hp": 91,
        "sp_def_AGG": 587
    },
    {
        "hp": 90,
        "sp_def_AGG": 1979
    },
    {
        "hp": 89,
        "sp_def_AGG": 160
    },
    {
        "hp": 88,
        "sp_def_AGG": 75
    },
    {
        "hp": 86,
        "sp_def_AGG": 304
    },
    {
        "hp": 85,
        "sp_def_AGG": 1438
    },
    {
        "hp": 84,
        "sp_def_AGG": 144
    },
    {
        "hp": 83,
        "sp_def_AGG": 135
    },
    {
        "hp": 82,
        "sp_def_AGG": 134
    },
    {
        "hp": 81,
        "sp_def_AGG": 75
    },
    {
        "hp": 80,
        "sp_def_AGG": 3001
    },
    {
        "hp": 79,
        "sp_def_AGG": 325
    },
    {
        "hp": 78,
        "sp_def_AGG": 582
    },
    {
        "hp": 77,
        "sp_def_AGG": 204
    },
    {
        "hp": 76,
        "sp_def_AGG": 300
    },
    {
        "hp": 75,
        "sp_def_AGG": 2964
    },
    {
        "hp": 74,
        "sp_def_AGG": 334
    },
    {
        "hp": 73,
        "sp_def_AGG": 285
    },
    {
        "hp": 72,
        "sp_def_AGG": 337
    },
    {
        "hp": 71,
        "sp_def_AGG": 338
    },
    {
        "hp": 70,
        "sp_def_AGG": 3435
    },
    {
        "hp": 69,
        "sp_def_AGG": 141
    },
    {
        "hp": 68,
        "sp_def_AGG": 440
    },
    {
        "hp": 67,
        "sp_def_AGG": 316
    },
    {
        "hp": 66,
        "sp_def_AGG": 194
    },
    {
        "hp": 65,
        "sp_def_AGG": 3128
    },
    {
        "hp": 64,
        "sp_def_AGG": 264
    },
    {
        "hp": 63,
        "sp_def_AGG": 146
    },
    {
        "hp": 62,
        "sp_def_AGG": 409
    },
    {
        "hp": 61,
        "sp_def_AGG": 233
    },
    {
        "hp": 60,
        "sp_def_AGG": 4647
    },
    {
        "hp": 59,
        "sp_def_AGG": 289
    },
    {
        "hp": 58,
        "sp_def_AGG": 373
    },
    {
        "hp": 57,
        "sp_def_AGG": 173
    },
    {
        "hp": 56,
        "sp_def_AGG": 45
    },
    {
        "hp": 55,
        "sp_def_AGG": 2009
    },
    {
        "hp": 54,
        "sp_def_AGG": 199
    },
    {
        "hp": 53,
        "sp_def_AGG": 102
    },
    {
        "hp": 52,
        "sp_def_AGG": 112
    },
    {
        "hp": 51,
        "sp_def_AGG": 75
    },
    {
        "hp": 50,
        "sp_def_AGG": 2988
    },
    {
        "hp": 49,
        "sp_def_AGG": 153
    },
    {
        "hp": 48,
        "sp_def_AGG": 136
    },
    {
        "hp": 46,
        "sp_def_AGG": 80
    },
    {
        "hp": 45,
        "sp_def_AGG": 1973
    },
    {
        "hp": 44,
        "sp_def_AGG": 349
    },
    {
        "hp": 43,
        "sp_def_AGG": 160
    },
    {
        "hp": 42,
        "sp_def_AGG": 56
    },
    {
        "hp": 41,
        "sp_def_AGG": 131
    },
    {
        "hp": 40,
        "sp_def_AGG": 1992
    },
    {
        "hp": 39,
        "sp_def_AGG": 100
    },
    {
        "hp": 38,
        "sp_def_AGG": 287
    },
    {
        "hp": 37,
        "sp_def_AGG": 41
    },
    {
        "hp": 36,
        "sp_def_AGG": 60
    },
    {
        "hp": 35,
        "sp_def_AGG": 724
    },
    {
        "hp": 31,
        "sp_def_AGG": 30
    },
    {
        "hp": 30,
        "sp_def_AGG": 589
    },
    {
        "hp": 28,
        "sp_def_AGG": 35
    },
    {
        "hp": 25,
        "sp_def_AGG": 110
    },
    {
        "hp": 20,
        "sp_def_AGG": 520
    },
    {
        "hp": 10,
        "sp_def_AGG": 45
    },
    {
        "hp": 1,
        "sp_def_AGG": 30
    }
]`

`const line = new Line('container', {
  data,
  xField: 'hp',
  yField: 'sp_def_AGG',
});

line.render();
`

**Comment by potatozerg** [comment]
I think the type of xField can be Number in G2, but has to be String in G2Plot.

**Comment by visiky** [comment]
Make sure the x values is sorted

**Comment by potatozerg** [comment]
@visiky It's sorted in descending order. "hp" is the x value.

**Comment by visiky** [comment]
config `meta` as follow, because type of xField meta is default set tot `cat` 👉 [source file](https://github.com/antvis/g2plot/blob/7d0a5301ae1ac5994fcb926080e03422d36d5d89/src/plots/line/adaptor.ts#L66)
```ts
meta: {
    hp: {
      type: undefined
    }
  },
```

**Comment by zhangxiumei99** [comment]
I encountered the same problem, did you solve it? How to solve it。please help me

**Comment by potatozerg** [comment]
@zhangxiumei99 What's the data type? I kinda forgot how I solved it. Try to convert it to String.
Have you tried visiky's solution?

**Comment by zhangxiumei99** [comment]
折线图，多条数据线，动态更新会出现首尾连接，折线变乱变多，按照上面的解决方法 没能解决我的问题

**Comment by JLibyvali** [comment]
@zhangxiumei99 
检查动态更新后赋值给 `data` 字段的数组：
```
Line {
  data: sortexX_Array,
}
```
内部所有元素都应该按照 x 字段值进行排序, [例如](https://g2plot.antv.antgroup.com/examples/line/multiple/#line-large-data)
data内所有元素都按照 x 值进行了排序
