### ISSUE TITLE
tooltip中的图例没有对齐 

### ISSUE THREAD

**Issue by potatozerg** [antvis/G2Plot#2463]
same issue as https://github.com/antvis/G2Plot/issues/926

I really wonder why https://g2plot.antv.vision/zh/examples/area/stacked#basic is working well.
This is what I got using exact same data on G2Plot:
![image](https://user-images.githubusercontent.com/3282773/112544828-de097900-8d8d-11eb-91da-7c189a92e304.png)
This is exact same code on my page:
![image](https://user-images.githubusercontent.com/3282773/112544944-01ccbf00-8d8e-11eb-8f85-23e0fc07f2cc.png)

This is why I tried to set domStyle of tooltip to:
`domStyles: { 'g2-tooltip-marker': { float: 'left' }, 'g2-tooltip-name': { float: 'left' } }`
But when the number has different lengths, the colon's position can't be set.
As you can see, 103 is shorter than 69.97, so the colon's positioning is not working well.
![image](https://user-images.githubusercontent.com/3282773/112545229-5708d080-8d8e-11eb-9380-827853b0975a.png)

**Comment by potatozerg** [comment]
Fixed:
 `domStyles: {
            'g2-tooltip': { 'text-align': 'left' }
          }`

**Comment by potatozerg** [comment]
@visiky Can you tell me why it's different on the G2Plot website and my page? Is there any hidden setting for the website?

**Comment by visiky** [comment]
maybe it's affected by other styles configured in your page, which the priority is higher than tooltip's style.
