### ISSUE TITLE
分组柱状图无法按xField,yField的值设置颜色

### ISSUE THREAD

**Issue by haue** [antvis/G2Plot#2466]
版本：2.3.17

分组柱状图的color函数里只能获取到seriesField的值，无法获取到xField,yField对应的值，进而无法按xField,yField的值设置颜色。

**Comment by visiky** [comment]
添加一下 rawFields string[] 类型，看下回调增加参数了没

**Comment by haue** [comment]
@visiky 问题解决了，没有看到过rawFields的介绍。文档需要完善呀
