### ISSUE TITLE
antd-vue-pro引入后不显示图表

### ISSUE THREAD

**Issue by yuanyayi** [antvis/G2Plot#2467]
* **G2Plot Version**: 2.3.17
* **Platform**: mac
* **Mini Showcase(like screenshots)**:

* 使用antd-vue-pro框架，直接升级后出现的错误：
![image](https://user-images.githubusercontent.com/19421507/112605230-09559c00-8e52-11eb-863d-1495252cd2f2.png)
![image](https://user-images.githubusercontent.com/19421507/112605201-0064ca80-8e52-11eb-8335-2f8b94c3a590.png)

我看到有人反应是环境问题了，但确实没思路，请大神帮帮忙吧谢谢！

附上我的vue.config.js文件：
```
const path = require('path')
const webpack = require('webpack')
const createThemeColorReplacerPlugin = require('./config/plugin.config')

function resolve (dir) {
  return path.join(__dirname, dir)
}

// vue.config.js
const vueConfig = {
  configureWebpack: {
    plugins: [
      // Ignore all locale files of moment.js
      new webpack.IgnorePlugin(/^\.\/locale$/, /moment$/)
    ]
  },

  chainWebpack: (config) => {
    config.resolve.alias
      .set('@$', resolve('src'))

    const svgRule = config.module.rule('svg')
    svgRule.uses.clear()
    svgRule
      .oneOf('inline')
      .resourceQuery(/inline/)
      .use('vue-svg-icon-loader')
      .loader('vue-svg-icon-loader')
      .end()
      .end()
      .oneOf('external')
      .use('file-loader')
      .loader('file-loader')
      .options({
        name: 'assets/[name].[hash:8].[ext]'
      })
  },

  css: {
    loaderOptions: {
      less: {
        modifyVars: {
          // less vars，customize ant design theme

          // 'primary-color': '#F5222D',
          // 'link-color': '#F5222D',
          // 'border-radius-base': '4px'
        },
        javascriptEnabled: true
      }
    }
  },

  devServer: {
    // development server port 8000
    port: 8000,
    // If you want to turn on the proxy, please remove the mockjs /src/main.jsL11
    proxy: {
      '/api': {
        target: '********',
        ws: false,
        changeOrigin: true,
        pathRewrite: {
          '^/api': ''
        }
      }
    }
  },

  // disable source map in production
  productionSourceMap: false,
  lintOnSave: undefined,
  // babel-loader no-ignore node_modules/*
  transpileDependencies: []
}

// preview.pro.loacg.com only do not use in your production;
if (process.env.NODE_ENV !== 'production' || process.env.VUE_APP_PREVIEW === 'true') {
  // add `ThemeColorReplacer` plugin to webpack plugins
  vueConfig.configureWebpack.plugins.push(createThemeColorReplacerPlugin())
}

module.exports = vueConfig

```

**Comment by visiky** [comment]
删除依赖锁 重装依赖；再不行的话 npm ls @antv/util 看下版本号

**Comment by xinde** [comment]
┬ @antv/g2plot@2.3.17
  └─┬ @antv/g2@4.1.13
    ├─┬ @antv/adjust@0.2.3
    │ └── @antv/util@2.0.13  deduped
    ├─┬ @antv/attr@0.3.2
    │ └── @antv/util@2.0.13  deduped
    ├─┬ @antv/color-util@2.0.6
    │ └── @antv/util@2.0.13  deduped
    ├─┬ @antv/component@0.8.10
    │ └── @antv/util@2.0.13  deduped
    ├─┬ @antv/coord@0.3.1
    │ └── @antv/util@2.0.13  deduped
    ├─┬ @antv/g-base@0.5.6
    │ ├─┬ @antv/g-math@0.1.7
    │ │ └── @antv/util@2.0.13  deduped
    │ └── @antv/util@2.0.13  deduped
    ├─┬ @antv/g-canvas@0.5.7
    │ └── @antv/util@2.0.13  deduped
    ├─┬ @antv/g-svg@0.5.6
    │ └── @antv/util@2.0.13  deduped
    ├─┬ @antv/matrix-util@3.1.0-beta.2
    │ └── @antv/util@2.0.13  deduped
    ├─┬ @antv/path-util@2.0.9
    │ └── @antv/util@2.0.13  deduped
    ├─┬ @antv/scale@0.3.9
    │ └── @antv/util@2.0.13  deduped
    └── @antv/util@2.0.13 

也是有canvas，但是不显示图表。最简单的引入例子，vue3+vite

**Comment by visiky** [comment]
升级后如何了？
