### ISSUE TITLE
🌹玫瑰图🌹，轴向轴的轴标签，怎么让它默认显示在图形上方哈。

### ISSUE THREAD

**Issue by ntscshen** [antvis/G2Plot#2478]
![image](https://user-images.githubusercontent.com/21041458/113130261-7308e800-924e-11eb-93cd-061164c5eecc.png)

请教个问题哇[抱大腿]，玫瑰图中，轴向轴的轴标签，怎么让它默认显示在图形上方哈。
测试地址：https://antv-g2plot.gitee.io/zh/examples/rose/grouped#basic
测试数据
```js
  yAxis: {
    min: 0,
    tickLine: {
      length: 20,
      style: {stroke: "#ff0000", lineWidth: 6}
    },
    label: {
      style: {
        fill: "blue",
        fontSize: 32,
        fontWeight: "bold"
      }
    }
  }
```

**Comment by visiky** [comment]
```ts
yAxis: {
    top: true
}
```

文档补全中
