### ISSUE TITLE
2.3.17版本treemap-drill-down-action.js中 import { ext } from '@antv/matrix-util'; 编译报错

### ISSUE THREAD

**Issue by chenzio** [antvis/G2Plot#2486]
* **G2Plot Version**: 2.3.17
* **Platform**: PC
* **Mini Showcase(like screenshots)**:
* 
![image](https://user-images.githubusercontent.com/24283515/113370868-870c3100-9397-11eb-82a3-d3d3cd04bd49.png)

* **CodePen Link**:

**Comment by visiky** [comment]
@liuzhenying package.json 中没有引入这个依赖

**Comment by visiky** [comment]
npm ls @antv/matrix-util 看下版本号是不是 3.0.x，不是的话，更新到 3.1.x

**Comment by chenzio** [comment]
![image](https://user-images.githubusercontent.com/24283515/114328992-d6f5af80-9b70-11eb-9ed5-49e0925b671c.png)
@antv/matrix-util 的版本是3.1.0-beta.2
