### ISSUE TITLE
How to make sunburst reflect render deep reqursive struncture?

### ISSUE THREAD

**Issue by R31N3** [antvis/G2Plot#2493]
* **G2Plot Version**: v2
* **Platform**: Linux

How to render sunburst reflect with deep structures with many parent-child links? 
![image](https://user-images.githubusercontent.com/34096555/114021758-b8926a00-9879-11eb-836e-52763aedce7e.png)

I found out that hierarchyConfig may help my and found examples in D3-Hierarchy references, like what I actually want.
There's the Link:
https://observablehq.com/@d3/zoomable-sunburst?collection=@d3/d3-hierarchy 
https://observablehq.com/@d3/sunburst?collection=@d3/d3-hierarchy (zoomable feature is not necessary)

Here's the Input Data Example:
https://gist.github.com/R31N3/ec46aeb62f94bf23e1a43ddc6e31639e
https://gist.githubusercontent.com/R31N3/ec46aeb62f94bf23e1a43ddc6e31639e/raw/b620ce9de8bef3e02445b08eff7eb11fc163ae6c/test.json

**Comment by visiky** [comment]
Try this example: http://localhost:8080/en/examples/more-plots/sunburst#basic

```ts
import { Sunburst } from '@antv/g2plot';

fetch('https://gw.alipayobjects.com/os/antfincdn/XfLX8sX9z%26/sunburst.json')
  .then((data) => data.json())
  .then((data) => {
    const plot = new Sunburst('container', {
      data: { children: data },
      innerRadius: 0.3,
      interactions: [{ type: 'element-active' }],
    });
    plot.render();
  });
```

💡 Make sure the value of the parent node (which has children nodes),  to be undefined. 

😊 And we'll add a new configuration `ignoreParentValue` in the next version. https://github.com/antvis/G2Plot/pull/2637
