### ISSUE TITLE
hi， 地图图表什么时候支持呢？

### ISSUE THREAD

**Issue by yilo** [antvis/G2Plot#2495]
hi， 地图图表什么时候支持呢？和 G2一样的，另外什么时候在 react 版本会支持呢？

**Comment by hustcc** [comment]
@yilo 可以描述一下你的需求。

我们会在 Charts 中使用 L7 去做更加专业的地图，而不是使用 G2 做地图。

**Comment by yilo** [comment]
嗯， 主要是地图的下钻 上卷这些， 看看什么时候回支持呢。 貌似半年前就有计划的， 呵呵

**Comment by lxfu1** [comment]
Using L7 first ? https://l7.antv.vision/en/examples/gallery#category-DrillDown

**Comment by visiky** [comment]
G2Plot 不直接提供了，后续关注 ant-design-chart 上新 react 版本的地图哈

**Comment by zhanggaoke** [comment]
L7用的是webgl，在某些环境下webgl是不开启的（费性能）导致无法显示，G2本来就是有geojson地图的啊，为什么不实现？？
