### ISSUE TITLE
对称条形图xAxis的line样式只生效了左侧

### ISSUE THREAD

**Issue by frequdem** [antvis/G2Plot#2502]
* **G2Plot Version**: 2.3.17
* **Platform**: macOS 11.2.1  chrome 89.0.4389.114
* **Mini Showcase(like screenshots)**: 
![image](https://user-images.githubusercontent.com/17846621/114359440-9153d980-9ba6-11eb-8d76-b3c734a43f70.png)

**Comment by hustcc** [comment]
对称条形图的 xAxis，只显示了其中一个条形图的，另外一个隐藏，他们共用一个 xAxis，不过这个地方的逻辑确实有问题，应该只是隐藏 xAxis.label。
