### ISSUE TITLE
散点图 刷选交互 刷选后的个别点会显示在轴上，影响视觉效果

### ISSUE THREAD

**Issue by Lemon-XXL** [antvis/G2Plot#2507]
* **G2Plot Version**: v2
* **Platform**: Windows10 Chrome 
* **Mini Showcase(like screenshots)**:
![散点图2](https://user-images.githubusercontent.com/52128964/114523806-3938d800-9c77-11eb-8a25-dd5057154602.gif)
<img width="1025" alt="1618303477(1)" src="https://user-images.githubusercontent.com/52128964/114524349-b6fce380-9c77-11eb-8d19-735143771f33.png">

* **Code**: `scatterPlot.chart.interaction('brush')`
* **Link**: https://g2plot.antv.vision/zh/examples/scatter/scatter#color-mapping

现象：散点图刷选之后，如果刷选范围内只有一个点，会显示在坐标轴上，视觉效果不是很好；刷选多个点时，个别情况下，会有多个点都出现在轴上

预期：如果只有一个点，居中显示；如果有多个点，坐标轴范围最好进行扩展，尽量减少点出现在轴上或边缘的情况

**Comment by visiky** [comment]
在 G2 层，没有对单一数据进行默认优化好看：https://codesandbox.io/s/sandiantu-23gh4

这个问题，我们会在后续 G2Plot 层解决
