### ISSUE TITLE
g2plot 2.x 玉珏图 动画问题：当加 padding配置 和 圆角配置时 会出现

### ISSUE THREAD

**Issue by rabbit-tian** [antvis/G2Plot#2510]
* **G2Plot Version**: g2plot 2.x
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**: https://codesandbox.io/s/bold-dawn-4mc0j?file=/index.js

![image](https://user-images.githubusercontent.com/26690191/115512583-b89c5c00-a2b4-11eb-9c1c-9b6ae269b941.png)

**Comment by rabbit-tian** [comment]
@visiky 麻烦看下哈

**Comment by visiky** [comment]
复现链接错了哈
