### ISSUE TITLE
饼图和环图修改了 padding，有分页的图例会被截断

### ISSUE THREAD

**Issue by jasonjcpeng** [antvis/G2Plot#2511]
这个是复合逻辑的，需要修改 legend 配置。

```ts
maxItemWidth: number; // 图例项的最大宽度，默认是 200
itemWidth: number;  // 图例项的宽度
```

_Originally posted by @hustcc in https://github.com/antvis/G2Plot/issues/2039#issuecomment-748718713_

版本2.3.18，legend设置
maxItemWidth: number; // 图例项的最大宽度，默认是 200 itemWidth: number; // 图例项的宽度
后，有分页的legend，被截断问题仍未解决。
![image](https://user-images.githubusercontent.com/13363216/115519636-f6e94980-a2bb-11eb-9bc4-f5864d38c9cc.png)
![image](https://user-images.githubusercontent.com/13363216/115519681-0072b180-a2bc-11eb-8cc1-bcf097117c32.png)

**Comment by visiky** [comment]
新增 `maxWidthRatio` 参数，具体见：xxx
```ts
  legend: {
    maxWidthRatio: null,
  },
```
