### ISSUE TITLE
折线图数据中没有 04-17，但是坐标轴刻度多了一条

### ISSUE THREAD

**Issue by visiky** [antvis/G2Plot#2512]
* **G2Plot Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**: https://riddle.alibaba-inc.com/riddles/68b7b9fa

![image](https://user-images.githubusercontent.com/15646325/115538464-7e3fb880-a2ce-11eb-8bdf-3930ed100236.png)

**Comment by visiky** [comment]
1. 临时方案：
```ts
meta: {
   date: { type: 'cat' }
}
```

2. 完整解决，需要到 g2 层处理

**Comment by pearmini** [comment]
Try to set nice option to false for xAxis.
