### ISSUE TITLE
堆叠面积图，面积中的部分折线穿过了部分面积

### ISSUE THREAD

**Issue by ntscshen** [antvis/G2Plot#2515]
* **G2Plot Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**: https://codesandbox.io/s/charming-haslett-ykque?file=/index.js:0-12889

![image](https://user-images.githubusercontent.com/21041458/115988023-5318da00-a5ea-11eb-91c1-38c56297530d.png)

**Comment by ntscshen** [comment]
这个一看，就是，x轴为1858时候，只村子Liquid fuel这一种类型导致的。边界处理条件。

**Comment by hustcc** [comment]
感觉是数据排序上的问题。

**Comment by visiky** [comment]
![image](https://user-images.githubusercontent.com/15646325/118355033-7fe45f80-b5a0-11eb-8c08-478a8422ebaf.png)

![image](https://user-images.githubusercontent.com/15646325/118355041-8a9ef480-b5a0-11eb-92ce-8f158852fbb3.png)

**Comment by visiky** [comment]
> 感觉是数据排序上的问题。

你啥想法 💡
