### ISSUE TITLE
【和弦图】若干诉求

### ISSUE THREAD

**Issue by visiky** [antvis/G2Plot#2525]
- [ ] 【交互】节点元素激活，联动边元素
- [x] 【组件】节点没有 Tooltip 且边元素和节点元素有重叠，导致事件或者交互会出现触发异常
- [x] 【颜色】和弦图暂时不提供 seriesField 映射
- [x] 【动画】支持 'wave-in'，'zoom-in'，"scale-in-x"，'scale-in-y' 等动画效果
- [x] 【状态】修复 getState, state 不生效

**Comment by rabbit-tian** [comment]
动画效果：目前测试，'wave-in'，'zoom-in'，"scale-in-x"，'scale-in-y' 等动画效果都不支持

**Comment by rabbit-tian** [comment]
1. color，seriesField 是不支持的
2. state不支持
