### ISSUE TITLE
柱状图的onColumnDblClick没有用

### ISSUE THREAD

**Issue by darknoll** [antvis/G2Plot#2526]
onColumnClick可以，onColumnDblClick点击毫无反应

**Comment by visiky** [comment]
g2plot 1.x 版本不再维护，可以考虑按照升级指南 升级到2.x版本

**Comment by darknoll** [comment]
> g2plot 1.x 版本不再维护，可以考虑按照升级指南 升级到2.x版本

升级的话代价太大了啊，能不能指点下在源码哪个地方，我手动去改一下，先凑合用着

**Comment by visiky** [comment]
看下这个文件：https://github.com/antvis/g2plot/blob/b4a8d47502df40f80f3c257b362aeb869a94382e/src/plots/column/event.ts
具体不太了解了
