### ISSUE TITLE
折线图获取数据点

### ISSUE THREAD

**Issue by chaoqunzhan** [antvis/G2Plot#2530]
* **G2Plot Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

目前的折线图事件是不是只能获取所有数据？有什么办法可以获取点击的数据点的数据吗？

**Comment by wangQingAi** [comment]
`point: {
      visible: true,
 },
 onReady: (plot)=>{
        plot.on('point:click',(evt)=>{
              const data = evt?.data?.data || {};
     })
},`

**Comment by visiky** [comment]
纠正一个小点，point 没有 visible 属性。
解决方案：开启折线图上的数据点，监听 point 点击事件
```ts
const plot = new Line('contaienr', {
   data: [],
   // ....
   point: {  }, 
}

plot.on('point:click',(evt)=>{ const data = evt?.data?.data || {}; }) },
```
