### ISSUE TITLE
🥰 [需求] 3d柱状图如何实现

### ISSUE THREAD

**Issue by swimfish09** [antvis/G2Plot#2536]
类似这种的
https://www.highcharts.com.cn/demo/highcharts/3d-column-interactive
![image](https://user-images.githubusercontent.com/3916975/117520496-087c6200-afdb-11eb-8ee3-f3384139ba40.png)

**Comment by hustcc** [comment]
暂时无法实现。伪 3D 的二维图对于数据分析来说几乎没有任何意义，仅仅是为了美观上做伪 3D 也不是很合适。如果需要做一些自定义图来实现。

**Comment by swimfish09** [comment]
伪 3D 的二维图对于数据分析来说几乎没有任何意义，要是客户也这样想就好了
