### ISSUE TITLE
柱状图对显示x轴为数字类型的数据的缺陷

### ISSUE THREAD

**Issue by LQING27** [antvis/G2Plot#2538]
* **G2Plot Version**: 2.3.19
* **Platform**:
* **Mini Showcase(like screenshots)**:
* 
![image](https://user-images.githubusercontent.com/20120874/117673490-6b3d4b80-b1dd-11eb-8e06-41a8799a9e35.png)

* **CodePen Link**:https://g2plot.antv.vision/zh/examples/column/basic#basic

代码如下，柱状图id为2的数据为什么会是堆积柱状图的样式，而id为2的是没有柱状图的？如果将id=1改成其他数字，显示则是正常。

import { Column } from '@antv/g2plot';

const data = [
    {
        "日期": "2021-05-03 15:07:12",
        "id":1,
        "到课率": 20,
        "就餐率": 20
    },
    {
        "日期": "2021-05-05 21:07:04",
        "id": 2,
        "到课率": 19,
        "就餐率": 10,
    }
]

const columnPlot = new Column('container', {
  data,
  xField: 'id',
  yField: '就餐率',
  label: {
    // 可手动配置 label 数据标签位置
    position: 'middle', // 'top', 'bottom', 'middle',
    // 配置样式
    style: {
      fill: '#FFFFFF',
      opacity: 0.6,
    },
  },
  xAxis: {
    label: {
      autoHide: true,
      autoRotate: false,
    },
  },
  meta: {
    type: {
      alias: '类别',
    },
    sales: {
      alias: '销售额',
    },
  },
});

columnPlot.render();

**Comment by visiky** [comment]
同 #2620 一起解决
