### ISSUE TITLE
Is it possible to make the tooltip crosshair not snap to the closest data point?

### ISSUE THREAD

**Issue by sleighsoft** [antvis/G2Plot#2540]
* **G2Plot Version**: Current

Source: https://g2plot.antv.vision/en/docs/api/components/tooltip

Currently:
![image](https://user-images.githubusercontent.com/9438971/117961725-bb6ff700-b31e-11eb-803b-eb63fb890a75.png)

What I would like:
![image](https://user-images.githubusercontent.com/9438971/117961998-07bb3700-b31f-11eb-8e3b-434f2943606d.png)

**Comment by sleighsoft** [comment]
Ah found it! Great library: https://g2plot.antv.vision/en/docs/api/components/tooltip#crosshairs!

**Comment by sleighsoft** [comment]
However, what I didn't find is an option to make the marker follow the crosshair as well. It will always stay snapped to the nearest data point. Is that possible to achieve?

It currently looks like this:
![image](https://user-images.githubusercontent.com/9438971/117968926-08f06200-b327-11eb-9aab-8b374138edcb.png)

**Comment by visiky** [comment]
> It will always stay snapped to the nearest data point. Is that possible to achieve

1. Could you provide an online demo which can reproduce the situation like as follow:
![image](https://user-images.githubusercontent.com/15646325/118061680-f8dc8f00-b3c7-11eb-8dd3-134080cc9903.png)

2. You can listen for click events of plot and make it's possible to add an lineannotation to the exact position.

The pseudo code is as follows:

```ts
const g2Chart = linePlot.chart;
linePlot.on('plot:click', (evt) => {
    // get x, y
   g2Chart.annnotation().line({
       // ....
   });
  
  // update render
  g2Chart.render(true);
})
```
Related API:
- [Plot events](https://g2plot.antv.vision/en/docs/api/options/events#event-listener)
- [Annoations](https://g2plot.antv.vision/en/docs/api/components/annotations#configurations%EF%BC%88annotationcfg%EF%BC%89)

**Comment by sleighsoft** [comment]
Thank you very much @visiky for getting back to me so quickly.

I believe your code already gets me very close.
My question would be how do I actually get `x` and `y` and how can I use those specifically to add a line stretching across vertically? I do not see an option to pass those into `line()`

```javascript
line.on('plot:click', ({view, gEvent, data, type}) => {
  console.log('view', view);
  console.log('data', data);
  console.log('gEvent', gEvent);
  console.log('type', type);
  line.chart.annotation().line({
    
  });
});
```
This is the output of `gEvent`. 
<img width="1443" alt="image" src="https://user-images.githubusercontent.com/9438971/118111165-9beed200-b3e3-11eb-8a9e-b578c7f3300b.png">


Also, when clicking on an annotation, how could I delete it again from the chart? I don't see a way to match the event object to any entry in `line.options.annotations`.

```javascript
line.on('annotation:click', ({view, gEvent, data, type}) => {
  gEvent.stopPropagation();
  console.log('view', view);
  console.log('data', data);
  console.log('gEvent', gEvent);
  console.log('type', type);
});
```

Your help is appreciated a lot!

**Comment by sleighsoft** [comment]
I think the issue with the marker is that the x-axis is basically a "category" axis with discrete categories `["1", "2", "3", ...]` and therefore no "intermediate" values exist.

**Comment by sleighsoft** [comment]
Regarding the coordinate transformation I think I have it solved now, albeit there was no real documentation for that
```javascript
line.on('plot:click', ({view, gEvent, data, type}) => {
  // Datum to pixel
  var xScale = view.getXScale();
  var x = xScale.scale('7');
  var yScale = view.getYScales()[0];
  var y = yScale.scale(yScale['max']);
  console.log([x, y]);
  var inpixel = view.getCoordinate().convert({x: x, y: y}); // in pixel
  console.log(inpixel);

  // Pixel to datum
  var click = view.getCoordinate().invert({x: gEvent.x, y: gEvent.y});
  console.log('click', click);
  var clickX = xScale.invert(click.x);
  var clickY = yScale.invert(click.y);
  console.log('clickXY', [clickX, clickY]);
});
```
