### ISSUE TITLE
g2plot 2.x 双轴图存在的问题

### ISSUE THREAD

**Issue by rabbit-tian** [antvis/G2Plot#2547]
* **G2Plot Version**: 2.3.21
* **Platform**: g2plot 2.x 
* **Mini Showcase(like screenshots)**:
* **CodePen Link**: https://codesandbox.io/s/bold-dawn-4mc0j?file=/index.js

- 部分动画效果还是不生效：只有 scale-in-y 生效，其余（zoom-in, wave-in, scale-in-x）均不生效
- 滚动轴不生效
- 提示框显示多个, 这个问题比较严重
- 不支持连续型图例

**Comment by liuzhenying** [comment]
提示框显示多个，已沟通，用户的个性化需求（点击时显示tooltip），可通过暴露的 g2 接口设置

`dualAxes.chart.interaction('tooltip', {
  start: [{ trigger: 'plot:click', action: 'tooltip:show' }],
});`

**Comment by liuzhenying** [comment]
不支持连续型图例，关联 issue https://github.com/antvis/G2Plot/issues/2476

**Comment by liuzhenying** [comment]
暂时不支持 scrollbar，之后版本会尽快支持

**Comment by visiky** [comment]
总结一下：
1. 动画问题，不是每个动画效果都可以适用的；这个等【动画专题】处理
2. 双轴图暂不支持滚动条，等【组件 - 滚动条专题】处理
3. 因为交互放在配置项进行设置的话，会保留原始的触发方式，进行一个 merge；所以有两种方式处理：
     1.  全局注册复写 tooltip 交互触发
     2. 局部复写 tooltip 交互触发，直接调用 G2 chart 实例方法 (plot.chart): `plot.chart.interaction('tooltip', { start: [{ trigger: 'plot:click', action: 'tooltip:show' }], });`
4. 不支持连续型图例 (给出具体说明)
