### ISSUE TITLE
柱状图: 在meta设置alias后, tooltip无效 

### ISSUE THREAD

**Issue by Bob0411** [antvis/G2Plot#2548]
* **G2Plot Version: 2.3.21**:
* **Platform: g2plot 2.x**:
* **Mini Showcase(like screenshots):**:

* 柱状图: 在meta设置alias后, tooltip无效 :

**Comment by visiky** [comment]
不要只描述问题，不给复现链接或者截图

**Comment by visiky** [comment]
无法复现

![image](https://user-images.githubusercontent.com/15646325/122637636-647dee80-d122-11eb-9d2a-54e87ffc3d3b.png)
