### ISSUE TITLE
桑吉图的字体颜色如何更改

### ISSUE THREAD

**Issue by Uvpcsman** [antvis/G2Plot#2554]
* **G2Plot Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:
桑吉图的字体颜色如何更改，一直没有找到相关参数

**Comment by hustcc** [comment]
暂时还不支持，下一个 PR 处理，本周内处理完。

**Comment by hustcc** [comment]
```ts
label: {
        fields: ['x', 'name'],
        callback: (x: number[], name: string) => {
          const isLast = x[1] === 1; // 最后一列靠边的节点
          return {
            style: {
              fill: '#545454', // 这里改颜色
              textAlign: isLast ? 'end' : 'start',
            },
            offsetX: isLast ? -8 : 8,
            content: name,
          };
        },
        layout: [
          {
            type: 'hide-overlap',
          },
        ],
      },
```

**Comment by Uvpcsman** [comment]
您好，我照着改了index.js文件，但未生效




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "antvis/G2Plot"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月20日(星期四) 中午1:02
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [antvis/G2Plot] 桑吉图的字体颜色如何更改 (#2554)





 label: {         fields: ['x', 'name'],         callback: (x: number[], name: string) =&gt; {           const isLast = x[1] === 1; // 最后一列靠边的节点           return {             style: {               fill: '#545454', // 这里改颜色               textAlign: isLast ? 'end' : 'start',             },             offsetX: isLast ? -8 : 8,             content: name,           };         },         layout: [           {             type: 'hide-overlap',           },         ],       },
