### ISSUE TITLE
折线柱状图 提示框显示问题

### ISSUE THREAD

**Issue by rabbit-tian** [antvis/G2Plot#2555]
* **G2Plot Version**: 2.3.17
* **Platform**: g2plot 2.x
* **Mini Showcase(like screenshots)**:
* **CodePen Link**: https://codesandbox.io/s/sharp-jackson-fqqvg?file=/index.js

当提示框加  position 属性后，提示框显示异常
不加position 后，最后一个柱子显示也有问题

**Comment by rabbit-tian** [comment]
@liuzhenying liu 麻烦看下哈

**Comment by rabbit-tian** [comment]
tooltip 使用的是 自定义 customContent，里面加的 svg

**Comment by visiky** [comment]
G2 复现 demo: https://codesandbox.io/s/tooltip-position-e4bzk

**Comment by yp0413150120** [comment]
`svg` 标签在未设置宽高参数下，默认宽 `300px`，高 `150px`
展示 `tooltip`，`svg` 图像超出 `tooltip` 容器，导致 鼠标焦点 聚焦在了 `svg` 图像上，触发了 `mouseLeave` 事件，造成 `tooltip` 闪动

建议：
1、`svg` 添加合适宽高
2、`tooltip` 容器添加 `overflow: hidden`

**Comment by visiky** [comment]
![image](https://user-images.githubusercontent.com/15646325/124262599-d1eb3f80-db64-11eb-9735-a4d07f5602ea.png)
