### ISSUE TITLE
【分类图例】marker & itemName & itemValue 支持回调设置

### ISSUE THREAD

**Issue by ntscshen** [antvis/G2Plot#2558]
> 连续图例，是否能抛出，对单独某一个图例的设置，现在只能统一设置
场景：折线图，指定某一类型的数据点样式为菱形 ，其他默认圆形。从用户角度，此时图例对应的symbol 形状应该跟着数据点和折线的线型去动态改变。这只是一个想法，统一的图例跟随线型和数据点的变更只要自定义symbol即可，但是我没办法具体的去修改其中的某一个图例

**Comment by visiky** [comment]
和连续图例什么关系？可以直接给一个截图说明吗

**Comment by ntscshen** [comment]
sorry，分类图例

**Comment by ntscshen** [comment]
求：图例的icon和name，支持Function类型

**Comment by visiky** [comment]
方案：需要对 @antv/component legend 进行扩展

**Comment by visiky** [comment]
**Checklist**

- [x] marker 支持回调
- ~~itemName、itemValue 暂时不支持~~

**Comment by ntscshen** [comment]
@visiky itemName 暂不支持回调吗
https://codesandbox.io/s/great-shadow-5smlm?file=/index.js:1237-1265
