### ISSUE TITLE
g2plot 2.x 雷达图 在 v2.3.18 及以上版本 提示框报错

### ISSUE THREAD

**Issue by rabbit-tian** [antvis/G2Plot#2559]
* **G2Plot Version**: v2.3.18 及以上版本
* **Platform**:  g2plot 2.x
* **Mini Showcase(like screenshots)**:
* **CodePen Link**: https://codesandbox.io/s/loving-kalam-4nh2l?file=/index.js

![image](https://user-images.githubusercontent.com/26690191/118613902-c67cc880-b7f1-11eb-91dc-48d7855fd92d.png)

**Comment by rabbit-tian** [comment]
@visiky 帮忙看下哈

**Comment by visiky** [comment]
- series 顾名思义：系列，接受分类型字段（文本型字段）
- 指定 seriesField 作为拆分，可以用不同的颜色来代表不同的拆分维度值（比如 seriesField 是 city，则可以展示不同的线，比如：杭州、广州等）
- 不要把数值型的作为拆分维度 seriesField

> 从实际数据分析可视化角度去看待
