### ISSUE TITLE
环图：由于容器宽度小，outer 类型的 label 显示不全，是否存在某种属性，可以令图的区域占比少一些，让label显示出来

### ISSUE THREAD

**Issue by 905868332** [antvis/G2Plot#2566]
环图：由于容器宽度小，outer 类型
的 label 显示不全，是否存在某种属性，可以令图的区域占比少一些，让label显示出来
![微信截图_20210520102739](https://user-images.githubusercontent.com/29794128/118910201-aa466c00-b956-11eb-81b0-36a1a35d6313.png)

**Comment by hustcc** [comment]
{
  radius: 0.5, // 设置从 0 ~ 1 的数字，表示图形占用画布的比例
}
