### ISSUE TITLE
g2plot 堆叠分组柱状图 提示框显示不全

### ISSUE THREAD

**Issue by rabbit-tian** [antvis/G2Plot#2572]
* **G2Plot Version**: 2.3.21
* **Platform**: g2plot 2.x 
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

![image](https://user-images.githubusercontent.com/26690191/119122382-0990a300-ba61-11eb-9308-e20f3a6cf32f.png)

**Comment by rabbit-tian** [comment]
@visiky 麻烦老师看下哈

**Comment by visiky** [comment]
🤔 以后加功能之后，check 一下是否 work，不 work 就不要加 @lxfu1
