### ISSUE TITLE
雷达图 如何设置 state => default 生效呢?

### ISSUE THREAD

**Issue by rabbit-tian** [antvis/G2Plot#2573]
* **G2Plot Version**: 2.3.21
* **Platform**: g2plot 
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:  https://codesandbox.io/s/condescending-morse-kk9xs?file=/index.js

![image](https://user-images.githubusercontent.com/26690191/119122629-4a88b780-ba61-11eb-9742-51b7afcda6a6.png)

**Comment by rabbit-tian** [comment]
@visiky 麻烦老师们看下哈，辛苦啦🌹🌹🌹

**Comment by visiky** [comment]
先通过 `point.state` 设置. [文档](https://g2plot.antv.vision/zh/docs/api/plots/radar#point)

后面支持下 point.state 没有设置的时候，继承外部主元素的 state 状态样式设置
