### ISSUE TITLE
使用antd/charts 的饼图，toolTip的customContent展示问题

### ISSUE THREAD

**Issue by sunshineLyx** [antvis/G2Plot#2581]
* **G2Plot Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

问题：使用antd/charts 的饼图，toolTip的customContent再次使用饼图，页面展示[object,object]
预期效果：
![image](https://user-images.githubusercontent.com/26115568/119323261-14da0d80-bcb1-11eb-8631-90e2ee993d62.png)
目前效果：
![image](https://user-images.githubusercontent.com/26115568/119323298-202d3900-bcb1-11eb-8a26-7c4cd0a78796.png)
帮忙看下是哪里写错了，谢谢！
在线demo：https://codesandbox.io/s/friendly-snow-23r7m?file=/App.tsx:966-979

**Comment by lxfu1** [comment]
这样用

![image](https://user-images.githubusercontent.com/31396322/119324269-38ea1e80-bcb2-11eb-9ad2-acee61d75d35.png)
