### ISSUE TITLE
G2Plot绘制流量图耗时太久

### ISSUE THREAD

**Issue by huoyuhao** [antvis/G2Plot#2590]
"@antv/g2plot": "^2.3.17",
vue3项目
场景：绘制流量图
一共8000多个点
发现渲染绘制耗时2s多，有没有优化方案
发现：
折线图耗时<面积图
使用缩放增加耗时
数据流过多耗时增加

目前我是面积图+有缩放+8000多个数据点+一个图表2个面积图

目前缩放异步渲染，先渲染数据，但是还是很慢

**Comment by visiky** [comment]
升级到最新版本
