### ISSUE TITLE
Tooltip配置自定义内容IE11下报错：”对象不支持"remove"属性或方法。“

### ISSUE THREAD

**Issue by Coocochen** [antvis/G2Plot#2594]
* **G2Plot Version**: 2.3.21
* **Platform**: react
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

![image](https://user-images.githubusercontent.com/44342750/120058058-81bb2200-c07a-11eb-9fb1-855a97a3f667.png)
![image](https://user-images.githubusercontent.com/44342750/120058063-8f70a780-c07a-11eb-9537-a5db653b0971.png)

问题描述：
IE11环境下，tooltip配置customContent, 鼠标悬浮到图表上，报错：对象不支持"remove"属性或方法。

**Comment by visiky** [comment]
应该是不会的，看下这个：https://developer.mozilla.org/zh-CN/docs/orphaned/Web/API/ChildNode/remove

看下 `this.get('container')` 获取的是不是一个 domNode

**Comment by hustcc** [comment]
@visiky @Coocochen 我猜应该是直接使用 script 标签加载，然后没有加入 polyfill 导致的。

**Comment by Coocochen** [comment]
@hustcc @visiky Childnode.remove()是DOM的一部分,因此babel不会对它做任何事情.建议只使用 Mozilla documentation中建议的polyfill，可以在g2plot里添加这个polyfill吗

**Comment by hustcc** [comment]
Poly fill 不会在底层库做，一定是在业务层做的，不然没个底层库都做一遍，不是很冗余吗，而且还容易出问题！

**Comment by visiky** [comment]
> @hustcc @visiky Childnode.remove()是DOM的一部分,因此babel不会对它做任何事情.建议只使用 Mozilla documentation中建议的polyfill，可以在g2plot里添加这个polyfill吗

直接看上面的 FAQ
