### ISSUE TITLE
🤔 [问题] 数据自适应问题，g2 是有能力自动调节 y 轴的，不知道为什么到 g2plot 就不行了

### ISSUE THREAD

**Issue by shenxiang11** [antvis/G2Plot#2611]
数据自适应问题，g2 是有能力自动调节 y 轴的，不知道为什么到 g2plot 就不行了。

g2
![1623049528107](https://user-images.githubusercontent.com/17292115/120975152-7f0bab80-c7a3-11eb-9349-65a208055d37.jpg)

g2plot
![1623049562116](https://user-images.githubusercontent.com/17292115/120975173-83d05f80-c7a3-11eb-87f2-76a9e42fd094.jpg)

**Comment by shenxiang11** [comment]
对比图更新一下：

g2
![1623049528107](https://user-images.githubusercontent.com/17292115/120975656-0f49f080-c7a4-11eb-992a-9959d504571b.jpg)

g2plot
![1623050472678](https://user-images.githubusercontent.com/17292115/120975672-140ea480-c7a4-11eb-92d6-9016513f6ff3.jpg)

**Comment by visiky** [comment]
G2Plot 默认做了优化，自动从 0 开始；如果需要自适应的话，可以用下面的方式：
```ts
 yAxis: {
    min: null
  },
```

**Comment by shenxiang11** [comment]
感谢

**Comment by shenxiang11** [comment]
感谢

**Comment by johnsxiong** [comment]
> G2Plot 默认做了优化，自动从 0 开始；如果需要自适应的话，可以用下面的方式：
> 
> ```ts
>  yAxis: {
>     min: null
>   },
> ```

请问nice属性是干嘛的啊 感觉用了没效果
![image](https://user-images.githubusercontent.com/37213061/131825787-423961fe-644d-49de-9ab4-8f11fd62e10c.png)
