### ISSUE TITLE
🐛 [BUG] G2Plot 漏斗图在数据为空时候会报错

### ISSUE THREAD

**Issue by mumu-baba** [antvis/G2Plot#2616]
### 🐛 Bug description
官方演示demo 就可以复现，数据给空就行
### 💻 Link to minimal reproduction

https://g2plot.antv.vision/zh/examples/case/statistical-scenario#trend-funnel

### 🚑 Any additional [like screenshots]

* **G2Plot Version**:latest
* **Platform**:

**Comment by susiwen8** [comment]
+1, G2的 漏斗图为空不会报错

**Comment by susiwen8** [comment]
https://github.com/antvis/G2Plot/blob/master/src/plots/funnel/geometries/basic.ts#L19
