### ISSUE TITLE
🐛 [BUG] g2plot 2.x 柱状图   连续型数据的时候，自定义提示框返回值 不完整

### ISSUE THREAD

**Issue by rabbit-tian** [antvis/G2Plot#2624]
### 🐛 Bug description [Please make everyone to understand it]
复现链接：https://codesandbox.io/s/winter-dust-y746n?file=/index.ts
![image](https://user-images.githubusercontent.com/26690191/121504595-b6cd5a00-ca14-11eb-8159-29a4b4762696.png)
![image](https://user-images.githubusercontent.com/26690191/121504613-b92fb400-ca14-11eb-8f03-05c300272ed5.png)

### 💻 Link to minimal reproduction

Please provide a link by forking these links [g2plot](https://codesandbox.io/s/g2plot-reproduction-template-gyej1) or GitHub repo. What is a minimal reproduction, and why is it required?

### 🚑 Any additional [like screenshots]

* **G2Plot Version**: 2.3.23
* **Platform**: g2plot

**Comment by rabbit-tian** [comment]
@visiky 麻烦老师看下哈

**Comment by Angelii** [comment]
你好，建议暂时可以把连续性数据转换成分类型的数据~

**Comment by visiky** [comment]
Duplicate with: https://github.com/antvis/G2Plot/issues/2601
