### ISSUE TITLE
🐛 [BUG] 分组玫瑰图🌹 自定义tooltip交互 && 自定义tooltip展示内容时，鼠标移入后部分tooltip不显示

### ISSUE THREAD

**Issue by ntscshen** [antvis/G2Plot#2627]
### 🐛 Bug description [Please make everyone to understand it]
自定义tooltip交互 && 自定义tooltip展示内容时，鼠标移入后部分tooltip不显示

1. 自定义tooltip交互？ 有点击触发需求
2. 自定义tooltip展示内容时？有自定义icon需求

### 💻 Link to minimal reproduction
https://codesandbox.io/s/stoic-heisenberg-sff3j?file=/index.js

### 🚑 Any additional [like screenshots]

* **G2Plot Version**:
* **Platform**:

**Comment by Angelii** [comment]
![image](https://user-images.githubusercontent.com/27258415/121985867-243c0a80-cdc8-11eb-8f23-f00e9bfeaa46.png)
你好，自定义tooltip中的svg遮挡了hover的部分，可以设置一下svg的宽高

**Comment by visiky** [comment]
是否已经解决了？

**Comment by ntscshen** [comment]
感谢~ 就是这个自定义svg导致的~
