### ISSUE TITLE
玉珏图没有考虑isStack的情况

### ISSUE THREAD

**Issue by wxfqf** [antvis/G2Plot#2645]
玉珏图没有考虑isStack的情况，导致column的总长度大于360度

![image](https://user-images.githubusercontent.com/3713167/122172667-91789a00-ceb3-11eb-8e33-dc2a583b4107.png)

* **G2Plot Version**:2.3.17
* **Platform**:win10

**Comment by visiky** [comment]
- [ ] G2 层是否可以获取到 stack 之后的数据

**Comment by wxfqf** [comment]
> * [ ]  G2 层是否可以获取到 stack 之后的数据

可以的，看源码是计算最大刻度的时候没考虑，我临时修改了下本地源码，可以显示正常


/*  meta 配置  @antv\g2plot\lib\plots\radial-bar\adaptor.js
*/
function meta(params) {
    var _a;
    var options = params.options;
    var yField = options.yField, maxAngle = options.maxAngle, data = options.data;
    var processData = utils_2.processIllegalData(data, yField);   
    **var isStack= options.isStack;
    if(isStack===true){
        var xField = options.xField
        var statckData=[];
        var statckDataMap={};
        processData.forEach(d=>{
            let xVal=d[xField];
            let yVal=d[yField];
            let xData=statckDataMap[xVal];
            if(xData==undefined){
                xData={};
                xData[xField]=xVal;
                xData[yField]=0;
                statckData.push(xData);
                statckDataMap[xVal]=xData;
            }
            xData[yField]+=yVal==undefined?0:yVal;

        });**      
        processData=statckData;

    }
    return utils_1.flow(common_1.scale((_a = {},
        _a[yField] = {
            min: 0,
            max: utils_3.getScaleMax(maxAngle, yField, processData),
        },
        _a)))(params);
}

**Comment by visiky** [comment]
> > * [ ]   G2 层是否可以获取到 stack 之后的数据
> 
> 可以的，看源码是计算最大刻度的时候没考虑，我临时修改了下本地源码，可以显示正常
> 
> /* meta 配置 @AntV\g2plot\lib\plots\radial-bar\adaptor.js
> */
> function meta(params) {
> var _a;
> var options = params.options;
> var yField = options.yField, maxAngle = options.maxAngle, data = options.data;
> var processData = utils_2.processIllegalData(data, yField);
> **var isStack= options.isStack;
> if(isStack===true){
> var xField = options.xField
> var statckData=[];
> var statckDataMap={};
> processData.forEach(d=>{
> let xVal=d[xField];
> let yVal=d[yField];
> let xData=statckDataMap[xVal];
> if(xData==undefined){
> xData={};
> xData[xField]=xVal;
> xData[yField]=0;
> statckData.push(xData);
> statckDataMap[xVal]=xData;
> }
> xData[yField]+=yVal==undefined?0:yVal;
> 
> ```
>     });  
>     processData=statckData;
> 
> }**    
> return utils_1.flow(common_1.scale((_a = {},
>     _a[yField] = {
>         min: 0,
>         max: utils_3.getScaleMax(maxAngle, yField, processData),
>     },
>     _a)))(params);
> ```
> 
> }

嗯嗯，我只是记录一个 todo list，解决方案都很多；但是目前玉珏图暂时从定义上还没有支持  isStack
