### ISSUE TITLE
🤔 折线图，大数据展示时，point 展示的很密集

### ISSUE THREAD

**Issue by feEden** [antvis/G2Plot#2647]
### 🐛 Question description [Please make everyone to understand it]
 折线图，大数据展示时，point 展示的很密集，怎么配置随主轴标签间隔隐藏策略

目前情况
![image](https://user-images.githubusercontent.com/46083022/122403415-f0700900-cfb0-11eb-9a8a-8de3801e5245.png)

最下面折线直接糊了
### 💻 Link to minimal reproduction

Please provide a link by forking these links [g2plot](https://codesandbox.io/s/g2plot-reproduction-template-gyej1) or GitHub repo. What is a minimal reproduction, and why is it required?

### 🏞 Expected result
有没有一个配置，可以配置随主轴标签间隔隐藏策略
像echarts一样
![image](https://user-images.githubusercontent.com/46083022/122403636-18f80300-cfb1-11eb-8387-5e51dd3f2d34.png)
### 🚑 Any additional [like screenshots]

* **G2Plot Version**: laster
* **Platform**:

**Comment by visiky** [comment]
目前需要自己手动控制下，比如：
```ts
point: {
        shape: 'circle',
        size: 2,
        style: (datum) => {
         // 找到数据索引
          const idx = DATA.findIndex( .... );
          return {
            // 每 10 个展示一个点
            fillOpacity: idx / 10 ? 0 : 1,
            stroke: 'transparent',
          };
        },
      },
```

**Comment by songsng** [comment]
> 目前需要自己手动控制下，比如：
> 
> ```ts
> point: {
>   shape: 'circle',
>   size: 2,
>   style: (datum) => {
>    // 找到数据索引
>     const idx = DATA.findIndex( .... );
>     return {
>       // 每 10 个展示一个点
>       fillOpacity: idx / 10 ? 0 : 1,
>       stroke: 'transparent',
>     };
>   },
> },
> ```

这个官方会有计划加入这个策略么

**Comment by songsng** [comment]
@visiky 官方有计划优化么

**Comment by ntscshen** [comment]
请以echarts为目标~ 在开发者体验上~

**Comment by visiky** [comment]
> @visiky 官方有计划优化么

看具体时间安排

**Comment by visiky** [comment]
> 请以echarts为目标~ 在开发者体验上~ 

要有自己的立场 请换位思考 每个人的时间安排

**Comment by visiky** [comment]
> @visiky 官方有计划优化么

仔细评估后 会更新到置顶issue的具体排期内

**Comment by hustcc** [comment]
> 请以echarts为目标~ 在开发者体验上~

![image](https://user-images.githubusercontent.com/7856674/122757184-eceac380-d2c9-11eb-8098-eb2f4d8b8f8b.png)

目前确实还是有不少的 bug，但是针对这一个 case，可以考虑一些场景，比如需要按照：

- 固定几个 x 轴添加 symbol
- 每 4 个数据显示一个 symbol
- y 轴大于某个界限的时候，显示 symbol
- ...

怎么做？如果是无限开配置，无限加文档，不仅我们自己的迭代开发无止尽，对于开发者来说感知到永远是配置文档，而不是可视化的基础技术，除此之外，G2Plot 可能需要像 echarts 那样迭代 6，7 年才能到好用。

这里面肯定有我们自己想法的，当然我们也会借鉴 echarts，highcharts 等，但是如果只是照搬，我们何必另开轮子。
