### ISSUE TITLE
G2Plot x轴刻度长度无法根据时间点绘制

### ISSUE THREAD

**Issue by wybiubiu1012** [antvis/G2Plot#2653]
代码如下：
https://codesandbox.io/s/anniuleixing-antd4161-forked-rfgk7?file=/index.js

存在问题
时间段 6.00-7.00 和 7.00-20.00 x轴划分长度一致
应该按照时间段划分长度  如6.00-7.00 长度应该占刻度 1/12   7.00-20.00占刻度11/12
已配置过属性
tickCount tickInterval 均无效

**Comment by pearmini** [comment]
这里的数据不是只有 7点 和 20点两个时间点吗？这里需要把 nice 设置成 false

```js
 xAxis: {
    type: "time",
    mask: "HH:mm:ss",
    nice: false,
    label: {
      rotate: -45,
      offset: 50
    }
  },
```

**Comment by wybiubiu1012** [comment]
@pearmini 
这里设置nice: false后，x轴的划分依然是等分的

**Comment by wybiubiu1012** [comment]
现在好像是根据数据的length进行划分的 而不是时间的刻度

**Comment by pearmini** [comment]
你的时间点只有 7 点和 20 点，等分时没有问题的，你的数据并没有体现 6 点 这个时间点

**Comment by wybiubiu1012** [comment]
我看了下 数据源的确有问题的

**Comment by pearmini** [comment]
嗯嗯，如果没有问题了，可以把这个 issue 关了
