### ISSUE TITLE
🐛 [BUG] Object(...) is not a function

### ISSUE THREAD

**Issue by Weber-hui** [antvis/G2Plot#2659]
### "@antv/g2plot"由1.1.24版本向2.3.23版本升级后，引入模块报错；
![image](https://user-images.githubusercontent.com/82556104/123263418-8369ef80-d52b-11eb-82b7-7055a9265927.png)

### 💻 求教！

* **G2Plot Version**:
* **Platform**:

**Comment by hustcc** [comment]
删除 lock，重装依赖，应该就可以了。

**Comment by Weber-hui** [comment]
> 删除锁，重装依赖，应该就可以了。

不行～，已经尝试了

**Comment by hustcc** [comment]
> > 删除锁，重装依赖，应该就可以了。
> 
> 不行～，已经尝试了

那看看是不是你们业务产品中，依赖了多个不同版本的 G2Plot，比如同时使用了 bizcharts 和 G2Plot

**Comment by Weber-hui** [comment]
> > > 删除锁，重装依赖，应该就可以了。
> > 
> > 
> > 不行～，已经尝试了
> 
> 那看看是不是你们业务产品中，依赖了多个不同版本的 G2Plot，比如同时使用了 bizcharts 和 G2Plot
只安装了antd vue和antv/g2，antv/g2plo
![image](https://user-images.githubusercontent.com/82556104/123266617-c7aabf00-d52e-11eb-898d-2f493bfc8cfc.png)

**Comment by hustcc** [comment]
还有其他的依赖吗？这几个没有什么问题。

**Comment by cnlinge** [comment]
> > 删除锁，重装依赖，应该就可以了。
> 
> 不行～，已经尝试了

我也遇到了，太奇怪了。  你是用的什么设备。

**Comment by cnlinge** [comment]
版本升级到   "@antv/g2plot": "^2.4.20" 解决了
