### ISSUE TITLE
🐛 [BUG] Cannot load in Safari 15 Beta

### ISSUE THREAD

**Issue by coder-bts** [antvis/G2Plot#2666]
### 🐛 Bug description [Please make everyone to understand it]

My website using G2Plot cannot load the charts in Apple Safari 15 Beta, in iOS 15 and macOS Monterey. Likely an Apple issue, but just thought you would like to know.

### 💻 Link to minimal reproduction

[g2plot example reproduction](https://codesandbox.io/s/g2plot-reproduction-template-gyej1) can reproduce this issue on Safari 15

### 📷 Step to reproduce

Visit any site with G2Plot charts on Safari 15 Beta on either iOS 15 or macOS Monterey.

Charts won't load and the page starts to consume a lot of memory.

### 🏞 Expected result

Graphs loaded correctly.

### 🚑 Any additional [like screenshots]

N/A

* **G2Plot Version**:
* **Platform**: macOS Monterey Beta 1 & 2, iOS 15 Beta 1 & 2

**Comment by coder-bts** [comment]
Also reported to Apple.

Again:
> Likely an Apple issue, but just thought you would like to know.

**Comment by coder-bts** [comment]
Update: The issue still can be reproduced on the latest Safari beta release. Apple couldn't diagnose the issue after an investigation.

I have opened a thread in Apple's developer forum: https://developer.apple.com/forums/thread/685866

**Comment by coder-bts** [comment]
Turns out, this issue can be resolved by turning off "CPU Processing: Canvas Rendering" in the WebKit Experimental Features section. This looks like, then, some WebKit issue.

**Comment by donglegend** [comment]
遇到此问题。。。

**Comment by visiky** [comment]
看下这个：https://github.com/antvis/G2/issues/3635. reinstall package dependencies
