### ISSUE TITLE
🤔 [QUESTION]堆叠的柱状图怎么设置显示一个总数的label。顺便吐槽一句：文档能写的更详细些不啦，有些有点看不懂

### ISSUE THREAD

**Issue by sun-die** [antvis/G2Plot#2669]
### 💻 Link to minimal reproduction

Please provide a link by forking these links [g2plot](https://codesandbox.io/s/g2plot-reproduction-template-gyej1) or GitHub repo. What is a minimal reproduction, and why is it required?

### 🚑 Any additional [like screenshots]

* **G2Plot Version**:
* **Platform**:

**Comment by visiky** [comment]
没写的就是不支持
