### ISSUE TITLE
一个chart里，多个view的图形重叠了，怎么办?（adjust只能影响同一个view里的图形）

### ISSUE THREAD

**Issue by huangup** [antvis/G2Plot#2678]
![image](https://user-images.githubusercontent.com/13741256/124446005-9d6cc300-ddb2-11eb-968e-6874dc70e843.png)

**Comment by huangup** [comment]
https://github.com/antvis/G6/issues/3014

**Comment by visiky** [comment]
方案 1、图层相互偏移下
方案 2、放在一个图层内，进行处理

**Comment by huangup** [comment]
> 方案 1、图层相互偏移下
> 方案 2、放在一个图层内，进行处理

如果是放在一个view内，那怎样把Y轴在左边和在右边的图形分开画？

**Comment by visiky** [comment]
1. 调整下 y 轴的位置
2. 如果这个图表很复杂，内置提供的图表不满足，建议看下 G2Plot 开放扩展机制去定制图表。但要求是对 G2 有所了解，另外 G2Plot 的每个图表都是用心处理过的，从架构上是流水线的处理，很多复用的功能，可以参考下具体实现，去实现一个定制的 adaptor。对于你的场景，可以参考下双轴图的实现。
