### ISSUE TITLE
方案 2、放在一个图层内，进行处理

### ISSUE THREAD

**Issue by huangup** [antvis/G2Plot#2684]
方案 1、图层相互偏移下
方案 2、放在一个图层内，进行处理

_Originally posted by @visiky in https://github.com/antvis/G2Plot/issues/2678#issuecomment-874845460_

如果是放在一个view内，那怎样把Y轴在左边和在右边的图形分开画出来？

**Comment by hustcc** [comment]
在一个 issue 中讨论吧。
