### ISSUE TITLE
🤔 [QUESTION] Y轴的起点可以根据数据的最小值来计算吗，这个是需要自定义tickMethod吗

### ISSUE THREAD

**Issue by zaki1991** [antvis/G2Plot#2686]
### 💻 Link to minimal reproduction

Please provide a link by forking these links [g2plot](https://codesandbox.io/s/g2plot-reproduction-template-gyej1) or GitHub repo. What is a minimal reproduction, and why is it required?

### 🚑 Any additional [like screenshots]

* **G2Plot Version**:
* **Platform**:

**Comment by hustcc** [comment]
```ts
{
  meta: {
     [y]: { min: 100 },
  },
},
```

**Comment by zaki1991** [comment]
@hustcc 这个值能根据返回的数据动态变化吗，不使用update的情况下 (使用update图表会闪烁)

**Comment by hustcc** [comment]
> @hustcc 这个值能根据返回的数据动态变化吗，不使用update的情况下 (使用update图表会闪烁)

目前不行，现在默认是：如果数值全部是正数或者负数，那么就从 0 开始，否则就是从最小开始。
