### ISSUE TITLE
一个chart里，多个view的图形和legend上，能够实现自动分配不同的颜色吗？

### ISSUE THREAD

**Issue by huangup** [antvis/G2Plot#2689]
![image](https://user-images.githubusercontent.com/13741256/125067011-43d40380-e0e6-11eb-966d-93d2f84a6558.png)

**Comment by huangup** [comment]
https://github.com/antvis/G2/issues/3513

**Comment by arcsin1** [comment]
是可以的哦。 参考这个：https://g2plot.antv.vision/zh/examples/dual-axes/grouped-stacked-line#stacked-grouped-column-line
