### ISSUE TITLE
🐛 [BUG] 折线图 - 缩略图 - 背景趋势

### ISSUE THREAD

**Issue by ntscshen** [antvis/G2Plot#2693]
### 🐛 Bug description [Please make everyone to understand it]
折线图 - 缩略图 - 背景趋势
1. 当数据中存在多个系列，其中有一个系列只有一条数据时，无背景趋势
### 💻 Link to minimal reproduction
https://codesandbox.io/s/festive-banzai-u5rpg?file=/index.js:315-415

**Comment by visiky** [comment]
@Aarebecca 看下 component 是不是有这个问题，修复一下
