### ISSUE TITLE
🐛 [BUG]直方图的最后一个分箱总是只有一个，且最后显示的分箱数量比binNumber大1

### ISSUE THREAD

**Issue by SakuraWangle** [antvis/G2Plot#2695]
### 💻 Link to minimal reproduction

Please provide a link by forking these links [g2plot](https://codesandbox.io/s/g2plot-reproduction-template-gyej1) or GitHub repo. What is a minimal reproduction, and why is it required?

### 🚑 Any additional [like screenshots]

* **G2Plot Version**:
* **Platform**:

**Comment by SakuraWangle** [comment]
设置binNumber时，最后一个依然总是1。
![8151627354518_ pic_hd](https://user-images.githubusercontent.com/37700655/127087934-c9c132a8-df7b-44d9-9c10-181b9b18fe82.jpg)
![8141627354429_ pic_hd](https://user-images.githubusercontent.com/37700655/127087941-7f534fea-26cc-4902-be57-c4e1e567bd4d.jpg)

**Comment by visiky** [comment]
看 release。。。还没发版呢
