### ISSUE TITLE
🐛 [BUG] Slider 绘制溢出

### ISSUE THREAD

**Issue by doudou003** [antvis/G2Plot#2696]
### 🐛 Bug description [Please make everyone to understand it]
slider 绘制溢出

### 💻 Link to minimal reproduction
见用例

### 📷 Step to reproduce
见用例

### 🏞 Expected result
见用例

### 🚑 验证用例
```js
import { Line } from '@antv/g2plot';
function random(min, max) {
  var range = max - min;
  var rand = Math.random();
  return min + Math.floor(rand * range);
}
const line = new Line('container', {
  data:Array.from({ length: 500 }, (v, item) => ({x: '2021-07-07 '+item+':00',y: random(0, 1200)})),
  height:300,
  xField: 'x',
  yField: 'y',
  slider: {
    height: 200,
    start: 0.1,
    end: 0.5,
    trendCfg:{
      limitInPlot: true,
      smooth:true,
      isArea: true,
    },
  },
});
line.render();
```

* **G2Plot Version**: 全部
* **Platform**: 全部

**Comment by visiky** [comment]
为什么要设置 `height: 200`

**Comment by doudou003** [comment]
slider太小了，需要放大一些

**Comment by visiky** [comment]
> slider太小了，需要放大一些

200px 高？怎么理解这个溢出呢

**Comment by doudou003** [comment]
![image](https://user-images.githubusercontent.com/62648044/125784799-e98ca8d7-749d-4069-ad85-9e9baa2d4f37.png)

**Comment by visiky** [comment]
更新依赖，确保 @antv/path-util 在 2.0.15 版本
