### ISSUE TITLE
🐛 [BUG] 当设置svg渲染时，柱形图/折线图等图表的x轴文本显示不全

### ISSUE THREAD

**Issue by JevonSeraph** [antvis/G2Plot#2697]
当设置svg渲染时，柱形图/折线图等图表的x轴文本显示不全
![image](https://user-images.githubusercontent.com/59252126/125602689-7af3cc7a-5da2-40bd-a74f-eb80a31cc2ee.png)

* **G2Plot Version**: 2.3.25
* **Platform**: win10 chrome 91.0.4472.124

**Comment by MGYYM** [comment]
我也有同样的问题，目前我的做法是设置appendPadding

**Comment by MGYYM** [comment]
我也有同样的问题，目前我的做法是设置appendPadding
