### ISSUE TITLE
🐛 [BUG] g2plot 2.x 密度热力图 系列bug （color Func，heatmapStyle，state，setState均不生效）

### ISSUE THREAD

**Issue by rabbit-tian** [antvis/G2Plot#2700]
### 🐛 Bug description [Please make everyone to understand it]
color 的Func回调，heatmapStyle，state，setState等配置项  均不生效

### 🏞 Expected result
https://codesandbox.io/s/proud-wave-oyg8d?file=/index.ts:1088-1096

* **G2Plot Version**: 2.3.26
* **Platform**: g2plot 2.x

**Comment by rabbit-tian** [comment]
@visiky 麻烦老师看一下

**Comment by ai-qing-hai** [comment]
> @visiky麻烦老师看一下

color 的话，  颜色是通过渐变来的。 如果是回调 那就是确定的颜色了， 没有渐变可言。 所以 heatmap 的  color  没有 回调时正确的。

**Comment by visiky** [comment]
需要 G2 解决：
1. https://github.com/antvis/G2/issues/3522

**Comment by hustcc** [comment]
@visiky G2 中，这个可能没有办法像常规的 Geometry 一样进行 color 映射吧~

**Comment by visiky** [comment]
不知道，先记录着呗，再看看具体情况

**Comment by visiky** [comment]
![image](https://user-images.githubusercontent.com/15646325/126111345-b4cdf4b5-a233-4e7e-81bc-640021a68452.png)

**Comment by visiky** [comment]
结论：密度热力图不支持该系列功能（即：通过回调的方式来设置密度热力图的样式）
