### ISSUE TITLE
🐛 [BUG] 表格图例 legend 未显示所有数据

### ISSUE THREAD

**Issue by violetjack** [antvis/G2Plot#2704]
### 🐛 Bug description [Please make everyone to understand it]

图表的 data 提供了 2021-06-23 到 2021-07-16 的这 24 天的数据，但是显示的图例只是间隔性的 7 个。是不是由于 YYYY-MM-DD 这种日期格式会导致 legend 图例缩减显示不全？

### 💻 Link to minimal reproduction

codesadbox address：https://codesandbox.io/s/clever-curie-6sjx9?file=/index.ts

### 🏞 Expected result

按道理来说，是不是应该显示全部 24 天数据的图例？

### 🚑 Any additional [like screenshots]

* **G2Plot Version**: 2.3.21
* **Platform**: google chrome for mac 91.0.4472.114

**Comment by violetjack** [comment]
后来为了显示全部图例，我为每个 seriesField 的日期格式加了个个空格： ` 2021-06-27` 就能实现显示全部 legend 的需求了。

**Comment by visiky** [comment]
指定下就好了
![image](https://user-images.githubusercontent.com/15646325/137516677-910a58ad-351c-4c32-b76f-18b0a1ea25bc.png)

**Comment by bmob77** [comment]
> 指定下就好了 ![image](https://user-images.githubusercontent.com/15646325/137516677-910a58ad-351c-4c32-b76f-18b0a1ea25bc.png)

没有work~~
