### ISSUE TITLE
双轴图, 辅助线不可用

### ISSUE THREAD

**Issue by zzfy8023** [antvis/G2Plot#2710]
### 💻 Link to minimal reproduction

Please provide a link by forking these links [g2plot](https://codesandbox.io/s/g2plot-reproduction-template-gyej1) or GitHub repo. What is a minimal reproduction, and why is it required?

### 🚑 Any additional [like screenshots]

* **G2Plot Version**:
* **Platform**:

**Comment by zzfy8023** [comment]
option = {
  xField: 'name',
  yField: ['count', 'value'],
  meta: {
    value: {
      alias: "占比"
    },
  },
  annotations: [
    {
      type: 'line',
      /** 起始位置 */
      start: ['min', 'median'],
      /** 结束位置 */
      end: ['max', 'median'],
      text: {
        content: '中位线',
        position: 'right',
        offsetY: 18,
        style: {
          textAlign: 'right',
        },
      },
      style: {
        lineDash: [4, 4],
      },
    },],
  height: 300,
  padding: [22, 20, 20, 20],
  xAxis: {
    line,
  },
  yAxis: {
    count: {
      line,
      tickCount: 5,
    },
    value: {
      line,
      tickCount: 5,
      label: {
        formatter: function (value) {
          if (value > 0) {
            return value + "%";
          } else {
            return 0
          }

        }
      },
      max: 105,
      min: 0
    }
  },
  legend: {
    position: "top-right",
    itemSpacing: 10,
    itemHeight:17,
    offsetX: -30,
    offsetY: -3,
  },
  tooltip: {
    customContent: function (x, data) {
      var str = `<p style="padding:12px 0;font-size:12px">${x}</p>`;
      data.map(item => {
        if (item.name == "占比") {
          str += `<p style="padding:4px 10px 4px 4px;font-size:12px;">
                <span style="display: flex; justify-content:space-between">
                   <span>
                        <span style="display:inline-block;background:${item.color}; width: 8px;height: 2px;margin-right: 4px;margin-bottom: 4px;"></span>
                        <span style="margin-right: 30px;">${item.name} :</span>
                    </span>
                    <span> ${item.value}%</span>
              </span>
               </p>`;
        } else {
          str += `<p style="padding:4px 10px 4px 4px;font-size:12px;">
                <span style="display: flex; justify-content:space-between">
                   <span>
                        <span style="display:inline-block;background:${item.color};  width: 8px;height: 8px;margin-right: 4px;"></span>
                        <span style="margin-right: 30px;">${item.name} :</span>
                    </span>
                    <span> ${item.value}个</span>
              </span>
               </p>`;
        }
      });
      return str;
    }
  },
  animation: false,
  theme: 'custom-theme',
}

**Comment by visiky** [comment]
文档错误，参考使用：https://codesandbox.io/s/dual-axes-8q9un?file=/index.ts
