### ISSUE TITLE
🐛 [BUG] g2plot 2.x 堆叠分组柱状图 连续型数据的时候，自定义提示框返回值 不完整

### ISSUE THREAD

**Issue by rabbit-tian** [antvis/G2Plot#2724]
### 🐛 Bug description [Please make everyone to understand it]
柱状图的 分类型数据 提示框数据ok，但是 连续型数据的时候，自定义提示框返回值 不完整
![image](https://user-images.githubusercontent.com/26690191/126750024-8762de39-733a-43ee-92fa-432fb2141591.png)

### 💻 Link to minimal reproduction
复现：https://codesandbox.io/s/reverent-bash-bdr58?file=/index.ts

* **G2Plot Version**: 2.3.27
* **Platform**: g2plot

**Comment by rabbit-tian** [comment]
@visiky 麻烦老师有时间 看下哈💗

**Comment by visiky** [comment]
问题见：https://github.com/antvis/G2/pull/3763#issuecomment-1003315666
