### ISSUE TITLE
🥰 [FEATURE]g2plot 矩形树图 下钻功能开启时，面包屑的 样式暂时无配置，需要添加

### ISSUE THREAD

**Issue by rabbit-tian** [antvis/G2Plot#2743]
### 🥰 Features description [Please make everyone to understand it]
![image](https://user-images.githubusercontent.com/26690191/127624913-14cfca4a-1b9b-4ce8-949b-1050d39db6b3.png)

**Comment by liuzhenying** [comment]
更新，看下这个属性是否满足需求：
https://g2plot.antv.vision/zh/docs/api/plots/treemap#drilldown
demo 见 https://g2plot.antv.vision/zh/examples/more-plots/treemap#drill-down 注释部分

**Comment by rabbit-tian** [comment]
面包屑可配置了
drilldown: {
        enabled: true,
        breadCrumb: {
          rootText: '初始11',
          textStyle: {
            fill: "red"
          },
          activeTextStyle: {
            fill: "blue"
          }
        },
      },
