### ISSUE TITLE
🤔 [QUESTION] 求，桑基图label.callback返回带value相关数据

### ISSUE THREAD

**Issue by ntscshen** [antvis/G2Plot#2746]
### 🐛 Question description [Please make everyone to understand it]
🤔 [QUESTION] 求，桑基图label.callback返回带value相关数据

官方案例: https://antv-g2plot.gitee.io/zh/examples/relation-plots/sankey#alipay
```js
  // 求入参，包含value数据相关
  label: {
    callback: (x, name) => {
      console.log(x); // Array(4) [ 0.992, 1, 1, 0.992 ]
      console.log(name); // 蚂蚁森林
      return { content: name }
    }
  }
```

**Comment by visiky** [comment]
新的使用方式，依赖: #2756 

![image](https://user-images.githubusercontent.com/15646325/128143379-3ed0b664-3cb6-41db-a417-e0cea51bd940.png)
