### ISSUE TITLE
🤔 [QUESTION]多个独立载体图表联动效果，求个demo.

### ISSUE THREAD

**Issue by apgk** [antvis/G2Plot#2759]
目前想多个图表联动，但没找着资料，官方联动是mix，这个是一个载体多个图表，但实际使用是多个独立载体多个图表联动。
类似 echart 的 connect
* **G2Plot Version**:2.3.23
* **Platform**:

**Comment by visiky** [comment]
参考案例：https://g2plot.antv.vision/zh/examples/dynamic-plots/brush#advanced-brush1
事件文档：https://g2plot.antv.vision/zh/docs/api/options/events
其他交互，可以参考其他事件监听；如果说还不是很清楚的话，可以试着描述清楚具体诉求，看下是否可以提供 demo 给到

**Comment by apgk** [comment]
官方demo示例 ：https://g2plot.antv.vision/zh/examples/plugin/association#association-pie 
类似下方伪代码，如何让这两个联动起来，piePlot1 选中弹出tooltip , piePlot2 也跟着同等弹出
echarts  是有 echarts.connect([piePlot1 ,piePlot2 ])
伪代码：
`const piePlot1 = new Pie('container1', ....)`
`const piePlot2 = new Pie('container2', ....)`
