### ISSUE TITLE
🤔 [QUESTION] Bar 条形图 如何使用 连续图例？

### ISSUE THREAD

**Issue by SixLib** [antvis/G2Plot#2760]
### 🐛 Question description [Please make everyone to understand it]
  Bar 条形图 如何使用 连续图例？查了好久没有查到，目前是不支持么？
### 💻 Link to minimal reproduction

Please provide a link by forking these links [g2plot](https://codesandbox.io/s/g2plot-reproduction-template-gyej1) or GitHub repo. What is a minimal reproduction, and why is it required?

### 🚑 Any additional [like screenshots]

* **G2Plot Version**:
* ^2.3.28
* **Platform**:

**Comment by visiky** [comment]
为什么需要在条形图上使用连续图例，大概是怎么样的场景呢

**Comment by visiky** [comment]
似乎可以满足? 如果还不满足的话，可以另开 issue，描述下诉求哈 ❤️

```ts
import { Bar } from '@antv/g2plot';

const data = [
  { year: '1951 年', value: 38, type: 1 },
  { year: '1952 年', value: 52, type: 2 },
  { year: '1956 年', value: 61, type: 2 },
  { year: '1957 年', value: 145, type: 2 },
  { year: '1958 年', value: 48, type: 1 },
];

const bar = new Bar('container', {
  data,
  xField: 'value',
  yField: 'year',
  seriesField: 'type',
  legend: {
    position: 'top-left',
  },
});

bar.render();
```
![image](https://user-images.githubusercontent.com/15646325/137628388-9388ba93-718f-4d66-9fd3-d4cb75f144e1.png)
