### ISSUE TITLE
🐛 [BUG]官网柱状图文档，无限层叠，天女散花

### ISSUE THREAD

**Issue by zhongyue2332** [antvis/G2Plot#2765]
### 🐛 Bug description [Please make everyone to understand it]
当翻到tooltip的container相关的时候，无限生成tooltip框
### 💻 Link to minimal reproduction
https://g2plot.antv.vision/zh/docs/api/plots/column#container
### 🚑 Any additional [like screenshots]
![QQ截图20210806114219](https://user-images.githubusercontent.com/26564587/128452809-78123d97-c39a-4ce8-81d1-769bf68f0d61.png)

* **G2Plot Version**:
* **Platform**:

**Comment by visiky** [comment]
收到，立马跟进
