### ISSUE TITLE
🐛 [BUG] 词云，legend样式配置失效

### ISSUE THREAD

**Issue by ntscshen** [antvis/G2Plot#2775]
### 🐛 Bug description [Please make everyone to understand it]
https://codesandbox.io/s/hidden-mountain-kbdyg?file=/index.js:352-537
词云图，legend 配置不生效 [发呆]

**Comment by ntscshen** [comment]
![image](https://user-images.githubusercontent.com/21041458/128683279-f19e9517-29d9-4dd6-b3e6-9f137108384c.png)
> 
![image](https://user-images.githubusercontent.com/21041458/128683141-20eee1dc-ee6c-4757-a140-18093f540620.png)


color回调，入参展示的有bug，还是怎么滴。感觉不符合预期呀~

**Comment by ai-qing-hai** [comment]
> ![image](https://user-images.githubusercontent.com/21041458/128683279-f19e9517-29d9-4dd6-b3e6-9f137108384c.png)
> 
> > 
> 
> ![image](https://user-images.githubusercontent.com/21041458/128683141-20eee1dc-ee6c-4757-a140-18093f540620.png)
> 
> color回调，入参展示的有bug，还是怎么滴。感觉返回的不是期待的内容~
暂时 是因为 词云图内部的数据原因。    如果想要全部数据color 返回， 可以在 rawFields 中 加入 datum

**Comment by ntscshen** [comment]
@ai-qing-hai  omg，我的朋友，您的回复是黑夜中的一盏明灯。thanks
期待，词云的图例相关配置得到抛出~ color回调入参可以通过rawFields配置。
在下个小版本中...
