### ISSUE TITLE
🐛 [BUG] g2plot 2.x 对称条形图 tooltip  "formatter、 customContent、crosshairs、domStyles" 等配置都不生效

### ISSUE THREAD

**Issue by rabbit-tian** [antvis/G2Plot#2779]
### 🐛 Bug description [Please make everyone to understand it]
复现：https://codesandbox.io/s/busy-benz-1x5eu?file=/index.ts

* **G2Plot Version**: 2.3.29
* **Platform**: g2plot

**Comment by rabbit-tian** [comment]
@visiky 麻烦老师看下哈

**Comment by visiky** [comment]
你设置了两个 tooltip，导致上一个被覆盖了
