### ISSUE TITLE
🐛 [BUG] Legend's selected option doesn't work on DualAxes chart

### ISSUE THREAD

**Issue by Shamann** [antvis/G2Plot#2783]
### 🐛 Bug description

Setting a legend's [selected](https://g2plot.antv.vision/en/docs/api/components/legend#selected--) property has no effect on legend items and chart's geometries.
Possible root cause of the similar ant-design-charts [issue](https://github.com/ant-design/ant-design-charts/issues/745).

### 💻 Link to minimal reproduction

<https://codesandbox.io/s/nostalgic-kowalevski-3t163>

### 📷 Step to reproduce
1. Create a DualAxes chart with categorical data.
2. Add legend.selected property to the chart's config and set some of the categorical data values to false:
`legend: {
    selected: {
       bill: false,
       b: false
    }
}`

### 🏞 Expected result
1. Legend items of the categorical values, which were set to false, are unchecked.
2. Geometric elements corresponding to the categorical values, which were set to false, aren't displayed on the chart.
![dualaxes](https://user-images.githubusercontent.com/5092842/128891942-9308e5d7-480c-4464-a207-003604e922ce.jpg)

### 🚑 Any additional

* **G2Plot Version**: 3.2.29
* **Platform**: Windows 10, Chrome 92.0.4515.131

**Comment by kiradea** [comment]
提问，如何默认隐藏折线图？
