### ISSUE TITLE
代码 warning 是否去掉

### ISSUE THREAD

**Issue by hustcc** [antvis/g2plot#279]
几乎所有的 demo 都有 warning

![image](https://user-images.githubusercontent.com/7856674/69243125-55009180-0bdd-11ea-8d4f-a66491da807e.png)

**Comment by paleface001** [comment]
啥意思，warning是啥，来个截图

**Comment by hustcc** [comment]
图发不上去，好囧~~~跑单测的时候，控制台也会报这个 warning 的。

**Comment by hustcc** [comment]
确实是网站的 warning。
