### ISSUE TITLE
🐛 [BUG]g2plot 堆叠和分组条形图，colorField 为数值类型时（连续型图例），提示框内容返回不完整

### ISSUE THREAD

**Issue by rabbit-tian** [antvis/G2Plot#2790]
### 🐛 Bug description [Please make everyone to understand it]
复现: https://codesandbox.io/s/cgemo?file=/index.ts

![image](https://user-images.githubusercontent.com/26690191/129293375-7259dfd1-a36d-46fe-b3b1-9c4fda8c0c26.png)

* **G2Plot Version**: 2.3.29
* **Platform**: g2plot

**Comment by rabbit-tian** [comment]
@visiky

**Comment by visiky** [comment]
Duplicate with: #2601
