### ISSUE TITLE
🐛 [BUG]tooltip-showMarkers not work

### ISSUE THREAD

**Issue by leewhite97** [antvis/G2Plot#2794]
### 🐛 Bug description [Please make everyone to understand it]
tooltip组件，showMarkers配置不生效

### 💻 Link to minimal reproduction
官网示例里有个现成的
[https://g2plot.antv.vision/zh/examples/line/basic#line-point-style](url)

### 🏞 Expected result
tooltip marker不渲染

### 🚑 Any additional [like screenshots]

* **G2Plot Version**:2.3.29
* **Platform**:chrome

**Comment by visiky** [comment]
![image](https://user-images.githubusercontent.com/15646325/129466462-70d7fcc3-48c2-4199-8757-b3d91dff5a1f.png)


![image](https://user-images.githubusercontent.com/15646325/129466471-81eed563-02e6-4ad6-bb69-904eeb0be9b5.png)

**Comment by leewhite97** [comment]
好吧，谢谢。原来是图表上的标记，我以为是浮窗上的
