### ISSUE TITLE
🐛 [BUG] 桑基图，交互，单选 - 表现的是多选的行为

### ISSUE THREAD

**Issue by ntscshen** [antvis/G2Plot#2796]
桑基图，交互，单选图表 - 表现的是多选的行为 { type: "element-single-selected", enable: true }
element-selected 和 element-single-selected，点击效果一致。
Link: https://codesandbox.io/s/sad-keldysh-wofni?file=/index.js:1026-1076

**Comment by ntscshen** [comment]
g2可以使用chart， g2plot怎么搞？

**Comment by visiky** [comment]
使用 plot.chart 就行了

**Comment by ai-qing-hai** [comment]
通常 charts 是通过 生成 geometry 来绘制的， 而桑基图 先是 生成两个 view ，然后进行的绘制。  要向正确的 进行 单选， 需要分别对两个 views 添加,  现在 g2plot 还没有对 interations 进行了 view 对适配， 如果想要在当前 使用 element-single-selected的交互， 需要 分别对 views[0] edgeView边缘 和 views[1] nodeView 节点 进行添加， 两个交互并没有互通， 可能之后会进行g2plot 适配。

sankey.chart.views[0].interaction('element-single-selected')
sankey.chart.views[1].interaction('element-single-selected')

**Comment by ai-qing-hai** [comment]
![image](https://user-images.githubusercontent.com/65594180/150309588-d72f2faf-e8f0-4495-a14c-0ba1d9205d9a.png)
@ntscshen
