### ISSUE TITLE
🐛 [BUG] label 无 position 时 style 设置无效

### ISSUE THREAD

**Issue by lxfu1** [antvis/G2Plot#2822]
### 🐛 Bug description [Please make everyone to understand it]

```ts
import { Column } from '@antv/g2plot';

const data = [
  { type: '1-3秒', value: 0.16 },
  { type: '4-10秒', value: 0.125 },
  { type: '11-30秒', value: 0.24 },
  { type: '31-60秒', value: 0.19 },
  { type: '1-3分', value: 0.22 },
  { type: '3-10分', value: 0.05 },
  { type: '10-30分', value: 0.01 },
  { type: '30+分', value: 0.015 },
];

const columnPlot = new Column('container', {
  data,
  xField: 'type',
  yField: 'value',
  label: {
    //position: 'middle',
    style: {
      fill: 'red'
    },
  },
});

columnPlot.render();

```

![image](https://user-images.githubusercontent.com/31396322/131318236-c2f2019b-ce59-46ef-b83b-b02186d3e70f.png)

### 🚑 Any additional [like screenshots]

* **G2Plot Version**: latest
* **Platform**:  macOS

**Comment by visiky** [comment]
`label: { layout: [] }`

**Comment by visiky** [comment]
![image](https://user-images.githubusercontent.com/15646325/132149056-6bea0d3f-4407-462f-8102-c65224e340c4.png)

没有设置 position，内部会自动给 label 添加 adjust-color 布局，导致 style.fill 设置失效
