### ISSUE TITLE
🐛 [BUG]PC端正常，移动端所有事件不触发

### ISSUE THREAD

**Issue by xu-Aurora** [antvis/G2Plot#2827]
### 💻 Link to minimal reproduction

Please provide a link by forking these links [g2plot](https://codesandbox.io/s/g2plot-reproduction-template-gyej1) or GitHub repo. What is a minimal reproduction, and why is it required?

### 🚑 Any additional [like screenshots]

* **G2Plot Version**: 2.3.32
* **Platform**: chrome 92.0.4515.159

切换成chrome手机端模拟器，所有的点击事件不触发，切换回pc，所有事件正常触发？请问这是不兼容移动端嘛？

**Comment by visiky** [comment]
兼容的
