### ISSUE TITLE
🐛堆积面积图-不同指标数值差距较大时，较小的指标区域无法显示

### ISSUE THREAD

**Issue by LazyJoke** [antvis/G2Plot#2833]
### 🐛 Bug description
不同指标数值差距较大时，较小的指标区域无法显示

### 💻 Link to minimal reproduction
https://codesandbox.io/embed/charming-black-egd0y?fontsize=14&hidenavigation=1&theme=dark

### 🚑 Any additional [like screenshots]

* **G2Plot Version**:
* **Platform**:

**Comment by visiky** [comment]
因为堆叠面积图是堆叠的，所以在这个 case 中，数据小的会堆叠在上面，造成被遮挡隐藏的现象。可以考虑排序下，如下：
![image](https://user-images.githubusercontent.com/15646325/136305045-0c4d7a29-b1e5-45fe-8822-dbc846e31040.png)

https://codesandbox.io/s/suspicious-mclaren-sbwvm
