### ISSUE TITLE
demo中tooltip样式不对

### ISSUE THREAD

**Issue by zqlu** [antvis/g2plot#284]
![image](https://user-images.githubusercontent.com/1142242/69302320-31c4f900-0c54-11ea-93c1-07da95c91d6d.png)

本地site打包问题？

**Comment by zqlu** [comment]
试了下本地是ok的

**Comment by paleface001** [comment]
拉最新的master重新tnpm install一下，components更新之后应该没问题了

**Comment by paleface001** [comment]
> 试了下本地是ok的

那清一下缓存试试？

**Comment by hustcc** [comment]
@paleface001 确实是依赖的 g2 资源不对，刚那个闪烁的问题，我本地启动就不会出问题，但是远程上的就是有问题。闪烁问题和 tooltip 一起修复的。

建议 gh-pages 使用 action 在远程去打包和 上传。@afc163 看看是否可行？
