### ISSUE TITLE
🤔 scrollbar start 不生效

### ISSUE THREAD

**Issue by Mr-sandaman** [antvis/G2Plot#2845]
### 🐛 Question description [Please make everyone to understand it]
scrollbar start 不生效

### 💻 Link to minimal reproduction
<img width="585" alt="截屏2021-09-12 下午7 02 08" src="https://user-images.githubusercontent.com/26588526/132985114-934afaeb-c6f7-40ac-b941-48ca3f5348ee.png">

### 🏞 Expected result

滚动条在最右边

### 🚑 Any additional [like screenshots]

* **G2Plot Version**:
* **Platform**:

**Comment by Aarebecca** [comment]
现版本未提供scrollbar的初始位置配置，可以使用下列来实现相同效果
`column.chart.getController('scrollbar').scrollbar.component.updateThumbOffset(Infinity)`

参考[带滚动条的条形图](https://g2plot.antv.vision/zh/examples/bar/basic#scrollbar)
```js
import { Bar } from '@antv/g2plot';

fetch('https://gw.alipayobjects.com/os/bmw-prod/be63e0a2-d2be-4c45-97fd-c00f752a66d4.json')
  .then((res) => res.json())
  .then((data) => {
    const column = new Bar('container', {
      data,
      yField: '城市',
      xField: '销售额',
      yAxis: {
        label: {
          autoRotate: false,
        },
      },
      scrollbar: {
        type: 'vertical',
      },
    });

    column.render();
    // 将滚动条拖动至末尾
    column.chart.getController('scrollbar').scrollbar.component.updateThumbOffset(Infinity)
  });

```

**Comment by Aarebecca** [comment]
也可使用下列方法手动出发滚动事件，后续会提供API。`ratio`是范围为0-1的小数
`
column.chart.getController('scrollbar').onValueChange({ ratio: 1 })
`
