### ISSUE TITLE
迷你进度条图   color跟progressStyle有冲突

### ISSUE THREAD

**Issue by jiaicon** [antvis/G2Plot#2846]
我使用progressStyle添加颜色，color属性就被覆盖了，无法定义进度条百分比的颜色。
![image](https://user-images.githubusercontent.com/34124517/133022237-324ca57e-5c9d-4dfe-9b17-9eed574ca474.png)
![image](https://user-images.githubusercontent.com/34124517/133022248-8c4a6e11-b6bc-4324-bb17-4e35545b4ca4.png)

**Comment by Aarebecca** [comment]
暂时先不在progressStyle中使用fill属性，该属性会同时作用于百分比和背景部分。

**Comment by Aarebecca** [comment]
直接设置progressStyle会同时作用于百分比和背景部分，可通过回调方法来分别设置两部分样式：
```ts
progressStyle: ({ type }) => {
    if (type === 'current') {
      return {
        fill: 'red',
        fillOpacity: 1
      }
    }
    return {
      // 背景部分样式
    }
  }
```

**Comment by Aarebecca** [comment]
后续会完善文档
