### ISSUE TITLE
🐛 [BUG]： 折线图，存在 color 回调的时候，slider 滚动轴，对 axis 不起效果。

### ISSUE THREAD

**Issue by ai-qing-hai** [antvis/G2Plot#2847]
### 📷 Step to reproduce
`没有color回调`
![image](https://user-images.githubusercontent.com/65594180/133047978-aa9a354b-0bcb-4257-8bce-3c1f7d8175d0.png)
`color回调`
![image](https://user-images.githubusercontent.com/65594180/133048061-c604695a-cc48-480e-8cc6-77042e95d6f2.png)

* **G2Plot Version**: 2.3.33

**Comment by BodhiHu** [comment]
Is there a way to fix this ?
