### ISSUE TITLE
请问Y坐标的刻度如何保证是整数，不要有小数

### ISSUE THREAD

**Issue by zaki1991** [antvis/G2Plot#2854]
请问Y坐标的刻度如何保证是整数，不要有小数，当数据只有1，2，3的时候，y坐标的刻度是0，0.5，1，1.5，2这样，怎么能使刻度至少是1呢

**Comment by visiky** [comment]
tickInterval 设置为 1看下

**Comment by zaki1991** [comment]
> tickInterval 设置为 1看下

设置为1，y轴的刻度就有点儿密集了，例如y轴为0,2,4,6,8,10,12，设置tickCount，超过部分又不显示了

**Comment by hustcc** [comment]
tick 算法是一个非常复杂的算法，要兼顾美观 + 数量，所以产出的标签是各种场景综合后相对不错的，如果对于自己的场景，知道一些数据范围等信息，可以使用 tickMethod 自定义算法，返回符合自己要求的标签。
