### ISSUE TITLE
🐛 [BUG] 我这里有一份测试数据，目前使用的分组柱状图和折线图分别有些问题，不清楚是组件问题还是数据问题

### ISSUE THREAD

**Issue by Ashhhhhh520** [antvis/G2Plot#2858]
数据json
[DataJson.txt](https://github.com/antvis/G2Plot/files/7182442/DataJson.txt)

1.分组柱状图
问题：全部显示列时，共52列，会出现无法选中第52列；鼠标位置和悬浮数据窗位置不匹配问题，这个问题在blazor框架上比较明显，在g2plot官网的测试页面上不明显...

配置：
  xField: 'Week',
  yField: 'TotalRepairTime',
  seriesField: 'Year',

2.带缩略轴的折线  ，拷其中Year:2019的数据出来测试就好
问题：轴选中1-9时， Week1和2的数据在同一列上， 轴选中2-9时，图像就出现bug了

配置：
xField: 'Week',
yField: 'TotalRepairTime',

![image](https://user-images.githubusercontent.com/31700716/133721522-5d3fdb7d-8869-443f-a32b-984005d3cee9.png)
----
![image](https://user-images.githubusercontent.com/31700716/133721188-ef76e32d-3312-41ee-9027-9aec5dba9a47.png)

**Comment by Ashhhhhh520** [comment]
貌似测试出问题所在了，object中包含额外的字段会导致这个问题。

**Comment by visiky** [comment]
您好，我也看了你给的数据了。目前折线图 x 轴不支持数值型字段，可以这么处理就行。Duplicate with #2620 

![image](https://user-images.githubusercontent.com/15646325/137564606-f1a998d7-e79e-44bf-9d8d-a213b47fd8ee.png)
