### ISSUE TITLE
🤔 [ build workflow] lint 和 build 可以换一个系统环境

### ISSUE THREAD

**Issue by lijinke666** [antvis/G2Plot#2862]
### 🐛 Question description [Please make everyone to understand it]

目前 lint, build, test 都是在 macos 环境跑, 但是超过5个会排队

![image](https://user-images.githubusercontent.com/21015895/133885296-7d880ba2-fe91-4ebb-b711-152864a3f683.png)

https://github.com/antvis/G2Plot/blob/5678aa44fa524d719e4c57635df314edc27948ad/.github/workflows/build.yml#L7

建议将  lint 和 build 换成 unbutu, test 由于有 jest-electron. 必须要 macos 环境才行

### 💻 Link to minimal reproduction

Please provide a link by forking these links [g2plot](https://codesandbox.io/s/g2plot-reproduction-template-gyej1) or GitHub repo. What is a minimal reproduction, and why is it required?

### 🚑 Any additional [like screenshots]

* **G2Plot Version**:
* **Platform**:

**Comment by visiky** [comment]
直接提交 pr 吧
