### ISSUE TITLE
🥰 [FEATURE] 折线图内置 brush 交互，支持自定义按钮、mask 等

### ISSUE THREAD

**Issue by Superzzw1994** [antvis/G2Plot#2865]
https://g2plot.antv.vision/zh/examples/case/statistical-scenario#trend

这个例子中的 指标卡趋势图 在框选后 会出现一个 <button>reset</button>
我想将 reset 替换为自己的文字，查阅文档后 将            interactions: [{ type: 'marker-active' }, { type: 'brush' }],
修改为           interactions: [{ type: 'marker-active' }, { type: 'brush', cfg: {button: {text: '重置'}} }],
并未生效，请问下如何才能正确设置button的文字呢？

**Comment by visiky** [comment]
> https://g2plot.antv.vision/zh/examples/case/statistical-scenario#trend
> 
> 这个例子中的 指标卡趋势图 在框选后 会出现一个 reset 我想将 reset 替换为自己的文字，查阅文档后 将 interactions: [{ type: 'marker-active' }, { type: 'brush' }], 修改为 interactions: [{ type: 'marker-active' }, { type: 'brush', cfg: {button: {text: '重置'}} }], 并未生效，请问下如何才能正确设置button的文字呢？

可以给一下你看到的文档地址吗？

**Comment by visiky** [comment]
我看了一下，目前一些精细化的内置交互操作（不需要用 interactions 的方式）还在开展中，目前内置 brush 交互的有：柱状图、条形图、散点图。如何看是否有内置的精细化交互操作，可以这么看 API 文档：

![image](https://user-images.githubusercontent.com/15646325/136728262-3d14aa05-2dd0-4f62-8afd-8bf1666778b9.png)
![image](https://user-images.githubusercontent.com/15646325/136728315-b4100311-9c8f-47cc-a1b6-1cc096c97d63.png)

如下：柱状图是可以生效的，另外：折线图我们会尽快补全上
![image](https://user-images.githubusercontent.com/15646325/136728162-e907b4f3-2a17-46a2-ad4d-9f5590a5c019.png)
