### ISSUE TITLE
🐛 [BUG]

### ISSUE THREAD

**Issue by donglegend** [antvis/G2Plot#2866]
### 条形图的缩略轴 文案是不是搞反了呢?

最新版就能看到，官网demo也是这样的，如下：

![image](https://user-images.githubusercontent.com/13144324/134303806-e81664c4-09bf-4b39-9e0a-b3c198fc899d.png)

**Comment by Aarebecca** [comment]
这个跟数据相关的，调整下数据顺序就正常了
![image](https://user-images.githubusercontent.com/25787943/134335559-54594015-0535-4375-b8f4-03b480c78b71.png)

**Comment by donglegend** [comment]
> 这个跟数据相关的，调整下数据顺序就正常了
> ![image](https://user-images.githubusercontent.com/25787943/134335559-54594015-0535-4375-b8f4-03b480c78b71.png)

感谢答复，但是效果不是这样的。比如数据就是一个升序的 数组，图形展示是没问题的，但是缩略轴slider的文案反转了。
我在G2 上试验了一个案例，G2是正常的，如下：
![image](https://user-images.githubusercontent.com/13144324/134336845-f4302dfe-79e8-4243-826b-215a2626a158.png)
![image](https://user-images.githubusercontent.com/13144324/134336866-b7d72913-3a84-4de0-996c-1776468a2bef.png)
希望看一下哈，感谢！
