### ISSUE TITLE
> 条形图缩略轴slider文案被反转了

### ISSUE THREAD

**Issue by donglegend** [antvis/G2Plot#2868]
> 这个跟数据相关的，调整下数据顺序就正常了
> ![image](https://user-images.githubusercontent.com/25787943/134335559-54594015-0535-4375-b8f4-03b480c78b71.png)

感谢答复，但是效果不是这样的，上面legend是反的，图形也不符合要求。比如数据就是一个升序的 数组，图形展示是没问题的，但是缩略轴slider的文案反转了，缩略的最小值不是 配置里数据的 第一个元素，被反转了。
我在G2 上试验了一个案例，G2是正常的，如下：
![image](https://user-images.githubusercontent.com/13144324/134336845-f4302dfe-79e8-4243-826b-215a2626a158.png)
![image](https://user-images.githubusercontent.com/13144324/134336866-b7d72913-3a84-4de0-996c-1776468a2bef.png)
希望看一下哈，感谢！

_Originally posted by @donglegend in https://github.com/antvis/G2Plot/issues/2866#issuecomment-924847354_

**Comment by Aarebecca** [comment]
G2Plot中目前不支持`coordinate`相关的API操作。在常规使用过程中，一般不会出现中`interval`图表使用`Slider`组件，非连续的数据使用图例就行了吧，缩略轴在这里并没有什么意义。

**Comment by Aarebecca** [comment]
后续会修改条形图的逻辑，适应这种情况

**Comment by donglegend** [comment]
收到，希望尽快修复哈，着急使用

**Comment by donglegend** [comment]
查了下你们的代码，知道slider被反转的原因了。你们为了让条形图符合直觉展示，对数据进行了transformBarData反转。
图形倒是符合需求了，但是 忽略了slider缩略轴数据被反转后的问题。
下面模拟了一下 重置数据反转影响的配置项，但是 这么改有点黑魔法感觉，不太合适。应该比较容易修复，希望尽快发版，感谢！
![image](https://user-images.githubusercontent.com/13144324/134644092-c8714d76-0a73-4a73-bd28-c24b3a7d3faf.png)
