### ISSUE TITLE
你们唯一的钉钉群人满了, 不考虑再开个2号群吗?

### ISSUE THREAD

**Issue by Eve-Sama** [antvis/G2Plot#2874]
### 💻 Link to minimal reproduction

Please provide a link by forking these links [g2plot](https://codesandbox.io/s/g2plot-reproduction-template-gyej1) or GitHub repo. What is a minimal reproduction, and why is it required?

### 🚑 Any additional [like screenshots]

* **G2Plot Version**:
* **Platform**:

**Comment by visiky** [comment]
看下二维码，有 2 群的
