### ISSUE TITLE
在父元素上存在scale的情况下，鼠标移到图表上，无法选中移上去的那个点，会发生错位现象，当设置pixelRatio等于父元素缩放的scale时也没有效果，麻烦帮忙看看这个问题

### ISSUE THREAD

**Issue by limyxi** [antvis/G2Plot#2879]
g2plot版本为2.3.31   浏览器为chrome 83.0.4103.97
![image](https://user-images.githubusercontent.com/20531560/135009141-1d457fb6-d60a-4168-9284-be5d15da95c9.png)
![image](https://user-images.githubusercontent.com/20531560/135009210-4b4c3449-119c-40a4-b9b2-dadd1c9961de.png)
鼠标在红色框内，显示的确不是对应坐标点的数据，存在祖先元素是scale缩放的情况，但是设置pixelRatio等于父元素缩放的scale时也没有效果，不知道是设置有问题，还是本来存在这个。
麻烦帮忙看看。
感谢！

**Comment by limyxi** [comment]
![image](https://user-images.githubusercontent.com/20531560/135014109-cf4001ef-cb8a-41ee-b2d6-0ea38e8a3fbd.png)
![image](https://user-images.githubusercontent.com/20531560/135014306-d2ed65c1-d27b-4797-968d-880422f8e1e0.png)
缩放比例是一样的

**Comment by limyxi** [comment]
发现可以用supportCSSTransform，pixelRatio是无效的，但是g2plot的文档却是没有这个属性的，在G3

**Comment by hustcc** [comment]
```ts
{
   supportCSSTransform: true,
}
```

**Comment by visiky** [comment]
我加一下文档
