### ISSUE TITLE
🐛 [BUG]双轴图数据只有一条时，应当居中展示

### ISSUE THREAD

**Issue by woshilaoda97** [antvis/G2Plot#2885]
### 🐛 Bug description 
双轴图数据量少是应当和单轴图保持一致居中展示

### 📷 Step to reproduce
将双轴图 data 数量减至一条即可。

### 🏞 Expected result
目前如果只有一条数据双轴图的点会在最左边，期望和单轴图单轴图效果一致居中展示

* **G2Plot Version**: @latest

**Comment by visiky** [comment]
![image](https://user-images.githubusercontent.com/15646325/136348423-f8132590-9d0a-44e3-b9c0-b1e131f3055e.png)
