### ISSUE TITLE
🐛 [BUG] gl-matrix模块 文件路径更改导致运行项目打包时报引用路径错误

### ISSUE THREAD

**Issue by Wzhex** [antvis/G2Plot#2889]
![image](https://user-images.githubusercontent.com/13358425/135953401-be366285-56fc-41b9-9bcf-9f556e85afb0.png)
![gl-matrix-directory](https://user-images.githubusercontent.com/13358425/135953554-b8f36aa2-4622-4e5e-bc44-93489cabd4d2.png)

**Comment by n7best** [comment]
related https://github.com/toji/gl-matrix/issues/439
