### ISSUE TITLE
🐛 [BUG] g2plot 2.x 箱型图 值标签对齐 和 meta影响 异常值的问题

### ISSUE THREAD

**Issue by rabbit-tian** [antvis/G2Plot#2912]
### 🐛 Bug description [Please make everyone to understand it]
1. 值标签 label，position不生效，使用 formatter 后，位置从顶部移到了随机位置
2. 使用meta后，异常值位置不居中了，发生偏移
复现地址：https://codesandbox.io/s/27u7v?file=/index.ts
对比图片：

- 不加 formatter 和 meta
![image](https://user-images.githubusercontent.com/26690191/136777755-3c469348-19eb-4931-a80c-3031f522f10c.png)

- 加 formatter 和 meta
![image](https://user-images.githubusercontent.com/26690191/136777798-057e74f8-cffe-4fd2-9eb9-c7914a47c763.png)

* **G2Plot Version**: 2.3.36
* **Platform**: g2plot 2.x

**Comment by visiky** [comment]
问题1. label position 只对柱、条形图生效 
![image](https://user-images.githubusercontent.com/15646325/136916008-97ae741e-4498-41fb-b8c9-19210d425782.png)
