### ISSUE TITLE
韦恩图逻辑问题

### ISSUE THREAD

**Issue by pxg950110** [antvis/G2Plot#2918]
Polt韦恩图例如data1 data2  形成2个数据集的韦恩交集图  A AB  B代表含义的问题，正常AB代表data1和data2的交集  A代表data1数据量-AB,B代表data2-AB,在官网图示上代表A 代表data1  B代表data2对韦恩图的操作有问题

**Comment by visiky** [comment]
maybe will be resolved by #2911 #2909

**Comment by pxg950110** [comment]
>>> c = venn3_circles(subsets=[set([1,2]), set([2,3,4,5]), set([4,5,6,7,8,9,10,11])])
    '''
    # Prepare parameters
    if isinstance(subsets, dict):
        subsets = [subsets.get(t, 0) for t in ['100', '010', '110', '001', '101', '011', '111']]
只是python的韦恩图交互逻辑，在官网提供的  data: [
    { sets: ['A'], size: 12, label: 'A' },
    { sets: ['B'], size: 12, label: 'B' },
    { sets: ['C'], size: 12, label: 'C' },
    { sets: ['A', 'B'], size: 2, label: 'A&B' },
    { sets: ['A', 'C'], size: 2, label: 'A&C' },
    { sets: ['B', 'C'], size: 2, label: 'B&C' },
    { sets: ['A', 'B', 'C'], size: 1 },
  ]中看示例 A代表了某个队列的数量，在交互中需要选择只在A不在B C中的数据，这个时候g2plot可以实现吗？python中'100'这个label代表了只在A队列的数据，如果有这种可交互的请帮忙一下，谢谢
