### ISSUE TITLE
双轴图如何默认显示最后一组数据的 Tooltip?🤔 [QUESTION]

### ISSUE THREAD

**Issue by LazyJoke** [antvis/G2Plot#2920]
### 💻 Link to minimal reproduction

Please provide a link by forking these links [g2plot](https://codesandbox.io/s/g2plot-reproduction-template-gyej1) or GitHub repo. What is a minimal reproduction, and why is it required?

### 🚑 Any additional [like screenshots]

* **G2Plot Version**:
* **Platform**:

**Comment by visiky** [comment]
目前没有直接的 api 提供，可以拿到最后一组数据的对应的 shape 位置，然后调用 showTooltip 触发默认行为，如下：
```ts
// 如果左轴是折线
const x = dualAxes.chart.views[0].getElements()[0].shape.getBBox().maxX;
dualAxes.chart.showTooltip({ x, y: 0 });

// 如果右轴是折线
const x = dualAxes.chart.views[1].getElements()[0].shape.getBBox().maxX;
dualAxes.chart.showTooltip({ x, y: 0 });

// 如果左轴是柱状图
const elements = dualAxes.chart.views[0].getElements();
const lastBox = elements[elements.length - 1].shape.getBBox();
const x = lastBox.x+lastBox.width/2;
dualAxes.chart.showTooltip({ x, y: 0 });
```

**Comment by LazyJoke** [comment]
非常感谢您的耐心解答

> 目前没有直接的 api 提供，可以拿到最后一组数据的对应的 shape 位置，然后调用 showTooltip 触发默认行为，如下：
> 
> ```ts
> // 如果左轴是折线
> const x = dualAxes.chart.views[0].getElements()[0].shape.getBBox().maxX;
> dualAxes.chart.showTooltip({ x, y: 0 });
> 
> // 如果右轴是折线
> const x = dualAxes.chart.views[1].getElements()[0].shape.getBBox().maxX;
> dualAxes.chart.showTooltip({ x, y: 0 });
> 
> // 如果左轴是柱状图
> const elements = dualAxes.chart.views[0].getElements();
> const lastBox = elements[elements.length - 1].shape.getBBox();
> const x = lastBox.x+lastBox.width/2;
> dualAxes.chart.showTooltip({ x, y: 0 });
> ```

非常感谢您的耐心解答
