### ISSUE TITLE
Bar/GroupBar的数据为啥要reverse

### ISSUE THREAD

**Issue by Jeffy2012** [antvis/G2Plot#293]

**Comment by paleface001** [comment]
@zqlu

**Comment by zqlu** [comment]
是为了数据顺序看起来是从上往下的，同时在配置了垂直滚动条的是在，也是和滚动条从上往下滚动方向一致的

**Comment by Jeffy2012** [comment]
但是 percentage-stack-bar和StackBar没有reverse

**Comment by zqlu** [comment]
> 但是 percentage-stack-bar和StackBar没有reverse

stackBar是有的，percentage是漏掉了

**Comment by paleface001** [comment]
percentage有岂不是很奇怪

**Comment by zqlu** [comment]
![image](https://user-images.githubusercontent.com/1142242/69519669-90acaa00-0f95-11ea-997f-6c781dadff9b.png)

这个demo，如有有的话，就1950在上方，2050在下方
