### ISSUE TITLE
GroupBar 的legend上下关系与实际渲染的不一样

### ISSUE THREAD

**Issue by Jeffy2012** [antvis/G2Plot#294]
![image](https://user-images.githubusercontent.com/2225478/69516837-e8471780-0f8d-11ea-9fca-8ea9eb49f602.png)

**Comment by paleface001** [comment]
我来定位一下吧，感觉是3.6.x components的绘制问题

**Comment by zqlu** [comment]
这个因为reserve的data，可能需要把groupField的顺序也配置下，在groupBar里面默认加上？ 

![image](https://user-images.githubusercontent.com/1142242/69517624-4117af80-0f90-11ea-9f8b-f3284a4ae232.png)

**Comment by paleface001** [comment]
> 这个因为reverse的data，可能需要把groupField的顺序也配置下，在groupBar里面默认加上？
> 
> ![image](https://user-images.githubusercontent.com/1142242/69517624-4117af80-0f90-11ea-9f8b-f3284a4ae232.png)

找道理来说reverse data不应该影响分类顺序啊

**Comment by paleface001** [comment]
fixed in #410
