### ISSUE TITLE
🤔 [求助] 1.x版本，每个配置有visible属性，2.x版本是去掉了吗？

### ISSUE THREAD

**Issue by jiaicon** [antvis/G2Plot#2945]
### 💻 demo地址

https://codesandbox.io/s/sleepy-chihiro-omkdw?file=/index.ts

### 🚑 如图：
![image](https://user-images.githubusercontent.com/34124517/139012831-a18bdc47-8e3a-4bcd-83f8-61373a687ba1.png)
![image](https://user-images.githubusercontent.com/34124517/139012772-abb1d545-fdd5-46ae-aa1f-7546c217ef55.png)

* **G2Plot Version**:1.x
* **Platform**:windows

**Comment by visiky** [comment]
> 是否支持自动转化呢，因为对象的层级可能比较深。

暂时没有这个打算
