### ISSUE TITLE
🤔 [QUESTION] 请问如何设置 Bar 图的Label组件的文字颜色和位置？

### ISSUE THREAD

**Issue by Ashhhhhh520** [antvis/G2Plot#2949]
### 🐛 Question description [Please make everyone to understand it]
 请问如何设置 Bar 图的Label组件的文字颜色？
### 💻 Link to minimal reproduction
  label:{
    style:{
      fill:'red',
      fontSize:32,
      color:'red'
    },
    type:'outer'
  }
该配置可以设置文字大小，无法设置文字颜色， 添加type配置会提示 wn(...) is not a constructor
Please provide a link by forking these links [g2plot](https://codesandbox.io/s/g2plot-reproduction-template-gyej1) or GitHub repo. What is a minimal reproduction, and why is it required?
https://antv-g2plot.gitee.io/zh/examples/bar/basic#basic

### 🏞 Expected result
能够跟其他图一样可以设置文字颜色
### 🚑 Any additional [like screenshots]

* **G2Plot Version**:
* **Platform**:

**Comment by visiky** [comment]
条形图内置了label 布局，可能会影响颜色设置（不过只会影响 inner-label 才对）

![image](https://user-images.githubusercontent.com/15646325/145924868-b239c53f-c71b-4299-8a52-0b6699bb9e50.png)

如果想要完全自控，可以关闭 `type: "adjust-color"` 的 label 布局, 选取自己需要的
```ts
label: {
   layout: [
       { type: 'interval-adjust-position' },
       { type: 'interval-hide-overlap' },
    //  { type: 'adjust-color' },
       { type: 'limit-in-plot', cfg: { action: 'hide' } },
   ]
}
```

**Comment by visiky** [comment]
如果还不能解决的话，可以重新开一个 issue 给一下复现地址
