### ISSUE TITLE
g2plot 交互 element-active 黑边能不能样式控制颜色

### ISSUE THREAD

**Issue by kaivin** [antvis/G2Plot#2955]
### 💻 https://antv-g2plot.gitee.io/zh/examples/pie/donut#basic

![D59E1772-1122-43d8-91AB-E6DE0ED3F00A](https://user-images.githubusercontent.com/21193621/139812598-6391c3c7-7de5-4ab5-86db-682fa70ed39a.png)

* **G2Plot Version**:
* **Platform**:

**Comment by visiky** [comment]
相关示例：https://g2plot.antv.vision/zh/examples/general/state#custom-state-style

状态量：`default`, `active`, `inactive`, `selected`

**Comment by kaivin** [comment]
@visiky 谢谢~ 还是我文档读的不够透~
