### ISSUE TITLE
🐛 [BUG]

### ISSUE THREAD

**Issue by ajaxpost** [antvis/G2Plot#2966]
### 不能运行
WARNING in ./node_modules/@antv/component/esm/util/label.js 71:27-42
export 'getEllipsisText' (imported as 'getEllipsisText') was not found in '@antv/util' (possible exports: Cache, assign, augment, clamp, clearAnimationFrame, clone, contains, debounce, deepMix, difference, each, endsWith, every, extend, filter, find, findIndex, firstValue, fixedBase, flatten, flattenDeep, forIn, get, getRange, getType, getWrapBehavior, group, groupBy, groupToMap, has, hasKey, hasValue, head, identity, includes, indexOf, isArguments, isArray, isArrayLike, isBoolean, isDate, isDecimal, isElement, isEmpty, isEqual, isEqualWith, isError, isEven, isFinite, isFunction, isInteger, isMatch, isNegative, isNil, isNull, isNumber, isNumberEqual, isObject, isObjectLike, isOdd, isPlainObject, isPositive, isPrototype, isRegExp, isString, isType, isUndefined, keys, last, lowerCase, lowerFirst, map, mapValues, max, maxBy, memoize, min, minBy, mix, mod, noop, number2color, omit, parseRadius, pick, pull, pullAt, reduce, remove, requestAnimationFrame, set, size, some, sortBy, startsWith, substitute, throttle, toArray, toDegree, toInteger, toRadian, toString, union, uniq, uniqueId, upperCase, upperFirst, values, valuesOfKey, wrapBehavior)

**Comment by hustcc** [comment]
删除一下 lock，然后重装依赖就可以。
