### ISSUE TITLE
🥰 [FEATURE]希望Pie的Tooltip添加类似Label的percentage的数据

### ISSUE THREAD

**Issue by qiujie8092916** [antvis/G2Plot#2975]
### 🥰 Features description [Please make everyone to understand it]
Tooltip可以定义content，里面暴露了数据，但是没有暴露百分比

### 🏞 What problem does this feature solve
Label暴露百分比`percentage`，但在页面比较紧凑的时候，Label的数据可能展示不完整（...省略），这样会导致看不见百分比，这个时候，希望如果鼠标移上去，出现Tooltip时，可以能将百分比展示出来

### 🧐 What does the proposed API look like
暂无

### 🚑 Any additional [like screenshots]
![image](https://user-images.githubusercontent.com/18651667/141614378-b983c34d-230b-45ce-b559-594956d1e4f4.png)
![image](https://user-images.githubusercontent.com/18651667/141614414-d0e3c5e1-dd8c-429c-9c5e-9f8c515f8e1a.png)
![image](https://user-images.githubusercontent.com/18651667/141614489-8970b0f2-69f3-4eb1-8db9-5cf3883726df.png)

**Comment by visiky** [comment]
这个问题，其实可以在业务层上自己计算下百分比，把饼图的数据处理如下，然后利用 tooltip 的 customItems 或者 formatter、customContent 去处理就行了
```ts
const data = [
   { type: '分类一', value: 10, percentage: 0.1 },
   { type: '分类二', value: 90, percentage: 0.9 },
]
```

**Comment by qiujie8092916** [comment]
> 这个问题，其实可以在业务层上自己计算下百分比，把饼图的数据处理如下，然后利用 tooltip 的 customItems 或者 formatter、customContent 去处理就行了
> 
> ```ts
> const data = [
>    { type: '分类一', value: 10, percentage: 0.1 },
>    { type: '分类二', value: 90, percentage: 0.9 },
> ]
> ```

Label里的percentage值是会跟随右侧激活的legend动态计算，而单纯从业务层计算出来的百分比传入data里，是固定而不是动态的
