### ISSUE TITLE
🤔 [QUESTION] 生成折线图时由于线条过多，除了几个重点关注的数据线显示外其余的都隐藏，隐藏的可以通过点击图例显示

### ISSUE THREAD

**Issue by huadong-guo** [antvis/G2Plot#2982]
生成折线图时由于线条过多，除了几个重点关注的数据线显示外其余的都隐藏，隐藏的可以通过点击图例显示。
尝试过element的changeVisible，可是这个离需求还有点距离，请问还有其他的方法吗？

**Comment by hustcc** [comment]
默认只显示其中几个图例是嘛？

**Comment by huadong-guo** [comment]
> 默认只显示其中几个图例是嘛？

嗯嗯，是的。但是图例要显示，然后点击图例的时候可以显示相应的折线。请问有什么好的解决方法吗？我的那个方法，隐藏的折线首次显示时要点两下才可以

**Comment by visiky** [comment]
https://g2plot.antv.vision/zh/examples/component/legend#legend-focus

**Comment by huadong-guo** [comment]
> https://g2plot.antv.vision/zh/examples/component/legend#legend-focus

感谢感谢
