### ISSUE TITLE
🤔 [QUESTION] OR [BUG] Display seems wrong based on the data

### ISSUE THREAD

**Issue by quirynen** [antvis/G2Plot#2984]
Hello, I have been trying to use G2plot for a basic line graph.  I made some tests a while ago with the 1.28 version and it was working fine. I removed some config that became obsolete and tried the latest version but the display of the graph isn't the same and looks like something sketchy.
I guess I made a mistake but I can't see which one, any help would be very much appreciated.

Thanks in advance

Here is a link to the sandbox :  [https://codesandbox.io/s/szzhq?file=/index.ts](https://codesandbox.io/s/szzhq?file=/index.ts)

I found a screenshot of what it used to look like with the same data :
[https://ibb.co/H2MkfFj](https://ibb.co/H2MkfFj)
* **G2Plot Version**: 2.3.40 (latest)

**Comment by Shamann** [comment]
When you're using numbers as x-axis data, you should either pass them as a string type (please, consider year field in data of [this ](https://g2plot.antv.vision/en/examples/line/basic#line-point-style)example), or explicitly set x-axis type as linear. Here is a solution to your problem:
<https://codesandbox.io/s/flamboyant-roman-tbkj0?file=/index.ts>
