### ISSUE TITLE
饼图改变容器大小后，显示错乱🐛 [BUG]

### ISSUE THREAD

**Issue by MissLixf** [antvis/G2Plot#2988]
![image](https://user-images.githubusercontent.com/32625824/142612774-2cab781a-a434-46e1-9c13-0e0d20f7a23f.png)

### 🐛 Bug description [Please make everyone to understand it]

> Please provide a link by forking these links [G2Plot](https://codesandbox.io/s/g2plot-issue-template-gzfdq?file=/index.ts) or GitHub repo, a minimal reproduction.

* _Required_ **Link to minimal reproduction**:

### 🚑 Any additional [like screenshots]

* **G2Plot Version**:
* **Platform**:

**Comment by visiky** [comment]
@pearmini G2层看一下
