### ISSUE TITLE
🐛 [BUG]数据标签 - Label 鼠标悬浮不触发element-active交互

### ISSUE THREAD

**Issue by dovewine** [antvis/G2Plot#2999]
### 🐛 Bug description
如果colorField对应绑定的数据字段值中存在空格，当鼠标悬浮到Lable数据标签上时，不会触发元素的element-active交互。

### 📷 Step to reproduce
![image](https://user-images.githubusercontent.com/38154124/143763272-28350957-8113-4313-97dd-baa5a0cc4a81.png)

### 🏞 Expected result
![image](https://user-images.githubusercontent.com/38154124/143763369-4729b0ff-4a7e-47d4-9ba0-d3004c8c7753.png)

* **G2Plot Version**:2.3.39
* **Platform**:window10

**Comment by visiky** [comment]
目前 element-active 交互只监听 element 上的交互，解决方案：自定义交互，监听 label 事件，触发 element-active action。
自定义交互文档：https://g2plot.antv.vision/zh/docs/api/options/interactions#%E7%BB%84%E8%A3%85%E4%BA%A4%E4%BA%92
