### ISSUE TITLE
🥰 [FEATURE]雷达图支持自定义刻度

### ISSUE THREAD

**Issue by Eve-Sama** [antvis/G2Plot#3000]
### 🥰 Features description [Please make everyone to understand it]
![图片](https://user-images.githubusercontent.com/30228406/143820594-b5480796-98ae-4227-9c4f-100e8041a076.png)
条形图、柱状图等X、Y的刻度都是支持自定义的. 最重要的是大部分图表都支持了`meta.formatter`方法, 雷达图的这个刻度可以也支持到吗?

**Comment by visiky** [comment]
雷达图射线方向对应 yField 字段，meta 配置相应字段的元信息即可
这个不管用？

![image](https://user-images.githubusercontent.com/15646325/145705026-72d31702-4c5c-4350-a18c-43e90ea98f15.png)

**Comment by Eve-Sama** [comment]
感谢解答.
