### ISSUE TITLE
🤔 [QUESTION]Interface 'VennOptions' incorrectly extends interface 'Options'

### ISSUE THREAD

**Issue by wen2204** [antvis/G2Plot#3006]
### 🐛 Question description
I setup a demo project to test antv/g2plot in angular project.at first,I install @antv/g2plot": "^2.3.40" to the empty project,and then run ng serve-o command to build the project ,the g2plot comes out the error:Interface 'VennOptions' incorrectly extends interface 'Options'

中文描述操作步骤如下：
步骤1：ng new demo,创建一个angular demo空项目，创建后vs打开，build不报错；
步骤2：npm install @antv/g2plot --save，引用该库，build不报错；
步骤3：在app.component.ts中添加一句：import { Line } from '@antv/g2plot';build报错

Error: node_modules/@antv/g2plot/lib/plots/venn/types.d.ts:10:18 - error TS2430: Interface 'VennOptions' incorrectly extends interface 'Options'.
  Types of property 'color' are incompatible.
    Type 'string | string[] | ((datum: Datum, defaultColor: string) => string) | undefined' is not assignable to type 'ColorAttr | undefined'.
      Type '(datum: Datum, defaultColor: string) => string' is not assignable to type 'ColorAttr | undefined'.
        Type '(datum: Datum, defaultColor: string) => string' is not assignable to type '(datum: Datum, defaultColor?: string | undefined) => string'.
          Types of parameters 'defaultColor' and 'defaultColor' are incompatible.
            Type 'string | undefined' is not assignable to type 'string'.
              Type 'undefined' is not assignable to type 'string'.

### 💻 Link to minimal reproduction

Please provide a link by forking these links [g2plot](https://codesandbox.io/s/g2plot-reproduction-template-gyej1) or GitHub repo. What is a minimal reproduction, and why is it required?

### 🚑 Any additional [like screenshots]

* **G2Plot Version**:2.3.40
* **Platform**:Angular 12.2.13.
                      Node.js:16.13.1
                      typescript:4.5.2
                      npm version:7.6.3

**Comment by visiky** [comment]
VennOptions、DualAxesOptions 都是不完全继承 Options 的, 你这里没有使用 Venn 图，build 也会报这个错误吗？可以给一个在线 demo，帮你定位下？

**Comment by FOWind** [comment]
Same problem.
`VennOptions` ’s `color` should be `string | string[] | ((datum: Datum, defaultColor?: string) => string)` instead of `string | string[] | ((datum: Datum, defaultColor: string) => string);`

**Comment by FOWind** [comment]
![image](https://user-images.githubusercontent.com/13653453/145364451-d5d57ba9-9060-4dad-b94e-dfeda37f33be.png)

**Comment by FOWind** [comment]
https://github.com/antvis/G2Plot/pull/3015
