### ISSUE TITLE
tslib_es6["__spreadArray"] TypeError

### ISSUE THREAD

**Issue by hljwwyy123** [antvis/G2Plot#3007]
### 问题描述
本地构建访问的属性是 tslib_es6['d' /* __spreadArray */]
![image](https://user-images.githubusercontent.com/8967002/144816000-06adf083-3d37-42a8-8e20-80c3d0cd7f6a.png)

但是build之后 变成了tslib_es6['__spreadArray'] 访问不到该属性
![image](https://user-images.githubusercontent.com/8967002/144813260-19adc645-7690-498b-b192-a0a541452be0.png)
构建中的 Warning

![image](https://user-images.githubusercontent.com/8967002/145137096-3d469be2-11a5-44c5-84ef-04291decd539.png)

package.json
`typescript: 4.3.5`
`tslib@latest`
`import { Line, LineOptions } from '@antv/g2plot';`

### 🚑 Any additional [like screenshots]
* **G2Plot Version**: 2.3.40
* **Platform**: React 16.13.1

**Comment by visiky** [comment]
检查下是不是哪里的依赖安装不正确？

**Comment by hljwwyy123** [comment]
为啥closed？？ 根本没解问题啊，，antv 现在都这样么？
我也知道是哪里的依赖不正确，我要是知道 就不提issue了

**Comment by visiky** [comment]
> 为啥closed？？ 根本没解问题啊，，antv 现在都这样么？ 我也知道是哪里的依赖不正确，我要是知道 就不提issue了

那给您远程？

**Comment by hljwwyy123** [comment]
@lxfu1 已经尝试过安装最新的 tslib了，上面贴图了

**Comment by JackMeng1209** [comment]
我找到了问题所在！
text.js,start.js等文件引用的是antv项目中的package.json安装的tslib依赖，我通过看package.json发现使用的是2.0.0版本！
我进入到antv中的node_modules内发现tslib.js只有__spreadArrays没有__spreadArray。

此时我通过yarn add tslib发现package.json的内tslib版本是2.3.0。这个问题应该是antv插件的tslib版本过低导致的吧！

**Comment by JackMeng1209** [comment]
我找到了问题所在！
text.js,start.js等文件引用的是antv项目中的package.json安装的tslib依赖，我通过看package.json发现使用的是2.0.0版本！
我进入到antv中的node_modules内发现tslib.js只有__spreadArrays没有__spreadArray。

**Comment by JackMeng1209** [comment]
我也出现了该问题，我找到了我的问题所在！
text.js,start.js等文件引用的是antv项目中的package.json安装的tslib依赖，我通过看package.json发现使用的是2.0.0版本！
我进入到antv中的node_modules内发现tslib.js只有__spreadArrays没有__spreadArray。
此时我通过yarn add tslib发现package.json的内tslib版本是2.3.0。
后删除了yarn.lock和项目的node_modules重新yarn。问题就解决了。

**Comment by hljwwyy123** [comment]
@JackMeng1209 我这里没有 .lock文件，已经都清了。删除 node_modules 重装依赖都试过了

**Comment by hljwwyy123** [comment]
我自己找到问题的根本原因了！
是 tnpm 和 npm 工具链安装依赖、引用依赖的问题
蚂蚁都是使用tnpm作为工具链的，tnpm 安装依赖会安装多个版本的依赖如下图：
![image](https://user-images.githubusercontent.com/8967002/145348722-e425a6fd-d610-4ce4-bc8a-99d968c9ebd0.png)
然后在每个需要使用到 tslib 项目中的package.json 声明使用的tslib版本。
这是tnpm引用依赖的机制，我这边开始本地构建没问题是因为我也是使用的tnpm 安装的依赖，
但是云构建是使用的Npm作为工具链，而我的项目中又没有package.lock.json 所以tslib的版本就装混了

**Comment by visiky** [comment]
tnpm 有点不好用 🤔 可以用 `tnpm i --by=yarn` 改用 yarn 来处理这些奇奇怪怪的事情
