### ISSUE TITLE
🤔 [QUESTION] Label is hidden under bar serie

### ISSUE THREAD

**Issue by 1323** [antvis/G2Plot#3010]
### 🐛 Label is hidden under bar chart serie.

Hello, I have a problem with hiding the label under the Bar chart series, when the chart is inverted.

In order to reverse bar series of the chart, I use the `meta.range` property as in the attached example. Maybe there is a dedicated property for this? 

When I remove `yAxis.label.style.textAlign` property then problem not exists, but I want my labels to be aligned.

### 💻 Link to minimal reproduction

https://codesandbox.io/s/festive-wind-q3qeo?file=/index.ts

### 🏞 Expected result

I expect that label won't overlap, or could be ellipsed.

### 🚑 Any additional [like screenshots]

![image](https://user-images.githubusercontent.com/7734208/145029713-28268ee8-d72f-44a2-8203-7542200ac8c5.png)

* **G2Plot Version**:
2.3.40

* **Platform**:
Chrome 96.0.4664.4

**Comment by visiky** [comment]
first, the reason why axis-label is hidden under bar series is: axis is drawn at the backgroundGroup, and element(bar series) is drawn at the middleGroup, so the z-index of bar series is higher than axis-label
then, you can use `yAxis.verticalLimitLength` to limit the max-length of axis-label

![image](https://user-images.githubusercontent.com/15646325/145182709-b2ca12d3-1cd3-44fa-8dc0-329f01a11f08.png)

**Comment by 1323** [comment]
Great! This was the property I was searching for. Thank you for help
