### ISSUE TITLE
🤔 [QUESTION]图表 Y 轴 title 如何能在顶部水平显示

### ISSUE THREAD

**Issue by keuby** [antvis/G2Plot#3022]
### 🐛 Question description [Please make everyone to understand it]

如题，如何让 Y 轴 title 在顶部水平显示，能否通过配置支持。如果配置无法支持的话有什么思路？

![image](https://user-images.githubusercontent.com/32365592/145740910-3737a31e-db1a-45a2-858b-5db9a2519370.png)

* **G2Plot Version**: 2.3.40
* **Platform**: MacOS Big Sur 11.6

**Comment by visiky** [comment]
duplicate with: https://github.com/antvis/G2Plot/issues/2994

**Comment by Lron-boy** [comment]
楼主解决了吗
