### ISSUE TITLE
🤔 [QUESTION]请问折线图的滚动scrollbar不支持吗

### ISSUE THREAD

**Issue by wsw2000** [antvis/G2Plot#3028]
### 💻 Link to minimal reproduction

Please provide a link by forking these links [g2plot](https://codesandbox.io/s/g2plot-reproduction-template-gyej1) or GitHub repo. What is a minimal reproduction, and why is it required?

### 🚑 Any additional [like screenshots]

* **G2Plot Version**:
* **Platform**:

**Comment by visiky** [comment]
是的，暂时不支持

**Comment by wsw2000** [comment]
好的thanks
