### ISSUE TITLE
🐛 [BUG] 404，官方文档有空更新下啊

### ISSUE THREAD

**Issue by AttackXiaoJinJin** [antvis/G2Plot#3031]
### 🐛 Bug description [Please make everyone to understand it]

* https://g2plot.antv.vision/zh/docs/api/components/zh/examples/component/legend#legend-marker-customize

### 📷 Step to reproduce

![image](https://user-images.githubusercontent.com/26433572/146511275-4cf85af1-4f4a-43f5-8235-355277e423a6.png)

**Comment by AttackXiaoJinJin** [comment]
https://github.com/antvis/G2Plot/pull/2961/commits/b9ba033deec7ab0ff6c5976a9552cc2cbaf975b9

**Comment by AttackXiaoJinJin** [comment]
https://g2plot.antv.vision/zh/docs/api/options/tooltip

![image](https://user-images.githubusercontent.com/26433572/146705522-193c8b09-bc20-4ea2-8591-afb53ed5be12.png)

**Comment by visiky** [comment]
顺手提交 PR ？
