### ISSUE TITLE
🐛 [BUG]饼图（环型图）图例在有分页的情况下，文字头部被切掉显示不全

### ISSUE THREAD

**Issue by zaite** [antvis/G2Plot#3040]
![企业微信截图_20211222085630](https://user-images.githubusercontent.com/22079456/147017575-da10b00b-0406-4b63-a264-4c44973914b9.png)
![企业微信截图_20211222085707](https://user-images.githubusercontent.com/22079456/147017595-67a0d3ea-fa2a-4de2-9eb4-a5e3f2107737.png)

经测试，官网案例和本地都出现此问题。其他类型的图表图例分页未做测试

**Comment by visiky** [comment]
duplicate with https://github.com/antvis/G2Plot/issues/3088
