### ISSUE TITLE
🐛 [BUG]y轴传字符串，就显示有bug了

### ISSUE THREAD

**Issue by wsw2000** [antvis/G2Plot#3041]
![nqqyFCtYI5](https://user-images.githubusercontent.com/63382474/147071268-09a1235c-2603-422a-a18d-ea019e24b48c.png)

y轴传字符串，就显示有bug了

**Comment by visiky** [comment]
y 轴对应的应该是数字哦~ 业务上数据就应该保证下为 number 类型
