### ISSUE TITLE
🐛 [BUG] 日期类型字段meta内设置formatter后会自动转换成时间戳

### ISSUE THREAD

**Issue by Esorakouki** [antvis/G2Plot#3046]
### 🐛 Bug description [Please make everyone to understand it]

> Please provide a link by forking these links [G2Plot](https://codesandbox.io/s/g2plot-issue-template-gzfdq?file=/index.ts) or GitHub repo, a minimal reproduction.

* _Required_ **Link to minimal reproduction**:
https://riddle.alibaba-inc.com/riddles/573bc35b
### 🚑 Any additional [like screenshots]

* **G2Plot Version**:  latest
* **Platform**:

**Comment by visiky** [comment]
目前对时间字段会进行转换，为了避免，可以手动设置为 cat 类型:
```ts
meta: {
   date: { type: 'cat' }
}
```
