### ISSUE TITLE
折线图缩略轴改变区间后图表始终显示全集

### ISSUE THREAD

**Issue by sugerliu1995** [antvis/G2Plot#3050]
改变缩略轴的区间，折线有联动，但是不像之前那样仅展示区间值了

![image](https://user-images.githubusercontent.com/94675963/147340404-85033a37-16fc-41a5-8c2e-40f8626087f9.png)

import { Line, Datum, G2 } from '@antv/g2plot';
import Vue from 'vue';
import { formatNum } from '../model';
import Empty from '../empty/index.vue';
import Header from '../title/index.vue';

interface LinkSlotData {
  title: string;
  url: string;
  cover: string;
}

interface LinkSlot {
  title: string;
  data: LinkSlotData[];
}

enum CustomTooltip {
  Link = 'link',
  Default = 'default',
}

const Color = [
  '#5D78FF',
  '#66D7A7',
  '#708FB5',
  '#F29236',
  '#8B65F4',
  '#64C4F3',
  '#EB5795',
  '#F8D20D',
  '#3A92FF',
  '#A2DF5B',
];

export interface LineData {
  value: string;
  name: string;
  interval: string;
  linkSlot?: LinkSlot;
}

export default Vue.extend({
  name: 'LineChart',
  props: {
    data: Array as () => LineData[],
    height: {
      type: Number,
      default: () => 220,
    },
    day: {
      type: Number,
      default: () => 0,
    },
    emptyDesc: String,
    loading: {
      type: Boolean,
      default: () => false,
    },
    title: Array as () => string[],
    download: String,
    slider: {
      type: Boolean,
      default: () => false,
    },
    sliderStart: {
      type: Number,
      default: () => 0,
    },
    sliderEnd: {
      type: Number,
      default: () => 1,
    },
    customTooltip: {
      type: String as () => CustomTooltip,
      default: () => CustomTooltip.Default,
    },
  },
  components: {
    Empty,
    Header,
  },
  computed: {
    renderHeight(): string {
      return `height: ${this.height}px`;
    },
    nameLength(): string[] {
      const arr: string[] = [];
      this.data.forEach((val: LineData) => {
        if (arr.indexOf(val.name) === -1) {
          arr.push(val.name);
        }
      });
      return arr;
    },
    xLength(): string[] {
      const arr: string[] = [];
      this.data.forEach((val: LineData) => {
        if (arr.indexOf(val.interval) === -1) {
          arr.push(val.interval);
        }
      });
      return arr;
    },
    dayArray(): string[] {
      if (this.day) {
        const arr: string[] = [];
        this.xLength.forEach((val: string, index: number) => {
          if (this.xLength.length - (index + 1) < this.day) {
            arr.push(val);
          }
        });
        return arr;
      }
      return [];
    },
    yLength(): string[] {
      const arr: string[] = [];
      this.data.forEach((val: LineData) => {
        if (arr.indexOf(val.value) === -1) {
          arr.push(val.value);
        }
      });
      return arr;
    },
  },
  watch: {
    data: {
      deep: true,
      handler() {
        if (this.data.length && !this.loading) {
          this.$nextTick(() => {
            this.renderChart();
          });
        }
      },
    },
  },
  mounted() {
    if (this.data.length && !this.loading) {
      this.renderChart();
    }
  },

  methods: {
    downloadAction() {
      this.$emit('download');
    },
    findIndex(item: LineData, source: string[]) {
      let index = 0;
      for (let i = 0; i < source.length; i += 1) {
        if (item.name === source[i]) {
          index = i;
        }
      }
      return index;
    },

    renderChart() {
      const customTooltip = this.customTooltip as string;
      // 添加标记点动画
      G2.registerShape('point', 'breath-point', {
        draw(cfg, container) {
          const data = cfg.data as LineData;
          const point = { x: cfg.x as number, y: cfg.y as number };
          const group = container.addGroup();
          if (customTooltip === CustomTooltip.Link && data.linkSlot) {
            const decorator1 = group.addShape('circle', {
              attrs: {
                x: point.x,
                y: point.y,
                r: 5,
                fill: cfg.color,
                opacity: 0.5,
              },
            });
            const decorator2 = group.addShape('circle', {
              attrs: {
                x: point.x,
                y: point.y,
                r: 5,
                fill: cfg.color,
                opacity: 0.5,
              },
            });
            const decorator3 = group.addShape('circle', {
              attrs: {
                x: point.x,
                y: point.y,
                r: 5,
                fill: cfg.color,
                opacity: 0.5,
              },
            });
            decorator1.animate(
              {
                r: 10,
                opacity: 0,
              },
              {
                duration: 1800,
                easing: 'easeLinear',
                repeat: true,
              },
            );
            decorator2.animate(
              {
                r: 10,
                opacity: 0,
              },
              {
                duration: 1800,
                easing: 'easeLinear',
                repeat: true,
                delay: 600,
              },
            );
            decorator3.animate(
              {
                r: 10,
                opacity: 0,
              },
              {
                duration: 1800,
                easing: 'easeLinear',
                repeat: true,
                delay: 1200,
              },
            );
            group.addShape('circle', {
              attrs: {
                x: point.x,
                y: point.y,
                r: 3,
                fill: cfg.color,
                opacity: 0.7,
              },
            });
            group.addShape('circle', {
              attrs: {
                x: point.x,
                y: point.y,
                r: 0.75,
                fill: cfg.color,
              },
            });
          }
          return group;
        },
      });

      const el = this.$refs.line as HTMLDivElement;
      const area = new Line(el, {
        appendPadding: [10, 0, 0, 0],
        data: this.data,
        smooth: true,
        xField: 'interval',
        yField: 'value',
        seriesField: 'name',
        color: Color,
        legend: {
          position: 'bottom',
          offsetY: 10,
          itemHeight: 30,
        },
        autoFit: true,
        xAxis: {
          label: {
            style: (value) => {
              if (this.dayArray.indexOf(value) > -1) {
                return {
                  fill: '#5d78ff',
                };
              }
              return {
                fill: '#999',
              };
            },
            // formatter: (text, item, index) => {
            //   let str = '';
            //   if (this.xLength.length - (index + 1) < this.day) {
            //     str = `★${text}`;
            //   } else {
            //     str = `${text}`;
            //   }
            //   return str;
            // },
            rotate: this.xLength.length <= 14 ? 0 : 0.5,
            offset: 20,
          },
        },
        yAxis: {
          label: {
            formatter: (value) => formatNum(parseInt(value, 10)),
          },
        },
        slider: this.slider ? {
          start: this.sliderStart,
          end: this.sliderEnd,
          padding: [10, 20, 0, 0],
        } : undefined,
        lineStyle: (item: LineData) => {
          let index = 0;
          index = this.findIndex(item, this.nameLength);
          const color = Color[index];
          return {
            shadowColor: color,
            shadowBlur: 12,
            shadowOffsetX: 0,
            shadowOffsetY: 8,
            cursor: 'pointer',
            opacity: 0.8,
          };
        },
        point: {
          shape: 'breath-point',
        },
        tooltip: this.formatTooltip(),
        annotations: this.day ? [{
          type: 'region',
          start: (xScale: any) => {
            let x;
            if (this.slider) {
              const index = xScale.ticks.indexOf(this.dayArray[0]);
              if (index === -1) {
                x = 1;
              } else {
                x = index / xScale.ticks.length;
              }
            } else {
              x = (1 - this.day / this.xLength.length);
            }
            return [`${x * 100}%`, '0%'];
          },
          end: () => [`${1 * 100}%`, '100%'],
          style: {
            fill: '#5D78FF',
          },
        }] : undefined,
      });

      area.render();
      this.$nextTick(() => {
        this.$emit('onRendered');
      });
    },
    formatTooltip() {
      let tooltip;
      const that = this;
      function clickLinkSlot(value: LinkSlotData) {
        that.$emit('clickLinkSlot', value);
      }
      if (this.customTooltip === CustomTooltip.Link) {
        tooltip = {
          shared: false,
          enterable: true,
          customContent: (title: string, data: Datum) => {
            if (title && data && data[0].data) {
              if (data[0].data.linkSlot) {
                const point = data[0].data;
                const title = `<p style="font-size: 16px; color: #222;font-weight: bold;">${point.linkSlot.title}</p>
                <div style="background-color:${data[0].color};border-radius: 50%; width: 8px;height: 8px;display: inline-block;margin-right: 5px"></div><div style="margin-bottom: 10px;display: inline-block;">${data[0].data.name}: ${data[0].data.value}</div>`;
                let listItem = '';
                point.linkSlot.data.forEach((item: {
                  title: string;
                  url: string;
                  cover: string;
                }) => {
                  listItem += `<p style="overflow: hidden; text-overflow: ellipsis;white-space: nowrap;">
                  <img src=${item.cover} width="32" height="32" style="border: 1px solid rgba(93, 120, 255, 0.1);"/>
                  <a href=${item.url} style="line-height: 32px; font-size: 14px; color: #5d78ff; margin-left: 5px" onClick="${clickLinkSlot(item)}">${item.title}</a>
                  </p>`;
                });
                return `<div style="width: 220px;height: 210px;padding: 20px 10px;">${title}${listItem}</div>`;
              }
              return `<p style="margin-top: 10px">${title}</p><div style="background-color:${data[0].color};border-radius: 50%; width: 8px;height: 8px;display: inline-block;margin-right: 5px"></div><div style="margin-bottom: 10px;display: inline-block;">${data[0].data.name}: ${data[0].data.value}</div>`;
            }
            return '';
          },
        };
      } else {
        tooltip = {
          showMarkers: false,
        };
      }
      return tooltip;
    },
  },
});

**Comment by ntscshen** [comment]
#### 这发的是什么个东西，建议如下修改

1. 给出最小化代码实现
2. 给出线上地址（codesandbox）

> 参考如下地址修改： https://codesandbox.io/s/area-plot-state-lvvmk?file=/index.ts

**Comment by sugerliu1995** [comment]
问题已关闭，感谢



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: ntscshen ***@***.***&gt;
发送时间: 2021年12月28日 15:56
收件人: antvis/G2Plot ***@***.***&gt;
抄送: sugerliu1995 ***@***.***&gt;, State change ***@***.***&gt;
主题: Re: [antvis/G2Plot] 折线图缩略轴改变区间后图表始终显示全集 (Issue #3050)





 
这发的是什么个东西，建议如下修改
  
给出最小化代码实现 

给出线上地址（codesandbox） 
  
参考如下地址修改： https://codesandbox.io/s/area-plot-state-lvvmk?file=/index.ts
  
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
