### ISSUE TITLE
🐛 [BUG]国内镜像-图标示例，更多图表-旭日图，第一个跳转的路由有问题

### ISSUE THREAD

**Issue by Webming19** [antvis/G2Plot#3057]
### 🐛 Bug description [Please make everyone to understand it]

> Please provide a link by forking these links [G2Plot](https://codesandbox.io/s/g2plot-issue-template-gzfdq?file=/index.ts) or GitHub repo, a minimal reproduction.

* _Required_ **Link to minimal reproduction**:(https://antv-g2plot.gitee.io/zh/examples/gallery)

### 📷 Step to reproduce
图标示例页面-更多图表-旭日图，点击第一个图标，进去的永远是第二个

### 🚑 Any additional [like screenshots]

* **G2Plot Version**:2.4.1
* **Platform**:

**Comment by visiky** [comment]
@ai-qing-hai 估计是匹配路径的时候用了 match？或者还有一个原因，markdown 的限制数量导致后续的都匹配不到

![image](https://user-images.githubusercontent.com/15646325/147813039-13390500-c33d-4db9-8967-e3e042a8bbac.png)

**Comment by ai-qing-hai** [comment]
@Webming19  能否附上图表说明一下

**Comment by ai-qing-hai** [comment]
@Webming19  麻烦再看一下， 是否还有这个问题。
