### ISSUE TITLE
🤔 [自定义图例后，筛选功能失效]

### ISSUE THREAD

**Issue by deerLoves** [antvis/G2Plot#3058]
双折线图中自定义图例后，发现筛选功能无法使用
legend: {
        // 自定义图例
        custom: true,
        items: [
          {
            id: "value",
            name: "value",
            value: "value",
            marker: {
              symbol: "circle",
              style:{
                fill: "#FF2300"
              },
            },
          },
          {
            id: "count",
            name: "count",
            value: "count",
            marker: {
              symbol: "circle",
              style:{
                fill: "#2233B3"
              },
            },
          }
        ]
      },

**Comment by visiky** [comment]
自定义图例之后，需要自己手动去监听图例事件，进行处理

**Comment by deerLoves** [comment]
https://github.com/antvis/G2Plot/issues/3058#issuecomment-1002871248
好吧。。。。

**Comment by deerLoves** [comment]
> 自定义图例之后，需要自己手动去监听图例事件，进行处理

好吧。。。。
