### ISSUE TITLE
折线图怎么设置平滑曲线？

### ISSUE THREAD

**Issue by caoke** [antvis/G2Plot#306]

**Comment by paleface001** [comment]
设置`smooth`配置项为true即可，具体可以参考这个demo: https://g2plot.antv.vision/zh/examples/line/basic#line-smooth

**Comment by caoke** [comment]
> 设置`smooth`配置项为true即可，具体可以参考这个demo: https://g2plot.antv.vision/zh/examples/line/basi

**Comment by caoke** [comment]
> 设置`smooth`配置项为true即可，具体可以参考这个demo: https://g2plot.antv.vision/zh/examples/line/basic#line-smooth

感谢~，还想问下 legend可以设置其他类型吗？类似于G2中的marker属性
![image](https://user-images.githubusercontent.com/20351354/69705950-93440680-1131-11ea-8086-92e37a9b9791.png)

**Comment by paleface001** [comment]
> > 设置`smooth`配置项为true即可，具体可以参考这个demo: https://g2plot.antv.vision/zh/examples/line/basic#line-smooth
> 
> 感谢~，还想问下 legend可以设置其他类型吗？类似于G2中的marker属性
> ![image](https://user-images.githubusercontent.com/20351354/69705950-93440680-1131-11ea-8086-92e37a9b9791.png)

目前还没有开放，G2Plot作为一个上层封装的图表库应该开放多大的自由度，我们也在摸索，最终还是取决于用户的需求。欢迎多给我们输入。😊
