### ISSUE TITLE
🤔 [QUESTION]请问散点图支持滚动条嘛？

### ISSUE THREAD

**Issue by YuArtian** [antvis/G2Plot#3063]
### 🐛 Question description [Please make everyone to understand it]
写了
scrollbar: {
    type: ['horizontal'],
  },
貌似没有生效？x轴的有些刻度还是被省略了

### 💻 Link to minimal reproduction

Please provide a link by forking these links [g2plot](https://codesandbox.io/s/g2plot-reproduction-template-gyej1) or GitHub repo. What is a minimal reproduction, and why is it required?

### 🚑 Any additional [like screenshots]

* **G2Plot Version**:
* **Platform**:

**Comment by visiky** [comment]
scrollbar: {
type: 'horizontal', // 'vertical'
},
