### ISSUE TITLE
🤔 [QUESTION] pie 图表怎样使用showTooltip 自动显示第一项

### ISSUE THREAD

**Issue by tomieric** [antvis/G2Plot#3067]
### 💻 Link to minimal reproduction

Please provide a link by forking these links [g2plot](https://codesandbox.io/s/g2plot-reproduction-template-gyej1) or GitHub repo. What is a minimal reproduction, and why is it required?

### 🚑 Any additional [like screenshots]

* **G2Plot Version**:
* **Platform**:

```
const elements = this.pieInstance.chart.getElements()
const x = elements[0].shape.getBBox().maxX
this.pieInstance.chart.showTooltip({ x, y: 100 }) // pie图表不能生效
```

**Comment by visiky** [comment]
饼图是扇形，bbox是一个包围住这个扇形的规则矩形，所以要取中心点
```
x = (minX + maxX)/2
y = (minY + maxY)/2
```
