### ISSUE TITLE
y轴设置meta的max,min值，同时设置图例位置是top，图形和图例重叠🐛 [BUG]

### ISSUE THREAD

**Issue by lkxing** [antvis/G2Plot#3069]
### 🐛 Bug description [Please make everyone to understand it]

> Please provide a link by forking these links [G2Plot](https://codesandbox.io/s/g2plot-issue-template-gzfdq?file=/index.ts) or GitHub repo, a minimal reproduction.

* _Required_ **Link to minimal reproduction**:

### 🚑 Any additional [like screenshots]

* **G2Plot Version**:
* **Platform**:
![image](https://user-images.githubusercontent.com/43607327/148667867-d8da4abc-1ded-4d5e-83d1-35a288030119.png)

**Comment by ai-qing-hai** [comment]
@lkxing  
![image](https://user-images.githubusercontent.com/65594180/150754130-a6953eab-c229-49da-86ed-0dbe2cedc5b0.png)
 可以通过设置 超出隐藏来解决重叠的问题。
