### ISSUE TITLE
🐛 [BUG]分组柱状图，x轴只存在一个分组，y轴有多个数据时，鼠标移入图表的第一个和最后一个图无悬浮提示

### ISSUE THREAD

**Issue by kuzurec** [antvis/G2Plot#3070]
### 🐛 Bug description [Please make everyone to understand it]
分组柱状图，x轴只存在一个分组，y轴有多个数据时，鼠标移入图表的第一个和最后一个图无悬浮提示
> Please provide a link by forking these links [G2Plot](https://codesandbox.io/s/g2plot-issue-template-gzfdq?file=/index.ts) or GitHub repo, a minimal reproduction.
https://codesandbox.io/s/g2plot-issue-template-forked-3pwko

* _Required_ **Link to minimal reproduction**:

### 🚑 Any additional [like screenshots]
![image](https://user-images.githubusercontent.com/44342750/148713823-fa6e5672-7940-4215-aa37-a2dd6aae5182.png)

* **G2Plot Version**: 2.3.21
* **Platform**:

**Comment by visiky** [comment]
看起来，xScale 的定义域可能有问题。 invert 只能正常转 `[0.25, 0.75)` 区间的数据
![image](https://user-images.githubusercontent.com/15646325/150468534-04c03c01-057e-4fe2-9430-81ce568d29ee.png)

**Comment by yehoan** [comment]
你好想问一下 在分组柱状图里面怎么设置数字的分隔符   例如 百位分隔符   我试了自定义的 他只能显示一个

**Comment by kuzurec** [comment]
> 看起来，xScale 的定义域可能有问题。 invert 只能正常转 `[0.25, 0.75)` 区间的数据 ![image](https://user-images.githubusercontent.com/15646325/150468534-04c03c01-057e-4fe2-9430-81ce568d29ee.png)
> 
> ![image](https://user-images.githubusercontent.com/15646325/150468736-51393f83-25b4-4581-90cb-8fe3ad68aaff.png)
> 
> 所以第一个柱子，在某些场景下无法触发 tooltip

有解决办法吗

**Comment by kuzurec** [comment]
> 看起来，xScale 的定义域可能有问题。 invert 只能正常转 `[0.25, 0.75)` 区间的数据 ![image](https://user-images.githubusercontent.com/15646325/150468534-04c03c01-057e-4fe2-9430-81ce568d29ee.png)
> 
> ![image](https://user-images.githubusercontent.com/15646325/150468736-51393f83-25b4-4581-90cb-8fe3ad68aaff.png)
> 
> 所以第一个柱子，在某些场景下无法触发 tooltip

我试了下，设置columnWidthRatio为0.5就没问题了
