### ISSUE TITLE
🐛 [BUG] 在safari浏览器里正则报错

### ISSUE THREAD

**Issue by kongdemin** [antvis/G2Plot#3071]
![image](https://user-images.githubusercontent.com/34759731/148741655-9dd6f716-7a3e-4855-8f13-7a79b5f44bd3.png)

**Comment by visiky** [comment]
现在版本是？更新到最新版本看看？

**Comment by kongdemin** [comment]
被同学锁成了2.0.1。 最新版本可以。 锁版本的原因是最新版本的代码里编译后里面有es6代码 可否去除掉

**Comment by hustcc** [comment]
> 被同学锁成了2.0.1。 最新版本可以。 锁版本的原因是最新版本的代码里编译后里面有es6代码 可否去除掉

最新版本编译的 es6 代码是什么？我们看看更新下打包的配置。

**Comment by visiky** [comment]
webpack 配置下编译 node_modules 中一些依赖存在的 es6 代码即可
