### ISSUE TITLE
🤔 [QUESTION] 水波图的动画能配置关闭吗？

### ISSUE THREAD

**Issue by HaceraI** [antvis/G2Plot#3072]
水波图的荡漾动画有配置项能关闭吗？
只需要一个静态的水波图，不需要内部的荡漾动画.

尝试过以下几点，都失败了
1、将`renderer`设置为`svg`.
2、配置内增加`animation: false`.

**Comment by visiky** [comment]
目前不行，这个我来处理下

**Comment by HaceraI** [comment]
好的，感谢
