### ISSUE TITLE
🐛 [BUG]桑基图 自定义tooltip，无法区分是node节点还是流转的线条

### ISSUE THREAD

**Issue by zsq19941105** [antvis/G2Plot#3078]
### demo代码如下：

import React, { useState, useEffect } from "react";
import ReactDOM from "react-dom";
import { Sankey } from "@ant-design/plots";

const onClick = (e) => {
  console.log(222, e);
};

const DemoSankey = () => {
  const DATA = [
    {
      source: "首次打开",
      target: "首页 UV",
      value: 160
    },
    {
      source: "结果页",
      target: "首页 UV",
      value: 40
    },
    {
      source: "验证页",
      target: "首页 UV",
      value: 10
    },
    {
      source: "我的",
      target: "首页 UV",
      value: 10
    },
    {
      source: "朋友",
      target: "首页 UV",
      value: 8
    },
    {
      source: "其他来源",
      target: "首页 UV",
      value: 27
    },
    {
      source: "首页 UV",
      target: "理财",
      value: 30
    },
    {
      source: "首页 UV",
      target: "扫一扫",
      value: 40
    },
    {
      source: "首页 UV",
      target: "服务",
      value: 35
    },
    {
      source: "首页 UV",
      target: "蚂蚁森林",
      value: 25
    },
    {
      source: "首页 UV",
      target: "跳失",
      value: 10
    },
    {
      source: "首页 UV",
      target: "借呗",
      value: 30
    },
    {
      source: "首页 UV",
      target: "花呗",
      value: 40
    },
    {
      source: "首页 UV",
      target: "其他流向",
      value: 45
    }
  ];
  const config = {
    data: DATA,
    sourceField: "source",
    targetField: "target",
    weightField: "value",

    nodeWidthRatio: 0.008,
    nodePaddingRatio: 0.03,
    tooltip: {
      fields: ["fromCrowdName", "toCrowdName", "value"],
      customContent: (title, items) => {
        console.log(items);
        return `<div>${title}</div>`;
      },
      enterable: true
    }
  };

  return <Sankey {...config} />;
};
ReactDOM.render(<DemoSankey />, document.getElementById("container"));

代码试运行链接：https://codesandbox.io/s/falling-haze-qd9cj?file=/index.js:0-1750

**Comment by connono** [comment]
设置 tooltip : { showContent: true } 通过判断 item.data.isNode 是否为true 即可判断是否为node或是edge。
