### ISSUE TITLE
🐛 [BUG]limitInPlot属性无法屏蔽一些后出现的状态

### ISSUE THREAD

**Issue by qiansheng1989** [antvis/G2Plot#3079]
limitInPlot: true 设置了屏蔽图表外的显示但是折线图的active还是会显示
### 🐛 Bug description [Please make everyone to understand it]

> Please provide a link by forking these links [G2Plot](https://codesandbox.io/s/g2plot-issue-template-gzfdq?file=/index.ts) or GitHub repo, a minimal reproduction.

* _Required_ **Link to minimal reproduction**:

### 📷 Step to reproduce
limitInPlot: true 设置了屏蔽图表外的显示但是折线图的active还是会显示
### 🏞 Expected result
坐标轴以外的不显示
### 🚑 Any additional [like screenshots]
![image](https://user-images.githubusercontent.com/37897917/149898832-1ab6e748-f826-434b-99d7-a123ce3bf758.png)

* **G2Plot Version**:
* **Platform**:

**Comment by visiky** [comment]
这个好像是 tooltip 的 showMarkers，确实是个问题
