### ISSUE TITLE
轴标签文本对齐不对

### ISSUE THREAD

**Issue by zqlu** [antvis/G2Plot#308]
![image](https://user-images.githubusercontent.com/1142242/69719553-b1b6fb80-114b-11ea-8a80-7ec693dd2f17.png)

![image](https://user-images.githubusercontent.com/1142242/69719581-be3b5400-114b-11ea-95ed-54d51e7c7e04.png)

**Comment by paleface001** [comment]
这个应该去g2 3.6.x提

**Comment by zqlu** [comment]
> 这个应该去g2 3.6.x提

只有堆积条形图有这个问题，我想看下是哪的问题吧

**Comment by zqlu** [comment]
最新代码已经ok了
