### ISSUE TITLE
🐛 [BUG]双轴图添加标注

### ISSUE THREAD

**Issue by HuntSweet** [antvis/G2Plot#3084]
### 🐛 Question description [Please make everyone to understand it]
请问如何给双轴图动态地（比如说点击plot时）添加标记？
我使用addAnnotations方法给双轴图添加标记，但是是失效的
![image](https://user-images.githubusercontent.com/48612445/150454191-28da49c8-d32a-4894-a0bf-006557e69501.png)
所以，请问有没有什么方法添加标记

### 💻 Link to minimal reproduction

Please provide a link by forking these links [g2plot](https://codesandbox.io/s/g2plot-reproduction-template-gyej1) or GitHub repo. What is a minimal reproduction, and why is it required?

### 🚑 Any additional [like screenshots]

* **G2Plot Version**:
* **Platform**:

**Comment by connono** [comment]
传进去的参数格式有问题，应该是 Annotation，例如
<img width="659" alt="iShot2022-02-14 16 57 01" src="https://user-images.githubusercontent.com/36756846/153831788-ca3d97fd-9bb0-4836-a9e2-b366418a5025.png">
目前双轴图等具有分view的图表使用addAnnotations，annotation会固定在左下角，等request通过了就可以指定view添加annotations，并且位置可以调整。
