### ISSUE TITLE
🤔 [QUESTION]  图例显示不完整，被遮挡

### ISSUE THREAD

**Issue by LipiAndPili** [antvis/G2Plot#3087]
### 🐛 Question description [Please make everyone to understand it]

图例的汉字会有遮挡，怎么解决？（好像是加了分页导致的）
![image](https://user-images.githubusercontent.com/50241817/150503125-f2f7163c-90c3-48b7-a2ec-8cdc12ced8be.png)

### 💻 Link to minimal reproduction

Please provide a link by forking these links [g2plot](https://codesandbox.io/s/g2plot-reproduction-template-gyej1) or GitHub repo. What is a minimal reproduction, and why is it required?

### 🚑 Any additional [like screenshots]

* **G2Plot Version**:
* **Platform**:

**Comment by visiky** [comment]
duplicate with: https://github.com/antvis/G2Plot/issues/3088
