### ISSUE TITLE
🐛 [BUG] 图例显示不完整，被遮挡

### ISSUE THREAD

**Issue by LipiAndPili** [antvis/G2Plot#3088]
### 🐛 Bug description [Please make everyone to understand it]
图例显示不完整
![image](https://user-images.githubusercontent.com/50241817/150503297-d2bc0b39-05f0-4922-96ae-f0cfe0faa00d.png)

> Please provide a link by forking these links [G2Plot](https://codesandbox.io/s/g2plot-issue-template-gzfdq?file=/index.ts) or GitHub repo, a minimal reproduction.

* _Required_ **Link to minimal reproduction**:

### 🚑 Any additional [like screenshots]

* **G2Plot Version**:
* **Platform**:

**Comment by visiky** [comment]
做了缩放了吗？提供下 在线 demo 链接地址

**Comment by LipiAndPili** [comment]
正常不会遮挡，缩放以后，出现【分页】箭头就会这样遮挡（win10系统）

**Comment by LipiAndPili** [comment]
legend 添加了 itemHeight属性解决了
