### ISSUE TITLE
🥰 [FEATURE] 请问G2plot的仪表盘能否支持多指针

### ISSUE THREAD

**Issue by kooriookami** [antvis/G2Plot#3094]
### 🥰 Features description [Please make everyone to understand it]
![image](https://user-images.githubusercontent.com/38392315/150924952-5d824705-d74d-4f85-9f81-0924c1a42d3f.png)
这是G2的仪表盘，可以支持多指针效果。想问一下G2plot能否支持这个特性呢。

**Comment by visiky** [comment]
@connono 参考下，官网仪表盘的自定义指针方式，看下是否可以提供一个 demo 演示
