### ISSUE TITLE
🤔 [QUESTION]如何获取每个元素的具体位置 getXY()

### ISSUE THREAD

**Issue by LipiAndPili** [antvis/G2Plot#3099]
### 🐛 Question description [Please make everyone to understand it]
如何获取元素具体位置信息？

多柱图，同一纬度下的 chart.getXY(data) 获取到的 x 为什么是一样的？
![image](https://user-images.githubusercontent.com/50241817/151304770-d54d108a-b080-47b2-91e7-9920fd61d8c2.png)

**Comment by connono** [comment]
通过  chart.geometries[a].elements[b].getModel() 来获取图形元素的具体绘制信息

**Comment by visiky** [comment]
获取到 elements，通过 element.getBBox() 可以获取到对应的包围盒（然后，可以通过 `bbox.x + bbox.width / 2` 获取对应中心点 x 坐标）
