### ISSUE TITLE
自定义label的命名规范 & 饼图配置项的透出

### ISSUE THREAD

**Issue by Me-Momo** [antvis/G2Plot#310]
- 目前提供了自定义注册label的方式，但是label不允许重复注册，每个plot有自己注册的自定义label的话，是不是可以讨论一个 label 的命名规范，如果不是通用的label 就加上相应的 plot 命名空间

- 目前饼图实现的自定义注册label有以下几种(同时还提供了是否平滑连线的配置项)：
1. 环绕型label `outer-label` 
2. 环绕型抽样label `outer-sample-label` 
3. 对齐型label `align-label`
4. 对齐型抽样label `align-sample-label`

类型 | 示例|示例(平滑连线)
---|---|---
环绕型label `outer-label` |![image](https://user-images.githubusercontent.com/15646325/69769351-7524e780-11bf-11ea-9845-48f5122e464f.png)|![image](https://user-images.githubusercontent.com/15646325/69769894-cfbf4300-11c1-11ea-93b9-f70ed8069302.png)
环绕型label `outer-sample-label` |![image](https://user-images.githubusercontent.com/15646325/69769461-e795c780-11bf-11ea-99c1-f5e39d9dacb7.png)|![image](https://user-images.githubusercontent.com/15646325/69769558-3f343300-11c0-11ea-8ed4-c5ce752b971f.png)
对齐型label `align-label`|![image](https://user-images.githubusercontent.com/15646325/69772490-09e11280-11cb-11ea-8f92-9dbc8c3ca363.png)|![image](https://user-images.githubusercontent.com/15646325/69772528-23825a00-11cb-11ea-8c3e-268bc28cc6b2.png)
对齐型label `align-sample-label`|![image](https://user-images.githubusercontent.com/15646325/69769449-dc429c00-11bf-11ea-849a-76af7367e8a1.png)|![image](https://user-images.githubusercontent.com/15646325/69769874-b1594780-11c1-11ea-859e-0addf4a3e818.png)

**需要讨论的问题:**
1. 自定义注册label的命名规范(是否需要加上 plot 的类型作为命名空间)
如: `pie-outer-label`, `pie-align-label`, `pie-outer-sample-label`, `pie-align-sample-label`

2. 配置项的透出(如数据标签连接线是否平滑连接 & 数据标签是否抽样)

**配置项方案**
> 其中 `labelLine` 是否要拎出 `label`
```typescript
label: {
    // TODO
   sample: true,
   labelLine: {
     smooth: true, 
   }
}
```
**highcharts配置（参考）**
```typescript
dataLabels: {
   crop: true, //  see: https://api.highcharts.com.cn/plotOptions.pie.dataLabels.crop
   overflow: 'justify', // see:  https://api.highcharts.com.cn/plotOptions.pie.dataLabels.overflow
   softConnector: true, // 是否使用曲线连线
}
```
**echarts配置（参考）**
```typescript
avoidLabelOverlap: true, // Whether to enable the strategy to avoid labels overlap. Defaults to be enabled, which will move the label positions in the case of labels overlapping
stillShowZeroSum:  true, // Whether to show sector when all data are zero.
label: {
   // ....
},
labelLine: {
   smooth: false,
} 
```
附录:

配置|示例
---|---
默认配置|![image](https://user-images.githubusercontent.com/15646325/69771322-60e4e880-11c7-11ea-8d84-5386d44e9b15.png)
`labelLine: {  smooth: true },`|![image](https://user-images.githubusercontent.com/15646325/69771419-b3bea000-11c7-11ea-990a-e1e3c245c64f.png)
`avoidLabelOverlap: false`|![image](https://user-images.githubusercontent.com/15646325/69771353-79550300-11c7-11ea-84d4-beb7ca18feeb.png)

**Comment by Me-Momo** [comment]
其中，抽样label 即 echarts的 `avoidLabelOverlap: false, ` 的基础上 加了**遮挡自动隐藏策略**

**Comment by paleface001** [comment]
* 环绕label和环绕抽样label，这类可以考虑合并，是否抽样开成配置项
* 对齐label感觉不大直观，一起再想想

**Comment by hustcc** [comment]
抽样开启和不开启，有一个隐含的逻辑：开启抽样的时候，label 是不会偏移；不开启抽样，label 是最 y 方向偏移的。

**Comment by Me-Momo** [comment]
> * 环绕label和环绕抽样label，这类可以考虑合并，是否抽样开成配置项
> * 对齐label感觉不大直观，一起再想想

1. 是的，所以在想 是不是通过配置项的方式，以及 是否叫做 抽样，也要考虑一下
2. 对齐label可以考虑先不透露出去，但是命名也先考虑一下

**Comment by Me-Momo** [comment]
> 抽样开启和不开启，有一个隐含的逻辑：开启抽样的时候，label 是不会偏移；不开启抽样，label 是最 y 方向偏移的。

` echarts的 avoidLabelOverlap: false， `  逻辑就是：不开启的时候，label是不会偏移的，同时遮挡也不会隐藏；开启的时候，label是偏移的，label之间不会遮挡，但是溢出边界也不会隐藏

**Comment by hustcc** [comment]
保留两种：
方案 1：替代 outer
方案 2：替代 spider-label
