### ISSUE TITLE
似乎没有clearStatus

### ISSUE THREAD

**Issue by aAJia** [antvis/G2Plot#3101]
写了一个循环 给目标添加active，但添加过一轮以后状态无法清除

```
const list = ['a','b'];
setInterval(() => {
        index = index ? 0 : 1;
        const current = list[index];
        piePlot.setState('active', (data) => {
          return (data as any).type === current
        })
      }, 4000)
```

**Comment by connono** [comment]
需要手动清除

`
piePlot.setState('active', (data) => {
     return (data as any).type === current
}, false);
`

![3101-1](https://user-images.githubusercontent.com/36756846/153115195-a5b8ee11-f84e-445d-a5ee-ca67383dca5d.jpg)

**Comment by ZombieBrand** [comment]
建议文档说明一下第三个参数status的作用

**Comment by 1078195353** [comment]
> 
使用```piePlot.setState('active', (data) => { return (data as any).type === current }, true)```不能触发我自定义的state类型？

**Comment by 1078195353** [comment]
> 需要手动清除
> 
> `piePlot.setState('active', (data) => { return (data as any).type === current }, false);`
> 
> ![3101-1](https://user-images.githubusercontent.com/36756846/153115195-a5b8ee11-f84e-445d-a5ee-ca67383dca5d.jpg)

当我在option当中设置：
```
state: { 
 active: {
   style: {
     lineWidth: 5
   }
  }
}
```
去设置```piePlot.setState('active', (data) => { return (data as any).type === current }, true);```
方法生效，但是选择了默认的 ```active``` 样式，并没有选择我自定义的样式。
如何在设置的时候选择上我的自定义样式呢

**Comment by visiky** [comment]
> 当我在option当中设置：
> 
> ```
> state: { 
>  active: {
>    style: {
>      lineWidth: 5
>    }
>   }
> }
> ```
> 
> 去设置`piePlot.setState('active', (data) => { return (data as any).type === current }, true);` 方法生效，但是选择了默认的 `active` 样式，并没有选择我自定义的样式。 如何在设置的时候选择上我的自定义样式呢 @connono

给一下复现 demo
