### ISSUE TITLE
🤔 [QUESTION] 计量图和环形图的【中心文本组件】如何同比缩放

### ISSUE THREAD

**Issue by LipiAndPili** [antvis/G2Plot#3103]
### 🐛 Question description [Please make everyone to understand it]
缩放图表，中心文本不能同比例缩放
![image](https://user-images.githubusercontent.com/50241817/151652509-34798d56-5675-49fa-a546-51a13eadd83a.png)

**Comment by visiky** [comment]
需要外部去根据容器大小，调整 statistics 文本的大小。可以参考下这个 demo：https://g2plot.antv.vision/zh/examples/pie/donut#statistics 看下是否能够有些启发

**Comment by LipiAndPili** [comment]
@visiky 好的，十分感谢
