### ISSUE TITLE
🤔 [QUESTION] Area / default stacked

### ISSUE THREAD

**Issue by mehdi-dalil** [antvis/G2Plot#3109]
### 🐛 Question description
By default, multiple areas are stacked and I see no options to unstack them, is it possible ?

* **G2Plot Version**: 1.2.11
* **Platform**: macOS

**Comment by visiky** [comment]
try to set `isStack: false`

**Comment by mehdi-dalil** [comment]
Yes, my use case was with the Mix plot, and i was creating a plot for every area serie i had, instead i put all the series in one table and I could use `isStack` in it ! Thanks !
