### ISSUE TITLE
下载使用改成开始使用

### ISSUE THREAD

**Issue by afc163** [antvis/G2Plot#311]
英文 Getting Started，链接到 https://g2plot.antv.vision/zh/docs/manual/introduction

**Comment by paleface001** [comment]
Done. #312

**Comment by afc163** [comment]
要用 commit message 关 issue。https://github.com/antvis/antvis.github.io/issues/29#issuecomment-555052453

**Comment by paleface001** [comment]
> 要用 commit message 关 issue。[antvis/antvis.github.io#29 (comment)](https://github.com/antvis/antvis.github.io/issues/29#issuecomment-555052453)

手快了 😇 以后注意
