### ISSUE TITLE
🐛 [BUG] 【折线图】label展示，如果多个系列距离太近的话，有部分标注会被默认隐藏

### ISSUE THREAD

**Issue by ntscshen** [antvis/G2Plot#3115]
##  A picture is worth a thousand words | 一图胜千言

问题：当线条比较接近时，标注会展示不全

![image](https://user-images.githubusercontent.com/21041458/153550400-64a1e0a2-ea41-48ac-bee6-282b973df1a6.png)

* _Required_ **Link to minimal reproduction**: https://stackblitz.com/edit/react-2cej7r?file=src/index.js

**Comment by ntscshen** [comment]
当线条比较接近时，标注会展示不全

**Comment by visiky** [comment]
label layout 有一些策略，导致碰撞会隐藏；可以考虑下自定义 label layout，按照业务自己的诉求，去定制策略
