### ISSUE TITLE
🤔 [QUESTION] colorField in Column

### ISSUE THREAD

**Issue by iliasov-artem** [antvis/G2Plot#3118]
### 🐛 Question description
I`m trying to use: 

`{
  colorField: 'type',
  color: ({ type }) => {
    if(type === 'male'){
      return 'red';
    }
    return 'yellow';
  }
}`

but it doesn`t work, "type" is undefined
Is it bug or mistake in documentation?

**Comment by mehdi-dalil** [comment]
can you send your entire config object please ?

**Comment by visiky** [comment]
maybe you should use `seriesField`

<img width="1213" alt="image" src="https://user-images.githubusercontent.com/15646325/153976697-70c632c8-5a92-4f9d-aa64-0f3545af0117.png">

**Comment by iliasov-artem** [comment]
`const data = [
  {
    type: '家具家电',
    sales: 38,
    color: 'red'
  },
  {
    type: '粮油副食',
    sales: 52,
    color: 'black'

  },
  {
    type: '生鲜水果',
    sales: 61,
    color: 'red'

  },
  {
    type: '美容洗护',
    sales: 145,
    color: 'red'

  },
  {
    type: '母婴用品',
    sales: 48,
    color: 'yellow'

  },
  {
    type: '进口食品',
    sales: 38,
    color: 'red'

  },
  {
    type: '食品饮料',
    sales: 38,
    color: 'red'

  },
  {
    type: '家庭清洁',
    sales: 38,
    color: 'red'

  },
];

const columnPlot = new Column('container', {
  data,
  xField: 'type',
  yField: 'sales',
  label: {
    // 可手动配置 label 数据标签位置
    position: 'middle', // 'top', 'bottom', 'middle',
    // 配置样式
    style: {
      fill: '#FFFFFF',
      opacity: 0.6,
    },
  },
  xAxis: {
    label: {
      autoHide: true,
      autoRotate: false,
    },
  },
  colorField: 'color', // or seriesField in some cases
  color: ({ color }) => {
    return color;
  },
  meta: {
    type: {
      alias: '类别',
    },
    sales: {
      alias: '销售额',
    },
  },
});

columnPlot.render();
`

**Comment by iliasov-artem** [comment]
> can you send your entire config object and a sample of your data ?

```
const data = [
  {
    type: '家具家电',
    sales: 38,
    color: 'red'
  },
  {
    type: '粮油副食',
    sales: 52,
    color: 'black'

  },
  {
    type: '生鲜水果',
    sales: 61,
    color: 'red'

  },
  {
    type: '美容洗护',
    sales: 145,
    color: 'red'

  },
  {
    type: '母婴用品',
    sales: 48,
    color: 'yellow'

  },
  {
    type: '进口食品',
    sales: 38,
    color: 'red'

  },
  {
    type: '食品饮料',
    sales: 38,
    color: 'red'

  },
  {
    type: '家庭清洁',
    sales: 38,
    color: 'red'

  },
];

const columnPlot = new Column('container', {
  data,
  xField: 'type',
  yField: 'sales',
  label: {
    // 可手动配置 label 数据标签位置
    position: 'middle', // 'top', 'bottom', 'middle',
    // 配置样式
    style: {
      fill: '#FFFFFF',
      opacity: 0.6,
    },
  },
  xAxis: {
    label: {
      autoHide: true,
      autoRotate: false,
    },
  },
  colorField: 'color', // or seriesField in some cases
  color: ({ color }) => {
    return color;
  },
  meta: {
    type: {
      alias: '类别',
    },
    sales: {
      alias: '销售额',
    },
  },
});

columnPlot.render();
```

**Comment by iliasov-artem** [comment]
> maybe you should use `seriesField`
> 
> <img alt="image" width="1213" src="https://user-images.githubusercontent.com/15646325/153976697-70c632c8-5a92-4f9d-aa64-0f3545af0117.png">

I can`t, because I need them both

**Comment by visiky** [comment]
> > can you send your entire config object and a sample of your data ?
> 
> ```
> const data = [
>   {
>     type: '家具家电',
>     sales: 38,
>     color: 'red'
>   },
>   {
>     type: '粮油副食',
>     sales: 52,
>     color: 'black'
> 
>   },
>   {
>     type: '生鲜水果',
>     sales: 61,
>     color: 'red'
> 
>   },
>   {
>     type: '美容洗护',
>     sales: 145,
>     color: 'red'
> 
>   },
>   {
>     type: '母婴用品',
>     sales: 48,
>     color: 'yellow'
> 
>   },
>   {
>     type: '进口食品',
>     sales: 38,
>     color: 'red'
> 
>   },
>   {
>     type: '食品饮料',
>     sales: 38,
>     color: 'red'
> 
>   },
>   {
>     type: '家庭清洁',
>     sales: 38,
>     color: 'red'
> 
>   },
> ];
> 
> const columnPlot = new Column('container', {
>   data,
>   xField: 'type',
>   yField: 'sales',
>   label: {
>     // 可手动配置 label 数据标签位置
>     position: 'middle', // 'top', 'bottom', 'middle',
>     // 配置样式
>     style: {
>       fill: '#FFFFFF',
>       opacity: 0.6,
>     },
>   },
>   xAxis: {
>     label: {
>       autoHide: true,
>       autoRotate: false,
>     },
>   },
>   colorField: 'color', // or seriesField in some cases
>   color: ({ color }) => {
>     return color;
>   },
>   meta: {
>     type: {
>       alias: '类别',
>     },
>     sales: {
>       alias: '销售额',
>     },
>   },
> });
> 
> columnPlot.render();
> ```

use  `seriesField` instead of `colorField`, `colorField` isn't supported here

**Comment by mehdi-dalil** [comment]
`colorField` isn't supported anymore, and if you cannot use `seriesField`, use `color` like this:
```js
color: data.map(({ color }) => color),
```
