### ISSUE TITLE
🐛 [BUG]图表销毁文档上有destory方法，但实际上使用报错，实例上没有这个方法！

### ISSUE THREAD

**Issue by webzmj530** [antvis/G2Plot#3121]
### 🐛 Bug description [Please make everyone to understand it]

> Please provide a link by forking these links [G2Plot](https://codesandbox.io/s/g2plot-issue-template-gzfdq?file=/index.ts) or GitHub repo, a minimal reproduction.

* _Required_ **Link to minimal reproduction**:

### 🚑 Any additional [like screenshots]

* **G2Plot Version**:2.4.8
* **Platform**:windows

**Comment by visiky** [comment]
哪个图表？提问的时候，提供下复现 demo 链接吧

**Comment by liuxinmei** [comment]
方法名叫destroy，文档写错了
