### ISSUE TITLE
🐛 [BUG]瀑布图中，xField的值为日期格式，不显示total

### ISSUE THREAD

**Issue by XiaJunjie2020** [antvis/G2Plot#3136]
### 🐛 Bug description [Please make everyone to understand it]

瀑布图中，xField的值为日期格式（yyyy-MM-dd），没有显示total柱子，但留出了total的区域（空白）

![image](https://user-images.githubusercontent.com/59437931/157002308-c1a9312f-35b5-41ed-9650-05ef20b21c4a.png)

>  [瀑布图｜G2Plot](https://g2plot.antv.vision/zh/examples/more-plots/waterfall#basic)

* _Required_ **Link to minimal reproduction**:

### 📷 Step to reproduce

代码如下：

```
import { Waterfall } from '@antv/g2plot';

const data = [{
  "value": 1,
  "field": "1995-01-01"
}, 
{
  "value": 1,
  "field": "1995-01-02"
}, 
{
  "value": 1,
  "field": "1995-01-03"
},
 {
  "value": 1,
  "field": "1995-01-04"
}];

const waterfallPlot = new Waterfall('container', {
  data,
  xField: 'field',
  yField: 'value',
  total: {
    label: '合计',
    style: {
      fill: '#96a6a6',
    },
  },
});

waterfallPlot.render();
```

### 🏞 Expected result

希望能绘制出合计柱子

### 🚑 Any additional [like screenshots]

* **G2Plot Version**:2.4.9
* **Platform**:

**Comment by BBchicken-9527** [comment]
我也遇到了相同的问题。希望能尽快修复

**Comment by tzlaosiji** [comment]
+1，希望能尽快修复呀，否则这个瀑布图不太能用。。。

**Comment by ai-qing-hai** [comment]
@tzlaosiji  @BBchicken-9527  如果x坐标数据为 time 类型， 最标轴就加不上 total 字段。  你需要把 meta[xField].type 设置为 cat 才行。

**Comment by XiaJunjie2020** [comment]
好的，感谢
