### ISSUE TITLE
🐛 [BUG] 图例文本 设置 fontWeight 为无效值时，会导致 字体 失效

### ISSUE THREAD

**Issue by rabbit-tian** [antvis/G2Plot#3139]
当设置图例文本的 fontWeight 设置为 "regular" 或 "ttt" 这种无效值时，会导致字体大小失效
![image](https://user-images.githubusercontent.com/26690191/157414392-07d69a88-5880-4a53-8472-60d2e47e1cf7.png)

复现：https://codesandbox.io/s/interesting-dream-wtbckk?file=/index.ts

* **G2Plot Version**:  2.4.9
* **Platform**: g2plot

**Comment by visiky** [comment]
这种在原生canvas也会出现，上层控制只能输入有效字体吧（底层无法枚举）

**Comment by rabbit-tian** [comment]
好滴
