### ISSUE TITLE
🐛 [BUG]设置point后，animation的animation/enter设置为path-in报错

### ISSUE THREAD

**Issue by shaoyh** [antvis/G2Plot#3141]
设置point后，animation的animation/enter设置为path-in报错，设置成wave-in正常；
animation: {
            appear: {
                animation: 'path-in',
                enter: 'path-in',
                duration: 3500,
            },
        },
        point: {
          shape: 'breath-point',
        },

G2.registerShape('point', 'breath-point', {
        draw(cfg, container) {
            const data = cfg.data;
            const point = {
                x: cfg.x,
                y: cfg.y,
            };
            const group = container.addGroup();

            if (data?.peakType === 'max' || data?.peakType === 'min') {
                const decorator1 = group.addShape('circle', {
                    attrs: {
                        x: point.x,
                        y: point.y,
                        r: 5,
                        fill: cfg.color,
                        opacity: 0.5,
                    },
                });
                const decorator2 = group.addShape('circle', {
                    attrs: {
                        x: point.x,
                        y: point.y,
                        r: 5,
                        fill: cfg.color,
                        opacity: 0.5,
                    },
                });
                const decorator3 = group.addShape('circle', {
                    attrs: {
                        x: point.x,
                        y: point.y,
                        r: 5,
                        fill: cfg.color,
                        opacity: 0.5,
                    },
                });
                decorator1.animate(
                    {
                        r: 10,
                        opacity: 0,
                    },
                    {
                        duration: 1800,
                        easing: 'easeLinear',
                        repeat: true,
                    },
                );
                decorator2.animate(
                    {
                        r: 10,
                        opacity: 0,
                    },
                    {
                        duration: 1800,
                        easing: 'easeLinear',
                        repeat: true,
                        delay: 600,
                    },
                );
                decorator3.animate(
                    {
                        r: 10,
                        opacity: 0,
                    },
                    {
                        duration: 1800,
                        easing: 'easeLinear',
                        repeat: true,
                        delay: 1200,
                    },
                );
                group.addShape('circle', {
                    attrs: {
                        x: point.x,
                        y: point.y,
                        r: 3,
                        fill: cfg.color,
                        opacity: 0.7,
                    },
                });
                group.addShape('circle', {
                    attrs: {
                        x: point.x,
                        y: point.y,
                        r: 0.75,
                        fill: cfg.color,
                    },
                });
            }

            return group;
        },
    });

**Comment by ai-qing-hai** [comment]
@shaoyh  path-in 是代表 按照路径会显示， line 是有路径 的， 而 point 只有 x y 和 自身的形状。 所以不能使用 path-in 。 后续增加 动画回调吧。 这样就可以分别加上动画了。
