### ISSUE TITLE
在中国打开网站太慢了，看个示例等半天，请优化网站访问速度

### ISSUE THREAD

**Issue by kemistep** [antvis/G2Plot#3148]
- [ ] I have searched the [issues](https://github.com/antvis/g2plot/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
https://antv-g2plot.gitee.io/zh/ 网站打开慢

### What does the proposed API look like?
提高网站打开速度

**Comment by kemistep** [comment]
补充 访问速度图

![image](https://user-images.githubusercontent.com/16223610/158497612-0a939a5f-7be1-46e7-91ba-a3d0e3099043.png)

**Comment by visiky** [comment]
duplicate with #3150

**Comment by visiky** [comment]
官网更新了，新地址：http://g2plot.antv.antgroup.com/
