### ISSUE TITLE
🐛 [BUG]legend title 设置有问题

### ISSUE THREAD

**Issue by Ein212** [antvis/G2Plot#3154]
legend的title，一开始看了文档设置不上去。https://g2plot.antv.vision/zh/docs/api/plots/pie#title-1
![image](https://user-images.githubusercontent.com/45907846/159615794-6ddc1e31-31ef-4db8-b698-7ebe538351bd.png)
设置不上去
![image](https://user-images.githubusercontent.com/45907846/159615903-1ec3cbeb-d8c4-4b40-a103-29b3c5c5e10e.png)
改成text可以了，文档里写的是title。
![image](https://user-images.githubusercontent.com/45907846/159615579-b0e2b3f0-a837-4a6a-a2ee-8940cd8eacbd.png)

* **G2Plot Version**:2.4.11
* **Platform**:windows

**Comment by wensaint** [comment]
2.4.11问题不少，刚刚试了分组柱状图也没法显示。不知道是文档没更新还是版本bug，我已经回退到2.4.10了

**Comment by visiky** [comment]
文档没更新，帮忙提交一个Pr 吧（按道理是一直的文档问题）
