### ISSUE TITLE
🤔 矩形树图-自定义Label

### ISSUE THREAD

**Issue by hubye** [antvis/G2Plot#3160]
Label文本自定义展示如何给每块文本区域以HTML标签方式插入矢量图标？

**Comment by ai-qing-hai** [comment]
@hubye  label 没有 html 的形式。  可以使用 annotation 的 html 代替 https://g2plot.antv.vision/zh/examples/component/annotation#text-annotation1

**Comment by ai-qing-hai** [comment]
@hubye  label 没有 html 的形式

**Comment by hubye** [comment]
那如何在区域里加icon图标或者是图片？

**Comment by ai-qing-hai** [comment]
尝试使用自定义形状进行 添加 image  https://g2.antv.vision/zh/examples/point/bubble#bubble-image https://g2plot.antv.vision/zh/examples/case/statistical-scenario#conversion-funnel

**Comment by visiky** [comment]
> 尝试使用自定义形状进行 添加 image https://g2.antv.vision/zh/examples/point/bubble#bubble-image https://g2plot.antv.vision/zh/examples/case/statistical-scenario#conversion-funnel

- 按照这种解法先处理
- 新版会更好支持
