### ISSUE TITLE
图表需求相关issue

### ISSUE THREAD

**Issue by elaine1234** [antvis/G2Plot#318]
![image](https://user-images.githubusercontent.com/8325822/69848570-64ef3400-12b5-11ea-8c42-a0c4fc2c9fd0.png)

**Comment by paleface001** [comment]
条形图 xAxis 与 legend 之间间距异常
条形图 padding 异常
![image](https://user-images.githubusercontent.com/8325822/69848642-949e3c00-12b5-11ea-8b87-1f637c9cace9.png)

**Comment by paleface001** [comment]
点击 canvas 空白部分不会触发 onPlotClick & onPlotDblclick 事件
