### ISSUE TITLE
🤔 柱形图Bar使用changeData接口会白屏。

### ISSUE THREAD

**Issue by yuanyayi** [antvis/G2Plot#3180]
官方示例地址：https://g2plot.antv.vision/zh/examples/dynamic-plots/basic#dynamic-spline

将其中的Line改为Bar，就可以看到具体情况。
只有第一屏能够正常显示，之后会变为有坐标轴的白屏。

![image](https://user-images.githubusercontent.com/19421507/162700374-cf10b90e-b95a-4b32-b46f-60263855321f.png)

请问下如何正常更新数据？

我大概理解问题出在我需要向柱状图中补充更多的数据这件事儿上，有什么解决方法吗？

**Comment by visiky** [comment]
注意下，bar 的 `xField` 和 `yField` 应该做一个转换
