### ISSUE TITLE
y轴会出现数据错乱， 用了formatter也不起作用， 请问是什么情况🤔 [QUESTION]

### ISSUE THREAD

**Issue by wuyanghou** [antvis/G2Plot#3181]
### 💻 Link to minimal reproduction

Please provide a link by forking these links [g2plot](https://codesandbox.io/s/g2plot-reproduction-template-gyej1) or GitHub repo. What is a minimal reproduction, and why is it required?

### 🚑 Any additional [like screenshots]

* **G2Plot Version**:
* **Platform**:

![image](https://user-images.githubusercontent.com/25168633/162724217-616a8aa9-55e0-4e48-b8a2-f8cdd058ae5c.png)

**Comment by wuyanghou** [comment]
用官网的例子添加不同的数据也会出现

**Comment by visiky** [comment]
先用 formatter 处理下，应该小数精点问题
