### ISSUE TITLE
🤔 [QUESTION] Tooltip styling

### ISSUE THREAD

**Issue by severinlandolt** [antvis/G2Plot#3193]
### 🐛 Question description [Please make everyone to understand it]

Dear team,

I am trying to style the tooltip of the line chart, but I cannot get it to work. May you assist in how I can customize the tooltip's border radius and shadow? Thanks!

 const config = {
    tooltip: {
      showTitle:true,
      shared: true,
      showContent: true,
 **_borderRadius: 12px,_**
  },

* **G2Plot Version**:
* **Platform**:

**Comment by ai-qing-hai** [comment]
@severinlandolt       
 tooltip: {
        domStyles: {
          'g2-tooltip': {
            borderRadius: ' 12px',
          },
        }
      },
