### ISSUE TITLE
钉钉群满了，有新的群吗

### ISSUE THREAD

**Issue by iCloudys** [antvis/G2Plot#3196]
### 💻 Link to minimal reproduction

Please provide a link by forking these links [g2plot](https://codesandbox.io/s/g2plot-reproduction-template-gyej1) or GitHub repo. What is a minimal reproduction, and why is it required?

### 🚑 Any additional [like screenshots]

* **G2Plot Version**:
* **Platform**:

**Comment by visiky** [comment]
钉钉群已更新，可以进入三群
