### ISSUE TITLE
🐛 [BUG] Area在smooth为false时候显示错误

### ISSUE THREAD

**Issue by OneGIl** [antvis/G2Plot#3199]
### 🐛 Bug description [Please make everyone to understand it]

[codesandbox](https://codesandbox.io/s/g2plot-issue-template-forked-74zhw6?file=/index.ts)

### 📷 Step to reproduce
参考codesandbox中的代码

### 🏞 Expected result
当area设置smooth为false时，面积图和线段都应该是平直状态，但线段依然保持平滑状态。

### 🚑 Any additional [like screenshots]
如果要按照预期显示的话，需要把Y轴的字段名改为其他，比如“value”即可按照预期的方式显示。不知道为什么Y轴字段名设置成“line”就会出现这个问题（折线图没有这个问题）。

* **G2Plot Version**: 2.4.15, 2.4.16
* **Platform**: Firefox v99, edge v100, chrome v100 (全部浏览器都在Mac M1 pro 环境下)

**Comment by ai-qing-hai** [comment]
@OneGIl  是这样的 G2 种的 曲线是通过 shape 形状方法去控制的。  g.shape('rect');  g.shape('shape', ['rect', 'circle']); 而 shape 方法有多种方式 1、包括 'smooth' 'line' 'area' 这些默认的内部形状。2、  第一个 参数也作为 分类字段， 用户 第二个参数 数组或回调的参数  所以 如果数据中 出现 smooth line area 等字样，会默认为 第二个方法 。

**Comment by OneGIl** [comment]
@ai-qing-hai 好的，理解了，就是说我使用了G2里的关键字导致冲突了，没有按照预期执行。感谢你的解释！
