### ISSUE TITLE
图表视觉 & 事件优化

### ISSUE THREAD

**Issue by elaine1234** [antvis/G2Plot#321]
- 饼图 label 蜘蛛布局下 padding 不对
![image](https://user-images.githubusercontent.com/8325822/69849280-35412b80-12b7-11ea-83a9-56cafcdb469e.png)
- 条形图 xAxis 与 legend 之间间距异常
- 条形图 padding 异常
![image](https://user-images.githubusercontent.com/8325822/69849296-3eca9380-12b7-11ea-8f29-a62bb52a80c9.png)
- 点击 canvas 空白部分不会触发 onPlotClick & onPlotDblclick 事件

**Comment by paleface001** [comment]
条形图padding异常这个是因为label组件无法参与padding，在g2plot层无法解决。G2 4.0能解这个问题吗？ @hustcc

**Comment by paleface001** [comment]
> * 点击 canvas 空白部分不会触发 onPlotClick & onPlotDblclick 事件
这个有可能是因为这部分不在view的范围内，看来需要在g2plot层将plot(canvas)事件和layer(view)事件拆开。

**Comment by paleface001** [comment]
@zqlu  刀哥来看看条形图axis和legend间距异常？

**Comment by hustcc** [comment]
- onPlotClick 这个不是 Geometry 区域点击的时候才会触发吗？
 - label 参入 padding 估计难做，不过可以优化的是，如果超出，就向内偏移显示全。

**Comment by paleface001** [comment]
> * onPlotClick 这个不是 Geometry 区域点击的时候才会触发吗？
> * label 参入 padding 估计难做，不过可以优化的是，如果超出，就向内偏移显示全。

* onPlotClick是在g2plot层抛出的图表点击事件，并不对应G2的事件
* label超出之后向内偏移这个在条形图上不合适，因为偏移之后label会直接改在图形上，用户仍然会认为这是bug

**Comment by zqlu** [comment]
> @zqlu 刀哥来看看条形图axis和legend间距异常？

我今天看下
