### ISSUE TITLE
🐛 [BUG] latest g2plot 版本中 x, y 轴数据不是满射

### ISSUE THREAD

**Issue by junhaideng** [antvis/G2Plot#3221]
### 🐛 Bug description [Please make everyone to understand it]
不同的 x 数据，会对应到同一个 x 点上，比如 x=1, y=1, x=2,y=2，图中会出现 x=1,y=1, x=1,y=2 的情况

> Please provide a link by forking these links [G2Plot](https://codesandbox.io/s/g2plot-issue-template-gzfdq?file=/index.ts) or GitHub repo, a minimal reproduction.

* _Required_ **Link to minimal reproduction**: https://codesandbox.io/s/g2plot-issue-template-forked-pfj5vd

### 📷 Step to reproduce

run [reproduction](https://codesandbox.io/s/g2plot-issue-template-forked-pfj5vd)

<img src="https://user-images.githubusercontent.com/47896650/169684335-7727c877-6433-4c59-a001-12d15cf35a35.png" width=400>

### 🏞 Expected result
<img src="https://user-images.githubusercontent.com/47896650/169684309-54cbea5d-2bfb-4627-b95c-543889055ade.png" width=400>

### 🚑 Any additional [like screenshots]

* **G2Plot Version**: latest, 2.3.35 也有，其他版本未测
* **Platform**: codesandbox
* 文档上的 examples 也有这些问题，不仅是 折线图，柱状图也是有的

**Comment by hustcc** [comment]
之前 G2 内部做了默认的数据排序。可以改成：

```ts
chart.line({ sortable: true })
```

**Comment by haikyuu** [comment]
Thanks a log, this was a very hard issue to find an answer for as I don't know Chinese (yet) :) 
Leaving some keywords here ...

Inaccurate Y-values Representation on Line Chart for Unique X-axis Data Points

I am experiencing an issue with G2Plot where my line chart does not accurately represent y-values according to the provided dataset. Despite having distinct y-values for different x-axis points in my dataset, the chart incorrectly displays multiple x-axis points as having the same y-value. This visual inconsistency does not align with the data input, suggesting a possible bug in the rendering or data processing logic of the chart
