### ISSUE TITLE
🐛 [BUG]label.fill对柱状图不生效, 无法修改label颜色

### ISSUE THREAD

**Issue by Eve-Sama** [antvis/G2Plot#3233]
### 🐛 Bug description [Please make everyone to understand it]
![图片](https://user-images.githubusercontent.com/30228406/171377402-685cbfe7-96e6-43e3-8c48-6fdbe1a3679f.png)

> Please provide a link by forking these links [G2Plot](https://codesandbox.io/s/g2plot-issue-template-gzfdq?file=/index.ts) or GitHub repo, a minimal reproduction.

* _Required_ **Link to minimal reproduction**:

### 📷 Step to reproduce

label.fill对条形图生效, 但对柱状图不生效.

### 🚑 Any additional [like screenshots]

* **G2Plot Version**:
* **Platform**:

**Comment by visiky** [comment]
因为内置了一个 label layout 为 adjustColor，可以将其关闭。这个处理会根据label背景色来动态调整label fill，让字体和背景色的区分度提升，避免出现背景是白色，字体溢出shape之后也是白色的情况

**Comment by jiangxiaoxilsy** [comment]
可以在文档里面将这种情况写详细点吗？
另外关闭怎么关闭呢？
