### ISSUE TITLE
🐛 [BUG] 找不到依赖 @antv/util

### ISSUE THREAD

**Issue by alphabetabc** [antvis/G2Plot#3239]
### 🐛 Bug description [Please make everyone to understand it]

> Please provide a link by forking these links [G2Plot](https://codesandbox.io/s/g2plot-issue-template-gzfdq?file=/index.ts) or GitHub repo, a minimal reproduction.

* _Required_ **Link to minimal reproduction**:

### 📷 Step to reproduce
项目正常启动，就报错
### 🚑 Any additional [like screenshots]
![image](https://user-images.githubusercontent.com/29876424/172087953-5bab5c5f-f523-4a53-9baf-a3213dfdd965.png)

* **G2Plot Version**: latest
* **Platform**: windows

**Comment by alphabetabc** [comment]
项目中不止一处用到了 
![image](https://user-images.githubusercontent.com/29876424/172088284-4d255c20-cb99-4b04-bc64-e002fc96af93.png)

**Comment by visiky** [comment]
在依赖链中，应该是可以找到的（至少 G2Plot 依赖的 G2，是有指明依赖了 `@antv/util` 的）

**Comment by alphabetabc** [comment]
@visiky  我用pnpm管理的依赖，然后写过一个demo里面用了antv/util
