### ISSUE TITLE
如何在react项目中使用G2Plot?

### ISSUE THREAD

**Issue by xiaodu527** [antvis/G2Plot#324]
hello, 如题，请问如何在react项目中使用g2plot？

**Comment by xgj1988** [comment]
我要想问这个问题。。

**Comment by paleface001** [comment]
G2Plot的react封装版本会以Ant Design Chart的方式呈现，敬请期待~

**Comment by kaoding** [comment]
同问？

**Comment by hustcc** [comment]
@xiaodu527 @xgj1988 @kaoding   G2Plot 项目本身是不感知用户使用 React 还是 Vue 技术栈的，在 React 环境中封装一层 G2Plot 包装，应该难不倒大家。

欢迎大家开源各种 G2Plot 的 react 周边项目，可以参考 [echarts-for-react](https://github.com/hustcc/echarts-for-react)。

**Comment by afc163** [comment]
最简单的方式：

```jsx
import React, { useRef, useEffect } from 'react';
import { Bar } from '@antv/g2plot';

const App = () => {
  const data = [
    { year: '1951 年', sales: 38 },
    { year: '1952 年', sales: 52 },
    { year: '1956 年', sales: 61 },
    { year: '1957 年', sales: 145 },
    { year: '1958 年', sales: 48 },
  ];

  const container = useRef(null);

  useEffect(() => {
    if (!container.current) {
      return;
    }
    const bar = new Bar(container.current, {
      data,
      xField: 'sales',
      yField: 'year',
      colorField: 'year',
    });
    bar.render();
  }, []);

  return (
    <div>
      <div ref={container} />
    </div>
  ); 
};
```

**Comment by xgj1988** [comment]
@hustcc  难是不难，关键是我npm 装不上。yarn 也不行。 。项目重新删了。重新 npm install 和 yarn 都不行

**Comment by hustcc** [comment]
> @hustcc 难是不难，关键是我npm 装不上。yarn 也不行。 。项目重新删了。重新 npm install 和 yarn 都不行

有报什么错误码？来来点具体的信息~

**Comment by xgj1988** [comment]
#325  @hustcc  看看这个

**Comment by zlab** [comment]
没有index.js，暂时只能这样`import { Ring } from '@antv/g2plot/esm'`

![image](https://user-images.githubusercontent.com/2288630/69961024-d6ddac80-1545-11ea-98ea-9ead61c2ca61.png)

**Comment by xgj1988** [comment]
@zlab  谢谢。

**Comment by zlab** [comment]
和bizcharts有什么区别？

```
chart.tooltip({
  useHtml: true,
  htmlContent: function(title, items) {
    return '<div><ul><li>.....</li></ul></div>';
  },
});
```
`htmlContent`不支持ReactNode，太恶心了，回到了拼接html的时代

**Comment by ldd27** [comment]
请问下如何刷新图表数据呢，暂时没有找到刷新数据的接口呢

**Comment by GiorgioPeng** [comment]
> 最简单的方式：
> 
> ```js-jsx
> import React, { useRef, useEffect } from 'react';
> import { Bar } from '@antv/g2plot';
> 
> const App = () => {
>   const data = [
>     { year: '1951 年', sales: 38 },
>     { year: '1952 年', sales: 52 },
>     { year: '1956 年', sales: 61 },
>     { year: '1957 年', sales: 145 },
>     { year: '1958 年', sales: 48 },
>   ];
> 
>   const container = useRef(null);
> 
>   useEffect(() => {
>     if (!container.current) {
>       return;
>     }
>     const bar = new Bar(container.current, {
>       data,
>       xField: 'sales',
>       yField: 'year',
>       colorField: 'year',
>     });
>     bar.render();
>   }, []);
> 
>   return (
>     <div>
>       <div ref={container} />
>     </div>
>   ); 
> };
> ```

@afc163 请问一下
```Javascript
  if (!container.current) {     
     return;
 }
```
这段代码是否是多余的(因为我删除了一下试了试好像也能用,这个useEffect 第二个参数为空数组不是只会执行一次吗?)
再请问一下useEffect第一次执行是否对应class组件生命周期中的componentDidMount?

**Comment by hustcc** [comment]
> 请问下如何刷新图表数据呢，暂时没有找到刷新数据的接口呢

```ts
chart.updateConfig({ data: newData });
```

**Comment by ldd27** [comment]
> > 请问下如何刷新图表数据呢，暂时没有找到刷新数据的接口呢
> 
> ```ts
> chart.updateConfig({ data: newData });
> ```

好的，我试下，谢谢

**Comment by daoyi7** [comment]
> > > 请问下如何刷新图表数据呢，暂时没有找到刷新数据的接口呢
> > 
> > 
> > ```ts
> > chart.updateConfig({ data: newData });
> > ```
> 
> 好的，我试下，谢谢

![image](https://user-images.githubusercontent.com/22697900/71342709-8c75ab80-2598-11ea-8b53-a82758feba98.png)

**Comment by 18402025768** [comment]
当成js就可以在vue,react,或者其他语言环境中使用
![image](https://user-images.githubusercontent.com/20633660/71454129-1f495c80-27ca-11ea-96ea-4e65d302f07a.png)

**Comment by git-lt** [comment]
在 umi 中引用，一直报错，页面上出不来


 warning  in ./node_modules/_@antv_g2@3.6.0-beta.14@@antv/g2/esm/plot/view.js

"export '__spreadArrays' was not found in 'tslib'

 warning  in ./node_modules/_@antv_g2@3.6.0-beta.14@@antv/g2/esm/plot/controller/legend.js

"export '__spreadArrays' was not found in 'tslib'

 warning  in ./node_modules/_@antv_g2@3.6.0-beta.14@@antv/g2/esm/plot/controller/legend.js

"export '__spreadArrays' was not found in 'tslib'

**Comment by git-lt** [comment]
![image](https://user-images.githubusercontent.com/8443758/72309685-a0ee2500-36ba-11ea-89e1-94f4b3d52a2e.png)

**Comment by kagawagao** [comment]
简单的封装了一下

[g2plot-react](https://github.com/open-data-plan/g2plot-react)

**Comment by Jackeriss** [comment]
Ant Design Charts 已经发布了：https://charts.ant.design/

**Comment by JuSanZhi** [comment]
页面多个图形，采用珊格布局，如何设置当页面变化时图形自适应。

**Comment by ZhaoTim** [comment]
> Ant Design Charts 已经发布了：https://charts.ant.design/

太逗了...刚刚去看文档，网站居然报错了....没人管
