### ISSUE TITLE
Module is not installed，，怎么破

### ISSUE THREAD

**Issue by xgj1988** [antvis/G2Plot#325]
导入  0.10.1  

代码里面： 出现  Module is not installed
import { StackColumn } from "@antv/g2plot";

**Comment by paleface001** [comment]
你好，最新版本为0.11.1，试试这个~

**Comment by xgj1988** [comment]
@paleface001  一样的。。。你们可以试试。

**Comment by hustcc** [comment]
@xgj1988 能方便提供下代码，已经错误截图吗？最好能有一个在线示例。我这边在测试环境是 ok 的~

**Comment by elaine1234** [comment]
`npm install --save @antv/g2plot`

**Comment by xgj1988** [comment]
@hustcc 没有 index.js
![image](https://user-images.githubusercontent.com/8272614/69969912-4a88b500-1558-11ea-93ea-2ecce1615280.png)

**Comment by hustcc** [comment]
@xgj1988 你需要看 lib / esm 目录中有没有 index.js

**Comment by xgj1988** [comment]
@hustcc  我就是用的 esm 里面的。。现在
