### ISSUE TITLE
🥰 [FEATURE]支持线图的坐标轴逆序

### ISSUE THREAD

**Issue by SakuraWangle** [antvis/G2Plot#3252]
支持线图中，Y坐标轴的逆序，小的值在上面，大的值在下面，同时X轴在下面
![image](https://user-images.githubusercontent.com/37700655/173540165-aa588f6b-602b-4ae6-b06c-096337a70200.png)

**Comment by visiky** [comment]
<img width="1083" alt="image" src="https://user-images.githubusercontent.com/15646325/177712696-553d9584-a632-4991-a661-19986d8f17aa.png">
