### ISSUE TITLE
🤔 [QUESTION] 区间面积图的官网示例坐标轴不对齐该怎么处理

### ISSUE THREAD

**Issue by Engelce** [antvis/G2Plot#3255]
https://g2plot.antv.vision/zh/examples/plugin/multi-view#range-area

![image](https://user-images.githubusercontent.com/87524394/174013907-134583a6-6df5-477e-84bd-67f25ce69103.png)

range值调到[0.005, 0.995]第一个点对齐了，但是后面的点还是没对齐

**Comment by ntscshen** [comment]
@Engelce 

你把上面nice注释了看看？
![image](https://user-images.githubusercontent.com/21041458/174213480-468a0abe-31bb-47d5-be1e-a7122d792b87.png)

[MetaOption.nice](https://g2plot.antv.vision/zh/docs/api/options/meta#metaoptionnice)
------
如果你在API中找不到对应字段的描述信息，建议你把源码拉下来，全局搜索一下去找。

**Comment by Engelce** [comment]
![image](https://user-images.githubusercontent.com/87524394/174743804-7e17e59c-324c-4c7a-8dbc-848b0397706c.png)
裂开，跟nice啥的都没关系，是这个tickInterval导致的，去掉 * 2就好了
