### ISSUE TITLE
有了G2Plot以后，是不是就可以不用G2了。

### ISSUE THREAD

**Issue by kaoding** [antvis/G2Plot#326]
有G2Plot和G2不同场景使用的说明和它们之间的对比。
也就是让一个新手如何在G2和G2Plot选择的问题。

**Comment by hustcc** [comment]
@kaoding G2Plot 是基于 G2 做的一层重点打磨图表体验的通用图表库。

两者并不存在一定要选择其一的问题。如果你的项目中，仅仅只有通用图表库，那么可以选择 G2Plot 去绘制，如果也存在一些自定义图形的绘制，那么可以考虑使用 G2 去绘制。
