### ISSUE TITLE
🤔 [QUESTION] 仪表盘percent为0时，仪表盘渲染了整个弧度

### ISSUE THREAD

**Issue by XUBXUE** [antvis/G2Plot#3262]
怎么才能使 在percent为0时，没有任何弧度渲染的样子

**Comment by hustcc** [comment]
@ai-qing-hai 已经排查到问题：

![image](https://user-images.githubusercontent.com/7856674/175865994-4456120b-8160-4723-bb8d-df1c4ab29cab.png)

仪表盘使用两个 geometry 绘制，一个是绘制指针，一个是绘制进度条，当 percent = 0 的时候，进度条 的数据是错误的，应该是生成这个数据的方法有问题。实际期望的数据是：

```ts
[
  {
    "range": 0,
    "type": "1",
    "percent": 0
  },
  {
    "range": 1,
    "type": "2",
    "percent": 1
  },
]
```

**Comment by XUBXUE** [comment]
麻烦解决了 回复我提醒下 辛苦啦
