### ISSUE TITLE
🐛 [BUG] 官网饼图示例 demo 有问题

### ISSUE THREAD

**Issue by hustcc** [antvis/G2Plot#3263]
### 🐛 Bug description [Please make everyone to understand it]

> Please provide a link by forking these links [G2Plot](https://codesandbox.io/s/g2plot-issue-template-gzfdq?file=/index.ts) or GitHub repo, a minimal reproduction.

* _Required_ **Link to minimal reproduction**:

### 📷 Step to reproduce

官网 [demo](https://g2plot.antv.vision/zh/examples/pie/donut#statistics)，中心文本没有自适应大小。

![image](https://user-images.githubusercontent.com/7856674/175862611-4d9faae3-1a7e-4ca8-960b-1b4adce20d9e.png)

### 🚑 Any additional [like screenshots]

* **G2Plot Version**:
* **Platform**:

**Comment by hustcc** [comment]
原因是 demo 中使用 measureTextWidth，这个方法仅仅返回 width，但是确使用了 width height 参数。

**Comment by ai-qing-hai** [comment]
@hustcc  官网没问题。  官网案例有一个 条件， 盒子比 text 大才会自适应。 
![image](https://user-images.githubusercontent.com/65594180/176127011-7e6934fb-6f1f-4b74-95a0-7b8030718184.png)

![image](https://user-images.githubusercontent.com/65594180/176126850-ee02e81b-e95a-4b17-b667-cf8889d0061b.png)
