### ISSUE TITLE
🐛 [BUG]堆叠柱状图tooltip位置出现偏移的问题

### ISSUE THREAD

**Issue by cooper1x** [antvis/G2Plot#3274]
### 🐛 Bug description [Please make everyone to understand it]

> Please provide a link by forking these links [G2Plot](https://codesandbox.io/s/g2plot-issue-template-gzfdq?file=/index.ts) or GitHub repo, a minimal reproduction.
图表容器设置css transform scale缩放后，鼠标悬停tooltip位置会出现偏移。

* _Required_ **Link to minimal reproduction**:

### 📷 Step to reproduce
https://g2plot.antv.vision/zh/examples/column/stacked#basic
任意一个示例，打开Chrome Devtool，在container上加一行代码：
```
transform:scale(0.8)
```
![image](https://user-images.githubusercontent.com/9080789/178222950-f4105b28-6263-4cf4-91db-79f96a2c8078.png)

### 🏞 Expected result
无论容器怎么加scale，鼠标悬停位置即是tooltips显示位置，比如echarts这个柱图
https://www.makeapie.cn/echarts_content/xSJJXiE1Wx.html
![image](https://user-images.githubusercontent.com/9080789/178223277-361de874-e4fe-4e5b-a39a-edb63cba97db.png)

### 🚑 Any additional [like screenshots]

* **G2Plot Version**:2.4.17
* **Platform**:macOS Chrome Dev 105.0.5148.2（正式版本）dev (x86_64)

**Comment by xueli327426** [comment]
> ### 🐛 Bug description [Please make everyone to understand it]
> > Please provide a link by forking these links [G2Plot](https://codesandbox.io/s/g2plot-issue-template-gzfdq?file=/index.ts) or GitHub repo, a minimal reproduction.
> > 图表容器设置css transform scale缩放后，鼠标悬停tooltip位置会出现偏移。
> 
> * _Required_ **Link to minimal reproduction**:
> 
> ### 📷 Step to reproduce
> https://g2plot.antv.vision/zh/examples/column/stacked#basic 任意一个示例，打开Chrome Devtool，在container上加一行代码：
> 
> ```
> transform:scale(0.8)
> ```
> 
> ![image](https://user-images.githubusercontent.com/9080789/178222950-f4105b28-6263-4cf4-91db-79f96a2c8078.png)
> 
> ### 🏞 Expected result
> 无论容器怎么加scale，鼠标悬停位置即是tooltips显示位置，比如echarts这个柱图 https://www.makeapie.cn/echarts_content/xSJJXiE1Wx.html ![image](https://user-images.githubusercontent.com/9080789/178223277-361de874-e4fe-4e5b-a39a-edb63cba97db.png)
> 
> ### 🚑 Any additional [like screenshots]
> * **G2Plot Version**:latest
> * **Platform**:macOS Chrome Dev 105.0.5148.2（正式版本）dev (x86_64)

我也遇到了这个问题，请问您解决了吗 @cooper1x

**Comment by rskmin** [comment]
请移步至 https://github.com/antvis/G2Plot/issues/1160

**Comment by hustcc** [comment]
```diff
import { Column } from '@antv/g2plot';

const stackedColumnPlot = new Column('container', {
  data,
+ supportCSSTransform: true,
  isStack: true,
  xField: 'year',
  yField: 'value',
  // ...
});
```

![image](https://user-images.githubusercontent.com/7856674/220496545-2dea9ce8-03b3-4f95-b220-c45200b2d90a.png)
