### ISSUE TITLE
🤔 [QUESTION] function的python实现方式

### ISSUE THREAD

**Issue by Eymecoo** [antvis/G2Plot#3276]
{
      geometry: 'line',
      seriesField: 'name',
      lineStyle: ({ name }) => {
        if (name === 'a') {
          return {
            lineDash: [1, 4],
            opacity: 1,
          };
        }
        return {
          opacity: 0.5,
        };
      },
    },

这样子的function怎么转成python中的代码呢，用哪一个方法？

**Comment by hustcc** [comment]
是 PyGPlot 吗？如果是，可以参考[这个文档](https://github.com/hustcc/PyG2Plot/blob/e469c7327519c848710f994ac033f41b2147c5df/README_ZH.md#%E4%BD%BF%E7%94%A8-javascript-%E5%9B%9E%E8%B0%83)。
