### ISSUE TITLE
x轴不展示没生效

### ISSUE THREAD

**Issue by WMY187** [antvis/G2Plot#3280]
![image](https://user-images.githubusercontent.com/85543917/178882551-55b8571f-d354-4b2c-9b7f-4ce76789b890.png)
![image](https://user-images.githubusercontent.com/85543917/178882591-191b0d07-f8e3-4921-ba61-76bf3488958c.png)

**Comment by ai-qing-hai** [comment]
@WMY187  1、 grid 和 line 和 tickLine 是同一级的 2、你要去除 横向的 线 得 在 yAxis.grid

**Comment by WMY187** [comment]
![image](https://user-images.githubusercontent.com/85543917/178885124-38da4c88-87d5-4530-a4fc-141e8ee28045.png)
![image](https://user-images.githubusercontent.com/85543917/178885348-62e672c7-ab16-4665-92c5-0997af3907ff.png)

丝毫动静都没有哇！！！！

**Comment by ai-qing-hai** [comment]
@WMY187 
![image](https://user-images.githubusercontent.com/65594180/179132719-467c8e21-4e23-485d-9054-ab48edebe9ac.png)
你得结合双轴图的特性来啊

**Comment by WMY187** [comment]
双轴图的特性？谢谢你的解答。
我是看IPA这么写的
![image](https://user-images.githubusercontent.com/85543917/179135312-544091f0-b99f-4381-850d-c2e8926ff0d7.png)
