### ISSUE TITLE
🐛 [BUG] 切换数据量cpu就一直很高

### ISSUE THREAD

**Issue by wuyx0914** [antvis/G2Plot#3283]
### 🐛 Bug description [Please make everyone to understand it]

> Please provide a link by forking these links [G2Plot](https://codesandbox.io/s/g2plot-issue-template-gzfdq?file=/index.ts) or GitHub repo, a minimal reproduction.

* _Required_ **Link to minimal reproduction**:

### 📷 Step to reproduce
https://g2plot.antv.vision/en/examples/dynamic-plots/basic#dynamic-spline
1. 把for (let i = -19; i <= 0; i += 1) {        改成    for (let i = -1999; i <= 0; i += 1) {
2.再把1999改回19，重复几次后，cpu保持100%以上

### 🏞 Expected result
cpu恢复正常

### 🚑 Any additional [like screenshots]
一开始
![image](https://user-images.githubusercontent.com/46918672/179442977-c451b3ae-5402-45af-b572-27921bd6f832.png)
多次修改后
![image](https://user-images.githubusercontent.com/46918672/179443282-2a65f21e-000e-47b8-8b0f-a441f17a84bc.png)

* **G2Plot Version**:
* 2.4.20
* **Platform**:

**Comment by cdx0** [comment]
切换浏览器看看会不会

**Comment by wuyx0914** [comment]
> 切换浏览器看看会不会

用chrome和firefox最新版一样的问题，数据量恢复成20也会有明显的卡顿
