### ISSUE TITLE
为什么高度一直变大🤔 [QUESTION]

### ISSUE THREAD

**Issue by hj12hj** [antvis/G2Plot#3300]
### 💻 Link to minimal reproduction

Please provide a link by forking these links [g2plot](https://codesandbox.io/s/g2plot-reproduction-template-gyej1) or GitHub repo. What is a minimal reproduction, and why is it required?

### 🏞 Expected result
<img width="941" alt="image" src="https://user-images.githubusercontent.com/52463603/181417903-99e0c1b4-556a-4d04-9321-4393b631ba88.png">

### 🚑 Any additional [like screenshots]

* **G2Plot Version**:
* **Platform**:

**Comment by visiky** [comment]
AutoFit 的时候，注意父容器要有高度，特别是flex布局下
