### ISSUE TITLE
Do not mutate iteratee in getStockData !

### ISSUE THREAD

**Issue by floydspace** [antvis/G2Plot#3301]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `@antv/g2plot@2.4.20` for the project I'm working on.

I faced with the following error on the basic config of Stock react component: `"Cannot add property trend, object is not extensible"`. The issue is caused by the code smell in the `getStockData` utils function where list elements are mutated on iterating, which basically is not good JS development practice, and I understand now why.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/@antv/g2plot/esm/plots/stock/utils.js b/node_modules/@antv/g2plot/esm/plots/stock/utils.js
index 36fbff9..7f94ee4 100644
--- a/node_modules/@antv/g2plot/esm/plots/stock/utils.js
+++ b/node_modules/@antv/g2plot/esm/plots/stock/utils.js
@@ -6,7 +6,7 @@ import { TREND_FIELD, TREND_DOWN, TREND_UP, Y_FIELD } from './constant';
  * @param yField
  */
 export function getStockData(data, yField) {
-    return map(data, function (obj) {
+    return map(data, function ({...obj}) {
         if (isArray(yField)) {
             var open_1 = yField[0], close_1 = yField[1], high = yField[2], low = yField[3];
             obj[TREND_FIELD] = obj[open_1] <= obj[close_1] ? TREND_UP : TREND_DOWN;
```

 I can make a quick PR if you accept them, just assign the ticket to me. Thank you.

**Comment by visiky** [comment]
ok~ welcome to make a pr
