### ISSUE TITLE
🥰 [FEATURE]水波图数据映射后续是否支持自定义数值单位、数据格式、单位的展示隐藏

### ISSUE THREAD

**Issue by suciy** [antvis/G2Plot#3304]
### 🧐 比如可以在数据映射中增加percentUnit, isShowPercent 属性，具体如下：
![37A8A4EB-0DB2-4C7D-BA2A-B87160283CCB](https://user-images.githubusercontent.com/22518267/182282469-3ec66e74-d016-46fc-98c4-44854a439625.png)

**Comment by visiky** [comment]
参考这个：https://g2plot.antv.antgroup.com/zh/examples/progress-plots/liquid/#style
