### ISSUE TITLE
🤔 [QUESTION] 折线图 brush 功能

### ISSUE THREAD

**Issue by xuoutput** [antvis/G2Plot#3305]
### 🐛 Question description [Please make everyone to understand it]
https://github.com/antvis/G2Plot/issues/2865
折线图的 brush 功能什么时候开放呢
<img width="1353" alt="image" src="https://user-images.githubusercontent.com/16385443/182301210-256aafb6-9cf2-4b1c-866c-b49d24bc6385.png">

### 💻 Link to minimal reproduction

Please provide a link by forking these links [g2plot](https://codesandbox.io/s/g2plot-reproduction-template-gyej1) or GitHub repo. What is a minimal reproduction, and why is it required?

### 🚑 Any additional [like screenshots]

* **G2Plot Version**:
* **Platform**:

**Comment by visiky** [comment]
https://github.com/antvis/G2Plot/issues/2865 这个不可以满足吗？

**Comment by visiky** [comment]
```ts
import { Line } from '@antv/g2plot';

fetch('https://gw.alipayobjects.com/os/bmw-prod/1d565782-dde4-4bb6-8946-ea6a38ccf184.json')
  .then((res) => res.json())
  .then((data) => {
    const line = new Line('container', {
      data,
      padding: 'auto',
      xField: 'Date',
      yField: 'scales',
      xAxis: {
        // type: 'timeCat',
        tickCount: 5,
      },
      interactions:[{type:'brush-x'}]
    });

    line.render();
  });

```
