### ISSUE TITLE
🤔 [QUESTION] scrollbar可以根据数据量的长度自动显示或不显示吗

### ISSUE THREAD

**Issue by ChaoQunPeng** [antvis/G2Plot#3321]
### 🐛 Question description [Please make everyone to understand it]
加了scrollbar属性后滚动条就直接出现了，也没法显示，数据量少也是直接出现，可以做到数据超过容器长度时，自动显示吗。

### 💻 Link to minimal reproduction

Please provide a link by forking these links [g2plot](https://codesandbox.io/s/g2plot-reproduction-template-gyej1) or GitHub repo. What is a minimal reproduction, and why is it required?

### 🚑 Any additional [like screenshots]

* **G2Plot Version**:
* "@antv/g2plot": "^2.4.20"
* **Platform**:
mac

**Comment by visiky** [comment]
目前还没有这种推断，你可以在业务层根据数据量的大小先处理下，我们会在新版本中将其考虑
