### ISSUE TITLE
折线图的背景是否支持Y轴0以上一个背景色，0以下一个背景色，Help me！

### ISSUE THREAD

**Issue by hanyongchao** [antvis/G2Plot#3327]
### 💻 Link to minimal reproduction

Please provide a link by forking these links [g2plot](https://codesandbox.io/s/g2plot-reproduction-template-gyej1) or GitHub repo. What is a minimal reproduction, and why is it required?

### 🚑 Any additional [like screenshots]

* **G2Plot Version**:
* **Platform**:

**Comment by TopAlien** [comment]
![企业微信20220823-143354](https://user-images.githubusercontent.com/33052129/186088172-a37348a7-f74a-448a-b2f8-101a9a851ee1.png)
