### ISSUE TITLE
🐛 [BUG]在水波图百分比为1时进入全屏，图表没有自适应容器宽高

### ISSUE THREAD

**Issue by konghirt** [antvis/G2Plot#3334]
### 🐛 Bug description [Please make everyone to understand it]
水波图的百分比为1时进入全屏，图表没有自适应容器宽高
https://antv-g2plot.gitee.io/zh/examples/progress-plots/liquid#basic

* _Required_ **Link to minimal reproduction**:

### 📷 Step to reproduce
percent设置为1，然后进入全屏
![image](https://user-images.githubusercontent.com/51156881/186845642-598fe9d7-27ce-4d6b-a64e-48897f35e035.png)

图表没有自适应容器，导致文本不居中
![image](https://user-images.githubusercontent.com/51156881/186845900-1e5a3b0b-20ba-44a6-86be-2fbb704781c8.png)

### 🏞 Expected result
图表自适应容器
### 🚑 Any additional [like screenshots]

* **G2Plot Version**:
* **Platform**:

**Comment by visiky** [comment]
https://g2plot.antv.antgroup.com/zh/examples/progress-plots/liquid#basic 拖拽可自适应

![水波图自适应](https://user-images.githubusercontent.com/15646325/206890638-99d4811a-14f5-428e-a512-5b94dbcd7f20.gif)
