### ISSUE TITLE
🐛 [BUG]仪表盘，当percent为0时，仪表图形颜色被充满

### ISSUE THREAD

**Issue by zbczbc2006** [antvis/G2Plot#3338]
### 🐛 Bug description [Please make everyone to understand it]
https://g2plot.antv.vision/zh/examples/progress-plots/gauge#basic
### 官方例子，将percent设置为0，仪表颜色被100%绿色充满
![image](https://user-images.githubusercontent.com/19605617/187163913-eddb338d-c419-4831-9f15-74b0a5eb2624.png)

### 正常应该与设置为0.001一样，颜色是底色的灰色
![image](https://user-images.githubusercontent.com/19605617/187164478-b5776bd5-8de7-4e07-818c-f361a844f9f5.png)

**Comment by visiky** [comment]
已修复
