### ISSUE TITLE
静态资源连接失效

### ISSUE THREAD

**Issue by nan3302** [antvis/G2Plot#334]
```
<!-- 引入本地脚本 -->
<script src="./g2plot.js"></script>
<!-- 引入在线资源 -->
<script src="https://gw.alipayobjects.com/os/lib/antv/g2plot/1.0.0-beta/dist/g2plot.min.js"></script>
```
其中地址： https://gw.alipayobjects.com/os/lib/antv/g2plot/1.0.0-beta/dist/g2plot.min.js 失效状态

**Comment by nan3302** [comment]
node.js 执行下来的 g2plot.js  也是有问题的  
在多折线下  执行 案例 
https://antv-g2plot.gitee.io/zh/examples/line/multiple 
会提示 Uncaught TypeError: w is not a function
    at e.translate (time.js:18)
    at time.js:44
    at map.js:10
    at u (each.js:10)
    at Module.se (map.js:9)
    at e._init (time.js:44)
    at e.t (base.js:10)
    at new e (time.js:14)
    at t.createScale (scale.js:52)
    at e._initScale (view.js:752)

**Comment by zqlu** [comment]
- 推荐使用npm包来使用g2plot `npm install --save @antv/g2plot`
```js
import { Line } from '@antv/g2plot'
```
- 如果需要UMD静态资源，可以使用 `https://unpkg.com/@antv/g2plot@latest/dist/g2plot.js`

**Comment by nan3302** [comment]
老的项目  纯静态的 谢谢

**Comment by JLoveI** [comment]
静态资源引用有问题，Uncaught (in promise) TypeError: w is not a function
