### ISSUE TITLE
请问下，雷达图的维度 Title 在哪更改🤔 [QUESTION]

### ISSUE THREAD

**Issue by HuangHongRui** [antvis/G2Plot#3342]
### 💻 Link to minimal reproduction

Please provide a link by forking these links [g2plot](https://codesandbox.io/s/g2plot-reproduction-template-gyej1) or GitHub repo. What is a minimal reproduction, and why is it required?

### 🚑 Any additional [like screenshots]

* **G2Plot Version**:
* **Platform**:

![image](https://user-images.githubusercontent.com/26321899/187643430-008a1cc4-4b09-4c0d-b72a-351a8ca8fdd7.png)

找不到类似 Echart 这个API
![image](https://user-images.githubusercontent.com/26321899/187643714-82608405-5da5-4807-a599-3b0cfec0aa0e.png)

**Comment by TopAlien** [comment]
<img width="787" alt="123" src="https://user-images.githubusercontent.com/33052129/187653822-86ac5f87-48fd-4043-a820-d51b01ceaa84.png">

**Comment by HuangHongRui** [comment]
@TopAlien Thanks~ 这个我知道，没有其他不改变数据源的方法了吗？ =。。=

**Comment by HuangHongRui** [comment]
> <img alt="123" width="787" src="https://user-images.githubusercontent.com/33052129/187653822-86ac5f87-48fd-4043-a820-d51b01ceaa84.png">

有没有其他方法？另外有没这部分的样式接口暴露出来？我需要对它们的字体样式进行修改~ T_T

**Comment by TopAlien** [comment]
<img width="736" alt="企业微信20220908-110625@2x" src="https://user-images.githubusercontent.com/33052129/189025096-6ea8f2dc-d47b-4457-ae17-40503297b6bc.png">
