### ISSUE TITLE
🤔 [QUESTION] 初始化显示 toolTip

### ISSUE THREAD

**Issue by TopAlien** [antvis/G2Plot#3343]
### 💻 Link to minimal reproduction

Please provide a link by forking these links [g2plot](https://codesandbox.io/s/g2plot-reproduction-template-gyej1) or GitHub repo. What is a minimal reproduction, and why is it required?

### 🏞 Expected result
<img width="714" alt="123123123" src="https://user-images.githubusercontent.com/33052129/187657109-7d4c1c1c-b229-4b56-bb7c-34abd9643041.png">
使用联动图标Mix 如何默认高亮一个坐标点，并显示其tooltip
### 🚑 Any additional [like screenshots]

* **G2Plot Version**:
* **Platform**:

**Comment by TopAlien** [comment]
![13123](https://user-images.githubusercontent.com/33052129/187818010-3837e69b-7a94-4264-9f1f-01d5c0c6740c.png)
<img width="1075" alt="99999" src="https://user-images.githubusercontent.com/33052129/187818015-67412254-6c6b-456a-b9ab-dddb0bb11019.png">
已解决

**Comment by visiky** [comment]
手动触发tooltip展示
