### ISSUE TITLE
🤔 请问水波球怎么设置渐变色（多色）

### ISSUE THREAD

**Issue by sunjiesama** [antvis/G2Plot#3356]
按照文档中的方法直接没有颜色了，是我哪里写的不对吗，还请大佬指教一下orz
![image](https://user-images.githubusercontent.com/54022918/190612982-62476985-7e97-43c8-b553-ef78e3dabd28.png)

**Comment by visiky** [comment]
水波图没有 colorField 去做数据分组，设置渐变色用绘图属性的渐变色就行 [文档](http://g2plot.antv.antgroup.com/api/graphic-style#%E7%BA%BF%E6%80%A7%E6%B8%90%E5%8F%98)

```js
import { Liquid } from '@antv/g2plot';

const liquidPlot = new Liquid('container', {
  percent: 0.25,
  outline: {
    border: 4,
    distance: 8,
  },
  wave: {
    length: 128,
  },
  liquidStyle: {
    fill: 'l(90) 0:#1890ff 0.3:#ffffff 1:#7ec2f3 '
  }
});
liquidPlot.render();
```

<img width="657" alt="image" src="https://user-images.githubusercontent.com/15646325/206858582-b6d0ac68-db3f-4da5-a4dc-ce5bfd555982.png">
