### ISSUE TITLE
请问可以设置竖向缩略轴吗 ? 🤔 [QUESTION]

### ISSUE THREAD

**Issue by YongHao0** [antvis/G2Plot#3359]
### 🐛 Question description [Please make everyone to understand it]

从文档未找到如何设置竖向缩略轴, 或者说如何同时设置横向、竖向缩略轴

### 💻 Link to minimal reproduction

类似于: https://echarts.apache.org/examples/zh/editor.html?c=mix-zoom-on-value

### 🏞 Expected result

支持竖向缩略轴

### 🚑 Any additional [like screenshots]

* **G2Plot Version**: 2.4.7
* **Platform**: Mac、Win

**Comment by visiky** [comment]
我们会在新版本支持

**Comment by bmob77** [comment]
> 我们会在新版本支持

请问现在支持了吗？
