### ISSUE TITLE
打包后产物违反CSP策略

### ISSUE THREAD

**Issue by supuwoerc** [antvis/G2Plot#3371]
### 🐛 Vue打包部署在cdn后，发现页面报错，排查到是违反了csp策略

![企业微信截图_1665629189634](https://user-images.githubusercontent.com/36561218/195488790-ecf4f07a-e2e8-4d6a-80b9-1c33f19c2292.png)

### 🏞 请问如何解决这个报错

* **"@antv/g2plot": "^2.4.20"**:
* **"vue": "^2.6.11"**:

**Comment by supuwoerc** [comment]
具体报错如下：
![企业微信截图_16656351122817](https://user-images.githubusercontent.com/36561218/195501217-13122085-b25d-4c5b-b348-50fe5b517cca.png)

**Comment by visiky** [comment]
<img width="454" alt="image" src="https://user-images.githubusercontent.com/15646325/200467428-4e232837-c387-4407-8b09-f07caca649ab.png">

**Comment by supuwoerc** [comment]
> <img alt="image" width="454" src="https://user-images.githubusercontent.com/15646325/200467428-4e232837-c387-4407-8b09-f07caca649ab.png">

就是我提的问哦，🤣🤣🤣 @visiky
