### ISSUE TITLE
🐛 [BUG] vite项目引用g2plot报错

### ISSUE THREAD

**Issue by Frank-Mei** [antvis/G2Plot#3378]
### 🐛 Bug description [Please make everyone to understand it]

![image](https://user-images.githubusercontent.com/40459063/196618489-6cb7ae68-8e44-43db-b55d-284983ac80c9.png)

![image](https://user-images.githubusercontent.com/40459063/196618562-6e94e7d8-27e0-4b82-b92b-678bce043f2f.png)

* _Required_ **Link to minimal reproduction**:

### 🚑 Any additional [like screenshots]

* **G2Plot Version**: 2.4.20:
* **Platform**:

**Comment by visiky** [comment]
可以给一个最小复现demo吗？比如看下你是怎么引入G2Plot 以及项目是怎么配置的。错误信息看不到出问题；
给一个复现codesanbox（应该也可以用vite）然后新建一个issue
