### ISSUE TITLE
🐛 [BUG]折线图Y轴一些汉字最顶部会被遮住

### ISSUE THREAD

**Issue by gaojian88888888** [antvis/G2Plot#3379]
![image](https://user-images.githubusercontent.com/33544855/196646315-791c2ba1-db7e-4ae9-b86d-c8973f3c67a9.png)
![image](https://user-images.githubusercontent.com/33544855/196646494-53a99dc7-e122-4c9d-90e8-b107fbd9a75c.png)

一些汉字最顶部会被遮住，这种情况下改如何解决问题

**Comment by visiky** [comment]
appendPadding 顶部预留多一些空间，参考：#3374
