### ISSUE TITLE
g2 在实现动画wave-in的时候如何在尾部添加动画效果的label  相当于以前版本的clipingWithData

### ISSUE THREAD

**Issue by 1052130497** [antvis/G2Plot#3383]
![image](https://user-images.githubusercontent.com/116713792/197975831-7fdc78da-f52d-4801-88e4-89810f96241e.png)
![image](https://user-images.githubusercontent.com/116713792/197976744-81814280-0a08-4ffd-9d6a-4e219346736c.png)
下面的方法也会出现报错
![image](https://user-images.githubusercontent.com/116713792/197977280-daf3db0a-6a5a-4577-9c1d-9b2cb91cae0c.png)

**Comment by 1052130497** [comment]
![image](https://user-images.githubusercontent.com/116713792/197975971-6294ef4b-05ca-4111-a00b-c03ba6c29a59.png)
文档上面利用label中的type属性可以实现,但是在2.4.20的版本中内置的type:'line'已经舍去了

**Comment by 1052130497** [comment]
g2百度上真搜不到文档   自定义动画里面的参数什么意思也没有  太难了

**Comment by visiky** [comment]
duplicate with #3385
