### ISSUE TITLE
g2官网上折线图尾部添加了文本标签，但是点进去后就没有这个文本标签

### ISSUE THREAD

**Issue by 1052130497** [antvis/G2Plot#3385]
https://g2plot.antv.vision/zh/examples/gallery
![image](https://user-images.githubusercontent.com/116713792/198533748-6875ce7b-9efe-4f63-8979-fbca0eaff338.png)
![image](https://user-images.githubusercontent.com/116713792/198534055-7a9e5f0c-db7a-400c-9117-b6d97824788d.png)

**Comment by visiky** [comment]
这个功能会在新版本提供
