### ISSUE TITLE
如何设置渐变色

### ISSUE THREAD

**Issue by ywcr** [antvis/G2Plot#339]
如何设置渐变色

**Comment by paleface001** [comment]
以面积图为例，可以这样写：
```
areaStyle:{
   fill:'l(0) 0:#ffffff 0.5:#7ec2f3 1:#1890ff'
}
```
为面积图形设置了一个线性渐变，详细可以参考 [G使用文档](https://www.yuque.com/antv/g6/smhvyn#a9fc2d0f)，我们也会尽快把G2Plot进行图形样式设置的文档补齐。

<img width="668" alt="屏幕快照 2019-12-04 下午5 52 23" src="https://user-images.githubusercontent.com/5888974/70132284-dddbfa80-16be-11ea-87fe-1a2e73d5240d.png">

**Comment by ywcr** [comment]
面积图这样使用是可以的，条形图可以这样使用吗？ color:'l(90) 0:#4493fe 1:#ffffff'  

这样出现了其他的问题，导致条形图上面显示的数据有一部分消失了

import { Bar } from '@antv/g2plot';

const data = [
  { 地区: '华东', 销售额: 4684506.442 },
  { 地区: '中南', 销售额: 4137415.0929999948 },
  { 地区: '东北', 销售额: 2681567.469000001 },
  { 地区: '华北', 销售额: 2447301.017000004 },
  { 地区: '西南', 销售额: 1303124.508000002 },
  { 地区: '西北', 销售额: 815039.5959999998 },
];

const barPlot = new Bar(document.getElementById('container'), {
  title: {
    visible: true,
    text: '基础条形图',
  },
  forceFit: true,
  data,
  xField: '销售额',
  yField: '地区',
  color:'l(90) 0:#97d0fd 1:#5fa3fc',
  xAxis: {
    formatter: (v) => Math.round(v / 10000) + '万',
  },
});

barPlot.render();


可以尝试一下。

**Comment by ywcr** [comment]
或者使用
```
barStyle:{
     fill:'l(90) 0:#97d0fd 1:#5fa3fc',
}
```
不生效
