### ISSUE TITLE
Legend type definition problem🐛 [BUG]

### ISSUE THREAD

**Issue by Like-late-rain** [antvis/G2Plot#3394]
Setting offsetY: 12 in legend reports a type error, cannot assign number to Legend, I find that Legend's type is incorrectly defined. Hopefully it will be resolved in time

**Comment by Like-late-rain** [comment]
![飞书20221108-150157](https://user-images.githubusercontent.com/71917676/200496519-30d5a983-e6d6-45c5-a3c7-f3c500bb951d.jpeg)
![Uploading 飞书20221108-150208.jpeg…]()

**Comment by Like-late-rain** [comment]
![飞书20221108-150208](https://user-images.githubusercontent.com/71917676/200496680-092e972e-5075-4cc5-9a59-591139684ce1.jpeg)

**Comment by visiky** [comment]
mix 图表的图例配置是：
```
legend: {
   [fieldName]: {
       offsetY: 12
   } 
}
```
