### ISSUE TITLE
如何格式化 tooltip 里面的 yField 

### ISSUE THREAD

**Issue by cai148480** [antvis/G2Plot#341]
比如 `yField: value` , 默认 tooltip 里面的显示的是 value ，想让value变成中文的

**Comment by ywcr** [comment]
自定义

**Comment by ywcr** [comment]
或者 "yField": "调用次数"

**Comment by paleface001** [comment]
可以通过`meta`配置项进行设置：
```
meta:{
   value:{ // 字段名
          alias:'中文名称'
   }
},
```

**Comment by cai148480** [comment]
好的，已解决，感谢！

**Comment by paleface001** [comment]
> 好的，已解决，感谢！

欢迎给我们star一下哦

**Comment by cai148480** [comment]
好，已star，话说文档在哪里有 meta 这个配置项呀

**Comment by paleface001** [comment]
> 好，已star，话说文档在哪里有 meta 这个配置项呀

文档里还没放，我们会尽快加上 😁

**Comment by ywcr** [comment]
我都对着g2文档看。

**Comment by ywcr** [comment]
如何格式化tooltip中的数据呢？ 我现在格式化都是自定义tooltip 有没有配置可以直接格式化
