### ISSUE TITLE
🤔 [QUESTION]G2PLOT areaStyle怎么给多个折线面积图设置渐变色？

### ISSUE THREAD

**Issue by li-guanlong** [antvis/G2Plot#3410]
### 💻 Link to minimal reproduction

![image](https://user-images.githubusercontent.com/54611134/204939904-34b78eda-4d0b-48d1-8e01-396fea5c46bc.png)

* **G2Plot Version**: 2.4.20
* **Platform**: Vue 2.7

**Comment by visiky** [comment]
渐变色 [文档](http://g2plot.antv.antgroup.com/api/graphic-style#%E7%BA%BF%E6%80%A7%E6%B8%90%E5%8F%98)

**Comment by PossibleMaybe** [comment]
分档上并没有回答提问的问题
