### ISSUE TITLE
柱状图、条形图中xAxis属性的label属性中的autoEllipsis配置不生效

### ISSUE THREAD

**Issue by 532pyh** [antvis/G2Plot#3418]
![QQ截图20221209113046](https://user-images.githubusercontent.com/26398280/206618032-75c2a5a3-ae6d-4d28-b308-1bf854b2d1cf.png)

**Comment by visiky** [comment]
会在新版本中解决

**Comment by aldo-sanchez** [comment]
Is this still not working?
