### ISSUE TITLE
本地正常，打包上线后，Y轴不显示且报错

### ISSUE THREAD

**Issue by 531431988** [antvis/G2Plot#345]
本地效果
![image](https://user-images.githubusercontent.com/8703951/70212714-c9f1d080-1772-11ea-9dbb-0578466de904.png)
打包线上效果
![image](https://user-images.githubusercontent.com/8703951/70212742-d6762900-1772-11ea-81aa-9b52086e5ac7.png)
![image](https://user-images.githubusercontent.com/8703951/70212754-dc6c0a00-1772-11ea-8abc-118cbfa43315.png)
这可能是什么问题

**Comment by elaine1234** [comment]
没数据没源码靠截图如何 debug (摊手)

**Comment by 531431988** [comment]
https://g2plot.antv.vision/zh/examples/column/stack#connected-area-style
源码就是这个，数据用的，而且我在官网上测试也是正常的
[{"year":"2006","type":"湖北","value":10},{"year":"2006","type":"湖南","value":15},{"year":"2006","type":"广东","value":9},{"year":"2006","type":"浙江","value":6},{"year":"2007","type":"湖北","value":12},{"year":"2007","type":"湖南","value":18},{"year":"2007","type":"广东","value":9},{"year":"2007","type":"浙江","value":4},{"year":"2008","type":"湖北","value":5},{"year":"2008","type":"湖南","value":20},{"year":"2008","type":"广东","value":8},{"year":"2008","type":"浙江","value":2},{"year":"2009","type":"湖北","value":1},{"year":"2009","type":"湖南","value":15},{"year":"2009","type":"广东","value":5},{"year":"2009","type":"浙江","value":4},{"year":"2010","type":"湖北","value":2},{"year":"2010","type":"湖南","value":10},{"year":"2010","type":"广东","value":4},{"year":"2010","type":"浙江","value":2},{"year":"2011","type":"湖北","value":3},{"year":"2011","type":"湖南","value":12},{"year":"2011","type":"广东","value":6},{"year":"2011","type":"浙江","value":3},{"year":"2012","type":"湖北","value":4},{"year":"2012","type":"湖南","value":15},{"year":"2012","type":"广东","value":8},{"year":"2012","type":"浙江","value":1},{"year":"2013","type":"湖北","value":6},{"year":"2013","type":"湖南","value":11},{"year":"2013","type":"广东","value":9},{"year":"2013","type":"浙江","value":4},{"year":"2014","type":"湖北","value":10},{"year":"2014","type":"湖南","value":13},{"year":"2014","type":"广东","value":9},{"year":"2014","type":"浙江","value":5}]

**Comment by 531431988** [comment]
其他一摸一样，就换了个数，打包就Y轴没了，后面的联通区域也没有，报错，本地和官网一切正常，可能是什么问题呢？

**Comment by paleface001** [comment]
能把图表配置项也发一下吗？

**Comment by RaoHai** [comment]
cc https://github.com/antvis/G2/issues/1848

**Comment by neekko33** [comment]
同样碰到这个问题了，本地环境和测试环境都没问题，一到线上环境就报错...现在有什么解决办法么

**Comment by paleface001** [comment]
已在g2 3.6新版本修复
