### ISSUE TITLE
🐛 [BUG]export 'Scale' (reexported as 'Scale') was not found in '@antv/scale' ]...

### ISSUE THREAD

**Issue by Whering** [antvis/G2Plot#3459]
export 'Scale' (reexported as 'Scale') was not found in '@antv/scale' (possible exports: Band, Base, Constant, Continuous, DURATION_DAY, DURATION_HOUR, DURATION_MINUTE, DURATION_MONTH, DURATION_SECOND, DURATION_WEEK, DURATION_YEAR, Diverging, Identity, Linear, Log, Ordinal, Point, Pow, Quantile, Quantize, Sequential, Sqrt, Threshold, Time, createInterpolateColor, createInterpolateNumber, createInterpolateValue, d3Log, d3Ticks, d3Time, rPretty, wilkinsonExtended)

**Comment by Whering** [comment]
The problem seems to appear in version 2.4.24

**Comment by KuduroJS** [comment]
+1，解决了吗？
