### ISSUE TITLE
🥰 [FEATURE] 回归散点图增加显示拟合函数的配置项

### ISSUE THREAD

**Issue by Cuiyansong** [antvis/G2Plot#3474]
### 🥰 Features description [Please make everyone to understand it]
希望如ECharts回归散点图一样，允许展示回归后的函数方程式（例如下图红框中的内容），进而判断回归参考线是否有意义。

### 🧐 What does the proposed API look like
最终可能实现的样式基本可以参考[G2的示例](https://g2.antv.antgroup.com/zh/examples/analysis/regression/#polynomial-regression)，唯一需要开发的从regression函数（如d3-regression中的[out](https://github.com/HarryStevens/d3-regression/blob/master/src/linear.js)值）中获取不同回归函数的方程式替代G2示例中的label.text中的内容，这样是否合理？

### 🚑 Any additional [like screenshots]
ECharts示例参考：
![WX20230221-nihe](https://user-images.githubusercontent.com/4497555/220293685-033294ef-b4f6-471b-b2e1-76f24af46e03.png)

**Comment by hustcc** [comment]
@Cuiyansong 在 G2 中这么做还是挺合理的，到 G2Plot 中，也有相关的 [demo](http://g2plot.antv.antgroup.com/examples/scatter/scatter/#line)。你不确定是否合理的是指什么？

**Comment by Cuiyansong** [comment]
我期望的需求是在图形上显示出回归函数的方程式，回归方程式是从运算的函数中获取的，而不是在外部（可以使用G2Plot的RegressionLine配置参数中的algorithm+d3-regression计算并获取，但是显示在G2Plot上也有一定的开发量）或者如[G2的示例](https://g2.antv.antgroup.com/zh/examples/analysis/regression/#polynomial-regression)中的“写死的/固定的”一个方程式。

不确定是否合理的是：在G2Plot中扩展RegressionLine配置参数，例如增加项{ showEquation: boolean }, 如果为true的话，则显示的效果类似上面的EChart的现实方式（红框内的方程式）

**Comment by Cuiyansong** [comment]
再确认下，目前在G2Plot中显示上图中红框内的方程式吧？在不扩展regression { algorithm } 配置的方式下。

**Comment by Cuiyansong** [comment]
参考了源码的adaptor.ts中的[regressionLine]()函数，大体改造思路如下：

step1:  开启显示
```javascript
regressionLine: {
    showEquation: true
}
```

step2: 改造[util.ts]()中的getPath方法，增加equation值返回
<img width="526" alt="image" src="https://user-images.githubusercontent.com/4497555/220323648-77fc58ab-8858-482f-8f17-9476f56349b0.png">

step3: 使用annotation显示方程式文本值
<img width="542" alt="image" src="https://user-images.githubusercontent.com/4497555/220323908-20e0f8f8-25f4-4836-ad06-8d22bd9c556d.png">

**Comment by hustcc** [comment]
@Cuiyansong 👍🏻 你的思路是对的，应该是需要内置一个文本，显示公式的，以及公式文本的样式。有兴趣来 PR 吗？

**Comment by Cuiyansong** [comment]
可以试试

**Comment by Cuiyansong** [comment]
@hustcc 您好，已经提交了一个PR，方便的时候帮忙Review一下，不足的地方在补齐。
