### ISSUE TITLE
🐛 [BUG] 组件 Line 有内存泄露

### ISSUE THREAD

**Issue by jayrom123** [antvis/G2Plot#3475]
### 🐛 Bug description [Please make everyone to understand it]

React 17 版本下：初步推断组件Line内部的 size-sensors 使用不当或者此依赖包有bug，导致 Line 组件卸载后，仍然保留引用。

> demo: https://codesandbox.io/s/distracted-sound-9rphg8?file=/index.js

操作步骤： 

1. 初始状态下，用devtools 记录memory
2. 操作卸载按钮，多点击几次
3. 再次记录memory
4. 发现很多内存引用仍然存在

**Comment by hustcc** [comment]
ref: https://github.com/hustcc/size-sensor/issues/17 内部实现中的 sensorPool 使用的一个简单的 object，存在泄漏。
