### ISSUE TITLE
条形图使用 渐变 导致label不显示了

### ISSUE THREAD

**Issue by ywcr** [antvis/G2Plot#348]

**Comment by ywcr** [comment]
条形图使用 color:'l(90) 0:#4493fe 1:#ffffff'

**Comment by ywcr** [comment]
label 设置 `position:'right'` 可以显示出来 只要在柱子上就显示不出

**Comment by paleface001** [comment]
> label 设置 `position:'right'` 可以显示出来 只要在柱子上就显示不出
把label上设置默认适应图形颜色的配置项 `adjustColor`关闭即可
```
label:{
  adjustColor: false
}
```

**Comment by ywcr** [comment]
这种情况呢，如何解决




| |
yao_wr
|
|
邮箱：yao_wr@126.com
|

Signature is customized by Netease Mail Master

在2019年12月06日 10:26，paleface001 写道：

label 设置 position:'right' 可以显示出来 只要在柱子上就显示不出
把label上设置默认适应图形颜色的配置项 adjustColor关闭即可

label:{

  adjustColor: false

}

**Comment by ywcr** [comment]
好像传不进来图片 
`import { Bar } from '@antv/g2plot';

const data = [
  { 地区: '华东', 销售额: 4684506.442 },
  { 地区: '中南', 销售额: 4137415.0929999948 },
  { 地区: '东北', 销售额: 2681567.469000001 },
  { 地区: '华北', 销售额: 2447301.017000004 },
  { 地区: '西南', 销售额: 1303124.508000002 },
  { 地区: '西北', 销售额: 8150392.5959999998 },
];

const barPlot = new Bar(document.getElementById('container'), {
  title: {
    visible: true,
    text: '基础条形图',
  },
  forceFit: true,
  data,
  xField: '销售额',
  yField: '地区',
  xAxis: {
    formatter: (v) => v + 'ms',
  },
  label: {
    visible: true,
    position: 'left', // options: left / middle / right
  },
});

barPlot.render();
`

这是条形图的代码，麻烦可否试一下，格式化后 文字位置出现了变化。

**Comment by paleface001** [comment]
对坐标轴文本进行格式化：
```
xAxis:{
  label:{
     formatter: (v) => v + 'ms'
  }
}
```

同样的，如果想对坐标轴标题进行格式化：
```
xAxis:{
  title:{
     visible: true,
     formatter: (v) => v + 'ms'
  }
}
```
`

**Comment by ywcr** [comment]
`xAxis:{
  label:{
     formatter: (v) => v + 'ms'
  }
}`

这样是不生效的。

**Comment by ywcr** [comment]
`xAxis: {
    formatter: (v) => v + 'ms',
  },`

这样使用是可以的，不知道是我哪里配置出问题了吗？

**Comment by ywcr** [comment]
或者这样使用
`
label: {
    visible: true,
    formatter: (v) => v + 'ms',
    position: 'left', // options: left / middle / right
  },
`
但是也会出现label 位置与其他不在同一水平线上

**Comment by paleface001** [comment]
你是想格式化坐标轴标签，还是图形标签？

**Comment by ywcr** [comment]
图形标签

**Comment by ywcr** [comment]
`xAxis: {
    formatter: (v) => Math.round(v / 10000) + '万',
  }
  `
这是代码演示中配置项

以下是API文档

`label: {
     formatter: (v) => Math.round(v / 10000) + '万',
  },`

label
optional

visible: boolean    图形标签是否显示
position: 'top' | 'middle' | 'bottom'    图形标签相对于柱形的位置
formatter: function  对 label 的显示文本进行格式化。
offsetX: number 在 label 位置的基础上再往 x 方向的偏移量。
offsetY: number 在 label 位置的基础上再往 y 方向的偏移量。
style: object 配置 label 文本

这两个配置有区别吗？  对于条形图来说

**Comment by paleface001** [comment]
刚在demo里试了一下，这是因为文本过长，条形内部放不开了，于是自动放置在了图形外面，看来要开配置项

**Comment by paleface001** [comment]
#351

**Comment by ywcr** [comment]
那把label放在条形图右侧过长导出超出图表是不是也得想法处理一下了，

**Comment by paleface001** [comment]
> 那把label放在条形图右侧过长导出超出图表是不是也得想法处理一下了，

U got it，少年  这个是肯定要默认处理好的

**Comment by ywcr** [comment]
😁，我是测试人员了emoji。

**Comment by paleface001** [comment]
> 😁，我是测试人员了emoji。

还请不要大意，继续测试 😜

**Comment by ywcr** [comment]
哈喽，打扰一下。
目前在react中使用图表 ，把图表单独做了组件
在table中使用图表时切换分页图表并未重新渲染（除图表外其他数据已经更新，使用echart时也未遇到这个问题）
第二页的图表用了第一次使用的数据
图表的id也发生了变化 数据未变更

是需要在哪里重置一下图表吗？




| |
yao_wr
|
|
邮箱：yao_wr@126.com
|

Signature is customized by Netease Mail Master

在2019年12月06日 11:31，paleface001 写道：

😁，我是测试人员了emoji。

还请不要大意，继续测试 😜

**Comment by ywcr** [comment]
如果更新了数据，图表会发生变化吗？

**Comment by paleface001** [comment]
> 如果更新了数据，图表会发生变化吗？

只做数据更新，不涉及其他配置项的话，可以用changeData()方法
