### ISSUE TITLE
条形图格式化加文字之后，条形图label位置发生变化，与其他文字不在同一水平线上

### ISSUE THREAD

**Issue by ywcr** [antvis/G2Plot#349]
xAxis: {
        "title": {
          "visible": false,
        },
        formatter: (v) => (`${v}`.replace(/\d{1,3}(?=(\d{3})+$)/g, s => `${s},`))+unit,
 },

**Comment by paleface001** [comment]
> formatter: (v) => (`${v}`.replace(/\d{1,3}(?=(\d{3})+$)/g, s => `${s},`))+unit,

你是想格式化坐标轴文本吗？

**Comment by ywcr** [comment]
是的 使用的条形图，

**Comment by ywcr** [comment]
`
import { Bar } from '@antv/g2plot';

const data = [
{ 地区: '华东', 销售额: 4684506.442 },
{ 地区: '中南', 销售额: 4137415.0929999948 },
{ 地区: '东北', 销售额: 2681567.469000001 },
{ 地区: '华北', 销售额: 2447301.017000004 },
{ 地区: '西南', 销售额: 1303124.508000002 },
{ 地区: '西北', 销售额: 8150392.5959999998 },
];

const barPlot = new Bar(document.getElementById('container'), {
title: {
visible: true,
text: '基础条形图',
},
forceFit: true,
data,
xField: '销售额',
yField: '地区',
xAxis: {
formatter: (v) => v + 'ms',
},
label: {
visible: true,
position: 'left', // options: left / middle / right
},
});

barPlot.render();
`

这是条形图的代码，麻烦可否试一下，格式化后 文字位置出现了变化。
