### ISSUE TITLE
Label (图形标签）配置项优化

### ISSUE THREAD

**Issue by paleface001** [antvis/G2Plot#351]
- [x]  柱状图、条形图目前默认position为middle的情况下，label过长导致图形放置不下的时候，默认将label移至图形外面。 现在需要将这个功能开放为配置项 `adjustPosition`，使用户可控。  #349 

- [ ] 加入数据精度配置项

- [ ] 加入单位配置项

- [ ]  每一个图表的默认配置要体现在文档里，否则用户不明所以会认为是bug

**Comment by zqlu** [comment]
这个我来改吧

**Comment by paleface001** [comment]
> 这个我来改吧

刀哥棒棒哒！

**Comment by ywcr** [comment]
y轴label也会出现文字过长超出图形看不到

**Comment by zqlu** [comment]
> y轴label也会出现文字过长超出图形看不到

有DEMO或者截图看下吗

**Comment by ywcr** [comment]
`
import { Bar } from '@antv/g2plot';

const data = [
  { 地区: '华东dsfljsdalkfjklasdjflkjasldf', 销售额: 4684506.442 },
  { 地区: '中南施蒂利克放假啊快来事点击分类卡视角都分开了', 销售额: 4137415.0929999948 },
  { 地区: '东北', 销售额: 2681567.469000001 },
  { 地区: '华北', 销售额: 2447301.017000004 },
  { 地区: '西南', 销售额: 1303124.508000002 },
  { 地区: '西北', 销售额: 815039.5959999998 },
];

const barPlot = new Bar(document.getElementById('container'), {
  title: {
    visible: true,
    text: '基础条形图',
  },
  forceFit: true,
  data,
  xField: '销售额',
  yField: '地区',
  xAxis: {
  },
  label: {
    visible: true,
    position: 'right', // options: left / middle / right
  },
});

barPlot.render();

`

这个是右侧超出的，左侧超出在demo中弄不出来，使用中有这个问题，左侧label过长。

**Comment by ywcr** [comment]
还有一个问题，第一次图表加载没有数据，x轴与y轴都是空，使用changeData更新数据之后左侧label没有把宽度撑起来。 

左侧label过长被隐藏可能也是这个问题。

**Comment by ywcr** [comment]
第一次没有数据


第二次 更新数据 

使用
repaint() 也没有作用

在 2019-12-11 19:17:15，"Zhiqiang Lu" <notifications@github.com> 写道：


y轴label也会出现文字过长超出图形看不到

有DEMO或者截图看下吗

**Comment by ywcr** [comment]
![1576130820786](https://user-images.githubusercontent.com/8427087/70689490-67a74b80-1cef-11ea-9a7c-4634832a09c1.jpg)
![WechatIMG592](https://user-images.githubusercontent.com/8427087/70689513-74c43a80-1cef-11ea-9a4c-d000a29a9b50.png)

**Comment by 18402025768** [comment]
用法是怎么用,我之间想隐藏了
