### ISSUE TITLE
🐛 [BUG]官网k线图多层图示例显示不正常

### ISSUE THREAD

**Issue by cdx111** [antvis/G2Plot#3526]
### 🐛 Bug description [Please make everyone to understand it]
https://g2plot.antv.antgroup.com/zh/examples/plugin/multi-view/#customized-stock
stock没有显示出来
> Please provide a link by forking these links [G2Plot](https://codesandbox.io/s/g2plot-issue-template-gzfdq?file=/index.ts) or GitHub repo, a minimal reproduction.
https://g2plot.antv.antgroup.com/zh/examples/plugin/multi-view/#customized-stock
* _Required_ **Link to minimal reproduction**:
https://g2plot.antv.antgroup.com/zh/examples/plugin/multi-view/#customized-stock
### 📷 Step to reproduce
https://g2plot.antv.antgroup.com/zh/examples/plugin/multi-view/#customized-stock
### 🏞 Expected result
预期stock应该正常显示
### 🚑 Any additional [like screenshots]

* **G2Plot Version**:
* **Platform**:

**Comment by rrwang05** [comment]
同遇到这个问题

**Comment by hustcc** [comment]
感谢反馈，demo 有问题。可以把 stock 写在 line 的后面。

```ts
[
  { ...line }
  {
    type: 'stock',
    // 共享顶层 data
    top: true,
    options: {
      xField: 'trade_date',
      yField: ['open', 'close', 'high', 'low'],
    },
  },
]
```
