### ISSUE TITLE
🤔如何动态更新slider的位置?

### ISSUE THREAD

**Issue by cdx111** [antvis/G2Plot#3527]
### 🐛 Question description [Please make everyone to understand it]
🤔如何动态更新slider的位置?
### 💻 Link to minimal reproduction

Please provide a link by forking these links [g2plot](https://codesandbox.io/s/g2plot-reproduction-template-gyej1) or GitHub repo. What is a minimal reproduction, and why is it required?

### 🚑 Any additional [like screenshots]

* **G2Plot Version**:
* **Platform**:

**Comment by controllerz** [comment]
![image](https://user-images.githubusercontent.com/22693880/233281623-441eab94-63fb-41ae-b33f-0efa84db0e40.png)
plot.update({
      "slider": {
        start: 0.3
      }
    });
