### ISSUE TITLE
选择轴标签如何定义旋转中心

### ISSUE THREAD

**Issue by jiaxing-1994** [antvis/G2Plot#3535]
场景：柱状图数据比较多，x轴标签又想全部展示，就做了45度旋转，如图
![image](https://user-images.githubusercontent.com/26563716/234742766-96003a04-925e-46fb-b421-d824852e1ae6.png)

问题：由于轴标签文字长度不一致，45度旋转轴标签后，无法做到顶部对齐，能否有配置参数可以配置旋转中心，使label文字支持顶部对齐。

**Comment by hustcc** [comment]
![image](https://user-images.githubusercontent.com/7856674/234743588-20f2535d-d554-469d-8e4c-1e961a1d6539.png)
