### ISSUE TITLE
🤔 [QUESTION] 滚动轴-鼠标滚轮滚动

### ISSUE THREAD

**Issue by LipiAndPili** [antvis/G2Plot#3554]
### 💻 Link to minimal reproduction

Please provide a link by forking these links [g2plot](https://codesandbox.io/s/g2plot-reproduction-template-gyej1) or GitHub repo. What is a minimal reproduction, and why is it required?

### 🏞 Expected result

条形图添加纵向滚动轴，鼠标在图表内容区域滚动滑轮可以控制图表数据滚动吗？

### 🚑 Any additional [like screenshots]

* **G2Plot Version**:
2.3.40
* **Platform**:

**Comment by hustcc** [comment]
当前版本基于 G2 4.x，其中的滚动条不支持滚动交互。我们在 5.x 会考虑进去。
