### ISSUE TITLE
官网-图表演示-基础雷达图 样式闪烁

### ISSUE THREAD

**Issue by shinima** [antvis/G2Plot#360]
文档链接： https://antv-g2plot.gitee.io/zh/examples/radar/basic
运行环境： win10, chrome78

官网中图表演示中的基础雷达图偶尔会样式闪烁，效果如下：

![g2plot-radar-flickering](https://user-images.githubusercontent.com/5550931/70390242-2e778e80-1a04-11ea-9dba-d3d6f760fb79.gif)

**Comment by paleface001** [comment]
感谢告知，感觉是底层图形active的问题，我来定位修复一下~
