### ISSUE TITLE
打包上线报错

### ISSUE THREAD

**Issue by ldd27** [antvis/G2Plot#361]
在react中使用，测试环境正常，打包到正式环境就报错
```bash
import React, { useRef, useEffect } from 'react';
import { Column } from '@antv/g2plot';

const Chart = () => {
  const data = [
    { organize: '区域1', value: 5 },
    { organize: '区域2', value: 66 },
    { organize: '区域3', value: 36 },
    { organize: '区域4', value: 27 },
    { organize: '区域5', value: 11 },
  ];

  const chart = useRef(null);

  useEffect(() => {
    if (!chart.current) {
      return;
    }

    const columnPlot = new Column(chart.current, {
      title: {
        visible: true,
        text: 'xx',
      },
      forceFit: true,
      padding: 'auto',
      data,
      xField: 'organize',
      yField: 'value',
      columnSize: 30,
      meta: {
        organize: {
          alias: '行政区域',
        },
        value: {
          alias: '处',
        },
      },
    });

    columnPlot.render();
  }, []);
  return <div ref={chart} />;
};

export default Chart;

```

![image](https://user-images.githubusercontent.com/11850305/70391166-1c4e1e00-1a0d-11ea-94c8-359e8c12ec37.png)

**Comment by hustcc** [comment]
确认下是否 xField 和 yField 没有指定？另外也可以告知一下版本。

**Comment by ldd27** [comment]
版本：0.11.4
 xField 和 yField 配置中有指定，测试环境显示正常，打包上线后就报错了

**Comment by ldd27** [comment]
以下是复现repo，其中Chart1.js是 #358 的复现例子
[repo.zip](https://github.com/antvis/G2Plot/files/3937682/repo.zip)

**Comment by ldd27** [comment]
请使用以下repo，加上了数据更新，点击更新数据，图表变空
[repo.zip](https://github.com/antvis/G2Plot/files/3937698/repo.zip)

**Comment by paleface001** [comment]
> 请使用以下repo，加上了数据更新，点击更新数据，图表变空
> [repo.zip](https://github.com/antvis/G2Plot/files/3937698/repo.zip)

只更新数据的话，可以使用`changeData`方法：

```
    columnPlot.current.changeData([
        { organize: '区域11', value: 0 },
        { organize: '区域21', value: 662 },
        { organize: '区域31', value: 361 },
        { organize: '区域41', value: 273 },
        { organize: '区域51', value: 11 },
      ])
  };
```

**Comment by paleface001** [comment]
使用`updateConfig`的方式进行数据更新也可以，但是要记得再执行一下`render`

```
  const onUpdate = () => {
    columnPlot.current.updateConfig({
      data: [
        { organize: '区域11', value: 0 },
        { organize: '区域21', value: 662 },
        { organize: '区域31', value: 361 },
        { organize: '区域41', value: 273 },
        { organize: '区域51', value: 11 },
      ],
    });
    columnPlot.current.render();
  };
```

**Comment by ldd27** [comment]
收到，试了下两种都可以，希望官网文档中能增加数据更新的说明

**Comment by paleface001** [comment]
> 收到，试了下两种都可以，希望官网文档中能增加数据更新的说明

好的，现在才刚刚起步，我们会让文档逐渐丰富起来的。欢迎给star一下哦~

**Comment by ldd27** [comment]
上周刚发现这个项目就star了，以前用的bizchart，配置起来感觉还是比较麻烦，还有打包报错的问题也帮忙排查一下哈，这个问题比较紧急

**Comment by ldd27** [comment]
调试发现doGroupScaleIn方法中的zeroY是undefined
![image](https://user-images.githubusercontent.com/11850305/70428357-6983cb80-1ab1-11ea-9f57-19fffa229c70.png)

**Comment by ldd27** [comment]
初步排查是g2 3.6.0beta版本execAnimation方法的237行调用方法没有传zeroY参数导致doGroupScaleIn的140行报错
设置animation: false关闭动画可以解决
https://github.com/antvis/G2/blob/ae7503751120cfd48312a3577909ea2a3bd830ed/packages/g2/src/animate/index.ts#L237
https://github.com/antvis/G2/blob/ae7503751120cfd48312a3577909ea2a3bd830ed/packages/g2/src/animate/util.ts#L140

**Comment by paleface001** [comment]
> 初步排查是g2 3.6.0beta版本execAnimation方法的237行调用方法没有传zeroY参数导致doGroupScaleIn的140行报错
> 设置animation: false关闭动画可以解决
> https://github.com/antvis/G2/blob/ae7503751120cfd48312a3577909ea2a3bd830ed/packages/g2/src/animate/index.ts#L237
> https://github.com/antvis/G2/blob/ae7503751120cfd48312a3577909ea2a3bd830ed/packages/g2/src/animate/util.ts#L140

赞！我们会修改一下底层bug然后尽快发一版。

**Comment by FOKIKI** [comment]
遇到同样，柱状图本地开发正常。打包上线就报错。
排查是跟代码打包压缩有关
https://github.com/antvis/G2/blob/ae7503751120cfd48312a3577909ea2a3bd830ed/packages/g2/src/animate/index.ts#L224
导致animate函数的名称发生了变化

**Comment by RaoHai** [comment]
cc https://github.com/antvis/G2/issues/1848

**Comment by paleface001** [comment]
已在g2 3.6新版本修复
