### ISSUE TITLE
🤔 [QUESTION] g2plot label文本样式设置fontSize字体大小无效

### ISSUE THREAD

**Issue by 18211365467** [antvis/G2Plot#3672]
### 💻 Link to minimal reproduction

Please provide a link by forking these links [g2plot](https://codesandbox.io/s/g2plot-reproduction-template-gyej1) or GitHub repo. What is a minimal reproduction, and why is it required?

### 🚑 Any additional [like screenshots]

* **G2Plot Version**:
* **Platform**:

**Comment by hustcc** [comment]
```ts
label: {
    layout: [],
    style: {
      stroke: 'red',
      lineWidth: 2,
      fill: 'red',
    },
  }
```

g2plot 默认设置了 label.layout，导致标签颜色按照柱子的颜色取对比度高的颜色。所以设置颜色不生效了。

![image](https://github.com/antvis/G2Plot/assets/7856674/dcbe4123-fb2d-4540-8af1-c30367d6d6db)
