### ISSUE TITLE
🤔 [QUESTION] 画布旋转 rotate

### ISSUE THREAD

**Issue by LipiAndPili** [antvis/G2Plot#3678]
### 🐛 Question description [Please make everyone to understand it]
怎么旋转图表90度，并且点击事件均正常，例如下图所示
![image](https://github.com/antvis/G2Plot/assets/50241817/e11dfbad-fd5c-4b5f-94df-ba0d23997eb3)

* **G2Plot Version**:
2.3.40
* **Platform**:

**Comment by hustcc** [comment]
旋转可以用 css 的 transform 把图表的容器旋转，然后应该默认就可以支持事件的，如果有异常，可以设置 supportCSSTransform: true。

**Comment by LipiAndPili** [comment]
@hustcc 加了这个属性图表可以正常交互了，但scrollbar滚动条没办法拖动，如何解决这个问题？
