### ISSUE TITLE
感觉文档不是很详细

### ISSUE THREAD

**Issue by Hyj2543** [antvis/G2Plot#368]
有很多参数都没有介绍，比如说我想要设置图表 title 样式该怎么做呢

**Comment by paleface001** [comment]
> 有很多参数都没有介绍，比如说我想要设置图表 title 样式该怎么做呢

```
title:{
  visible: true,
  text: ' ',
  style:{
    fill: 'red', // 文字颜色
    fontSize: 16, // 文字大小
    opacity: 0.5, // 透明度
    textAlign:'left',  // 文本对齐方式
    textBaseline:'top' // 文本基线
  }
}
```

**Comment by Hyj2543** [comment]
是我没有表达清楚，我是想要在标题的位置加一个日期选择控件，但找不到一个方法去做

**Comment by Hyj2543** [comment]
> > 有很多参数都没有介绍，比如说我想要设置图表 title 样式该怎么做呢
> 
> ```
> title:{
>   visible: true,
>   text: ' ',
>   style:{
>     fill: 'red', // 文字颜色
>     fontSize: 16, // 文字大小
>     opacity: 0.5, // 透明度
>     textAlign:'left',  // 文本对齐方式
>     textBaseline:'top' // 文本基线
>   }
> }
> ```

**Comment by paleface001** [comment]
title仅仅是用来配置图表标题，没有添加日期选择控件这种附加功能

**Comment by Me-Momo** [comment]
> 是我没有表达清楚，我是想要在标题的位置加一个日期选择控件，但找不到一个方法去做

可以在图表外层封装
```typescript
<>
    <div>{日期控件} {图表标题}</div>
   <G2PlotChart />
</>
```

**Comment by Hyj2543** [comment]
我明白了，非常感謝
