### ISSUE TITLE
🤔 [QUESTION]g2plot里为什么没有指标拆解图

### ISSUE THREAD

**Issue by lsjxscs** [antvis/G2Plot#3684]
[Ant Design Charts](https://github.com/ant-design/ant-design-charts)中的指标拆解图在g2和g2plot里为什么都没有，[Ant Design Charts]不是g2plot封装来的吗

**Comment by hustcc** [comment]
[Ant Design Charts](https://github.com/ant-design/ant-design-charts) 会包含有 3 大类图表：

- plot：统计图表，比如折柱饼
- graph：关系图之类的，比如上述说的指标拆解图
- map：地图相关的，比如行政地图

其中只有 plot 部分才是基于 g2plot  的。
