### ISSUE TITLE
🤔 [QUESTION] 图表联动问题反馈

### ISSUE THREAD

**Issue by xiecg** [antvis/G2Plot#3743]
目前 G2Plot 图表联动这个功能，是利用 Mix 组件来实现。但实际使用都是独立的图表组件，目前让开发者实现联动还有一些问题。

主要的问题就是颜色设置问题，目前的 color api  非常鸡肋，返回的信息太少。

![image](https://github.com/antvis/G2Plot/assets/10857932/9be7f7f7-fef8-4921-9eb6-e52d6d0d1387)

只有分组信息，没有维度信息，开发者完全不知道是哪个月份，应该把分组、维度和数值信息都返回出来。

目前 color 同时支持 [] 和 函数，需求一多就显得冗余，建议拆成两个 api，如图。

![image](https://github.com/antvis/G2Plot/assets/10857932/b943d87e-ea02-4589-81c5-b6abbe48c994)

这样图形基础配色可以用 color 来实现，数据分析、预警和联动这种需求都可以利用 setFieldColor 来异化图形的颜色。

**Comment by lxfu1** [comment]
可以通过配置rawFields获取更多信息

![image](https://github.com/antvis/G2Plot/assets/31396322/f5d9db43-a6d6-4ce9-91f0-9aeb0a3ab768)
