### ISSUE TITLE
@antv/g2 新的大版本v5 的升级 有开发和发布计划吗？

### ISSUE THREAD

**Issue by panjunqiu** [antvis/G2Plot#3751]
### 🐛 Question description [Please make everyone to understand it]
@antv/g2 新的大版本v5 已经发布了好多个版本了，我们的项目中也看到了v3分支，但挺久没更新了，是否有发布计划？
我们项目这边想升级antv/g2 的新版本

### 💻 Link to minimal reproduction

Please provide a link by forking these links [g2plot](https://codesandbox.io/s/g2plot-reproduction-template-gyej1) or GitHub repo. What is a minimal reproduction, and why is it required?

### 🚑 Any additional [like screenshots]

* **G2Plot Version**:
* **Platform**:

**Comment by hustcc** [comment]
代码全部放到 ant design charts 中，代码量不多，四千多行，所以暂时不会发布 v3。

**Comment by panjunqiu** [comment]
好的谢谢。之前用ant design charts 安装的依赖太多，不太想用。我再去用下看看。

**Comment by hustcc** [comment]
@panjunqiu ant design charts 是一个总包，如果指向用其中的统计图表，可以只使用其中的 @ant-design/plot 包。
