### ISSUE TITLE
🤔 [QUESTION] 如何修改柱状图柱hover的背景样式

### ISSUE THREAD

**Issue by ryanuo** [antvis/G2Plot#3773]
### 🐛 Question description [Please make everyone to understand it]
<img width="822" alt="image" src="https://github.com/antvis/G2Plot/assets/66169324/f1825849-58b3-4953-a414-411ffbc54610">
hover 后背景如何调整，未找到相应的api 求解🙏

* **G2Plot Version**:^2.4.31
* **Platform**:

**Comment by hustcc** [comment]
G2Plot 中修改不了，在 G2 5.0 新版本中增加了这个特性。
