### ISSUE TITLE
🐛 [BUG]切换浏览器标签页，切回图表页后，图表空白

### ISSUE THREAD

**Issue by 3764446961** [antvis/G2Plot#3778]
demo： https://riddle.alibaba-inc.com/riddles/8b5af522

**Comment by 3764446961** [comment]
![image](https://github.com/antvis/G2Plot/assets/168057074/36f1a725-a5f4-44b6-ac65-5b6c3043e1a9)

**Comment by kooriookami** [comment]
+1，浏览器最小化后，过段时间打开图标没了

**Comment by lxfu1** [comment]
Disabled!

![image](https://github.com/antvis/G2Plot/assets/31396322/f5062793-c387-44b6-9993-fdf8e27809bd)
