### ISSUE TITLE
🤔 [QUESTION] Liquid组件的percent为0时， 边框没有显示

### ISSUE THREAD

**Issue by Shuo-Mr** [antvis/G2Plot#3783]
### 🐛 Liquid 组件的percent为0时， 边框没有显示， 效果如下图

![image](https://github.com/antvis/G2Plot/assets/50469430/1eb2f006-4d68-41d8-a8dc-326026f53a78)

Antv 1 时有outline这个配置， 但查询了文档 Antv 2 里面没有相关配置， 有人知道的话，麻烦告诉一下， 谢谢

* **G2Plot Version**: 2.2.2
* **Platform**: Mac, Chorme

**Comment by hustcc** [comment]
https://g2plot.antv.antgroup.com/examples/progress-plots/liquid/#basic

测试设置为 0，也有边框，需要提供更多信息。
