### ISSUE TITLE
🐛 按照官网示例的代码开发，结果总是渲染出两个

### ISSUE THREAD

**Issue by Dolov** [antvis/G2Plot#3796]
你好，刚开始试用 g2plot ，按照官网的实例进行操作，结果总是渲染出两个图表，如图所示
可复现仓库地址 https://github.com/Dolov/vite-g2-bug

<img width="790" alt="image" src="https://github.com/antvis/G2Plot/assets/19704420/cc4fd2c4-20b8-4c03-90f5-58414b97cb5d">
<img width="714" alt="image" src="https://github.com/antvis/G2Plot/assets/19704420/848472ef-db56-4870-8bf1-4e1fb6cbc060">

**Comment by Dolov** [comment]
"react": "^18.3.1",
"react-dom": "^18.3.1"

应该是版本问题，17+ 没有这个问题

**Comment by lxfu1** [comment]
Strict Mode
