### ISSUE TITLE
🤔 [QUESTION] RegionFilter with diagonal

### ISSUE THREAD

**Issue by quirynen** [antvis/G2Plot#3801]
### 🐛 Question description [Please make everyone to understand it]
Is is possible to apply a regionFilter between 2 points forming a diagonal line?

### 💻 Link to minimal reproduction
This is the current display that I have 
https://codesandbox.io/s/admiring-kate-7v3qnk?file=/index.ts

![Screenshot 2024-07-22 154553](https://github.com/user-attachments/assets/4a8fdeb2-92db-4386-954d-7465d102626a)

### 🏞 Expected result
This is the display I would like to have
![editpeak](https://github.com/user-attachments/assets/6e45b8d6-ac03-49fd-b3d4-b8edeeec3000)

* **G2Plot Version**: 2.4.25
* **Platform**: Windows 11

**Comment by hustcc** [comment]
当前不支持这个能力。
