### ISSUE TITLE
🤔 [QUESTION]饼图如何设置圆角

### ISSUE THREAD

**Issue by far310** [antvis/G2Plot#3802]
饼图如何设置圆角

### 🏞 Expected result
<img width="746" alt="image" src="https://github.com/user-attachments/assets/edb9455b-e6b2-4282-9c7d-0097b28311db">

### 🚑 Any additional [like screenshots]

* **G2Plot Version**: 最新版
* **Platform**: vue

**Comment by hustcc** [comment]
不支持，这个是 G2 5.0 中的新特性能力。
