### ISSUE TITLE
🤔 [QUESTION]

### ISSUE THREAD

**Issue by DiF1202** [antvis/G2Plot#3806]
### 🐛 Question description [Please make everyone to understand it]
请问在自定义图表的tooltup的时候？只允许传入string和和HtmlElement，有办法支持Antd的组件吗请问？如果用原生元素写的话，样式又需要全部重新手撸一遍了。

* **G2Plot Version*^2.4.31*:

**Comment by hustcc** [comment]
使用 HtmlElement，以及 ReactDOM.render 结合，就可以实现用 React 自定义 tooltip 了。
