### ISSUE TITLE
🐛 [BUG]柱线双轴图时当折线数据是小数点时，图例的线坐标轴数据精确度展示异常

### ISSUE THREAD

**Issue by Lewis-li-0** [antvis/G2Plot#3807]
### 🐛 Bug description [Please make everyone to understand it]

> Please provide a link by forking these links [G2Plot](https://codesandbox.io/s/g2plot-issue-template-gzfdq?file=/index.ts) or GitHub repo, a minimal reproduction.
https://g2plot.antv.antgroup.com/examples/dual-axes/column-line/#column-line
* _Required_ **Link to minimal reproduction**:

### 📷 Step to reproduce
![image](https://github.com/user-attachments/assets/6ac7994b-e81c-4f48-abc4-9b669e5ee8cf)

### 🚑 Any additional [like screenshots]

* **G2Plot Version**:2.4.25
* **Platform**: window10

**Comment by hustcc** [comment]
需要手动 formatter 一下，这个是 js 的浮点数计算精度问题。
