### ISSUE TITLE
上线报错

### ISSUE THREAD

**Issue by HoorayHY** [antvis/G2Plot#381]
![Uploading image.png…]()

代码：

**Comment by HoorayHY** [comment]
"@antv/g2plot": "0.11.5",
"@antv/g6": "3.2.4",

**Comment by HoorayHY** [comment]
在编辑环境上都没有问题，但是部署到线上就报错x为undefined。配置了xFiled、yFiled

**Comment by paleface001** [comment]
上线报错有可能是g2plot和g2的G版本不统一

**Comment by HoorayHY** [comment]
> 上线报错有可能是g2plot和g6的G版本不统一

那有相应的匹配的版本信息吗，是需要更新g6版本吗

**Comment by HoorayHY** [comment]
import { Component, useEffect } from 'react';
import { Bar } from '@antv/g2plot';
class QuestionReport extends Component {

    constructor(props) {
        super(props);
    }

    componentWillReceiveProps(nextProps, nextState) {
        if(this.props.data !== nextProps.data) {
          this.barPlot.updateConfig({
            data: nextProps.data
          });
          this.barPlot.repaint();
          this.barPlot.render();
        }
    }

    componentDidMount(){
        this.renderReport();
    }

    renderReport = () => {
      const { title, xField, yField, xAxis=null, yAxis=null, data } = this.props;
      this.barPlot = new Bar(this.container, {
          title: {
            visible: true,
            text: title || '图表',
          },
          forceFit: true,
          data: data,
          xField: xField || '值',
          yField: yField || '值',
          xAxis: xAxis,
          yAxis: yAxis,
      });
        
      this.barPlot.render();
    }

    render(){
        return (
            <div className={reportWrap} ref={ref => this.container = ref}></div>
        )
    }
}

export default QuestionReport;

**Comment by HoorayHY** [comment]
报错页面只用到g2plot，也会受g6版本影响吗

**Comment by HoorayHY** [comment]
问题比较着急，辛苦紧急帮忙看一下

**Comment by paleface001** [comment]
> 报错页面只用到g2plot，也会受g6版本影响吗

只要你项目打包在一起就会相互影响，目前g2plot和g6不能用一个版本的G

**Comment by licg9999** [comment]
@HoorayHY  有 package-lock.json  或 yarn.lock 文件吗？

**Comment by HoorayHY** [comment]
> @HoorayHY 有 package-lock.json 或 yarn.lock 文件吗？

有

**Comment by HoorayHY** [comment]
> @HoorayHY 有 package-lock.json 或 yarn.lock 文件吗？
而且我本地每次都会生成一个report.xxx.json的文件

**Comment by licg9999** [comment]
> > @HoorayHY 有 package-lock.json 或 yarn.lock 文件吗？
> > 而且我本地每次都会生成一个report.xxx.json的文件

先上传一下吧

**Comment by HoorayHY** [comment]
> > > @HoorayHY 有 package-lock.json 或 yarn.lock 文件吗？
> > > 而且我本地每次都会生成一个report.xxx.json的文件
> 
> 先上传一下吧

git上传不上去

**Comment by hustcc** [comment]
最快的办法是先引入 dist 的文件。

**Comment by RaoHai** [comment]
这 https://github.com/antvis/G2/issues/1848

**Comment by paleface001** [comment]
已在g2 3.6新版本修复
