### ISSUE TITLE
🤔 [多折线图，怎么对指定的折线图不展示point数据点

### ISSUE THREAD

**Issue by Shanks0724** [antvis/G2Plot#3810]
### 💻 Link to minimal reproduction

Please provide a link by forking these links [g2plot](https://codesandbox.io/s/g2plot-reproduction-template-gyej1) or GitHub repo. What is a minimal reproduction, and why is it required?

### 🏞 
![20240828-144049](https://github.com/user-attachments/assets/40e50272-a2da-4efd-924a-8ab2ec49121e)

### 🚑 Any additional [like screenshots]

* **G2Plot Version**:
* **Platform**:

**Comment by hustcc** [comment]
可以使用双轴图中的双折线图。
