### ISSUE TITLE
🐛 [BUG]分组柱状图设置自动调整标签颜色后无法设置标签字体大小

### ISSUE THREAD

**Issue by gaving2016** [antvis/G2Plot#3811]
### 🐛 Bug description [Please make everyone to understand it]

> Please provide a link by forking these links [G2Plot](https://codesandbox.io/p/sandbox/kn6rq4?file=%2Findex.ts) or GitHub repo, a minimal reproduction.

* _Required_ **Link to minimal reproduction**:

### 📷 Step to reproduce
 label: {
    layout: [
      {
        type: 'adjust-color', // 自动调整颜色
      },
    ],
    style: {
      fontSize: 96, // 手动设置标签字体大小
      fontWeight: 'bold', // 设置标签字体粗细
      fill: 'red', // 默认字体颜色
    },
  },

### 🏞 Expected result
设置自动调整标签颜色后支持自定义标签字体大小

### 🚑 Any additional [like screenshots]

* **G2Plot Version**: 2.4.25
* **Platform**:  Chrome

**Comment by hustcc** [comment]
```ts
label: {
    position: 'middle', // 'top', 'middle', 'bottom'
    style: {
      fontSize: 20,
    },
    layout: [
      // 数据标签文颜色自动调整
      { type: 'adjust-color' },
    ],
```

已测试，可以生效。
