### ISSUE TITLE
🤔 [QUESTION] 项目文档编译

### ISSUE THREAD

**Issue by JRICKL** [antvis/G2Plot#3815]
### 🐛 Question description [Please make everyone to understand it]
Hi! 日常在内网做开发，项目文档可以编译本地部署吗？
尝试过将 ./site 目录  build ，过程没报错,但是生成的 dist文件用 用VSCode Live Server快速测试了一下，似乎内容不能正常访问

**Comment by hustcc** [comment]
可以直接 clone 下来，然后用 gh-pages 分支的代码部署。
