### ISSUE TITLE
🤔 [QUESTION] 柱图每个分组内如何排序 ?

### ISSUE THREAD

**Issue by xiecg** [antvis/G2Plot#3816]
看例子，x 轴有9月和10月的数据。
9月的数据是排序好了的，从大到小，渲染也是正确的。
10月也是排序好的，但并不是按照数据的顺序渲染的，而是根据9月的数据排序渲染的。
请问如何实现分组的排序/自定义排序功能呢 ？

![QQ_1727248633173](https://github.com/user-attachments/assets/414894ad-57e9-47ac-b65c-b647200c124f)

### 💻 Link to minimal reproduction

https://codesandbox.io/p/sandbox/clever-rgb-ckljzv

* **G2Plot Version**: 2.4.32
* **Platform**: macOS 15.0

**Comment by hustcc** [comment]
目前没法每组柱子单独排序，只能根据分类字段来排序。
