### ISSUE TITLE
坐标轴标签如何自适应

### ISSUE THREAD

**Issue by cai148480** [antvis/G2Plot#382]
![1576235157(1)](https://user-images.githubusercontent.com/47582074/70795822-aadee880-1ddb-11ea-8db8-c2c76002a825.png)
比如这个，当坐标轴标签文字多了，就会往外跑，容器设置了高度，也设置了padding，开启了自适应。

还有就是怎么统一让坐标轴标签统一只有一种表现形式，现在是当文字少了就会变成省略号，文字多了有时候是竖着的，有时候是斜着的

![1576235372(1)](https://user-images.githubusercontent.com/47582074/70796042-42443b80-1ddc-11ea-8210-572a8259c204.png)
![1576235432(1)](https://user-images.githubusercontent.com/47582074/70796049-45d7c280-1ddc-11ea-8805-54f097685593.png)

**Comment by paleface001** [comment]
可以自定义响应式规则，这块文档还不全，我周末会补充一下

**Comment by tobemaster56** [comment]
![image](https://user-images.githubusercontent.com/8998761/71229204-9e98e500-231f-11ea-8336-a87e34fe3f99.png)
我也有这个问题，坐标轴 label 密密麻麻，看了文档，好像没有倾斜文本设置

**Comment by paleface001** [comment]
> 我也有这个问题，坐标轴 label 密密麻麻，看了文档，好像没有倾斜文本设置
以Y轴为例：
```
xAxis:{
  visible: true,
   autoRotateLabel: true
}
```
