### ISSUE TITLE
🥰 [FEATURE] 热力图建议增加个最小透明度配置

### ISSUE THREAD

**Issue by S-Lemon** [antvis/G2Plot#3824]
### 🥰 Features description [Please make everyone to understand it]
期望可以在热力图配置中，增加一个最小透明度配置，用以将数据点的透明度不至于接近0导致看不见
### 🏞 What problem does this feature solve
在密度热力图中，当数据点的数值过小时，会出现alpha过小而看不见
![image](https://github.com/user-attachments/assets/2b1901fe-aef1-4dfb-8a47-e6d27a29230e)
红框这里其实还有一个数据点
### 🧐 What does the proposed API look like
类似[heatmapjs文档](https://www.patrick-wied.at/static/heatmapjs/docs.html)
![image](https://github.com/user-attachments/assets/d4262ee5-22ee-4a54-8fae-fc74223623eb)

**Comment by S-Lemon** [comment]
关联[g2 issue](https://github.com/antvis/G2/issues/6509)

**Comment by S-Lemon** [comment]
g2plot版本：v2.4.31

**Comment by hustcc** [comment]
G2 是支持这个配置的：https://g2.antv.antgroup.com/spec/mark/heatmap

G2Plot 使用 G2 4.x 不支持这个配置，也无法改进优化，建议直接升级 G2 5.0~

**Comment by S-Lemon** [comment]
对于提到的”无法改进优化“，我理解该说法是指无法实现。
如果是指的无法实现，那我不太可以理解。
https://github.com/antvis/G2/blob/81a10f8c9b36694facd856c9ae8318679941f790/src/geometry/heatmap.ts#L183
直接改成
`pixels[i] = alpha && Math.max(alpha, minOpacity);`
这样不就可行了吗？
另外，使用的g2plot而不是直接使用g2，但官方没有看到g2plot升级为@ant-design/charts的方案。
