### ISSUE TITLE
🤔 [QUESTION] Column 不支持水平柱状图 么？

### ISSUE THREAD

**Issue by Lemonreds** [antvis/G2Plot#3825]
### 💻 Link to minimal reproduction

Please provide a link by forking these links [g2plot](https://codesandbox.io/s/g2plot-reproduction-template-gyej1) or GitHub repo. What is a minimal reproduction, and why is it required?

### 🚑 Any additional [like screenshots]

* **G2Plot Version**:
* **Platform**:

**Comment by hustcc** [comment]
水平条形图叫 Bar。
