### ISSUE TITLE
🤔 [QUESTION]玉珏图RadialBar X轴标签显示位置问题

### ISSUE THREAD

**Issue by seven-sent** [antvis/G2Plot#3827]
### 🐛 Question description [Please make everyone to understand it]
玉珏图RadialBar设置宽高自适应，有时候X轴标签显示的位置会变，导致被遮挡，如下图。
请问有没有方法能够固定标签显示的位置？比如把标签固定在左边？
<img width="474" alt="image" src="https://github.com/user-attachments/assets/78c95974-8335-4abb-9a59-9af4b225dc1d">

### 💻 Link to minimal reproduction

Please provide a link by forking these links [g2plot](https://codesandbox.io/s/g2plot-reproduction-template-gyej1) or GitHub repo. What is a minimal reproduction, and why is it required?

### 🚑 Any additional [like screenshots]

* **G2Plot Version**: 2.4.32
* **Platform**:

**Comment by hustcc** [comment]
需要复现，和这个 demo 的使用有什么区别吗？https://g2plot.antv.antgroup.com/examples/more-plots/radial-bar/#basic

**Comment by seven-sent** [comment]
> 需要复现，和这个 demo 的使用有什么区别吗？https://g2plot.antv.antgroup.com/examples/more-plots/radial-bar/#basic

这个是会出现问题的代码：

```
import { RadialBar } from '@antv/g2plot';

const data = [
  { name: 'X6', star: 297 },
  { name: 'G', star: 506 },
  { name: 'AVA', star: 805 },
  { name: 'G2Plot', star: 1478 },
  { name: 'L7', star: 2029 },
  { name: 'G6', star: 7100 },
  { name: 'F2', star: 7346 },
  { name: 'G2', star: 10178 },
];

const bar = new RadialBar('container', {
  autoFix: false,
  width: 500,
  height: 500,
  data,
  xField: 'name',
  yField: 'star',
  // maxAngle: 90, //最大旋转角度,
  radius: 1,
  innerRadius: 0.2,
  tooltip: {
    formatter: (datum) => {
      return { name: 'star数', value: datum.star };
    },
  },
});
bar.render();
```
<img width="300" alt="image" src="https://github.com/user-attachments/assets/85d4b91d-ff76-4042-aa9d-95f2c9a2d880">
