### ISSUE TITLE
🤔 [QUESTION]和弦图Chord的标签位置问题

### ISSUE THREAD

**Issue by seven-sent** [antvis/G2Plot#3828]
### 🐛 Question description [Please make everyone to understand it]
和弦图Chord的标签位置无法自适应，即使设置了offset也无法避免图表跟标签文字重叠(因为图表宽高自适应)：
<img width="400" alt="image" src="https://github.com/user-attachments/assets/854ea7d0-67c9-4a3a-93cf-a5e14fe01f6d">
能否像G2 5.0的那样显示：
<img width="440" alt="image" src="https://github.com/user-attachments/assets/316713e9-ee1a-4995-a6a2-e1eed92ef7f5">

### 💻 Link to minimal reproduction

Please provide a link by forking these links [g2plot](https://codesandbox.io/s/g2plot-reproduction-template-gyej1) or GitHub repo. What is a minimal reproduction, and why is it required?

### 🚑 Any additional [like screenshots]

* **G2Plot Version**: 2.4.32
* **Platform**: MacOS

**Comment by hustcc** [comment]
建议升级 G2 5.0，这个在旧版本比较难处理。
