### ISSUE TITLE
🤔 [QUESTION]

### ISSUE THREAD

**Issue by Maximus-ckp** [antvis/G2Plot#3835]
<img width="560" alt="微信图片_20241129171337" src="https://github.com/user-attachments/assets/8e15a035-8ccd-4059-bd46-a8a51bc7e7e4">
请问雷达图如何分别设置各维度的最大值？（如上图）
How to set the maximum value for each dimension of the radar chart respectively? (As shown in the above picture)

**Comment by hustcc** [comment]
G2Plot 当前是不支持的这个的，只支持一个度量方式。在 G2 5.0 中支持，看[这个](https://g2.antv.antgroup.com/examples/general/radar/#parallel-radar)。

当然基于 G2Plot 也可以有取巧的方式：

1. 将数据归一化到 0-1。
2. 然后在不同的维度上，通过数据标签的 formatter 显示成不同的数据。
3. 同时记得处理一下 tooltip 的显示。

当然建议还是进行升级最好。
