### ISSUE TITLE
怎么把图表标题放在中间？加上offset不生效

### ISSUE THREAD

**Issue by ZengZhenfei** [antvis/G2Plot#401]
https://codesandbox.io/s/nq7m7

**Comment by paleface001** [comment]
目前title没有offset和居中的配置项，文档： https://g2plot.antv.vision/zh/docs/manual/general-config#title

如果居中显示和offset有需求的话，后面会考虑加上

**Comment by ZengZhenfei** [comment]
谢谢，非常有必要，有些项目需求大部分title都是居中显示的

**Comment by paleface001** [comment]
> 谢谢，非常有必要，有些项目需求大部分title都是居中显示的

好的~
