### ISSUE TITLE
guideLine 待优化点

### ISSUE THREAD

**Issue by hustcc** [antvis/G2Plot#402]
- [ ] 默认样式不是很好看
 - [x] min max 反了，而且 max 标记的不是最大值，而是最大 scale 值；另外 median、mean 可以再确认一下。
 - [x] text 在 start、end、center 的时候，对齐方式可以默认最优（left, right, center）

----

![image](https://user-images.githubusercontent.com/7856674/71226299-604af800-2316-11ea-8b6c-3e27eef1a078.png)

**Comment by paleface001** [comment]
fixed in #550
