### ISSUE TITLE
坐标轴日期出现重复值

### ISSUE THREAD

**Issue by cai148480** [antvis/G2Plot#404]
![1576833373(1)](https://user-images.githubusercontent.com/47582074/71244137-c94d6280-234c-11ea-9c6b-42021fc12ebd.png)

**Comment by 18402025768** [comment]
yAxis.type 改一下类型试试,  'time' 或者 'dateTime' 或者 'timeCat';

**Comment by 18402025768** [comment]
xAxis.type 改一下类型试试, 'time' 或者 'dateTime' 或者 'timeCat';

**Comment by cai148480** [comment]
> xAxis.type 改一下类型试试, 'time' 或者 'dateTime' 或者 'timeCat';

没有用

**Comment by paleface001** [comment]
0.11.27 已解决
