### ISSUE TITLE
响应式 细节bug

### ISSUE THREAD

**Issue by heiniuhaha** [antvis/G2Plot#41]
![image](https://user-images.githubusercontent.com/668144/64579637-29c81d80-d3b6-11e9-87be-e79fd2ebe7f1.png)

**Comment by paleface001** [comment]
https://bizcharts.alibaba.net/plot/component/stack-bar-chart
label没居中是因为配了offsetX

**Comment by paleface001** [comment]
tooltip貌似是因为iframe，3.x demo也有一样的问题
