### ISSUE TITLE
Radar 的几个问题

### ISSUE THREAD

**Issue by Liu-Ya** [antvis/G2Plot#436]
![image](https://user-images.githubusercontent.com/23520283/71541540-8d8e4a80-2995-11ea-8cfe-8d5ac40fb600.png)

```jsx
radar = new Radar(document.getElementById('radar') as HTMLElement, {
          data: ['basis', 'family', 'activity', 'evaluation', 'quality', 'perfect'].map(item => ({
            type: radarType[item],
            value: numeral(res?.perfect_total[item]).value(),
          })),
          angleField: 'type',
          radiusField: 'value',
          // angleAxis: 'type',
          // radiusAxis: 'value',
        });
        radar.render();
```
预期
![image](https://user-images.githubusercontent.com/23520283/71541558-d940f400-2995-11ea-807e-91bd0d086af6.png)

如果取消`angleAxis`和`radiusAxis`注释
![image](https://user-images.githubusercontent.com/23520283/71541552-c9291480-2995-11ea-9009-d9badc9f0114.png)

**Comment by Liu-Ya** [comment]
初始化`render`时，如果设置`data`为空数组，之后`changeData`无法生效

**Comment by Liu-Ya** [comment]
`render` 是异步的吗？会出现如下的情况
![render](https://user-images.githubusercontent.com/23520283/71541947-1e1b5980-299b-11ea-841b-7d48a28c89fa.gif)

希望提供Promises或回调方法

**Comment by Liu-Ya** [comment]
浏览器窗口resize后，重新渲染了`render`时的数据，而不是`changeData`的数据，demo代码中加入
```
```

**Comment by BlackGanglion** [comment]
这个问题我来跟进吧

**Comment by BlackGanglion** [comment]
@Liu-Ya render不是异步的，我这边无法复现，请给一下复现demo，其他两个问题已修复

**Comment by Liu-Ya** [comment]
@BlackGanglion 元旦后我再看看现在发现不能兼容IE11，有解决方案吗 😂

**Comment by BlackGanglion** [comment]
> @BlackGanglion 元旦后我再看看现在发现不能兼容IE11，有解决方案吗

我找IE11看下是什么原因

**Comment by Liu-Ya** [comment]
@BlackGanglion 用的antd-pro，build后代码还有箭头函数，`umi`的IE兼容已经打开了

**Comment by Liu-Ya** [comment]
```js
onLineMouseup:"line:mouseup",onLineMouseenter:"line:mouseenter",onLineMouseleave:"line:mouseleave",onLineContextmenu:"line:contextmenu"})},function(t,e,i){"use strict";function n(t,e,i,n){t=t.filter(t=>{let n=e(t),r=i(t);return null!=n&&isFinite(n)&&null!=r&&isFinite(r)}),n&&t.sort((t,i)=>e(t)-e(i));
```
