### ISSUE TITLE
调整padding-left 会影响 legend 位置

### ISSUE THREAD

**Issue by Me-Momo** [antvis/G2Plot#445]
![image](https://user-images.githubusercontent.com/15646325/71632041-44fdb800-2c47-11ea-8085-fa5e4e3ead6a.png)

![image](https://user-images.githubusercontent.com/15646325/71632055-5050e380-2c47-11ea-8b10-41e34d7fb739.png)

![image](https://user-images.githubusercontent.com/15646325/71632064-58108800-2c47-11ea-819c-f36983ec446e.png)

**Comment by Me-Momo** [comment]
@paleface001 知道这个是什么导致的么？有没有办法来自定义legend的位置，绕过这个问题

**Comment by Me-Momo** [comment]
![image](https://user-images.githubusercontent.com/15646325/71638278-cc264c80-2c96-11ea-9c90-064c72feecb4.png)
还有这些问题～～ 现在DI上没办法上线

**Comment by paleface001** [comment]
没复现出来，在riddle里复现一下看看？ https://riddle.alibaba-inc.com/riddles/d5b9745d

**Comment by Me-Momo** [comment]
> 没复现出来，在riddle里复现一下看看？ https://riddle.alibaba-inc.com/riddles/d5b9745d

https://riddle.alibaba-inc.com/riddles/13d54f88 试着微调 padding-left
