### ISSUE TITLE
主标签title和副标签description能否支持html tag? 比如<a href="https：//abc.com">

### ISSUE THREAD

**Issue by yufeishi** [antvis/G2Plot#449]
主标签title和副标签description能否支持html tag? 比如<a href="https：//abc.com">?
比如副标签： 此表格数据来源 <a href="https：//abc.com">abc.com</a>。 用户点击副标签就能访问数据提供商

**Comment by paleface001** [comment]
点击副标签访问不需要通过html tag也可以做到，通过`events`配置项即可：

```
events:{
  onDescriptionClick:()=>{
    //链接跳转
  }
}
```

**Comment by yufeishi** [comment]
谢谢

Yufei
