### ISSUE TITLE
Legend (图形标签)能否支持自适应以及style配置字体大小/文字颜色

### ISSUE THREAD

**Issue by yufeishi** [antvis/G2Plot#450]
Legend (图形标签)能否支持自适应以及style配置字体大小/文字颜色？目前当页面宽度放大，Label字体不会自动放大。比例会失调。formatter: function  format legend content 这个属性能做到字体大小/文字颜色吗？

**Comment by paleface001** [comment]
g2plot不会做自动放大，这部分配置是开放给用户的。

如果你说的图形标签是指label的话，可以进行label的样式配置：

```
label:{
  visible: true,
  style:{
     fontSize: 16, // 字号
     fill:'black',  // 字体颜色
     opacity: 0.8  // 字体透明度
  }
}
```

**Comment by yufeishi** [comment]
谢谢

Yufei
