### ISSUE TITLE
水波图示例 遇到的问题

### ISSUE THREAD

**Issue by wuzengduo** [antvis/G2Plot#461]
**未使用国内镜像：**
①ie浏览器：
![71716150-b6f41e00-2e4e-11ea-95e9-6ad17ee8f6fe 1](https://user-images.githubusercontent.com/37041167/71717212-4818c400-2e52-11ea-81ac-951acc157e6e.png)

颜色设置生效，中心字体未显示

②谷歌浏览器：
![1578044148(1)](https://user-images.githubusercontent.com/37041167/71717279-93cb6d80-2e52-11ea-9f35-704399f96ebd.jpg)

颜色设置生效，中心字体百分比显示错误

**使用国内镜像：**
①ie浏览器：
![1578044216(1)](https://user-images.githubusercontent.com/37041167/71717179-27506e80-2e52-11ea-9893-022066f20841.jpg)

水波图中心字体未显示，颜色设置未生效

②谷歌浏览器：
![1578044148(2)](https://user-images.githubusercontent.com/37041167/71717250-74344500-2e52-11ea-9176-d0ff213b2432.jpg)

颜色设置未生效

**Comment by wuzengduo** [comment]
还有一个ie浏览器左上角的title，description也没有显示出来

**Comment by licg9999** [comment]
亲，不要直接使用color属性，试一下 liquidStyle，具体用法如下，文档后续会补充起来的：

```js
import { Liquid } from '@antv/g2plot';

const liquidPlot = new Liquid(document.getElementById('container'), {
  title: {
    visible: true,
    text: '水波图',
  },
  width: 400,
  height: 400,
  min: 0,
  max: 10000,
  value: 3000,
  liquidStyle: {
    fill: '#000000',
    stroke: '#999999'
  },
});
liquidPlot.render();
```
效果1：
![image](https://user-images.githubusercontent.com/8203034/72785410-28f99f00-3c66-11ea-8e3d-3ab0dea42c2b.png)


```js
import { Liquid } from '@antv/g2plot';

const liquidPlot = new Liquid(document.getElementById('container'), {
  title: {
    visible: true,
    text: '水波图',
  },
  width: 400,
  height: 400,
  min: 0,
  max: 10000,
  value: 7000,
  liquidStyle: {
    fill: '#000000',
    stroke: '#999999'
  },
});
liquidPlot.render();
```
效果2：
![image](https://user-images.githubusercontent.com/8203034/72785451-3f075f80-3c66-11ea-8864-014e11f13afe.png)
