### ISSUE TITLE
使用 padding:auto ，更新数据changeData() 方法， 重新绘制时 左侧padding没有重新计算 

### ISSUE THREAD

**Issue by staiv1** [antvis/G2Plot#480]
<img width="165" alt="屏幕快照 2020-01-09 上午12 57 39" src="https://user-images.githubusercontent.com/22257758/71999028-a4794a80-327b-11ea-9149-18a77f2ac9ae.png">
<img width="401" alt="屏幕快照 2020-01-09 上午12 56 24" src="https://user-images.githubusercontent.com/22257758/71999035-a8a56800-327b-11ea-90a9-f5283a8b9106.png">

**Comment by staiv1** [comment]
官方文档，销毁图表的 destory() 单词拼写错误了～

**Comment by ldd27** [comment]
+1
