### ISSUE TITLE
暗黑主题下【雷达图】、【分组柱状图】等图表标签颜色异常

### ISSUE THREAD

**Issue by realeve** [antvis/G2Plot#489]
## 现象
![image](https://user-images.githubusercontent.com/448208/72116913-af6cd180-3386-11ea-998c-14a0527659f5.png)

测试链接[https://antv-g2plot.gitee.io/zh/examples/radar/basic](https://antv-g2plot.gitee.io/zh/examples/radar/basic) 

```js
import { Radar } from '@antv/g2plot';

const data = [
  {
    item: 'Design',
    user: 'a',
    score: 70,
  },
  {
    item: 'Design',
    user: 'b',
    score: 30,
  },
  {
    item: 'Development',
    user: 'a',
    score: 60,
  },
  {
    item: 'Development',
    user: 'b',
    score: 70,
  },
  {
    item: 'Marketing',
    user: 'a',
    score: 60,
  },
  {
    item: 'Marketing',
    user: 'b',
    score: 50,
  },
  {
    item: 'Users',
    user: 'a',
    score: 40,
  },
  {
    item: 'Users',
    user: 'b',
    score: 50,
  },
  {
    item: 'Test',
    user: 'a',
    score: 60,
  },
  {
    item: 'Test',
    user: 'b',
    score: 70,
  },
  {
    item: 'Language',
    user: 'a',
    score: 70,
  },
  {
    item: 'Language',
    user: 'b',
    score: 50,
  }, 
];

const radarPlot = new Radar(document.getElementById('container'), {
 
  data,
  angleField: 'item',
  radiusField: 'score',
  seriesField: 'user',
  line: {
    visible: true,
  },

 // dark主题显示异常

  theme:'dark',
    // 配置以下angelAxis后正常显示
	/*angleAxis:{
    label:{
      textStyle:{
        fill:'#fff'
      }
    }
  }*/
}); 
radarPlot.render(); 
```
## 问题原因
[https://github.com/antvis/g2plot/blob/master/src/plots/radar/layer.ts#L118](https://github.com/antvis/g2plot/blob/master/src/plots/radar/layer.ts#L118) 这里不应该初始化颜色值。

## 类似问题

以  **theme:'dark',** 测试， 以下链接也存在类似问题：
[https://antv-g2plot.gitee.io/zh/examples/column/group](https://antv-g2plot.gitee.io/zh/examples/column/group)

[https://antv-g2plot.gitee.io/zh/examples/bar/basic](https://antv-g2plot.gitee.io/zh/examples/bar/basic)

[https://antv-g2plot.gitee.io/zh/examples/liquid/basic](https://antv-g2plot.gitee.io/zh/examples/liquid/basic)

[https://antv-g2plot.gitee.io/zh/examples/liquid/basic#percent](https://antv-g2plot.gitee.io/zh/examples/liquid/basic#percent)

[https://antv-g2plot.gitee.io/zh/examples/gauge/basic#half](https://antv-g2plot.gitee.io/zh/examples/gauge/basic#half)

**Comment by realeve** [comment]
@zqlu

**Comment by BlackGanglion** [comment]
我调整一下 dark 下默认 label color 好了

**Comment by BlackGanglion** [comment]
@realeve 几个图表是不同的问题，仪表盘的标签是css控制的，可以自行调整一下

**Comment by realeve** [comment]
@BlackGanglion 好的，谢谢。
