### ISSUE TITLE
是否重写 spider-label，统一为使用 自定义注册的方式

### ISSUE THREAD

**Issue by Me-Momo** [antvis/G2Plot#497]
1. 目前 spider-label 的实现方案与其他自定义label不一致
2. spider-label 是否要支持下面这两种形式，新增 alignTo的配置项？
3. 其他 issue 需要解决，如 #471 

详细思路与设计：见 [文档](https://yuque.antfin-inc.com/xinming.lxj/byp4a9/upxz7i#GxskC)

![image](https://user-images.githubusercontent.com/15646325/72196991-75b7cb80-3457-11ea-9b58-baebcc2893c1.png)

**Comment by simaQ** [comment]
建议还是统一为 registerGeometryLabel 的方式

**Comment by paleface001** [comment]
1. 可以试一试能不能迁移为register的方式

2.aliginTo配置项没有问题，我们默认采用第一种就可以了~
