### ISSUE TITLE
X坐标轴显示不正确

### ISSUE THREAD

**Issue by kewang85** [antvis/G2Plot#502]
用以下的代码配置，X坐标轴显示不正确， 图表见下图：
title: {
          visible: true,
          text: '单折线图的基础用法',
        },
        description: {
          visible: true,
          text: '最基础简单的折线图使用方式，显示一个指标的趋势',
        },
        forceFit: true,
        data: [
          {
            Date: "2020-01-10",
            value: 12300
          },
          {
            Date: "2020-01-11",
            value: 18067
          },
          {
            Date: "2020-01-12",
            value: 14069
          }
        ],
        padding: 'auto',
        xField: 'Date',
        yField: 'value',

![ab](https://user-images.githubusercontent.com/5967556/72245223-04c90d00-362b-11ea-8b34-b79517094bb9.png)

**Comment by paleface001** [comment]
0.11.27 已解决
