### ISSUE TITLE
hover的点在边缘的时候，不显示tooltip

### ISSUE THREAD

**Issue by sevenbian** [antvis/G2Plot#505]
lineType为point的时候，X轴上的首尾点超出可视区域范围内，会出现提示不了tooltip的情况，这种情况下该如何解决？
[https://codesandbox.io/s/fancy-framework-wyrmc](url)
![WeChat Image_20200114104011](https://user-images.githubusercontent.com/26078029/72309625-6be1d280-36ba-11ea-8055-c2c3772ed932.png)

**Comment by BlackGanglion** [comment]
G2 的问题麻烦去 G2 的 repo 提 issue 吧
