### ISSUE TITLE
支持按需加载

### ISSUE THREAD

**Issue by afc163** [antvis/G2Plot#507]
现在 index 指向 dist 文件。

```jsx
import { Bar } from '@antv/g2plot';
```

这样使用会导致全量加载。

**Comment by paleface001** [comment]
https://github.com/antvis/G2Plot/blob/0f889fea7f9a2b85d6677f5b4bc3567c9b13ff51/package.json#L6

是说要改demo里的引用方式吗

**Comment by afc163** [comment]
啊，我看错了。
