### ISSUE TITLE
饼图配置项 avoidOverlap 讨论

### ISSUE THREAD

**Issue by Me-Momo** [antvis/G2Plot#522]
前几天加了一个 `outer-center` 的饼图label，本质上只是 label 没有做任何偏移，碰撞则隐藏

在 spider-label 下，其实也有这部分的需求，碰撞不做偏移

所以配置项是否改为 `avoidOverlap`

1. `avoidOverlap` 避免遮挡，label 会进行偏移
2. `allowOverlap` 允许遮挡，label 遮挡情况下 是否隐藏

**Comment by hustcc** [comment]
可以把 inner、outer、spider 三种标签在有这些配置情况列举一下。可以可以就合并为配置吧~

**Comment by paleface001** [comment]
> 可以把 inner、outer、spider 三种标签在有这些配置情况列举一下。可以可以就合并为配置吧~
> 
> 另外，上面第二点是 allowOverlap 和 avoidOverlap 就是一个互斥关系吧，命名问题。

感觉 是否避免遮挡 通过allowOverlap一个配置项就可以做到了，出现遮挡的情况下，是偏移还是隐藏是互斥关系，需要给这两个配置项命名

**Comment by hustcc** [comment]
或者就叫 overlap，然后有三个枚举值：

 - none: 不处理
 - hide: 自动隐藏
 - adjust: 自动调整

**Comment by paleface001** [comment]
可以有，很清晰

**Comment by Me-Momo** [comment]
![image](https://user-images.githubusercontent.com/15646325/72678539-dbecc000-3ae1-11ea-9b7b-73782757bce6.png)


> 或者就叫 overlap，然后有三个枚举值：
> 
> * none: 不处理
> * hide: 自动隐藏
> * adjust: 自动调整

**Comment by paleface001** [comment]
三个枚举值的优先级还得确定下
