### ISSUE TITLE
G2Plot 与G2相比有什么区别？

### ISSUE THREAD

**Issue by BinWu1989** [antvis/G2Plot#533]
G2Plot 与G2相比有什么区别？

**Comment by lili21** [comment]
G2Plot是以G2为基础的一套图形库。

G2更加底层，你用G2画图表你要一步一步的告诉G2怎么画。

G2Plot直接就提供了像 `Bar`, `Line` 这样的图标。你把数据传给他，他就直接帮你画好了。

你可以对比一下用这个两个库，展示一个`Bar`代码的区别。
