### ISSUE TITLE
制作G2Plot Line Chart,如何修改chart title后重新制图？

### ISSUE THREAD

**Issue by yufeishi** [antvis/G2Plot#543]
场景: 多语言环境。如果客户切换浏览器语言，title也需要切换成新的语言。

**Comment by Dreammy23** [comment]
chart.destory()后再重新渲染，因该可以实现吧

**Comment by paleface001** [comment]
可以使用`updateConfig`方法更新图表配置项，相关文档：https://g2plot.antv.vision/zh/docs/manual/general-config/#updateconfig

用法：
```
plot.updateConfig({
  title:{
      visible: true,
      text: 'en'
   }
});
plot.render();
```
