### ISSUE TITLE
柱状图 Guideline 支持数值 + 百分比混用

### ISSUE THREAD

**Issue by focus7eleven** [antvis/G2Plot#572]
纯数值的情况下，辅助线首尾会有两段空白

![image](https://user-images.githubusercontent.com/8576839/73820378-95f76200-482c-11ea-8d1e-00dab5c56da9.png)

期望的用法：

```js
{
  start: ['0%', value],
  end: ['100%', value],
}
```

**Comment by paleface001** [comment]
已在g2plot 1.0中支持

**Comment by SusanLiu93** [comment]
> 已在g2plot 1.0中支持

 start: ['0%',500],
 end: ['100%', 500], 不生效
