### ISSUE TITLE
转置漏斗图label显示不正确

### ISSUE THREAD

**Issue by paleface001** [antvis/G2Plot#573]
![image](https://user-images.githubusercontent.com/5888974/73898864-af98b800-48c5-11ea-8fc7-6e2cab1f1e37.png)

**Comment by licg9999** [comment]
文字显隐逻辑如下：
当图形内文字大小超过所在图形大小时，将隐藏文字。

在上图情况中，由于第二个文字大小超过了绿色图形，所以被隐藏。

@paleface001 请共同商量一下，是否有更优逻辑可以改善。

**Comment by paleface001** [comment]
> 文字显隐逻辑如下：
> 当图形内文字大小超过所在图形大小时，将隐藏文字。
> 
> 在上图情况中，由于第二个文字大小超过了绿色图形，所以被隐藏。
> 
> @paleface001 请共同商量一下，是否有更优逻辑可以改善。

感觉可以做一下进一步优化：
首先默认平行展示 => 如果显示不开则进行文本和数值的折行显示 => 还是显示不开最后隐藏

上图这种情况，折行显示应该就ok了
