### ISSUE TITLE
饼图的label没有全部显示，而且没有弄清楚展示规律

### ISSUE THREAD

**Issue by kotoyo1516** [antvis/G2Plot#582]
![官方饼图示例](https://gw.alipayobjects.com/mdn/rms_d314dd/afts/img/A*4swYTIoCUdQAAAAAAAAAAABkARQnAQ)
分类48的标签没有展示，而且找不到规律，有点是相邻都显示，有的是隔一个才显示

**Comment by Me-Momo** [comment]
1. 截图看不清楚，可以给下复现代码吗


2. 可以试着配置
```
label: {
  allowOverlap: true
}
```

**Comment by kotoyo1516** [comment]
> 1. 截图看不清楚，可以给下复现代码吗
> 2. 可以试着配置
> 
> ```
> label: {
>   allowOverlap: true
> }
> ```
官方的例子来的
https://g2plot.antv.vision/zh/examples/pie/basic#outer-center-label
你看看不是所有的分类都有展示label

**Comment by Me-Momo** [comment]
> > 1. 截图看不清楚，可以给下复现代码吗
> > 2. 可以试着配置
> > 
> > ```
> > label: {
> >   allowOverlap: true
> > }
> > ```
> 
> 官方的例子来的
> https://g2plot.antv.vision/zh/examples/pie/basic#outer-center-label
> 你看看不是所有的分类都有展示label

outer-center 这种label布局是不对标签进行碰撞检测偏移处理，当标签发生遮挡的时候，自动隐藏，    allowOverlap: true, 可以开启显示所有

**Comment by kotoyo1516** [comment]
> > > 1. 截图看不清楚，可以给下复现代码吗
> > > 2. 可以试着配置
> > > 
> > > ```
> > > label: {
> > >   allowOverlap: true
> > > }
> > > ```
> > 
> > 
> > 官方的例子来的
> > https://g2plot.antv.vision/zh/examples/pie/basic#outer-center-label
> > 你看看不是所有的分类都有展示label
> 
> outer-center 这种label布局是不对标签进行碰撞检测偏移处理，当标签发生遮挡的时候，自动隐藏， allowOverlap: true, 可以开启显示所有

解决了，谢谢回复

**Comment by Gripexfc** [comment]
![image](https://github.com/user-attachments/assets/8bfc9506-6a01-46ee-a59a-3b3c573c53b2)
![image](https://github.com/user-attachments/assets/7e708e1e-80bd-4f94-859b-9abf3b15cf9b)
la'blabel被遮挡
