### ISSUE TITLE
G2Plot使用bar图出现重叠导致不能正常显示

### ISSUE THREAD

**Issue by GiorgioPeng** [antvis/G2Plot#593]
效果图：
<img width="1696" alt="截屏2020-02-11下午3 20 24" src="https://user-images.githubusercontent.com/34415646/74217500-938c8080-4ce2-11ea-9ed4-5590eb334eb8.png">
数据：
<img width="227" alt="截屏2020-02-11下午3 21 45" src="https://user-images.githubusercontent.com/34415646/74217502-95564400-4ce2-11ea-8878-57535dd2337c.png">
渲染代码：
<img width="417" alt="截屏2020-02-11下午3 22 08" src="https://user-images.githubusercontent.com/34415646/74217503-95eeda80-4ce2-11ea-8d2e-cbdd4bfa28d2.png">

**Comment by paleface001** [comment]
xField和yField设反了，在条形图里面，xField对应的是连续字段，而yField对应的是分类字段

**Comment by GiorgioPeng** [comment]
好的,非常感谢.
