### ISSUE TITLE
饼图outer label需要加offset default值，否则update配置项后绘制错误

### ISSUE THREAD

**Issue by paleface001** [antvis/G2Plot#598]
<img width="1069" alt="屏幕快照 2020-02-12 下午2 03 34" src="https://user-images.githubusercontent.com/5888974/74307513-85049e80-4da0-11ea-9605-7f520cf7f145.png">

**Comment by Me-Momo** [comment]
复现地址：https://riddle.alibaba-inc.com/riddles/50918e5f
