### ISSUE TITLE
Ring Chart Total Title Configurable

### ISSUE THREAD

**Issue by lilbumblebear** [antvis/G2Plot#601]
I am not able to change the total Title for the Ring Chart. I have tried the following in my configuration file, but any time I interact with the chart, the total title reverts to: 总计

Configurations I have tried:
`statistic: {
                        visible: true,
                        content: {
                            name: 'Total',
                            value: 100
                        }
                    },`
and
`annotation:[
                        {
                            type: 'centralText',
                            onActive: true,
                            content: 'Total'
                        }
                    ]`

I would like to be able to change the title only for the Total data calculation. 
![Screen Shot 2020-02-12 at 11 17 26 AM](https://user-images.githubusercontent.com/18397507/74354555-8d051400-4d89-11ea-8e54-6c19ce952bc0.png)

Please let me know how to configure this chart correctly. Thank you!

**Comment by tcharlot-datasweet** [comment]
Hi !
try `statistic: {
               visible: true,
               triggerOn: false,
               triggerOff: false,
               content: { name: 'Total', value: 100 },
             },`

**Comment by lilbumblebear** [comment]
Perfect!  Thank you!  Can you point me to the documentation that would help me figure that out?
