### ISSUE TITLE
报错：_antv_util__WEBPACK_IMPORTED_MODULE_0__.assign is not a function

### ISSUE THREAD

**Issue by huruji** [antvis/G2Plot#644]
代码：
```typescript
import * as React from "react";
import { Bar } from '@antv/g2plot';
import SectionTitle from "../sectionTitle";


const Report: React.SFC = () => {
  const container = React.useRef(null)
  React.useEffect(() => {
    const data = [
      { year: '1951 年', sales: 38 },
      { year: '1952 年', sales: 52 },
      { year: '1956 年', sales: 61 },
      { year: '1957 年', sales: 145 },
      { year: '1958 年', sales: 48 },
    ];

    const barPlot = new Bar(container.current, {
      data,
      xField: 'sales',
      yField: 'year',
      colorField: 'year',
    });

    barPlot.render();
  }, [])
  return <section>
    <SectionTitle title={"title"} subTitle={"数据表现"} />
    <section>
      <section ref={container}></section>
    </section>
  </section>
};


export default Report;

```

![image](https://user-images.githubusercontent.com/15937065/75027552-b20c2c00-54d9-11ea-81b3-f3f1657e664f.png)

版本：

0.11.32

![image](https://user-images.githubusercontent.com/15937065/75027601-c7815600-54d9-11ea-8680-20f325b17713.png)

**Comment by k983551019** [comment]
+1

**Comment by huruji** [comment]
求大佬们解决下这个问题，好劝退呀

**Comment by BlackGanglion** [comment]
@huruji 我这边无法复现，能否在 CodeSandbox 复现一下，或者麻烦本地检查一下 @antv/util 的版本与引入情况？

**Comment by TP026787** [comment]
我也是这个问题

**Comment by paleface001** [comment]
出现这个问题的各位在使用G2Plot的时候是不是还同时使用了AntV其他项目？

**Comment by BlackGanglion** [comment]
> 出现这个问题的各位在使用G2Plot的时候是不是还同时使用了AntV其他项目？

QBI 这边同时依赖 G2 3.5.x 与 G2Plot 0.1.x 并没有发现该问题

**Comment by paleface001** [comment]
> > 出现这个问题的各位在使用G2Plot的时候是不是还同时使用了AntV其他项目？
> 
> QBI 这边同时依赖 G2 3.5.x 与 G2Plot 0.1.x 并没有发现该问题

今天一个用户同时依赖 G6 和 G2Plot，G  报出了类似问题

**Comment by huruji** [comment]
是的，我这边也依赖了 G6，用的是 ggeditor @paleface001

**Comment by dengjingcj** [comment]
在 antd pro 里面，应该是因为也内置了图表，所以也报这个错误

**Comment by suncongc** [comment]
引入了G6 同样这个问题，怎么解决啊.

**Comment by suncongc** [comment]
我在index.html里面引入了， <script src="https://unpkg.com/@antv/g2plot@latest/dist/g2plot.js"></script>。可以打印出 全局的 G2Plot。

**Comment by paleface001** [comment]
使用1.0版本应该不会有这个问题了
