### ISSUE TITLE
关于 pie label 的几个疑问

### ISSUE THREAD

**Issue by BlackGanglion** [antvis/G2Plot#649]
* adjustOverlap 中，先处理 label 与 label 之间的重叠，再处理 label 与 panel 重叠情况，如果反过来，理论上是否可以放置下更多的标签？
* checkInPanel 中“横向溢出，暂不隐藏”是否是因为 '...'  处理而不会存在溢出情况？
* 标签能否根据占比大小进行抽样，占比大的，优先能被显示

**Comment by BlackGanglion** [comment]
第三条已提 MR，https://github.com/antvis/G2Plot/pull/650

**Comment by Me-Momo** [comment]
第一点：应该区别不大，「处理 label 与 panel 重叠情况」 是判断是否溢出面板
