### ISSUE TITLE
[1.x] G2Plot 1.x 迁移问题汇总

### ISSUE THREAD

**Issue by zqlu** [antvis/G2Plot#663]

**Comment by paleface001** [comment]
cc: #661

**Comment by zqlu** [comment]
- [ ] build 和 CI 报错 @zqlu

**Comment by zqlu** [comment]
- [ ] 单侧错误修复

**Comment by zqlu** [comment]
- [ ] 1.x上的interaction： lineActive/lineSelect

**Comment by paleface001** [comment]
<img width="685" alt="屏幕快照 2020-02-27 下午2 57 41" src="https://user-images.githubusercontent.com/5888974/75419796-98536480-5971-11ea-93c5-a43a23ba5112.png">
legend唯一两侧时布局有问题

**Comment by paleface001** [comment]
面积图hover闪烁:
http://localhost:8000/zh/examples/area/basic

**Comment by paleface001** [comment]
饼图图形被切割：
<img width="683" alt="屏幕快照 2020-02-27 下午3 01 11" src="https://user-images.githubusercontent.com/5888974/75420021-0861ea80-5972-11ea-8bb9-0f47c4c82ad1.png">

**Comment by paleface001** [comment]
<img width="677" alt="屏幕快照 2020-02-27 下午3 01 52" src="https://user-images.githubusercontent.com/5888974/75420052-1c0d5100-5972-11ea-90db-d0340a147fbd.png">
环图中心文本没对齐

**Comment by paleface001** [comment]
<img width="587" alt="屏幕快照 2020-02-27 下午3 02 38" src="https://user-images.githubusercontent.com/5888974/75420164-5aa30b80-5972-11ea-8b69-c42a7947d86c.png">
分组玫瑰图图形重叠

**Comment by paleface001** [comment]
treemap钻取崩了

**Comment by paleface001** [comment]
> <img alt="屏幕快照 2020-02-27 下午2 57 41" width="685" src="https://user-images.githubusercontent.com/5888974/75419796-98536480-5971-11ea-93c5-a43a23ba5112.png">
> 
> legend唯于两侧时布局有问题

done

**Comment by paleface001** [comment]
> <img alt="屏幕快照 2020-02-27 下午3 02 38" width="587" src="https://user-images.githubusercontent.com/5888974/75420164-5aa30b80-5972-11ea-8b69-c42a7947d86c.png">
> 
> 分组玫瑰图图形重叠

done.

**Comment by paleface001** [comment]
> 饼图图形被切割：
> <img alt="屏幕快照 2020-02-27 下午3 01 11" width="683" src="https://user-images.githubusercontent.com/5888974/75420021-0861ea80-5972-11ea-8bb9-0f47c4c82ad1.png">

done

**Comment by paleface001** [comment]
> treemap钻取崩了

done.

**Comment by zqlu** [comment]
- [ ] Axis的样式配置不生效 @zqlu ING

**Comment by paleface001** [comment]
- [ ] theme不生效 @paleface001 ING

**Comment by paleface001** [comment]
- [ ] 标题&描述支持居中和居右  @paleface001

**Comment by BlackGanglion** [comment]
- [ ] 我们的默认 geom label 的 parser 貌似要更新一下，G2 4.0 有变化，而且不支持 formatter

![image](https://user-images.githubusercontent.com/9314735/75740981-1fbf2000-5d44-11ea-93d6-6dbd6e8f1efc.png)

from https://github.com/antvis/G2/issues/2113

**Comment by BlackGanglion** [comment]
theme: 'dark' 不生效

**Comment by paleface001** [comment]
- [ ] guideLine 线条样式配置失效

- [ ] guideLine在条形图不生效

@paleface001  ING

**Comment by paleface001** [comment]
<img width="677" alt="屏幕快照 2020-03-09 下午3 32 45" src="https://user-images.githubusercontent.com/5888974/76191894-59e46200-621b-11ea-8b71-3a1f0ee40370.png">

**Comment by paleface001** [comment]
densityHeatmap背景设置失效

**Comment by paleface001** [comment]
- [ ] default label formatter走查

- [ ] label formatter入参统一

**Comment by paleface001** [comment]
- [x] 雷达图label失效

**Comment by zqlu** [comment]
- [ ] 堆积柱状图开启联通区域组件后图例交互失效 @zqlu

**Comment by zqlu** [comment]
- [ ] http://localhost:8000/zh/examples/column/stacked#label-auto-hide 堆积柱状图label自动隐藏和图例交互一起后失效

**Comment by zqlu** [comment]
- [ ] http://localhost:8000/zh/examples/bar/basic 示例：axis.foramtter -> label.foramtter

**Comment by zqlu** [comment]
- [ ] slider和scrollbar交互加上后tooltip没有了 @zqlu

**Comment by zqlu** [comment]
- [ ] http://localhost:8000/zh/examples/line/multiple#line-label 更新label只有数字跟随

**Comment by paleface001** [comment]
> * [ ]  http://localhost:8000/zh/examples/column/stacked#label-auto-hide label自动隐藏和图例交互一起后失效，应该柱条自定义label都有这个问题

修复了

**Comment by paleface001** [comment]
> * [ ]  http://localhost:8000/zh/examples/bar/basic 示例：axis.foramtter -> label.foramtter

done

**Comment by paleface001** [comment]
> * [x]  堆积柱状图开启联通区域组件后图例交互失效 @zqlu

done
