### ISSUE TITLE
边缘的空白区域怎么添加的？看示例图的代码并没有什么特殊的配置

### ISSUE THREAD

**Issue by Dreammy23** [antvis/G2Plot#671]
![image](https://user-images.githubusercontent.com/18047832/75334515-f5dca800-58c2-11ea-984a-e4d700c573db.png)

**Comment by hustcc** [comment]
代码配置贴一下，我们帮你看看问题。

**Comment by hustcc** [comment]
x y 轴的 min max 不要设置。图形会自动计算合适的 min max 值。
