### ISSUE TITLE
【0.1.x】tooltip enterable 无效，且不断闪烁

### ISSUE THREAD

**Issue by BlackGanglion** [antvis/G2Plot#682]
![Feb-28-2020 16-54-07](https://user-images.githubusercontent.com/9314735/75525614-1e8fa980-5a4b-11ea-972f-5b513abc2e0c.gif)

复现链接：https://riddle.alibaba-inc.com/riddles/558a1c79?mode=jsx

**Comment by paleface001** [comment]
老实说...我的想法是想把enterable干掉的。

**Comment by BlackGanglion** [comment]
> 老实说...我的想法是想把enterable干掉的。

我们使用 enterable 有两个原因
1. 饼图有个‘其他’ 项做合并，那里面 tooltip 的信息密度很高，需要加滚动条
2. 我们图表外层容器有个蛋疼的 overflow: hidden（虽然我也不明白为啥要加），tooltip 的 container 在 3.5.x 上又不能挂在 document.body 上，所以过长只能滚动了。。。

**Comment by BlackGanglion** [comment]
> 老实说...我的想法是想把enterable干掉的。

我喽了眼 3.6.x 版本的 tooltip，感觉有点复杂，不知道有没有熟悉的同学能解一下这个问题

**Comment by paleface001** [comment]
这个新茗想做饼图合并的时候也遇到过，除了enterable之外能不能通过其他交互方式来解？
即follow鼠标又能enterable，我始终觉得是个不科学的设计..

**Comment by BlackGanglion** [comment]
> 这个新茗想做饼图合并的时候也遇到过，除了enterable之外能不能通过其他交互方式来解？
> 即follow鼠标又能enterable，我始终觉得是个不科学的设计..

我目前能想到的降级方案就是 tooltip 支持挂载在 body 上了，全量展示不滚动，有其他好的想法么？

**Comment by BlackGanglion** [comment]
@linhuiw 看一下这个问题如何处理，G2Plot 如果 cover 不住可能我们要寻求业务上的解法

**Comment by BlackGanglion** [comment]
等 1.x 升 G2 4.x 吧，我们业务上先只显示其他，不显示明细
