### ISSUE TITLE
G2Plot 新版文档模板

### ISSUE THREAD

**Issue by paleface001** [antvis/G2Plot#699]
https://yuque.antfin-inc.com/antv/lghpbw/epeou2

大家看看文档这个结构ok吗？

**Comment by paleface001** [comment]
@hustcc @zqlu @Me-Momo @BlackGanglion @linhuiw @afc163 @dxq613

**Comment by afc163** [comment]
LGTM，可以写成 list 或者 table，尽量不要裸格式。

**Comment by paleface001** [comment]
> LGTM，可以写成 list 或者 table，尽量不要裸格式。

细分配置项可以table

**Comment by paleface001** [comment]
close,已经开始往新模板迁移
