### ISSUE TITLE
使用meta命名别名的时候，如果同时使用了seriesField就会失效？！

### ISSUE THREAD

**Issue by Fireplayer** [antvis/G2Plot#702]

**Comment by paleface001** [comment]
并没有失效啊？请提供复现demo? !

**Comment by chicheng** [comment]
https://g2plot.antv.vision/zh/examples/step-line/multiple#step-label
加上
`meta:{China:{alias:"中国"}},`

**Comment by chicheng** [comment]
https://g2plot.antv.vision/zh/examples/line/multiple
`meta:{bill:{alias:"账单"}},`

**Comment by paleface001** [comment]
meta里面传递的是字段名，比如https://g2plot.antv.vision/zh/examples/line/multiple 这个例子里，应该对`type`配置meta。如果是想为该字段所有值指定假名，可以用meta里面的formatter进行配置：

```
  meta:{
    type:{
      formatter:(v)=>{
        const mapping= {
          bill:'订单',
          register:'注册',
          download:'下载'
        };
        return mapping[v];
      }
    }
  },
```
