### ISSUE TITLE
饼图label的type除设置为Spider以外均空指针报错。

### ISSUE THREAD

**Issue by Ghostliming** [antvis/G2Plot#720]
现在使用的版本是：@antv/g2plot: 0.11.27。在配置饼图label的时候，只有type为spider的时候label不报错，其他的均报错。labels获取到的长度永远是data的两倍，导致以labels编译去data中取值的时候空指针。
![image](https://user-images.githubusercontent.com/11506222/76046319-92293d80-5f9a-11ea-8a8d-b86722e229c2.png)

**Comment by Me-Momo** [comment]
可以给下复现步骤吗

**Comment by Ghostliming** [comment]
> 可以给下复现步骤吗

我找到这个问题的问题了，由于在饼图中的label的formatter 是返回的一个数组，所以导致了此处label数量大于数据条数。

**Comment by Me-Momo** [comment]
> > 可以给下复现步骤吗
> 
> 我找到这个问题的问题了，由于在饼图中的label的formatter 是返回的一个数组，所以导致了此处label数量大于数据条数。

所以问题解决了是么（spider布局的formatter确实和其他不同）

**Comment by Ghostliming** [comment]
> > > 可以给下复现步骤吗
> > 
> > 
> > 我找到这个问题的问题了，由于在饼图中的label的formatter 是返回的一个数组，所以导致了此处label数量大于数据条数。
> 
> 所以问题解决了是么（spider布局的formatter确实和其他不同）

解决了，谢谢！
