### ISSUE TITLE
【讨论】饼图 label 分段省略的设计方案

### ISSUE THREAD

**Issue by BlackGanglion** [antvis/G2Plot#726]
### 目前业务中的实现方案
![1583326904562-e8a0a759-290c-419c-aa97-d4d1c9e3c35e](https://user-images.githubusercontent.com/9314735/76145472-9c475b00-60c4-11ea-8bcb-7315f959a052.png)

其中**维度值**、**度量值**、**百分比** 是否显示由用户配置，顺序不变

• 先全量放置 **度量值** 与 **百分比**，看看 **维度值** 是否可以放下至少一个字符
• 如果可以，那么 **度量值** 与 **百分比** 全量放置，剩余空间给 **维度值**
• 如果不可以，那么 **维度值** 放置一个字符 + ...，剩余空间给  **度量值** 与 **百分比** 按现有宽度，等比压缩
• 如果分配给 **维度值** 与  **百分比** 小于 ...，那么整个标签就不需要显示了

### 方案一
分段进行配置，content 为内容，priority为显示优先级，keep为内容中必须要保留的内容，此方案配置比较复杂，priority间的依赖关系与分配显示的区域宽度，keep字符与 ... 的位置关系，比较难处理
```js
label: {
  formatter: () => {
    return [
      { content: name, priority: 2, keep: [name[0]] },
      { content: value, priority: 1 },
      { content: `(${percent})`, priority: 1, keep: ['(', ')']  },
    ];
  }
}
```

### 方案二
仅有一个是否开启 label 分段省略的配置项，对用户 formatter 的结果进行自动识别，利用沉淀的业务规则进行省略。此方案自动识别感觉实现上有难度

**Comment by paleface001** [comment]
```
label:{
  visible: true,
  content:{
      name: {
          priority: 1,
          keep: 文字或正则
         formatter:()=>{},
      },
     value:{
         priority: 2,
         formatter:()=>{},
         keep: 文字或正则
     },
     percent:{
          priority: 3,
         formatter:()=>{},
         keep: 文字或正则
     }
   }
}
```
如果这样呢？ 用户设置了formatter则覆盖自动省略的内容

**Comment by hustcc** [comment]
暂定这样的结构，尝试实现。

```ts
label:{
  visible: true,
   name: {
          visible: true,
          priority: 1,
          keep: 文字或正则
         formatter:()=>{},
         style: {}
      },
     value:{
         visible: true,
         priority: 2,
         formatter:()=>{},
         keep: 文字或正则,
         style: {}
     },
     percent:{
          visible: true,
          priority: 3,
         formatter:()=>{},
         keep: 文字或正则
         style: {}
     }
  },
  template: '{name}\n{value}, {percent}',
}
```

**Comment by BlackGanglion** [comment]
@paleface001 @hustcc 我先按今天讨论结果尝试实现一版吧，还有一个问题就是 keep 如果把 content 分成多截怎么办？分截再 ... 么？

**Comment by paleface001** [comment]
keep为啥会把文字分成几截呢？我理解keep应该是配置文本省略的规则？

**Comment by BlackGanglion** [comment]
> keep为啥会把文字分成几截呢？我理解keep应该是配置文本省略的规则？

我的本意是需要保留的字符

**Comment by paleface001** [comment]
转移到antv讨论区讨论
