### ISSUE TITLE
Ring在changeData后，statistic不更新

### ISSUE THREAD

**Issue by zim-lee** [antvis/G2Plot#730]
更新数据后，统计值不更新，必须要在图表上移动的鼠标才更新，如果trigger设置为false，完全没方法更新了。目前只能updateConfig后重新render，希望修复下这个问题

**Comment by paleface001** [comment]
```
statistic: {
    visible: true,
    content:{
      name:'test',
      value:'100'
    }
  }
```
trigger为false的时候可以通过设置`content`进行更新。
更新数据后指标卡组件没有重新渲染，所以会造成这个问题。所有环图指标卡的Bug我们会优先排期修复。

**Comment by Me-Momo** [comment]
![image](https://user-images.githubusercontent.com/15646325/76813280-6cb9f080-6832-11ea-8d16-d1899645a69e.png)
目前好像是会更新的？可以给一个复现的demo吗

**Comment by zim-lee** [comment]
https://codepen.io/zim-lee/pen/JjdvwzR

现在好像连分类都不更新了 @Me-Momo

**Comment by Me-Momo** [comment]
> https://codepen.io/zim-lee/pen/JjdvwzR
> 
> 现在好像连分类都不更新了 @Me-Momo

changeData 之后，要手动调用一下 render ～

**Comment by zim-lee** [comment]
麻烦更新下文档呗，都没描述changeData后还需要render @Me-Momo 
新的文档好像连Ring的说明都不见了

**Comment by paleface001** [comment]
> 麻烦更新下文档呗，都没描述changeData后还需要render @Me-Momo
> 新的文档好像连Ring的说明都不见了

https://g2plot.antv.vision/zh/docs/manual/plots/donut

**Comment by paleface001** [comment]
changeData这个是个bug，稍后会修复~~~

**Comment by wangliang01** [comment]
如果只增加render()方法，会导致legend重复渲染。目前看来是要用在render()之前，先调用一下updateConfig()

**Comment by leitingx762** [comment]
> 如果只增加render()方法，会导致legend重复渲染。目前看来是要用在render()之前，先调用一下updateConfig()

确实，changeData()再render()会出现legend重复的现象，拖拽窗口就会发现
