### ISSUE TITLE
如何修改环图中心标题“总计”？

### ISSUE THREAD

**Issue by chicheng** [antvis/G2Plot#736]
需要显示为英文 `Total`，谢谢。

相关demo：
https://g2plot.antv.vision/en/examples/pie/ring

**Comment by afc163** [comment]
看了下源码好像是写死的？@paleface001 看看。

**Comment by paleface001** [comment]
> 看了下源码好像是写死的？@paleface001 看看。

确实是写死的，这块得开一个callback给用户。 @Me-Momo  一起看下
