### ISSUE TITLE
Could not find dependency: 'lodash'

### ISSUE THREAD

**Issue by afc163** [antvis/G2Plot#744]
https://codesandbox.io/s/blissful-golick-7rp8v

**Comment by paleface001** [comment]
https://github.com/antvis/G2Plot/blob/985833ffdf6164e5d21882de28c07c70e7b21b10/src/plots/pie/component/label/inner-label.ts#L5

**Comment by afc163** [comment]
依赖里有个 tslib 看着没用到。

**Comment by paleface001** [comment]
> 依赖里有个 tslib 看着没用到。

1.x已干掉

**Comment by atzcl** [comment]
希望 antv 相关的项目不要这么直接粗暴地 `import * as _ from 'lodash'`，这样会硬生生把整个 lodash 都给打包进去的，哪怕只是用了几个方法 ...

![image](https://user-images.githubusercontent.com/28823188/76475595-5da1ff80-643a-11ea-99f3-ef144f8b7340.png)

**Comment by afc163** [comment]
@atzcl 对的，会马上更新。

@paleface001 这里改掉速度发个 patch。

**Comment by Me-Momo** [comment]
> 希望 antv 相关的项目不要这么直接粗暴地 `import * as _ from 'lodash'`，可以使用 cherry pick 按需加载 lodash ，不然这样会硬生生把整个 lodash 都给打包进去的，哪怕只是用了几个方法，
> 
> ![image](https://user-images.githubusercontent.com/28823188/76475595-5da1ff80-643a-11ea-99f3-ef144f8b7340.png)

不好意思，马上改掉

**Comment by afc163** [comment]
是不是可以加个 https://www.npmjs.com/package/eslint-plugin-you-dont-need-lodash-underscore

**Comment by paleface001** [comment]
> 是不是可以加个 https://www.npmjs.com/package/eslint-plugin-you-dont-need-lodash-underscore

感觉口以有，感觉还可以写一份代码规范，把util按需引用这类写进去

**Comment by paleface001** [comment]
0.11.38版本已修复
