### ISSUE TITLE
[bug] forceFit do not work when specify height

### ISSUE THREAD

**Issue by afc163** [antvis/G2Plot#745]
https://codesandbox.io/s/blissful-golick-7rp8v

**Comment by hustcc** [comment]
![image](https://user-images.githubusercontent.com/7856674/77733935-aebd1080-7042-11ea-9b5d-7fdadc8a6585.png)


问题在于因为[类似的问题](https://github.com/antvis/G2/issues/2159)，导致重复 resize。暂时还是在 G2Plot 中砂纸  canvas 样式

**Comment by afc163** [comment]
@simaQ 来看看

**Comment by hustcc** [comment]
> @simaQ 来看看

个人建议，还是在 G 层修复比较好，毕竟 G 也是公开可以使用的，而且对于 canvas svg 这种绝对布局的，去做自动 resize，还是非常常见的。
