### ISSUE TITLE
对象不支持“remove”属性或方法

### ISSUE THREAD

**Issue by qyongkang** [antvis/G2Plot#747]
ie 浏览器 使用 tooltip 的htmlContent属性  一直提示 对象不支持“remove”属性或方法

**Comment by afc163** [comment]
https://caniuse.com/#search=remove

remove 兼容性不好，我们得换掉。

**Comment by paleface001** [comment]
1.0使用的新版component用的removeChild，看了下兼容性有提升：

https://caniuse.com/#search=removeChild
