### ISSUE TITLE
图表updateConfig后，stateManager就失效了

### ISSUE THREAD

**Issue by chenzhiwei199** [antvis/G2Plot#748]
通过StateManger进行状态管理，当图表通过updateConfig更新后，StateManger就失效了
https://riddle.alibaba-inc.com/riddles/318cb0a

**Comment by paleface001** [comment]
感谢提供复现riddle，这边会抓紧排查一下

**Comment by chenzhiwei199** [comment]
有提供的

**Comment by chenzhiwei199** [comment]
> 感谢提供复现riddle，这边会抓紧排查一下

提供过了
https://riddle.alibaba-inc.com/riddles/318cb0a
