### ISSUE TITLE
饼图带负数的情况下百分比处理方案

### ISSUE THREAD

**Issue by Ghostliming** [antvis/G2Plot#756]
1.现在的饼图在带负数的情况下，会直接通过累加所有数，然后用每一个数据除总数得百分比。这样如果负数比较大的情况，总数未负数。那么所有的正数的百分比就会为负，负数的就会为正。建议处理方案为负数不做百分比展示。
2. 如果有负数存在，label的位置错误。如例子所示，分类四的位置。
[代码示例](https://codesandbox.io/s/muddy-sunset-x21x2)

**Comment by BlackGanglion** [comment]
建议 data 传入 g2plot 前对负数做一下过滤

**Comment by Ghostliming** [comment]
> 建议 data 传入 g2plot 前对负数做一下过滤

因为我们目前产品是有负数的情况存在，目前感觉是渲染图形的时候是根据数据的绝对值渲染的，但是label的百分比没有按照绝对值。但是如果按照绝对值确实也有问题，或者看能否提供可以配置的方式。

**Comment by Me-Momo** [comment]
可以在业务层，对负数的数据进行过滤
