### ISSUE TITLE
堆叠柱状图 label 标签颜色配置失效

### ISSUE THREAD

**Issue by chenzhiwei199** [antvis/G2Plot#760]
![image](https://user-images.githubusercontent.com/20192061/76598110-13557700-653d-11ea-9665-da6387fe5e1c.png)

riddle 地址 https://riddle.alibaba-inc.com/riddles/258d0412

**Comment by paleface001** [comment]
这是因为label默认自动使用图形颜色，设置label.adjustColor为false即可
