### ISSUE TITLE
水波图修改数值(value)问题

### ISSUE THREAD

**Issue by cuiweihao1998** [antvis/G2Plot#761]
使用plot.chengeValue(value),修改值，修改值之后初始化的value还会保留，导致页面上会有很多value重叠。具体效果如下图所示。请问是什么原因导致的，如何解决。
![image](https://user-images.githubusercontent.com/46740856/76598911-d1c5cb80-653e-11ea-9d97-91427547a231.png)

**Comment by paleface001** [comment]
```
liquidPlot.updateConfig({
  value:6000
});

liquidPlot.render();
```
