### ISSUE TITLE
添加 Pipline 图表

### ISSUE THREAD

**Issue by wuzhao** [antvis/G2Plot#763]
![image](https://user-images.githubusercontent.com/712075/76626891-ecb33280-6574-11ea-820a-20780eedd379.png)

可以临时通过类似 G6 的图来解决。https://g6.antv.vision/zh/examples/case/customFlow

**Comment by paleface001** [comment]
G2Plot中地理类图表和关系类图表这两个确实的板块，怎么能够借助 L7 和 G6 的力量补起来，同时使 AntV 地理和关系可视化这个两个专业领域触达到更多的用户。

这个事情等1.0发布完之后需要好好规划一下了。

@kener  @afc163  @dxq613 @lzxue @Yanyan-Wang

**Comment by afc163** [comment]
这个肯定直接用 G6 做，放 G2Plot 里很难抽象。

**Comment by paleface001** [comment]
这个是云凤蝶的需求。倒不是单指这个图表，但和统计地图类似，一些常用的关系类图表比如桑基图、和弦图等等，g2plot是要有的。
https://www.echartsjs.com/examples/zh/index.html#chart-type-graph
https://www.highcharts.com.cn/demo/highcharts#relation-ship

**Comment by paleface001** [comment]
转移至antv讨论区讨论
