### ISSUE TITLE
双轴图中，line图如果配置了point，tooltip中展示项目错误。

### ISSUE THREAD

**Issue by Ghostliming** [antvis/G2Plot#768]
本来只有三项，结果展示了四项出来。
![image](https://user-images.githubusercontent.com/11506222/76672986-1f444600-65dc-11ea-9329-d2a87475b3a3.png)
[代码示例](https://codesandbox.io/s/sweet-kepler-j5le7)

**Comment by Ghostliming** [comment]
另外还有tooltip错位的问题，比如我放在第一周，它还是展示的“逾期”组的tooltip, 放在“第2周”展示的“第一周”的数据。

**Comment by paleface001** [comment]
目前双轴图对用户提供的方案过于底层，后续会在1.0小版本重构一下，对于一些常用双轴图，比如柱线混合、双折线等等，这样就没有这个问题了

**Comment by donglegend** [comment]
这个没修复吧？ 双轴图tooltip 错位现象很严重
