### ISSUE TITLE
堆叠条形图，tooltip抖动的厉害

### ISSUE THREAD

**Issue by chenzhiwei199** [antvis/G2Plot#769]
堆叠条形图，tooltip抖动的厉害

![抖动](https://user-images.githubusercontent.com/20192061/76677467-85938d80-6609-11ea-87eb-e12cd37a8222.gif)

riddle复现例子： https://riddle.alibaba-inc.com/riddles/cf196f08

**Comment by chenzhiwei199** [comment]
录制的图片效果感觉不是那么明显。。。

**Comment by zqlu** [comment]
这个问题在最新代码里面好像已经ok了
