### ISSUE TITLE
Bar图的label 展示出来有textShadow，如何能去除？

### ISSUE THREAD

**Issue by Ghostliming** [antvis/G2Plot#774]
![image](https://user-images.githubusercontent.com/11506222/76723659-06c26000-6783-11ea-8d38-f41524700d8e.png)

如何能移除这个黑色label的白色背景。

**Comment by paleface001** [comment]
这个效果是label默认样式的白色描边，去除方式：

```
label:{
   visible: true,
   adjustColor: false,
   style:{
     stroke: null
   }
}
```
