### ISSUE TITLE
环图中心文本 content 配置

### ISSUE THREAD

**Issue by Me-Momo** [antvis/G2Plot#784]
![image](https://user-images.githubusercontent.com/15646325/76812527-22d00b00-6830-11ea-8046-bc1a6715f93c.png)

`content`配置存在的原因：为了自定义显示中心文本内容
现状：
初始化的时候，显示 content，但是在 trigger 事件之后，又显示总计，是否要修改为 配置content的时候，`trigger` 非激活状态，始终显示 `content` 内容

**Comment by paleface001** [comment]
是滴，或者把content改成callback的形式
