### ISSUE TITLE
联通区域对比组件超过范围

### ISSUE THREAD

**Issue by zqlu** [antvis/G2Plot#786]
![image](https://user-images.githubusercontent.com/1142242/76815003-5b271780-6837-11ea-8f5d-7ae1fcf58e10.png)

**Comment by paleface001** [comment]
好森奇，来个riddle我看看咋回事

**Comment by zqlu** [comment]
> 好森奇，来个riddle我看看咋回事

在这 https://riddle.alibaba-inc.com/riddles/60757434，设置了Y轴的max

**Comment by paleface001** [comment]
嚯，看来是设置clip没有clip掉

**Comment by paleface001** [comment]
fixed via #823
