### ISSUE TITLE
g2plot里面怎么针对多个视觉通道进行tooltip的formatter

### ISSUE THREAD

**Issue by chenzhiwei199** [antvis/G2Plot#792]
比如堆叠柱状图，一个x轴维度，多个指标，映射y轴的值和颜色通道，需要根据不同的颜色通道进行数值的格式化
chart.tooltip('time*type*value', ( time, type, value) => {
  return { name: time + ':'+ type, value}
})
g2里可以通过这样的方式实现，我再阅读文档后发现tooltip没有formatter回调，通过尝试在meta里面使用 下面这种写法也没有用
{
  'time*type*value': {
     formatter: () => {}
   }
} ，
并且meta中的formatter方法也没有额外参数可以进行辅助判断。。。是目前不支持吗，还是以后也不会支持。。。

**Comment by chenzhiwei199** [comment]
为啥这个就关了。。。

**Comment by paleface001** [comment]
往上看，已经支持了，明天发版本

**Comment by chenzhiwei199** [comment]
好的，非常感谢，之前看ts定义里有formatter，但是没调到，没想到这么快就好了，厉害

**Comment by paleface001** [comment]
每一个图表的formatter默认入参逻辑不同，所以更新起来有些复杂。不过确实是一个非常必要的配置，所以快速支持了，文档稍后补上~

**Comment by chenzhiwei199** [comment]
非常有用的封装，大大减少图表开发的工作量，特别是autoPadding，非常的友好

**Comment by xudihui** [comment]
> 往上看，已经支持了，明天发版本

大佬，请问一下，formatter的版本已经发布了吗

**Comment by paleface001** [comment]
> > 往上看，已经支持了，明天发版本
> 
> 大佬，请问一下，formatter的版本已经发布了吗

发布了，使用方法：

```
  tooltip:{
    formatter:(...args)=>{
      //console.log(args);
      return {
        name:'a',
        value: 2
      }
    }
```

也可以通过指定tooltip的关联字段 `fields`  做更高程度的定制：

```
  tooltip:{
    fields:['a', 'b', 'c'],
    formatter:(...args)=>{
      //console.log(args);
      return {
        name:'a',
        value: 2
      }
    }
```

**Comment by xudihui** [comment]
> > > 往上看，已经支持了，明天发版本
> > 
> > 
> > 大佬，请问一下，formatter的版本已经发布了吗
> 
> 发布了，使用方法：
> 
> ```
>   tooltip:{
>     formatter:(...args)=>{
>       //console.log(args);
>       return {
>         name:'a',
>         value: 2
>       }
>     }
> ```
> 
> 也可以通过指定tooltip的关联字段 `fields` 做更高程度的定制：
> 
> ```
>   tooltip:{
>     fields:['a', 'b', 'c'],
>     formatter:(...args)=>{
>       //console.log(args);
>       return {
>         name:'a',
>         value: 2
>       }
>     }
> ```

收到，谢谢大佬

**Comment by xudihui** [comment]
> > > 往上看，已经支持了，明天发版本
> > 
> > 
> > 大佬，请问一下，formatter的版本已经发布了吗
> 
> 发布了，使用方法：
> 
> ```
>   tooltip:{
>     formatter:(...args)=>{
>       //console.log(args);
>       return {
>         name:'a',
>         value: 2
>       }
>     }
> ```
> 
> 也可以通过指定tooltip的关联字段 `fields` 做更高程度的定制：
> 
> ```
>   tooltip:{
>     fields:['a', 'b', 'c'],
>     formatter:(...args)=>{
>       //console.log(args);
>       return {
>         name:'a',
>         value: 2
>       }
>     }
> ```

大佬，在'/src/interface/config.ts'这个配置内部，我看到
export interface Tooltip {
  ....
  formatter?: (...args: any) => string;
  ...
}
但你回复的API是return一个对象，这里是否需要更新formatter接口声明
