### ISSUE TITLE
热力图通过updateConfig方法更新宽度后报错

### ISSUE THREAD

**Issue by chenzhiwei199** [antvis/G2Plot#805]
复现链接： https://codesandbox.io/s/thirsty-shirley-grtyo
报错截图： 
![image](https://user-images.githubusercontent.com/20192061/77043871-5c07a700-69f9-11ea-9d38-d0debbf02afc.png)

**Comment by ChrisEddy** [comment]
I have same bug.

**Comment by hustcc** [comment]
之前已经被解决了，但是 issue 之前没有关闭。
