### ISSUE TITLE
Pie 饼图的 meta 设置不生效

### ISSUE THREAD

**Issue by dengfuping** [antvis/G2Plot#806]
- G2Plot 版本: 1.0.1
- 重现链接: https://codesandbox.io/s/eager-fermat-d5xoz

**Comment by yuanyayi** [comment]
G2Plot更新版本1.0.2，饼图Pie的meta设置formatter依然没有生效。
我在下载的源代码中找到了#807提交的代码，但是formatter依然没有生效。

![image](https://user-images.githubusercontent.com/19421507/77847213-db615b80-71ed-11ea-8e15-001cf3ab4d68.png)

**Comment by yuanyayi** [comment]
我设置的formatter是对数据使用千分位标记法。tooltip中表现正常，但是label中没有效果。
