### ISSUE TITLE
堆叠面积图 areaLabel 不随x轴拖动导致的图线变化移动位置

### ISSUE THREAD

**Issue by chicheng** [antvis/G2Plot#811]
在 [areaLabel 示例](https://g2plot.antv.vision/en/examples/area/stacked#area-label) 加上interactions后拖动x轴时间范围：

`    interactions: [
        {
            type: 'slider',
            cfg: {
                start: 0.4,
                end: 1,
            },
        },
    ],
`

1.0.1 和 1.0.2 都可以复现，0.11.35和0.11.40中areaLabel可随图线变化移动到正确的位置。

Firefox 74 & Chrome 80

**Comment by chicheng** [comment]
[堆叠柱状图](https://g2plot.antv.vision/en/examples/column/stacked#label-auto-hide) 加上interactions后label一样不会移动

**Comment by paleface001** [comment]
好的，下周五之前fix

**Comment by zqlu** [comment]
已修复
