### ISSUE TITLE
请问line中的点击事件怎么使用？

### ISSUE THREAD

**Issue by zmaydays** [antvis/G2Plot#817]
![image](https://user-images.githubusercontent.com/25202083/77177648-d707b500-6b00-11ea-822b-5ce6f6ffe38e.png)

![image](https://user-images.githubusercontent.com/25202083/77177797-17673300-6b01-11ea-87bd-6498565ccde5.png)

**Comment by paleface001** [comment]
看来还需要补充一下demo

所有的事件都在`events`配置项里，使用方式：

```

const line = new Line(container,{
   events:{
       onLineClick(e)=>{
           console.log(e);
       }
   }
});

**Comment by arcsin1** [comment]
文档还没更新 ，还好找到这个issue
