### ISSUE TITLE
漏斗图没有兼容标题,图表区域出现重叠

### ISSUE THREAD

**Issue by JasonWong-ZS** [antvis/G2Plot#818]
![image](https://user-images.githubusercontent.com/20633660/77217422-63e05c00-6b5d-11ea-8a5d-c26c787a406d.png)
import { Funnel } from '@antv/g2plot';

const data = [
  { action: '浏览网站', pv: 50000 },
  { action: '放入购物车', pv: 35000 },
  { action: '生成订单', pv: 25000 },
  { action: '支付', pv: 15000 },
  { action: '成交', pv: 8500 },
];

const funnelPlot = new Funnel(document.getElementById('container'), {
  data,
  xField: 'action',
  yField: 'pv',
  dynamicHeight: true,
    title:{
    visible:true,
    text:'测试漏斗图标题兼容性',
  },
 
});
funnelPlot.render();

**Comment by paleface001** [comment]
fixed via #987
