### ISSUE TITLE
bundle size problem

### ISSUE THREAD

**Issue by afc163** [antvis/G2Plot#825]
1.0.2 包体积高了很多，需要检查一下。

https://bundlephobia.com/result?p=@antv/g2plot

<img width="338" alt="image" src="https://user-images.githubusercontent.com/507615/77301531-cc306880-6d2a-11ea-9867-16d881bcda7a.png">

**Comment by paleface001** [comment]
1.0.1
<img width="1286" alt="屏幕快照 2020-03-23 下午5 24 47" src="https://user-images.githubusercontent.com/5888974/77301767-36490d80-6d2b-11ea-8edc-c4d31850d681.png">

1.0.2
<img width="1181" alt="屏幕快照 2020-03-23 下午5 24 59" src="https://user-images.githubusercontent.com/5888974/77301781-3e08b200-6d2b-11ea-855d-93abb928a232.png">

怀疑跟我们的打包方式有关系 @zqlu

**Comment by paleface001** [comment]
对比一下0.x版本和1.0版本，更新完底层技术栈(g,g2)之后包体积翻了一倍

**Comment by zqlu** [comment]
1.0.2里面G相关的应该有双份

**Comment by paleface001** [comment]
1.0.3的bundle size降了一些，不过仍然是ECharts的两倍，看来这个问题要专门排期解一下了 🌚

**Comment by zqlu** [comment]
等 G2 下一个版本发布后，再来检查这两部分的合并缩小
![image](https://user-images.githubusercontent.com/1142242/78094103-49806b00-7406-11ea-88fb-0551f1d18669.png)

**Comment by afc163** [comment]
为啥 1.0.3-beta.1 这么小。

**Comment by zqlu** [comment]
> 为啥 1.0.3-beta.1 这么小。

1.0.3-beta.1 几个beta版本是我测试dependency和peerDependency的区别，如果把G2之外的AntV依赖都声明peerDependency，这个size是会减小；如果下个版本G2之后还有问题，可以再考虑

**Comment by zqlu** [comment]
G2边的升级已经发布，G2Plot新版本发布后大小就和之前的beta版本一致了：
![image](https://user-images.githubusercontent.com/1142242/78769872-731a3300-79c0-11ea-84f8-d0ea2bf7e19a.png)


等G层几个包新版本发布后，这部分应该还会减小：
![image](https://user-images.githubusercontent.com/1142242/78769800-609ff980-79c0-11ea-96cb-cece397750ea.png)

**Comment by afc163** [comment]
原因是啥？

**Comment by zqlu** [comment]
> 原因是啥？

* 之前有次版本是因为G2和G2Plot依赖的G版本不一致，导致打包两份G
* 还有应该是G/G2指定了browser字段，导致webpack打包的时候browser bundle中也会有重复的G/Component/Util等代码

**Comment by afc163** [comment]
比 echarts 还大不少，加油：https://bundlephobia.com/result?p=echarts@4.7.0

**Comment by hustcc** [comment]
> 比 echarts 还大不少，加油：https://bundlephobia.com/result?p=echarts@4.7.0

已经优化至 800 Kb 内了。稍小于 echarts！

![image](https://user-images.githubusercontent.com/7856674/97259556-054b3100-1856-11eb-95cc-3ec63c15be84.png)
