### ISSUE TITLE
antd Chart 迁移 1.0 问题集中

### ISSUE THREAD

**Issue by paleface001** [antvis/G2Plot#831]

**Comment by lxfu** [comment]
- Donut destroy is not function
<img width="961" alt="058C3578-B939-4FB7-A50C-43E1A39CA9B8" src="https://user-images.githubusercontent.com/20291784/77398162-f2fda600-6de1-11ea-93b1-9554d5e32f2b.png">

**Comment by lxfu** [comment]
- heatmap  getWidth  of undefined
<img width="931" alt="21A2F8B5-321C-4B1B-92CA-0010831B78C1" src="https://user-images.githubusercontent.com/20291784/77398287-335d2400-6de2-11ea-8c10-9ca80b612e0f.png">

**Comment by lxfu** [comment]
- g2plot props  style and antdCharts props style conflict
<img width="496" alt="5B630382-C234-4052-86E5-2646A150ABBA" src="https://user-images.githubusercontent.com/20291784/77398622-ddd54700-6de2-11ea-8523-8b1a7fa84146.png">

**Comment by paleface001** [comment]
> * Donut destroy is not function
> 
> <img alt="058C3578-B939-4FB7-A50C-43E1A39CA9B8" width="961" src="https://user-images.githubusercontent.com/20291784/77398162-f2fda600-6de1-11ea-93b1-9554d5e32f2b.png">

done.

**Comment by lxfu** [comment]
- OverlappedComboPlot 'values' of undefined，assign a [] value first,  fetch data and then render again.
<img width="891" alt="3382A30C-07DA-4EFA-9D91-FD78B5B8CFB3" src="https://user-images.githubusercontent.com/20291784/77400271-dd8a7b00-6de5-11ea-8f53-be6a746954c1.png">

**Comment by paleface001** [comment]
> * g2plot props  style and antdCharts props style conflict
> 
> <img alt="5B630382-C234-4052-86E5-2646A150ABBA" width="496" src="https://user-images.githubusercontent.com/20291784/77398622-ddd54700-6de2-11ea-8523-8b1a7fa84146.png">

done

**Comment by afc163** [comment]
@lxfu 统一给重现演示。

**Comment by paleface001** [comment]
> * heatmap  getWidth  of undefined
> 
> <img alt="21A2F8B5-321C-4B1B-92CA-0010831B78C1" width="931" src="https://user-images.githubusercontent.com/20291784/77398287-335d2400-6de2-11ea-8c10-9ca80b612e0f.png">

done.

**Comment by paleface001** [comment]
> * OverlappedComboPlot 'values' of undefined，assign a [] value first,  fetch data and then render again.
> 
> <img alt="3382A30C-07DA-4EFA-9D91-FD78B5B8CFB3" width="891" src="https://user-images.githubusercontent.com/20291784/77400271-dd8a7b00-6de5-11ea-8f53-be6a746954c1.png">

done.
