### ISSUE TITLE
柱状图显示的问题，明明有值，但是柱子无法显示，是最新的1.0.2版本

### ISSUE THREAD

**Issue by pine-zhao** [antvis/G2Plot#834]
![image](https://user-images.githubusercontent.com/52899092/77404837-33d9c880-6daa-11ea-8e8a-94192bbf39c8.png)

**Comment by paleface001** [comment]
https://codesandbox.io/s/g2qez  来个复现demo吧

**Comment by pine-zhao** [comment]
![image](https://user-images.githubusercontent.com/52899092/77407963-ea3fac80-6dae-11ea-8df7-a4e7921f0807.png)

**Comment by paleface001** [comment]
你的y轴字段数据是string类型的，转换成number吧。

**Comment by pine-zhao** [comment]
在codesandbox很难复现出来。
import React from 'react';
import {StackedArea,Column,StateManager} from '@antv/g2plot';
import utils from '@utils';
import requestFilter from 'Services/requestFilter';

class LineDeploy extends React.Component {

  constructor(props) {
    super(props);
    this.state = {
      data:null,
      dayBefore:7,
      deployDate:null,
      deployTime:null,
    };
  }

    componentDidMount(){
      this.showChart();
    
      if(this.props.autoRefresh){
        this.showChart();

      }
    }

  


    showChart=async ()=>{
        await this.getData();
        const {data}=this.state;
        this.showLine(data);
        if(data){
          this.changeDeployData(data[data.length-1]);
        }
        // this.showDeploy(data);
    }

    showLine=(data)=>{
     
      if(this.linePlot){
        this.linePlot.changeData(data);
        return;
      }

      this.linePlot = new StackedArea(document.getElementById(this.props.chartId+"_line_div"), {
        title: {
          visible: false,
          text: '',
        },
        data,
        areaStyle:{
          opacity:0.2

        },
       
        line:{
          style: {
            cursor:'pointer',
        }
        },
        point:{
          visible: true,
          shape: 'circle',
          size: 4,
          style: {
              stroke: '#fff',
              cursor:'pointer',
          }
        },
        xField: 'periodTime',
        yField: 'value',
        stackField: 'type',
        color: ['#6897a7',  '#fedca9'],
        legend: {
          visible: true,
          position: 'top-center',
        },
        responsive: true,
      });
      this.linePlot.render();
      this.bindEvent(); 
    }



    
  
  getData = async ( loadingOption) => {
    try {
      var url=this.props.url;
      var fieldName=this.props.fieldName;
      var metricId=this.props.metricId;
      var dayBefore=this.state.dayBefore;
      const result = await utils.ajax(
        requestFilter({
          url: url,
          ...loadingOption,
          method: 'post',
          data: {
            operId:'getData'+Date.now(),
            fieldName:fieldName,
            dayBefore,
            metricId,
          },
          loading: true,
          errorPop: true,
          errorAutoClose: false
        })
      );

      if (result.status == 'success') {
        const jsonResult = JSON.parse(result.data);
        this.setState({
          data:jsonResult.items
        });
        
      }
    } catch (e) {}
  };


  showDeploy=(data)=>{

      var detailsArray;
      var cfg={
        title: {
          visible: true,
          // text: this.props.deployTitle+"("+data.time+")",
          text: this.props.deployTitle,
        },
        forceFit: true,
        data:data.items,
        padding: 'auto',
        xField: 'type',
        yField: 'value',
        meta: {
          title: {
            alias: this.props.deployNameTitle,
          },
          value: {
            alias: this.props.deployValueTitle,
          },
        },
      };

      if(this.deployDetail){
        // this.deployDetail.updateConfig(cfg);
        // this.deployDetail.render();
        this.deployDetail.changeData(data.items);
        return;
      }
      
      this.deployDetail = new Column(document.getElementById(this.props.chartId+'_deploy_detail_div'),cfg );
      this.deployDetail.render();
  }


  getDeployData = async ( loadingOption) => {
    try {
      var url=this.props.deployUrl;
      var typeField=this.props.typeField;
      var metricId=this.props.deployMetricId;
      var valueField=this.props.valueField;
      var deployDate = this.state.deployDate;
      var dayBefore=this.state.dayBefore;
      var type=this.state.type;
      const result = await utils.ajax(
        requestFilter({
          url: url,
          ...loadingOption,
          method: 'post',
          data: {
            operId:'getDeployData'+Date.now(),
            dayBefore,
            typeField,
            type,
            deployDate,
            valueField,
            metricId,
          },
          loading: true,
          errorPop: true,
          errorAutoClose: false
        })
      );

      if (result.status == 'success') {
        const jsonResult = JSON.parse(result.data);
        this.showDeploy(jsonResult);

        
      }
    } catch (e) {
      console.error(e);
    }
  };


  changeDeployData=async (pointData)=>{
    // var detailsArray=[];
    // for(var i=0;i<Math.random()*100%100;i++){
    //   detailsArray.push({"title":"Eeception "+i,"value":(Math.random()*100%40)});
    // }

    // if(this.deployDetail){
    //   this.deployDetail.changeData(detailsArray);
    //   return;
    // }
    await this.setState({
      type:pointData.type,
      deployDate:pointData.periodTime
    });

    this.getDeployData();
  }

    bindEvent=()=>{
      this.stateManager = new StateManager();
    
      this.linePlot.bindStateManager(this.stateManager, {
        setState: [
          {
            event: 'point:click',
            state: (e) => {
              const origin = e.target.get('origin').data;
              this.changeDeployData(origin);
              const state = { name: 'type', exp: origin.type };
              return state;
            },
          }
        ],  

        
        
      })
    }


    render(){
       
        return ( 
                <div>
                  <div style={{display: 'flex'}}>
                    <div id={this.props.chartId+'_line_div'} style={{ width: "50%",height:500 }}></div>
                    <div id={this.props.chartId+'_deploy_detail_div'} style={{ width: "50%" ,height:500}}></div>
                </div>             
               </div>
             
                              );

    }
}

export default LineDeploy;

**Comment by pine-zhao** [comment]
已经解决，多谢
