### ISSUE TITLE
grid`s style no working from xAxis and yAxis

### ISSUE THREAD

**Issue by meitingshuoguo** [antvis/G2Plot#836]
I modified the [example](https://g2plot.antv.vision/zh/examples/general/axis#axis-style) on your official website and found grid`s style no working

Please tell me how should i modify grid`s style

**Comment by meitingshuoguo** [comment]
咋没人回答我这个问题呢，在官网的例子里尝试修改grid的样式，根本不生效啊，这个是怎么回事呢

**Comment by paleface001** [comment]
忘记回复了不好意思😂

```
xAxis:{
   grid:{
       line:{
        style:{ }
       }
    }
}
```

**Comment by meitingshuoguo** [comment]
哈哈，啊原来是要写在line里面的style才生效，那你们的例子和文档说明是不是也要改一下，不然真的是有点误解，我看文档里也写的是
>网格线
>- visible: boolean 是否可见
>- style：object 网格线样式

**Comment by paleface001** [comment]
> 哈哈，啊原来是要写在line里面的style才生效，那你们的例子和文档说明是不是也要改一下，不然真的是有点误解，我看文档里也写的是
> 
> > 网格线
> > 
> > * visible: boolean 是否可见
> > * style：object 网格线样式

嗯嗯，更新一下文档~

**Comment by caihai123** [comment]
为什么我将网格线宽度设置成1了感觉还是很粗啊 是不是有阴影什么的
