### ISSUE TITLE
在多线图中，当一条线的数据只有一个点时，图表中没有展示出来。漏掉了字段2的展示

### ISSUE THREAD

**Issue by xiaoweb** [antvis/G2Plot#845]
这是样例：https://codesandbox.io/s/zen-cherry-g0hhq

这里有4条数据，分别是字段1在3月23-3月25 有数据，字段2在3月25有数据， 当鼠标放在3月25日期时，提示数据应该展示字段1人数3，字段2人数5， 但是实际展示漏掉了字段2的人数5
![image](https://user-images.githubusercontent.com/3126352/77515717-0416e780-6eb4-11ea-92fb-d332e00d58e7.png)

**Comment by paleface001** [comment]
第二条折线只有一个数据点，折线图形无法绘制出来(>=两个点才能构成折线），所以在tooltip里面没有体现

**Comment by xiaoweb** [comment]
但此时需要显示对比数据的，有什么办法绘制出点吗？

**Comment by xiaoweb** [comment]
> 第二条折线只有一个数据点，折线图形无法绘制出来(>=两个点才能构成折线），所以在tooltip里面没有体现


但此时需要显示对比数据的，有什么办法绘制出点吗？

**Comment by afc163** [comment]
我感觉可以展示，单点可以视为零宽折线。

**Comment by paleface001** [comment]
> 我感觉可以展示，单点可以视为零宽折线。

@xiaoweb 可以尝试一下解解看，提个mr~~
