### ISSUE TITLE
刻度线虚线怎么配置

### ISSUE THREAD

**Issue by qyongkang** [antvis/G2Plot#852]
![image](https://user-images.githubusercontent.com/27326200/77609144-2bc08b00-6f5a-11ea-8a3a-050f75f26241.png)

**Comment by qyongkang** [comment]
虚线怎么配置

**Comment by paleface001** [comment]
```
yAxis:{
    grid:{
      line:{
        style:{
        lineDash:[2,2]
      }
      }
    }
  }
```

绘图属性文档： https://g2plot.antv.vision/zh/docs/manual/graphic-style
