### ISSUE TITLE
图表演示名称国际化

### ISSUE THREAD

**Issue by afc163** [antvis/G2Plot#858]
https://g2plot.antv.vision/en/examples/gallery

现在都是中文。

**Comment by paleface001** [comment]
同一份demo文件和配置文件有办法完成国际化吗？
配置文件：https://github.com/antvis/G2Plot/blob/master/examples/bubble/basic/demo/meta.json#L9

写在demo里的：
https://github.com/antvis/G2Plot/blob/master/examples/bar/basic/demo/basic.js#L15

**Comment by afc163** [comment]
https://github.com/antvis/gatsby-theme-antv/blob/b7d308b95a8fb418ac811613722380147d8e80b3/example/examples/basic/demo/meta.json#L9-L12

**Comment by paleface001** [comment]
👌~
