### ISSUE TITLE
蜘蛛图bug

### ISSUE THREAD

**Issue by Leannechn** [antvis/g2plot#86]
![image](https://user-images.githubusercontent.com/6812138/65825729-00135f80-e2ad-11e9-8410-71d2ea79267f.png)

label 布局失效

spider 的label，返回的值和inner outer的不一致
![image](https://user-images.githubusercontent.com/6812138/65825741-318c2b00-e2ad-11e9-9c55-5497d249be3b.png)

**Comment by paleface001** [comment]
fixed in #84
