### ISSUE TITLE
Please add support for Organization chart

### ISSUE THREAD

**Issue by NaveenDA** [antvis/G2Plot#860]
Examples 
1.  https://www.fusioncharts.com/charts/drag-node-charts/org-chart-visualization?framework=javascript
2. https://unicef.github.io/react-org-chart/

**Comment by paleface001** [comment]
rogger. Or you can try [G6](https://github.com/antvis/G6) which is a professional graph visualization framework for now.

**Comment by NaveenDA** [comment]
@paleface001  thanks, I looking into create a wrapper for org diagram for to ease the process
 and closing this issue now.
