### ISSUE TITLE
请问如何让饼图按当前显示的图例计算百分比？

### ISSUE THREAD

**Issue by yuanyayi** [antvis/G2Plot#863]
需求是，在取消部分图例显示时，label中的百分比要按剩余显示的图例显示。
[这是一个从G2跟过来的问题](https://github.com/antvis/G2/issues/855)，G2那边当时回复说会在下一版更新，但之后我也没找到相关文档。请问下在这边如何配置？

**Comment by paleface001** [comment]
不好意思，忘记回复了。使用label的formatter，在formatter入参中已经提供了计算好的百分比，直接使用即可。
```
label: {
    visible: true,
    formatter:(text,data,index)=>{
      const value = (data.percent * 100).toFixed(1);
      return `${value}%`;
    }
  },
```
<img width="437" alt="屏幕快照 2020-04-22 下午7 50 40" src="https://user-images.githubusercontent.com/5888974/79978485-940b7980-84d2-11ea-8f80-dacfd93c5030.png">
