### ISSUE TITLE
柱状图缩略图移动滚动轴数字错位

### ISSUE THREAD

**Issue by 1597531463** [antvis/G2Plot#865]

**Comment by paleface001** [comment]
请提供复现demo

**Comment by 1597531463** [comment]
[
![76FB47E8-F71B-43c0-8C8E-A230ADAA852E](https://user-images.githubusercontent.com/42985792/78120770-14dbd600-743d-11ea-89ca-fc87e429a679.png)
](url)

**Comment by zqlu** [comment]
这个最新版应该没问题的？ https://g2plot.antv.vision/zh/examples/column/basic#column-slider

**Comment by paleface001** [comment]
是的，这个issue可以关闭了。
