### ISSUE TITLE
演示英文名大小写

### ISSUE THREAD

**Issue by afc163** [antvis/G2Plot#879]
<img width="958" alt="屏幕快照 2020-03-31 下午5 50 31" src="https://user-images.githubusercontent.com/5888974/78013654-5e62ed00-7379-11ea-8ef1-f87c49bbfff4.png">

统一一下写法，现在比较混乱。

**Comment by paleface001** [comment]
啥写法？大小写？

**Comment by afc163** [comment]
首字母大小写统一。

**Comment by afc163** [comment]
<img width="910" alt="image" src="https://user-images.githubusercontent.com/507615/78976485-d636d180-7b48-11ea-82c1-0b7b68374df8.png">

没统一呀。

**Comment by paleface001** [comment]
应该是还没更新网站，另外首字母大写还没有改呢

**Comment by afc163** [comment]
开着等开完。

**Comment by paleface001** [comment]
> 开着等开完。

👌
