### ISSUE TITLE
legend设置项中使用marker设置其他（例如：“circle”）图例，图会消失？

### ISSUE THREAD

**Issue by JXCartland** [antvis/G2Plot#882]
设置circle图消失
![image](https://user-images.githubusercontent.com/29434335/78208364-cda22380-74d6-11ea-897b-c9a2c34994c9.png)
![image](https://user-images.githubusercontent.com/29434335/78208620-6769d080-74d7-11ea-9eb9-a577fd9389d7.png)
未设置circle
![image](https://user-images.githubusercontent.com/29434335/78209056-9af92a80-74d8-11ea-8ffe-92c66b6b7880.png)
![image](https://user-images.githubusercontent.com/29434335/78208439-03470c80-74d7-11ea-97be-6c6fc581d62e.png)
API介绍
![image](https://user-images.githubusercontent.com/29434335/78208525-2d98ca00-74d7-11ea-9e31-2b5a7e7b0361.png)

**Comment by paleface001** [comment]
不好意思，是我们没有即时更新文档
```
legend:{
  marker:{
    symbol:'circle',
    style:{
       r: 5, // 配置legend marker的大小
       fill: '#000000' // 配置legend marker的颜色
    }
 }
}
```
