### ISSUE TITLE
报错：扩展接口类型不兼容

### ISSUE THREAD

**Issue by jetango** [antvis/G2Plot#884]
版本： 1.0.3

**问题：构建上线的时候会报一个类型兼容错误。如下图。**

![image](https://user-images.githubusercontent.com/3116660/78242289-555a5300-7514-11ea-8e15-a8e4768736ac.png)

**排查定位如下两个原因：**

原因1:  offset的兼容问题
caseA： offset?: string | number;
caseB:    offset?: number;

![image](https://user-images.githubusercontent.com/3116660/78242790-3b6d4000-7515-11ea-963b-c84ac78e99ce.png)

原因2:  format的兼容问题

caseA:   formatter?: (text: string, item: any, idx: number) => string;
caseB:   formatter?: (text: string | number | undefined | null, item: any, idx: number, ...extras: any[]) => string;

![image](https://user-images.githubusercontent.com/3116660/78243172-de25be80-7515-11ea-8941-2e34db802692.png)

**Comment by UgineHuang** [comment]
我也遇到这样的问题了，代码中不初始化图表组件，只引入包，运行就给报错了。版本为1.0.2，也存在这个错误，1.0.3的版本还多了个formatter的错误😵

**Comment by paleface001** [comment]
好的， 这个问题我跟进一下，尽快发个包

**Comment by Leopoldthecoder** [comment]
#912 应该也是同样的问题。请问有发版计划吗？

**Comment by paleface001** [comment]
不好意思，这周发版
