### ISSUE TITLE
G2Plot的字体是否将支持适配屏幕分辨率（主要是大屏）

### ISSUE THREAD

**Issue by wanjiaHuang** [antvis/G2Plot#887]
目前在使用G2Plot做大屏数据可视化的过程中，发现图表中有一些使用canvas来绘制的字体无法适应屏幕分辨率（会变得超级小，估计是因为使用canvas绘制字体的过程中使用的单位是‘px’）

**Comment by paleface001** [comment]
试一下设置pixelRatio:
https://g2plot.antv.vision/zh/docs/manual/plots/line/#pixelratio
