### ISSUE TITLE
小屏幕下首页样式问题

### ISSUE THREAD

**Issue by afc163** [antvis/G2Plot#888]
<img width="562" alt="image" src="https://user-images.githubusercontent.com/507615/78350113-3b357900-75d7-11ea-8f4c-c3c0155315b0.png">

<img width="915" alt="image" src="https://user-images.githubusercontent.com/507615/78350131-412b5a00-75d7-11ea-8808-486bb43279ac.png">

**Comment by paleface001** [comment]
还真是。这都能发现！一排大拇指~~

**Comment by hustcc** [comment]
同理，目前的网站依然存在：

![image](https://user-images.githubusercontent.com/7856674/95546658-c2a2ef80-0a33-11eb-973c-f8be070b3bfc.png)
