### ISSUE TITLE
theme 配置指的是什么？

### ISSUE THREAD

**Issue by xiaohuoni** [antvis/G2Plot#897]
https://g2plot.antv.vision/zh/docs/manual/plots/line/#theme

**Comment by afc163** [comment]
应该是文档遗漏了。

**Comment by paleface001** [comment]
后两周会根据双端适配需求进行大重构，到时候再补文档

**Comment by afc163** [comment]
开着吧，到时候对着查缺补漏。

**Comment by Me-Momo** [comment]
1.x 不再迭代；迁移至 2.x 的话，可以看下 2.x 的[主题配置](https://g2plot.antv.vision/en/examples/general/theme/API)
