### ISSUE TITLE
LineChart attribute "connectNulls:false" 没有发挥作用

### ISSUE THREAD

**Issue by geoffreylzf** [antvis/G2Plot#898]
我用以下 list 作为 data, 
"date" 是 Xaxis
"house_no" 是 Yaxis
"qty" 是Series

我以为线会在 2020-03-22 中断因为没有资料, 但是线还是从 2020-03-21 接到2020-03-23.

请问要怎么做才能让线中断，请指教
```
[{
            "date": "2020-03-20",
            "house_no": "H-01",
            "qty": 113.0,
            "age": 1.0
        },
        {
            "date": "2020-03-21",
            "house_no": "H-01",
            "qty": 92.0,
            "age": 2.0
        },
        {
            "date": "2020-03-23",
            "house_no": "H-01",
            "qty": 53.0,
            "age": 3.0
        },
        {
            "date": "2020-03-24",
            "house_no": "H-01",
            "qty": 48.0,
            "age": 4.0
        }]
```

**Comment by paleface001** [comment]
```
[{
            "date": "2020-03-20",
            "house_no": "H-01",
            "qty": 113.0,
            "age": 1.0
        },
        {
            "date": "2020-03-21",
            "house_no": "H-01",
            "qty": 92.0,
            "age": 2.0
        },
        {
            "date": "2020-03-22",
            "house_no": "H-01",
            "qty": 92.0,
            "age": null
        },
        {
            "date": "2020-03-23",
            "house_no": "H-01",
            "qty": 53.0,
            "age": 3.0
        },
        {
            "date": "2020-03-24",
            "house_no": "H-01",
            "qty": 48.0,
            "age": 4.0
        }];
```
在数据集对应日期补齐数据，y轴数据如果没有的话设为null即可

还有你的字段类型指定的好像不对，yField对应连续字段，应该对应qty或者age。seriesField对应一个分类字段，会根据指定字段对数据进行分组，显示为多条折线，因此单折线无需指定seriesField。

**Comment by martinezjose** [comment]
Hello,

We have a use-case where we are dealing with timestamped data with second resolution on this chart; having to add nulls for all the categories we are showing does not seem like a feasible solution for us. Would it be possible to assume nulls if data is not present? I know this is dealing with continuous data, so the solution will probably be a bit complex; one way I could think of is having to pass a `dataInterval` or such to the axis config; if data is not present from one point to the next one and their difference is greater than the interval, it might be possible to skip drawing the line connecting those two points.
