### ISSUE TITLE
关于类型定义命名的问题

### ISSUE THREAD

**Issue by xiaohuoni** [antvis/G2Plot#899]
有的命名前面不加`I`
https://github.com/antvis/G2Plot/blob/4e1f5629982e6e446981df694b07a8424c0f9b9e/src/interface/config.ts#L12
有的命名前面加`I`
https://github.com/antvis/G2Plot/blob/4e1f5629982e6e446981df694b07a8424c0f9b9e/src/interface/config.ts#L19
有的后面加`Config`
https://github.com/antvis/G2Plot/blob/4e1f5629982e6e446981df694b07a8424c0f9b9e/src/interface/config.ts#L261
有的不加 `Config`
https://github.com/antvis/G2Plot/blob/4e1f5629982e6e446981df694b07a8424c0f9b9e/src/interface/config.ts#L165

两套紫米煎饼，一套煎饼不放葱，一套煎饼只放葱。

五套绿豆煎饼，两套加啥也不加辣，一套加辣啥也不加，剩下的啥啥也不加，五个茶叶蛋，两个笨鸡蛋，三个鹌鹑蛋，五个荷包蛋，荷包蛋两个单面煎，三个双面煎，单面煎的放酱油，双面煎的放辣椒酱。

剩下还要点原味豆浆，三杯热乎地，两杯凉嗖地，一杯温暾的一杯温暾地再有一杯温暾地，三杯黑豆豆浆，一杯加冰不加糖，一杯加糖不加冰，一杯加冰又加糖，所有原味豆浆都要大杯的，所有黑豆豆浆都要小杯的，所有加冰的都要中杯的。

**Comment by RaoHai** [comment]
配一个 eslint 就行了。。

**Comment by xiaohuoni** [comment]
> 配一个 eslint 就行了。。

不好意思，不太懂你的意思。

**Comment by hustcc** [comment]
请看 v2 的代码，今天刚到 master，欢迎挑问题！
