### ISSUE TITLE
为什么chart.getPlotTheme() 不返回 guideLine？

### ISSUE THREAD

**Issue by xiaohuoni** [antvis/G2Plot#900]
![image](https://user-images.githubusercontent.com/11746742/78653843-4c8fc580-78f6-11ea-8b67-78a306115460.png)

我有个场景，需要获取当前的辅助线信息，来判断，是否再配置 guideLine。
如果 getPlotTheme 取不到，那我需要怎么取？

**Comment by paleface001** [comment]
没懂，guideline是你自主决定配置不配置的，没配置guideline怎么拿到当前的辅助线信息呢？

**Comment by xiaohuoni** [comment]
是有配置了一条，但是获取的时候，没有这个对象。

**Comment by paleface001** [comment]
没get到，麻烦提供复现demo

**Comment by xiaohuoni** [comment]
复现demo： https://codesandbox.io/s/nifty-turing-s3mrd?file=/index.js
看控制台，打印的数据没有 guideline。

**Comment by xiaohuoni** [comment]
@paleface001 cc

**Comment by paleface001** [comment]
guideline目前没有在theme里配，这是个问题。下个月我们会重新整理一份theme机制
