### ISSUE TITLE
折线图，如何使用多折线？

### ISSUE THREAD

**Issue by xiaohuoni** [antvis/G2Plot#901]
legend 配置 
功能描述：图例，多折线时显示，用于展示颜色分类信息

文档里面没找到怎么使用多折线。

**Comment by paleface001** [comment]
https://g2plot.antv.vision/zh/examples/line/multiple
https://g2plot.antv.vision/zh/docs/manual/plots/line/#seriesfield-
文档和demo里都有，多看看再提issue

**Comment by xiaohuoni** [comment]
只看使用文档的话，找不到。感觉要补充
