### ISSUE TITLE
请问关系树图什么时间发布？

### ISSUE THREAD

**Issue by rookie-luochao** [antvis/G2Plot#904]
为啥都是基于g2引擎，阿里开源了bizcharts，还要开源g2plot，bizcharts明显图表更多，从表像上来看，bizcharts更加react组件化一点，g2plot趋向于不区分框架试用，请问真正开发g2plot的动机是什么呢？

**Comment by paleface001** [comment]
g2 = 可视化引擎，bizcharts其实不是对标g2plot，而是对标g2，可以理解为g2的一种react封装。g2plot = 图表库

**Comment by rookie-luochao** [comment]
@paleface001 我觉得大佬您好像没有看清楚我的描述

**Comment by paleface001** [comment]
我感觉说的比较清楚了呀？os: 关系树图推荐使用G6

**Comment by rookie-luochao** [comment]
好的，谢谢

**Comment by paleface001** [comment]
好滴，那这个issue我就先close了
