### ISSUE TITLE
Donut 里有些属性好像还没效果，如统计值格式化显示，标题位置？

### ISSUE THREAD

**Issue by mhsnet** [antvis/G2Plot#907]
Donut 里有些属性好像还没效果，如统计值格式化？和文档Ring属性命名不一致，Ring好像不建议用，文档还没更新

**Comment by paleface001** [comment]
现在文档里是Donut了呀：https://antv-g2plot.gitee.io/zh/docs/manual/plots/donut

**Comment by mhsnet** [comment]
但里面的代码还是引入Ring,title中还是position,donut好像是alignTo，但没效果

**Comment by paleface001** [comment]
title应该是改出bug了，我们修复一下

**Comment by paleface001** [comment]
fixed in #956
