### ISSUE TITLE
Column is not defined

### ISSUE THREAD

**Issue by MrTager** [antvis/G2Plot#909]
引入 <script src="js/g2plot.js"></script>
使用 const columnPlot = new Column(document.getElementById('c1'),{......
报错：Uncaught ReferenceError: Column is not defined
请问我是哪里出问题了

**Comment by zqlu** [comment]
`new G2Plot.Column`

参见文档：https://g2plot.antv.vision/zh/docs/manual/getting-started

```
<!-- 引入在线资源 -->
<script src="https://unpkg.com/@antv/g2plot@latest/dist/g2plot.js"></script>
<script>
  const plot = new G2Plot.Line(document.getElementById('app'), {
    // ...
  });
  plot.render();
</script>
```
