### ISSUE TITLE
error: Type 'T' does not satisfy the constraint 'ViewLayerConfig'

### ISSUE THREAD

**Issue by AliceYangqian** [antvis/G2Plot#912]
![image](https://user-images.githubusercontent.com/23236491/78984504-f5d5f600-7b58-11ea-8327-6ff083f23f1b.png)

Angular version: 9.1.0

Browser: [all]

Language: TypeScript 3.8.3

**Comment by AliceYangqian** [comment]
感谢您的更新，现在通过 npm 安装完成未进行任何引用，项目启动正常。但是 当我加入 `import { Line } from '@antv/g2plot';` 准备创建第一个图表时，终端抛出了同样的错误信息。

**Comment by zqlu** [comment]
新版本应该已经修复
