### ISSUE TITLE
希望完善文档。

### ISSUE THREAD

**Issue by makyo5** [antvis/G2Plot#913]
虽然我知道你们很忙，事情很多，但是作为有点菜的使用者，还是希望你们能尽快完善文档。
之前我用的是G2,这次尝鲜用plot。发现plot里面的文档太简单了，每个方法属性都是一段话就完了。点个demo，都是404.
其实，之前G2的文档，也是差不多。。。也是一两段话就完了。反正demo代码少。。。。我是去年看的。

**Comment by paleface001** [comment]
好的，链接404问题会尽快解决，顺便问一下你期待的文档形式是什么样的？能不能试着描述一下？

**Comment by makyo5** [comment]
> 好的，链接404问题会尽快解决，顺便问一下你期待的文档形式是什么样的？能不能试着描述一下？

各有各的特色吧。不过说句老实话，echarts的文档做的挺好的（参看：https://www.echartsjs.com/zh/option.html#title），既有一段话的解释，也有示例代码做说明（目前G2部分方法也有，可能是因为文档还不够完善的缘故。）（参看：https://www.echartsjs.com/zh/option.html#xAxis.nameTextStyle.rich）。

我所在的几个群，偶尔能听到群友说，因为echarts的文档做的好，所以他们一直在使用echarts。

我是觉得G2配色好，在chart的option上，也比较符合个人使用习惯，所以一直坚持在用G2。

还是说一下自己期待的文档形式（我是搞后端的，不过因为项目问题，做了两年的前端了，所以可能前端基础不是很好）就以自己的愚见说说：
DEMO：这个已经有了。挺好。
快速上手：还行，不过内容挺简单。生成一个快速图表够用，稍微改一下设置，可能就不够用。那，我就需要看demo，或者api了。
api：G2还是英文，感觉有点像summary，可能还在完善中吧。api看得一头雾水。（echarts单独把配置项拿出来做成一个标签，确实很有用。因为用这个charts的可能有很多是新手，光看api，确实没多大用。非熟练水平的，可能接触最多的就是这个setOption，参看：https://www.echartsjs.com/zh/option.html#title ），随意点一个option的属性，也有相应解释和实例，作为一个非熟手，能够照样子套自己的代码，并且根据解释，也懂得了每个选项中的具体的作用（参看：https://www.echartsjs.com/zh/option.html#series-line.data）


我知道要达到echats的文档，需要很多功夫，不过，看到你能这样回复，我已经对antv的文档感到很有信心了。感谢回复。

**Comment by makyo5** [comment]
还有个关于复用组件的问题。。。。
我不知道该怎么说。。。有一个只有一个视频

`<div class="row">
        <div class="col-sm-6" >      
          <MyChart :propData="chartData1" chartType="Line" chartTitle="今年风险" />
        </div>
        <div class="col-sm-6">
          <MyChart :propData="chartData2" chartType="Line" chartTitle="去年风险" />
        </div>
      </div>
`
MyChart基本是按照快速写的。
但是，在浏览网页的时候，图标会一直拉伸变高高高高。。。。。然后，图表就崩了。。。。
在linechart.render()处打一个断点，然后“继续”。就不会一直高高高。
用G2不会。G2plot会。

**Comment by paleface001** [comment]
> > 好的，链接404问题会尽快解决，顺便问一下你期待的文档形式是什么样的？能不能试着描述一下？
> 
> 各有各的特色吧。不过说句老实话，echarts的文档做的挺好的（参看：https://www.echartsjs.com/zh/option.html#title ）。
> 既有一段话的解释，也有示例代码做说明，目前G2部分方法也有，可能是因为文档还不够完善的缘故。（参看：https://www.echartsjs.com/zh/option.html#xAxis.nameTextStyle.rich ）。
> 
> 我所在的几个群，偶尔能听到群友说，因为echarts的文档做的好，所以他们一直在使用echarts。
> 
> 我是觉得G2配色好，在chart的option上，也比较符合个人使用习惯，所以一直坚持在用G2。
> 
> 还是说一下自己期待的文档形式（我是搞后端的，不过因为项目问题，做了两年的前端了，所以可能前端基础不是很好）就以自己的愚见说说：
> DEMO：这个已经有了。挺好。
> 快速上手：还行，不过内容挺简单。生成一个快速图表够用，稍微改一下设置，可能就不够用。那，我就需要看demo，或者api了。
> api：G2还是英文，感觉有点像summary，可能还在完善中吧。api看得一头雾水。（echarts单独把配置项拿出来做成一个标签，确实很有用。因为用这个charts的可能有很多是新手，光看api，确实没多大用。非熟练水平的，可能接触最多的就是这个setOption，参看：https://www.echartsjs.com/zh/option.html#title ），随意点一个option的属性，也有相应解释和实例，作为一个非熟手，能够照样子套自己的代码，并且根据解释，也懂得了每个选项中的具体的作用（参看：https://www.echartsjs.com/zh/option.html#series-line.data ）
> 
> 我知道要达到echats的文档，需要很多功夫，不过，看到你能这样回复，我已经对antv的文档感到很有信心了。感谢回复。

https://g2plot.antv.vision/zh/docs/manual/plots/line/#color  目前看g2plot的文档是以类似的方式组织的呀？你说的是g2的文档？

**Comment by makyo5** [comment]
> > > 好的，链接404问题会尽快解决，顺便问一下你期待的文档形式是什么样的？能不能试着描述一下？
> > 
> > 
> > 各有各的特色吧。不过说句老实话，echarts的文档做的挺好的（参看：https://www.echartsjs.com/zh/option.html#title ）。
> > 既有一段话的解释，也有示例代码做说明，目前G2部分方法也有，可能是因为文档还不够完善的缘故。（参看：https://www.echartsjs.com/zh/option.html#xAxis.nameTextStyle.rich ）。
> > 我所在的几个群，偶尔能听到群友说，因为echarts的文档做的好，所以他们一直在使用echarts。
> > 我是觉得G2配色好，在chart的option上，也比较符合个人使用习惯，所以一直坚持在用G2。
> > 还是说一下自己期待的文档形式（我是搞后端的，不过因为项目问题，做了两年的前端了，所以可能前端基础不是很好）就以自己的愚见说说：
> > DEMO：这个已经有了。挺好。
> > 快速上手：还行，不过内容挺简单。生成一个快速图表够用，稍微改一下设置，可能就不够用。那，我就需要看demo，或者api了。
> > api：G2还是英文，感觉有点像summary，可能还在完善中吧。api看得一头雾水。（echarts单独把配置项拿出来做成一个标签，确实很有用。因为用这个charts的可能有很多是新手，光看api，确实没多大用。非熟练水平的，可能接触最多的就是这个setOption，参看：https://www.echartsjs.com/zh/option.html#title ），随意点一个option的属性，也有相应解释和实例，作为一个非熟手，能够照样子套自己的代码，并且根据解释，也懂得了每个选项中的具体的作用（参看：https://www.echartsjs.com/zh/option.html#series-line.data ）
> > 我知道要达到echats的文档，需要很多功夫，不过，看到你能这样回复，我已经对antv的文档感到很有信心了。感谢回复。
> 
> https://g2plot.antv.vision/zh/docs/manual/plots/line/#color 目前看g2plot的文档是以类似的方式组织的呀？你说的是g2的文档？

没有别的意思，这次仅仅是提个希望完善文档的建议。
