### ISSUE TITLE
折线图有marker吗

### ISSUE THREAD

**Issue by cnyballk** [antvis/G2Plot#914]
我想在折线图的线上加marker标记，但是没找到配置

**Comment by paleface001** [comment]
demo: https://g2plot.antv.vision/zh/examples/gallery#category-%E6%A0%87%E6%B3%A8%E7%82%B9

文档：https://g2plot.antv.vision/zh/examples/line/marker/API

**Comment by cnyballk** [comment]
不好意思，怪我没说清楚，我说的是折线的面积图的
