### ISSUE TITLE
当值为负时，Bar的Label的位置 有误

### ISSUE THREAD

**Issue by lvlw** [antvis/G2Plot#916]
![image](https://user-images.githubusercontent.com/26396481/79182378-3c6d6e00-7e41-11ea-8284-dda048a2687d.png)
![image](https://user-images.githubusercontent.com/26396481/79182393-48f1c680-7e41-11ea-9f27-3a02ece44643.png)
![image](https://user-images.githubusercontent.com/26396481/79182420-54dd8880-7e41-11ea-8011-50683514fd16.png)

**Comment by zqlu** [comment]
已经修复，等待新版本发布。
