### ISSUE TITLE
当有负值的时候，Bar的Y轴能否支持在中间位置

### ISSUE THREAD

**Issue by lvlw** [antvis/G2Plot#917]
![image](https://user-images.githubusercontent.com/26396481/79183206-6a53b200-7e43-11ea-80ea-6e1345c17afa.png)

**Comment by paleface001** [comment]
关闭adjustPosition就可以了，这个配置项开启的时候，如果图形空间不够放下label，label的位置会自动调整。
```
label:{
    visible: true,
    position: 'middle',
    adjustPosition: false
}
```
