### ISSUE TITLE
如何格式化 tooltip 里面的内容

### ISSUE THREAD

**Issue by csnan** [antvis/G2Plot#919]
如果数据是
`{
    type: '家具家电',
    value: 38,
    aaa: 'aaa',
    bbb: 'bbb'
  },
  {
    type: '粮油副食',
    value: 52,
    aaa: 'aaa',
    bbb: 'bbb'
  }`

如何格式化 tooltip 里面 value 文本显示为 aaa + bbb + value
![tooltip](https://user-images.githubusercontent.com/47582074/79192352-21a7f300-7e5b-11ea-9b14-7c19b0903d03.jpg)

**Comment by paleface001** [comment]
tooltip formatter可以参考文档里的配置方式：https://g2plot.antv.vision/zh/docs/manual/plots/line/#tooltip
```
tooltip:{
    visible: true,
    fields:['value', 'aaa', 'bbb'],
    formatter:(v,a,b)=>{
        return a + b + v;
    }
}
