### ISSUE TITLE
tooltip 中的图例没有对齐

### ISSUE THREAD

**Issue by dengfuping** [antvis/G2Plot#926]
> 待提供重现链接

![image](https://user-images.githubusercontent.com/14918822/79311993-d5c77d80-7f30-11ea-88b6-253d82644487.png)

**Comment by csnan** [comment]
请问你怎么弄的显示多个字段的数据呀？

**Comment by dengfuping** [comment]
- 业务自身问题，与 G2Plot 无关。

**Comment by potatozerg** [comment]
@dengfuping How did you fix it? I have the exact same problem. On the G2Plot website, with no tooltip configuration, it works well. I tried to use domStyles to fix it. But when the number has different lengths, the colon's position can't be set.
As you can see, 103 is shorter than 69.97, so the colon's positioning is not working well.
`domStyles: {
    'g2-tooltip-marker': { float: 'left' },
    'g2-tooltip-name': { float: 'left' }
}`
![image](https://user-images.githubusercontent.com/3282773/112543573-553e0d80-8d8c-11eb-90de-c2ebb4fb8444.png)

All multi-dimension charts have this problem.
My Chinese input is broken on Ubuntu, you can reply in Chinese.

**Comment by potatozerg** [comment]
Fixed:
`domStyles: { 'g2-tooltip': { 'text-align': 'left' } }`
