### ISSUE TITLE
关于事件交互

### ISSUE THREAD

**Issue by phoema** [antvis/G2Plot#931]
请问G2plot以后会支持BizCharts那样的图表事件吗？
是否有大致的时间表?
如点击事件，以便钻取或查看明细数据

**Comment by paleface001** [comment]
已经支持事件了，详细可以参考每个图表的文档：https://g2plot.antv.vision/zh/docs/manual/plots/line/#%E4%BA%8B%E4%BB%B6

使用方法：
```
const line = new Line(container,{
   events:{
      onLineClick:(ev)=>{}, //折线点击事件
      onPointClick:(ev)=>{} //数据点点击事件
   }
});
```

**Comment by phoema** [comment]
找到了，谢谢。
