### ISSUE TITLE
 ERROR:/@antv/component/lib/tooltip/css-const"' has no default export.

### ISSUE THREAD

**Issue by betgo** [antvis/G2Plot#954]
"typescript": "~3.5.3"
  "@angular/core": "~8.2.11"
   "@antv/g2plot": "^1.0.3",
![C6~EF9HQC5LU(L5Q)NPI6HS](https://user-images.githubusercontent.com/23697638/79840609-b6c16380-83e8-11ea-953f-e62ab433f494.png)

**Comment by coloz** [comment]
the same issue

**Comment by zhangzhonghe** [comment]
I got the same error!
![截图](https://user-images.githubusercontent.com/38434641/81030445-6a335900-8ebb-11ea-8271-71953030f6dd.png)
![截图_](https://user-images.githubusercontent.com/38434641/81030548-c5654b80-8ebb-11ea-9828-6a87ab7faf0a.png)

**Comment by zqlu** [comment]
已合并
