### ISSUE TITLE
环形图（Donut）设置了tooltip但不显示

### ISSUE THREAD

**Issue by kiinlam** [antvis/G2Plot#959]
环形图（Donut）是不支持tooltip吗？

我看代码演示里也没有展示出tooltip的功能：
https://antv-g2plot.gitee.io/zh/examples/pie/donut

如下图，鼠标移到了右上方的扇形上，啥也没发生

![图片](https://user-images.githubusercontent.com/5861519/79935082-9b0c9a80-8486-11ea-9c4f-3bbe4da99613.png)

我在tooltip下设置了formatter方法，然后鼠标移到环形图上，也没有触发formatter方法。

**Comment by paleface001** [comment]
环图默认配置了指标卡(statistic）的情况下会替代tooltip的功能，使用tooltip需要将指标卡关闭：
```
{
  statistic:{
     visible: false
  }
}
```

**Comment by kiinlam** [comment]
问题解决了：
看了下我项目依赖里的版本号，用的是1.0.3版本，而github上releases里的最新版是1.0.4，22小时前更新的，于是我试着升级了版本，结果就可以了。
@paleface001 是不是偷偷更新了，顺便把bug修复了。

PS：提问里给的演示页面地址，在代码框里修改，设置`statistic`为`visible: false`，tooltip还是没有出现，但选择在sandbox打开，就能出现，sandbox里的package.json配置的是latest版本。估计演示页面还是存在问题的1.0.3版本。

**Comment by paleface001** [comment]
是的 在1.0.3版本中tooltip disable的判断条件有bug，在1.0.4中修复了。
主站已经更新了：https://g2plot.antv.vision/zh/examples/pie/donut#ring-basic
国内镜像我看看怎么回事
