### ISSUE TITLE
漏斗图在某项数据为0的时候，该层为什么没有显示出来？

### ISSUE THREAD

**Issue by cppypl** [antvis/G2Plot#961]
漏斗图在某项数据为0的时候，该层为什么没有显示出来？如何显示？文档是404。
并且数据为0的时候，转化率出现了NaN。

**Comment by paleface001** [comment]
数据为0当然就无法绘制出来了，你期待的显示结果是什么样的？

**Comment by cppypl** [comment]
> 数据为0当然就无法绘制出来了，你期待的显示结果是什么样的？

如果不显示的话，那就没有漏斗的形状了，比如初始化数据都是0，那就是空白了。所以我希望0的时候，该层也显示。

**Comment by paleface001** [comment]
初始化数据都是0的时候怎么能显示得出来漏斗呢......

**Comment by paleface001** [comment]
我理解你期待的效果是图形宽度为0，但标签和转化率组件正常显示？

**Comment by cppypl** [comment]
> 我理解你期待的效果是图形宽度为0，但标签和转化率组件正常显示？

嗯，我知道你们比较忙，先把转化率是NaN的问题解决还有文档404的问题解决。
不知道你们的转化率是不是通过除法得到的，但是0/0=NaN哦  
加油
