### ISSUE TITLE
目前使用g2plot不支持g2的limitInPlot属性

### ISSUE THREAD

**Issue by arcsin1** [antvis/G2Plot#962]
## 背景

-  在使用过程中发生y轴的值超过了y轴
![1587541268081_533E0D52-401B-44AE-AD12-D36BFF5DD538](https://user-images.githubusercontent.com/13724222/79955738-cbb5f980-84b1-11ea-93a2-4d929c925ba9.png)
![1587541243201_B9D40758-E115-482F-A471-AF16F6E8C451](https://user-images.githubusercontent.com/13724222/79955755-d1134400-84b1-11ea-9516-692587f07e21.png)

## 思路

- 建议支持类似g2的limitInPlot属性配置

**Comment by paleface001** [comment]
这个[demo](http://localhost:8000/zh/examples/general/axis/#axis-minmax)是因为设置的坐标轴max低于数据最高值，坐标轴min高于数据最低值。你是有什么场景用到这个功能吗？
g2的limitInPlot目前存在一些体验问题，我们会等打磨好之后再开放

**Comment by arcsin1** [comment]
但是，这个坐标轴 是自动计算出来的，就遇到了这种超出了，跟上面距离肯定会冲突。像echarts的图形绘制是不会超过y轴的（自动计算较好的y轴坐标轴是我们需要的） 谢谢

**Comment by paleface001** [comment]
自动计算会超出的话应该就是scale的问题了，能提供一下图表的数据和配置项吗？

**Comment by arcsin1** [comment]
官方实例就有问题的 比如：https://g2plot.antv.vision/zh/examples/line/basic#line-slider 和 https://g2plot.antv.vision/zh/examples/line/basic#line-point-style

**Comment by paleface001** [comment]
> 官方实例就有问题的 比如：https://g2plot.antv.vision/zh/examples/line/basic#line-slider 和 https://g2plot.antv.vision/zh/examples/line/basic#line-point-style

这种可以设置y轴的nice为true来解：

```
yAxis:{
   visible: true,
   nice: true
}
```

**Comment by arcsin1** [comment]
好吧 在线api文档居然没有这个属性 囧

**Comment by arcsin1** [comment]
建议 这个默认属性更友好 谢谢
