### ISSUE TITLE
Use log scale on yAxis of Line plot

### ISSUE THREAD

**Issue by EricCrosson** [antvis/G2Plot#968]
Hi -- this is a great project! Thanks for all the work and documentation to date.

Is there any way to use a log scale on the yAxis of a Line plot? This is essential for working with certain types of data

In `config.d.ts` it looks like `IValueAxis.type` can only be set to `'linear'` right now, I'll keep investigating

**Comment by paleface001** [comment]
Hi there -- the log yAxis can be used by setting the yAxis type to 'log'
```
yAxis:{
  type:'log'
}
```
<img width="656" alt="屏幕快照 2020-04-23 上午10 16 43" src="https://user-images.githubusercontent.com/5888974/80051775-965dea00-854b-11ea-9be3-36d26c9b267a.png">

And we'll fix the type error later.

**Comment by EricCrosson** [comment]
Lo and behold, it worked! Looks like I had to update from 1.0.3 to 1.0.4 to get the proper typings -- I downloaded the project one day too early :)

Cheers and happy hacking!

**Comment by jiahao1553** [comment]
I use the following in version 2, but it doesn't work. Is it a work in progress?
`yAxis:{
  type:'log'
}`

**Comment by hustcc** [comment]
> I use the following in version 2, but it doesn't work. Is it a work in progress?
> 
> `yAxis:{
> 
>   type:'log'
> 
> }`

You set the type in meta config. I will add the usage in next version.

Thanks for your feedback.
