### ISSUE TITLE
Customize a Bullet Chart tooltip (display names instead of indices)

### ISSUE THREAD

**Issue by YakimchykNadzeya** [antvis/G2Plot#969]
Is it possible to customize a tooltip of a Bullet Chart to display names instead of indices?

![image](https://user-images.githubusercontent.com/57988716/80013079-9a97f200-84ce-11ea-902f-be8102c71d62.png)

**Comment by paleface001** [comment]
the way of formatting tooltip content: 

```
tooltip:{
   fields:[], // the data fields you want display in tooltip,
   formatter:(...args)=>{
       return {
          name: xxx,
          value: xxx
       } //  the output value of tooltip data items
    }
}
```

**Comment by YakimchykNadzeya** [comment]
Thank you for your quick reply! Unfortunately, it still does not work. My goal is to name measures, so that a tooltip displays currencies ('CNY, 'TRY', 'RUB', 'EUR', ... ) instead of indices (0, 1, 2, 3, ...). 
Below is my piece of code. Could you please specify a tooltip formatter? Thanks a lot for your help!

` 
const config = {
                data: [
                    {
                        title: 'data',
                        measures: [5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 20],
                        targets: [160],
                        ranges: [0, 120 / 200, 140 / 200, 200 / 200],
                    },
                ],
                tooltip: {
                    visible: true,
                    fields: ['measures'],
                },

                rangeMax: 200,
                rangeColors: ['#B4EBBF', '#FFDBA2', '#FFB1AC'],
                title: {
                    visible: false,
                },
                legend: {
                    visible: false
                },
                description: {
                    visible: false,
                },
                label: {
                    visible: false,
                },
                height: 60,
                width: 320
            };


<ReactG2Plot
         Ctor={Bullet}
         config={config}
 />`
