### ISSUE TITLE
Blurry charts on Windows browsers

### ISSUE THREAD

**Issue by ginesete** [antvis/G2Plot#970]
In MS Windows 10, in ie11, edge, chrome and firefox, all updated to the latest versions, charts look blurry.

Check the examples at [the examples in the official page](https://g2plot.antv.vision/en/examples/line/basic#line,), where it can be seen that charts, and mostly ticks in axis, look very blurry.

**Comment by paleface001** [comment]
try to set the pixelRatio of chart manually

```
import { Line } from '@antv/g2plot';

const line = new Line(container,{
   pixelRatio: 2, // higher or lower value
});
line.render();
```

**Comment by ginesete** [comment]
Thanks, that solved it. A pixel ratio of 3 works fine for all screens
