### ISSUE TITLE
请考虑对column/bar 等图添加对{type:'timeCat'} (x轴/y轴配置）的支持。

### ISSUE THREAD

**Issue by OuyangQianba** [antvis/G2Plot#973]
因为processData 将xField指定的数据进行了toString操作，导致了后续的解析时间戳的操作失败，最终导致绘图失败。
![image](https://user-images.githubusercontent.com/17270099/80074482-cd4bf400-857b-11ea-9f1f-eac3043e91a2.png)

失败的错误：
![image](https://user-images.githubusercontent.com/17270099/80074977-91655e80-857c-11ea-93e8-6f4b734076ef.png)

如果对于type 为time 的情况不做toString才操作，就可以很方便的绘制x轴为时间的图了。
例如：
![image](https://user-images.githubusercontent.com/17270099/80074910-75fa5380-857c-11ea-9939-27ec75f45e47.png)

https://github.com/antvis/scale/issues/44

**Comment by paleface001** [comment]
柱状图按标准来说是不支持x轴绘制为连续数据的，连续数据的话建议用折线图表现

**Comment by OuyangQianba** [comment]
> 柱状图按标准来说是不支持x轴绘制为连续数据的，连续数据的话建议用折线图表现

那是能支持type: 'timeCat' 呢？

**Comment by paleface001** [comment]
> > 柱状图按标准来说是不支持x轴绘制为连续数据的，连续数据的话建议用折线图表现
> 
> 那是能支持type: 'timeCat' 呢？

timeCat是应该支持的，只是现在scale在这一块的表现还不够好，所以暂时还没有放出来。

**Comment by OuyangQianba** [comment]
> > > 柱状图按标准来说是不支持x轴绘制为连续数据的，连续数据的话建议用折线图表现
> > 
> > 
> > 那是能支持type: 'timeCat' 呢？
> 
> timeCat是应该支持的，只是现在scale在这一块的表现还不够好，所以暂时还没有放出来。

嗯，我试过timecat，如果数据里的日期是日期字符串，就可以，如果是时间戳就是上面的错误。
原因一样的，g2plot里把时间戳转为了字符串，而scale那边没有处理字符串表示的时间戳

**Comment by OuyangQianba** [comment]
更正一下，对于type为timeCat的情况，没有错误抛出，是静默的失败了。
