### ISSUE TITLE
饼图 & 环图相关bug

### ISSUE THREAD

**Issue by paleface001** [antvis/G2Plot#981]
- [x]  legend为false时padding错误

- [x] 环图spider label不显示

**Comment by jaredleechn** [comment]
还有一个 case 也非常痛，开启了 guideLine 的图表，如果 yAxis 和 xAxis 配置错误会 crash

**Comment by paleface001** [comment]
第一个问题复现不出来了，来个riddle吧~ @jaredleechn

**Comment by paleface001** [comment]
fixed via #987
