### ISSUE TITLE
折线图中， 辅助线最大值画的有问题

### ISSUE THREAD

**Issue by chenzhiwei199** [antvis/G2Plot#984]
![image](https://user-images.githubusercontent.com/20192061/80193868-1ec3b400-864c-11ea-9d09-b8c5d758ad36.png)

复现例子： https://codesandbox.io/s/ihi83?file=/index.js

**Comment by hustcc** [comment]
设置：

```ts
meta: {
  value: {
     nice: false, // 或者改成 false，忘记是哪个有这个问题。
  }
}
```
