### ISSUE TITLE
g2Plot 啥时候支持分面功能？ 

### ISSUE THREAD

**Issue by arcsin1** [antvis/G2Plot#994]
背景

- 目前遇到有分类的统计图，发现g2plot不支持分面分类作图

解决办法

- 能否支持g2类似的分面功能 

（ 总感觉g2plot的更新稍慢，加油）

**Comment by paleface001** [comment]
分面不是G2Plot今年的重点，今年G2Plot的重点是移动端和统计分析能力，如果比较急的话建议直接用G2

**Comment by arcsin1** [comment]
总感觉你们人手不够做这个库，不过看好你们做好这个；
有时间就来看看你们源码来贡献这个，谢谢。

**Comment by paleface001** [comment]
太棒啦，欢迎MR~

**Comment by arcsin1** [comment]
有个疑问 你们打算是把F2给替换掉吗

**Comment by paleface001** [comment]
F2是有自己的业务场景的，G2Plot做通用图表库也需要相应的移动端能力，这两个不冲突~
