### ISSUE TITLE
在react使用报错：Cannot read property 'offsetWidth' of null

### ISSUE THREAD

**Issue by explorefit** [antvis/G2Plot#997]
使用版本："@antv/g2plot": "^1.0.4",
使用官网的 快速使用的方法，就报错误：TypeError: Cannot read property 'offsetWidth' of null
![image](https://user-images.githubusercontent.com/24665389/80326581-dda9ea80-886b-11ea-92e3-481c139915e8.png)

**Comment by cxs1994** [comment]
刚好今天也遇到同样问题，可以使用mounted方法，在视图加载后渲染数据
`methods: {
        data() {
            const data = [
                { year: '1951 年', sales: 38 },
                { year: '1952 年', sales: 52 },
                { year: '1956 年', sales: 61 },
                { year: '1957 年', sales: 145 },
                { year: '1958 年', sales: 48 },
            ];
            const bar = new Bar(document.getElementById('container'), {
                data,
                xField: 'sales',
                yField: 'year',
                colorField: 'year',
            });
            bar.render();
        }
    },
    mounted() {
        this.data()
    },
`

**Comment by cxs1994** [comment]
刚好今天也遇到了同样问题，可以使用mounted的方法，在视图加载后，再加载渲染数据

**Comment by cxs1994** [comment]
`methods: {
        data() {
            const data = [
                { year: '1951 年', sales: 38 },
                { year: '1952 年', sales: 52 },
                { year: '1956 年', sales: 61 },
                { year: '1957 年', sales: 145 },
                { year: '1958 年', sales: 48 },
            ];
            const bar = new Bar(document.getElementById('container'), {
                data,
                xField: 'sales',
                yField: 'year',
                colorField: 'year',
            });
            bar.render();
        }
    },
    mounted() {
        this.data()
    },`

**Comment by cxs1994** [comment]
![1587981456(1)](https://user-images.githubusercontent.com/16110495/80359596-9d209000-88b0-11ea-86a4-a6dc17d0bd72.jpg)

**Comment by ChenxiiCheng** [comment]
渲染完才能拿到dom，代码放componentDidMount中或者用useEffect

**Comment by ChenxiiCheng** [comment]
> 使用版本："@antv/g2plot": "^1.0.4",
> 使用官网的 快速使用的方法，就报错误：TypeError: Cannot read property 'offsetWidth' of null
> ![image](https://user-images.githubusercontent.com/24665389/80326581-dda9ea80-886b-11ea-92e3-481c139915e8.png)

渲染完才能拿到dom，代码放componentDidMount中或者用useEffect

**Comment by paleface001** [comment]
> 使用版本："@antv/g2plot": "^1.0.4",
> 使用官网的 快速使用的方法，就报错误：TypeError: Cannot read property 'offsetWidth' of null
> ![image](https://user-images.githubusercontent.com/24665389/80326581-dda9ea80-886b-11ea-92e3-481c139915e8.png)

使用早期版本会出现这个问题吗？比如0.11.40、1.0.2

**Comment by lxfu** [comment]
> 使用版本："@antv/g2plot": "^1.0.4",
> 使用官网的 快速使用的方法，就报错误：TypeError: Cannot read property 'offsetWidth' of null
> ![image](https://user-images.githubusercontent.com/24665389/80326581-dda9ea80-886b-11ea-92e3-481c139915e8.png)

使用antd/charts试试   https://github.com/ant-design/ant-design-charts

**Comment by supnate** [comment]
遇到了同样的错误，然后发现是自己 code 的问题，见中文注释部分：
```
// Init chart when component mount
  const initChart = useCallback(node => {
    if (!node) return; // 这里需要判断 node 是否存在，因为在组件 unmount 时，ref callback 也会被执行
    chartRef.current = new Area(node, {
      data: [],
      xField: 'year',
      yField: 'value',
    });
    chartRef.current.render();
  }, []);

...
<div ref={initChart} />
```

**Comment by hustcc** [comment]
@supnate 有没有兴趣提一个 PR，在 G2Plot 代码中处理掉这个。

**Comment by supnate** [comment]
不需要处理，是使用代码的问题。@hustcc

**Comment by withwz** [comment]
我也遇到了，在componentDidMounted中和useEffect中使用可以，是要等组建挂载完成渲染才可以
